### ISSUE TITLE
Use S3 bucket's name as part of an object's name

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#10]
At the moment, we just use the object name in its URN (and auto-propagate that to the key).  Unfortunately, this means if you have two objects in the same module, with the same names but different buckets, they will get assigned the same URN.  Ideally there would be a way to use a different property than `id` when referencing another resource object, in which case object could reference bucket's `name` property and then it would, in theory, not be computed (necessarily).

**Comment by joeduffy** [comment]
@jen20 if this is obviously a bad idea, let's close out. Otherwise, just assigning to you for future consideration.

**Comment by lukehoban** [comment]
I'm not exactly clear what the specific issue was here - but regardless we've lived in this state for 2+ years without new reports of this - so closing out for now.
