### ISSUE TITLE
aws:sqs FIFO queue 'name' option is mandatory, update the doc

### ISSUE THREAD

**Issue by tigran-gruv** [pulumi/pulumi-aws#1000]
Hi there. I think this is basically concerning the Documentation.

My short story how I got there is this:
AWS SQS requires queue name to have '.fifo' suffix for FIFO queue. 

I have set the option `fifoQueue: true` .

When I name my queue 'messages-dev.fifo' I got this error:
```
aws:sqs:Queue (messages-dev.fifo):
    error: aws:sqs/queue:Queue resource 'messages-dev.fifo' has a problem: only alphanumeric characters and hyphens allowed in "name"
```

So I remove '.fifo' suffix and again error
```
aws:sqs:Queue (messages-dev):
    error: Error validating the FIFO queue name: [FIFO queue name should end with ".fifo": messages-dev-eb6b723]
```

Here is my code of queue creation
```javascript
  const queue = new aws.sqs.Queue(`messages-${config.ENV_STAGE}.fifo`, {
    fifoQueue: true,
    visibilityTimeoutSeconds: 1,
    messageRetentionSeconds: 345600, // 4 days
    maxMessageSize: 262144, // 256 KiB
    contentBasedDeduplication: true,
    delaySeconds: 0,
  });
```

Then in the issue #447 I saw the `name` property given in options. I tried and it worked.
Just added `name: 'messages-dev.fifo'` in options

My suggestion is to update [this doc](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/sqs/).

Related to the issue #967

**Comment by abrahampcmb** [comment]
Based on the testing I'm doing with the latest version (3.32.1) this appears to be an issue still. However, the [related issue](https://github.com/pulumi/pulumi-aws/issues/967) was closed and a [PR](https://github.com/pulumi/pulumi-aws/pull/1257) was done to fix this. This issue seems to be present even when running what is [documented](https://www.pulumi.com/docs/reference/pkg/aws/sqs/queue/) in the example of how to create an SQS FIFO queue.

**Comment by stack72** [comment]
Hi @abrahampcmb 

We shipped a patch release for this yesterday that fixes a regression of autonaming of fifo queues - so this piece of code will now work as expected:

```
const queue = new aws.sqs.Queue(`messages-${config.ENV_STAGE}`, {
    fifoQueue: true,
    visibilityTimeoutSeconds: 1,
    messageRetentionSeconds: 345600, // 4 days
    maxMessageSize: 262144, // 256 KiB
    contentBasedDeduplication: true,
    delaySeconds: 0,
  });
```

Notice I didn't have to add ".fifo" anywhere in the name - Pulumi will detect it is required and ensure it is added

Please let us know if this continues to be a problem

Paul
