### ISSUE TITLE
lambda vs. lambda_ Python modules

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-aws#1020]
It seems that there is now a `lambda_` module in the Python SDK. Moreover, the previous `lambda` module hasn't been receiving updates since May; likely due to codegen changes.

**Comment by komalali** [comment]
Okay! So this is actually working as expected, lambda_ is the correct module name since `lambda` is a keyword. It looks like there was a regression a few months ago that was then corrected, but the lambda folder was a leftover build artifact.
