### ISSUE TITLE
aws.apigateway.BasePathMapping changing basePath causes replace rather than update.

### ISSUE THREAD

**Issue by shellicar** [pulumi/pulumi-aws#1026]
## Version
Windows - v2.5.0
@pulumi/pulumi 2.5.0
@pulumi/aws 2.11.0

## Description
When changing the basePath for a BasePathMapping, the resulting change is a 'replace' when I would expect 'update'.
When the previous basePath was empty, this results in the following error: `Error creating Gateway base path mapping: ConflictException: Only one base path mapping is allowed if the base path is empty.`
The basePath can be updated with the following method: https://docs.aws.amazon.com/apigateway/api-reference/link-relation/basepathmapping-update/
The CLI command: https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-base-path-mapping.html

## Error
error: `Error creating Gateway base path mapping: ConflictException: Only one base path mapping is allowed if the base path is empty.`

**Comment by leezen** [comment]
While 'update' would be more desirable, the current 'replace' behavior is not a bug as it's what's specified in the schema. I'll leave this open to track the desire to change that behavior. You may also want to open an issue in the terraform provider https://github.com/terraform-providers/terraform-provider-aws/issues

**Comment by vubogovich** [comment]
Curious why this issue is still open. Getting `update` on change of `BasePathMapping.basePath` now.

**Comment by leezen** [comment]
Thanks for re-pinging this issue -- it was indeed addressed upstream in https://github.com/hashicorp/terraform-provider-aws/pull/16147
