### ISSUE TITLE
add PolicyDocument type to QueuePolicyArgs

### ISSUE THREAD

**Issue by koneru9999** [pulumi/pulumi-aws#1032]
Provide an option to use `PolicyDocument` instead of only json string to `aws.sqs.QueuePolicy`. This also greatly improves the type safety.

https://github.com/pulumi/pulumi-aws/blob/22a1d0fd9cc882a38d25306162be97e48c8dc4e7/sdk/nodejs/sqs/queuePolicy.ts#L136

above can be changed to
```typescript
readonly policy: pulumi.Input<string | PolicyDocument>;
```

This is also inline with the other IAM policies or s3 bucket policy and etc...

I would be willing to provide a PR for this small change if required.

**Comment by leezen** [comment]
A PR would be great! Note that you'll want to do it via the schema mapping in https://github.com/pulumi/pulumi-aws/blob/master/provider/resources.go and not editing `queuePolicy.ts` directly.

**Comment by koneru9999** [comment]
Thanks for the heads up.

**Comment by stack72** [comment]
closed via #1033
