### ISSUE TITLE
Changing subnets of SubnetGroup fails if DB Instance is a dependent

### ISSUE THREAD

**Issue by jclangst** [pulumi/pulumi-aws#1040]
`@pulumi/aws`: v2.12

In the below configuration, changing the subnet ids in the `SubnetGroup` fails because the `Instance` is using the subnets. In this failure scenario, it would be ideal if the `SubnetGroup` were replaced rather than updated.

Example configuration:

```Typescript
  const subnetGroup = new aws.rds.SubnetGroup(
    'auth-service-rds',
    {
      subnetIds: config.requireObject('postgresSubnetIds'),
    },
    { provider: awsProvider },
  );

  const db = new aws.rds.Instance(
    'auth-service-rds',
    {
      name: config.require('postgresInitialDBName'),
      engine: 'postgres',
      engineVersion: config.require('postgresVersion'),
      applyImmediately: true,
      autoMinorVersionUpgrade: true,
      deletionProtection: config.requireBoolean('postgresDeletionProtection'),
      finalSnapshotIdentifier: finalSnapshotName.hex,
      instanceClass: config.require('postgresInstanceClass'),
      allocatedStorage: config.requireNumber('postgresAllocatedStorage'),
      maxAllocatedStorage: config.requireNumber('postgresMaxAllocatedStorage'),
      iops: config.getNumber('postgresIOPS'),
      storageEncrypted: true,
      multiAz: config.requireBoolean('postgresMultiAZ'),
      backupRetentionPeriod: config.requireNumber('postgresBackupRetentionPeriod'),
      performanceInsightsEnabled: config.require('postgresVersion').startsWith('1'),
      enabledCloudwatchLogsExports: ['postgresql', 'upgrade'],
      monitoringInterval: 15,
      monitoringRoleArn: postgresMonitoringRole.arn,
      password: dbPassword.result,
      username: 'authservice',
      port: config.requireNumber('postgresPort'),
      dbSubnetGroupName: subnetGroup.name,
      vpcSecurityGroupIds: [securityGroup.id],
      caCertIdentifier: config.require('postgresCert'),
    },
    { provider: awsProvider },
  );
```

**Comment by leezen** [comment]
As a workaround, you can specify `--target-replace <subnetGroup urn>` to force replacement of that resource.

**Comment by jclangst** [comment]
@leezen That's a good callout!

**Comment by lukehoban** [comment]
> In this failure scenario, it would be ideal if the SubnetGroup were replaced rather than updated.

Core Pulumi doesn't currently have any way to express this sort of thing - so there's nothing the AWS provider could do currently to make that happen.

I believe you can use `replaceOnChanges: ['subnetIds']` on the SubnetGroup to cause the SubnetGroup to be recreated if there are changes, which will create a new one, update all dependencies to use it, then delete the old one.  This should result in the right transition (and ideally with no downtime for your database!).
