### ISSUE TITLE
Eventual consistency problem with ECS cluster and ECS service-linked role?

### ISSUE THREAD

**Issue by hexmoose** [pulumi/pulumi-aws#1041]
When creating the first Fargate ECS cluster in an account without an existing ECS service-linked role, the initial update fails with the message:

```
Diagnostics:
  aws:ecs:Cluster (cluster):
    error: InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
```

It succeeds when run again a few minutes later. This appears to be related to https://github.com/terraform-providers/terraform-provider-aws/issues/11417. Is something going on at the pulumi level or is this a regression in the terraform provider?

I'm running pulumi v2.6.1 with pulumi-aws v2.12.0.

Thanks for looking into this!

**Comment by leezen** [comment]
There's nothing happening at the pulumi level for this, so it could be a potential regression upstream. Any chance you could please provide detailed logs? https://www.pulumi.com/docs/troubleshooting/#verbose-logging

**Comment by hexmoose** [comment]
I ran a test from a sample project using the official pulumi docker container (https://hub.docker.com/r/pulumi/pulumi). The contents of the run are just:

```typescript
import * as aws from "@pulumi/aws";

export const cluster = new aws.ecs.Cluster("cluster", {
  capacityProviders: ["FARGATE"],
  defaultCapacityProviderStrategies: [
    {
      capacityProvider: "FARGATE",
    },
  ],
});
```

To reproduce, delete the `arn:aws:iam::012345678910:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS` role in your account and run `pulumi up` with the above code.

Detailed logs:
- [run1_out.txt](https://github.com/pulumi/pulumi-aws/files/4914284/run1_out.txt): Console output from the first (unsuccessful) attempt.
- [run1_log.txt](https://github.com/pulumi/pulumi-aws/files/4914286/run1_log.txt): Verbose logs from the first attempt.
- [run2_out.txt](https://github.com/pulumi/pulumi-aws/files/4914289/run2_out.txt): Console output from the second (successful) attempt. The role that is needed is created in the first run even though the cluster creation fails.
- [run2_log.txt](https://github.com/pulumi/pulumi-aws/files/4914290/run2_log.txt): Verbose logs from the second attempt.

Thanks for investigating.

**Comment by leezen** [comment]
Closing stale issue as the provider has changed substantially since this issue was filed
