### ISSUE TITLE
Destroying stack containing Lambda@Edge fails

### ISSUE THREAD

**Issue by allroundexperts** [pulumi/pulumi-aws#1045]
Deleting Lambda@Edge functions manually is not possible as of now in AWS. The Lambda@Edge function gets deleted automatically 1 hour after the associated Cloudfront distribution gets removed. As such, `Pulumi destroy` keeps on failing during that time. Ideally, Pulumi should skip the deletion of Lambda@Edge functions.

<img width="1132" alt="Screenshot 2020-07-18 at 10 27 18 PM" src="https://user-images.githubusercontent.com/30054992/87858232-d9aad780-c945-11ea-88a8-a729554bbfad.png">

**Comment by leezen** [comment]
As a workaround, you can `pulumi state delete` the function in question (which will leave it behind) if this is preventing you from destroying the rest of your stack. Then, delete the function after the replicas no longer exist.

**Comment by m4dc4p** [comment]
@leezen AWS will delete the function automatically (replicas included). So really if the SDK tracked these functions differently (and didn't attempt to delete at all) it wouldn't be a problem. 

@allroundexperts did you find a workaround?

**Comment by allroundexperts** [comment]
> https://forums.aws.amazon.com/thread.jspa?threadID=331402

So the only workaround that I found was using `pulumi state delete` the function in question. I think it would be more easier for Pulumi to treat replicas differently instead of Amazon directly.

**Comment by allroundexperts** [comment]
> @leezen AWS will delete the function automatically (replicas included). So really if the SDK tracked these functions differently (and didn't attempt to delete at all) it wouldn't be a problem.
> 
> @allroundexperts did you find a workaround?
> 
> I think a simple solution Amazon could provide is to not return a 400 in this case, but just treat the call as a success (the fucntion will get deleted eventually by CloudFront anyways). If you want to show support, check out my thread on their forums https://forums.aws.amazon.com/thread.jspa?threadID=331402

So the only workaround that I found was using pulumi state delete the function in question. I think it would be more easier for Pulumi to treat replicas differently instead of Amazon directly.

**Comment by lukehoban** [comment]
This is being tracked upstream in https://github.com/hashicorp/terraform-provider-aws/issues/1721.

**Comment by mattiloh** [comment]
It looks like this has been fixed upstream two weeks ago with https://github.com/hashicorp/terraform-provider-aws/pull/29646. 🎉 
Any ETA when this might be integrated in Pulumi? We're blocked by this issue in an e2e test-setup that creates a new stack for each build (destroying the resources manually is not a feasible option in this case).

**Comment by mattiloh** [comment]
Just tested it with the latest @pulumi/aws (v5.31.0), which seems to integrate the relevant terraform-provider-aws version (https://github.com/pulumi/pulumi-aws/releases/tag/v5.31.0). This time it tried for 10 minutes to delete two Lambda@Edge functions. Unfortunately, this might still not be enough:

```
aws:lambda:Function (lambda-edge-redirect-404-to-resizer):
    error: deleting urn:pulumi:test-add-e2e-tests::file-processing-service::aws:lambda/function:Function::lambda-edge-redirect-404-to-resizer: 1 error occurred:
    	* deleting Lambda Function (lambda-edge-redirect-404-to-resizer-4ac83c9): operation error Lambda: DeleteFunction, https response error StatusCode: 400, RequestID: ea99fb70-6272-4b53-bad6-ba50f035cbf2, InvalidParameterValueException: Lambda was unable to delete arn:aws:lambda:us-east-1:xxx:function:lambda-edge-redirect-404-to-resizer-4ac83c9:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.
```

**Comment by H0R5E** [comment]
I'm having similar issues with a single lambda@edge function. On first try to delete it times out. If I wait a while and try again, it deletes nearly instantaneously.

**Comment by gpcherchi** [comment]
I am having the same issue and we are using @pulumi/aws (v5.40.0).

As it is fixed upstream, can we expect to get it fixed too?

**Comment by corymhall** [comment]
This is a limitation of the way Lambda@Edge works in AWS. When a Lambda@Edge function is deployed it is replicated to all of the edge locations. When it is then deleted, it has to be deleted from all of the edge locations which can take an indeterminate amount of time.

The upstream fix is as good as can be done for this issue. You can try setting a very long deletion timeout, but even then it is not guaranteed.

```ts
  new aws.lambda.Function('handler', {
    role: role.arn,
    code,
    handler: 'index.handler',
    runtime: 'nodejs20.x',
  }, {
    customTimeouts: {
      delete: '30m',
    }
  });

```
