### ISSUE TITLE
Unable to get AWS account ID

### ISSUE THREAD

**Issue by matke2002** [pulumi/pulumi-aws#1047]
Hi,
just started to examine pulumi with python

I am trying to get AWS account ID  
https://www.pulumi.com/docs/reference/pkg/aws/iam/getaccountalias/  

my code is:  
```python
current = aws.iam.get_account_alias()   
pulumi.export("accountAlias", current.account_alias)   
pulumi.export("accountId", current.id)   
```

outputs are:
```
accountAlias:  MyAlias   <------ this is ok, but I don't need ithis
accountId: 2020-07-21 14:16:43.0216479 +0000 UTC   <--------- error, date instead ID in format 1234567890
```

**Comment by leezen** [comment]
Interestingly, it seems like the AWS API itself doesn't return any IDs for this operation. So likely, the ID being picked up is just the timestamp of the event. If you're trying to get the account ID of the caller, you can use `get_caller_identity` instead: https://www.pulumi.com/docs/reference/pkg/aws/getcalleridentity/

```
import pulumi
import pulumi_aws as aws

current = aws.get_caller_identity()
pulumi.export("accountId", current.account_id)
pulumi.export("callerArn", current.arn)
pulumi.export("callerUser", current.user_id)
```
