### ISSUE TITLE
OpenIdConnectProvider Thumbprint is case sensitive

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-aws#1049]
When I use `Pulumi.Aws.IamOpenIdConnectProvider.ThumbprintLists`, if I put in a thumbprint that's all upper case, AWS stores it as lower case. When I then run Pulumi again, it considers it different and wants to keep updating it.

Since in this scenario, case doesn't matter, the OpenIdConnectProvider should be case insensitive.

**Comment by stack72** [comment]
Hi @NArnott 

Sorry we have not responded to this issue in a long time - we are trying to get better with that. Unfortunately, we have no real control here about how things get returned from AWS. There are a lot of resources where case sensitivity is important and we can't easily add DiffSuppression generally. To be fully deterministic here, I would suggest using a strings.ToLower style func locally to format the ThumbprintList details before passing to the resource

Paul
