### ISSUE TITLE
Feature Request | AWS ListenerRule Conditions Support Array of Items

### ISSUE THREAD

**Issue by jkrusic19** [pulumi/pulumi-aws#1053]
Hello,

I would like to open a feature request so that a ListenerRule Conditions, such as PathPattern rule support an array of conditions instead of a single item/Value.

Issue:
- I would like to be able to supply an List<string> to Conditions for PathPattern in a single Rule. Instead of having to create multiple ListenerRules.

Example:
```
public static void AlbListenerPathRule(string environment, Pulumi.Input<string> ListenerArn, string Patterns, string service, Pulumi.Input<string> TgArn, string application = "app01")
        {
            var ecsListenerRule = new ALB.ListenerRule($"{environment}-{application}-{service}-listener-rule", new ALB.ListenerRuleArgs
            {
                ListenerArn = ListenerArn,
                Actions =
                {
                    new ALB.Inputs.ListenerRuleActionArgs
                    {
                        TargetGroupArn = TgArn,
                        Type = "forward"
                    }
                },
                Conditions =
                {
                    new ALB.Inputs.ListenerRuleConditionArgs
                    {
                        PathPattern = new ALB.Inputs.ListenerRuleConditionPathPatternArgs
                        {
                            Values =
                            {
                                "/test/*", "/stage/*" //Would like it supported as such
                            }
                        }
                    }
                }
            });
        }
```

Currently Values only supports a MaxItem => 1. The work around is to create multiple ListenerRules thus creating an exorbitant amount of rules. Granted the limit is 100 rules outside of the default. Per AWS Limits per rule you can have 5 values.

**Comment by stack72** [comment]
Conditions is now:

`conditions?: pulumi.Input<pulumi.Input<inputs.alb.ListenerRuleCondition>[]>;`

Apologies we didn't close this issue out earlier

Paul
