### ISSUE TITLE
Public access block on access logs bucket is applied to main bucket, without being explicitly configured

### ISSUE THREAD

**Issue by amichel** [pulumi/pulumi-aws#1058]
When setting public access block on access logs bucket that is used in loggings definitions,
related public content bucket inherits this block, without one being configured for it.

This effectively blocks access to my buckets that must be public every time I run pulumi up -r

**Comment by leezen** [comment]
I'm not quite sure I understand what you mean here. Do you mind providing a repro?

**Comment by amichel** [comment]
Sharing gist with example:
[](https://gist.github.com/amichel/a7183c136ad7c4dd1d42e49d8aaf39d2)

**Comment by leezen** [comment]
I'm not sure I follow. S3 buckets aren't public by default, so you'll have to configure a bucket to be publicly readable. It's not that it's 'inheriting' the public access block in some way.

**Comment by stack72** [comment]
Going to close this out as we have not had any other reports of this issue

Paul
