### ISSUE TITLE
Provide a way to get the deployment account id in code

### ISSUE THREAD

**Issue by jamesholmes-linktree** [pulumi/pulumi-aws#1059]
As per getRegion and other Pulumi parallels of the CF PseudoParams, it would be great to be able to get the current account ID.

**Comment by leezen** [comment]
I think you're looking for `GetCallerIdentity`: https://www.pulumi.com/docs/reference/pkg/aws/getcalleridentity/
Please re-open if that's not the case.

**Comment by jamesholmes-linktree** [comment]
Not if I'm doing a cross-account deployment and I've given a role in my deployer account access to make changes in my resource account.
