### ISSUE TITLE
Disable autonaming on directoryservice.Directory

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-aws#1061]
See this AWS directory example: https://www.pulumi.com/docs/reference/pkg/aws/workspaces/directory/

If you specify a `name` with a `-`, you get the following error:

```py
main_directory = aws.directoryservice.Directory("mainDirectory",
                                                password="#S1ncerely",
                                                size="Small",
                                                name='main-dir',
                                                vpc_settings={
                                                    "subnet_ids": [
                                                        private_a.id,
                                                        private_b.id,
                                                    ],
                                                    "vpc_id": main_vpc.id,
                                                })

```

```
Diagnostics:
  aws:directoryservice:Directory (main):
    error: InvalidParameterException: Invalid directory name. The directory name must be between 2 and 64 characters, and can only contain alphanumeric characters, periods (.). or minus signs (-). Also, the directory name must begin and end with an alphanumeric character. : RequestId: 362da74b-62dc-4116-8785-e65cbacb52c3
    {
      RespMetadata: {
        StatusCode: 400,
        RequestID: "362da74b-62dc-4116-8785-e65cbacb52c3"
      },
      Message_: "Invalid directory name. The directory name must be between 2 and 64 characters, and can only contain alphanumeric characters, periods (.). or minus signs (-). Also, the directory name must begin and end with an alphanumeric character. : RequestId: 362da74b-62dc-4116-8785-e65cbacb52c3",
      RequestId: "362da74b-62dc-4116-8785-e65cbacb52c3"
    }
  pulumi:pulumi:Stack (training_workspaces-dev):
    error: update failed
```

I'm not 100% sure where the above error comes from, TF or AWS? Anyways the error message is incorrect. If you try to remove the `-` from the name, you get a validation error against a regex that shows that either the `-` or the `.` is required in the middle:

```py
main_directory = aws.directoryservice.Directory("mainDirectory",
                                                password="#S1ncerely",
                                                size="Small",
                                                name='maindir',
                                                vpc_settings={
                                                    "subnet_ids": [
                                                        private_a.id,
                                                        private_b.id,
                                                    ],
                                                    "vpc_id": main_vpc.id,
                                                })

```

```
    error: ValidationException: 1 validation error detected: Value 'maindir' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([a-zA-Z0-9]+[\\.-])+([a-zA-Z0-9])+$
    	status code: 400, request id: 5076cbcb-233a-457f-97cd-e2826dd2af8f
```

This regex is consistent with the docs for the `name` property, and indicates that there must be at least one `-` or `.` in the sandwiched between alphanumeric sections. This contradicts the first error message that indicates the `.` and `-` as being optional.

To get this to work you need to specify a `name` with a `.` in the middle:

```py
main_directory = aws.directoryservice.Directory("mainDirectory",
                                                password="#S1ncerely",
                                                size="Small",
                                                name='main.dir',
                                                vpc_settings={
                                                    "subnet_ids": [
                                                        private_a.id,
                                                        private_b.id,
                                                    ],
                                                    "vpc_id": main_vpc.id,
                                                })
```

Feels like this is a combination of TF and/or AWS bugs. Given the inconsistency between the regex, the validation message, and the observed working behavior.

**Comment by stack72** [comment]
This isn't coming from the upstream Terraform provider - this is actually the response returned from AWS. I am trying to dig into their naming validation rules for this specific issue

Paul

**Comment by stack72** [comment]
So, there are no naming rules around this field either in Pulumi nor Terraform. This is an AWS side issue - although it is important to note that the name parameter does specify this in the documentation:

```
The fully qualified name for the directory, such as corp.example.com
```

https://www.pulumi.com/docs/reference/pkg/aws/directoryservice/directory/#name_nodejs

I think we can close this out @EvanBoyle - thoughts?

**Comment by EvanBoyle** [comment]
`fully qualified name` is ambiguous, so I don't think the docs are super helpful here. 

I don't think we should close this out as we're still responsible for our users' experience. Some potential action items:

1. FIle a bug on the AWS SDK, or appropriate repo. 
2. Fix our examples.
3. Add our own validation and return a sane error message

Now priority of doing this work is a different conversation, but let's not close the issue until there's a fix.

**Comment by DVAlexHiggs** [comment]
Thanks for discussing this issue. 
For the record, the reason this error occurred is because when by default, Pulumi postfix hex using a `-`, it will also occur without providing a `name` parameter. I was using `name` to get around this error, not realising that the `-` was the culprit. Either the hex postfix default needs to change to not use `-` or the error message needs to be made more clear.

**Comment by stack72** [comment]
So it looks like we need to disable autonaming for the DirectoryService
