### ISSUE TITLE
Add AWSXRayDaemonWriteAccess to ManagedPolicies

### ISSUE THREAD

**Issue by michael-golden** [pulumi/pulumi-aws#1062]
Can we get the AWSXRayDaemonWriteAccess ARN added to the ManagedPolicies module?

Name: AWSXRayDaemonWriteAccess
ARN: arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess

@stack72

**Comment by lukehoban** [comment]
Definitely feel free to submit a PR here. This file is manually maintained currently - so just adding the policy to the list should be fine (and including primary reference in AWS docs for where this is defined in the commit message). 

https://github.com/pulumi/pulumi-aws/blob/65c47e93776a7d710194e4a13aca207913418328/sdk/nodejs/iam/managedPolicies.ts
