### ISSUE TITLE
Systematic diff in Elastic Beanstalk settings

### ISSUE THREAD

**Issue by odusseys** [pulumi/pulumi-aws#1073]
Running `pulumi up` with the same Elastic Beanstalk Environment settings twice will (almost) invariably lead to a diff being show when there is none.

## Expected Behavior
There should be no diff and the Environment should not be updated.

## Current Behavior
- The order of settings is randomly queried by pulumi and generates a diff if it is different from what pulumi finds in the declaration.
 - the `resource` field of each setting, if left undefined in the declaration, is compared to an empty string when queried by pulumi.

![image](https://user-images.githubusercontent.com/7863870/90135663-4d88a600-dd73-11ea-96ae-957c24bfe328.png)

## Steps to Reproduce
1. Declare an `aws.elasticbeanstalk.Environment` with several settings (eg. a few environment variables)
2. Run `pulumi up` twice

**Comment by ffMathy** [comment]
This happens to me too. There is a previous issue #878 that was closed prematurely regarding this problem.

**Comment by lukehoban** [comment]
There isn't a repro here to validate against, but I am fairly confident this is ultimately one of the three issues noted in https://github.com/pulumi/pulumi-aws/issues/920#issuecomment-623580979, so closing as a duplicate of those.
