### ISSUE TITLE
Unable to use updateDefaultVersion LaunchTemplate resource property

### ISSUE THREAD

**Issue by disk-edit** [pulumi/pulumi-aws#1077]
This property is listed here [updateDefaultVersion property](https://www.pulumi.com/docs/reference/pkg/aws/ec2/launchtemplate/#updatedefaultversion_nodejs). I can't use it in my code specifically in LaunchTemplateArgs where I would expect to use it.

In [Slack](https://pulumi-community.slack.com/archives/CRH5ENVDX/p1597442407093600?thread_ts=1597441158.093500&cid=CRH5ENVDX) @jaxxstorm confirmed this with "I can repro it and it seems to be missing from the schema..."

**Comment by jaxxstorm** [comment]
I used an existing stack to try and test this which had an older version of the `pulumi-aws` provider. To fix it:

- update `package.json` to latest version of pulumi-aws (`3.1.0`)
- run `pulumi up` to update the checkpoint
- you should now have this property.

@disk-edit what is in your `package.json` ?

**Comment by disk-edit** [comment]
I also had to manually clear the node_modules folder (thanks for the suggestion @jaxxstorm). That resolved the issue.
