### ISSUE TITLE
Support appsync direct lambda

### ISSUE THREAD

**Issue by michael-golfi** [pulumi/pulumi-aws#1081]
Hi!

AppSync just released a feature for connecting Appsync directly to Lambda. Although I'm not well-versed in the deployment code, it looks like it would be enabled by not providing a `requestTemplate` and `responseTemplate` parameter for a Lambda datasource, from the link:

```bash
aws appsync create-resolver –-api-id myapiexample12345678 --typeName Query --fieldName getOrder –-data-source-name LambdaDS
```

[Link](https://aws.amazon.com/blogs/mobile/appsync-direct-lambda/)

**Comment by leezen** [comment]
Tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/14488

**Comment by aterreno** [comment]
Adapting this https://github.com/hashicorp/terraform-provider-aws/issues/14488#issuecomment-678101695 to a pulumi project seems to work well. 

HTH

**Comment by emiliza** [comment]
Please update to pulumi-aws v4.2.0+, as this has the fix from the upstream provider. Thanks!
