### ISSUE TITLE
Support for Amazon EventBridge 

### ISSUE THREAD

**Issue by ronoc** [pulumi/pulumi-aws#1089]
I can't see any support to manage eventbridge. Am I missing something ?
https://aws.amazon.com/eventbridge/

**Comment by leezen** [comment]
This isn't implemented yet either directly in the pulumi provider or upstream (tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/9330)

**Comment by ronoc** [comment]
:+1:

**Comment by lukehoban** [comment]
This is available now in https://www.pulumi.com/docs/reference/pkg/aws/cloudwatch/eventbus/ and related APIs.
