### ISSUE TITLE
Provider configuration mismatch when upgrading to pulumi-aws 3.2.0

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aws#1093]
When upgrading from pulumi-aws 2.13.1 to pulumi-aws 3.2.0, using Python, I get the following weird behaviour:

```
├─ pulumi:providers:aws           prod                         update      [diff: +assumeRole-assume_role]
```

This makes it practically impossible to upgrade, since now Pulumi wants to replace all my resources.

Relevant piece of source code:

```
aws.Provider(account_name,
    assume_role={"role_arn": assume_role},
    region=region)
```

Going back to pulumi-aws 2.13.1 works. I'm using Pulumi 2.9.0.

**Comment by stack72** [comment]
Hi @Sodki 

Looking into this immediately

Paul

**Comment by stack72** [comment]
Hi @Sodki 

So I am trying to reproduce this right now and I am not able to when upgrading from 2.13.1 to 3.2.0

```
~/code/aws-assume-role
▶ pulumi up
Previewing update (dev):
     Type                 Name                 Plan
     pulumi:pulumi:Stack  aws-assume-role-dev

Resources:
    3 unchanged
```

Any chance you could send me the diff that gets output in the details view of the `pulumi up` prompt? If you can't share it publicly then you can do so to my email stack72@pulumi.com

**Comment by Sodki** [comment]
These are the steps I did to get the error again:

1. Make sure that `pulumi preview` doesn't show any changes;
2. Change the requirements.txt file:
```
-pulumi-aws>=2.0.0,<3.0.0
+pulumi-aws>=3.0.0,<4.0.0
```
3. Run `venv/bin/pip install -r requirements.txt --upgrade` to make sure everything is up to date;
4. Confirm that I'm using Pulumi 2.9.0 both on the virtualenv and on the CLI binaries;
5. At this stage, running `pulumi up` shows the difference on the providers:
```
Previewing update (<redacted>):
     Type                     Name       Plan       Info
     pulumi:pulumi:Stack      <redacted>
 ~   ├─ pulumi:providers:aws  <redacted>        update     [diff: +assumeRole-assume_role]


Resources:
    ~ 1 to update
    <redacted> unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:<redacted>::<redacted>::pulumi:pulumi:Stack::<redacted>]
    ~ pulumi:providers:aws: (update)
        [id=2ea8042d-ee32-41da-b3e8-3673876ae22a]
        [urn=urn:pulumi:<redacted>::<redacted>::pulumi:providers:aws::<redacted>]
      + assumeRole : "{\"role_arn\": \"arn:aws:iam::<redacted>:role/<redacted>\"}"
      - assume_role: "{\"role_arn\": \"arn:aws:iam::<redacted>:role/<redacted>\"}"
```
6. Then I've noticed something, the latest plugin wasn't installed:
```
$ pulumi plugin ls | grep ^aws
aws         resource  2.13.1   228 MB  n/a        10 hours ago
aws         resource  2.13.0   228 MB  n/a        10 hours ago
aws         resource  2.12.0   228 MB  n/a        10 hours ago
```
7. I've installed the correct one:
```
$ pulumi plugin install resource aws 3.2.0
[resource plugin aws-3.2.0] installing
Downloading plugin: 68.86 MiB / 68.86 MiB [========================] 100.00% 25s
Moving plugin... done.
```
8. `pulumi up` result is now very different, it wants to replace _every_ resource that uses that provider and doesn't even stop the planning, just keeps running until I do Ctrl+C.

Please let me know if there is any other debugging that I can help with.

**Comment by marioapardo** [comment]
The same thing happens to me in point 8 to deploying a new resource or updating some resources.

**Comment by marioapardo** [comment]
update pulumi_aws plugin to v3.2.1 and solved point 8, no problem in version change v2.13.1 to v3.2.1.

**Comment by Sodki** [comment]
Interesting, I still get the same bad behaviour with 3.2.1.

**Comment by stack72** [comment]
Hi @Sodki 

Can you run `pulumi refresh` and see if it tells you it needs to make any changes to the provider? Don't actually accept the changes - just grab the details view

P.

**Comment by Sodki** [comment]
No, there are no changes to the provider when doing `pulumi refresh`.

**Comment by marioapardo** [comment]
Perform the process of a deployment of an EKS cluster again with all its resources, also including the installation of resources within Kubernetes, in total 320 resources to deploy. I did it with the version of pulumi 2.9.2 and AWS versions 2.13.1 and 3.2.1 without any problem .. also upgrade the AWS provider from version 2 to 3 and make a change in the deploy and it worked without problems.

**Comment by Sodki** [comment]
@marioapardo This seems to be a problem only when using custom provider configuration with an assumed role. If this is your case, would you mind sharing the relevant part of your state with me (using `pulumi stack export`)? I'm not interested in values, just the structure.

For example, in my case, this is what I have:

```
{
  "urn": <redacted>,
  "custom": true,
  "id": <redacted>,
  "type": "pulumi:providers:aws",
  "inputs": {
    "assume_role": <redacted>,
    "region": <redacted>
  },
  "outputs": {
    "assume_role": <redacted>,
    "region": <redacted>
  },
  "parent": <redacted>,
  "propertyDependencies": {
    "assume_role": null,
    "region": null
  }
}
```

**Comment by marioapardo** [comment]
@Sodki  Various custom providers including AWS are also used and roles are assumed

**Comment by marioapardo** [comment]
Sorry not being able to place the text, I no longer have the output of the console but I can make these screenshots.

![image](https://user-images.githubusercontent.com/379136/91917148-bf725200-ec84-11ea-83bc-53bea9bf81be.png)
![image](https://user-images.githubusercontent.com/379136/91917328-33acf580-ec85-11ea-889d-2f62d3e3bce5.png)
![image](https://user-images.githubusercontent.com/379136/91917334-37d91300-ec85-11ea-84e2-43a4ab84bb1d.png)

**Comment by marioapardo** [comment]
@Sodki  This is the output of the export, it is important to create an AWS API call to validate that the credentials in the profile are valid and generate an authentication message if it fails.

{
    "urn": "<redacted>",
    "custom": true,
    "id": "<redacted>",
    "type": "pulumi:providers:aws",
    "inputs": {
        "assume_role": "<redacted>",
        "profile": "<redacted>",
        "region": "<redacted>"
    },
    "outputs": {
        "assume_role": "<redacted>",
        "profile": "<redacted>",
        "region": "<redacted>"
    },
    "parent": "<redacted>",
    "propertyDependencies": {
        "assume_role": null,
        "profile": null,
        "region": null
    }
}

**Comment by Sodki** [comment]
@marioapardo Thank you very much! So you also have the same problem that I have, the provider changing from "assume_role" to "assumeRole". It's good to know that I'm not alone at least.

**Comment by Sodki** [comment]
@stack72 I was able to reproduce this with a simple test case:
 
**1.** Started a new project with `pulumi new python`
**2.** Used the following code:
```
$ cat requirements.txt
pulumi>=2.0.0,<3.0.0
pulumi-aws>=2.0.0,<3.0.0

$ cat __main__.py
import pulumi_aws
pulumi_aws.Provider("provider",
                    assume_role={"role_arn": "arn:aws:iam::<redacted>:role/<redacted>"})
```
**3.** Ran `pulumi up` and accepted changes:
```
$ pulumi up
Previewing update (dev):
     Type                     Name         Plan       
 +   pulumi:pulumi:Stack      project-dev  create     
 +   └─ pulumi:providers:aws  provider     create     
 
Resources:
    + 2 to create

Permalink: file:///tmp/project/.pulumi/stacks/dev.json
Do you want to perform this update? yes
Updating (dev):
     Type                     Name         Status      
 +   pulumi:pulumi:Stack      project-dev  created     
 +   └─ pulumi:providers:aws  provider     created     
 
Resources:
    + 2 created

Duration: 1s

Permalink: file:///tmp/project/.pulumi/stacks/dev.json
```
**4.** Updated requirements file:
```
$ cat requirements.txt
pulumi>=2.0.0,<3.0.0
pulumi-aws>=3.0.0,<4.0.0
```
**5.** Upgraded Python packages with `venv/bin/pip3 install -r requirements.txt`
**6.** Ran `pulumi up` and saw the mismatch:
```
reviewing update (dev):
     Type                     Name         Plan       Info
     pulumi:pulumi:Stack      project-dev             
 ~   └─ pulumi:providers:aws  provider     update     [diff: +assumeRole-assume_role]
 
Resources:
    ~ 1 to update
    1 unchanged
```
**7.** I've accepted the errors and confirmed that the state was changed:
```
$ diff old_state new_state
5c5
<             "time": "2020-09-02T15:12:00.86856505+01:00",
---
>             "time": "2020-09-02T15:25:50.009804876+01:00",
27c27
<                     "assume_role": "{\"role_arn\": \"arn:aws:iam::<redacted>:role/<redacted>\"}",
---
>                     "assumeRole": "{\"role_arn\": \"arn:aws:iam::<redacted>:role/<redacted>\"}",
31c31
<                     "assume_role": "{\"role_arn\": \"arn:aws:iam::<redacted>:role/<redacted>\"}",
---
>                     "assumeRole": "{\"role_arn\": \"arn:aws:iam::<redacted>:role/<redacted>\"}",
36c36
<                     "assume_role": null,
---
>                     "assumeRole": null,
```

**Comment by justinvp** [comment]
This is an unfortunate side effect of https://github.com/pulumi/pulumi/pull/5170 ☹️. We're now including Provider property names in the snake_case/camelCase translation tables for Python, so `assume_role` (Python name) is being translated to `assumeRole` (Pulumi name) before being sent to the engine.

That change was made for a couple reasons:

1. Some providers (such as the Kubernetes provider) _require_ the names to be camelCase Pulumi names
2. All other language SDKs send these to the engine as camelCase Pulumi names

The reason we got away with _not_ doing the translation previously for Python (for TF-based providers) is because the TF name happens to be snake_case, so it'd end up being passed-through as-is. Otherwise, camelCase Pulumi names are translated to the TF names inside the provider via the TF bridge.

Unfortunately, this means existing stacks that use explicitly configured providers with snake_case property names are going to see these diffs after upgrading.

Probably the easiest way to avoiding replacing existing resources is to fix-up the name in the state, via pulumi stack export/import.

1. Export the stack's state.

    ```
    pulumi stack export > stack.json
    ```

2. Change `assume_role` to `assumeRole` for the provider resource in `stack.json`, basically:

    ```diff
            "resources": [
                {
                    "urn": "urn:pulumi:dev::awsassume::pulumi:providers:aws::provider",
                    "custom": true,
                    "id": "1bef5022-788b-4316-b796-771540eed224",
                    "type": "pulumi:providers:aws",
                    "inputs": {
    -                    "assume_role": "{\"role_arn\": \"redacted\"}"
    +                    "assumeRole": "{\"role_arn\": \"redacted\"}"
                    },
                    "outputs": {
    -                    "assume_role": "{\"role_arn\": \"redacted\"}"
    +                    "assumeRole": "{\"role_arn\": \"redacted\"}"
                    },
                    "parent": "urn:pulumi:dev::awsassume::pulumi:pulumi:Stack::awsassume-dev",
                    "propertyDependencies": {
    -                    "assume_role": null
    +                    "assumeRole": null
                    }
                }
            ]
    ```

3. Import the updated state.

    ```
    pulumi stack import < stack.json
    ```

**Comment by Sodki** [comment]
@justinvp Thank you for the clarification. I think my biggest problem was the lack of information, which reinforced my idea that this was a regression.

Should [the documentation](https://www.pulumi.com/docs/reference/pkg/aws/provider/) be changed to reflect this? It's still shows `assume_role` everywhere and says nothing about `assumeRole`.

**Comment by justinvp** [comment]
> which reinforced my idea that this was a regression.

For existing stacks, I would consider it a regression. Ideally, we would have come up with a way to avoid the diff, so that you wouldn't have even run into this. I'm sorry about that.

> Should [the documentation](https://www.pulumi.com/docs/reference/pkg/aws/provider/) be changed to reflect this? It's still shows `assume_role` everywhere and says nothing about `assumeRole`.

You can and should continue to use `assume_role` in your program! This is the expected name to use for Python programs. It's just that under the covers, we now translate it to `assumeRole` (like we do for many other Python properties), which is saved as part of the stack's state.

**Comment by Sodki** [comment]
Thanks, I'll close this issue then.

**Comment by justinvp** [comment]
> This makes it practically impossible to upgrade, since now Pulumi wants to replace all my resources.

@Sodki, do you have a repro that demonstrates Pulumi replacing resources? We see the provider resource being updated, after upgrading, but aren't seeing any resource _replacements_.

**Comment by Sodki** [comment]
Unfortunately no, not even a screenshot. I'm thinking this was probably not an issue with Pulumi _per se_, but a consequence of moving to pulumi-aws 3.x, which in my particular case did trigger a lot of valid replacements. Maybe at the time I just got scared and rolled back without connecting the two dots. I'm sorry about that.
