### ISSUE TITLE
Add support for AppMesh VirtualGateway

### ISSUE THREAD

**Issue by kamushadenes** [pulumi/pulumi-aws#1094]
Now you can configure ingress for your applications running within App Mesh with virtual gateways that allow services outside of your mesh to communicate with services inside the mesh.

This issue tracks AppMesh VirtualGateway support on Pulumi.

# Upstream
https://github.com/terraform-providers/terraform-provider-aws/issues/14169

# References
- https://aws.amazon.com/about-aws/whats-new/2020/07/aws-app-mesh-launches-ingress-support-for-virtual-gateways/
- https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_gateways.html

**Comment by RXminuS** [comment]
This has been closed upstream.

**Comment by lukehoban** [comment]
Indeed - and available in Pulumi at https://www.pulumi.com/docs/reference/pkg/aws/appmesh/virtualgateway/.
