### ISSUE TITLE
GetPolicyDocumentStatementPrincipalArgs.Identifiers should be of type List<Input<string>> ?

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi-aws#1102]
Hi, reason I am creating this issue:

![image](https://user-images.githubusercontent.com/57436/91664936-a46fd880-eaf2-11ea-9802-972431717f61.png)

I think this property should be of type `List<Input<string>>`?

https://github.com/pulumi/pulumi-aws/blob/191dd1ae2577c0754f3f4f7bd696e42ddf1e4538/sdk/dotnet/Iam/Inputs/GetPolicyDocumentStatementPrincipalArgs.cs#L16-L26

The node/ts version appears to be, so it looks like a discrepancy:

https://github.com/pulumi/pulumi-aws/blob/191dd1ae2577c0754f3f4f7bd696e42ddf1e4538/sdk/nodejs/iam/documents.ts#L175-L185

Cheers

**Comment by leezen** [comment]
The values to a `Get` invoke should be prompt values, so this appears to be by design. The Node code you're pointing toward is used as a convenience for constructor args and not retrieving them.
