### ISSUE TITLE
aws.appsync.DataSource defaults to generating an invalid resource name

### ISSUE THREAD

**Issue by woeps** [pulumi/pulumi-aws#1107]
The AWS resource name constructed by Pulumi for an Appsync DataSoure doesn't adhere to AWS naming policies (dash is not allowed).
Therefore you're forced to set a custom name in the args, which in my case is causing issues when Pulumi tries to update this resource. (naming collissions)

Devs can solve this by passing in a transformation in the opts or generating their own hash to be used in the custom name. But a far better DX would be achieved, if Pulumi would already handle the naming correctly.

As a sidenote: This issue was already present for about a year (since appsync provider were released), but just recently surfaced in a project again.

This same issue was already reported (#781) and solved (#802) for aws.appsync.Function.

**Comment by stack72** [comment]
Ho @woeps 

My apologies for this - can you share a snippet of code that I can use to test this and get it working?

Thanks

Paul
