### ISSUE TITLE
aws.budgets.Budget will always be updated without any changes made

### ISSUE THREAD

**Issue by CanRau** [pulumi/pulumi-aws#1126]
```
Plan          Info
update     [diff: ~limitAmount]
```

haven't touched anything, it always wants to update the Budget resource even if set to a static string 🤷‍♂️

**Comment by stack72** [comment]
To add some more detail here - this manifests itself as:

```
 ~ limitAmount: "1200.0" => "1200"
```

I can see the same issue upstream - https://github.com/terraform-providers/terraform-provider-aws/issues/10692

**Comment by stack72** [comment]
Hi @CanRau 

As a workaround, you can add the single decimal place and you will no longer get a diff

Paul

**Comment by CanRau** [comment]
Thank you @stack72 that seems to help 😃🙏

By the way, where did you see ` ~ limitAmount: "1200.0" => "1200"` I only get `[diff: ~limitAmount]` as shown above 🤔

**Comment by stack72** [comment]
@CanRau 

When you run `pulumi up`, it will offer you `yes / no / details` - have a look in the details view and it will show you a more detailed diff

P.

**Comment by CanRau** [comment]
Uuh, forgot about the details 😅 thanks a lot 🙏🤜🤛

**Comment by stack72** [comment]
Folks, I am sorry I didn't close this out earlier - this has been fixed!
