### ISSUE TITLE
Updating tags on Directory causes Pulumi to (offer to) delete-replace it

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi-aws#1127]
**Background:**
The `aws.directoryservice.Directory` resource correctly doesn't support tags. However due to an oversight in the example [auto-tagging stack transformation code](https://github.com/joeduffy/aws-tags-example/blob/master/autotag-ts/taggable.ts), it is listed as supporting tags. I auto-tagged a few things, and the tags went into the Pulumi state. (They're not applied in AWS, there's no way to see them anywhere except in the state. This is expected.)

**Problem:**
When I updated the tags being applied by the auto-tagger, Pulumi noticed the change and wanted to delete and replace the Directory. Deleting a Directory is a Big Deal.

**Expected behaviour:**
Resources that truly don't support tags probably shouldn't put them into state. And if they do, the resources should never rely on delete-replace for updating tags, or any properties that don't actually _require_ delete-replace. Delete-replace shouldn't be a "default" method of updating a resource.

**Workaround:**
I removed the offending line from my copy of `taggable.ts` and removed the tags from the state. So it's not a problem locally any more.

**Comment by stack72** [comment]
hi @tenwit 

I just tried updating tags in a directory (without autotag) and it works as expected - https://asciinema.org/a/hpEfzlYAruIx9kYbnFrPX3eEB

Then I added the autotagging code and got the following

https://asciinema.org/a/HtgWamalAiQ3dCfKLqAMJqLw9

Notice it never tried to replace the directory...

Paul

**Comment by stack72** [comment]
Just to also note - DirectoryServices Directory *does* allow tags to be added

It's even available via the CLI - https://docs.aws.amazon.com/cli/latest/reference/ds/add-tags-to-resource.html

**Comment by tenwit** [comment]
Your experience is the experience I want :) Didn't work that way for me :(
It must be something specific to my configuration though. I will close this issue and live with my workaround.

Odd about the tags not appearing in the console, just the API/CLI. They don't show up in the results from describe-directories either.
