### ISSUE TITLE
Dynamic or redistributable taggable resources

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi-aws#1134]
Right now to implement auto-tagging, you need to copy: https://github.com/joeduffy/aws-tags-example/blob/master/autotag-py/taggable.py on each project.

Would be a nice idea to make it a package or make it something dynamic, so you don't have to maintain the file across many projects.

**Comment by iwahbe** [comment]
The AWS provider now supports default tags. You can set them via `pulumi config` or by using the `defaultTags` option on explicit providers.
