### ISSUE TITLE
aws.neptune create encrypted cluster from snapshot does not work

### ISSUE THREAD

**Issue by aravinth-1234** [pulumi/pulumi-aws#1136]
I am trying to create a new encrypted neptune cluster from an unencrypted cluster snapshot through pulumi using node js sdk `neptune.Cluster` but the created cluster is not encrypted.

## Expected Behavior

Neptune cluster created should be encryption enabled

## Current Behavior

Created cluster is not encryption enabled

## Steps to Reproduce

1. code snippet:
```
const cluster = new aws.neptune.Cluster('foo-cluster', {
    clusterIdentifier: 'foo-cluster',
    applyImmediately: true,
    backupRetentionPeriod: 2,
    deletionProtection: false,
    engine: "neptune",
    iamDatabaseAuthenticationEnabled: false,
    preferredBackupWindow: clusterInfo.backupWindow,
    preferredMaintenanceWindow: clusterInfo.maintenanceWindow,
    neptuneClusterParameterGroupName: clusterParameterGroup.name,
    neptuneSubnetGroupName: neptuneConfig["subnet"],
    vpcSecurityGroupIds: neptuneConfig["securitygroup"],
    snapshotIdentifier: snapshotArn,
    skipFinalSnapshot: false,
    finalSnapshotIdentifier: 'foo-cluster-final-snapshot',
    storageEncrypted: true,
    kmsKeyArn: key_arn
  });
```
2. pulumi preview - shows `storageEncrypted` as true
3. pulumi up - successfully created
4. on verification in aws console the cluster shows `Encryption` as Not Enabled

## Context (Environment)

Pulumi version : 2.10.0
This issue is stopping us from doing a production release. Let us know if there are any ways to resolve this.

**Comment by stack72** [comment]
hi all

I'm sorry we have not responded to this issue - this is something we are trying to get better about. As I pointed out above, this isn't able to happen in the AWS SDK therefore, this is not something we are able to support in our provider :/

I apologise for this

Paul
