### ISSUE TITLE
ManagedPolicies consts for dotnet

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi-aws#1147]
Hi,

Node (JS/TS) has a useful collection of [managed policies](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/iam/managedPolicies.ts). However the equivalent does not exist for .NET (or possibly other langs).

Cheers.

**Comment by leezen** [comment]
Dupe of https://github.com/pulumi/pulumi-aws/issues/1130 (I'll add a note in there to make sure we include managed policies)
