### ISSUE TITLE
Typescript typings incorrectly limits type of Secret "valueFrom"

### ISSUE THREAD

**Issue by dustinboss** [pulumi/pulumi-aws#1150]
When adding `Secret` values to an ECS Container definition, I am getting Typescript errors because the `valueFrom` key is expecting a type of `string`. This is overly-restrictive, and in reality,  I think it can accept a `pulumi.Input<string>` such as the one returned from an instance of `aws.secretsmanager.Secret`.

Here's some sample code of what currently raises a Typescript error, but will actually compile correctly if I use `@ts-ignore` to suppress the error:

```javascript
const mySecret = new aws.secretsmanager.Secret('secret', {
  name: `my-secret'
  kmsKeyId: kmsKey.keyId
})

new awsx.ecs.FargateTaskDefinition('task-definition, {
  container: {
    secrets: [{
      name: 'MY_SECRET',
      valueFrom: mySecret.arn // This line expects a string but should accept pulumi.Input<string>
    }]
  }
})
```

Interface code referenced: 
https://github.com/pulumi/pulumi-aws/blob/06ad9e337fabcfe7aa0f936b3903fee40ce6d966/sdk/nodejs/ecs/container.ts#L247-L263

**Comment by lukehoban** [comment]
With the latest AWSX, this does typecheck correctly:

```ts
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const kmsKey = new aws.kms.Key("key")

const mySecret = new aws.secretsmanager.Secret('secret', {
    name: `my-secret`,
    kmsKeyId: kmsKey.keyId,
})

new awsx.ecs.FargateTaskDefinition('task-definition', {
    container: {
        image: "nginx",
        secrets: [{
            name: 'MY_SECRET',
            valueFrom: mySecret.arn // This line expects a string but should accept pulumi.Input<string>
        }]
    }
});
```

```
@pulumi/aws     5.21.1
@pulumi/awsx    0.40.1
```

This was seemingly fixed in https://github.com/pulumi/pulumi-aws/pull/1054.
