### ISSUE TITLE
AWS Batch py example not working due to missing VPC in sg

### ISSUE THREAD

**Issue by mehd-io** [pulumi/pulumi-aws#1155]
Hello there!

The example usage of aws batch [here](https://www.pulumi.com/docs/reference/pkg/aws/batch/computeenvironment/) which I guess is taken from [here](https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/batch/compute_environment.py#L38) is not actually working because the VPC is not specify in the sg created. It results by creating another sg which is not correctly configured to the VPC and an error state in the compute environment 

> `One or more security groups in the launch configuration are not linked to the VPCs configured in the Auto Scaling group`

I fixed this one by simply explicitly attached the sg created to the VPC created in the stack. Will make a PR for the py one but I guess this is the same for the other sdk.

**Comment by stack72** [comment]
Hi @mehd-io 

This is an autogenerated example that we need to fixup - the PR that you created won't fix this as we autogenerate it

I need to fix this at source

Paul

**Comment by mehd-io** [comment]
Ah alright, sorry about that, where that source is located ?

**Comment by stack72** [comment]
oh nothing to apologise for at all :) We actually generate our examples based from the Terraform provider docs.

I am fixing it up right now and it will be regenerated tomorrow

**Comment by stack72** [comment]
You will see a PR appear shortly @mehd-io :)
