### ISSUE TITLE
aws:region in stack config is ignored in 3.6.0

### ISSUE THREAD

**Issue by mleclercq** [pulumi/pulumi-aws#1158]
I have `aws:region` set in my stack configs but my stack is failing with the following error:

```
  aws:iam:User (xyz):
    error: 1 error occurred:
    	* Invalid AWS Region:
```

I do not get that error on version 3.5.0

**Comment by stack72** [comment]
Hi @mleclercq 

What region are you setting?

Paul

**Comment by mleclercq** [comment]
```
config:
  aws:region: us-east-1
```

**Comment by stack72** [comment]
Interesting - I will look into this immediately - we didn't see any failures on our tests over this so I need to dig in more

For now, you may be able to "pulumi config set aws:skipRegionValidation true" to see if that helps?

**Comment by mleclercq** [comment]
No that doesn't seem to help. I still get the same error with 3.6.0.

**Comment by stack72** [comment]
Ok I will look into this immediately

**Comment by jakegibson** [comment]
Running into this as well. Created a new stack in the same project that has a working stack, nearly identical config.  Both have region set to us-east-1, only difference is domain names but both are subdomains of the same domain

Pulumi.development.yaml
```
config:
  aws:region: us-east-1
  my-service:domain: service-development.mydomain.com
```

Error
```
  aws:acm:Certificate (certificate):
    error: 1 error occurred:
    	* Invalid AWS Region:
 ```

**Comment by stack72** [comment]
Hi all

We have found and are investigating this regression and will get a new version shipped asap!

P.

**Comment by Sodki** [comment]
I'm having a different behaviour, but I find it too much of a coincidence that I'm having region related problems at the same time.

1. I have multiple AWS accounts being managed by the same Pulumi stack in the same run
2. For whatever reason I had `AWS_DEFAULT_REGION` set in this session
3. `pulumi up` is running fine
4. `pulumi` refresh is breaking
5. I've unset `AWS_DEFAULT_REGION` and now `pulumi up` is breaking with `error: failed to load checkpoint: blob (key ".pulumi/stacks/prod.json") (code=Unknown): MissingRegion: could not find region configuration`

To anyone having this problem: does setting up `AWS_DEFAULT_REGION` work? If not, try combining it with `skipRegionValidation`. Perhaps we can find some workarounds that can help with finding out the root problem.

**Comment by stack72** [comment]
Setting environment variables will allow you to get past this problem while we work on things

**Comment by catmeme** [comment]
I'm seeing this with `3.5.0` as well.

**Comment by stack72** [comment]
I am cutting a new release right now - v3.6.1 will be available soon that fixes the problem
