### ISSUE TITLE
MissingRegion error when running any Pulumi command

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aws#1170]
Hi, when I run any `pulumi` command I'm getting the following error:

```
error: failed to load checkpoint: blob (key ".pulumi/stacks/prod.json") (code=Unknown): MissingRegion: could not find region configuration
```

More information:

```
$ cat Pulumi.prod.yaml
...
config:
  aws:region: eu-west-1
...

$ pulumi plugin ls | grep aws
aws         resource  3.7.0    248 MB  n/a        23 minutes ago

$ pulumi version
v2.11.2
```

I'm using S3 to store the state files and KMS to store the secret key.

Things do work if I set up the environment variable `AWS_DEFAULT_REGION`:

```
$ export AWS_DEFAULT_REGION=eu-west-1

$ pulumi config get aws:region
eu-west-1
```

I would expect that Pulumi's stack configuration would be used to get the state initially. Is this not the case?

Thank you

**Comment by stack72** [comment]
Hi @Sodki 

So I am not quite following here - you have set the region as pulumi config set or are you starting with an empty pulumi config file?

Paul

**Comment by Sodki** [comment]
I have the region set in Pulumi config and I have been using Pulumi for a couple of months now.

I've noticed that I had `AWS_DEFAULT_REGION` set in my shell profile and I got this error when I removed it. So I'm not sure if this is a bug in Pulumi, a limitation or a design decision. For my use case I'd prefer that my developers don't have to add extra configuration and can rely solely on Pulumi.

**Comment by leezen** [comment]
Looking at the error `error: failed to load checkpoint: blob (key ".pulumi/stacks/prod.json") (code=Unknown): MissingRegion: could not find region configuration` this looks like you're using the S3 backend? In which case, the backend retrieval path never uses what's in `Pulumi.<stack>.yaml`. Per https://www.pulumi.com/docs/intro/concepts/state/#self-managed-backends, the backend configuration is governed by what's described in https://docs.aws.amazon.com/sdk-for-go/api/aws/session/

**Comment by Sodki** [comment]
Thank you, it makes sense now, and yes I'm using the S3 backend.

Someone in Slack helped me to fix my problem by adding the region to the backend URL, like so:

```
backend:
  url: s3://bucket/path?region=us-east-1
```

In this case there is no need to try and find out which region to use, so the SDK doesn't complain anymore. Would it make sense to add this to the documentation somehow? If you think it doesn't then feel free to close this issue.

Thank you

**Comment by stack72** [comment]
Hi @Sodki 

this is currently documented - not very well - in the stacks doc - https://www.pulumi.com/docs/intro/concepts/project/

**Comment by stack72** [comment]
We are going to spend some time with regards to backends soon - I will ensure the docs are updated in this set of work to make it way more clear
