### ISSUE TITLE
AWS Lex bot, intent, and slottypes can not use autogenerated names with hyphens

### ISSUE THREAD

**Issue by displague** [pulumi/pulumi-aws#1174]
The generated name is not acceptable for use in AWS Lex when using the order_flower_bot example at https://www.pulumi.com/docs/reference/pkg/aws/lex/bot/:

```
Diagnostics:
  aws:lex:Bot (order_flower_bot):
    error: aws:lex/bot:Bot resource 'order_flower_bot' has a problem: expected value of name to match regular expression "^([A-Za-z]_?)+$", got order_flower_bot-d885833
```

This also applies to `intents` and `slottypes` (I haven't checked other resources).

**Comment by mikhailshilkov** [comment]
Should we keep auto naming but remove dashes? (`Separator: ""`)
