### ISSUE TITLE
AWS EKS worker node taints

### ISSUE THREAD

**Issue by Kirill-Garbar** [pulumi/pulumi-aws#1176]
Hello.
As far as I understand pulumi golang doesn't have possibility to create tainted worker node for EKS.
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
I've found this possibility only for TypeScript.
https://www.pulumi.com/docs/guides/crosswalk/kubernetes/worker-nodes/#pod-scheduling

Is it planned to implement it for golang?

**Comment by lukehoban** [comment]
The https://github.com/pulumi/pulumi-eks component is a higher-level API for working with EKS in Pulumi.  It is currently only available in TypeScript, but you can do the same things that higher-level library does in any Pulumi language.  See the implementation of the taints feature [here](https://github.com/pulumi/pulumi-eks/blob/b087075c833a0f60243cf3ef064f28c22690e881/nodejs/eks/nodegroup.ts#L423-L432).  The full higher-level Pulumi EKS package is coming to all Pulumi languages soon as part of https://github.com/pulumi/pulumi-eks/issues/408 and https://github.com/pulumi/pulumi-eks/issues/57 (expected ~end of this month).

**Comment by Kirill-Garbar** [comment]
@lukehoban Hi.
> The full higher-level Pulumi EKS package is coming to all Pulumi languages soon as part of pulumi/pulumi-eks#408 and pulumi/pulumi-eks#57 (expected ~end of this month).

Am I right that end of this month is end of october? Could you please tell the approximate timeline for porting of pulumi-eks to golang?

**Comment by leezen** [comment]
@Kirill-Garbar We were originally targeting end of October. We ran into a couple problems while porting and have revised the timeline and are targeting 11/11 (see also https://github.com/pulumi/pulumi/issues/2430)
