### ISSUE TITLE
Aws ignoreTags seems not working

### ISSUE THREAD

**Issue by gdeber** [pulumi/pulumi-aws#1178]
Hi all.
I'm trying to use ignoreTags in aws.
I created a simple ec2 with tag "name". After that i added a new tag "mytag" (outside pulumi workflow), which should be ignored in pulumi up.
So this my stack configuration file:
```
config:
  aws:region: eu-west-1
  aws:ignoreTags:
    - keys: ['mytag']
```

after a stack refresh, this is output of _pulumi up_ :

```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:deleteme-ignoretags::pulumi-aws-ec2::pulumi:pulumi:Stack::pulumi-aws-ec2-deleteme-ignoretags]
    ~ aws:ec2/instance:Instance: (update)
        [id=i-076a8ebc1bb2b4b61]
        [urn=urn:pulumi:deleteme-ignoretags::pulumi-aws-ec2::aws:ec2/instance:Instance::deleteme-testtags01]
        [provider=urn:pulumi:deleteme-ignoretags::pulumi-aws-ec2::pulumi:providers:aws::default_3_5_0::4f758df6-1e47-4551-a41d-3fd619128d16]
      ~ tags: {
          - mytag: "ignoremeplease"
        }
```

After the update,  mytag is removed.

**Comment by johnnyrun** [comment]
@stack72 may you drive me in the direction of resolving this issue?
I would like to contribute to this issue, but I need suggestions.

**Comment by iwahbe** [comment]
@gdeber, thanks for opening an issue. You passed `'mytag'` at the path `config.aws:ignoreTags[0].keys[0]`. That isn't quite right. You need to pass the keys you want at `config.aws:ignoreTags.keys[0]`:

```patch
 config:
   aws:region: eu-west-1
   aws:ignoreTags:
-    - keys: ['mytag']
+    keys: ['mytag']
```

This works for me (in that Pulumi won't delete ignored tags). Please file another issue if this doesn't work for you.
