### ISSUE TITLE
mapping bug on `aws.iam.OpenIdConnectProvider` - `thumbprint_lists ` should be `thumbprint_list`

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aws#1182]
There is a mapping bug on `aws.iam.OpenIdConnectProvider` has `thumbprint_lists ` should be `thumbprint_list`.

https://github.com/pulumi/pulumi-aws/blob/49c8fa2f323b1de58d40e2d63a2088838ac80eac/sdk/python/pulumi_aws/iam/open_id_connect_provider.py#L124-L130

This appears to be the case across all language SDKs.

**Comment by stack72** [comment]
Closing this out - this is a list and we pluralize list property names
