### ISSUE TITLE
Can not create RDS instance with identifierPrefix. "ConflictsWith" error

### ISSUE THREAD

**Issue by chrisportela** [pulumi/pulumi-aws#1184]
Getting an error creating the following instance

```
const rdsInstance = new aws.rds.Instance(
      `${env}-postgres`,
      {
        identifierPrefix: `${serviceName}-${env}-`,
        engine: 'postgres',
        engineVersion: rdsConfig.get('version') || '9.6.11',
        instanceClass: rdsConfig.get('instanceType') || aws.rds.InstanceType.T3_Micro,
        allocatedStorage: 100,
        storageType: aws.rds.StorageTypes.GP2,
        storageEncrypted: true,
        snapshotIdentifier: rdsConfig.get('baseSnapshot'),
        backupRetentionPeriod: 5,
        backupWindow: '04:00-04:30',
        maintenanceWindow: 'sun:04:30-sun:05:30',
        allowMajorVersionUpgrade: true,
        autoMinorVersionUpgrade: true,
        finalSnapshotIdentifier: `${serviceName}-${env}-rds-final-snapshot`,
        skipFinalSnapshot: true,
        copyTagsToSnapshot: false,
        multiAz: rdsConfig.getBoolean('multiAz') || false,
        applyImmediately: rdsConfig.getBoolean('applyImmediately') || false,
        vpcSecurityGroupIds: [rdsSg.id],
        port: 5432,
        name: serviceName,
        username: 'postgres',
        password: rdsConfig.requireSecret('adminPassword'),
        dbSubnetGroupName: rdsSubnetGroup.name,
        parameterGroupName: rdsParamGroup.name,
        performanceInsightsEnabled: rdsConfig.getBoolean('performanceInsights') || false,
        monitoringInterval: 0,
        deletionProtection: env === 'prod',
      },
      {
        protect: env === 'prod',
      },
    );
```

This is part of the output:

```
     └─ aws:rds:Instance                        qa-postgres                 1 error
 
Diagnostics:
  aws:rds:Instance (qa-postgres):
    error: aws:rds/instance:Instance resource 'qa-postgres' has a problem: ConflictsWith
```

If I remove the identifierPrefix it works. If I make identifier `undefined` it still errors. I'm just trying to create a database with a consistent name but including the random part at the end. I can't tell if this is a terraform provider or pulumi code problem because I don't have an up to date terraform config to test this with.

**Comment by clstokes** [comment]
Hey @chrisportela, I suspect it's the `identifierPrefix` property that is causing the issue. Can you try omitting that and see if the error goes away?

**Comment by chrisportela** [comment]
yes it does go away if I remove `identifierPrefix` but then it uses the resource name as the prefix.

**Comment by chrisportela** [comment]
@clstokes @stack72 A co-worker reading this issue assumed I was using `identifier` and `identifierPrefix` together so I just want to make sure it's clear the issue is only using `identifierPrefix` by itself. If I remove that everything works fine, but it's using the resource name as the prefix.

I think this is a legit bug in either terraform or pulumi instead of just the warning being a little vague.

We're using Node `12.19.1` and these are our versions of pulumi packages

```
├─ @pulumi/aws@3.9.0
├─ @pulumi/awsx@0.22.0
├─ @pulumi/docker@2.2.3
├─ @pulumi/postgresql@2.4.0
├─ @pulumi/pulumi@2.12.1
│  ├─ semver@6.3.0
│  └─ typescript@3.7.5
```

**Comment by stack72** [comment]
So the issue here is that Pulumi will always specify a name parameter - either directly or indirectly (through autonaming)

This means that there's a bug here that the name-prefix is useless when using Pulumi

Ok, leave this one with me to talk about with other members of the team and see what we should do here

**Comment by lukehoban** [comment]
While the error message improvement discussed in https://github.com/pulumi/pulumi-terraform-bridge/issues/309 will help here - I believe the core issue is - as @stack72 notes - that these `prefix` properties will not work correctly with autonaming.  This is a deeper issue that will need to be addressed.

**Comment by chrisportela** [comment]
We're still having this error. As a work around we simply name the resource what we want prefixed and then it gets the random letters added on the end.

**Comment by iwahbe** [comment]
We no longer see this error. I am able to deploy an `aws.rds.Instance` with `identifierPrefix` set:

```yaml
name: example
runtime: yaml
resources:
  aws-provider:
    type: pulumi:providers:aws
    properties:
      region: us-east-2
    defaultProvider: true
  res:
    type: aws:rds:Instance
    properties:
      identifierPrefix: "foo"
      engine: "postgres"
      instanceClass: "db.t3.micro"
      allocatedStorage: 20
      username: "myusername"
      password: "mypassword"
      skipFinalSnapshot: true
outputs:
  actual: ${res.identifier}
```

```
Do you want to perform this update? yes
Updating (test)

View in Browser (Ctrl+O): https://app.pulumi.com/pulumi/example/test/updates/162

     Type                 Name                     Status             
     pulumi:pulumi:Stack  example                     
 +   └─ aws:rds:Instance  res                      created (215s)     


Outputs:
  + actual: "foo20230811083041830000000001"

Resources:
    + 1 created
    2 unchanged

Duration: 3m40s

```
