### ISSUE TITLE
Certain ASG metrics not supported

### ISSUE THREAD

**Issue by jhinklew** [pulumi/pulumi-aws#1187]
Hallo!

The `enabledMetrics` property of the `autoscaling.Group` class allows us to enable which metrics we want to enable for an autoscaling group. 

[In the documentation](https://www.pulumi.com/docs/reference/pkg/aws/autoscaling/group/#enabledmetrics_nodejs) it states the following are allowed values: 

1. `GroupDesiredCapacity`
1. `GroupInServiceCapacity`
1. `GroupPendingCapacity`
1. `GroupMinSize`
1. `GroupMaxSize`
1. `GroupInServiceInstances`
1. `GroupPendingInstances`
1. `GroupStandbyInstances`
1. `GroupStandbyCapacity`
1. `GroupTerminatingCapacity`
1. `GroupTerminatingInstances`
1. `GroupTotalCapacity`
1. `GroupTotalInstances`

However, if we take a look at the [source of the enum](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/enums/autoscaling/index.ts#L5-L14) or the [constant definitions](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/autoscaling/metrics.ts) for `Metric` you'll notice only 8 ASG metrics are _actually_ supported (out of the 13).

Specifically, these are missing:
1. `GroupInServiceCapacity`
1. `GroupPendingCapacity`
1. `GroupStandbyCapacity`
1. `GroupTerminatingCapacity`
1. `GroupTotalCapacity`

This is easily confirmed locally because attempting to use one of the "missing metrics" causes an error in VS Code:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/36640094/97230150-6cf67300-17a7-11eb-974c-b2a0ab9c8e3e.png">

Hoping this is an easy fix and I'm more than happy to submit a PR if needed. Either way, let me know if you require any further information!

**Comment by stack72** [comment]
Hi @jhinklew 

Thanks so much for opening this - a PR is on the way to fix this up!

Paul
