### ISSUE TITLE
Unable to add Aurora cluster roles

### ISSUE THREAD

**Issue by jamesholmes-linktree** [pulumi/pulumi-aws#1191]
Aurora cluster roles now need to specify the SupportedFeatureName and this is not possible with Pulumi.

## Expected Behaviour
When adding cluster roles, there should be some way of specifying the SupportedFeatureName, as there is with instance role attachments.

## Current Behavior
The only provision for cluster roles is the iamRoles parameter on aws.rds.Cluster, which doesn't allow the feature name to be specified.

## Steps to Reproduce
Create an Aurora PostgreSQL cluster and try to add roles for s3Import and s3Export.

## Context (Environment)
I'm trying to get a cluster up with the right roles for the right features.

**Comment by jamesholmes-linktree** [comment]
This was the push we needed to swap to CDK. That should result in a decent savings on our monthly bill, as we'll now only need a user or two to maintain the odd thing that is outside of CF.

**Comment by stack72** [comment]
This shipped a while ago
