### ISSUE TITLE
LB Listener protocol docs are worng

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi-aws#1193]
For https://www.pulumi.com/docs/reference/pkg/aws/lb/listener/#protocol_python is stated that "The protocol for connections from clients to the load balancer. Valid values are TCP, TLS, UDP, TCP_UDP, HTTP and HTTPS. Defaults to HTTP."
But when trying to use `HTTP` i get the fllowing error: `* error creating ELBv2 Listener: ValidationError: Listener protocol 'HTTP' must be one of 'TLS, TCP, TCP_UDP, UDP'`

So I believe that HTTP and HTTPS are not valid values.

**Comment by viveklak** [comment]
Could you confirm you are trying to attach the listener to an ALB and not an NLB?

**Comment by GaboFDC** [comment]
Yes i was creating an NLB, didn't realize the documentation covered both. Maybe make some kind of separation or notation to be aware of this?

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/terraform-provider-aws/pull/60.
