### ISSUE TITLE
Fail to destroy internet gateway

### ISSUE THREAD

**Issue by ronoc** [pulumi/pulumi-aws#1221]
Any time I try to tear down a stack, it times out destroying an internet gateway resource. I have to then manually delete it and retry. 

```
deleting urn:pulumi:test::private::aws:ec2/internetGateway:InternetGateway::axiom-private-public-igw-testing: Error waiting for internet gateway (igw-00d0e33c0887b089a) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)
```

**Comment by ronoc** [comment]
i'm pretty sure that this then it making it pretty impossible to delete vpc via pulumi

```
  aws:ec2:Vpc (axiom-private-vpc-development):
    error: deleting urn:pulumi:test::private::aws:ec2/vpc:Vpc::axiom-private-vpc-development: Error deleting VPC: DependencyViolation: The vpc 'vpc-00e0b5c344c4a73c8' has dependencies and cannot be deleted.
    	status code: 400, request id: 48cc8145-d7b3-43b5-aa6c-c6dcdc53da40
 
  pulumi:pulumi:Stack (private-test):
    error: update failed
 
  aws:ec2:Vpc (axiom-private-vpc-testing):
    error: deleting urn:pulumi:test::private::aws:ec2/vpc:Vpc::axiom-private-vpc-testing: Error deleting VPC: DependencyViolation: The vpc 'vpc-06741e7a5c81724fe' has dependencies and cannot be deleted.
    	status code: 400, request id: e0bd18c9-57e9-4b25-b329-fcc67748c993
```

**Comment by leezen** [comment]
One option here would be to try increasing the timeout for this resource via a customTimeout: https://www.pulumi.com/docs/intro/concepts/programming-model/#customtimeouts

Could you please try that and see if that works for you?

**Comment by ronoc** [comment]
Will do, the next time I need to tear down a stack.

**Comment by ronoc** [comment]
Found a solution in my case, make sure to make the IG a dependency on both the elastic ip and the ecs instance (both for your bastion). This fixed it for me at least. From what I can find on the interweb people have had this issue when some elastic ip which is dependent upon the gateway has not yet been destroyed.

**Comment by leezen** [comment]
Thanks for the update!
