### ISSUE TITLE
Cannot create SecurityGroupRule using EKS outputs using TypeScript SDK

### ISSUE THREAD

**Issue by vyrwu** [pulumi/pulumi-aws#1222]
### Description
Using TypeScript SDK, I want to be able to add custom SecurityGroupRules based on the Security Group outputs from the EKS cluster. However, when I do so, Pulumi throws an error for the SecurityGroupRule resource, indicating that a required attribute is not set, but it doesn't really say which one - though I suspect it's the _securityGroupId_:

```
Diagnostics:
  aws:ec2:SecurityGroupRule (cluster-ingress-rule):
    error: aws:ec2/securityGroupRule:SecurityGroupRule resource 'cluster-ingress-rule' has a problem: Required attribute is not set
```

Interestingly, if I run **pulumi up** once without creating that rule, which will bring my EKS up, and then provision the Rule with another **pulumi up**, the error is no longer there and the resource builds correctly. It only happens when I'm bringing up my entire stack from scratch in one go. For building ephemeral environments with Pulumi, this becomes a big blocker.

### My TS script
```js
  // 1. Create a Security Group for an EKS
  const clusterSecurityGroup = new aws.ec2.SecurityGroup(
    getConventionName('cluster-sg'),
    {
      vpcId,
      ingress: [
        {
          fromPort: 0,
          toPort: 0,
          protocol: '-1',
          securityGroups: [securityGroupId] // here, the SG ID is a string
        }
      ]
    }
  )
  ...
  // 2. Create an EKS cluster and pass SG ID as Output
  const eksCluster = new aws.eks.Cluster(
    getConventionName('eks'),
    {
      vpcConfig: {
        subnetIds,
        endpointPublicAccess: false,
        endpointPrivateAccess: true,
        securityGroupIds: [clusterSecurityGroup.id] // here, the SG ID is Output<string>
      },
      enabledClusterLogTypes: [...],
      roleArn: clusterRole.arn,
      version
    },
    {
      dependsOn: pulumiLogGroups
    }
  )
  ...
  // 3. Create SecurityGroupRule based on the EKS Security Group
  new aws.ec2.SecurityGroupRule(getConventionName('cluster-ingress-rule'), {
          securityGroupId: eksCluster.vpcConfig.clusterSecurityGroupId, // here, the SG ID is also evaluated to Output<string>
          type: "ingress",
          fromPort: 0,
          toPort: 0,
          protocol: "-1",
          sourceSecurityGroupId: "some-id"
      }, {
          parent: eksCluster,
          dependsOn: [eksCluster], // maybe putting 'eksCluster.vpcConfig' here would be a solution?
          deleteBeforeReplace: true,
      })
``` 

### Question
I can resolve this trivially by passing the ID from the Security Group object, but it feels like this should not be erroring out. Am I falling into an implicit anti-pattern here? I wanted to ask more knowledgeable Pulumi people here if that is indeed the case, and if so - why? Maybe my code follows some false assumptions about Pulumi that I need to be aware of going forward? Or maybe this is a bug?

### Suggestion
Give more meaningful error messages, like: 'securityGroupId is not an Output'.

Thanks for taking the time

**Comment by leezen** [comment]
Is that error you reference occurring during the preview step of the `pulumi up` or during the update?

**Comment by vyrwu** [comment]
@leezen during `pulumi up`

**Comment by leezen** [comment]
I took a look and this appears to be the same issue as pulumi/pulumi-azure#192. As a workaround, you can switch to using something like this:

```typescript
eksCluster.vpcConfig.clusterSecurityGroupId.apply(id => id || "sg-id")
```

which should get you past the preview error.

**Comment by leezen** [comment]
Tracking in https://github.com/pulumi/pulumi/issues/5864
