### ISSUE TITLE
python-aws: depends_on not being respected

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#1226]
**Issue:**
The attached python pulumi application has two resources that use dependsOn to drive deployment and deletion orders.
Neither of the dependencies are respected during the destroy.
In the case of the ECS cluster, specifically, it will try to delete the cluster before the autoscaling group which results in a failure since AWS can't delete the cluster if there are instances. 
While it is trying to delete the cluster, if you go into the AWS console and delete the auto scaling group, the stack will destroy correctly.

Attached is a file containing the debug output from a destroy that failed as described.

**How to Reproduce**
1) copy the pulumi application
2) `pulumi up`
3) Once the deployment completes, wait a minute and confirm the URL link works - it should show an nginx splash page.
4) `pulumi destroy`

The Service will be the first thing deleted and will take a few minutes.
Then it will try to delete the cluster which will hang until failure since it needs to delete the autoscaling group first.

[__main__.py.txt](https://github.com/pulumi/pulumi-aws/files/5570990/__main__.py.txt)
[pulumi_destroy.out.txt](https://github.com/pulumi/pulumi-aws/files/5570991/pulumi_destroy.out.txt)

**Comment by MitchellGerdisch** [comment]
Oh dear. I believe I've got my thinking backwards.
Destroy would naturally try to destroy the cluster the first since it is dependent on the autoscaling group and so naturally one should not delete the autoscaling group until after the cluster is deleted.
I think this issue can be closed.

**Comment by lukehoban** [comment]
> Destroy would naturally try to destroy the cluster the first since it is dependent on the autoscaling group and so naturally one should not delete the autoscaling group until after the cluster is deleted.

Yes - that's right.  If A depends on B, then B must be created before A, and A must be destroyed before B.
