### ISSUE TITLE
LifecyclePolicy doesn't allow custom cron expression in Policy Schedule

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-aws#1230]
Current definition for LifecyclePolicy https://www.pulumi.com/docs/reference/pkg/aws/dlm/lifecyclepolicy/ doesn't allow cron expression in Policy Schedule.

This is important, because with the current definition the minimum period to create a snapshot is 1 hour. 

However, on AWS if I want to take a snapshot every 15 minutes, I can configure it like this:
![image](https://user-images.githubusercontent.com/33038414/100235037-3178d100-2f2c-11eb-80d7-d296ccca9193.png)

**Comment by stack72** [comment]
This is being tracked upstream at https://github.com/hashicorp/terraform-provider-aws/issues/13627

**Comment by lukehoban** [comment]
This was fixed upstream, and should now be available in pulumi-aws releases.
