### ISSUE TITLE
ec2.getSecurityGroups sample code is not clear

### ISSUE THREAD

**Issue by bit-cloner** [pulumi/pulumi-aws#1234]
example code 
```
import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const test = aws.ec2.getSecurityGroups({
 *     filters: [
 *         {
 *             name: "group-name",
 *             values: ["*nodes*"],
 *         },
 *         {
 *             name: "vpc-id",
 *             values: [_var.vpc_id],
 *         },
 *     ],
 * });
```
stops at this and doesn't expand on how to use "test" object here. 
When i tried to run this and console.log(test) I am getting a "promise { pending }"
Any guidance and updated documentation would be helpful.

**Comment by stack72** [comment]
Hi @bit-cloner 

When accessing the promise, you can either wrap in in pulumi.output or call the .then function afterwards

https://github.com/pulumi/examples/blob/7447138787b31503a4da0d82f7b44015914dcfc4/aws-ts-appsync/iam.ts#L8

Please ignore the async:true - that is the default now

**Comment by bit-cloner** [comment]
Hi @stack72 Thans for the tip. I am not an expert in async javascript concept , but it still made sense. 
I gave it a try like this but still seeing promise {pending}

```

   import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const test = aws.ec2.getSecurityGroups({
 *     filters: [
 *         {
 *             name: "group-name",
 *             values: ["*nodes*"],
 *         },
 *         {
 *             name: "vpc-id",
 *             values: [_var.vpc_id],
 *         },
 *     ],
 * }).then((result) => result.ids)
    console.log(test) // promise {pending}
```

Any ideas where I am going wrong ?

**Comment by bit-cloner** [comment]
Hey @stack72 figured it out myself 
like this 
```

import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const test = aws.ec2.getSecurityGroups({
 *     filters: [
 *         {
 *             name: "group-name",
 *             values: ["*nodes*"],
 *         },
 *         {
 *             name: "vpc-id",
 *             values: [_var.vpc_id],
 *         },
 *     ],
 * }).then((result) => {console.log(result.ids})

  ```

Thanks a bunch for your help.

**Comment by stack72** [comment]
Hi @bit-cloner 

Is there anything we can do to help this going forward? Or are we ok to close out this issue?

P.

**Comment by bit-cloner** [comment]
The reported issue is due to my lack of understanding of promises in javascript. I think I get it now.

What would be helpful is some examples in official pulumi docs Web page to show this.

Again thanks a lot. This issue can be closed now.
