### ISSUE TITLE
Elastic Beanstalk environment variables not being removed

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi-aws#1235]
Environment variables that have been added via multiple `aws:elasticbeanstalk:environment` keys doesn't get removed again once the configuration key is removed as well from my `Pulumi.dev.yaml` file.

**Comment by ffMathy** [comment]
Actually, it does seem to work - it just seems to produce a weird diff in the "preview" feature.

**Comment by leezen** [comment]
Could you please provide more details about the oddity you're seeing?
