### ISSUE TITLE
eks package's createNodeGroup function would benefit from some advanced examples

### ISSUE THREAD

**Issue by bit-cloner** [pulumi/pulumi-aws#1236]
I am struggling to use createNodeGroup with extraNodeSecurityGroups parameter. the documentation says the value of this parameter needs to be SecurityGroup[]. I tried passing an array of strings of security group ids and also passing the output of ec2
.getSecurityGroup but it is simply not assigning those security groups to worker nodes. 

My code that is not working looks like this 
```
      cluster1.createNodeGroup("abc", {
      instanceType: "t3.medium",
      autoScalingGroupTags: {
        ["k8s.io/cluster-autoscaler/enabled"]: "true",
        [asgtag]: "owned",
      },
      spotPrice: "0.6",
      nodeAssociatePublicIpAddress: false,
      nodeSubnetIds: [privatesnetids[0][0][0], privatesnetids[0][0][1]], 
      desiredCapacity: 1,
      amiId: "ami-00d7f1aeda5144f18", 
      minSize:1,
      nodeUserDataOverride: userdata,
      extraNodeSecurityGroups: [
        aws.ec2
          .getSecurityGroup({
            id: "sg-78673456687673",
          })
          .then((selected) => {
            selected
          }),
      ],
      maxSize: 4,
.....


```

Where am i getting it wrong ? any guidance is much appreciated Thank you

**Comment by bit-cloner** [comment]
further debugging the issue . I noticed that if I add extraNodeSecurityGroups after a node group is created . It throws a panic with the following message
```
panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:dev::eks18::eks:index:Cluster$eks:index:NodeGroup$aws:ec2/launchConfiguration:LaunchConfiguration::apps-spot4-nodeLaunchConfiguration
```
Looks like updating a launchconfiguration with new securitygroupids seem to fail when done an existing node group. If it is a new nodegroup it simply ignores extraNodeSecurityGroups.

FYI pulumi version I am on is v2.14.0

**Comment by bit-cloner** [comment]
Digging deeper It seems pulumi is not aware that a launch configuration cannot be edited/updated. As per AWS API only a new launch configuration can be created and attached to existing ASG. AWS doesn't allow edit of launch configurations.

Terraform does it as documented below. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration

Pulumi tries to update in place a node launch configuration which results in this error. Starting to think this is a bug.

**Comment by lukehoban** [comment]
@bit-cloner Sorry for the issues here.  The error you are seeing `Expected diff to not require deletion or replacement` is always a bug in Pulumi, so this is definitely something we need to look into - and is not expected behaviour.

I don't 100% follow the repro case here.  It sounds like you hit that panic after hitting some other issue - but what exactly was the original issue you hit?  Any chance you have a repro for each of the two issues?

**Comment by lukehoban** [comment]
Looks like this may be ultimately related to https://github.com/pulumi/pulumi-terraform-bridge/issues/296.

**Comment by bit-cloner** [comment]
Possibly. But can't confirm. What I was trying to do is add "extraNodeSecurityGroups" to an existing node group.

Panic error happens when adding these to existing resource.

Ultimately I Want to be able to create a node group with extra security groups.

I will raise a detailed repro tomorrow

Thank you

**Comment by pgavlin** [comment]
Closing as a duplicate of #1242.
