### ISSUE TITLE
Add support for new Amazon Managed Workflows for Apache Airflow (MWAA) service

### ISSUE THREAD

**Issue by r-clancy** [pulumi/pulumi-aws#1243]
Amazon has added a new managed Airflow service which should be deployable from Pulumi.

https://aws.amazon.com/blogs/aws/introducing-amazon-managed-workflows-for-apache-airflow-mwaa/

**Comment by stack72** [comment]
Hey @r-clancy 

going to track this as a waiting on upstream - https://github.com/hashicorp/terraform-provider-aws/issues/16432

We will ensure we get this added ASAP

P.

**Comment by discovery-NukulSharma** [comment]
This has been merged by upstream - https://github.com/hashicorp/terraform-provider-aws/issues/16432
Do we know when shall we expect this on pulumi ?

**Comment by stack72** [comment]
Hey @discovery-NukulSharma 

This will hit Pulumi tomorrow after the Terraform AWS release tonight

Paul

**Comment by discovery-NukulSharma** [comment]
thank you Paul ( @stack72 )
