### ISSUE TITLE
Support MSK CreateSourceMapping for Lambda

### ISSUE THREAD

**Issue by levimichael** [pulumi/pulumi-aws#1251]
Source mapping for MSK is needed to set up Lambda consumers for Kafka.

More details here: https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html

**Comment by CIII** [comment]
Looks like this may not be working 100% as expected. When I create an EventSourceMapping to an MSK topic my mapping shows the status: 

`PROBLEM: Connection error. Please check your event source connection configuration.`

For context my lambda is set with the same VPC as the MSK cluster and I confirmed the topic exists.
