### ISSUE TITLE
Import AWS role causes a panic

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#1252]
This was raised by a user trying to import an Amazon managed IAM policy, but when I tried with one I created and the error still occurred.

This was the error message that I received:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4a81a96]

goroutine 30 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).importResources(0xc000e84ca0, 0x5c10ac0, 0xc000ebbe30, 0xc023c98, 0xc000438640, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20201206-63899-1azabtx/pkg/resource/deploy/deployment_executor.go:459 +0x276
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc000e84ca0, 0x5c10ac0, 0xc000ebbe30, 0xc023c98, 0xc000438640, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20201206-63899-1azabtx/pkg/resource/deploy/deployment_executor.go:138 +0x1247
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
	/private/tmp/pulumi-20201206-63899-1azabtx/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x5c1b700, 0xc000438640, 0xc000e39540, 0x5c10ac0, 0xc000ebbe30, 0xc000ebbe01, 0xc000ed3660, 0xc00140cd20)
	/private/tmp/pulumi-20201206-63899-1azabtx/pkg/engine/deployment.go:251 +0x267
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
	/private/tmp/pulumi-20201206-63899-1azabtx/pkg/engine/deployment.go:237 +0x306
```

This happens on both `2.15.1` and `2.15.2`

It looks like this is only for importing IAM roles right now. I tried importing an S3 bucket and it worked fine.

**Comment by othatbrian** [comment]
To be pedantic, I was importing an IAM _policy_.

**Comment by othatbrian** [comment]
Ah, I reread, and your comment mentioned `policy` first and `role` later.

**Comment by stack72** [comment]
Hi @othatbrian 

My apologies you are seeing this issue - I just opened a PR that fixes the problem and it will be made available in Pulumi v2.15.4 later today

Paul

**Comment by othatbrian** [comment]
Is there an expected "availability" time for 2.15.14? I see that 2.15.2 and 2.15.3 both went out yesterday, but I'm not not picking up 2.15.4.

**Comment by stack72** [comment]
Hi @othatbrian 

I am working on preparing the release now - so it will be out today!

Paul

**Comment by leezen** [comment]
@othatbrian In case you didn't see, 2.15.4. was released earlier today.
