### ISSUE TITLE
ECS load balancer with two listeners not working well

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-aws#1258]
I'm trying to run EventStore on ECS with docker and creating the corresponding infrastructure with Pulumi.

To do so, I need to create one Network load balancer (NBL) with two listener, one for port 2113 and another for port 1113. 

In my pulumi implementation: 
- I create one awsx.lb.NetworkLoadBalancer. 
- I create two awsx.elasticloadbalancingv2.NetworkListener for ports 1113 and 2113.
- I create one awsx.ecs.Cluster.
- And finally, I create one awsx.ecs.FargateService and I assign to it my cluster and my two listeners as portMappings for EventStore docker container.

The issue is that pulumi creates one NBL with two listeners (for ports 1113 and 2113) and two target groups, but only one register ECS instances automatically. I've observed it only works with the last one you assign in portMappings list.

For other target groups, you have to register new instance IPs manually. But that is not practical, because ECS task instances are created and destroyed automatically, so all target groups should be able to register or deregister instances automatically.

I also created a thread on AWS Developer Forums regarding this issue, because I'm not sure if it can be something working wrong on AWS https://forums.aws.amazon.com/thread.jspa?messageID=944626

**Comment by pierskarsenbarg** [comment]
I've managed to reproduce this with a simple example: https://github.com/pierskarsenbarg/pulumi-demos/tree/main/nlb-fargate

I think it's this provider rather than the awsx one because if you look at the output where my transformation writes out the container details including the portmappings.

**Comment by RXminuS** [comment]
Exact same problem and observations, only the last portMapping is actually registered.

**Comment by RXminuS** [comment]
@lukehoban would this be better placed in the `pulumi/pulumi-awsx` repo?
