### ISSUE TITLE
AWS MQ now supports RabbitMQ engine

### ISSUE THREAD

**Issue by SebastianGogoasa** [pulumi/pulumi-aws#1262]
File: [docs/reference/pkg/aws/mq/broker.md](https://www.pulumi.com/docs/reference/pkg/aws/mq/broker/)

According to AWS (Nov. / 2020 announcement), RabbitMQ engine is now available: https://aws.amazon.com/about-aws/whats-new/2020/11/announcing-amazon-mq-rabbitmq/ and also https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/broker-engine.html

PS: Sorry, not sure if this supposed to be submitted on Issues

**Comment by leezen** [comment]
Tracked upstream in https://github.com/hashicorp/terraform-provider-aws/issues/16030

**Comment by stack72** [comment]
This has been fixed and released - sorry for the lack of response here

Paul
