### ISSUE TITLE
Imported ElastiCache cluster does not produce diff for values not defined in code.

### ISSUE THREAD

**Issue by crielly** [pulumi/pulumi-aws#1265]
I've imported an ElastiCache cluster using `pulumi import`. That process seems to work fine - however, when I then run a preview, diffs are not shown for values not defined in my code.

```
package main

import (
	"github.com/crielly/pulumi-lib/getters"
	"github.com/pulumi/pulumi-aws/sdk/v3/go/aws/elasticache"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		sv := config.New(ctx, "stack")
		ev := config.New(ctx, "env")

		_, err := elasticache.NewCluster(ctx, "main", &elasticache.ClusterArgs{
			Engine:        pulumi.String("redis"),
			EngineVersion: pulumi.String("5.0.6"),
			NodeType:      pulumi.String("cache.t2.small"),
			ClusterId:     getters.GetStringWithDefault(*sv, "clusterid", "somesessionstore"),
			NumCacheNodes: pulumi.IntPtr(1),
			Tags: pulumi.StringMap{
				"Name":          getters.GetStringWithDefault(*sv, "clusterid", "somesessionstore"),
				"pulumi":        pulumi.String("true"),
				"environment":   pulumi.String(ev.Get("name")),
			},
		})
		if err != nil {
			return err
		}
		return nil
	})
}

```
As examples, the cluster I am importing has a non-default security group, parameter group etc. If I define these in code with an incorrect value, it'll produce a diff. However, since I have not yet defined them here, a preview shows no diffs.

Naturally, showing these diffs is very important for confidently adopting existing resources.

I did try a `pulumi refresh` which did not change this behaviour.

**Comment by jaxxstorm** [comment]
We discussed this internally, and the suspicion here is that these are optional computed properties, which mean that removing them provides no diff.

I'm going to ask @stack72 for more info, but in the meantime, can I assume setting these values manually will have the desired effect?

**Comment by crielly** [comment]
That's correct. If I specify a value, a diff is produced as expected.

This is mostly just a quality of life thing - having the diff would increase my confidence that the code I write has been reconciled with reality and I can reproduce the resource from code.

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
