### ISSUE TITLE
Cannot change finalSnapshotIdentifier aurora db cluster

### ISSUE THREAD

**Issue by adrianleonmorell** [pulumi/pulumi-aws#1276]
Hi guys, I'm trying to add the **finalSnapshotIdentifier** property to an aws.rds.Cluster that already contains the property **skipFinalSnapshot** to false and I'm getting an error:
Difference confirmation picture:
![aurora-changes-diff](https://user-images.githubusercontent.com/17031755/102776067-5ecf6800-438e-11eb-9099-ea8bf1ed6277.PNG)
Command output after confirmation:
![aurora-changes-output](https://user-images.githubusercontent.com/17031755/102776092-6989fd00-438e-11eb-9e3c-485e61888c46.PNG)

I would expect that modification to be allowed since a cluster created with skipFinalSnapshot=false fails to delete if the finalSnapshotIdentifier is not set. Another important thing is that making skipFinalSnapshot required when skipFinalSnapshot=false would have avoided the issue.

I'm using Typescript and these are the dependencies on my package.json
![image](https://user-images.githubusercontent.com/17031755/102776759-a276a180-438f-11eb-8a0e-695ceaf37c83.png)

Thanks in advance

**Comment by komalali** [comment]
@adrianleonmorell I followed the steps you described and wasn't able to get a repro, so I suspect there may be something deeper at play here. Can you share some more information or a code sample? From your screenshots it looks like there are other resources in the stack, it would be helpful to understand if there are any inter-resource dependencies here.

To clarify, these are the steps I took:
1. Create a cluster:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const cluster = new aws.rds.Cluster("my-cluster", {
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"],
    databaseName: "mydb",
    engine: "aurora-mysql",
    masterPassword: "foobarbaz",
    masterUsername: "bar",
});

export const identifier = cluster.finalSnapshotIdentifier;
export const skipFinalSnapshot = cluster.skipFinalSnapshot

```
2. Run pulumi up:
<img width="876" alt="Screen Shot 2020-12-22 at 1 21 39 PM" src="https://user-images.githubusercontent.com/24326455/102934267-a3273a80-4458-11eb-8277-4e489e06d676.png">

3. Add a finalSnapshotIdentifier:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const cluster = new aws.rds.Cluster("my-cluster", {
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"],
    databaseName: "mydb",
    engine: "aurora-mysql",
    masterPassword: "foobarbaz",
    masterUsername: "bar",
    finalSnapshotIdentifier: "some-identifier"
});

export const identifier = cluster.finalSnapshotIdentifier;
export const skipFinalSnapshot = cluster.skipFinalSnapshot

```
4. Run pulumi up:
<img width="894" alt="Screen Shot 2020-12-22 at 1 23 45 PM" src="https://user-images.githubusercontent.com/24326455/102934425-eed9e400-4458-11eb-8e36-32b488590fff.png">

**Comment by adrianleonmorell** [comment]
Hi @komalali, I have other parameters, I will send you the full example.
Thanks for the quick response.

**Comment by adrianleonmorell** [comment]
Hi @komalali, sorry for the delayed response, I was on vacations :blush:

I could reproduce the error with this cluster:
![image](https://user-images.githubusercontent.com/17031755/104755196-7239dd00-575a-11eb-8f73-9cfdef947c13.png)

Region: eu-west-1
Pulumi version: 2.16.0

Thanks

**Comment by komalali** [comment]
@adrianleonmorell Thanks for sending that along. I successfully repro the error with the code you provided 🎉!
That should help me get to the bottom of this.

**Comment by komalali** [comment]
I think this bug is related to `ignoreChanges`. I still need to dig deeper, but I found that if you remove `ignoreChanges` from your code and list all 3 availability zones this error doesn't happen. Code below:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const resourcePrefix = "my-resource";

const cluster = new aws.rds.Cluster("my-cluster", {
    clusterIdentifier: `${resourcePrefix}-cluster`,
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"],
    engine: "aurora-mysql",
    engineVersion: "5.7.mysql_aurora.2.03.2",
    masterPassword: "password",
    masterUsername: "admin",
    skipFinalSnapshot: false,
    storageEncrypted: true,
    // finalSnapshotIdentifier: "some-identifier",
    tags: {
        "domain": "id",
        "tenant": "multitenant",
        "accessLevel": "private"
    },
});
```

**Comment by komalali** [comment]
Alright, looks like it was a bug with `ignoreChanges`! Thanks so much for your help repro-ing this @adrianleonmorell - we'll have a fix out once https://github.com/pulumi/pulumi-terraform-bridge/pull/317 makes it way out to the provider. In the meanwhile, you can get around this by specifying the 3 availability zones `availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"],` explicitly.

**Comment by adrianleonmorell** [comment]
Thanks for your help @komalali, I think that the 2 az is a requirement but it's great to be aware of the issue. I guess I will need to create a new cluster with the finalSnapshotIdentifier from the beginning but that's OK even though I was trying to avoid it.

**Comment by komalali** [comment]
Just to clarify, if you specify 2 AZs, AWS will automatically expand that to 3 zones. If you check your cluster in the AWS console or look at the outputs from `pulumi stack export`, you'll see that the AZs are actually 3 and not 2. There's a little more context on this issue: https://github.com/pulumi/pulumi-aws/issues/1086

Unless 3 zones are specified, the underlying tf provider will always try to replace because there's a mismatch between the 2 zones you have provided and the 3 that are the actual values. Once we get this fix rolled out to pulumi-aws you'll be able to use `ignoreChanges` if specifying 3 zones is not an option to get around this issue.

**Comment by komalali** [comment]
Another option is to just remove availability zones from the inputs altogether, as this will avoid the mismatch in availability zones and the existing AZs will be retained, avoiding the replacement. 

Here's an explanation of the underlying behavior from the tf aws provider and possible workarounds: https://github.com/hashicorp/terraform-provider-aws/issues/7307#issuecomment-457441633
