### ISSUE TITLE
Problem creating EKS cluster in python library

### ISSUE THREAD

**Issue by colearendt** [pulumi/pulumi-aws#1278]
### Problem description

I have had trouble creating an EKS cluster using the Pulumi Python library. There is not an example in the docs, and many iterations of varying parameters, computed / hardcoded values, etc. have all ended with:

```
error: aws:eks/cluster:Cluster resource 'training-eks-cluster' has a problem: Computed attribute cannot be set
```

One of the many variants I have tried:
```
eks_cluster = aws.eks.Cluster(
    'training-eks-cluster',
    role_arn = eks_role.arn,
    vpc_config = aws.eks.ClusterVpcConfigArgs(
      vpc_id= training_vpc.id,
      subnet_ids= [private1.id, private2.id]
    ),
)
```

Slack discussion: https://pulumi-community.slack.com/archives/C84L4E3N1/p1608570994454500

### Affected product version(s)

```
✗ pulumi version
v2.15.5
```

```
✗ pip freeze | grep pulumi
pulumi==2.15.6
pulumi-aws==3.21.0
pulumi-kubernetes==2.7.2
```

**Comment by stack72** [comment]
Hi @colearendt 

I know this doesn't fix the issue to make this easier to spot but remove:

`vpc_id= training_vpc.id,`

The subnets should be enough to set the vpc config

Paul

**Comment by leezen** [comment]
The underlying bug is tracked in https://github.com/pulumi/pulumi-terraform-bridge/issues/74.

**Comment by colearendt** [comment]
Thanks so much! Definitely missed that issue 😄
