### ISSUE TITLE
[ARM] unsupported plugin architecture: arm64

### ISSUE THREAD

**Issue by roderik** [pulumi/pulumi-aws#1283]
On an M1 Macbook, I previously installed the x86 version of pulumi out of homebrew. This worked without any issues.

Just before the new year, I noticed that the pulumi binary got an ARM bottle on Homebrew, so I uninstalled the x86 one and installed the arm one. The binary appears to work as well.

Using it via the automation API (arm nodejs) I noticed that after installing a new plugin, that it could not install it because (I assume) no arm version is available

```
[resource plugin aws-3.22.0] downloading from : unsupported plugin architecture: arm64
```

Workaround: Reverting back to the x86 version

**Comment by lukehoban** [comment]
Thanks for checking on this @roderik!  

We indeed have not started publishing ARM binaries for our providers, so this is expected for now. We intend to do this soon as part of https://github.com/pulumi/pulumi/issues/4868, though I'll leave this issue open as well for now.

**Comment by kherings** [comment]
@lukehoban - do you have an indication or idea about the time-frame? Would be so great to have this thing out of the way. 

> We indeed have not started publishing ARM binaries for our providers, so this is expected for now. We intend to do this soon as part of [pulumi/pulumi#4868](https://github.com/pulumi/pulumi/issues/4868), though I'll leave this issue open as well for now.

**Comment by stack72** [comment]
Hi @roderik / @kherings 

This is in progress right now - I am going to close this out so we can track the questions centrally

Paul
