### ISSUE TITLE
Launching instances on dedicated hosts

### ISSUE THREAD

**Issue by mkey0bc** [pulumi/pulumi-aws#1287]
When deploying an instance using an AMI registered with license manager the deployment fails.  When testing using the aws cli api call, it deploys fine.  When testing using the aws-sdk within Pulumi it deploys fine.  I have included the commands and code below that I have tested with as well as the error received at the bottom.

aws cli api call from command line: (works)
`aws ec2 run-instances --image-id 'ami-############' --instance-type 'm5.large' --subnet-id 'subnet-############'`

aws sdk call from Pulumi: (works)
`import * as awscli from 'aws-sdk'

const ecc2 = new awscli.EC2
const param = {
    InstanceType: 'r5.large',
    SubnetId: 'subnet-############',
    ImageId: 'ami-############',
    MaxCount: 1,
    MinCount: 1
}
ecc2.runInstances(param, function(err, data) {
    console.log(data)
})`

Code using Pulumi aws.ec2.Instance resource: (fails)
`        const sqlInstance = new aws.ec2.Instance(
            `${element.instanceName}-ec2`,
            {
                ami: amiId.apply((id) => id.value),
                instanceType: element.instanceArgs.instanceType,
                tags: element.instanceArgs.tags,
                keyName: element.instanceArgs.keyName,
                iamInstanceProfile: element.instanceArgs.instanceProfile,
                subnetId: element.SubnetID,
                vpcSecurityGroupIds: sqlSecurityGroupIds,
                userData: element.instanceArgs.userData,
                tenancy: 'host',
                rootBlockDevice: {
                    encrypted: true,
                    volumeType: 'io1',
                    iops: element.instanceArgs.iops
                },
                disableApiTermination: element.terminationProtection
            },
            { ignoreChanges: [] }
        );`

Error:
Error launching source instance: InvalidParameterValue: Invalid value 'When HostResourceGroupArn is specified, Placement GroupName cannot be set

**Comment by leezen** [comment]
@stack72 Could this be an upstream issue where with https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_instance.go#L2316 the group name is an empty string but not actually not set? I don't think I'm familiar enough with the way the upstream provider works.

**Comment by lukehoban** [comment]
This looks like the same issue as https://github.com/hashicorp/terraform-provider-aws/issues/16995, which has been fixed upstream and should now be available here as well.
