### ISSUE TITLE
Support for FARGATE and FARGATE Spot in Batch ComputeEnvironment

### ISSUE THREAD

**Issue by Ajay2002** [pulumi/pulumi-aws#1292]
At the moment it is not possible to specify the type of compute instance as `FARGATE` in the `ComputeEnvironment` under `aws.batch.ComputeEnvironment`, this issue has been raised on the Terraform GitHub ([issue](https://github.com/hashicorp/terraform-provider-aws/issues/16592)) and a branch has been created where this has been made possible. 

This is the [cli command](https://docs.aws.amazon.com/cli/latest/reference/batch/create-compute-environment.html)
 to spawn a new ComputeEnvironment and note that this change to incorporate FARGATE has to be reflected in the JobDefinition as well.

**Comment by viveklak** [comment]
Thanks for opening the issue. We will keep this open to track https://github.com/hashicorp/terraform-provider-aws/issues/16592.

**Comment by tlinhart** [comment]
Hey guys, as the [related issue](https://github.com/hashicorp/terraform-provider-aws/issues/16592) has just been closed, what can we do to make it into Pulumi? We are eager to test it out and use it in production :rocket:

**Comment by stack72** [comment]
Hey @tlinhart 

We will pick this up as soon as the new provider is released :)

So it will go out in a day or 2

Paul

**Comment by tlinhart** [comment]
@stack72 awesome news! We'll be more than happy to test it out.
