### ISSUE TITLE
Cloudformation stack parameters should accept more types

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-aws#1295]
The parameters for a `aws.cloudformation.Stack` are currently required to be a map of string to string ([see docs](https://www.pulumi.com/docs/reference/pkg/aws/cloudformation/stack/#parameters_nodejs)). Some cloudformation templates use other value types causing them to fail (e.g., "creating CloudFormation stack failed: ValidationError: Parameter 'MinInstancesInService' must be a number.").

```typescript
new aws.cloudformation.Stack(`my-gq`, {
    templateUrl: "https://s3.amazonaws.com/datomic-cloud-1/cft/732-8992/datomic-query-group-732-8992.json",
    capabilities: ["CAPABILITY_NAMED_IAM"],
    parameters: {
        "SystemName": "my-system",
        "InstanceType": "t3.medium",
        "KeyName": "kenny",
        "DesiredCapacity": 1
    }
})
```

**Comment by kennyjwilli** [comment]
Hi all. This is a pretty big blocker for us. Do you have a general idea of when this may get addressed?

**Comment by lukehoban** [comment]
I believe CloudFormation defines all arguments as being strings, and then processes those strings into other internal types based on the parameter definitions. But for example in the core CloudFormation APIs themselves, ParameterValue is a string.

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html

You should be able to pass `"1"` and have it work.

**Comment by kennyjwilli** [comment]
@lukehoban you are absolutely correct. Upon looking at the code written, I can now see the values in the `parameters` map passed to the `Stack` were written like this: ``"DesiredCapacity": `${args.desiredCapacity}` ``. That code was incorrect and resulted in CF stack updates being passed "Calling [toString] on an [Output<T>] is not supported. ..." The CF update would fail with an obtuse error. After correcting the call to ``"DesiredCapacity": pulumi.interpolate`${args.desiredCapacity}` ``, it all works as expected. Sorry for not noticing earlier. Thank you for the prompt response. Closing this as it is not an issue.
