### ISSUE TITLE
Lambda container update completes in Pulumi but not in AWS

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#1296]
If I update a container-based lambda there is a short time period where Pulumi thinks the update is complete, but AWS is still updating the lambda and no further updates can be made.

The error returned from AWS is:

```json
{
  "RespMetadata": {
    "StatusCode": 409,
    "RequestID": "d99c6311-6b61-4912-9e38-a1f9db830018"
  },
  "Message_": "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:{region}:{accountid}:function:{functionname}",
  "Type": "User"
}
```

I've managed to reproduce it using automation API: https://github.com/pierskarsenbarg/pulumi-scratchpad/tree/main/lambda-container-automation

**Comment by lukehoban** [comment]
I tried this repro a couple times and could not get this error to trigger.  The upstream provider is correctly waiting on the state to be "Active" - so if there were a remaining issue here, it would most likely be in the AWS service itself in reporting `Active` while in this state.  Though my belief is that this no longer repros.
