### ISSUE TITLE
feature request: support use localstack for testing

### ISSUE THREAD

**Issue by zjj2wry** [pulumi/pulumi-aws#1302]
- https://github.com/localstack/localstack

I want to run some e2e test in localstack, seems it already support in terraform (https://github.com/localstack/localstack#integration-with-terraform).

**Comment by komalali** [comment]
@stack72 do you have any context around this?

**Comment by lukehoban** [comment]
@zjj2wry The same kind of configuration as noted in the link you shared (which directs to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack) is possible in Pulumi via the equivalent settings noted in https://www.pulumi.com/docs/reference/pkg/aws/provider/.

**Comment by zjj2wry** [comment]
@lukehoban thanks
