### ISSUE TITLE
Issues in the type definition of Lambda handler context.

### ISSUE THREAD

**Issue by iam-yan** [pulumi/pulumi-aws#1314]
pulumi does not rely on aws-lambda types, and the type definition of Lambda handler context is different:

1. In aws doc and aws-lambda, `getRemainingTimeInMillis()` returns number, while in pulumi it returns string.

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/17c183b287efe9f95050150128cca68bf36b989a/types/aws-lambda/handler.d.ts#L106
https://github.com/pulumi/pulumi-aws/blob/d512d62694ce8f457f1af1232f6c42e28ac149d0/sdk/nodejs/lambda/lambdaMixins.ts#L109

2. aws-lambda kept the no-longer-documented properties and mark them with @deprecated, while pulumi does not include them.
```
// Functions for compatibility with earlier Node.js Runtime v0.10.42
    // No longer documented, so they are deprecated, but they still work
    // as of the 12.x runtime, so they are not removed from the types.

    /** @deprecated Use handler callback or promise result */
    done(error?: Error, result?: any): void;
    /** @deprecated Use handler callback with first argument or reject a promise result */
    fail(error: Error | string): void;
    /** @deprecated Use handler callback with second argument or resolve a promise result */
    succeed(messageOrObject: any): void;
    // Unclear what behavior this is supposed to have, I couldn't find any still extant reference,
    // and it behaves like the above, ignoring the object parameter.
    /** @deprecated Use handler callback or promise result */
    succeed(message: string, object: any): void;
```

These differences lead to incompatible issues when using together with apollo-server-lambda.

**Comment by cbisbee-rapidai** [comment]
Issue #2 referenced above with `done`, `fail`, `succeed`  not being included also causes issues when trying to use Middy.
