### ISSUE TITLE
Page does not exist - https://www.pulumi.com/docs/reference/pkg/python/pulumi_aws/ssoadmin

### ISSUE THREAD

**Issue by charudut** [pulumi/pulumi-aws#1331]
There is a link to https://www.pulumi.com/docs/reference/pkg/python/pulumi_aws/ssoadmin in https://www.pulumi.com/docs/reference/pkg/aws/ssoadmin/ but this page does not exist.

**Comment by leezen** [comment]
References to language-specific API documentation has been removed and this should no longer be the case.
