### ISSUE TITLE
External Id is not required but cognito.UserPoolClientAnalyticsConfiguration.externalId is not optional

### ISSUE THREAD

**Issue by juuyan** [pulumi/pulumi-aws#1334]
![image](https://user-images.githubusercontent.com/48427014/106380239-c7791e00-63eb-11eb-8e5e-d5075d69faf3.png)
![image](https://user-images.githubusercontent.com/48427014/106380243-d233b300-63eb-11eb-9b26-f22df3a46346.png)

**Comment by leezen** [comment]
This was fixed in the latest version of the provider.
