### ISSUE TITLE
Question: how does the`forceDestroy` on `aws.s3.Bucket` work?

### ISSUE THREAD

**Issue by adrians5j** [pulumi/pulumi-aws#1337]
I have an S3 bucket (`aws.s3.Bucket`), with `forceDestroy: true` but it seems this only works when files were deployed (like .e.g. a React app build files), but not if the files were created by the application user (like uploading a file).

So what I wanted to confirm is... the `forceDestroy` will only delete files that were deployed via Pulumi, and not the rest?

**Comment by doitadrian** [comment]
I guess the only way is to just destroy files by yourself, using the AWS SDK.

I will try it.

**Comment by doitadrian** [comment]
P.S. It seems this is already mentioned here - https://github.com/hashicorp/terraform-provider-aws/issues/428

**Comment by lukehoban** [comment]
Forcedestory will remove all files in the bucket.
