### ISSUE TITLE
Non-deterministic ordering of IAM policy items causes unexpected diff

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-aws#1338]
It looks like AWS returns IAM policy documents with inconsistently ordered `Service` lists, which results in a "diff" that ultimately causes `pulumi refresh --expect-no-changes` fail, even when the items in those lists haven't changed (aside from their ordering). For example, here's what I see when I request the same role twice with the AWS CLI:  

```
$ aws iam get-role --role-name lambdaEdgeRole-4840406
{
    "Role": {
        ...
        "AssumeRolePolicyDocument": {
            ...
            "Statement": [
                {
                    ...
                    "Principal": {
                        "Service": [
                            "lambda.amazonaws.com",
                            "edgelambda.amazonaws.com"
                        ]
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        }
    }
}

$ aws iam get-role --role-name lambdaEdgeRole-4840406
{
    "Role": {
        ...
        "AssumeRolePolicyDocument": {
            ...
            "Statement": [
                {
                    ...
                    "Principal": {
                        "Service": [
                            "edgelambda.amazonaws.com",
                            "lambda.amazonaws.com"
                        ]
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        }
    }
}
```

And the resulting diff:

![image](https://user-images.githubusercontent.com/274700/106535280-c0651500-64aa-11eb-9552-6c76fa745c3c.png)

Seems like Ideally, we'd compute handle this as unchanged, since the actual content of the policy hasn't changed.

**Comment by stack72** [comment]
We believe this has been fixed @cnunciato 

Going to close this out - let me know if that's not the case
