### ISSUE TITLE
ECS Container appears to be missing logConfiguration.secretOptions

### ISSUE THREAD

**Issue by loganyott** [pulumi/pulumi-aws#1345]
I'm trying to setup an integration for `awsfirelens` on an ECS Fargate Container. I need to specify an API key in my log configuration options. 

From what I can tell, AWS documentation suggests there's a `secretOptions` property that can be passed to `logConfiguration` for the container definition: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-secretOptions
However, this doesn't exist on the TS typings here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/ecs/container.ts#L163
If you look at the definition for `Secret`, you'll even see the `secretOptions` property referenced.

Pulumi is still a little magical for me, is this just a matter of updating the Container type definition or is there something else I am missing?

Thank you!

**Comment by loganyott** [comment]
FWIW, it appears that `secretOptions` do pass through correctly from some field testing (I was trying to set this up for DataDog logging)

```
logConfiguration: {
    logDriver: 'awsfirelens',
        options: {
        Name: 'datadog',
            Host: 'http-intake.logs.datadoghq.com',
            TLS: 'on',
            dd_service: tags.service,
            dd_source: 'ecs',
            provider: 'ecs',
            compress: 'gzip',
    },
    secretOptions: [{ // truly secret apparently
        name: 'apikey',
        valueFrom: ddApiKey,
    }],
} as any
```
![Screen Shot 2021-02-12 at 5 30 38 PM](https://user-images.githubusercontent.com/4369081/107836203-71946680-6d59-11eb-921e-4a48ae0effa8.png)

**Comment by stack72** [comment]
I can see this was added - https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/ecs/container.ts#L175 - sorry for not posting back and closing this issue sooner

Paul
