### ISSUE TITLE
Cannot programatically get the AWS region from config file

### ISSUE THREAD

**Issue by sandhujasmine** [pulumi/pulumi-aws#1347]
I have this stack config:
```
config:
  aws:region: us-west-2
  test:regions:
  - us-west-1
  - us-west-2
```
I can retrieve the config value from the CLI.
```
$ pulumi config get aws:region
us-west-2
```
But if I try to retrieve from python, it returns a None:
```
import pulumi

config = pulumi.Config()
default_region = config.get_object("aws:region")
print(default_region)
```
I've tried various ways and the `default_region` is always None. The list of regions defined for the `test` stack works fine but I can't access the `aws:region` key programatically. Wondering what I'm doing wrong?

**Comment by stack72** [comment]
Hi @sandhujasmine 

You need to load the "aws" config namespace before you can do it

e.g. 

```
import pulumi

config = pulumi.Config("aws")
default_region = config.get_object("region")
print(default_region)
```

**Comment by sandhujasmine** [comment]
That works - thanks @stack72 
I thought I tried various things but this works so I clearly must've missed it!

**Comment by stack72** [comment]
Sorry we didn't make this more clear
