### ISSUE TITLE
Some top-level EC2 functions are in the aws namespace (TypeScript)

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi-aws#1352]
Some functions built from data sources in Terraform's EC2 package have been put in pulumi-aws' top-level namespace.
I'm not au fait with all the Terraform modules and data sources, but I see at least three: Terraform's `aws_ami`, `aws_ami_ids` and `aws_eip` have become Pulumi's `aws.getAmi`, `aws.getAmiIds` and `aws.getElasticIp`. I expect to see these functions in the ec2 namespace: `aws.ec2.getAmi`, `aws.ec2.getAmiIds` and `aws.ec2.getElasticIp`.

There are only 9 top-level data sources in the Terraform AWS module, but currently 15 functions show up in VSCode when I view the IntelliSense pop-up after typing `aws.get`. So there may be  a few more errant functions to track down..

**Comment by pgavlin** [comment]
I think that we could duplicate the function definitions into the `ec2` namespace (removing them from the top-level namespace would be a breaking change that we don't want to take). I'm not entirely sure that we have support for that in `pulumi-terraform-bridge`.
