### ISSUE TITLE
Get an existing Load Balancer based on tags or other means. 

### ISSUE THREAD

**Issue by seivan** [pulumi/pulumi-aws#1353]
Edit: Could someone move this to AWSX/Kubernetes as its related to the load balancers created with EKS. 

Looking at the [documentation](https://www.pulumi.com/docs/reference/pkg/aws/lb/getloadbalancer/#using) for ` GetLoadBalancer` I can't tell if `GetLoadBalancerArgs`takes optional values since both `arn` and `name` are defined as `string` as opposed to say `string?` or `optional<string>`.

That being said there is a `tags` key, so I was wondering if it's possible to fetch a load balancer using just tags? 

This is so something like this can be used.

```typescript
const www = new aws.route53.Record("www", {
    zoneId: aws_route53_zone.primary.zone_id,
    name: "www.example.com",
    type: "A",
    ttl: "300",
    records: [aws_eip.lb.public_ip],
});
```

or
```typescript
const www = new aws.route53.Record("www", {
    zoneId: aws_route53_zone.primary.zone_id,
    name: "example.com",
    type: "A",
    aliases: [{
        name: main.dnsName,
        zoneId: main.zoneId,
        evaluateTargetHealth: true,
    }],`
```

Can be possible when the Load Balancer is created using Kubernetes, though I am open for suggestions on how to create a load balancer using `crosswalk/awsx` via Pulimi and make it work with EKS.

**Comment by pgavlin** [comment]
> That being said there is a tags key, so I was wondering if it's possible to fetch a load balancer using just tags?

Unfortunately, it is not possible to fetch a load balancer using tags alone. It might be possible to use the AWS SDK to search for the load balancer using its tags, then transform the result into an ID that is appropriate for use with `GetLoadBalancer`.

**Comment by seivan** [comment]
@pgavlin Would you be open to a pull request adding this feature? 
I don't see how this isn't a bigger issue, I'd almost say it's a bug. 
Not being able to access part of the infrastructure necessary to setup a EKS cluster, is a bit of a concern. 
I'd say ALB is almost necessary as both NLB and ELB would use instance type load balancing, where some nodes might not run a specific pod and fail health checks.

**Comment by leezen** [comment]
@seivan What @pgavlin is pointing out is that the `GetLoadBalancer` invocation doesn't support retrieving via only tags. This is how the call is designed to work (to use either an ARN or a name). You could, as he suggests, use the AWS SDK to perform the search you want to do, so there's nothing preventing you from accessing the part of the infrastructure you want to use.

**Comment by seivan** [comment]
@leezen So why is tags part of the function definition? 
Just to be clear, it's either name **OR** ARN, correct?

**Comment by leezen** [comment]
Correct, name or ARN. In some cases, additional parameters are available in arguments for filtering purposes to narrow down the resource.
