### ISSUE TITLE
Regression with Pulumi.Aws 3.28.1 for .net

### ISSUE THREAD

**Issue by AliBazzi** [pulumi/pulumi-aws#1354]
## Expected Behavior
when doing Pulumi up in a container in an EC2 instance who has IAM assume profile to access the AWS environment, the Pulumi runtime should be able to pick up the access key id and secret.

## Current Behavior
facing the following error by using 2.8.1:

```
Diagnostics:
--
  | aws:dynamodb:Table (Development-***):
  | error: 1 error occurred:
  | * error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
  |  
  | Please see https://registry.terraform.io/providers/hashicorp/aws
  | for more information about providing credentials.
  |  
  | Error: NoCredentialProviders: no valid providers in chain. Deprecated.
  | For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

## Steps to Reproduce

1. Create Pulumi project with .net that targets Pulumi.Aws provider version 3.28.1
2. use pulumi .net sdk container with tag "latest"
3. do pulumi up within the container who has access to the EC2 instance that has IAM assume role profile
4. you will see the previous error

## Context (Environment)
Repeating the same steps above with version `3.28.0` and prior will have the expected outcome, so it looks like there is a regression -not sure what is it- introduced with `3.28.1`

**Comment by AliBazzi** [comment]
Hi @stack72 

I can confirm that your suggestion worked for me.

Thanks !

**Comment by stack72** [comment]
Hey @AliBazzi 

I'm delighted to hear that - as a follow up I'm going to add some extra documentation to our README for that repo to suggest these types of things

My apologies again for this

Paul

**Comment by AliBazzi** [comment]
No worries, thanks for your proactiveness
