### ISSUE TITLE
RouteAlreadyExists AWS 'up' error

### ISSUE THREAD

**Issue by ronoc** [pulumi/pulumi-aws#1372]
I have not touched any of the route tables on an existing stack. But when I try to deploy a redis instance within the stack the update fails, because of 

```
aws:ec2:RouteTable (axiom-private-subnet-3-routetable-cloud-development):
    error: 1 error occurred:
    	* updating urn:pulumi:axiom-cloud::Development::aws:ec2/routeTable:RouteTable::axiom-private-subnet-3-routetable-cloud-development: 1 error occurred:
    	* error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
    	status code: 400, request id: 6c24f1c6-ca0d-48aa-a340-54a5e99a2cb5
```

This happened before previously,  when I did an update that was even adding anything to the stack.

**Comment by leezen** [comment]
Could you please provide more diff information along with the code that creates your route tables/network to help debug?

**Comment by stack72** [comment]
Hi,

As there has been no further details added here, I am going to close this out as a stale issue. If this is still a problem, please let us know and we can try and help

Paul
