### ISSUE TITLE
Upon import elastic search domain import code is very sparse

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#1380]
## Expected behavior

The import is successful and the code snippet provided has all the relevant inputs in it.

## Current behavior

The import is successful but the inputs available in the code snippet returned to the user are sparse. The inputs are there in the stack if you export it and view it, but not in the code, similar to pulumi/pulumi-cloudflare#139

## Steps to reproduce

1. Attempt to import an elastic search domain
2. View code snippet on the screen

**Comment by stack72** [comment]
We believe this has been fixed with the latest import improvements
