### ISSUE TITLE
Enable x-ray tracing in Step Functions

### ISSUE THREAD

**Issue by jacbar** [pulumi/pulumi-aws#1388]
AWS allows to enable X-Ray tracing for step functions: [https://docs.aws.amazon.com/step-functions/latest/dg/concepts-xray-tracing.html](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-xray-tracing.html) 

but the option to enable it is missing in pulumi-aws package api: 
[https://www.pulumi.com/docs/reference/pkg/aws/sfn/statemachine/ ](https://www.pulumi.com/docs/reference/pkg/aws/sfn/statemachine/ )

Can you add it in, or provide other way for enabling x-ray tracing in state functions with pulumi?

Thanks,
Jacek

**Comment by justinvp** [comment]
Upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/15430
