### ISSUE TITLE
 The unencrypted value of a SecureString will be stored in the raw state as plain-text.

### ISSUE THREAD

**Issue by seivan** [pulumi/pulumi-aws#1392]
https://github.com/pulumi/pulumi-aws/blob/e5caa37d17f72c31a8b6a51a6bda4d314ab07851/sdk/nodejs/ssm/parameter.ts#L53

Is this accurate? I thought you guys used the default CMK to encrypt secrets?

**Comment by stack72** [comment]
Hi @seivan 

You are correct - this is misleading - I will update this and get it fixed in our SDK docs

Paul
