### ISSUE TITLE
Support for configuring of Private ECR *Registry*

### ISSUE THREAD

**Issue by roitalpaz** [pulumi/pulumi-aws#1400]
We want to configure permissions and replications for the entire ECR on an AWS account. but Pulumi doesn't support this feature.
Note: I mean registry and not repository.

Below there is no ECR Registry object.
https://www.pulumi.com/docs/reference/pkg/aws/ecr/

AWS documentation about the feature:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry-settings.html

**Comment by t0yv0** [comment]
https://www.pulumi.com/registry/packages/aws/api-docs/ecr/registrypolicy/ is now available. Let us know if that does not do what you want.
