### ISSUE TITLE
Support for RetryPolicy and DeadLetterConfig in aws.cloudwatch.EventTarget

### ISSUE THREAD

**Issue by aviflax** [pulumi/pulumi-aws#1406]
I recently started using Pulumi to provision and maintain some EventBridge (née CloudWatch Events) resources, including an `EventTarget`. I was slightly baffled as to why the API didn’t seem to support setting a retry policy and dead letter queue, as they’re supported by [the AWS API](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html).

Just now it occurred to me to check whether the Terraform AWS provider supports these properties, and I found hashicorp/terraform-provider-aws#17240 which added them — but only just about 25 days ago. OK, so that explains things.

My request is that this project be updated accordingly to add support for these properties.

Also:

* If this is going to happen, any chance you could give me a guess as to the time frame?
* Is there any kind of mechanism in Pulumi for setting “custom” properties that I could use as a workaround, in the meantime?

Thanks!

**Comment by stack72** [comment]
Hey @aviflax 

So they were actually added as part of pulumi-aws v3.30.0 (https://github.com/pulumi/pulumi-aws/blob/master/CHANGELOG.md#3300-2021-02-22)

I can see they are part of the SDK in that release

Please let me know if you see something different here

Paul

**Comment by aviflax** [comment]
Aha, I didn’t realize — that’s excellent. I updated and it worked great. Already applied. Thank you!

**Comment by stack72** [comment]
Wonderful - thanks for getting back to me so fast

Just a note, we try to update from the upstream provider in about a day max so we shouldn't be too far behind

P.
