### ISSUE TITLE
Missing name field for Elasticache NewReplicationGroup

### ISSUE THREAD

**Issue by themoah** [pulumi/pulumi-aws#1420]
afaiu, pulumi always adds suffix to create an uniq name, but we can override this behaviour with providing the full name by ourselves.

## Expected behavior
Creating Elasticache cluster with https://pkg.go.dev/github.com/pulumi/pulumi-aws/sdk/v3/go/aws/elasticache#ReplicationGroupArgs doesn't provide such option. 

## Current behavior
It breaks internal naming convention, as also import doesn't work (separate problem).
```
    error: aws:elasticache/replicationGroup:ReplicationGroup resource '%redacted_cluster_name%' has a problem: ExactlyOne: "number_cache_clusters": one of `cluster_mode,number_cache_clusters` must be specified. Examine values at 'ReplicationGroup.NumberCacheClusters'.
    error: aws:elasticache/replicationGroup:ReplicationGroup resource '%%redacted_cluster_name%' has a problem: ExactlyOne: "cluster_mode": one of `cluster_mode,number_cache_clusters` must be specified. Examine values at 'ReplicationGroup.ClusterMode' 
```

**Comment by stack72** [comment]
Hi @themoah 

Are you saying that in an elasticache.ReplicationGroup, there is no way to disable the autonaming?

Paul

**Comment by themoah** [comment]
@stack72 yes, exactly. Can't disable adding suffix.

**Comment by stack72** [comment]
Hey @themoah 

So Circling back here - the value you'd actually have to set for this would be:

```
ReplicationGroupId
```

I've just tested this and I can turn off the auto-naming for the cluster using this field

Paul

**Comment by stack72** [comment]
Please let me know if there are any other issues and I can reopen this

Paul

**Comment by themoah** [comment]
@stack72 thanks, helped !
