### ISSUE TITLE
Region not read from profile configuration

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-aws#1422]
The `aws.Provider` has started refusing to read the `region` configuration for a `profile` set in `~/.aws/config`, while other values appear to be loaded fine.

I'm not 100% certain when this started happening, but I noticed on March 10th and I'm usually pretty up to date, sorry.

Basically just started getting this kind of error:

```
    Error: invocation of aws:iam/getRole:getRole returned an error: 1 error occurred:
    	* missing required configuration key "aws:region": The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
    Set a value using the command `pulumi config set aws:region <value>`.
```

when creating a `Provider` like this:

```
new Provider('blah', { profile: 'production' });
```

## Expected behavior
Should use `region` value specified in profile.

## Current behavior
Requires `region` be programmatically set in pulumi code, duplicating the configuration.

## Steps to reproduce
1. Configure a non-default profile in your `~/.aws/config`, it can be for the same account, role, keys, etc.
2. Create a `Provider` using _only_ that profile as above ☝🏻
3. Create or read a resource using that provider.
4. `pulumi up` 💥😢

## Context (Environment)
Recent usage is setting up cross-account assume role trust where the role is consistently named.

**Comment by mikhailshilkov** [comment]
@stack72 are you aware of any changes in this space?

**Comment by mikhailshilkov** [comment]
I tested it today with a 6.x version. Used this program:

```ts
import * as aws from "@pulumi/aws";

const p = new aws.Provider('blah', { profile: 'dev' });
const table = new aws.dynamodb.Table("tenants", {
  hashKey: "id",
  attributes: [{ name: "id", type: "S" }],
  readCapacity: 1,
  writeCapacity: 1,
}, {provider: p});
```

also checked that I don't have a region configured in my stack config.

The program deployed and the Table got created in the region from my `~/.aws/config`. I'll close the issue as fixed.
