### ISSUE TITLE
Support for AthenaEngineVersion option in Athena workgroups

### ISSUE THREAD

**Issue by pdpark** [pulumi/pulumi-aws#1424]
[Support for AthenaEngineVersion option in Athena workgroups](https://github.com/hashicorp/terraform-provider-aws/issues/17456)

**Comment by mikhailshilkov** [comment]
Hi @pdpark thank you for opening this. As soon as the upstream issue is resolved, we will automatically pick it up in the following release of the Pulumi provider. As there's nothing specific to be done here, I'll close the issue and let's track upstream.
