### ISSUE TITLE
`namePrefix` properties are not usable

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#143]
Many AWS TF resources expose `namePrefix` members.  These will use a user-provided prefix, and augment with randomness from the TF provider.

However, `namePrefix` and `name` cannot both be specified.  And we auto-specify `name` unless `name` itself has already been specified.

As a result, there is no way to pass the `namePrefix` property on these APIs (for example `LoadBalancer`, `TargetGroup`, etc.).

**Comment by lukehoban** [comment]
Feedback from @jen20 in offline discussion:

> Probably easiest to just strip them out if Pulumi already does the correct thing?

That's one option we should consider.

**Comment by pgavlin** [comment]
As long as a resource's `name` and `name_prefix` properties are marked as conflicting in its TF schema, the latter should in fact be usable: we no longer fill defaults that would conflict with existing properties.

**Comment by guitarrapc** [comment]
This is trouble when forcing update ASG like many terraform do.

> https://github.com/hashicorp/terraform-provider-aws/issues/13785#issuecomment-704177150
