### ISSUE TITLE
Enable envelope encryption inplace

### ISSUE THREAD

**Issue by segal90** [pulumi/pulumi-aws#1432]
AWS supports enabling envelope encryption on the existing cluster. It would be great if Pulumi supports this feature instead of recreating the whole cluster.
https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-eks-supports-adding-kms-envelope-encryption-to-existing-clusters/

## Affected feature

AWS clusters / envelope encrytion

**Comment by mikhailshilkov** [comment]
Hi @segal90 

Do you know if this is tracked in the upstream [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws)?

**Comment by segal90** [comment]
Hi @mikhailshilkov 

This one: https://github.com/hashicorp/terraform-provider-aws/issues/17952
This also looks related: https://github.com/hashicorp/terraform-provider-aws/issues/14866

**Comment by mikhailshilkov** [comment]
Great! As soon as those issues are fixed, we will port them to the Pulumi provider. I'll close this issue for now because there's nothing special we need to do here, let's track this upstream.

**Comment by stack72** [comment]
Hi @segal90 

So a quick note back on this - one of our customers desperately needed this feature so we worked with them to add it

It will go into the latest release of pulumi-aws which I am working on a PR for now

Paul
