### ISSUE TITLE
Magic functions can't use variables created outside function

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#1433]
I wanted to be able to use the lambda context and re-use the HTTP client that the AWS SDK sets up between invocations. Code can be found here: https://gist.github.com/pierskarsenbarg/a7b86d64cb3ccccac7dcbc55deb5caa4 (note the new SSM client being set up on [line 33](https://gist.github.com/pierskarsenbarg/a7b86d64cb3ccccac7dcbc55deb5caa4#file-magic-function-ts-L33)).

I think this might just be a "you can't do this using magic functions" but Pulumi shouldn't just hang.

## Expected behavior

Pulumi uses the "magic function" to create a lambda with the callback code in the main handler but the ssm client outside of the handler.

## Current behavior

Pulumi hangs when trying to deploy. [Verbose output here](https://github.com/pulumi/pulumi-aws/files/6263787/out.txt) (I stopped it running ten minutes after the last line in the log)

## Steps to reproduce

1. [Clone repo](https://github.com/pierskarsenbarg/ssm-magic-function)
2. Run `pulumi up`

**Comment by colin-williams** [comment]
I updated the dependencies and ran your program and looks like this has been resolved. I think this can be closed.

https://github.com/colin-williams/test-pulumi-aws-1433

```
Previewing update (test-other-magic):
     Type                                  Name                             Plan       
 +   pulumi:pulumi:Stack                   magic-function-test-other-magic  create     
 +   ├─ aws:ssm:Parameter                  myParam                          create     
 +   ├─ aws:s3:Bucket                      my-bucket                        create     
 +   │  ├─ aws:s3:BucketEventSubscription  docHandler                       create     
 +   │  │  └─ aws:lambda:Permission        docHandler                       create     
 +   │  └─ aws:s3:BucketNotification       docHandler                       create     
 +   ├─ aws:iam:Role                       docsHandlerRole                  create     
 +   ├─ aws:iam:RolePolicyAttachment       lambda-ssm                       create     
 +   └─ aws:lambda:Function                function                         create     
 
Resources:
    + 9 to create

Do you want to perform this update?  [Use arrows to move, enter to select, type to filter]
  yes
> no
```

As an aside:
I've been struggling to develop a more robust lambda via Pulumi / Typescript. I have an open bug https://github.com/pulumi/pulumi-aws/issues/1665 for "magic lambdas". But I think perhaps creating a seperate node application and importing it like: https://www.pulumi.com/blog/easy-serverless-apps-and-infrastructure-real-events-real-code/#approach2-manual-function-resources would be ideal. But I can't find a complete example. If you'd be interested in trying to pair up to produce some lambda example(s) feel free to reach out.

**Comment by colin-williams** [comment]
Updating (test-other-magic):
     Type                                  Name                             Status      
 +   pulumi:pulumi:Stack                   magic-function-test-other-magic  created     
 +   ├─ aws:s3:Bucket                      my-bucket                        created     
 +   │  ├─ aws:s3:BucketEventSubscription  docHandler                       created     
 +   │  │  └─ aws:lambda:Permission        docHandler                       created     
 +   │  └─ aws:s3:BucketNotification       docHandler                       created     
 +   ├─ aws:ssm:Parameter                  myParam                          created     
 +   ├─ aws:iam:Role                       docsHandlerRole                  created     
 +   ├─ aws:iam:RolePolicyAttachment       lambda-ssm                       created     
 +   └─ aws:lambda:Function                function                         created     
 
Outputs:
    bucketName: "my-bucket-a7a878f"

Resources:
    + 9 created

Duration: 1m5s
