### ISSUE TITLE
externalId should be optional on UserPoolSmsConfiguration.

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-aws#1434]
Minor issue, similar to #1334, except on `UserPoolSmsConfiguration`. See [AWS docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SmsConfigurationType.html#CognitoUserPools-Type-SmsConfigurationType-ExternalId).

## Expected behavior
`externalId` should be optional.

## Current behavior
`externalId` is required.

## Steps to reproduce
N/A

## Context (Environment)
N/A

## Affected feature
Creating/updating Cognito User Pools without External IDs for their SMS configuration.

**Comment by stack72** [comment]
This resource has since been deleted so we can close this issue

Paul
