### ISSUE TITLE
Read AWS SSO generated roles

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-aws#1460]
## Affected feature

AWS SSO provisions roles in your sub-accounts based on the permission sets with a dynamically generated name. Using `aws.iam.getRole` isn't currently capable of identifying these, as the roles have a name that could only be pattern matched and the roles have no tags, nor does SSO support tagging the provisioned roles.

The `terraform-aws-provider` has PRs open to support more methods to retrieve roles that would help with this: https://github.com/hashicorp/terraform-provider-aws/pull/18048 and https://github.com/hashicorp/terraform-provider-aws/pull/18585.

Would these be rapidly supported by `pulumi-aws`, or is this the sort of thing you'd handle without terraform?

**Comment by komalali** [comment]
This will be supported in pulumi as soon as the upstream tf provider supports it
