### ISSUE TITLE
AWS SDK 4.0.0 problems with Glue

### ISSUE THREAD

**Issue by manca-disc** [pulumi/pulumi-aws#1462]
Hi there,

We've just upgraded to the latest Pulumi and AWS SDK for Go. However, when we try to build our project we get the following error:

```
../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.0.0/go/aws/glue/init.go:49:8: undefined: Schema
```

Seems to be related to Glue adapter. What's the solution to this problem?

**Comment by stack72** [comment]
Hi @manca-disc 

my apologies for this - can you give me a small snippet of code that we can use to try and diagnose this? Or is this a case of just using a glue schema resource?

thanks

paul

**Comment by manca-disc** [comment]
Hi @stack72 ,

This seems to be related to usage of AWS Glue package as-is. For example, we use glue package to create a new job and a new workflow. Since upgrading to AWS 4.0.0 we started seeing this error.
Here's the code that we have for creating a new Glue job:

```
glue.NewJob(ctx, jobName, &glue.JobArgs{
		Name:            pulumi.StringPtr(jobName),
		Description:     pulumi.StringPtr(desc),
		RoleArn:         svcRole,
		GlueVersion:     pulumi.StringPtr("2.0"),
		WorkerType:      pulumi.StringPtr(workerType),
		NumberOfWorkers: pulumi.IntPtr(numberOfWorkers),
		ExecutionProperty: &glue.JobExecutionPropertyArgs{
			MaxConcurrentRuns: pulumi.IntPtr(maxConcurrentRuns),
		},
```

**Comment by stack72** [comment]
Hey @manca-disc 

Ok, I found the source of the issue here and it will be in a release this evening CET time

Sorry about that

Paul
