### ISSUE TITLE
Kinesis firehose instructions incomplete

### ISSUE THREAD

**Issue by ksapchuk** [pulumi/pulumi-aws#1468]
File: [themes/default/content/docs/reference/pkg/aws/kinesis/firehosedeliverystream.md](https://www.pulumi.com/docs/reference/pkg/aws/kinesis/firehosedeliverystream/)

The instructions for setting up kinesis firehose with an S3 destinations are incomplete. The kinesis firehose role needs permissions to write to the S3 bucket as documented here https://docs.aws.amazon.com/firehose/latest/dev/controlling-access.html#using-iam-s3

The s3 destination also appears to be deprecated with extendedS3 being the recommended replacement.
> This is the destination to where the data is delivered. The only options are s3 (Deprecated, use extendedS3 instead), extendedS3, redshift, elasticsearch, splunk, and httpEndpoint.

**Comment by komalali** [comment]
Hi, thanks for the issue!

Our examples and documentation are autogenerated from the upstream provider, so this isn't something that we control. And we do link to the firehose documentation for more in-depth guidance on using firehose. 

We also do have an example for the [extendedS3 destination](https://www.pulumi.com/docs/reference/pkg/aws/kinesis/firehosedeliverystream/#extended-s3-destination)
