### ISSUE TITLE
Why deprecated IAM is representing the right IAM Role?

### ISSUE THREAD

**Issue by Indosaram** [pulumi/pulumi-aws#1480]
https://github.com/pulumi/pulumi-aws/blob/1f1490c1b4b89e733b93054b4b140c0bd2d20864/provider/resources.go#L3205

I was following [this tutorial](https://www.youtube.com/watch?v=o-_pDWaGDNw), and I realized the actual IAM is not matching with the list of IAM in the SDK. I understand this is expected behavior.

So, the end users should use an enum `LAMBDA_FULL_ACCESS`, instead of `AWS_LAMBDA_FULL_ACCESS` which makes more sense? I am really confused.

**Comment by mikhailshilkov** [comment]
Hi @Indosaram 

Sorry for the confusion. Indeed, the old policy from the video has been deprecated since then, see this AWS announcement: https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation

You should use `LAMBDA_FULL_ACCESS` now.
