### ISSUE TITLE
DMS s3 endpoint extra_connection_attributes property is not set correctly when creating new endpoint

### ISSUE THREAD

**Issue by samurex** [pulumi/pulumi-aws#1491]
Hi, when I create new endpoint with engine_name='s3' and  extra_connection_attributes="dataFormat=parquet;" the endpoint  is created but ExtraConnectionAttributes is missing "dataFormat=parquet;". Interestingly this value is being saved correctly when endpoint is updated.

## Expected behavior
After endpoint is created with extra_connection_attributes="dataFormat=parquet;" the value is saved to ExtraConnectionAttributes in aws 

## Current behavior
Currently ExtraConnectionAttributes is created from S3Settings (which doesn't contain DataFormat property)

## Steps to reproduce
1. create a task with  engine_name='s3' and  extra_connection_attributes="dataFormat=parquet;
2. pulumi up
3. go to the console or run cli to retrieve ExtraConnectionAttributes

## Context (Environment)
We are not able to manage DMS with pulumi

## Affected feature
pulumi dms

**Comment by snikolakis** [comment]
Hello! Is there any update on that?

**Comment by lukehoban** [comment]
This appears to be due to https://github.com/hashicorp/terraform-provider-aws/issues/19501, https://github.com/hashicorp/terraform-provider-aws/issues/19667, https://github.com/hashicorp/terraform-provider-aws/issues/23506.  Once those are addressed upstream, the improvements will become available here as well.

**Comment by lukehoban** [comment]
I believe this was fixed by https://github.com/hashicorp/terraform-provider-aws/issues/19667.  There isn't a complete repro here to validate against, but if anyone is still seeing issues here, add a repro and we can reopen.
