### ISSUE TITLE
How to specify platform credential when importing an AWS SNS platform application?

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi-aws#1497]
I'm following [this page](https://www.pulumi.com/docs/reference/pkg/aws/sns/platformapplication/#import) to import an existing AWS SNS platform application. 

The command I ran is `pulumi import aws:sns/platformApplication:PlatformApplication my_dev arn:aws:sns:ap-northeast-1:123456789123:app/APNS_SANDBOX/my_dev`.

## Expected behavior
I expect pulumi to import the platform application smoothly without any problem.

## Current behavior
The problem I encountered with the command is 

```
Previewing import (etc):
     Type                            Name                    Plan       Info
 +   pulumi:pulumi:Stack             my_name-my_stack       create     1 error
 =   └─ aws:sns:PlatformApplication  my_dev                 import     2 errors

Diagnostics:
  pulumi:pulumi:Stack (my_name-my_stack):
    error: preview failed

  aws:sns:PlatformApplication (my_dev):
    error: aws:sns/platformApplication:PlatformApplication resource 'my_dev' has a problem: Missing required argument: The argument "platform_credential" is required, but no definition was found.. Examine values at 'PlatformApplication.PlatformCredential'.
    error: Preview failed: one or more inputs failed to validate
```
It seems that I should provide `platform_credential` in the import command. But where can I place the value of `platform_credential` when importing?

## Steps to reproduce

1. Create an AWS SNS platform application using AWS console.
2. Initialize a pulumi aws-python project.
3. Import the platform application using a command like `pulumi import aws:sns/platformApplication:PlatformApplication my_dev arn:aws:sns:ap-northeast-1:123456789123:app/APNS_SANDBOX/my_dev`

## Context (Environment)
I want to import an existing AWS SNS platform application so that I can configure it with pulumi.

My pulumi version is `3.2.1`

**Comment by leezen** [comment]
Though not directly solving the problem, I think we should consider showing both forms of import (both CLI-based and programmatic) to account for cases like this where I'm guessing the programmatic style will work because the inputs are explicitly set vs. inferred.

**Comment by lukehoban** [comment]
After work earlier this year to improve `pulumi import`, this is now just a warning:

```
  aws:sns:PlatformApplication (my_dev):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: aws:sns/platformApplication:PlatformApplication resource 'my_dev' has a problem: Missing required argument: The argument "platform_credential" is required, but no definition was found.. Examine values at 'PlatformApplication.PlatformCredential'.
```

However, it's still challenging to import this because AWS does not return the required input for this `platformCredential` (for security reasons I expect).  See https://github.com/hashicorp/terraform-provider-aws/issues/27423#issuecomment-1289436623 for some available workarounds.

But nothing more that we can do in Pulumi here given AWS behaviour - so will close this out.
