### ISSUE TITLE
Where can I get the value of `platform_principal` when creating a `aws.sns.PlatformApplication` with `platform="APNS_SANDBOX"`?

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi-aws#1498]
I'm following [this page](https://www.pulumi.com/docs/reference/pkg/aws/sns/platformapplication/#platform_principal_python) to create a platform application using python.

Here's the code I ran:

```
apns_application = aws.sns.PlatformApplication("apnsApplication",
    platform="APNS_SANDBOX",
    platform_credential="<APNS PRIVATE KEY>",
    platform_principal="<APNS CERTIFICATE>")
```
I'm not sure what I should put in `platform_principal`.

The [CreatePlatformApplication page](https://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformApplication.html) says that 

> For `APNS` and `APNS_SANDBOX`, `PlatformPrincipal` is `SSL certificate` and `PlatformCredential` is `private key`.

But where can I find `SSL certificate` when I create a platform application?

I don't see anything like `SSL certificate` when I create a platform application through AWS console.

The only thing I need when creating through AWS console are a `*.p12` file and a certificate password.

**Comment by lblackstone** [comment]
Here's some info that might be helpful: https://docs.aws.amazon.com/sns/latest/dg/sns-prerequisites-for-mobile-push-notifications.html

This issue isn't specific to Pulumi, so I'd suggest asking in the [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=72) or our [Community Slack](https://slack.pulumi.com/) in case someone there knows.
