### ISSUE TITLE
[aws.ses] Support SES v2 ConfigurationSet fields

### ISSUE THREAD

**Issue by ceefour** [pulumi/pulumi-aws#1506]
## Affected feature

SES v2 has new ConfigurationSet fields, see https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateConfigurationSet.html .

Specifically:

1. `DeliveryOptions.SendingPoolName`
2. `ReputationOptions.LastFreshStart`
3. `SuppressionOptions.*`
4. `Tags`
5. `TrackingOptions.*`

Upstream: https://github.com/hashicorp/terraform-provider-aws/issues/14320

**Comment by mikhailshilkov** [comment]
The upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/14320 has been resolved as fixed, so I'll close this issue too. Please report a new issue if the problem occurs again.
