### ISSUE TITLE
Importing Existing AWS users loginProfile doesn't work

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-aws#1512]
Importing Existing AWS users loginProfile doesn't work whether you import via
[UserProfile Import](https://www.pulumi.com/docs/reference/pkg/aws/iam/userloginprofile/#import) or via [import resource options](https://www.pulumi.com/docs/intro/concepts/resources/#import) with ignoreChanges
## Steps to reproduce

1. git clone and cd into the directory
 ```
 git clone git@github.com:tusharshahrs/pulumi-homelab.git
 cd https://github.com/tusharshahrs/pulumi-homelab/tree/master/aws-userprofile-import-ts
```

2. Create the following iam user in the aws console: **demotest-forimport**.  You can name your user whatever you want. Screen shot of [demotest-forimport](https://share.getcloudapp.com/X6uABAYw)

3. Update your index.json to match the user that you created. For example, the `user`, `pgpkey`, and the `import` are all updated to `demotest-forimport`

4. run `pulumi up` and the following error will be thrown.
```

     pulumi up
     Previewing update (dev)

     View Live: https://app.pulumi.com/myuser/aws-userprofile-import-ts/dev/previews/4a5abd4e-8910-4cdb-8493-359f9de6263f

         Type                         Name                           Plan       Info
         pulumi:pulumi:Stack          aws-userprofile-import-ts-dev             1 error
     =   └─ aws:iam:UserLoginProfile  UserLoginProfile               import     2 errors
     
     Diagnostics:
     pulumi:pulumi:Stack (aws-userprofile-import-ts-dev):
         error: preview failed
     
     aws:iam:UserLoginProfile (UserLoginProfile):
         error: aws:iam/userLoginProfile:UserLoginProfile resource 'UserLoginProfile' has a problem: Missing required argument: The argument "pgp_key" is required, but no definition was found.. Examine values at 'UserLoginProfile.PgpKey'.
         error: Preview failed: one or more inputs failed to validate
```

Expected: 
That import works one of the 2 ways.

Actual: 
Neither method of import works, they both give errors.

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
