### ISSUE TITLE
Python SDK uses duplicate argument in `servicecatalog/tag_option_resource_association.py`

### ISSUE THREAD

**Issue by csssuf** [pulumi/pulumi-aws#1519]
The Python SDK has a function with a duplicate argument (`resource_name`) in `servicecatalog/tag_option_resource_association.py`:

https://github.com/pulumi/pulumi-aws/blob/e17984805f03c02f7b0b6433c585e3b71b7846d8/sdk/python/pulumi_aws/servicecatalog/tag_option_resource_association.py#L270-L278

This is an unrecoverable error for mypy, which means any projects depending on pulumi-aws can no longer run mypy against pulumi-aws 4.7.0.

## Steps to reproduce
1. `mypy sdk/python`

Expected:
mypy passes.

Actual:
```
sdk/python/pulumi_aws/servicecatalog/tag_option_resource_association.py:277: error: Duplicate argument 'resource_name' in function definition
Found 1 error in 1 file (errors prevented further checking)
```

**Comment by stack72** [comment]
Hi @csssuf 

I will get this fixed up and a new release cut!

Sorry this happened

Paul

**Comment by lukehoban** [comment]
@stack72 Are we running `mypy` on the generated SDKs in our provider repos?  If not, perhaps that's worth adding to catch this earlier?

**Comment by stack72** [comment]
we are not - that is definitely something I will add here!

**Comment by tlinhart** [comment]
Hi guys, what's the status of this issue, please? We are using https://github.com/tlinhart/pulumi-aws-tags extensively for autotagging our AWS resources and the library crashes due to this bug prohibiting us from provisioning the resources during CI/CD.
