### ISSUE TITLE
Support `MultiRegion` KMS Key

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws#1536]
Hi,

AWS has released a new feature in their KMS service. As of now, Customer Managed Keys can be multi-region by setting the `MultiRegion` flag during creating.

This feature would be helpful for customers who have a multi-region setup such has neobanks and cryptocurrency exchanges. This would also be very helpful for customers who have a multi-region disaster recovery setup allowing them to protect assets in one region and restore these encrypted assets in another region.

**Comment by lukehoban** [comment]
Tracked upstream in https://github.com/hashicorp/terraform-provider-aws/issues/19896.

**Comment by cynicaljoy** [comment]
Looks like the upstream has been resolved, but not release yet. Should be available in v3.64.0 though 🙌
