### ISSUE TITLE
Unable to install aws plugin on Apple M1

### ISSUE THREAD

**Issue by holmok** [pulumi/pulumi-aws#1537]
I can not install the AWS plug-in on my apple m1 machine.  I have v3.5.1 of the CLI.  My project is typescript using AWS 3.32.0 and Pulumi 2.22.

## Steps to reproduce
When I run `pulumi plugin install resource aws v3.32.0` I get an error

Expected: install the plugin
Actual: this error `error: [resource plugin aws-3.32.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v3.32.0-darwin-arm64.tar.gz`

**Comment by stack72** [comment]
Hi @holmok 

The first release of the arm binary was Pulumi-aws 3.32.1

When upgrading to a new version that is arm compatible you can have a read of our troubleshooting doc

https://www.pulumi.com/docs/troubleshooting/#403-http-error-fetching-plugin

Hope this helps

Paul

**Comment by holmok** [comment]
So I updated the `@pulumi/aws@latest` and it updated to `4.8.0`.  Now when I run `pulumi preview` it still thinks I am on the older version of it with the following error:
```
error: could not load plugin for aws provider 'urn:pulumi:dev::alphamap::pulumi:providers:aws::default_3_32_0': no resource plugin 'aws-v3.32.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.32.0`
```

**Comment by lukehoban** [comment]
@holmok The article that @stack72 linked above discusses why that happens and how to work around it. 

https://www.pulumi.com/docs/troubleshooting/#403-http-error-fetching-plugin
