### ISSUE TITLE
Set custom user agent

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi-aws#1553]
Similar to https://github.com/pulumi/pulumi-google-native/issues/73, we should set the user agent of this provider to a Pulumi-specific string to help Pulumi and AWS measure updates that are made by Pulumi. We should allow users to opt out of this user agent if they choose.

This helps both companies understand which features and options are most commonly used by Pulumi and helps us prioritize where to invest in improvements, examples, etc.

**Comment by isaac-pulumi** [comment]
**Instructions:**
The unique UA should use the syntax listed below:

APN/1.0<PARTNER>/1.0<SOLUTION>/<VERSION>([0-9]+.[0-9]+)

 

For example, if your company name is Cloud Corp and you have a product called My Solution that has a current version of 5.0 you can use the UA below:

APN/1.0 cloudcorp/1.0 mysolution/5.0

 

<PARTNER> - This should be the name of your company. Please be consistent with the name you use across all products, including case.

<SOLUTION> - This can include letters and numbers, avoid spaces and do not use any special characters. - The product/solution name.

<VERSION> - This can include letters and numbers, avoid spaces and do not use any special characters. For AWS Marketplace solutions add a space and “MP” after the solution name.

**Documentation:**
[AmazonS3-PartnerTrackingv1.2 (1).pdf](https://github.com/pulumi/pulumi-aws/files/6869257/AmazonS3-PartnerTrackingv1.2.1.pdf)
[AmazonEC2-PartnerTrackingv1.1 (1).pdf](https://github.com/pulumi/pulumi-aws/files/6869258/AmazonEC2-PartnerTrackingv1.1.1.pdf)


**Code Sample:**
[](https://gist.github.com/aossey/5fffe2a436862fe3e16034cbbf38f22f)
