### ISSUE TITLE
Input properties: "tags"

### ISSUE THREAD

**Issue by sebandgo** [pulumi/pulumi-aws#1556]
File: [docs/reference/pkg/aws/autoscaling/group.md](https://www.pulumi.com/docs/reference/pkg/aws/autoscaling/group/)

Current text:
"Configuration block(s) containing resource tags. Conflicts with tags. Documented below."

It should be: 
"Configuration block(s) containing resource tags. Conflicts with tags_collection. Documented below."

**Comment by leezen** [comment]
Thanks for pointing this out. I've created https://github.com/pulumi/terraform-provider-aws/pull/64 to hopefully address this.

**Comment by iwahbe** [comment]
This has been resolved by https://github.com/pulumi/terraform-provider-aws/pull/64, so I'm closing as fixed.
