### ISSUE TITLE
AWS RDS SQLServer need instance name to be null

### ISSUE THREAD

**Issue by oscarphang** [pulumi/pulumi-aws#1557]
When I creating RDS instance for SQLServer, 
there's a issue when the name is null or empty, Pulumi won't able to run successfully,
if I insert a name on it AWS will prompt that name should be null.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
Here stated for SQLServer name should be null.

**Comment by lukehoban** [comment]
You should be able to pass `name: ""`.

Pulumi [autonames](https://www.pulumi.com/docs/intro/concepts/resources/#autonaming) resources, so if you leave off `name` entirely, Pulumi will provide a default name.  So you need to explicitly set an empty name.

You can use `identifier` to uniquely name the RDS instance.
