### ISSUE TITLE
ECS Cluster logging not working (using the example from docs)

### ISSUE THREAD

**Issue by jamesla** [pulumi/pulumi-aws#1558]
Unable to create ECS cluster with logging enabled as per the documentation:

## Steps to reproduce

1. Deploy the following resources (https://www.pulumi.com/docs/reference/pkg/aws/ecs/cluster/#example-wlog-configuration)
```
const exampleKey = new aws.kms.Key("exampleKey", {
    description: "example",
    deletionWindowInDays: 7,
});
const exampleLogGroup = new aws.cloudwatch.LogGroup("exampleLogGroup", {});
const test = new aws.ecs.Cluster("test", {configuration: {
    executeCommandConfiguration: {
        kmsKeyId: exampleKey.arn,
        logging: "OVERRIDE",
        logConfiguration: {
            cloudWatchEncryptionEnabled: true,
            cloudWatchLogGroupName: exampleLogGroup.name,
        },
    },
}});
```

Expected: It should deploy

Actual: ` aws:ecs:Cluster (test): error: aws:ecs/cluster:Cluster resource 'test' has a problem: Invalid or unknown key`

Things I have tried:
1. Using the latest version of the pulumi libraries.
2. Tried the terraform provider equivalent which works fine.

**Comment by lukehoban** [comment]
The fact that the error message doesn't say *what* key is invalid is tracked in https://github.com/pulumi/pulumi/issues/6096.

We'll need to repro and get a verbose log to understand which key was actually invalid and why the example was suggesting passing an invalid key to one of these inputs.

**Comment by mikhailshilkov** [comment]
I tried the exact repro above and the program deployed successfully. I'll assume the issue has been fixed in those 2+ years since the issue was reported.
