### ISSUE TITLE
API Gateway API Mapping Path property is missing

### ISSUE THREAD

**Issue by pgermishuys** [pulumi/pulumi-aws#1564]
The API Gateway Custom Domain API Mappings allows the user to point to different stages from the API Gateway, but specifying more than 1 stage requires the user to provide a different `Path`. This `Path` property is currently not exposed in the Pulumi AWS SDK.
_Reference to the API Mapping from the AWS Console_
![image](https://user-images.githubusercontent.com/1062417/124895902-426ae400-dfdd-11eb-8953-94230bb65b74.png)
_Reference to the API Mapping Pulumi SDK_
https://www.pulumi.com/docs/reference/pkg/aws/apigatewayv2/apimapping/

Expected: The `Path` to be a property on the `ApiMapping` type.
Actual: The `Path` is missing on the`ApiMapping` type.

**Comment by RedmondK** [comment]
Did you solve this @pgermishuys  ?

**Comment by RedmondK** [comment]
For anyone else with the same issue, use property apiMappingKey in ApiMappingArgs to set this value. It's not immediately clear in the docs which seem to be WebSocket API specific.

https://www.pulumi.com/registry/packages/aws/api-docs/apigatewayv2/apimapping/#inputs
