### ISSUE TITLE
Bug: ReplaceOnChange is not detected on aws.cognito.UserPool

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws#1582]
Changing the `schemas` attribute of an UserPool is not possible after creation. Therefore I want to replace the user pool when I change the schemas attribute with the recent `replaceOnChanges` option. However, pulumi still tries to update the schema instead.

## Steps to reproduce
```
const pool = new aws.cognito.UserPool("NAME", {
  usernameAttributes: ["email"],
  schemas: [{
    attributeDataType: "String",
    name: "email",
    required: true,
    string_attribute_constraints: {
      max_length: 2048,
      min_length: 1,
    },
  }
}, { replaceOnChanges: ["*"], deleteBeforeReplace: true });
```

Change the schemas attribute by adding another property, not making it required or change the min_length. While `replaceOnChanges` is set, pulumi will still try to update the user pool and will not replace it. I've tested it with different replaceOnChanges values (`schemas`, `schemas.*`, `*`), but nothing helps.

Expected: Deleted old user pool and a fresh new user pool with an updated schema.
Actual: Error: `error updating Cognito User Pool (xxx): cannot modify or remove schema items`

**Comment by leezen** [comment]
@Jimmy89 Can you please indicate the versions of the pulumi CLI, SDK, and pulumi-aws you're using? It sounds like you might be on an older version of the CLI.

**Comment by Jimmy89** [comment]
@leezen I was wondering the same thing, but I I am using the pulumi cli 3.8.0 and these packages (using JS)

```
"@pulumi/aws": "^4.14.0",
 "@pulumi/pulumi": "^3.8.0",
```

**Comment by leezen** [comment]
Your code above seems odd while I was trying to reproduce and I suspect this is why it's not working. When I went to reproduce, I had to fix up the code so it would typecheck correctly.

```
const pool = new aws.cognito.UserPool("foo", {
    usernameAttributes: ["email"],
    schemas: [{
      attributeDataType: "String",
      name: "email",
      required: true,
      stringAttributeConstraints: {
        maxLength: "2048",
        minLength: "100",
      },
    }]
}, { replaceOnChanges: ["*"], deleteBeforeReplace: true });
```

After doing so, I got the expected replacement:

```bash
     Type                     Name                    Status      
     pulumi:pulumi:Stack      scratch-typescript-dev              
 +   └─ aws:cognito:UserPool  foo                     created     
 
Resources:
    + 1 created
    1 unchanged

Duration: 5s

# I went and edited to change minLength

❯ pulumi up                                                                                                                                                                               

Previewing update (dev)

     Type                     Name                    Plan        Info
     pulumi:pulumi:Stack      scratch-typescript-dev              
 +-  └─ aws:cognito:UserPool  foo                     replace     [diff: ~schemas]
 
Resources:
    +-1 to replace
    1 unchanged

```
