### ISSUE TITLE
`pulumi import` with AWS Lambda function unable to import

### ISSUE THREAD

**Issue by glitchwizard** [pulumi/pulumi-aws#1589]
running `pulumi import` on a lambda function, and it's not able to import, and gives the following error:

```
pulumi import aws:lambda/function:Function lambda1 lambda1
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Previewing import (foobarfoo-local_test_stack):
     Type                    Name                              Plan       Info
 +   pulumi:pulumi:Stack     local_test_stack  create     1 error
 =   └─ aws:lambda:Function  lambda1                   import     1 error

Diagnostics:
  aws:lambda:Function (lambda1):
    error: Preview failed: diffing urn:pulumi:local_test_stack::foobarfoo::aws:lambda/function:Function::lambda1: handler and runtime must be set when PackageType is Zip

  pulumi:pulumi:Stack (foobarfoo-local_test_stack):
    error: preview failed
```

## Steps to reproduce

1. In the Pulumi CLI, I typed `pulumi import aws:lambda/function:Function lambda1 lambda1`
2. The error was produced from that 

Expected: 
I expected to get the code and import information for the lambda function
Actual: 
The error shown above happened.

**Comment by stack72** [comment]
Hi @glitchwizard 

I am sorry this has caused an issue for you - we are tracking a higher level bug with import and I have linked this specific issue to that one

I will close this out as a duplicate so that we can track the import issue centrally. Please use that issue for any extra information / or to get updates

Paul
