### ISSUE TITLE
Cannot import resources with a "/" in is id (compound resource ids)

### ISSUE THREAD

**Issue by fernandocarletti** [pulumi/pulumi-aws#1591]
This issue happens on resource that rely on multiple ids to be imported such as [RouteTableAssociation](https://www.pulumi.com/docs/reference/pkg/aws/ec2/routetableassociation/#import) and [Route](https://www.pulumi.com/docs/reference/pkg/aws/ec2/route/) where the id is compound by its related resources id.

## Steps to reproduce
1. Straight from the documentation: `pulumi import aws:ec2/routeTableAssociation:RouteTableAssociation assoc subnet-6777656e646f6c796e/rtb-656c65616e6f72`

Expected: The resource to be imported.
Actual: The following error:

```
  aws:ec2:RouteTableAssociation (public-cc):
    error: aws:ec2/routeTableAssociation:RouteTableAssociation resource 'public-x' has a problem: ExactlyOne: "gateway_id": one of `gateway_id,subnet_id` must be specified. Examine values at 'RouteTableAssociation.GatewayId'.
    error: aws:ec2/routeTableAssociation:RouteTableAssociation resource 'public-x' has a problem: ExactlyOne: "subnet_id": one of `gateway_id,subnet_id` must be specified. Examine values at 'RouteTableAssociation.SubnetId'.
    error: Preview failed: one or more inputs failed to validate
    ```

**Comment by stack72** [comment]
Hi @fernandocarletti 

I am sorry this has caused an issue for you - we are tracking a higher level bug with import and I have linked this specific issue to that one

I will close this out as a duplicate so that we can track the import issue centrally. Please use that issue for any extra information / or to get updates

Paul
