### ISSUE TITLE
Unable to apply an SSL certificate to a CloudFront distribution in AWS China.

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi-aws#1596]
I want to set the SSL certification of a CloudFront distribution in AWS China. 
However, pulumi goes to the wrong region (`us-east-1` region) to look for the SSL certificate.

## Steps to reproduce

1. Run `pulumi up` with AWS credentials set to `cn-northwest-1` reigon in AWS China using the following code.

```
import pulumi
import pulumi_aws as aws

s3_origin_id = "myS3Origin"
s3_distribution = aws.cloudfront.Distribution("s3Distribution",
    origins=[aws.cloudfront.DistributionOriginArgs(
        domain_name=wecare_bucket.bucket_regional_domain_name,
        origin_id=s3_origin_id,
    )],
    enabled=True,
    is_ipv6_enabled=False,
    comment="CloudFront distribution for Weixin widget ",
    default_root_object="index.html",
    aliases=[
        "my-domain.my-comp.com.cn"
    ],
    default_cache_behavior=aws.cloudfront.DistributionDefaultCacheBehaviorArgs(
        allowed_methods=[
            "GET",
            "HEAD"
        ],
        cached_methods=[
            "GET",
            "HEAD",
        ],
        compress=False,
        target_origin_id=s3_origin_id,
        forwarded_values=aws.cloudfront.DistributionDefaultCacheBehaviorForwardedValuesArgs(
            query_string=False,
            cookies=aws.cloudfront.DistributionDefaultCacheBehaviorForwardedValuesCookiesArgs(
                forward="none",
            ),
        ),
        viewer_protocol_policy="allow-all",
        min_ttl=0,
        default_ttl=86400,
        max_ttl=86400,
    ),
    price_class="PriceClass_All",
    restrictions=aws.cloudfront.DistributionRestrictionsArgs(
        geo_restriction=aws.cloudfront.DistributionRestrictionsGeoRestrictionArgs(
            restriction_type="none"
        ),
    ),
    retain_on_delete=False,
    tags={
        "Environment": "production",
    },
    wait_for_deployment=True,
    viewer_certificate=aws.cloudfront.DistributionViewerCertificateArgs(
        iam_certificate_id="XSCAQIQDJAGFOVLXUVKET",
        ssl_support_method="sni-only"
    )
    )
```
2. You will find an error saying ` error updating CloudFront Distribution (P3T8JCU42L3GDZ): InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.`

Expected: The SSL certificate `XSCAQIQDJAGFOVLXUVKET` in IAM is applied to the CloudFront distribution without any problem.
Actual: ` error updating CloudFront Distribution (P3T8JCU42L3GDZ): InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.`

My certificate is located in `cn-northwest-1` region, not `us-east-1` region. How can I tell pulumi to look for the certificate in `cn-northwest-1` region?

**Comment by stack72** [comment]
Hi @lyenliang 

This isn't actually a Pulumi thing - by default, AWS Cloudfront will try and load certificates from us-east-1 by default. Are you able to see the same certificate from the AWS Console?

Paul

**Comment by lyenliang** [comment]
I've found that the real reason for this error is that the length of my certificate is longer than 2048 bits. 

This [document](https://docs.amazonaws.cn/en_us/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html) says that CloudFront supports only 1024-bit and 2048-bit RSA keys.

Pulumi works successfully after I change the key length.

**Comment by stack72** [comment]
Ah - that's VERY interesting! I never knew that was the case :/ I am sorry for the misleading information here

Glad you have it working as expected now
