### ISSUE TITLE
AWS Redshift Security Group Error

### ISSUE THREAD

**Issue by XanManZA** [pulumi/pulumi-aws#1600]
When trying to add an EC2 Security Group to a Redshift Cluster through Pulumi, you get an error that the "Security group does not exist in the VPC".
In this instance the Security Group was successfully added to the Redshift Cluster through the console with no errors and when doing a sanity check on the EC2 Network tab then the Security Group is in fact in the right VPC.
The error:
![image](https://user-images.githubusercontent.com/12627519/129867276-ddd31b85-bf4b-47c0-9a69-ed5c19729fd8.png)
Here you can see that the SG is in fact in the correct VPC:
![image](https://user-images.githubusercontent.com/12627519/129867322-681a9978-5993-4e14-b08b-cab4cd701db4.png)

## Steps to reproduce

1. Create a Redshift Cluster through Pulumi using `pulumi up`
2. Now add a new Security Group to the cluster using Pulumi, run `pulumi up`
3. Receive above error

I understand this might have different reproducibility so please let me know if you need more details on my setup.

Expected: Security Group assigned to cluster successfully
Actual: Receive error "Security Group does not exist in VPC"

**Comment by XanManZA** [comment]
Closing, there was a sneaky space character in my config.

**Comment by stack72** [comment]
Thanks for being so fast to get back to us on this @XanManZA - it's very much appreciated
