### ISSUE TITLE
Can't get it working in Lambda (Cannot find module 'vite-plugin-ssr/dist/cjs/node/index.js')

### ISSUE THREAD

**Issue by CanRau** [pulumi/pulumi-aws#1608]
Hey there ☺️

I'm trying to deploy a [Vite](https://vitejs.dev/) React app using [vite-plugin-ssr](https://vite-plugin-ssr.com/) to provide SSR but testing the Lambda via AWS Console results in `Cannot find module 'vite-plugin-ssr/dist/cjs/node/index.js'` so it seems it's not correctly bundling the right version or something?
I opened an [issue](https://github.com/brillout/vite-plugin-ssr/issues/137) at the plugin repo but was told it's more likely some bundling issue with Pulumi

I'm running
```
pulumi version => v3.10.3
node -v => v16.5.0
```

The full error from the AWS Lambda Console:

```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'vite-plugin-ssr/dist/cjs/node/index.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Error: Cannot find module 'vite-plugin-ssr/dist/cjs/node/index.js'",
    "Require stack:",
    "- /var/task/__index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:745:27)",
    "    at Module.require (internal/modules/cjs/loader.js:961:19)",
    "    at require (internal/modules/cjs/helpers.js:92:18)",
    "    at /var/task/__index.js:80:15",
    "    at Object.__f2 [as createPageRender] (/var/task/__index.js:85:6)",
    "    at /var/task/__index.js:105:32",
    "    at Generator.next (<anonymous>)",
    "    at /var/task/__index.js:16:71",
    "    at new Promise (<anonymous>)"
  ]
}
```

## Steps to reproduce

1. `git clone https://github.com/CanRau/pulumi-bundle-issue`
2. `yarn`
3. `cd www`
4. `yarn && yarn build`
5. `cd ..`
6. `pulumi up` to some test environment if possible

Expected:  Working Lambda
Actual:  Error as in title

I use `www/server/lambda.ts` as Lambda function handler [index.ts#L3](https://github.com/CanRau/pulumi-bundle-issue/blob/bundle-issue/index.ts#L3)
Which as mentioned in the [plugins docs](https://vite-plugin-ssr.com/cloudflare-workers) imports [`import "../dist/server/importBuild";`](https://github.com/CanRau/pulumi-bundle-issue/blob/bundle-issue/www/server/lambda.ts)
Actually `lambda.ts` itself already imports `vite-plugin-ssr`.

Maybe I've got some `tsconfig.json` confusions?

Let me know if I can provide anything else 🙏

**Comment by emiliza** [comment]
I just tried again with these versions (same as you, minus node where I'm behind): 
```
"@pulumi/aws": "4.17.0"
"@pulumi/pulumi": "3.11.0"
pulumi CLI: v3.11.0
node: v14.16.1
```

I'm still able to `pulumi up` without issue 🤷‍♀️  As for how I got the `toLowerCase` error, I just went to the lambda console in AWS and triggered a test event

**Comment by CanRau** [comment]
> Uh, the `toLowerCase` happens probably because I didn't provide a test event 😅
> 
> ```
> {
>   "body": "",
>   "resource": "/{proxy+}",
>   "path": "/",
>   "httpMethod": "GET",
>   "isBase64Encoded": true,
>   "queryStringParameters": {},
>   "multiValueQueryStringParameters": {},
>   "pathParameters": {
>     "proxy": "/"
>   },
>   "stageVariables": {
>     "baz": "qux"
>   },
>   "headers": {
>     "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
>     "Accept-Encoding": "gzip, deflate, sdch",
>     "Accept-Language": "en-US,en;q=0.8",
>     "Cache-Control": "max-age=0",
>     "CloudFront-Forwarded-Proto": "https",
>     "CloudFront-Is-Desktop-Viewer": "true",
>     "CloudFront-Is-Mobile-Viewer": "false",
>     "CloudFront-Is-SmartTV-Viewer": "false",
>     "CloudFront-Is-Tablet-Viewer": "false",
>     "CloudFront-Viewer-Country": "US",
>     "Host": "1234567890.execute-api.us-east-1.amazonaws.com",
>     "Upgrade-Insecure-Requests": "1",
>     "User-Agent": "Custom User Agent String",
>     "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
>     "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
>     "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
>     "X-Forwarded-Port": "443",
>     "X-Forwarded-Proto": "https"
>   },
>   "multiValueHeaders": {
>     "Accept": [
>       "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
>     ],
>     "Accept-Encoding": [
>       "gzip, deflate, sdch"
>     ],
>     "Accept-Language": [
>       "en-US,en;q=0.8"
>     ],
>     "Cache-Control": [
>       "max-age=0"
>     ],
>     "CloudFront-Forwarded-Proto": [
>       "https"
>     ],
>     "CloudFront-Is-Desktop-Viewer": [
>       "true"
>     ],
>     "CloudFront-Is-Mobile-Viewer": [
>       "false"
>     ],
>     "CloudFront-Is-SmartTV-Viewer": [
>       "false"
>     ],
>     "CloudFront-Is-Tablet-Viewer": [
>       "false"
>     ],
>     "CloudFront-Viewer-Country": [
>       "US"
>     ],
>     "Host": [
>       "0123456789.execute-api.us-east-1.amazonaws.com"
>     ],
>     "Upgrade-Insecure-Requests": [
>       "1"
>     ],
>     "User-Agent": [
>       "Custom User Agent String"
>     ],
>     "Via": [
>       "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)"
>     ],
>     "X-Amz-Cf-Id": [
>       "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA=="
>     ],
>     "X-Forwarded-For": [
>       "127.0.0.1, 127.0.0.2"
>     ],
>     "X-Forwarded-Port": [
>       "443"
>     ],
>     "X-Forwarded-Proto": [
>       "https"
>     ]
>   },
>   "requestContext": {
>     "accountId": "123456789012",
>     "resourceId": "123456",
>     "stage": "prod",
>     "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
>     "requestTime": "09/Apr/2015:12:34:56 +0000",
>     "requestTimeEpoch": 1428582896000,
>     "identity": {
>       "cognitoIdentityPoolId": null,
>       "accountId": null,
>       "cognitoIdentityId": null,
>       "caller": null,
>       "accessKey": null,
>       "sourceIp": "127.0.0.1",
>       "cognitoAuthenticationType": null,
>       "cognitoAuthenticationProvider": null,
>       "userArn": null,
>       "userAgent": "Custom User Agent String",
>       "user": null
>     },
>     "path": "/prod/path/to/resource",
>     "resourcePath": "/{proxy+}",
>     "httpMethod": "POST",
>     "apiId": "1234567890",
>     "protocol": "HTTP/1.1"
>   }
> }
> ```

Yeah because it's supposed to be a APIGateway event and I don't yet verify it and just access `toLowerCase` on `event.httpMethod` 😅
And maybe because of this you don't get the "correct" error as it fails earlier
