### ISSUE TITLE
Elastic Beanstalk Option settings not removing

### ISSUE THREAD

**Issue by locus-akhilkrishna** [pulumi/pulumi-aws#1609]
Options settings that have been added using Pulumi not removing from the beanstalk after removing from Pulumi
Expected: When we remove the option settings from Pulumi this has to remove from the Beanstalk also

**Comment by leezen** [comment]
@locus-akhilkrishna Could you please provide more details on what you're referring to and a repro case if possible? Are you talking about the `settings` property for an environment or something else?

**Comment by lukehoban** [comment]
There isn't a repro here - so will close this out.  But there are a number of issues with Beanstalk in the upstream provider and noted in https://github.com/pulumi/pulumi-aws/issues/920#issuecomment-623580979 which may be relevant.
