### ISSUE TITLE
Can't use aws.secretsmanager.getSecretVersion without VersionId

### ISSUE THREAD

**Issue by nickcaballero** [pulumi/pulumi-aws#1613]
I'm trying to import existing secrets into stack by using `getSecretVersion`. However, it results in the following error:

```
  aws:secretsmanager:SecretVersion (my-secret):
    error: Preview failed: refreshing urn:pulumi:localstack::localstack::aws:secretsmanager/secretVersion:SecretVersion::my-secret: 1 error occurred:
    	* error reading Secrets Manager Secret Version (arn:aws:secretsmanager:us-east-1:000000000000:secret:my-secret-SFWGVf|AWSCURRENT): InvalidParameter: 1 validation error(s) found.
    - minimum field size of 32, GetSecretValueInput.VersionId
```

## Steps to reproduce

1. Call `getSecretVersion` with just the `secretId`.

It seems to be related to https://github.com/hashicorp/terraform-provider-aws/issues/16507 but I'm not sure.

**Comment by leezen** [comment]
Yes, given the provider will use the same read path, this is related to the upstream issue. Per the upstream, you can workaround this by specifying the `versionId`

**Comment by Johana30** [comment]
the versionId does not recognise AWSCURRENT  as a versionId, so after used terraform import aws_secretsmanager_secret_version.superuser 'arn:aws:secretsmanager:eu-west-2:::::::secret:rds-superuser-T:::::::::B|"AWSCURRENT"
I get a error api error ValidationException: 1 validation error detected: Value 'AWSCURRENT' at 'versionId' failed to satisfy constraint: Member must have length greater than or equal to 32

**Comment by t0yv0** [comment]
I'm going to close this for inactivity. There's a chance that something is still not working as expected here, if you are encountering this please open a fresh issue with a self-contained Pulumi program that reproduces the problem, we'll take a closer look. Thank you.
