### ISSUE TITLE
vpnconnectionroute renaming of resource does NOT recreate vpnconnectionroute(static route) in aws console even though Pulumi says it does

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-aws#1615]
[vpnconnectionroute](https://www.pulumi.com/docs/reference/pkg/aws/ec2/vpnconnectionroute/#inputs) - renaming the resource after the 1st time it is created, it does NOT show up in the aws console
even though pulumi shows 1 resource created, and 1 deleted.  

High Level Summary:
  We are able to create the vpnconnectionroute with the following block of code the 1st time around:
```
const my_cidrblock_1 = "192.168.11.0/24";
const office = new aws.ec2.VpnConnectionRoute(`myname-vpnconnectionroute`, {
  destinationCidrBlock: my_cidrblock_1,
  vpnConnectionId: vpnconnection.id,
});
```

When we rename the resource(Adding a 1 here) from 
```
myname-vpnconnectionroute
```
TO:
```
myname-vpnconnectionroute1
```
the resource shows deleted in the aws console, even though Pulumi cli states that it did get recreated.
## Version Information
pulumi version:  `v3.11.0`
node -v:`v16.1.0`
[package.json](https://github.com/tusharshahrs/pulumi-homelab/blob/master/aws-ts-site2site-vpn/package.json)
```pulumi plugin ls -p
NAME    KIND      VERSION  SIZE    INSTALLED    LAST USED
aws     resource  4.18.0   278 MB  1 day ago    9 minutes ago
docker  resource  3.1.0    40 MB   2 hours ago  2 hours ago
nodejs  language           21 MB   1 week ago   now
```

## Steps to reproduce

1. git clone https://github.com/tusharshahrs/pulumi-homelab
1. cd into the directory:    `cd aws-ts-site2site-vpn`
1. Initialize that stack:      `pulumi stack init dev`
1. Install dependencies `npm install`
1. Set the aws region:   `pulumi config set aws:region us-east-2`
1. Bring up the stack:  `pulumi up -y`
1. Check the outputs `pulumi stack output` 
1. [Screen Shot](https://share.getcloudapp.com/04uxLq0J) from AWS Console showing that static route was created.
1. Update the following 1 line of code changing the [resource name](https://github.com/tusharshahrs/pulumi-homelab/blob/master/aws-ts-site2site-vpn/index.ts#L66) from 
      ```
      ${name}-vpnconnectionroute
      ```
      TO
      ```
      ${name}-vpnconnectionroute1
      ```
      Notice, we have just added a number to the end.

1. Run `pulumi up` and check the `details` and it will show that 1 resource will be created and 1 deleted (this is expected).
   ```
        View Live: https://app.pulumi.com/shaht/aws-ts-site2site-vpn/dev/previews/3ee91fcd-6ae4-458d-b3db-25cd9a354aa0
      
           Type                           Name                                Plan       
           pulumi:pulumi:Stack            aws-ts-site2site-vpn-dev                       
       +   ├─ aws:ec2:VpnConnectionRoute  demo-site2site-vpnconnectionroute1  create     
       -   └─ aws:ec2:VpnConnectionRoute  demo-site2site-vpnconnectionroute   delete     
       
      Outputs:
        ~ office_vpnconnectionroute_id             : "192.168.11.0/24:vpn-0d63297be1d248e14" => output<string>
        ~ office_vpnconnectionroute_urn            : "urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute" => "urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute1"
      
      Resources:
          + 1 to create
          - 1 to delete
          2 changes. 41 unchanged
      
      Do you want to perform this update? details
        pulumi:pulumi:Stack: (same)
          [urn=urn:pulumi:dev::aws-ts-site2site-vpn::pulumi:pulumi:Stack::aws-ts-site2site-vpn-dev]
          + aws:ec2/vpnConnectionRoute:VpnConnectionRoute: (create)
              [urn=urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute1]
              [provider=urn:pulumi:dev::aws-ts-site2site-vpn::pulumi:providers:aws::default_4_18_0::54624ff9-c34c-4298-ba13-935a059190a4]
              destinationCidrBlock: "192.168.11.0/24"
              vpnConnectionId     : "vpn-0d63297be1d248e14"
          --outputs:--
        ~ office_vpnconnectionroute_id             : "192.168.11.0/24:vpn-0d63297be1d248e14" => output<string>
        ~ office_vpnconnectionroute_urn            : "urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute" => "urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute1"
          - aws:ec2/vpnConnectionRoute:VpnConnectionRoute: (delete)
              [id=192.168.11.0/24:vpn-0d63297be1d248e14]
              [urn=urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute]
              [provider=urn:pulumi:dev::aws-ts-site2site-vpn::pulumi:providers:aws::default_4_18_0::54624ff9-c34c-4298-ba13-935a059190a4]
   ```
1. After selecting `yes`, you will see the following which is expected:
   ```
         View Live: https://app.pulumi.com/shaht/aws-ts-site2site-vpn/dev/updates/32
      
           Type                           Name                                Status      
           pulumi:pulumi:Stack            aws-ts-site2site-vpn-dev                        
       +   ├─ aws:ec2:VpnConnectionRoute  demo-site2site-vpnconnectionroute1  created     
       -   └─ aws:ec2:VpnConnectionRoute  demo-site2site-vpnconnectionroute   deleted     
       
      Outputs:
          customergateway_id                       : "cgw-0f094a3610ca4ff7d"
          office_vpnconnectionroute_id             : "192.168.11.0/24:vpn-0d63297be1d248e14"
        ~ office_vpnconnectionroute_urn            : "urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute" => "urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute1"
          office_vpnconnectionroute_vpnconnectionid: "vpn-0d63297be1d248e14"
          vpcs_id                                  : "vpc-07024c488ec5940f9"
          vpcs_name                                : "vpc-07024c488ec5940f9"
          vpn_connection_id                        : "vpn-0d63297be1d248e14"
          vpn_gateway_id                           : "vgw-0919c724b026ddd7e"
      
      Resources:
          + 1 created
          - 1 deleted
          2 changes. 41 unchanged
      
      Duration: 6s
   ```
1. Check the outputs via `pulumi stack output` and it will show you the office_vpnconnection_route.. outputs
   ```
        Current stack outputs (8):
        OUTPUT                                     VALUE
        customergateway_id                         cgw-0f094a3610ca4ff7d
        office_vpnconnectionroute_id               192.168.11.0/24:vpn-0d63297be1d248e14
        office_vpnconnectionroute_urn              urn:pulumi:dev::aws-ts-site2site-vpn::aws:ec2/vpnConnectionRoute:VpnConnectionRoute::demo-site2site-vpnconnectionroute1
        office_vpnconnectionroute_vpnconnectionid  vpn-0d63297be1d248e14
        vpcs_id                                    vpc-07024c488ec5940f9
        vpcs_name                                  vpc-07024c488ec5940f9
        vpn_connection_id                          vpn-0d63297be1d248e14
        vpn_gateway_id                             vgw-0919c724b026ddd7e
   ```
1.  Check the AWS console and it will show **deleted** and the route is missing.  [Screen Shot](https://share.getcloudapp.com/kpun4bO0)

1.  Note, we have also added **{deleteBeforeReplace: true}** but it makes no difference in the behavior.

Expected: 
That the route would be created when we are renaming a resource.

Actual: 
The current route is deleted ( which we expect), the resource shows up as being created in pulumi does NOT show up in the aws console

**Comment by clstokes** [comment]
@tusharshahrs can you work on reproducing this in Terraform? From a quick read it doesn’t seem like this should be specific to Pulumi.

**Comment by tusharshahrs** [comment]
We are able to validate that this error is due to the following upstream issue.
[aws_vpn_connection_route "Invalid memory address or nil pointer dereference"](https://github.com/hashicorp/terraform-provider-aws/issues/20685)

Here is our code that shows this:
This is our main.tf

```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "demo-site2site"
  cidr = "10.0.0.0/23"

  azs             = ["us-east-2a", "us-east-2b", "us-east-2c"]
  private_subnets = ["10.0.1.0/26", "10.0.1.64/26", "10.0.1.128/25"]
  public_subnets  = ["10.0.0.0/25", "10.0.0.128/26", "10.0.0.192/26"]

  default_vpc_enable_dns_hostnames = true
  default_vpc_enable_dns_support   = true

  enable_nat_gateway = true
  enable_vpn_gateway = false
  single_nat_gateway = true

  tags = {
    environment = "dev"
    costcenter  = "1234"
  }

}

// add vpn gateway
resource "aws_vpn_gateway" "vpngateway" {
  vpc_id = module.vpc.vpc_id

  tags = {
    Name = "demo-site2site-vpngateway"
  }
}

// add customer gateway
resource "aws_customer_gateway" "customergateway" {
  bgp_asn    = 65000
  ip_address = "172.83.124.10"
  type       = "ipsec.1"

  tags = {
    Name = "demo-site2site-customergateway"
  }
}

//add vpcn connection
resource "aws_vpn_connection" "vpnconnection" {
  vpn_gateway_id      = aws_vpn_gateway.vpngateway.id
  customer_gateway_id = aws_customer_gateway.customergateway.id
  type                = "ipsec.1"
  static_routes_only  = true
  tags = {
    Name = "demo-site2site-vpnconnection"
  }
}

// add static route
resource "aws_vpn_connection_route" "office" {
  destination_cidr_block = "192.168.10.0/24"
  vpn_connection_id      = aws_vpn_connection.vpnconnection.id
}

We run `terraform apply` and the static route shows up in the vpn connection
Change the resource name from **office** to **office1**
and run `terraform apply` and the following error shows up:

```
aws_vpn_connection_route.office1: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_vpn_connection_route.office1,
│   on main.tf line 57, in resource "aws_vpn_connection_route" "office1":
│   57: resource "aws_vpn_connection_route" "office1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.56.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x633e97d]

goroutine 72 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsVpnConnectionRouteCreate.func1(0xc0023c16e0, 0xc0023c16a0, 0x0, 0x0, 0x2, 0x8c40e01)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_vpn_connection_route.go:69 +0x9d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc00066e960, 0xc0016a90a0, 0xc00289a7e0, 0xc000deaf00, 0xc000054e30, 0xc000054de8)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/resource/state.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/resource/state.go:83 +0x1c6

Error: The terraform-provider-aws_v3.56.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by lukehoban** [comment]
This has been fixed upstream and should be available in Pulumi AWS releases now.
