### ISSUE TITLE
ServiceDnsConfigDnsRecord `type` comment is incorrect

### ISSUE THREAD

**Issue by jmcdo29** [pulumi/pulumi-aws#1616]
The comment for [`ServiceDnsConfigDnsRecord#type`](https://www.pulumi.com/docs/reference/pkg/aws/servicediscovery/service/#servicednsconfigdnsrecord) is incorrect, mentioning that it should only be `HTTP`, `HTTPS`, or `TCP`, when it _should_ be `A`, `AAAA`, `SRV`, `CNAME`

## Steps to reproduce

This comment persists in both the code and in the docs. Let me know if I need to create a minimum reproduction repository for this.

1. Go to the [AWS.ServiceDiscovery](https://www.pulumi.com/docs/reference/pkg/aws/servicediscovery/service/) page and navigate to the [ServiceDnsConfigDnsRecord type](https://www.pulumi.com/docs/reference/pkg/aws/servicediscovery/service/#servicednsconfigdnsrecord)
2. Observe the comment on `type` to

**Comment by lukehoban** [comment]
This is another instance of https://github.com/pulumi/pulumi-terraform-bridge/issues/529 and will need to be fixed there.

**Comment by lukehoban** [comment]
Going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529 to track the required work centrally.
