### ISSUE TITLE
AWS ec2 name not set when use 'aws.ec2.Instance' to create instance.

### ISSUE THREAD

**Issue by linwukang** [pulumi/pulumi-aws#1619]
## Steps to reproduce

code we use: 

``` python
ec2 = aws.ec2.Instance(
    "aaron-dev-ec2",
    instance_type=size,
    vpc_security_group_ids=[security_group.id],
    availability_zone=az,
    subnet_id=public_subnet.id,
    ami="ami-087c17d1fe0178315",
    key_name=keypair.key_name,
)

ec2_non_public = aws.ec2.Instance(
    "aaron-dev-ec2-non-public",
    instance_type=size,
    vpc_security_group_ids=[security_group.id],
    availability_zone=az,
    subnet_id=public_subnet.id,
    ami="ami-087c17d1fe0178315",
    key_name=keypair.key_name,
)
```

Expected: 

the name of ec2 instance can be found from aws console.

Actual: 
name is not set:
![image](https://user-images.githubusercontent.com/5113926/132451138-3f59ad61-4682-4399-bfff-bb215732d8d1.png)

**Comment by stack72** [comment]
Hi

This is expected behaviour as you would need to set tags on the resource (and one of those tags being a Name)

I am going to close this out as this is nothing actionable on the Pulumi side

Thanks

Paul

**Comment by linwukang** [comment]
> Hi
> 
> This is expected behaviour as you would need to set tags on the resource (and one of those tags being a Name)
> 
> I am going to close this out as this is nothing actionable on the Pulumi side
> 
> Thanks
> 
> Paul

Hi, Thanks for the explanation.
