### ISSUE TITLE
aws.ec2.SecurityGroupRule fails to track external changes

### ISSUE THREAD

**Issue by jre21** [pulumi/pulumi-aws#1633]
I want to preface this report by noting that I've found Pulumi to be a really solid product which has been a joy to work with.  In fact, it's precisely because Pulumi's ability to track external changes is so robust under most circumstances that lapses like this have the potential to be so damaging.

Pulumi's SecurityGroupRule resource fails to adequately track changes in the environment, causing it to go out of sync if an external process deletes the rule.  This behavior violates what is perhaps Pulumi's most important invariant: that immediately after an update, the live environment fully reflects the configuration defined in our IaC codebase.

## Setup
I performed several tests to demonstrate the aberrant behavior, using the following stack to create the security group in question.
```
import * as aws from '@pulumi/aws'
import * as pulumi from '@pulumi/pulumi'

export async function configure() {
    const testSg = new aws.ec2.SecurityGroup('testSg', {
        vpcId: 'vpc-00011122233344455',  // hardcoded for demonstration purposes
    });

    new aws.ec2.SecurityGroupRule('testIngress', {
        type: 'ingress',
        fromPort: 443,
        toPort: 443,
        protocol: 'tcp',
        cidrBlocks: ['0.0.0.0/0'],
        securityGroupId: testSg.id,
    });

    return {};
}
```

### steps to reproduce
1.  Run `pulumi up` to create the security group and ingress rule.
2.  Manually delete the ingress rule from the AWS web console.
3.  Run `pulumi up` a second time.

### expected behavior
During the second update, Pulumi detects that the security group rule has been deleted and recreates it.

### actual behavior
Pulumi's preview does not show any diff, and after allowing the update to proceed, the AWS console shows that the security group rule has not been recreated.

### steps to reproduce
Proceed as above, but run `pulumi destroy` after manually deleting the ingress rule.

### expected behavior
Pulumi deletes the security group.

### actual behavior
Pulumi attempts to delete the (now-absent) security group rule, which fails with

```
error: deleting urn:pulumi:platform.us-east-2.security-group-test::dev::aws:ec2/securityGroupRule:SecurityGroupRule::testIngress: 1 error occurred:
    * Error revoking security group sg-0c703550a00038e11 rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
    status code: 400, request id: 9c8a7506-80f5-4e99-96d0-2081258518ef
```

## Additional notes
I also ran the above tests in Terraform, in case the bug was in shared code within an underlying provider.  Terraform correctly detected that the security group rule had been deleted and offered to recreate it, leaving me reasonably confident in my belief that this bug exists entirely within the pulumi-aws codebase.

## Analysis
The above tests clearly demonstrate that, when it comes to security group rules, Pulumi is not doing any sort of environment discovery and instead takes it on faith that the live infrastructure matches its internal state.  This results in surprising and dangerous behavior because Pulumi is now taking actions based on an outdated model of its environment, potentially leading to cascading failures when further actions are taken based on this invalid information.

To give a concrete example of just how badly this could blow up: I discovered the full extent of this bug while doing infrastructure cleanups in our live environment.  We restrict traffic between our application and database tiers by specifying both egress rules in the application's security group and ingress rules on the database, with the goal of ensuring that a given application cannot query another app's database, either through misconfiguration or system compromise.

Because a few of our database stacks had been written before this model was fully solidified, we have a small number of database security groups with rules allowing ingress traffic from the entire VPC in addition to the rules allowing their own application servers.  I had made sure that our narrowly-tailored rules were correctly defined and our stacks were up to date and was preparing to instruct Pulumi to delete the older, overly-broad rules, and happened to look into the AWS console as a final check that I fully understood what was going on, when I noticed rather fewer rules on the database security group than expected.  In particular, the rule that would have allowed the database to accept incoming requests from its application was missing.

Had I not made this extra check, I would have caused a production outage _simply by trusting Pulumi's ability to detect and fix configuration drift, as it was designed to do_.  This behavior may seem like a small detail within the scope of the AWS provider or the Pulumi product as a whole, but any lapse in Pulumi's ability to update its internal state when the environment changes carries the potential for customer outages.

**Comment by stack72** [comment]
Hi @jre21

So when you run a Pulumi up - Pulumi will achieve its desired state. When you make a change outside of Pulumi to resources under management, the Pulumi state needs to be refreshed to that new state

Pulumi doesn't run a refresh by default but if you run "pulumi refresh" then Pulumi will understand that the resource has been deleted and Pulumi can act accordingly

This is an issue in the pulumi/Pulumi repo for us to consider changing the behaviour for Pulumi to always refresh by default but we've not made a decision on that as yet. In order to combat that you can tell your Pulumi up command to refresh:

pulumi up -r

This will ensure the refresh happens to ensure that we don't get into this cycle

I'm sorry this has been a frustrating experience, I actually showed this exact workflow to a friend a few days ago as well so maybe we need to make it more clear in the docs that we don't do this

I hope this helps

Paul

**Comment by joeduffy** [comment]
Here is the issue tracking "refresh by default": https://github.com/pulumi/pulumi/issues/2247.

**Comment by jre21** [comment]
I'll respond in the earlier issue so I'm not further fragmenting discussion on the topic.  Feel free to close this issue as a duplicate.

**Comment by stack72** [comment]
Thanks so much @jre21 - this type of feedback really helps us understand the frustrations and the usecases that people expect so I really appreciate it

Paul
