### ISSUE TITLE
aws.lambda.CallbackFunction arguments doesn't match aws.lambda.Function

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi-aws#1649]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

Expected: 

`aws.lambda.CallbackFunction()` arguments doesn't match `aws.lambda.Function()`. Specifically `CallbackFunction` class doesn't take Role ARN, or Policy ARN with pulumi.Output<> type support. `policies` property only takes string[], `role` property only takes `aws.iam.Role` class, not ARN or ID, this makes it necessary to pass around the actual `aws.iam.Role` class value, which is not always the best case.

Actual: 
`CallbackFunction()` takes RoleARN, or PolicyARN with pulumi.Output type support.

**Comment by shinebayar-g** [comment]
Well in that case, could it be improved to support this?

**Comment by lukehoban** [comment]
The type of `policies` being prompt and not `Input` is tracked in https://github.com/pulumi/pulumi-aws/issues/995 and ultimately can't be addressed until https://github.com/pulumi/pulumi/issues/4834#issuecomment-644827733 is addressed in core Pulumi.

The `role` input not accepting an Input<ARN> as an input is though something that we could support, so I'll leave this open to track that.
