### ISSUE TITLE
DynamoDb `replicas` field always shows update

### ISSUE THREAD

**Issue by dmattia** [pulumi/pulumi-aws#1653]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I had a DynamoDb table that I managed using another service that I wanted to import into Pulumi. Using the `import` opt, I could find the resource, but it told me that the replica configuration had a diff, as shown in this image:

<img width="394" alt="Screen Shot 2021-10-07 at 9 23 27 AM" src="https://user-images.githubusercontent.com/8922077/136404265-4c5758f4-fda3-49d3-aa6c-5df44eb89480.png">

I was able to eventually import by adding `ignoreChanges: ['replicas']`, but now each `pulumi up` shows the same diff from that image unless I leave in the `ignoreChanges` block, even though as far as I can tell nothing should change.

### Steps to reproduce

1. Create a DynamoDb table with read replicas in the AWS console
2. Create a pulumi resource that matches it exactly (steps 1 and 2 can be done easily by creating the table in pulumi, then deleting the table from state)
3. Import the table into the resource
4. run pulumi up

Expected: No changes would appear in the diff
Actual: The `replicas` field shows a diff

**Comment by mikhailshilkov** [comment]
I tried reproducing this issue today but failed to do so. My steps:

1. Create a global table with two replicas. I used this program:
```
import * as aws from "@pulumi/aws";

const example = new aws.dynamodb.Table("example", {
    attributes: [{
        name: "TestTableHashKey",
        type: "S",
    }],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "TestTableHashKey",
    replicas: [
        {
            regionName: "us-east-2",
        },
        {
            regionName: "us-west-2",
        },
    ],
    streamEnabled: true,
    streamViewType: "NEW_AND_OLD_IMAGES",
});
```
2. Deployed the above from stack A.
3. Imported the same resource in stack B.
4. Pasted the generated program
```
import * as aws from "@pulumi/aws";

const example = new aws.dynamodb.Table("example", {
    attributes: [{
        name: "TestTableHashKey",
        type: "S",
    }],
    billingMode: "PAY_PER_REQUEST",
    hashKey: "TestTableHashKey",
    name: "example-1904f44",
    pointInTimeRecovery: {
        enabled: false,
    },
    replicas: [
        {
            regionName: "us-west-2",
        },
        {
            regionName: "us-east-2",
        },
    ],
    streamEnabled: true,
    streamViewType: "NEW_AND_OLD_IMAGES",
    ttl: {
        attributeName: "",
    },
}, {
    protect: true,
});
```
5. Ran `pulumi up` and received no diff.

I'll assume the issue has been fixed since 2021.
