### ISSUE TITLE
aws.route53.Zone cannot access the `name` output

### ISSUE THREAD

**Issue by dmattia** [pulumi/pulumi-aws#1654]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Calling `aws.route53.Zone.get('zone', <some_hosted_zone_id>)` returns a `Zone` object, but it is not currently possible to my understanding to get the domain name of the hosted zone. The domain name would likely be under the `name` field, but when I access `zone.name` I see the name of the lookup in pulumi's state, not the name of the Route53 Hosted zone.

### Steps to reproduce

1. Create a hosted zone
2. Call `const zone = aws.route53.Zone.get('zone', <some_hosted_zone_id>)`
3. Use `zone.name` in any other resource
4. Check the preview output, noticing that it is not the domain name of the hosted zone that you have access to

Expected: Being able to access the domain name of a hosted zone
Actual: Getting the name of the zone in pulumi state

**Comment by aureq** [comment]
@dmattia Is this still happening?
