### ISSUE TITLE
v4.24.0 introduced Go SDK dependency on unreleased pulumi SDK

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#1661]
This release moved the Go SDK to depend on `v3.14.1-0.20211007222624-789e39219452`, which is an unreleased version.  The SDK should always depend on released versions of its dependencies as these are required to be pulled into user programs.

It is not clear that this change was necessary to update the codegeneration version as needed for https://github.com/pulumi/pulumi-aws/pull/1658/.

**Comment by lukehoban** [comment]
It appears that a similar change was made to `pulumi-cloud-init` in https://github.com/pulumi/pulumi-cloudinit/commit/58e5af014148ad1d39bda5435598507c5f5ea04c.

**Comment by stack72** [comment]
Without adding this, a build of the go SDK was yielding an error regarding the new type added to register the input types as it wasn't in the version of Pulumi that the sdk referenced

**Comment by stack72** [comment]
I can now see that this new func was added in 3.14.0 so I can change the SDK to use that version
