### ISSUE TITLE
Can't create a Target Group in C#

### ISSUE THREAD

**Issue by MvnTruong** [pulumi/pulumi-aws#1671]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When I try to create a target group, I get an error which prevents the rest of my `pulumi up` command from working. I'm using version `4.25.0`. I've tried dropping down many versions and they all produce the same errror.

Note that error only pops up intermittently. Most of the time, I will get the error, but in rare occasions (< 5% of the time) I don't get an error.

### Steps to reproduce
1. Start a new C# project with `pulumi new aws-csharp`
2. Create a new target group within the stack (this is an exerpt straight out of the [samples](https://github.com/pulumi/examples/blob/master/aws-cs-fargate/Infra/FargateStack.cs) but using `Pulumi.Aws.LB` instead of the deprecated `Pulumi.Aws.ElasticLoadBalancingV2` (which also produces the same error)
```cs
using Pulumi;
using Ec2 = Pulumi.Aws.Ec2;
using Elb = Pulumi.Aws.LB;

class MyStack : Stack
{
    public MyStack()
    {
        // Read back the default VPC and public subnets, which we will use.
        var vpc = Output.Create(Ec2.GetVpc.InvokeAsync(new Ec2.GetVpcArgs { Default = true }));
        var vpcId = vpc.Apply(vpc => vpc.Id);
        var webTg = new Elb.TargetGroup("web-tg", new Elb.TargetGroupArgs
        {
            Port = 80,
            Protocol = "HTTP",
            TargetType = "ip",
            VpcId = vpcId
        });
    }
}
```
3.  Run with `pulumi up`

Expected: Everything to run fine and the AWS target group should be generated

Actual:
```
Diagnostics:
  pulumi:pulumi:Stack (app-dev):
    error: Running program 'app.dll' failed with an unhandled exception:
    System.InvalidOperationException: Expected System.Double but got System.String deserializing Pulumi.Aws.LB.TargetGroup.deregistrationDelay
       at object Pulumi.Serialization.Converter.ConvertObject(string context, object val, Type targetType)
       at OutputData<object> Pulumi.Serialization.Converter.ConvertValue(string context, Value value, Type targetType, ImmutableHashSet<Resource> resources)
       at async Task Pulumi.Deployment.CompleteResourceAsync(Resource resource, bool remote, Func<string, Resource> newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary<string, IOutputCompletionSource> completionSources)
```

**Comment by MvnTruong** [comment]
@stack72  I can confirm this is now working across all my systems. Amazing work, thank you very much for fixing this!

**Comment by stack72** [comment]
Thanks for checking back on this issue @MvnTruong
