### ISSUE TITLE
bug: pulumi not deleting AWS Spot instances

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-aws#1673]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hi everyone,

When i try to delete AWS spotinstances (aws-classic provider), it does not delete them. I need to terminate the instances by hand.

```go
spotInstanceRequest, err := ec2.NewSpotInstanceRequest(ctx, "control-plane", &ec2.SpotInstanceRequestArgs{
				Ami:              pulumi.StringPtr("ami-05f7491af5eef733a"),
				InstanceType:     pulumi.StringPtr("c4.xlarge"),
				Ipv6AddressCount: pulumi.IntPtr(1),
				KeyName:          keyPair.KeyName,
				SubnetId:         subnet.ID(),
				VpcSecurityGroupIds: pulumi.StringArray{
					newSecurityGroup.ID(),
				},
			})
			if err != nil {
				return err
			}
```

### Steps to reproduce

1. Create a pulumi deployment with the aws-classic provder, use  ec2.NewSpotInstanceRequest
2. pulumi up -> everything gets deployed
3. pulumi destroy -> Stuck on delete 

Expected: Pulumi terminates spot instances
Actual: Not delete the spot instances

**Comment by mikhailshilkov** [comment]
I tried reproducing this error today with the following program:

```ts
import * as aws from "@pulumi/aws";

const ami = aws.ec2.getAmi({
    filters: [
        { name: "name", values: ["amzn-ami-hvm-*-x86_64-ebs"] },
    ],
    owners: ["137112412989"], // Amazon
    mostRecent: true,
}).then(result => result.id);

const cheapWorker = new aws.ec2.SpotInstanceRequest("cheapWorker", {
    ami: ami,
    instanceType: "c4.xlarge",
    spotPrice: "0.03",
    tags: {
        Name: "CheapWorker",
    },
});
```

It succeeds both on `up` and `destroy`. I'll assume the issue has been fixed. If anyone still experience the problem, please provide a repro for it.
