### ISSUE TITLE
Missing EC2 instance types

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws#1674]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It appears some recent [EC2 instance types](https://aws.amazon.com/about-aws/whats-new/2021/07/introducing-new-amazon-ec2-g4ad-instance-sizes/) are currently missing in this provider.

* `g4ad.xlarge`
* `g4ad.2xlarge`

These have been released in late July 2021.

Thanks

**Comment by stack72** [comment]
Closed as part of #1856
