### ISSUE TITLE
ECS Cluster "name" argument wrong description

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [pulumi/pulumi-aws#1678]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The `name` argument has a wrong description: https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/ecs/cluster.py#L29 

It was changed by d7d3d36b7324981b15c27397b80ee7159552de01

Expected:  "The name of the cluster (up to 255 letters, numbers, hyphens, and underscores)"
Actual:  "Name of the setting to manage. Valid values: `containerInsights`."

**Comment by lukehoban** [comment]
This appears to be another instance of https://github.com/pulumi/pulumi-terraform-bridge/issues/529.
