### ISSUE TITLE
Creating RabbitMQ broker fails during preview

### ISSUE THREAD

**Issue by bryanmig** [pulumi/pulumi-aws#1686]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Creating a RabbitMQ broker fails after upgrading to `@pulumi/aws@4.26.0` with the following errors:
```
  aws:mq:Broker (developInfrastructureRabbitmq):
    error: aws:mq/broker:Broker resource 'developInfrastructureRabbitmq' has a problem: Missing required argument: The argument "broker_name" is required, but no definition was found.. Examine values at 'Broker.BrokerName'.
    error: aws:mq/broker:Broker resource 'developInfrastructureRabbitmq' has a problem: Invalid or unknown key. Examine values at 'Broker.BrokerName'.
```

Likely related to https://github.com/pulumi/pulumi-aws/pull/1680 or https://github.com/pulumi/pulumi-aws/pull/1685

### Steps to reproduce

```

  const broker = new aws.mq.Broker("developInfrastructureRabbitmq", {
    applyImmediately: true,
    brokerName: "developInfrastructureRabbitmq"",
    engineType: "RabbitMQ",
    engineVersion: "3.8.22",
    deploymentMode: "SINGLE_INSTANCE",
    publiclyAccessible: true,
    hostInstanceType: "mq.t3.micro",
    subnetIds: params.vpc.publicSubnetIds.then((subnetIds) => [subnetIds[0]]),
    users: [
      {
        username: config.require("managementUser"),
        password: config.requireSecret("managementPassword")
      }
    ]
  });

```

Expected:  Broker is created or left unchanged if already created
Actual:  Error occurs during preview

Reverting to `4.25.0` allows the stack updates to proceed as expected.

**Comment by Sodki** [comment]
Changelog for pulumi-aws 4.26.0 mentions:
```
Add support for autonaming aws.mq.Broker resources
```
Safe to assume that the problem started with this.

**Comment by jwtje** [comment]
We are having the same issues with 4.26.0. Downgrading to 4.25.0 works.

**Comment by stack72** [comment]
Hi all

My apologies about this - I am sending a PR right now to fix it

Paul
