### ISSUE TITLE
duplicate argument 'id' in ResolverDnsSecConfig.get()

### ISSUE THREAD

**Issue by jamesfmilne** [pulumi/pulumi-aws#1695]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I upgraded python to v3.8 to work around https://github.com/pulumi/pulumi/issues/5621 with dynamic provider subclasses during `pulumi preview` or `pulumi refresh`.

This newer version of python has stricter checking on duplicate arguments and is failing during `pulumi up` with:

```
      File "/home/.../venv/lib64/python3.8/site-packages/pulumi_aws/route53/resolver_dns_sec_config.py", line 231
        def get(resource_name: str,
        ^
    SyntaxError: duplicate argument 'id' in function definition
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

This is using pulumi-aws version 4.27.0 which is the current as of writing (08/11/2021)

### Steps to reproduce

1. Upgrade to python38 on CentOS 8
2. Set python38 as the default interpreter (sudo alternatives --set python3 /usr/bin/python3.8)
3. Delete or move any existing venv directory in your checkout
4. Run `pulumi up` to regenerate the venv then provision the stack
5. Run into this above error when parsing the resolver_dns_sec_config.py file

**Comment by jamesfmilne** [comment]
I worked around this by patching resolver_dns_sec_config.py to rename the second argument.
I then ran into the same problem in resolver_firewall_rule_group.py line 271.

**Comment by artemslobodian** [comment]
@jamesfmilne as a workaround you can use 4.26.0 version

**Comment by Detrous** [comment]
@jamesfmilne  as a workaround you can use 4.26.0 version

**Comment by alepinzon** [comment]
I have been experiencing this issue since today. Duplicate params (id) in the constructor method.

https://github.com/pulumi/pulumi-aws/blame/master/sdk/python/pulumi_aws/route53/resolver_dns_sec_config.py#L232

- :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
- :param pulumi.Input[str] id: The ID for a configuration for DNSSEC validation.

```
 @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            arn: Optional[pulumi.Input[str]] = None,
            id: Optional[pulumi.Input[str]] = None,
            owner_id: Optional[pulumi.Input[str]] = None,
            resource_id: Optional[pulumi.Input[str]] = None,
            validation_status: Optional[pulumi.Input[str]] = None) -> 'ResolverDnsSecConfig':
```

**Comment by stack72** [comment]
Hi all

I am currently in the process of fixing this right now

Paul
