### ISSUE TITLE
Add the `CloudWatchLambdaInsightsExecutionRolePolicy` to the AWS managed policies

### ISSUE THREAD

**Issue by caje731** [pulumi/pulumi-aws#1700]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like the value `CloudWatchLambdaInsightsExecutionRolePolicy` to be included as a constant in the AWS IAM managed policies. Besides making the IAM module more complete, this feature will also bring IDE auto-completion for the string-literal `CloudWatchLambdaInsightsExecutionRolePolicy` and avoid magic strings in code.

### Affected area/feature

The `ManagedPolicy` constant exported from `@pulumi/aws/types/enums/iam/index.d.ts`

Pulumi version: v3.17.0
Runtime: Typescript

**Comment by leezen** [comment]
This change would need to be made in schema so that all languages can pick up the value.

**Comment by guineveresaenger** [comment]
Dropping some reference notes for myself here

https://docs.aws.amazon.com/lambda/latest/dg/monitoring-insights.html
