### ISSUE TITLE
Uploading an object larger than 5GB to an S3 bucket fails

### ISSUE THREAD

**Issue by cpcloud** [pulumi/pulumi-aws#1703]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Problem:

Uploading a file asset larger than 5GB to an S3 bucket fails. In my case, this is a VHD for a custom AMI. The VHD can be uploaded successfully with `aws s3 cp`.

Presumably, this is because Pulumi is trying to use a single PUT request to upload the entire file asset and thus hits [the AWS limit](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html).

Notably, a similar image built for GCP uploads just fine to GCS, likely because GCP allows request sizes of up to 5TB.

### Solution:

I assume that `aws s3 cp` is making use of multipart uploads, and I would expect that Pulumi would need to do the same (through the SDK of course).

### Affected area/feature

I don't know exactly where this lies, but if someone can point me to where the code that ultimately calls into the AWS API I would be willing to implement this feature.

**Comment by cpcloud** [comment]
This issue exists upstream in Terrform, and I've [submitted a PR](https://github.com/hashicorp/terraform-provider-aws/pull/21727) to address it there.

Would `pulumi-aws` automatically pick this behavior up when the next version of Terraform is released?

I'm having a bit of trouble understanding how the Pulumi AWS SDK ultimately translates into AWS SDK/API calls.

**Comment by leezen** [comment]
@cpcloud Yes, `pulumi-aws` would pick up this behavior from an upstream release. Thanks for finding the issue and submitting a PR to improve the behavior!

**Comment by cpcloud** [comment]
Looks like this is in https://github.com/pulumi/pulumi-aws/releases/tag/v4.34.0 since my PR to the terraform provider update [made it into v3.70](https://github.com/hashicorp/terraform-provider-aws/pull/21727#issuecomment-1007023490).

Huzzah!
