### ISSUE TITLE
LifecyclePolicyPolicyDetailsScheduleCreateRule.times accepts str not list

### ISSUE THREAD

**Issue by turgay** [pulumi/pulumi-aws#1704]
There is an inconsistency between the doc (including the doc in the doc) and the code itself in LifecyclePolicyPolicyDetailsScheduleCreateRule.

The example should be updated to:
 times=["23:45"] should be  times="23:45" in LifecyclePolicyPolicyDetailsScheduleCreateRuleArgs 

File: [themes/default/content/registry/packages/aws/api-docs/dlm/lifecyclepolicy/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/dlm/lifecyclepolicy/)

**Comment by mikhailshilkov** [comment]
For better or worse, there is no example like this in the docs anymore. I'll close the issue as not currently actionable.
