### ISSUE TITLE
No support for IoT Thing Groups

### ISSUE THREAD

**Issue by napalm684** [pulumi/pulumi-aws#1707]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It does not appear that you have the ability to create IoT Thing Groups via the AWS provider.

**Comment by leezen** [comment]
This was added upstream recently and picked up in https://github.com/pulumi/pulumi-aws/pull/1713
