### ISSUE TITLE
Unable to create AWS CloudWatch MetricAlarm more than once

### ISSUE THREAD

**Issue by rozek1997** [pulumi/pulumi-aws#1710]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

AWS module version: 4.28.0
Language: Javascript

 Unable to create AWS CloudWacth MetricAlarm more than once. Despite of giving alarm unique name, URN stays the same for all MetricAlarms, and pulumi is thriving an error `Duplicate resource URN 'urn:pulumi:integration::route-optimizer-web::aws:cloudwatch/metricAlarm:MetricAlarm::'; try giving it a unique name`. Any option to fix that quickly?

## JS function that create MetricAlarm
![Function that create MetricAlarm](https://user-images.githubusercontent.com/38226876/142255058-77b51df6-6c16-4581-8542-46436ebfcfeb.png)

## Detail output on Pulumi up. 

As you see URN is insensitive to any name changes, and doesn't include the MetricAlarm name. Consequently pulumi throws an duplication error.

![Detail output on pulumi up](https://user-images.githubusercontent.com/38226876/142255200-1b09770e-17a7-445f-aa4d-179957d06d9e.png)

Expected:  FIx the bug or provider the solution to create MeticAlarm more that once
Actual:  Unable to create AWS CloudWatch MetricAlarm more than once

**Comment by leezen** [comment]
It looks like you're trying to feed an input into the actual resource name, which you cannot do, which is likely why the rest of the URN in the error message is blank instead of having any of the string you intended.

**Comment by rozek1997** [comment]
@leezen I don't get it. How it should look like, so I will be able to pass the dynamic values to resource name.  I passed values to resources name using `pulumi.interpolation` many many times at it worked, but it this specific use case it doesn't.

**Comment by leezen** [comment]
@rozek1997 There are two 'names': 1) the name used by a provider, also known as the physical name, and often referenced as `name` within the properties bag you pass to the resource and 2) the logical name referenced within the program (which turns into a Pulumi URN. See also: https://www.pulumi.com/docs/troubleshooting/faq/#resource-names and https://www.pulumi.com/blog/infrastructure-as-code-resource-naming/). The logical name doesn't accept outputs (see https://github.com/pulumi/pulumi/issues/5234)
