### ISSUE TITLE
Extend s3.BucketNotification for usage with EventBridge

### ISSUE THREAD

**Issue by wofl** [pulumi/pulumi-aws#1723]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

AWS S3 Buckets can directly send Events to EventBridge without other intermediate resources involved. This feature is potentially pretty new (included in AWS-CLI since Version 2.4.3). Instructions how to enable it through the console, aws-cli and REST-API are found [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-event-notifications-eventbridge.html). Neither the aws-classic nor the aws-native packages include anything to provide access to this feature as far as I can tell - althrough they most certainly should.

### Affected area/feature

aws-classic Integration
(aws-native Integration)

**Comment by wofl** [comment]
After some investigation I think this should be added to the s3.BucketNotification Inputs, doesn't it?

**Comment by leezen** [comment]
On the classic side, this is tracked in https://github.com/hashicorp/terraform-provider-aws/issues/22013 upstream.
On the native side, it doesn't look like this is supported in the AWS schema yet `aws cloudformation describe-type --type RESOURCE --type-name "AWS::S3::Bucket"`

**Comment by lukehoban** [comment]
This is available now: https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketnotification/#eventbridge_python.
