### ISSUE TITLE
Lake Formation Permissions issue not resolved by release 4.19

### ISSUE THREAD

**Issue by ArnoPauw** [pulumi/pulumi-aws#1744]
Release [4.19](https://github.com/pulumi/pulumi-aws/blob/master/CHANGELOG.md#4190-2021-09-03) did not resolve issue [#1531 ] where AWS Lake Formation Permissions do not work.

It would seem from the pull request, [#1614](https://github.com/pulumi/pulumi-aws/pull/1614/files), that the contributor might not have included the intended changes. Intended changes might have been included in a different pull request but I was unable to find any such PR.

Reproduction steps and result remains the same as stated in [#1531 ] while running @pulumi/aws version 4.32
Input
```
	new aws.lakeformation.Permissions(
		`xxxxxxxxxxxxxxxxxxxaaaaaaaaaaaxxxxxxxx`,
		{
			permissions: ['ALL'],
			principal:
				'arn:aws:iam::xxxxxxxxxxxxxx:role/service-role/AWSGlueServiceRole-xxxxxxxxx',
			database: {
				name: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
			},
		},
	);
```

Output and Version 
![Untitled](https://user-images.githubusercontent.com/25772290/170853465-ac6274f3-08a9-4987-bc92-f93f8cf9f9af.png)

I've also tested with pulumi/aws version 4.19 and got the same results.

**Comment by mikhailshilkov** [comment]
It looks like the bridge issue got resolved. I tested the following repro today with 6.4.0 and it deploys just fine:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("demo-bucket", {
});

const awsGlueCatalogDatabase = new aws.glue.CatalogDatabase("demo_aws_glue_catalog_database", {
    name: "mycatalogdatabase",
});

const awsGlueCatalogTable = new aws.glue.CatalogTable("demo_aws_glue_catalog_table", {
    databaseName: awsGlueCatalogDatabase.name,
    name: "mycatalogtable",
});

const lakeformations = new aws.lakeformation.Resource("demo-lakeformation", {arn: bucket.arn});

const datalakeuser = new aws.iam.User("demo-datalakeuser");

// Export the resources
export const bucketName = bucket.id;
export const glue_database_name = awsGlueCatalogDatabase.name;
export const glue_database_catalog_name = awsGlueCatalogTable.name;
export const lakeformations_name = lakeformations.id;
export const datalakeuser_name = datalakeuser.name;

const lakeformation_permissions = new aws.lakeformation.Permissions("demo-lakepermissions", {
 permissions: ["DESCRIBE"],
 principal: datalakeuser.arn,
 database: {
     name: awsGlueCatalogDatabase.name,
 }
});
```

I'll go ahead and resolve the issue.
