### ISSUE TITLE
Support for AWS OpenSearch

### ISSUE THREAD

**Issue by kedrzu** [pulumi/pulumi-aws#1747]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Recently AWS decided to fork ElasticSearch with their own product OpenSearch and made according changes to its offering. 
AWS CDK already allows to use new OpenSearch service:
https://docs.aws.amazon.com/cdk/api/v1/docs/aws-opensearchservice-readme.html
https://docs.aws.amazon.com/cdk/api/v1/docs/aws-elasticsearch-readme.html#migrating-to-opensearch

Please add support for OpenSearch within Pulumi SDK.

**Comment by leezen** [comment]
Related upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/20853

**Comment by leezen** [comment]
One alternative you could try is using the native provider's resource: https://www.pulumi.com/registry/packages/aws-native/api-docs/opensearchservice/domain/

**Comment by jerry153fish** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/20853 has been merged. Can we update the upstream support?
