### ISSUE TITLE
[docs/examples] Bucket policy attach example sets rather than attaches policy

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-aws#1750]
File: [themes/default/content/registry/packages/aws/api-docs/s3/bucketpolicy/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketpolicy/)

This resource set the policy rather than attaching a policy. That means that if one would like to add more than one policy, there will be a race condition and one policy would get override by the other.

**Comment by lukehoban** [comment]
> This resource set the policy rather than attaching a policy. That means that if one would like to add more than one policy, there will be a race condition and one policy would get override by the other.

I believe this is the by-design behaviour of this resource.  Per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html#cfn-s3-bucketpolicy-policydocument there is only one policy that can be attached.

You can use `replaceOnChanges` and `deleteBeforeReplace` to control the Pulumi side of this to give flexibility in how this is managed - but AWS does require that you define a single policy per bucket.

Closing out as by-design for now.
