### ISSUE TITLE
When Importing a MainRouteTableAssociation, pulumi preview works only with empty strings for args

### ISSUE THREAD

**Issue by peterhriser** [pulumi/pulumi-aws#1761]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Recently I have encountered a bug when trying to import a `aws.ec2.MainRouteTableAssociation` object using ResourceOptions. 

The preview statement shows the following when the parameters are filled in correctly:
```
 aws:ec2:MainRouteTableAssociation            route_table_association_private                import     [diff: +routeTableId,vpcId]; 1 warning
```
This implies that the values pulled in the comparison are empty. 

The only way to stop this diff is to set the `vpc_id` and the `route_table_id` parameters to empty strings in the object creation.  

This happens even when putting the id strings into the fields directly.

I suspect the import command is not pulling the fields correctly for this particular Resource
### Steps to reproduce

1. Import a MainRouteTableAssociation using `ResourceOptions(import_=...`
2. Run `pulumi preview`

Expected: The supplied required parameters are used
Actual: supplied parameters are not compared against the correct values.

**Comment by stack72** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
