### ISSUE TITLE
credit specification of a t4 instance ignored

### ISSUE THREAD

**Issue by rafalkrupinski** [pulumi/pulumi-aws#1779]
## Hello!
Hi, I'm creating a t4g instance with 'standard' cpu credit but it's created with 'unlimited'

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I use this object to start t4Nano instance

```typescript
new aws.ec2.Instance('bastion', {
    instanceType: aws.ec2.InstanceType.T4g_Nano,
    ami,
    creditSpecification: { cpuCredits: 'standard' },
});
```

But console shows its credit specification is 'unlimited' and the aws cli doesn't show anything regarding credits.

I was able to create identical instance with standard CPU credits via aws console.

version v3.22.1

**Comment by danielrbradley** [comment]
This appears to be an upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/15156

**Comment by rafalkrupinski** [comment]
Ah, the link has a workaround too, thank you @danielrbradley 

Should the issue remain open until upstream bug is closed?

**Comment by danielrbradley** [comment]
Yup, happy to leave open to help direct anyone else who encounters the issue 👍

**Comment by mikhailshilkov** [comment]
The upstream issue got closed in June 2022, so I'm closing this one too
