### ISSUE TITLE
Elasticache outputs do not output proper strings

### ISSUE THREAD

**Issue by mkabatek** [pulumi/pulumi-aws#1783]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```
root@83e295cb5664:/# pulumi version
v3.22.1
root@83e295cb5664:/# node --version
v12.22.9

"@types/node": "13.11.1",
"ts-node": "^8.2.0",
"typescript": "^3.8.3"
"@pulumi/aws": "^1.23.0",
"@pulumi/awsx": "^0.19.2",
"@pulumi/cloud-aws": "^0.18.2",
"@pulumi/pulumi": "^1.11.1",
```

1. Create an elasticache cluster
2. Try and access `cacheNodes` or `clusterAddress` Outputs

Expected: 

As far as I can tell these outputs should be able to be accessed in the following way.

<img width="851" alt="Screen Shot 2022-01-25 at 8 46 49 AM" src="https://user-images.githubusercontent.com/1764486/151011365-105c520e-d65e-439b-8dae-46714d56b6c6.png">

One be able to access `cacheNodes` and `clusterAddress`. I can access similar hostnames using RDS in the exact same way.

Actual: 

Notice you will get an error

```
Calling [toString] on an [Output<T>] is not supported. To get the value of an Output<T> as an Output<string> consider either: 1: o.apply(v => `prefix${v}suffix`) 2: pulumi.interpolate `prefix${v}suffix` See https://pulumi.io/help/outputs for more details. This function may throw in a future version of @pulumi/pulumi
```

Full TypeScript code below to setup elastiCache.

```
import * as pulumi from '@pulumi/pulumi'
import * as aws from '@pulumi/aws'

import {
  ENV_LOWER,
} from '../env'

class RedisSetup extends pulumi.ComponentResource {

  public RedisSetupOutput: any;

  constructor(name: string, vpc: any, cluster: any, opts: any) {
    // Register this component with name examples:S3Folder
    super("backend:portalInfrastructure:redis", name, {}, opts)
    console.log('opts', opts)

    let securityGroupIds = cluster.securityGroups.map((g:any) => g.id)

    let redis = new aws.elasticache.Cluster(`redis-${ENV_LOWER}`, {
      engine: "redis",
      engineVersion: "3.2.10",
      nodeType: "cache.t3.micro",
      numCacheNodes: 1,
      parameterGroupName: "default.redis3.2",
      port: 6379,
      securityGroupIds: securityGroupIds
    });

    this.RedisSetupOutput = {
      redisHost : redis.clusterAddress.apply(e => e),
      redis: redis
    }

    // For dependency tracking, register output properties for this component
    this.registerOutputs({
      RedisSetupOutput: this.RedisSetupOutput
    })
  }
}

export default RedisSetup;

```

**Comment by mkabatek** [comment]
Pretty sure this is a bug with `pulumi-aws` this works using and identical procedure using `MemoryDB` code below:

```

    let securityGroupIds = cluster.securityGroups.map((g:any) => g.id)
    
    let redisSubnets = new aws.memorydb.SubnetGroup(`${name}-redis-subnets-${ENV_LOWER}`, {
      subnetIds: vpc.publicSubnetIds,
    })

    // ------------ MEMORYDB ------------
    const redis = new aws.memorydb.Cluster(`${name}-redis-${ENV_LOWER}`, {
      aclName: `open-access`,
      nodeType: "db.t4g.small",
      numShards: 1,
      securityGroupIds: securityGroupIds,
      snapshotRetentionLimit: 7,
      subnetGroupName: redisSubnets.id
    });


    this.RedisSetupOutput = {
      redishost : redis.clusterEndpoints.apply(e=>e[0].address),
      redis: redis
    }

    // For dependency tracking, register output properties for this component
    this.registerOutputs({
      RedisSetupOutput: this.RedisSetupOutput
    })
```

**Comment by jkodroff** [comment]
@mkabatek This question is a better fit for the [Pulumi Community Slack](https://slack.pulumi.com/) where the problem will get more eyes on it.

I'd also suggest starting with a more simplified example: Try starting with a simple declaration of resources (no `ComponentResource`), and continue to add code until you're able to more precisely isolate the issue.

**Comment by mkabatek** [comment]
@jkodroff I will specify what the actual issue is here for people having this problem in the future, since I ended up figuring this out. 

The problem is that the `Elasticache` within pulumi is not unwrapping the output in the way that it "should" I suppose, or at least it doesn't unwrap the output in the way that `RDS` does.

The simple example below is a comparison between `RDS`  and. `Elasticache`:

```
    //  ------------ RDS ------------
    let db = new aws.rds.Instance(`${name}-postgres-${ENV_LOWER}-`, {
      engine: 'postgres',
      instanceClass: 'db.t3.micro',
      allocatedStorage: 20,
      dbSubnetGroupName: dbSubnets.id,
      vpcSecurityGroupIds: securityGroupIds,
      // TODO only needs to be publicly accessible
      // to run migrations from external host
      publiclyAccessible: true,
      ...DB_CONN,
      tags: {
        'env':ENV_LOWER
      },
      skipFinalSnapshot: true
    })

    this.DBSetupOutput = {
      dbhost : db.endpoint.apply(e => e.split(":")[0]),
      db: db
    }
```



```
    //  ------------ ELASTICACHE ------------
    let redis = new aws.elasticache.Cluster(`${name}-redis-${ENV_LOWER}`, {
      engine: "redis",
      engineVersion: "3.2.10",
      nodeType: "cache.t3.micro",
      numCacheNodes: 1,
      parameterGroupName: "default.redis3.2",
      port: 6379,
      subnetGroupName: redisSubnets.id,
      securityGroupIds: securityGroupIds
    });


    this.RedisSetupOutput = {
      redishost : redis.cacheNodes[0].apply(a=>a.address),
      redis: redis
    }
```


In the above example. For `RDS` I can now pass `this.DBSetupOutput.dbhost` to other components and I will get the actual underlying value of the endpoint for the `RDS` instance.

Contrast this to `Elasticache` above, one cannot simply pass `this.RedisSetupOutput.redishost` and expect to get the underlying address of the elasticache node to other components. 

In the `Elasticache` example above you will be greeted with the following error:

```
Calling [toString] on an [Output<T>] is not supported. To get the value of an Output<T> as an Output<string> consider either: 1: o.apply(v => `prefix${v}suffix`) 2: pulumi.interpolate `prefix${v}suffix` See https://pulumi.io/help/outputs for more details. This function may throw in a future version of @pulumi/pulumi
```

In order to use the underlying value of `address` for `Elasticache` one has to do the following

```
this.RedisSetupOutput.redishost.apply(address => {

    // do stuff here with the address

})
```

I personally think this is a bug, and that the two components should handle their outputs in the same way by automatically unwrapping the underlying value. e.g. `Elasticache` outputs should behave the same way that `RDS` handles it's output 🤷‍♀️

Either way that's for pointing me towards the slack. I posted this for reference if this is determined to be a bug.
