### ISSUE TITLE
When adding new entry to ManagedPrefixList get Version Error

### ISSUE THREAD

**Issue by peterhriser** [pulumi/pulumi-aws#1784]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hello!
I am trying to add a new entry to a ManagedPrefixList. In preview, the diff correctly shows the new entry however, when running up, it crashes with following error:
```
  aws:ec2:ManagedPrefixList (resource_name):
    error: 1 error occurred:
    	* updating urn:urn_of_resource: 1 error occurred:
    	* error updating EC2 Managed Prefix List (id): InvalidParameterValue: The specified value for version is not valid. The value must be greater than (1).
    	status code: 400, request id: id
```

Code showing deploy below:

```
        aws.ec2.ManagedPrefixList(
            "name",
            address_family="IPv4",
            entries=[
                aws.ec2.ManagedPrefixListEntryArgs(description="entry_{}".format(cidr), cidr=cidr) for cidr in cidrs
            ],
            max_entries=20,
        )
```
### Steps to reproduce

1. Created a prefix list in a separate deploy
2. Made a new deploy appending a new entry to the end
3. Preview showed correct diff
4. Deploy failed with error

The only other thing I did recently was change the stack name. But I had also applied that change and run a refresh before this error occurred

**Comment by pierskarsenbarg** [comment]
Bit more detailed example...

Run this:

```typescript
import * as aws from "@pulumi/aws";

new aws.ec2.ManagedPrefixList("mpl", {
    addressFamily: "IPv4",
    maxEntries: 5,
    entries: [{
        cidr: "86.28.229.82/32",
        description: "piers"
    },
        // {
        //     cidr: "10.0.0.1/32",
        //     description: "test1"
        // }
    ]
})
```

Then uncomment the commented out code and re-run the update.

**Comment by jordan52** [comment]
I am having the exact same issue. One additional behavior is every other time you run, there will be no error, but no changes either.  So, first error:

`* error updating EC2 Managed Prefix List (...) InvalidParameterValue: The specified value for version is not valid. The value must be greater than (
1).
` 

then next run, no error but:

`Resources:                                                                                                                                                                    
    ~ 1 updated                                                                                                                                                               
    2 unchanged `

run it again, error, then none, and so on. I found at least 2 other people with the same issue on the pulumi slack aws channel.

**Comment by peterhriser** [comment]
As a follow up to this @jordan52 and @pierskarsenbarg. I found if you create individual ManagedPrefixListEntry resources and associate them with empty ManagedPrefixList, it is a functional work around

**Comment by jordan52** [comment]
@peterhriser - That would be extremely helpful, but I cannot get it to work. Looks like entries is readonly `readonly entries: pulumi.Output<outputs.ec2.ManagedPrefixListEntry[]>;` How do you associate pre-created prefix list entries with a managed list?

**Comment by jordan52** [comment]
Nevermind, I figured it out. Terraform docs say:

> NOTE on Managed Prefix Lists and Managed Prefix List Entries:
>Terraform currently provides both a standalone Managed Prefix List Entry resource (a single entry), and a Managed Prefix List resource with entries defined in-line. At this time you cannot use a Managed Prefix List with in-line rules in conjunction with any Managed Prefix List Entry resources. Doing so will cause a conflict of entries and will overwrite entries.

Which helps me understand the error. I guess the workaround is to 

```javascript
var pfl = new aws.ec2.ManagedPrefixList("mpl", {
    addressFamily: "IPv4",
    maxEntries: 5,
})
new ManagedPrefixListEntry(`${name}-e1`,{prefixListId: pfl.id, cidr: '123.123.123.123/32'})
new ManagedPrefixListEntry(`${name}-e2`,{prefixListId: pfl.id, cidr: '134.134.134.134/32'})
```
The issue I have now is you cannot add multiple entries at the same time. First entry runs ok, but the prefix list is in a modify states so the second fails unless you wait a while and try again. error is:

`* error creating EC2 Managed Prefix List Entry (pl-......): IncorrectState: The request cannot be completed while the prefix list (pl-...) is in the current state (modify-in-progress). Target state is: (modify-in-progress)`

So... getting there, but not quite.

**Comment by jordan52** [comment]
update: You can avoid the "modify-in-progress" error above if you run `pulumi up --paralllel=1`

**Comment by corymhall** [comment]
I just tested this out on the latest version and it cannot be reproduced.
