### ISSUE TITLE
Service disappeared while waiting for it to reach a steady state

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#179]
We saw an intermittent failure when updating PPCs just now:

```
Plan apply failed: creating urn:pulumi:learningmachine-ppc-prod::pulumi-service-ppc::cloud:service:Service$aws:ecs/service:Service::learningmachine-ppc-prod-updates: Service arn:aws:ecs:us-east-1:396386917111:service/learningmachine-ppc-prod-updates-99c2e88 disappeared while waiting for it to reach a steady state
```

The full log is available at https://api.travis-ci.com/v3/job/115796809/log.txt?log.token=DGdrKxgiMyHZ73itqw0oyw.

It seems likely this is related to the changes pertaining to https://github.com/pulumi/pulumi-cloud/issues/312.

**Comment by mmdriley** [comment]
> If `Partial(true)` has been called, then attributes for which `SetPartial("attribute")` was called will be read from the _new_ state, and other attributes will be read from the _old_ state.

I think we can read some intent here. `Partial(true)` means: these are the only attributes I want to care about right now, and all the others should stay the same. Seems especially useful in `Update` operations where things not updated don't have to be re-read.
