### ISSUE TITLE
AWS m6a instances not supported

### ISSUE THREAD

**Issue by clamo** [pulumi/pulumi-aws#1791]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The Pulumi doesn't support the latest m6a family instances.
m6a.large
m6a.xlarge
m6a.2xlarge
m6a.4xlarge
m6a.8xlarge
m6a.12xlarge
m6a.16xlarge
m6a.24xlarge
m6a.32xlarge
m6a.48xlarge

### Steps to reproduce

1. instanceType: "m6a.large"
2. Confirm that the IDE throws an error

Expected: 
Pulumi should've handled AWS m6a instance family.

Actual: 
Pulumi doesn't handle AWS m6a instance family.

**Comment by SharpEdgeMarshall** [comment]
Also m6i instance types are not supported

**Comment by clamo** [comment]
> Also m6i instance types are not supported

Fix for this particular issue was merged.
I'd write up a new issue about m6i then we can go from there.
