### ISSUE TITLE
pulumi sdk upgrade v2 to v3 is trying to re-create route 53 hosted zone.

### ISSUE THREAD

**Issue by Avishek-Gulshan** [pulumi/pulumi-aws#1802]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Hi Team, 

This is Avishek from Discovery, Inc.

We had created route53 hosted zone using pulumi sdk v2  and pulumi-aws-sdk v2. 
Now, we are upgrading pulumi sdk to v3 and pulumi-aws-sdk to v4 and somehow pulumi thinks we have updated our route53 hosted zone. which will create a network outage for us.

Is this an expected behavior? Can we do something about this? Any workaround?

**This upgrade will result in Downtime for us**

### Steps to reproduce

1. Create route53 hosted zone with pulumi sdk v2 
2. Upgrade sdk to v3
3. Try running pulumi Up

Expected: no changes should have been observed.
Actual: 
`  ~ name: "discovery.experimental.domain.com." => "discovery.experimental.domain.com"
    --outputs:--
  ~ domain: "Z0**************F" => output<string>                                                                                                                     Resources:               
    +-1 to replace
 `

**Comment by Frassle** [comment]
For now does this work correctly if you edit your code to add the "." to the end?

**Comment by Frassle** [comment]
Ah and I've found another issue about this with a proper fix to try: https://github.com/pulumi/pulumi-aws/issues/1144

**Comment by Avishek-Gulshan** [comment]
Thanks,
This resolves my issue https://github.com/pulumi/pulumi-aws/issues/1144 but, shouldn't these details be available on your migration doc?

**Comment by Frassle** [comment]
Probably, but I'll let someone from @pulumi/platform-integrations confirm that.

**Comment by mikhailshilkov** [comment]
Given this issue is very old and is related to v2/v3 when we are on v6 now, I'll go ahead and close it as non-actionable.
