### ISSUE TITLE
aws.apigateway.Deployment - Invalid or unknown key

### ISSUE THREAD

**Issue by ievgen-boink** [pulumi/pulumi-aws#1806]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I was trying to add Aws ApiGateway Deployment just by instructions from Pulumi docs : `https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/deployment/` 
And I got an error : "Invalid or unknown key".
<img width="549" alt="Screen Shot 2022-02-04 at 1 07 05 PM" src="https://user-images.githubusercontent.com/83655818/152580399-d6892a89-2fc2-4af2-81a2-89bbc1ca4976.png">

### Steps to reproduce

1. Just follow docs: 
```
  const exampleRestApi = new aws.apigateway.RestApi("exampleRestApi", {body: JSON.stringify({
      openapi: "3.0.1",
      info: {
          title: "example",
          version: "1.0",
      },
      paths: {
          "/path1": {
              get: {
                  "x-amazon-apigateway-integration": {
                      httpMethod: "GET",
                      payloadFormatVersion: "1.0",
                      type: "HTTP_PROXY",
                      uri: "https://ip-ranges.amazonaws.com/ip-ranges.json",
                  },
              },
          },
      },
  })});
  const exampleDeployment = new aws.apigateway.Deployment("exampleDeployment", {
      restApi: exampleRestApi.id,
      triggers: {
          redeployment: exampleRestApi.body.apply(body => JSON.stringify(body)).apply(toJSON => crypto.createHash('sha1').update(toJSON).digest('hex')),
      },
  });
  const exampleStage = new aws.apigateway.Stage("exampleStage", {
      deployment: exampleDeployment.id,
      restApi: exampleRestApi.id,
      stageName: "example",
  });
```

Expected: Success
Actual: Failed

**Comment by guineveresaenger** [comment]
Hi @ievgen-boink  

I could not reproduce this error - this seems like an AWS credentials issue: https://www.pulumi.com/docs/get-started/aws/begin/#configure-pulumi-to-access-your-aws-account

**Comment by ievgen-boink** [comment]
@guineveresaenger  Yes, You are right. It was aws provider issue. Thanks You a lot for a quick answer.
