### ISSUE TITLE
aws.codedeploy.DeploymentConfig replacement fails 

### ISSUE THREAD

**Issue by Sammakman** [pulumi/pulumi-aws#1807]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

a aws.codedeploy.DeploymentConfig replacement always fails because the config already exists. This appears to be because the `deploymentConfigName` is set to an explicit value and pulumi tries to replace create a replacement before deleting the resource. internally AWS will auto-generate a name for your deployment config if one is not provided. I the node SDK `deploymentConfigName` is a required value so a naming conflict always happens. In the Cloudformation docs DeploymentConfigName is not a required field https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentconfig.html#cfn-codedeploy-deploymentconfig-deploymentconfigname

I also tried to use the `deleteBeforeReplace` flag, however the delete will fail in AWS if there is a dependency on the DeploymentConfig. In my case a DeploymentGroup had a dependency on the deployment config. 

My current work around is to append the date to the end of the DeploymentConfig name so that there are no naming conflicts 
`deploymentConfigName: `${input.name}-deploy-config-${Date.now()}`,`

```
Diagnostics:
  aws:codedeploy:DeploymentConfig (service-name-deploy-config):
    error: 1 error occurred:
        * DeploymentConfigAlreadyExistsException: service-name-deploy-config already exists.
```

### Steps to reproduce

1. create a new deployment config 
``` 
const deploymentConfig = new aws.codedeploy.DeploymentConfig(`${input.name}-deploy-config`, {
    computePlatform: 'Lambda',
    deploymentConfigName: `deployment-config-name`,
    trafficRoutingConfig: {
      timeBasedLinear: {
        interval: 1,
        percentage: 25
      },
      type: 'TimeBasedLinear'
    }
  })
```
2. Update the deployment config, rerun `pulumi up` 
``` 
const deploymentConfig = new aws.codedeploy.DeploymentConfig(`${input.name}-deploy-config`, {
    computePlatform: 'Lambda',
    deploymentConfigName: `deployment-config-name`,
    trafficRoutingConfig: {
      timeBasedLinear: {
        interval: 1,
        percentage: 50
      },
      type: 'TimeBasedLinear'
    }
  })
```
3. The deployment should fail 

Expected: 
Actual:

**Comment by guineveresaenger** [comment]
Thank you for reporting this!

I reproduced this successfully on the most recent version of pulumi-aws today (subbing out `${input.name} for `test`) and it does indeed fail with the following output:

```
@guin:aws🦉 pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/guinevere/aws/dev/previews/86298021-9d38-4226-93b9-b6fbfd3f298e

     Type                                Name                Plan        Info
     pulumi:pulumi:Stack                 aws-dev                         
 +-  └─ aws:codedeploy:DeploymentConfig  test-deploy-config  replace     [diff: ~trafficRoutingConfig]
 
Resources:
    +-1 to replace
    1 unchanged

Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/guinevere/aws/dev/updates/2

     Type                                Name                Status                   Info
     pulumi:pulumi:Stack                 aws-dev             **failed**               1 error
 +-  └─ aws:codedeploy:DeploymentConfig  test-deploy-config  **replacing failed**     [diff: ~trafficRoutingConfig]; 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (aws-dev):
    error: update failed
 
  aws:codedeploy:DeploymentConfig (test-deploy-config):
    error: 1 error occurred:
    	* DeploymentConfigAlreadyExistsException: deployment-config-name already exists.
 
Resources:
    1 unchanged

Duration: 2s
```

This is most likely an upstream issue, as the Terraform provider also requires the DeploymentConfigName field: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_config
although I could find no open issue for this particular occurrence.

**Comment by stack72** [comment]
Hi @Sammakman 

Thanks for opening the issue here - whilst I was looking through the repo, I noticed that we don't take advantage of autonaming for this resource. Autonaming would indeed fix this up.

```
const deploymentConfig = new aws.codedeploy.DeploymentConfig(`${input.name}-deploy-config`, {
    computePlatform: 'Lambda',
    trafficRoutingConfig: {
      timeBasedLinear: {
        interval: 1,
        percentage: 25
      },
      type: 'TimeBasedLinear'
    }
  })
```

This would create a DeploymentConfig of the name `${input.name}-deploy-config-<random-suffix>` and any changes that would force a new resource would allow this to be created.

I am preparing the PR right now that fixes it

Paul
