### ISSUE TITLE
cognito IdentityPool - allowClassicFlow property defaults to false

### ISSUE THREAD

**Issue by piwysocki** [pulumi/pulumi-aws#1812]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'd like to create IdentityPool with empty parameter: "AllowClassicFlow". Based on AWS documentation it is not required: [https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_CreateIdentityPool.html#API_CreateIdentityPool_RequestSyntax](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_CreateIdentityPool.html#API_CreateIdentityPool_RequestSyntax)
However in IdentityPoolArgs it defaults to false:

`    /**
     * Enables or disables the classic / basic authentication flow. Default is `false`.
     */
    allowClassicFlow?: pulumi.Input<boolean>;`

### Steps to reproduce

1. Create identity pool:

`new aws.cognito.IdentityPool(
      "name",
      {
        identityPoolName: "name",
        allowUnauthenticatedIdentities: true,
      }
    );`

Expected: 

Identity Pool should be created with empty allowClassicFlow parameter

Actual: 

allowClassicFlow is false

We can see CreateIdentityPool event parameters in CloudTrail:

`    "requestParameters": {
        "allowClassicFlow": false,
        "identityPoolName": "name",
        "allowUnauthenticatedIdentities": true
    },`

it should be:

`    "requestParameters": {
        "identityPoolName": "test",
        "allowUnauthenticatedIdentities": true
    },`

Example: CloudWatch RUM app monitor wizard creates IdentityPool with empty allowClassicFlow parameter.

**Comment by viveklak** [comment]
This comes from the terraform schema: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_pool#allow_classic_flow
