### ISSUE TITLE
AWS Cognito User Pool errors out on update even though nothing is changed

### ISSUE THREAD

**Issue by seunggs** [pulumi/pulumi-aws#1813]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When updating AWS Cognito User Pool (i.e. `pulumi up` for the second time) without changing anything, it errors out:

```
* error updating Cognito User Pool (us-west-1_xxxxxxxxx): cannot modify or remove schema items
``` 

I also noticed that Cognito IdentityProvider resource also shows diffs, even though nothing was changed in code:
```
[diff: ~attributeMapping,providerDetails]
```

### Steps to reproduce
1. Create a Cognito User Pool via classic AWS package (i.e. `new aws.cognito.UserPool()`)
2. Run `pulumi up`
3. Run `pulumi up` again without changing any code

Expected: `pulumi up` should complete with no changes and no errors when no code is changed
Actual: It errors out instead: `* error updating Cognito User Pool (us-west-1_xxxxxxxxx): cannot modify or remove schema items`

**Comment by guineveresaenger** [comment]
Hi there! This appears to be an upstream bug:
https://github.com/hashicorp/terraform-provider-aws/issues/21654

**Comment by seunggs** [comment]
OK thanks. So just to confirm - nothing we can do but wait til that upstream issue is fixed?

**Comment by mnlumi** [comment]
The upstream bug has been closed. We should test to verify that this is no longer an issue. cc @mikhailshilkov

**Comment by mnlumi** [comment]
Verified that there is no longer an error generated with AWS 5.42.0.
