### ISSUE TITLE
ValidationError (Target group stickiness duration must be between 1 and 604800 seconds) while modifying or importing Loadbalancer

### ISSUE THREAD

**Issue by sampathkolachana** [pulumi/pulumi-aws#1824]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
`aws.lb.Loadbalancer` raises Validation error for target group stickiness. `duration` field doesn't accept `0` as a valid value but itseems to be default value (set by AWS?) when `enabled` is `False`. This causes errors while importing or updating LBs. 
```
Diagnostics:
  pulumi:pulumi:Stack (xxx):
    error: update failed
 
  aws:alb:Listener (web-lb-listener):
    error: 1 error occurred:
    	* updating urn:pulumi:xxxx::xxxx::aws:alb/listener:Listener::web-lb-listener: 1 error occurred:
    	* error modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-xxxx-x:xxxxxx:listener/app/portalalb/xxxx/xxxx): ValidationError: Target group stickiness duration must be between 1 and 604800 seconds
    	status code: 400, request id: 7f3be540-e797-46ef-a17e-xxx
```

My load balancer definition has `aws.lb.Listener.default_actions[0].forward.stickiness` set to `None`.

### Steps to reproduce

1. Create an `aws.lb.Listener` with target group stickiness with `duration=0`  and `enabled=False`
2. Pulumi raises validation error for target group stickiness duration field.

Expected: 
`duration=0` is accepted when `enabled=False`
Actual: 
`ValidationError`

**Comment by danielrbradley** [comment]
I _think_ this is likely an upstream issue. Are you able to either remove the whole stickiness block when not enabling, or just set the duration to 1 when setting enabled false.

**Comment by sampathkolachana** [comment]
I am not able to remove the stickiness block, the same validation on the `duration` field is raised if I do. The only way I am able to work around is by setting a non-zero duration with `enabled=False`

**Comment by mikhailshilkov** [comment]
Here is a test program that works for me:

```ts
import * as aws from "@pulumi/aws";

const defaultVpc = aws.ec2.getVpcOutput({default: true});
const defaultVpcSubnets = aws.ec2.getSubnetsOutput({
    filters: [
        {name: "vpc-id", values: [defaultVpc.id]},
    ],
});

const group = new aws.ec2.SecurityGroup("web-secgrp", {
    vpcId: defaultVpc.id,
    description: "Enable HTTP access",
    ingress: [{
        protocol: "tcp",
        fromPort: 80,
        toPort: 80,
        cidrBlocks: ["0.0.0.0/0"],
    }],
    egress: [{
        protocol: "-1",
        fromPort: 0,
        toPort: 0,
        cidrBlocks: ["0.0.0.0/0"],
    }],
});

const alb = new aws.lb.LoadBalancer("app-lb", {
    securityGroups: [group.id],
    subnets: defaultVpcSubnets.ids,
});

const targetgroup = new aws.lb.TargetGroup("targetgroup", {
	port: 80,
	protocol: "HTTP",
	targetType: "ip",
    stickiness: {
        enabled: false,
        type: "lb_cookie",
    },
	vpcId: defaultVpc.id })

const listener = new aws.lb.Listener("listener", {
    loadBalancerArn:alb.arn,
    port: 80,
    protocol: "HTTP",
    defaultActions:[{
        type:"forward",
        forward: {
            targetGroups: [{
                arn: targetgroup.arn,
            }]},
    }]});
```

changing `forward` to 

```
        forward: {
            stickiness: {
                enabled: false,
                duration: 0,
            },
            targetGroups: [{
                arn: targetgroup.arn,
            }]},
```

does yield the original error message - but I'm not sure if it's a problem? Could somebody chime in and explain if so?

I'll mark the issue as `awaiting-feedback` but if nobody responds within a couple of weeks I will probably close it.
