### ISSUE TITLE
AWS_SHARED_CREDENTIALS_FILE not working as expected

### ISSUE THREAD

**Issue by alexbowers** [pulumi/pulumi-aws#1827]
## Issue details

In my CI environment, I am trying to make use of `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` environment variables which are not in their default location. This is because these are provided by the CI environment as a `File` type of variable, so it's held in a temporary file for me.

I know that the files and credentials are correct because in the CI scripts section I am running `aws sts get-caller-identity --profile production` and I can see the value's i'd expect.

In my Pulumi.production.yaml file I have `aws:profile` set to `production`, and locally this works fine (with the ~/.aws/credentials and ~/.aws/config files in their default location).

But in CI, with the environment variables defining where these files are located, it does not work.

To verify whether it worked, in my `index.ts` file I have the following:

```
aws.getCallerIdentity().then(provider => {
    if (provider.accountId !== config.require('aws_account_id')) {
        console.error("Assumed a role under the wrong account id", { provider });
        process.exit(4);
    }

    const match = provider.arn.match(/(,*)\/(.*)\/(.*)/)!;

    if (!match) {
        console.error("The provider has not been setup correctly.", { provider });
        process.exit(1);
    }

    if (!match.hasOwnProperty(2)) {
        console.error("The provider has not been setup correctly.", { provider });
        process.exit(2);
    }
});
```

and in my Pulumi.production.yaml file I have the `aws_account_id` set to the value of the account that should be assumed. 

This again works locally, but not in CI.

**Comment by guineveresaenger** [comment]
Hi @alexbowers - would you be able to have your CI log the value of `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` and share?

Also, could you share the output of the Pulumi program? That will help us track this down. :)

**Comment by rawkode** [comment]
I believe this was fixed by https://github.com/pulumi/pulumi-aws/pull/2004

Though #2016 has been introduced.
