### ISSUE TITLE
Add dotnet 6 to list of available lambda runtimes. 

### ISSUE THREAD

**Issue by moddaman** [pulumi/pulumi-aws#1837]
## Hello!

AWS lambda now supports net 6 as managed runtime: https://aws.amazon.com/about-aws/whats-new/2022/02/aws-lambda-adds-support-net6/ .   Your list does not: https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/enums/lambda/index.ts#L5-L23

Also see: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I tried to change runtime like this in  “runtime: ‘dotnet6’,“, But I get an error because it seems Pulumi checks against a static list:  `expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2]`

**Comment by nojaf** [comment]
Thank you for adding this!
When I tried to use this in my code (using [4.38.0-alpha.1646075893](https://www.nuget.org/packages/Pulumi.Aws/4.38.0-alpha.1646075893))
I got 
```
Diagnostics:
  aws:lambda:Function (my-lambda):
    error: aws:lambda/function:Function resource 'my-lambda' has a problem: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7
python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got dotnet6. Examine values at 'Function.Runtime'.
```

when running `pulumi up`. Do I need some additional parameters when using prerelease plugins?
