### ISSUE TITLE
Creating an aws target group of type alb doesn't work

### ISSUE THREAD

**Issue by AlmogVonage** [pulumi/pulumi-aws#1844]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

when trying to create an aws target group of type ‘alb’ we get the following:
`error: aws:lb/targetGroup:TargetGroup resource 'internal-lb-target-group' has a problem: expected target_type to be one of [instance ip lambda], got alb. Examine values at 'TargetGroup.TargetType'.
`
The 'alb' type does not seems to be supported by pulumi.

### Steps to reproduce

The code that creates the target group:
```
    const internalLbTargetGroup = new aws.lb.TargetGroup("internal-lb-target-group", {
        name: "studio-internal-lb-target-group",
        targetType: "alb",
        port: 80,
        protocol: "HTTP",
        vpcId: vpc.id,
        healthCheck: {
            path: "/api/health",
            interval: 10,
            enabled: true,
        },
        tags: {
            Owner: "studio",
            project: "studio"
        },
    });

```

Expected: Target group of type alb to be created
Actual: error creating

**Comment by nimbinatus** [comment]
Hi there! I'm also posting my response from our chat in Slack. I've stood up a similar bit of code, and I can create one with the ALB target type. The error comes because of the HTTP protocol. For the ALB target type, the only protocol allowed is TCP:
> 6. For Protocol, only TCP is allowed. Select the Port for your target group. This target group port must match the listener port of the Application Load Balancer. Alternatively, you can add or edit the listener port on the Application Load Balancer to match this port.

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html#register-application-load-balancer-target

**Comment by jkodroff** [comment]
Unfortunately, there's an example that illustrates this use case in the upstream repo that we drop. I'll look into see what we can do to ensure it's not dropped.

**Comment by lukehoban** [comment]
The example here covers this case:

https://www.pulumi.com/registry/packages/aws/api-docs/lb/targetgroup/#alb-target-group
