### ISSUE TITLE
Cannot target dotnet6 runtime for lambda's

### ISSUE THREAD

**Issue by nojaf** [pulumi/pulumi-aws#1845]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

In light of https://github.com/pulumi/pulumi-aws/issues/1837, where the option for `dotnet6` was added to the NuGet package, I still cannot run `pulumi up` without errors.

### Steps to reproduce

1. Create a `Lambda.FunctionArgs` where `Runtime` is set to `Lambda.Runtime.Dotnet6`. Note that I'm using the classic SDK (Pulumi.Aws on NuGet)
2. `pulumi up`

Expected: My deployment to run as `dotnet6` was added.
Actual: 
I got
```
Diagnostics:
  aws:lambda:Function (my-lambda):
    error: aws:lambda/function:Function resource 'my-lambda' has a problem: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7
python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got dotnet6. Examine values at 'Function.Runtime'.
```
There also is a weird thing going on where `pulumi plugin ls` shows two resources:
```
NAME  KIND      VERSION  SIZE    INSTALLED     LAST USED
aws   resource  4.38.0   356 MB  14 hours ago  14 hours ago
aws   resource  4.37.5   355 MB  14 hours ago  14 hours ago
```
Even when I remove all resources, running `pulumi up` still downloads both resources.
I'm not sure if this is expected behavior or relevant to the `dotnet6` runtime problem.

**Comment by moddaman** [comment]
It's also the same for the typescript package. Could it be "issue" from terraform?

**Comment by moddaman** [comment]
A fix is to use pulumis: `awsnative`. https://www.pulumi.com/registry/packages/aws-native/   /  https://www.npmjs.com/package/@pulumi/aws-native . Warning: this is in preview

**Comment by nojaf** [comment]
I considered that as well but would be blocked by https://github.com/pulumi/pulumi-aws-native/issues/124 in my case.

**Comment by moddaman** [comment]
> I considered that as well but would be blocked by [pulumi/pulumi-aws-native#124](https://github.com/pulumi/pulumi-aws-native/issues/124) in my case.

That sucks. My workaround was to create a script that builds and zips. This if of course sub optimal since you have to do this before you run pulumi. If you can wait I would.

```cd ../src/lambda

dotnet tool restore
dotnet tool run dotnet-lambda package -c release -o ./code/code.zip```

**Comment by jkodroff** [comment]
In order to support `dotnet6`, we'll have to wait for the upstream release. We'll do our best to get an update pulumi-aws out the door as soon as possible after terraform-provider-aws 4.4 is released.

As a temporary workaround, I'd suggest trying the .NET 6 Lambda Docker image: https://gallery.ecr.aws/lambda/dotnet

**Comment by nojaf** [comment]
Thanks, I'll just sit this one out. My lambda's are now on Core 3.1, I was excited when Amazon announced support for 6, but I can wait a bit longer.

**Comment by GodspeedYouBlackEmperor** [comment]
Hello,
Looks like terraform-provider-aws in v. 4.4.0 is released already. 
It will be great to get at least an alpha package with the upgrade as soon as possible.

**Comment by jameswoodley** [comment]
This has just stopped us in our tracks, if the value is available in the Runtime enum then I'd expect it to work?

**Comment by stack72** [comment]
Hi folks

I'll have v4.38.1 published in the morning (UK time) to address this

Sorry for the problem here

Paul

**Comment by stack72** [comment]
Folks, I just opened https://github.com/pulumi/pulumi-aws/pull/1854 to fix this up

**Comment by jameswoodley** [comment]
Sweet thanks for jumping on this Paul, very much appreciated

**Comment by stack72** [comment]
Wonderful - thanks for letting me know so fast @nojaf

**Comment by jameswoodley** [comment]
Same, thanks Paul!!

**Comment by pgermishuys** [comment]
Thanks for getting this out so quickly @stack72!
