### ISSUE TITLE
Error: an unhandled error occurred: Program exited with non-zero exit code: -1

### ISSUE THREAD

**Issue by nutrina** [pulumi/pulumi-aws#1846]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When running pulumi up, and we are using the typescript runtime we often get the error: 
`Error: an unhandled error occurred: Program exited with non-zero exit code: -1`

The equivalent scenario with python works fine. 

### Steps to reproduce

1. Follow the pulumi getting started guide for typescript: https://www.pulumi.com/docs/get-started/aws/
2. In the index.ts file replace the code:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";


const defaultDefaultVpc = new aws.ec2.DefaultVpc("default", {
    tags: {
        Name: "Default VPC",
    },
});

export const vpc_id  = vpc.id;
```
3. run `pulumi up`. (I have actually run `pulumi up --yes --skip-preview -v=9 --debug --logflow --logtostderr 2> logs.txt` to get the debug info)

Expected: I would expect the command to run successfully and see the vpc id.
Actual: I see an error:
```
❯ pulumi up --yes --skip-preview -v=9 --debug --logflow --logtostderr 2> logs.txt
Updating (dev)

View Live: https://app.pulumi.com/nutrina/quickstart_ts/dev/updates/1

     Type                 Name               Status                  Info
 +   pulumi:pulumi:Stack  quickstart_ts-dev  **creating failed**     1 error; 5 messages; 3 debugs

Diagnostics:
  pulumi:pulumi:Stack (quickstart_ts-dev):
    I0303 10:09:09.161756  922704 main.go:245] one or more errors while discovering plugins: 1 error occurred:
    	* unmarshaling package.json node_modules/resolve/test/resolver/malformed_package_json/package.json: unexpected end of JSON input
    I0303 10:09:09.207963  922704 main.go:527] Language host launching process:  /root/.nvm/versions/node/v14.18.3/bin/node /root/Projects/gitcoin/debug_infra/quickstart_ts/node_modules/@pulumi/pulumi/cmd/run/index.js --monitor 127.0.0.1:45463 --engine 127.0.0.1:38999 --sync /tmp/pulumi-node-pipes1135789607 --project quickstart_ts --stack dev --pwd /root/Projects/gitcoin/debug_infra/quickstart_ts --query-mode false --parallel 2147483647 .
    I0303 10:11:32.360176  922704 ignore.go:44] Explicitly ignoring and discarding error: sync /dev/stdout: invalid argument
    I0303 10:11:32.364435  922704 ignore.go:44] Explicitly ignoring and discarding error: sync /dev/stderr: invalid argument

    debug: Registering resource: t=pulumi:pulumi:Stack, name=quickstart_ts-dev, custom=false, remote=false
    debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=quickstart_ts-dev
    debug: RegisterResource RPC finished: resource:quickstart_ts-dev[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:dev::quickstart_ts::pulumi:pulumi:Stack::quickstart_ts-dev,,,,
    error: an unhandled error occurred: Program exited with non-zero exit code: -1

Resources:
    + 1 created
```

This is the log file produced:

[logs.txt](https://github.com/pulumi/pulumi-aws/files/8176951/logs.txt)

**Comment by guineveresaenger** [comment]
Hi @nutrina - this looks like an npm error to me. 
Can you check your node version, or re-generate your node modules folder?

**Comment by kpitzen** [comment]
We haven't received any feedback on this in a while - I agree that this seems like an npm issue but if the problem persists, feel free to email @pulumi.com, or respond here on this issue!  We're happy to reopen if it's still a problem.  Thanks!
