### ISSUE TITLE
Profile Assume Role not being consumed in named provider

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-aws#1850]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The Pulumi named provider ignores the role configured in the profile, you must add it explicitly.

### Steps to reproduce

```ts
    // Doesn't work
    new aws.Provider(
        name,
        {
            profile: profile.name,
            region: args.region,
        },
    )
    // Works
    new aws.Provider(
        name,
        {
            profile: profile.name,
            region: args.region,
            assumeRole: { roleArn: 'foo', sessionName: 'bar' },
        },
    )
}
```

**Comment by liamawhite** [comment]
Additionally, the exact same code worked before when I was using a named provider but passing in key, secret and assumeRole directly. We can't use this though as eks requires us to use the profile.

**Comment by liamawhite** [comment]
This is exactly the same as https://github.com/pulumi/pulumi-aws/issues/1422, but for assume role.

**Comment by viveklak** [comment]
@stack72 do you have thoughts here?

**Comment by corymhall** [comment]
@liamawhite can you let us know if you are still seeing this issue? I've tried to reproduce this on the latest version and everything seems to be working.
