### ISSUE TITLE
Unexpected Input of Type GetPolicyResult when using GetPolicy on an AWS Permissions Boundary

### ISSUE THREAD

**Issue by nmelche** [pulumi/pulumi-aws#1862]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When attempting to retrieve an AWS permissions boundary, via the [GetPolicy](https://www.pulumi.com/registry/packages/aws/api-docs/iam/getpolicy/) function, the following error occurs:
`ValueError: unexpected input of type GetPolicyResult`

### Steps to reproduce

1. Create a permissions boundary in AWS
2. Retrieve the permissions boundary like:
```python
import pulumi_aws as aws

pb = aws.iam.get_policy(name="<name_of_permissions_boundary>")
```

Expected: Since the permissions boundary is located under `Policies` in AWS with an ARN like `arn:aws:iam::<account>:policy/`,  I expected to be able to retrieve it like a normal policy.
Actual: The following error occurs: `ValueError: unexpected input of type GetPolicyResult`

**Comment by viveklak** [comment]
Could you provide the full stacktrace please?

**Comment by mikhailshilkov** [comment]
Since we haven't heard back and there is no clear repro or full stack trace, I'll close the issue as non-actionable. If anyone still experiences this problem, please file a new issue with a full repro, stack trace, and provider versions.
