### ISSUE TITLE
email protocol for SNS topic subscriptions

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi-aws#1868]
Got this error: `aws:sns/topicSubscription:TopicSubscription resource 'blah' has a problem: expected protocol to be one of [application http https lambda sms sqs], got email`

Documentation suggests that `email` is a valid value: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html

**Comment by lukehoban** [comment]
This support has been added to the provider via https://github.com/hashicorp/terraform-provider-aws/pull/14923.  See https://www.pulumi.com/registry/packages/aws/api-docs/sns/topicsubscription/#protocol_nodejs.
