### ISSUE TITLE
aws.budgets.Budget costFilters doesn't match documentation

### ISSUE THREAD

**Issue by matthewriedel-flux** [pulumi/pulumi-aws#1870]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce
The [documentation](https://github.com/pulumi/pulumi-aws/blob/f73d82bf022793a85cdd5bf7ac55638b64740cb9/sdk/nodejs/budgets/budget.ts#L17-L22) indicates that the `costFilters` attribute of an AWS Budget is a list of objects.

The [implementation](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/budgets/budget.ts#L346-L351), however, is simply a key/value map.

This causes an issue with the [provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget#cost_filter) which is expecting a list but isn't getting one.

To reproduce:
```typescript
            costFilters: [{
                name: "Service",
                values: ["Amazon Elastic Compute Cloud - Compute"],
            }],
```
produces this on `pulumi preview`:
```text
  pulumi:pulumi:Stack (alarms-alarms_dlvr_us-east-1):
    error: Running program '/Users/username/Source/devex/alarms/alarms' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(11,5): error TS2322: Type '{ Service: string; }[]' is not assignable to type '{ [key: string]: Input<string>; } | Promise<{ [key: string]: Input<string>; }> | OutputInstance<{ [key: string]: Input<string>; }> | undefined'.
      Type '{ Service: string; }[]' is not assignable to type '{ [key: string]: Input<string>; }'.
        Index signature is missing in type '{ Service: string; }[]'.

        at createTSError (/Users/matthew.riedel/Source/devex/alarms/alarms/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/matthew.riedel/Source/devex/alarms/alarms/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/matthew.riedel/Source/devex/alarms/alarms/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/matthew.riedel/Source/devex/alarms/alarms/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/matthew.riedel/Source/devex/alarms/alarms/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
        at Module.require (internal/modules/cjs/loader.js:974:19)
        at require (internal/modules/cjs/helpers.js:93:18)
```

If you match the type definition:
```typescript
    costFilters: {
        Service: "EC2-Other"
    }
```

You get a different error:
```text
    error: aws:budgets/budget:Budget resource 'budgetName' has a problem: Attribute must be a list. Examine values at 'Budget.CostFilters'.
```

Expected: Code matches documentation
Actual: Exception is raised

**Comment by guineveresaenger** [comment]
Hi @matthewriedel-flux - thank you for filing this issue!

Could you let us know:

- which version of Pulumi you're using
- which version of this provider you're using?

We've released a lot of changes this week, due to (some breaking) upstream updates, so this will help us figure out if this is an issue across all versions.

**Comment by matthewriedel-flux** [comment]
Hi @guineveresaenger:

This was with Pulumi v3.26.1 (both CLI and NPM version). I started with `@pulumi/aws@v4.38.1` but downgraded to `@pulumi/aws@4.14.0`

Based on what I could figure out, the AWS TF provider introduced a [change in v3.52.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3520-july-29-2021) to the structure of `costFilters` that the Pulumi code auto-gen didn't pick up. These changes were picked up in `@pulumi/aws@v4.15.0` and `costFilters` probably hasn't worked since.

**Comment by hansarh** [comment]
Can confirm I get the same error for costFilters using provider version 4.38.1 and 5.1.0: 
It now even looks like the documentation has included the deprecation warning from the terraform documentation:
![image](https://user-images.githubusercontent.com/6917956/160600150-4ac383ee-a652-428f-8a63-8b8327c03c26.png)

**Comment by jtriq** [comment]
Confirmed also with 5.1.0 version

**Comment by guineveresaenger** [comment]
Thank you all for reporting - will get this looked at ASAP!
