### ISSUE TITLE
Confusing docs for EC2 Security Group `self` option

### ISSUE THREAD

**Issue by piksel** [pulumi/pulumi-aws#1879]
The docs for EC2 Security Group rules about the `self` option are a bit confusing.

File: [themes/default/content/registry/packages/aws/api-docs/ec2/securitygroup/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/securitygroup/)

It is currently the same (wrong for both versions) description:

> Whether the security group itself will be added as a source to this egress rule.

For the [**egress**]() it should be

> Whether the security group itself will be added as a *destination* to this egress rule.

...and for the [**ingress**](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/securitygroup/#securitygroupingress) it should be:

> Whether the security group itself will be added as a source to this *ingress* rule.

**Comment by guineveresaenger** [comment]
Update: After digging into this, I come to the conclusion that unless I am mistaken about this resource type [the upstream docs are correct](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/security_group.html.markdown#egress). I'll find out the correct place to address and fix this.

Thank you again for reporting.

**Comment by guineveresaenger** [comment]
Update update: After talking to the team, it turns out this is a known bug and we're tracking it in https://github.com/pulumi/docs/issues/6854.

**Comment by danielrbradley** [comment]
Closing as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529

Once the core issue is solved this will be fixed on the next upgrade of the TF bridge.
