### ISSUE TITLE
Wrong type: evaluationPeriods string instead of number

### ISSUE THREAD

**Issue by floknip** [pulumi/pulumi-aws#1887]
File: [themes/default/content/registry/packages/aws/api-docs/cloudwatch/metricalarm/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/cloudwatch/metricalarm/)

In this example:
https://www.pulumi.com/registry/packages/aws/api-docs/cloudwatch/metricalarm/#example-of-monitoring-healthy-hosts-on-nlb-using-target-group-and-nlb

```ts
evaluationPeriods: "1",
```

Should be:
```ts
evaluationPeriods: 1,
```

Same with ` period: "60"`, ` actionsEnabled: "true",`

**Comment by mikhailshilkov** [comment]
This looks like it's been fixed: 
<img width="667" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/fa8b402e-214f-4a85-8150-6fae4e8d4b71">
