### ISSUE TITLE
failing to create/update aws sqs due to timeout of 2m

### ISSUE THREAD

**Issue by yossi-nagar** [pulumi/pulumi-aws#1893]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am trying to upgrade from Pulumi v2.20.0 to Pulumi v.3.28.0. Deployment process run by `pulumi up -r` fails because of timeouts origin by Terraform (so it seems): Creation/Update of SQS queues is failing all the time because of that:

i am using packages:
"@pulumi/aws": "^5.1.0",
"@pulumi/awsx": "^0.40.0",
"@pulumi/pulumi": "^3.28.0",

### Steps to reproduce

This is the code i ran:
`import * as aws from "@pulumi/aws";

const q = new aws.sqs.Queue('Experts-CS-dev-Experts-CSLambda20220404121254156400000016', {
    kmsDataKeyReusePeriodSeconds: 300,
    maxMessageSize: 10240,
    messageRetentionSeconds: 604800,
    namePrefix: 'Experts-CS-dev-Experts-CSLambda',
    policy: '{"Statement":[{"Action":["sqs:SendMessage"],"Condition":{"ArnEquals":{"aws:SourceArn":"arn:aws:sns:eu-west-1:225051786593:Experts-CS-dev-f8eba3f"}},"Effect":"Allow","Principal":{"Service":"sns.amazonaws.com"},"Resource":"*"}]}',
    redrivePolicy: '{"deadLetterTargetArn":"arn:aws:sqs:eu-west-1:225051786593:Experts-CS-dev-Experts-CSLambda-dlq-8672972","maxReceiveCount":10}',
    tags: {
        costCenter: 'operations',
        org: 'cliotechweb',
        project: 'backend-stacks',
        stack: 'dev'
    },
    visibilityTimeoutSeconds: 30
})

exports.queueName = q.id;`

Expected: deployment to be successfull
Actual: it fails because of that:
 aws:sqs:Queue (ApiCSP-dev-ApiCSPReport):
    error: 1 error occurred:
        * creating urn:pulumi:dev::backend-stacks::aws:sqs/queue:Queue::ApiCSP-dev-ApiCSPReport: 1 error occurred:
        * error waiting for SQS Queue (https://sqs.eu-west-1.amazonaws.com/225051786593/ApiCSP-dev-ApiCSPReport20220404121139274300000006) attributes to create: timeout while waiting for state to become 'equal' (last state: 'notequal', timeout: 2m0s)

**Comment by guineveresaenger** [comment]
Hi @yossi-nagar - it might be you're running into [this upstream bug](https://github.com/localstack/localstack/issues/5197).

There's a few workaround suggestions in that issue, hopefully one of those will help you!
