### ISSUE TITLE
Unable to Override AWS Profile Specified in Pulumi Stack Configuration After 5.0.0 Release

### ISSUE THREAD

**Issue by robodair** [pulumi/pulumi-aws#1897]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

On upgrading to version 5+ of `pulumi-aws` I hit this error in our CI which takes some stacks up/down:

```
Exception: invoke of aws:index/getCallerIdentity:getCallerIdentity failed: invocation of aws:index/getCallerIdentity:getCallerIdentity returned an error: 1 error occurred:
    	* error configuring Terraform AWS Provider: failed to get shared config profile, automation
``` 

The pulumi stack config contains a profile for use locally, but on CI this is overriden with the `AWS_*` environment variables to provide the secret access key and access key id:

```
config:
  aws:profile: automation
  aws:region: ap-southeast-2
```

On CI the profile specified in the stack config is not accessible.

### Steps to reproduce

https://github.com/robodair/pulumi-aws-profile-override

1. Install packages from `requirements-5.txt`
2. Set `AWS_*` environment variables for explicit credentials
3. Run `pulumi preview`
4. Downgrade to the requirements in `requirements-4.txt` and preview to observe expected behaviour

Expected: the preview should be successful
Actual: the preview reports an error with the aws profile, despite valid credentials being explicitly provided

**Comment by stack72** [comment]
Hey @robodair 

So I've investigated this and this is now indeed the correct authentication functionality. The upstream Terraform provider changed the ordering of the authentication that EnvVars do not override provider configuration

This means that `pulumi config set aws:profile X` is now taken as precedence over `AWS_PROFILE`

I'm sorry this is the case, this has been changed as it now moves closer toward what the AWS SDK does

You can read more about this in the upstream Upgrade Guide -https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication

Sorry again about this :/

Paul

**Comment by robodair** [comment]
Thanks Paul! We've managed to work around this change internally by disabling the default provider and explicitly creating all providers with exactly the arguments we need. Which is probably a better pattern anyway for our use case.

**Comment by stack72** [comment]
Hi @robodair 

I'm happy you've been able to get unblocked here - I'm really sorry again for this confusion on our part

Paul

**Comment by bombillazo** [comment]
Hello! What is the appropriate setup now for passing AWS credentials to a Pulumi AWS profile if we cannot do it by setting the ENV variables?
