### ISSUE TITLE
Package readme references non-existing changelog

### ISSUE THREAD

**Issue by vubogovich** [pulumi/pulumi-aws#1901]
### What happened?

[README.md](https://github.com/pulumi/pulumi-aws/blob/da381a2ecb4c7dbf1f2ca7a3f4eb75e1d356368e/README.md?plain=1#L113) contains a link to https://github.com/pulumi/pulumi-aws/blob/master/CHANGELOG.md which was renamed to `CHANGELOG_OLD.md` in #1805.

### Steps to reproduce

Open https://www.npmjs.com/package/@pulumi/aws or https://github.com/pulumi/pulumi-aws and click on the link "was changed".

### Expected Behavior

The link is valid

### Actual Behavior

HTTP 404

### Additional context

I'm very curious why `CHANGELOG.md` was renamed.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
@vubogovich We no longer use CHANGELOG.md because we use the git log as the source for release notes, but in any case this is definitely a bug and thank you for submitting!
