### ISSUE TITLE
aws.Provider ignores $AWS_PROFILE on `pulumi refresh`

### ISSUE THREAD

**Issue by jre21** [pulumi/pulumi-aws#1906]
### What happened?

When using a named AWS provider (i.e., calling new aws.Provider() within source code and then passing the result into other pulumi resources), the provider resource stores the current AWS profile into stack state even if it wasn't specified as part of the provider configuration.  Subsequent calls to `pulumi refresh` attempt to fetch credentials from the profile in stack state rather than the `AWS_PROFILE` environment variable, which can cause authentication errors if colleagues use different names for their AWS profiles.

### Steps to reproduce

1. Create a pulumi stack with a named AWS provider, such as
```
const provider = new aws.Provider("provider", {region: "us-east-1"});

const bucket = new aws.s3.Bucket("my-bucket", {}, {provider: provider});
```

2. Run `AWS_PROFILE=test1 pulumi up`

3. Run `AWS_PROFILE=test2 pulumi refresh`

### Expected Behavior

1. Because the AWS profile was not specified as part of the provider configuration, the profile should be stored in stack state.
2. The refresh should use the `test2` AWS profile when querying the live state of the AWS bucket.

### Actual Behavior

1. Pulumi's diff output indicates `profile: test1` as part of the recorded stack state for the `provider` resource.
2. The refresh is performed with the `test1` profile, ignoring the `AWS_PROFILE` environment variable.

### Versions used

Previously-filed issues (#1470, #1585) indicate that the undesired behavior was present in pulumi-aws 4.14.0 and earlier.  From my own tests, version 4.20.0 produced the expected behavior, while versions 4.21.1 and later (my latest tested version is 4.36.0) have reverted to the undesired behavior (the profile is stored in state and environment variables are ignored on refresh).

### Additional context

A colleague of mine provided some additional context on this in https://github.com/pulumi/pulumi-aws/issues/1585#issuecomment-1093541296.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jre21** [comment]
The general principle I'm advocating for here is that any AWS provider configuration which was read from the environment (rather than the provider resource's arguments) at stack creation should continue to be read from the environment (rather than stack state) in all further interactions.

**Comment by lukehoban** [comment]
> The general principle I'm advocating for here is that any provider configuration which was read from the environment (rather than the provider resource's arguments) at stack creation should continue to be read from the environment (rather than stack state) in all further interactions.

I think this is exactly right.  There's a "principle of least surprise" that the current approach is violating. 

Concretely, I believe this would mean removing the `defaultInfo` from the `profile` and `region` inputs on the AWS provider (and similar changes to other providers).  Today this looks like:

```json
            "profile": {
                "type": "string",
                "description": "The profile for API operations. If not set, the default profile created with `aws configure` will be used.\n",
                "defaultInfo": {
                    "environment": [
                        "AWS_PROFILE"
                    ]
                }
            },
            "region": {
                "type": "string",
                "$ref": "#/types/aws:index/region:Region",
                "description": "The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.\n",
                "defaultInfo": {
                    "environment": [
                        "AWS_REGION",
                        "AWS_DEFAULT_REGION"
                    ]
                }
            },
```

Removing those would address the situation raised here.  The one other impact it would have is that `aws.config.profile` would no longer return a value if this came from the environment. There may be code depending on that today.  There's two ways code could be fixed to deal with this though:
1. Specify the `aws.config.profile || os.env.AWS_PROFILE` explicitly in code.
2. Use invokes like `aws.iam.getCallerIdentity()` to discover things like this (though I'm not certain those provide the profile information - which is only a local concept)?

We would need to do some validation of the impact of changing this - but I do think it is the "right" behaviour.
