### ISSUE TITLE
s3.Bucket `websites` property is pluralized but should not be

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#191]
Looks like `website` is not marked as MaxItems = 1, even though it is in practice, so we should force this and/or update the TF provider.

```javascript
        let bucket = new aws.s3.Bucket(name, {
            websites: [{
                indexDocument: "index.html",
            }],
        }, { parent: this});
```

**Comment by jen20** [comment]
Commit 2a4132e in the Terraform provider fixes this, so this should be resolved with the next update.

**Comment by jen20** [comment]
This was fixed a while back, I'll close this issue out.
