### ISSUE TITLE
Investigate deprecated field warnings in AWS S3 BucketObject

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-aws#1911]
Since moving to 5.0.0 of the provider, the Bucket Object resource is providing deprecation warnings from upstream - we need to make sure that is not the case and provide a clear way to move from BucketObject to V2Object

**Comment by cnunciato** [comment]
Related:
* https://github.com/pulumi/pulumi-hugo/issues/1381
* https://github.com/pulumi/pulumi-aws/issues/1910
