### ISSUE TITLE
403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v2.13.1-darwin-arm64.tar.gz

### ISSUE THREAD

**Issue by raquelmsmith** [pulumi/pulumi-aws#1913]
### What happened?

I am trying to redeploy some cloud functions into a new GCP account. When I run `pulumi up` I get:

```
➜ pulumi up
Please choose a stack, or create a new one: ingredient-parser
Previewing update (ingredient-parser)

View Live: https://app.pulumi.com/brunchso/cookup-api/ingredient-parser/previews/6e3e78dc-c27f-4c59-a188-a68b1188be96

     Type                     Name                          Plan       Info
 +   pulumi:pulumi:Stack      cookup-api-ingredient-parser  create     
     └─ pulumi:providers:aws  default_2_13_1                           1 error
 
Diagnostics:
  pulumi:providers:aws (default_2_13_1):
    error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v2.13.1 or on your $PATH, install the plugin using `pulumi plugin install resource aws v2.13.1`
```

When I run the requested command to install the resource, I get:

```
➜ pulumi plugin install resource aws v2.13.1 
[resource plugin aws-2.13.1] installing
error: [resource plugin aws-2.13.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v2.13.1-darwin-arm64.tar.gz
```

I see in github that the release should exist, so I'm not sure why I'm getting a forbidden error here. https://github.com/pulumi/pulumi-aws/releases/tag/v2.13.1

### Steps to reproduce

Visit https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v2.13.1-darwin-arm64.tar.gz and get the 403 error

### Expected Behavior

The plugin to be installed

### Actual Behavior

The plugin is not installed.

### Versions used

➜ pulumi about
CLI          
Version      3.30.0
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     2.13.1
docker  2.8.0
nodejs  unknown

Host     
OS       darwin
Version  11.6
Arch     arm64

This project is written in nodejs (/usr/local/bin/node v12.13.1)

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/brunchso
User           brunchso
Organizations  brunchso

NAME                               VERSION
@pulumi/aws                        2.13.1
@pulumi/awsx                       0.20.0
@pulumi/pulumi                     2.20.0
recipe-ingredient-parser-v2        1.1.1
@types/natural                     0.2.33
@types/node                        10.17.52
natural                            0.6.3
@babel/preset-env                  7.16.11
@babel/preset-typescript           7.16.7
@google-cloud/functions-framework  1.10.0
@types/jest                        26.0.24
@typescript-eslint/eslint-plugin   4.33.0
@typescript-eslint/parser          4.33.0
eslint                             7.32.0
eslint-config-prettier             6.15.0
eslint-config-standard             14.1.1
eslint-plugin-import               2.26.0
eslint-plugin-node                 11.1.0
eslint-plugin-prettier             3.4.1
eslint-plugin-promise              4.3.1
eslint-plugin-standard             4.1.0
jest                               26.6.3
prettier                           2.6.2
sinon                              9.2.4
testcontainers                     4.7.0
ts-jest                            26.5.6

Pulumi locates its logs in /var/folders/cx/8pprr7l562zg97y94dbhgm9h0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack

### Additional context

I hesitate to upgrade my dependencies because I am just getting started with pulumi, this code specifically has been deployed successfully in the past, and I'd like to just get started from right where I left off.

```
"dependencies": {
        "@pulumi/aws": "^2.0.0",
        "@pulumi/awsx": "^0.20.0",
        "@pulumi/pulumi": "^2.0.0",
```

Also, oddly enough, when I look in my node modules I see a @pulumi/aws package, version `2.13.1` installed. Not sure if that's the resource it's trying to download, and if it is, why it's trying to download something that already exists?

<img width="549" alt="image" src="https://user-images.githubusercontent.com/18598166/164364210-c64a06f3-e683-4195-9842-8e087aba454d.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
Hi @raquelmsmith 

The issue you're having here is that you're trying to get the arm64 version of this provider (presumably you're on an M1 machine?) and we only started releasing arm64 versions around [v3.32.1](https://github.com/pulumi/pulumi-aws/releases/tag/v3.32.1). 

You'll need to update the version of the AWS provider that you're using to at least v3.32.1, although you'll be missing out on a load of great resources to it's best to use as recent a release as possible.

There are instructions on how to update the provider in our docs: https://www.pulumi.com/docs/troubleshooting/#403-http-error-fetching-plugin

**Comment by stack72** [comment]
Just to add a little extra detail here - there are no arm64 provider releases for the 2.x series of pulumi-aws. We are now in the 5.x series so to use arm64, you will need to upgrade to at least 4.x series

I am going to close this specific issue out as this is not something we will be back porting to 2.x series :/ I'm sorry for the issue here

Paul

**Comment by raquelmsmith** [comment]
Oh wow, I failed to read for comprehension. amd vs arm 🤦‍♀️  I guess I'll try upgrading. Thanks!
