### ISSUE TITLE
aws.dynamodb.TableItem fails when item keys have non-alpha characters

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [pulumi/pulumi-aws#1917]
### What happened?

Dynamodb TableItem resource cannot be created if the item to be created contains keys with non-alpha characters.

### Steps to reproduce

```
pulumi_aws.dynamodb.TableItem(
    'my-item',
    table_name='my-table',
    hash_key='my-id',
    item=json.dumps({
        'my-id': {
            'S': 'id1',
        },
        'my-data': {
            'S': 'data1',
        }
    }),
)
```

### Expected Behavior

Dynamodb TableItem resource is successfully created.

### Actual Behavior

```
    error: 1 error occurred:
        * creating urn:pulumi:***::***::pkg:index:AppSetup$aws:dynamodb/tableItem:TableItem::my-item: 1 error occurred:
        * Error retrieving DynamoDB table item: ValidationException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#a_my-data"
        status code: 400, request id: ...
```

### Versions used

```
pulumi>=3.0.0,<4.0.0
pulumi-aws>=5.2.0,<6.0.0
```

### Additional context

This issue existed in [Terraform AWS provider](https://github.com/hashicorp/terraform-provider-aws/issues/10385) and the fix was released in [4.9.0 version](https://github.com/hashicorp/terraform-provider-aws/issues/10385#issuecomment-1092274234).

Even though [pulumi-aws 5.2.0 release bumped Terraform AWS provider to 4.10.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.2.0), the errors still occurs in Pulumi. It seems that Pulumi doesn't call the code in Terraform provider that was fixed.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
The following program works fine for me with Pulumi AWS 6.4.0:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const exampleTable = new aws.dynamodb.Table("exampleTable", {
    readCapacity: 10,
    writeCapacity: 10,
    hashKey: "exampleHashKey",
    attributes: [{
        name: "exampleHashKey",
        type: "S",
    }],
});
const exampleTableItem = new aws.dynamodb.TableItem("exampleTableItem", {
    tableName: exampleTable.name,
    hashKey: exampleTable.hashKey,
    item: `{
  "exampleHashKey": {"S": "something"},
  "one": {"N": "11111"},
  "two": {"N": "22222"},
  "three": {"N": "33333"},
  "four": {"N": "44444"},
  "my-id": { "S": "d1" },
  "my-data": { "S": "data1" }
}
`,
});
```

I'll go ahead and close the issue as resolved.
