### ISSUE TITLE
When creation of ssoadmin:AccountAssignment fails, the API error message isn’t in the provider error message

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-aws#1927]
### What happened?

I’m trying to create an AccountAssigment. I’ve already created hundreds and until now they’ve all succeeded. This one is failing. So I need to troubleshoot why it’s failing. Unfortunately the provider seems to have a bug so the actual error message from the API isn’t included in the CLI output.

### Steps to reproduce

I don’t know how to reproduce. I don’t know why this API request is failing for me right now.

### Expected Behavior

I managed to see the underlying requests to the AWS API via TF_LOG=TRACE and `-v=9`, so I saw that the response was:

```json
{
  "AccountAssignmentCreationStatus": {
    "CreatedDate": 1650989104.461,
    "FailureReason": "An unexpected internal service exception was encountered",
    "PermissionSetArn": "<ELIDED>",
    "PrincipalId": "<ELIDED>",
    "PrincipalType": "GROUP",
    "RequestId": "25bf4416-48a7-434d-8d85-91a4575b7d5d",
    "Status": "FAILED",
    "TargetId": "<ELIDED>",
    "TargetType": "AWS_ACCOUNT"
  }
}
```

So I can see that the value of `FailureReason` is `An unexpected internal service exception was encountered`. Although this isn’t super helpful, it’s *something* — and it’s something I can convey to AWS tech support — so I’d rather see that in the error message from the Pulumi provider, rather than` last error: %!s(<nil>)`

### Actual Behavior

```
Diagnostics:
  aws:ssoadmin:AccountAssignment (org-management.sadmin):
    error: 1 error occurred:
    	* error waiting for SSO Account Assignment for GROUP (9a67146517-e8a1178b-7fd0-4b1e-8047-42168150e001) to be created: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)
```

The problem is that part at the end. I assume this is a bug in the underlying Terraform provider, but I thought it made more sense to report it here.

### Versions used

```
CLI          
Version      3.30.0
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.3.0
nodejs  unknown

Host     
OS       darwin
Version  12.3.1
Arch     arm64

This project is written in nodejs (/opt/homebrew/bin/node v18.0.0)

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aviflat
User           aviflat
Organizations  aviflat, latacora

NAME                           VERSION
@aws-sdk/client-identitystore  3.76.0
@pulumi/aws                    5.3.0
@pulumi/pulumi                 3.30.0
shadow-cljs                    2.18.0

Pulumi locates its logs in /var/folders/pp/l138dt0s605b5t04y1mj98w00000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aviflat** [comment]
Looks like this might be the same as https://github.com/hashicorp/terraform-provider-aws/issues/22952

**Comment by riqueps** [comment]
Same issue here.

I'm not able to do an "AccountAssignment"

 error: 1 error occurred:
        * waiting for SSO Account Assignment for GROUP (249774c8-c012-7038-b08d-922bfbc615ac) to be created: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)

**Comment by riqueps** [comment]
> Same issue here.
> 
> I'm not able to do an "AccountAssignment"
> 
> error: 1 error occurred: * waiting for SSO Account Assignment for GROUP (249774c8-c012-7038-b08d-922bfbc615ac) to be created: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s()

Solved!
My issue was because I'm using Customer managed Policies, and I forgot to create the custom policy on the target account.

**Comment by mikhailshilkov** [comment]
The upstream issue has been resolved, so I'll go ahead and close this one as done. The fix should be available in 6.x versions of the Pulumi AWS provider.
