### ISSUE TITLE
Unable to create a Aurora Postgresql RDS Cluster using serverless engine mode

### ISSUE THREAD

**Issue by catmeme** [pulumi/pulumi-aws#1942]
### What happened?

The `pulumi-aws` provider is unable to create a Postgresql RDS Cluster using serverless engine mode in a region that supports `aurora-postgresql`.

### Steps to reproduce

Declare a aurora-postgresql rds cluster using serverless engine mode.

```typescript
const rdsCluster = new aws.rds.Cluster("aurora-postgresql-rds-cluster", {
  clusterIdentifier: rdsClusterName,
  deletionProtection: true,
  engine: "aurora-postgresql",
  engineMode: "serverless",
  engineVersion: "13.6",
  masterPassword: rdsRandomPassword,
  masterUsername: "master",
  storageEncrypted: true,
  vpcSecurityGroupIds: [rdsSecurityGroup.id],
});
```

### Expected Behavior

Create the RDS Cluster using Postgresql Aurora 13.6 in serverless mode.

### Actual Behavior

An error is produced saying the engine mode is not supported

```
  aws:rds:Cluster (aurora-postgresql-rds-cluster):
    error: 1 error occurred:
        * error creating RDS cluster: InvalidParameterValue: The engine mode serverless you requested is currently unavailable.
```

### Versions used

```
@pulumi/aws                                 4.38.1
@pulumi/awsx                                0.32.0
@pulumi/pulumi                              3.32.1
@pulumi/random                              4.6.0
```

### Additional context

The engine mode and version are supported by AWS in the region

```shell
aws rds describe-orderable-db-instance-options --engine aurora-postgresql --db-instance-class db.serverless \
  --region us-east-1 --query 'OrderableDBInstanceOptions[].[EngineVersion]' --output text
13.6
```

Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/24502
* https://github.com/hashicorp/terraform-provider-aws/issues/24349 (Maybe?)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Is this supported in the upstream terraform provider?  If not it will need to be added there, or you can try using the pulumi-aws-native provider that automatically picks up new resource options if that resource is supported.

**Comment by iselegant** [comment]
It seems that upstream terraform provider for Aurora Serverless v2 already has supported until v 4.12.0 and pulumi-aws-native now does not yet support AWS RDS cluster to implement serverless v2.

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.12.0
https://www.pulumi.com/registry/packages/aws-native/api-docs/rds/
