### ISSUE TITLE
Phone Verification

### ISSUE THREAD

**Issue by SeamusY** [pulumi/pulumi-aws#1948]
## Hello!

I'd like to ask if it's possible to guide me or to submit a feature request. I have noticed that the library for pulumi is potentially missing something about this "Which attributes do you want to verify?" which the options aren't present from what I can see in the library.

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by kpitzen** [comment]
@SeamusY Thank you for opening this issue!

@Frassle is correct here - this is currently supported by configuring SMS verification on the user pool:
https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpool/#userpoolsmsconfiguration

I'll close this issue for now, as we haven't received any further information, but feel free to leave a comment or email @pulumi.com if there is anything else we can help with!  Thanks again.
