### ISSUE TITLE
Make or Document how to use CallbackFuntion with Layers/extensions.

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-aws#1950]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I tried to follow Datadog lambda integration which is using Layers to provide some libraries.
I was not able to achieve that with `CallbackFucntion` due to packaging issues. 
After trying `CodePathOptions` (which could be documented better #pulumi/pulumi-hugo/issues/1504) I hit the hard stop not being able to supply correct TS compiler options in `tsconfig.json`.

Based on [this article](https://www.qloudx.com/how-to-split-typescript-based-lambda-functions-into-lambda-layers/) I learned that I need to set [paths in `tsconfig.json`](https://www.typescriptlang.org/tsconfig#paths) however I failed to find out how to do this with Pulumi.

It would be good if the callback function could support this or document that its is not possible to use layers.

**Comment by cnunciato** [comment]
In case others find this issue, I've posted an example of this here: https://github.com/pulumi/pulumi-hugo/issues/1504#issuecomment-1979545206 (while we work on getting the docs updated to cover this).
