### ISSUE TITLE
AWS Auto Scaling Group Documentation missing important notes from upstream documentation

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-aws#1969]
The ASG documentation https://www.pulumi.com/docs/reference/pkg/aws/autoscaling/group/ is missing important notes from the upstream documentation about how instance refresh is triggered.

_Originally posted by @leezen in https://github.com/pulumi/pulumi-aws/issues/1577#issuecomment-909526437_

**Comment by mikhailshilkov** [comment]
We do have the note now
<img width="438" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/b58d59d5-ecad-4d8f-8db9-19ac41187fcc">
