### ISSUE TITLE
Add support for Python3d9

### ISSUE THREAD

**Issue by PatrickMilroy** [pulumi/pulumi-aws#1977]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Terraform added support for Lambda runtime `Python3.9` to the AWS provider in version `3.55` git@github.com:hashicorp/terraform-provider-aws.git

Even though Pulumi uses a newer version of the Terraform AWS provider (`v4.16.0`), support for `Python3d9` hasn't been added eg
https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/enums/lambda/index.ts#L1

**Comment by stack72** [comment]
Hi @PatrickMilroy 

You can still use the string "python3.9" while we add support for the Enum

Paul
