### ISSUE TITLE
ssm Document Provider not picking up Permissions Changes

### ISSUE THREAD

**Issue by mark-bixler** [pulumi/pulumi-aws#1979]
When creating a new SSM Document:

```
this._ssmAgentInstall = new aws.ssm.Document(
        `${ssmArgs.docName}`,
        {
          content: server_agent_install_yaml,
          documentFormat: 'YAML',
          documentType: 'Command',
          name: ssmArgs.docName,
          tags: ssmArgs.tags,
          permissions:
          {
            type: 'Share',
            accountIds: '927503xxxxxx,707608xxxx,825132xxxxx'
          }
        },
        {
          parent: this
        }
      );
```
The `accountIds` string does not get checked for changes. All other properties seems to validate any changes.

pulumi version v1.9.0

**Comment by lukehoban** [comment]
I've confirmed two things:
1. Changes to this property do now get picked up as diffs and updates on the provider
2. The property must be specified as `account_ids` not `accountIds` - and when not specified correctly produces an error.
