### ISSUE TITLE
Network Firewall Rule/RuleGroup Documentation: One of the examples doesn't apply to Pulumi's implementation

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#1998]
### What happened?

This example: https://www.pulumi.com/registry/packages/aws/api-docs/networkfirewall/rulegroup/#stateful-inspection-for-permitting-packets-from-a-source-ip-address
shows the use of a "dynamic" property which doesn't exist in Pulumi.
From looking at the analogous terraform provider (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_rule_group#stateful-inspection-for-permitting-packets-from-a-source-ip-address), it appears this "dynamic" construct is provided in terraform to support a looping mechanism to declare multiple rules.
However, in Pulumi, this would be done using a standard for-loop for the given language and then creating rules ala the DROP example here: https://www.pulumi.com/registry/packages/aws/api-docs/networkfirewall/rulegroup/#stateful-inspection-for-blocking-packets-from-going-to-an-intended-destination 

### Steps to reproduce

Look at the docs.

### Expected Behavior

The examples for the different languages should demonstrate the use of a language-specific for-loop to accomplish the intent of the example.

### Actual Behavior

The "dynamic" property doesn't exist.

### Additional context

You can work around this by using a for-loop over the dynamic property and create the Rule in the body of the for-loop.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
@jkodroff do you think we should apply an overlay here?

**Comment by mikhailshilkov** [comment]
For better or worse, the above example is not displayed in the docs anymore, it's been replaced with "Coming soon". We need to chase some of those "Coming soon" examples to come back online, but I think this issue in particular can be closed.
