### ISSUE TITLE
Recover lost typings

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#2]
After switching to the Terraform provider, we lost a fair number of strong typing niceties.  Once we pop up for air, we should attempt to recover as many of them as possible.  See the commit https://github.com/pulumi/lumi/commit/5eb8edc2942daee798a6e6558fcb82bf95381f4f for a good reference of what it used to look like.  Essentially any enums in that file are missing, and I'm sure many of the "capability-like" views have been lost in favor of weak IDs.

**Comment by lukehoban** [comment]
At this point, this is tracking finding some way to proactively identify and map strongly-typed proeprty references for AWS and TF providers generally.

Frankly, we've heard very little user feedback on this, and through many rounds of discussion have come up with no great ideas for how to get to "great" coverage on strongly typed references - so our investments have been very incremental, leading to unpredictable ability to pass strongly typed references.  At this point, we really need to proposal for how to get to (and stay at) 90%+ coverage on strongly typed references or I would suggest we should not be trying to drive this further - as being at 50% coverage is likely worse than being at ~0% in terms of API consistency.

**Comment by lukehoban** [comment]
I'm going to close this out - we've done a lot of work in and around this - and we'll continue to do more.  But we have no near-term plan to do anything radically different in a structured way.  And we broadly are adding these as incremental additions that preserve compatibility.
