### ISSUE TITLE
Pulumi - Failing to use AWS Profile

### ISSUE THREAD

**Issue by jkrusic19** [pulumi/pulumi-aws#2001]
Issue:
When using a credentials file for AWS and setting either environment variable AWS_PROFILE, or pulumi config set aws:profile, Pulumi does not assume the role and execute in the remote account. I also tried setting both AWS_PROFILE and aws:profile and still not luck. When I write out the CallerIdentity of the account it still points to main account upon pulumi preview and pulumi up.

Language: Python 3.7.7

Credentials example (~/.aws/credentials)
[default]
aws_access_key_id=KEY
aws_secret_access_key=KEY
region=us-east-1

[sandbox]
role_arn = arn:aws:iam::ACCOUNTID:role/role
source_profile=default
region=us-east-1

Expected:
Pulumi to assumeRole and output CallerIdentity of remote account, along with resource creation in remote account.

**Comment by stack72** [comment]
Closed via #2004
