### ISSUE TITLE
Custom STS endpoint for credentials validation not considered when upgrading from 4.38.1 -> 5.7.2

### ISSUE THREAD

**Issue by whummer** [pulumi/pulumi-aws#2003]
Thanks for creating Pulumi 🙏 - really a fantastic IaC framework!

### What happened?

Looks like the behavior of setting custom `endpoints` for STS has changed between versions 4.x (4.38.1) and 5.x (5.7.2). 

When running Pulumi deployment against local APIs ([LocalStack](https://github.com/localstack/localstack) running on `http://localhost:4566`), it works smoothly with 4.38.1, but fails in 5.7.2 (see details below). 

In a nutshell, we're seeing STS requests being made against real AWS (and not against the custom local endpoints) under certain conditions, resulting in 403 errors:
```
I0609 20:28:41.887857   20131 eventsink.go:59] Action=GetCallerIdentity&Version=2011-06-15
 +   pulumi:pulumi:Stack  tmp1-local2  create.
I0609 20:28:47.797696   20131 eventsink.go:59] [aws-sdk-go-v2] Response
I0609 20:28:47.797721   20131 eventsink.go:62] eventSink::Debug(<{%reset%}>[aws-sdk-go-v2] Response<{%reset%}>)
I0609 20:28:47.798107   20131 eventsink.go:59] HTTP/1.1 403 Forbidden
...
  aws:s3:Bucket (my-bucket):
    error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
```

To be honest, I'm not sure if this report is fully accurate and/or reproducible. It seems that several factors and combinations of configs may play into this, not all of which I'm familiar with. Some observations:
* With `aws:skipCredentialsValidation: true`, it seems to be working with both, 4.38.1 and 5.7.2
* With `aws:skipCredentialsValidation: true`, it seems to be working with 4.38.1
* With `aws:skipCredentialsValidation: true`, it seems to be **failing** with 5.7.2

### Steps to reproduce

# Using default version (5.7.2)

Bootstrap a new `aws-javascript` Pulumi project via:
```
$ pulumi new
...
> aws-javascript               A minimal AWS JavaScript Pulumi program
...
```

Configure the following `Pulumi.local.yaml` file:
```
config:
  aws:endpoints:
  - iam: http://localhost:4566
    s3: http://localhost:4566
    sts: http://localhost:4566
  aws:region: us-east-1
  aws:s3ForcePathStyle: 'true'
  aws:accessKey: test
  aws:secretKey: test
  aws:skipRequestingAccountId: 'true'
# commented out to expose the issue
#  aws:skipCredentialsValidation: 'true'
```
Deploy the stack:
```
$ pulumi --logtostderr --verbose 10 -s local1 up
```

--> results in the following error:
```
I0609 20:29:24.565900   18809 plugin.go:184] Launching plugin 'aws (resource)' from '~/.pulumi/plugins/resource-aws-v5.7.2/pulumi-
...
I0609 20:29:31.938147   18809 update.go:195] *** Update(preview=true) complete ***
 +   pulumi:pulumi:Stack  tmp-local1  create
     └─ aws:s3:Bucket     my-bucket              1 error

Diagnostics:
I0609 20:29:31.938736   18809 deployment_executor.go:240] deploymentExecutor.Execute(...): incoming events goroutine exiting
  aws:s3:Bucket (my-bucket):
    error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
```

-----

# Using previous 4.x version (4.38.1)

If we change the default version in the generated `package.json` from this:
```
        "@pulumi/aws": "^5.0.0",
```
to this:
```
        "@pulumi/aws": "^4.0.0",
```
and install the dependencies again:
```
$ npm install
```
Then we deploy the app with the same command again:
```
$ pulumi --logtostderr --verbose 10 -s local1 up
```
... the deployment succeeds and we get this output:
```
I0609 20:37:25.588129   18993 plugin.go:184] Launching plugin 'aws (resource)' from '~/.pulumi/plugins/resource-aws-v4.38.1/pulumi-resource-aws' with args: 127.0.0.1:52029
...
Do you want to perform this update?  [Use arrows to move, enter to select, type to filter]
> yes
...
I0609 20:39:55.482923   19008 host.go:417] Error closing 'nodejs' language plugin during shutdown; ignoring: 1 error occurred:
     Type                 Name        Status
 +   pulumi:pulumi:Stack  tmp-local1  created
 +   └─ aws:s3:Bucket     my-bucket   created

Outputs:
    bucketName: "my-bucket-b6d91fd"

Resources:
    + 2 created

Duration: 4s
```

### Expected Behavior

The custom `endpoints` should be considered and all AWS calls (incl. STS) should be performed against the custom endpoints.

### Actual Behavior

The custom STS endpoint configured in `endpoints` does not seem to be considered when Pulumi calls `sts:GetCallerIdentity` under pulumi-aws version 5.7.2. (i.e., request to real AWS is being made)

### Versions used

```
CLI
Version      3.34.0
Go Version   go1.18.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.38.1
docker  3.2.0
nodejs  unknown

Host
OS       darwin
Version  12.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.0.0'

Backend
Name           ...
URL            file://~
User           ...
Organizations

Dependencies:
NAME            VERSION
@pulumi/aws     4.38.1
@pulumi/awsx    0.40.0
@pulumi/pulumi  3.34.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @whummer 

I am really sorry about the issue you are getting here - I am working on a new release of the provider that will just avoid credentials validation completely while I am working on the solution for #1995 

Please be on the lookout for v5.8.0 which will hit later today!

Paul

**Comment by whummer** [comment]
Hi @stack72 , thanks for cross-posting - wasn't aware that there is already an active discussion thread going on in #1995, which is probably related to this issue. 👍 We can probably close this one in favor of #1995. We'll give it a try with 5.8.0 once released, thanks!
