### ISSUE TITLE
Unable to import ec2.KeyPair

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi-aws#2008]
I'm following this [document](https://www.pulumi.com/docs/reference/pkg/aws/ec2/keypair/#import) to import an EC2 key pair on my AWS account. However, I failed to import.

The error message I encountered is 

```
 error: aws:ec2/keyPair:KeyPair resource 'my_key_pair' has a problem: Missing required argument: The argument "public_key" is required, but no definition was found.. Examine values at 'KeyPair.PublicKey'.
```

## Steps to reproduce

1. Run `pulumi import aws:ec2/keyPair:KeyPair my_key my_key_pair`.

Expected: I expect to see the key pair being imported without any error.
Actual: The following error message will be displayed.
```
Previewing import (my_stack):
     Type                 Name                                    Plan       Info
 +   pulumi:pulumi:Stack  my_infrastructure-my_stack  create      1 error
 =   └─ aws:ec2:KeyPair   my_key                                  import     2 errors

Diagnostics:
  pulumi:pulumi:Stack (my_infrastructure-my_stack):
    error: preview failed

  aws:ec2:KeyPair (my_key):
    error: aws:ec2/keyPair:KeyPair resource 'my_key' has a problem: Missing required argument: The argument "public_key" is required, but no definition was found.. Examine values at 'KeyPair.PublicKey'.
    error: Preview failed: one or more inputs failed to validate
```

The official document also says

> When importing an existing key pair the public key material may be in any format supported by AWS.

But where can I provide the public key while importing?

**Comment by stack72** [comment]
Hi folks

unfortunately, the Go SDK doesn't return the Key material in the API calls therefore, we are not going to be able to do much here. Maybe you could do something regarding ignoreChanges?

This is actually pointed out in the Terraform provider docs as well in their import:

```
NOTE:
The AWS API does not include the public key in the response, so terraform apply will attempt to replace the key pair. There is currently no supported workaround for this limitation.
```

Sorry for this

Paul
