### ISSUE TITLE
Service times out on creation, but appears to have actually succeeded

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#201]
In https://travis-ci.com/pulumi/pulumi-cloud/builds/71591463, there is a failure during the second update to the `pulumi-nginx` service, saying it timed out after 10 minutes.

Looking at the logs for the service, it appears that it started new tasks for the second update at 8:51:09 and reached a steady state at 8:59:42 (8m33s elapsed).  Not clear why this triggered the timeout. But also seems that ECS can frequently take >8 mins to get to a healthy deployment given issues with NLB+ECS (https://github.com/pulumi/pulumi-cloud/issues/313).

Do we need to increase the timeout on Service health checks?

![screen shot 2018-04-24 at 9 32 48 am](https://user-images.githubusercontent.com/223467/39201065-b8983a82-47a2-11e8-890f-2184046bb6d8.png)

**Comment by mmdriley** [comment]
Solution here may be setting `healthCheckGracePeriodSeconds` in [the ECS service definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html).

**Comment by Blitz2145** [comment]
In order to reach steady state faster on our services, we had to lower the default `deregistrationDelay` in the targetGroup to something like 30 (app dependant) instead of 300, which lowered service deploy times by few minutes.
