### ISSUE TITLE
AWS RDS Cluster - pulumi destroy not working

### ISSUE THREAD

**Issue by WP-LKL** [pulumi/pulumi-aws#2020]
### What happened?

weweweewewewew

### Steps to reproduce

1. create RDS cluster
```python
for env in envs:
    rds[envs[env]["name"]] = paws.rds.Cluster(f"{envs[env]['name']}-rds",
    allocated_storage=100,
    # availability_zones=[
    #     "eu-west-1",
    #     "eu-west-2",
    #     "eu-west-3",
    # ],
    cluster_identifier=f"{envs[env]['name']}-rds",
    db_cluster_instance_class=f"db.{envs[env]['dbInstance']}",
    engine="postgres",
    iops=1000,
    master_password=cfg.require_secret("dbPassword"),
    master_username=cfg.require_secret("dbUsername"),
    # source_region=,
    storage_type="io1")
```

2. Deploy
3. Destroy

### Expected Behavior

Pulumi should delete the RDS cluster correctly.

### Actual Behavior

```     Type                 Name                Status        
     pulumi:pulumi:Stack  quickstart-dev      **failed**    
 -   ├─ aws:rds:Cluster   prod-rds     **deleting
 -   ├─ aws:rds:Cluster   staging-rds  **deleting
 -   └─ aws:rds:Cluster   dev-rds      **deleting
 
Diagnostics:
  aws:rds:Cluster (prod-rds):
    error: deleting urn:pulumi:dev::quickstart::aws:rds/cluster:Cluster::prod-rds: 1 error occurred:
        * RDS Cluster FinalSnapshotIdentifier is required when a final snapshot is required
 
  pulumi:pulumi:Stack (quickstart-dev):
    error: update failed
```

### Versions used

```
NAME         VERSION
pip          22.1.2
pulumi-awsx  1.0.0b8
setuptools   62.3.3
wheel        0.37.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
It looks like this is a [known issue in the upstream terraform provider](https://github.com/terraform-providers/terraform-provider-aws/issues/2588).

[This StackOverflow answer](https://stackoverflow.com/a/68022384) provides a workaround to unblock the deletion.

**Comment by stack72** [comment]
As @lblackstone pointed out, you need to set `skipFinalSnapshot: true` in your provider code otherwise RDS will try and take a final snapshot

This is by design I'm afraid to avoid deleting clusters by mistake

Paul
