### ISSUE TITLE
Setting default Encryption on a s3 Bucket gives an error

### ISSUE THREAD

**Issue by gertjana** [pulumi/pulumi-aws#2021]
Hi. pulumi devs,

developing on linux (manjaro 5.15.48-1) 
```
go 1.17
require (
	github.com/pulumi/pulumi-aws/sdk/v5 v5.9.0
	github.com/pulumi/pulumi/sdk/v3 v3.34.1
)
```
I'm try-ing to setup default encryption on a s3 bucket
I used the following code from the documentation [here](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketserversideencryptionconfigurationv2/)

```
if _, err = s3.NewBucketServerSideEncryptionConfigurationV2(ctx, "bucketEncryption", &s3.BucketServerSideEncryptionConfigurationV2Args{
	Bucket: bucket.Bucket,
	Rules: s3.BucketServerSideEncryptionConfigurationV2RuleArray{
		&s3.BucketServerSideEncryptionConfigurationV2RuleArgs{
			ApplyServerSideEncryptionByDefault: &s3.BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs{
				SseAlgorithm: pulumi.String("aws:kms"),
			},
		},
	},
}); err != nil {
	return err
}
```

but it gives me the following error:

```Diagnostics:
  aws:s3:Bucket (test-bucket):
    error: aws:s3/bucket:Bucket resource 'test-bucket' has a problem: Missing required argument: The argument "server_side_encryption_configuration.0.rule" is required, but no definition was found.. Examine values at 'Bucket.ServerSideEncryptionConfiguration.Rule'.
 
```
I tried browsing the source code, but as it is all generated, I haven't been able to pinpoint what or where it is wrong.
any pointers on how to proceed?
Is the documentation wrong. or is there a bug somewhere?

**Comment by pvnick** [comment]
According to the example given here: https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketserversideencryptionconfigurationv2/

you may need to pass _KmsMasterKeyId_ to  _BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs_

**Comment by kpitzen** [comment]
As noted above by the reporter, this appears to be an issue with the Pulumi program itself.  I'll go ahead and close this issue, but feel free to comment if you believe it to still be a bug!  Thank you for reporting this.
