### ISSUE TITLE
AWS OpenSearch Domain doesn't generate a unique physical resource name

### ISSUE THREAD

**Issue by Pavel910** [pulumi/pulumi-aws#2023]
### What happened?

I’m deploying an AWS OpenSearch domain alongside my old AWS ElasticSearch domain, and there’s one very important difference in how the physical domain name is handled: for Elasticsearch, a unique suffix is appended to the logical resource name by Pulumi, which is great, and it follows the behavior of all other resources. For OpenSearch domain, however, this resource works differently:
1) the `domainName` (physical name) is now for some reason required (in other resources, it's always optional)
![CleanShot 2022-06-25 at 20 43 51](https://user-images.githubusercontent.com/3920893/175786590-071d2175-d134-4a2c-a577-777ff863829f.png)

2) this essentially kills the ability to have the physical resource name be derived from the local name

The output of the 2 resources can be seen in this image. Elasticsearch clearly appends a unique ID, while Opensearch doesn't:

![image](https://user-images.githubusercontent.com/3920893/175786853-c63e10ec-31d0-493f-847b-8b804ad20e86.png)

### Steps to reproduce

The source code that will trigger the TS error is shown below:

```ts
import * as aws from "@pulumi/aws";

new aws.opensearch.Domain("example", {
    engineVersion: "OpenSearch_1.2",
    clusterConfig: {
        instanceType: "c5.xlarge.search"
    },
    ebsOptions: {
        ebsEnabled: true,
        volumeSize: 10,
        volumeType: "gp2"
    },
    advancedOptions: {
        "rest.action.multi.allow_explicit_index": "true"
    }
})
```

### Expected Behavior

I expected the physical resource name to be optional, and auto-generated using the local resource name + unique ID, as in all other resources.

### Actual Behavior

I see a TS error, which forces me to specify the physical resource name. I even tried disabling TS, but this check is also in the code, so it's not just a TS bug.

### Versions used

```
CLI          
Version      3.35.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.4
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Ok, we need to support that autonaming happens on the domain_name parameter for this resource
