### ISSUE TITLE
typo in example

### ISSUE THREAD

**Issue by GallibHub** [pulumi/pulumi-aws#2030]
File: [themes/default/content/registry/packages/aws/api-docs/lambda/function/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/)

In the first Basic Example, it reads 
`environment=aws.lambda..FunctionEnvironmentArgs(`

This should be 
`environment=aws.lambda_.FunctionEnvironmentArgs(`

**Comment by lukehoban** [comment]
This appears to be fixed now.
