### ISSUE TITLE
Incomplete Example for GetSubnetsFilter

### ISSUE THREAD

**Issue by jameswoodley** [pulumi/pulumi-aws#2031]
File: [themes/default/content/registry/packages/aws/api-docs/ec2/getsubnets/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/getsubnets/)

`Name`, use: 
then nothing

![image](https://user-images.githubusercontent.com/52610563/175111059-a4d3d4f8-591b-412c-b83c-44db592fce4c.png)

**Comment by mikhailshilkov** [comment]
We do show the examples under `use:` now: 
<img width="689" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/ebf496a4-d236-49f4-acc8-8491da7a099d">
