### ISSUE TITLE
Documentation error for AWS RestAPI documentation

### ISSUE THREAD

**Issue by joffreychambrin** [pulumi/pulumi-aws#2033]
Hi,

I spotted a minor error in the example of the following documentation:
File: [themes/default/content/registry/packages/aws/api-docs/apigateway/restapi/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/restapi/)

```
endpoint_configuration=aws.apigateway.RestApiEndpointConfigurationArgs(
        types=["REGIONAL"],
    ))
```
Should be replaced by:
```
endpoint_configuration=aws.apigateway.RestApiEndpointConfigurationArgs(
        types="REGIONAL",
    ))
```

**Comment by mikhailshilkov** [comment]
It looks like the example got even more broken since then... We just should this snippet as a resource:

```
example_rest_api = aws.apigateway.RestApi("exampleRestApi")
```

with no properties. That does not look right.
