### ISSUE TITLE
DomainLogPublishingOption - enabled documentation is incorrect

### ISSUE THREAD

**Issue by tatroc** [pulumi/pulumi-aws#2034]
File: [themes/default/content/registry/packages/aws/api-docs/elasticsearch/domain/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/elasticsearch/domain/)

enabled attribute for DomainLogPublishingOption reads: Whether to enable node-to-node encryption. If the nonde_to_node_encryption block is not provided then this defaults to false.

**Comment by lukehoban** [comment]
This appears to be another instance of https://github.com/pulumi/pulumi-terraform-bridge/issues/529.
