### ISSUE TITLE
Incorrect constraint for Multi-Attach enabled AWS EBS volumes

### ISSUE THREAD

**Issue by caje731** [pulumi/pulumi-aws#2036]
File: [themes/default/content/registry/packages/aws/api-docs/ebs/volume/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ebs/volume/)

The constructor for the `Volume` resource mentions multi-attached-enabled is only allowed on `io1` type volumes, whereas the [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html) says both `io1` and `io2` type volumes support multi-attach.

**Comment by mikhailshilkov** [comment]
This has been fixed, the current note says: 

> Specifies whether to enable Amazon EBS Multi-Attach. Multi-Attach is supported on io1 and io2 volumes.
