### ISSUE TITLE
Support for AWS Media*

### ISSUE THREAD

**Issue by jamesloosli** [pulumi/pulumi-aws#2067]
We're making use of the AWS Media services, specifically MediaLive and MediaConnect.

As of now, it seems those two services are unsupported in the latest version of Pulumi.

**Comment by stack72** [comment]
Hi @jamesloosli 

My apologies this wasn't picked up before - we will wait for this from the upstream Terraform provider and then be able to pick this up. It's been requested https://github.com/hashicorp/terraform-provider-aws/issues/7217

I am going to close this out as a duplicate 

Paul
