### ISSUE TITLE
can we get a specified version of LaunchTemplate

### ISSUE THREAD

**Issue by better0332** [pulumi/pulumi-aws#2072]
getLaunchTemplate() seems can't get a specified version of LaunchTemplate, any idea?

**Comment by guineveresaenger** [comment]
Hi @better0332 -

in order to help you out, can you please follow the [Bug Report Template](https://github.com/pulumi/pulumi-aws/issues/new/choose) to give us a bit more background? 

Thank you so much!

**Comment by stack72** [comment]
Going to close this out as we haven't had any response here.
