### ISSUE TITLE
support opensearch ebs type gp3

### ISSUE THREAD

**Issue by Matrix-Zhang** [pulumi/pulumi-aws#2073]
![image](https://user-images.githubusercontent.com/1751829/183256386-5e89404e-0eb8-444e-a989-17215c8054a5.png)

here the pulumi aws just support 'standard, io1 and gp2'

**Comment by guineveresaenger** [comment]
Hi @Matrix-Zhang - thank you for this enhancement request!

This will be pulled in as part of the next provider upgrade which should happen in the next few days! 🎉
