### ISSUE TITLE
ec2.TransitGatewayPeeringAttachmentAccepter feels out of place and would more properly fit under ec2transitgateway.PeeringAttachmentAccepter

### ISSUE THREAD

**Issue by prz666** [pulumi/pulumi-aws#2074]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The corresponding Terraform module has 16 resources, but Pulumi is missing this one: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_peering_attachment_accepter

This makes it impossible to properly complete an inter-region / inter-account transit-gateway peering.

Thanks

### Affected area/feature

ec2transitgateway module, even as far as 3.x releases of this provider. Surprised this has not surfaced earlier.

**Comment by prz666** [comment]
upon further investigation (couter-intuitive), it appears that the resource was classified under the ec2 module, instead of the ec2transitgateway one. See https://www.pulumi.com/registry/packages/aws/api-docs/ec2/transitgatewaypeeringattachmentaccepter/.

Probably too late to perform cleanup and re-categorize the resource under ec2transitgateway module. Else, there is no other Transitgateway related resource under ec2. It is true though, that in the Terraform AWS provider, there is no such artificial separation between ec2 and ec2transitgateway. In fact, AWS exposes only an ec2 API, no ec2transitgateway. A bit of a mess. Anyway, the feature is at least implemented somewhere in the hierarchy and inter-region, inter-account TransitGateway peerings can be expressed in Pulumi code.

**Comment by stack72** [comment]
Hi @prz666 

You are 100% correct - I will get an alias in place and get this moved this week. I am sorry for the problems here :/

Paul
