### ISSUE TITLE
Add Get Function that Returns all Results (List) from RDS GetEngineVersion rather than a Single Object

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-aws#2078]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently, the get function `getEngineVersion` returns a single result which fails when AWS returns multiple results. For most cases, the RDS API returns a single result, however, it is possible for the RDS API to return multiple results. In this latter scenario, the current `getEngineVersion` fails, as it expects a single result. In fact, it returns an error if more than one result is present.

See this issue in the upstream provider: https://github.com/hashicorp/terraform-provider-aws/issues/19715

### Affected area/feature
To address this scenario, a get function `getEngineVersions` which returns an array/list of all possible results from the RDS Service API allows the caller use client side filtering to select the appropriate version, for their use case. This eliminates the error condition seen when executing the following call:

```
const version = aws.rds.getEngineVersion({
  engine: aurora-postgresql,
  version: "11.13"
});
```
 
With the proposed feature, one could successfully use the following code to lookup _all_ versions and select the appropriate version based on some arbitrary criteria, such as `supportedProvisionModes == "provisioned"`.

**Comment by phillipedwards** [comment]
@stack72 For reference.

**Comment by guineveresaenger** [comment]
hi @phillipedwards - thank you for filing and for the context. We'll be pulling this into the provider as soon as the upstream issue is resolved. 🙇‍♀️

**Comment by stack72** [comment]
@guineveresaenger there is no upstream issuer for this :) We are implementing this in our fork :)
