### ISSUE TITLE
API Gateway integrations incorrectly updated when target changes (AWS Classic)

### ISSUE THREAD

**Issue by ewucc** [pulumi/pulumi-aws#2081]
### What happened?

I have a service deployed using pulumi as a lambda fronted with an API Gateway. I want to convert the lambda to use ECS and fargate instead. I update the pulumi files to change the lambda to now be an ECS Task/Service, spin up an ECS cluster, and create a restAPI integration to use HTTP_PROXY, VPC_LINK, and NLB url instead of the initial AWS_PROXY and event handler url.

I expect the Lambda along with any Lambda related resources like permissions and cloudwatch log groups to be deleted, while the ECS related services like task, service, vpc link, NLB, and any security groups, permissions to be created. I also expect the restAPI aws.apigateway.Integration to be updated to instead of using the lambda, use the VPC_LINK and nlb. 

Instead what happens is all of the expected resources are created, but the aws.apigateway.integrations are instead destroyed without recreating new integrations using the vpc link. At this point, I can navigate to the AWS console and manually update the method to create the integration. Doing so makes everything function correctly. 

### Steps to reproduce

Start off with a restAPI configured with resource and method. Create an integration for lambda and deploy your service

```
new aws.apigateway.Integration(`${methodPath}-${r.verb.toUpperCase()}`, {
                    restApi: restAPI.id,
                    resourceId: parentResource == null ? restAPI.rootResourceId : parentResource.id,
                    httpMethod: method.httpMethod,
                    integrationHttpMethod: "POST",
                    type: "AWS_PROXY",
                    uri: lambda.invokeArn
                })
```

After that is completed, set up pulumi code to create an ECS cluster and it's associated resources. Create a new integration 
for VPC link instead

```
new aws.apigateway.Integration(`${methodPath}-${r.verb.toUpperCase()}`, {
                    restApi: restAPI.id,
                    resourceId: parentResource == null ? restAPI.rootResourceId : parentResource.id,
                    httpMethod: method.httpMethod,
                    integrationHttpMethod: method.httpMethod,
                    type: "HTTP_PROXY",
                    connectionType: "VPC_LINK",
                    connectionId: vpcLink.id,
                    uri: pulumi.interpolate`http://${nlb.loadBalancer.dnsName}${r.path}`
                })
```
 
 Deploying this will result in all the resources being created but the integration being deleted. Pulumi up will complete and show that it was updated
 ```+-  ├─ aws:apigateway:Integration                 quote-POST                        replaced     [diff: ~connectionId,connectionType,type,uri]
 +-  ├─ aws:apigateway:Integration                 /-GET                     replaced     [diff: ~connectionId,connectionType,integrationHttpMethod,type,uri]
 +-  ├─ aws:apigateway:Integration                 quotes-GET                    replaced     [diff: ~connectionId,connectionType,integrationHttpMethod,type,uri]
 +-  ├─ aws:apigateway:Integration                 users-GET                         replaced     [diff: ~connectionId,connectionType,integrationHttpMethod,type,uri]
 +-  ├─ aws:apigateway:Integration                 users-POST                        replaced     [diff: ~connectionId,connectionType,type,uri]```
 
 But once you do a pulumi refresh, it will actually attempt to update the stack and show these resources were deleted.
 

### Expected Behavior

I expected the restAPI method integrations to be updated to point at NLB/VPC_link 

### Actual Behavior

aws.apigateway.Integrations using the lambda are destroyed and the ones using the VPC link are not created.

### Versions used

Version      3.16.0


### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ewucc** [comment]
Yeh that definitely works. I'm curious is there a way though to do that transition w/o doing a `pulumi refresh` first? The issue being the `pulumi refresh` destroys the initial set of integrations and then is created on the `pulumi up`. The idea being i'm hoping to have a smooth service transition with minimal to no interruption, but maybe that isn't possible

**Comment by ewucc** [comment]
Forgot to add that if I do a `refresh` and then `up`, some security groups ingress rules are incorrectly destroyed.

**Comment by guineveresaenger** [comment]
Hi @ewucc - thank you for notifying us of this bug!

I believe this is similar to #2075. You can add a [`deleteBeforeReplace`](https://www.pulumi.com/docs/intro/concepts/resources/options/deletebeforereplace) to your apigatewayIntegration while we work on a fix for this.

**Comment by ewucc** [comment]
Hey @guineveresaenger Just wanted to let you know that I got a chance to finally try this out and it seems I am still having the same issues. Even if I add the delete before replace, instead, all the integrations and methods using lambdas are simply deleted and not replaces with the new ones using ECS
