### ISSUE TITLE
egress instead of ingress in documentation

### ISSUE THREAD

**Issue by megacier** [pulumi/pulumi-aws#2083]
File: [themes/default/content/registry/packages/aws/api-docs/ec2/securitygroup/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/securitygroup/)

![image](https://user-images.githubusercontent.com/5756779/183919623-86921bad-81b3-4bf6-9e27-782bd8cab945.png)

**Comment by mikhailshilkov** [comment]
This has been fixed
<img width="736" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/a53fe56f-8b37-4ece-a91f-60f1d3c3f94e">
