### ISSUE TITLE
Update default node runtime for CallbackFunctions

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi-aws#2090]
### What happened?

CallbackFunctions created via lambdaMixins use Runtime.NodeJS12dX as their default. Lambdas with this runtime cause an email to be sent from AWS, with this content:

> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.
> 
> We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022.
> 
> As described in the Lambda runtime support policy, end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
> 
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.

https://github.com/pulumi/pulumi-aws/blob/91d648e705ff68105bce2092ed34431451c667e6/sdk/nodejs/lambda/lambdaMixins.ts#L349

This default should be updated to Runtime.NodeJS16dX before 2022/11/14.

### Steps to reproduce

Create a CallbackFunction without providing the optional `runtime` arg.

### Expected Behavior

No warning emails should be sent by AWS.

### Actual Behavior

The above warning email is sent by AWS.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
@pulumi/platform-providers 

I'm not sure if this needs to be a P1, but it looks like this will break completely starting on November 11, 2022
