### ISSUE TITLE
Regression with version 5.11.0 and resource options

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aws#2102]
### What happened?

After upgrading from version 5.10.0 to version 5.11.0, I get the following error when using resource options:

```
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
      File "/tmp/tmp.T1ec9S84a7/pulumi/venv/lib64/python3.10/site-packages/pulumi/invoke.py", line 115, in merge
        raise TypeError("Expected opts2 to be a InvokeOptions instance")
    TypeError: Expected opts2 to be a InvokeOptions instance
```

Reverting to 5.10.0 "fixes" the problem.

### Steps to reproduce

Using pulumi-aws version 5.11.0, try the following code:

```
pulumi_aws.get_availability_zones(
    opts=pulumi.ResourceOptions(),
)
```

### Expected Behavior

No exceptions should be raised

### Actual Behavior

An exception is raised.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
So the behavior here has changed, but I think it's not a regression.
The `opts` argument to `get_availability_zones` should be an `InvokeOptions` object, not a `ResourceOptions` object. If you run type checking against this mypy would error that opts is the wrong type, but we never used to do a runtime type test before. Python being dynamic this happened to work as the fields on `InvokeOptions` currently happen to be a subset of those on `ResourceOptions`, but that's not guaranteed to stay that way, and we now do a runtime type test to check that opts is the expected type.

If you update your code to pass `InvokeOptions` here instead everything will work.
