### ISSUE TITLE
Regression when migrating to SharedCredentialsFiles field

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-aws#2105]
### What happened?

When we are initializing our Provider we've been using `SharedCredentialsFile`. We wanted to upgrade from 4.9 -> 5.11.0 and we've noticed that the field is deprecated and we should move to use `SharedCredentialsFiles` when we tried to use this field it seems that it's being completely ignored and not used at all.

Errors we're seeing are:

```
  aws:sqs:Queue (diskanalyzer-scans-dlq):
    error: unable to validate AWS credentials. Make sure you have:

         • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
         • Configured your AWS credentials as per https://pulumi.io/install/aws.html
         You can also set these via cli using `aws configure`.
```

When we use the old field things seem to work fine.

### Steps to reproduce

Use `SharedCredentialsFile`

### Expected Behavior

AWS provider should use appropriate provider file

### Actual Behavior

Seems that it's not being used at all

### Output of `pulumi about`

```
❯ pulumi about
CLI
Version      3.26.1
Go Version   go1.17.8
Go Compiler  gc

Host
OS       darwin
Version  12.5.1
Arch     arm64

Backend
Name     Yarins-MacBook-Pro-4.local
URL      file:///Users/yarin/.pulumi-state
User     yarin
```

### Additional context

Using automation api to invoke pulumi

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @yarinm 

My apologies for this - you can skip this credentials validation check by using `pulumi config set aws:skipCredentialsValidation true`

I will ensure we get this working as expected now

Paul

**Comment by yarinm** [comment]
Hey @stack72 even when we set `skipCredentialsValidation` it fails, it doesn't seem to use the new field for credential files
