### ISSUE TITLE
display all misconfiguration in the same error message

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-aws#2108]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
As I was complaining, I thought of a solution.

Can we take all of the checks for provider configuration, and display them at the same time instead of failing iteratively.
### Desired State
if none are set:
```
    error: unable to configure AWS provider. Make sure you have all of the following configured:
    
     	 [ ] Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
     	 [ ] Configured your AWS credentials(https://pulumi.io/install/aws.html)
```
if one is set, but not the other:
```
    error: unable to configure AWS provider. Make sure you have all of the following configured:
    
     	 [x] Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
     	 [ ] Configured your AWS credentials(https://pulumi.io/install/aws.html)
```

### Current State:
```
    error: unable to find a AWS Region config. Set the Region by using:
    
     	 • `pulumi config set aws:region us-west-2` or
     	 • An AWS Profile or
     	 • Environment variables:`AWS_REGION` or `AWS_DEFAULT`
```
after resolving this, my creds were not configured and I received this error message
```
    error: unable to validate AWS credentials. Make sure you have:
    
     	 • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
     	 • Configured your AWS credentials as per https://pulumi.io/install/aws.html
     	 You can also set these via cli using `aws configure`.
```

### Motivation
I was using pulumi-aws and the error message confused me as there is an error message/check to see that the region is set.
```
    error: unable to find a AWS Region config. Set the Region by using:
    
     	 • `pulumi config set aws:region us-west-2` or
     	 • An AWS Profile or
     	 • Environment variables:`AWS_REGION` or `AWS_DEFAULT`
```
after resolving this, my creds were not configured and I received this error message
```
    error: unable to validate AWS credentials. Make sure you have:
    
     	 • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
     	 • Configured your AWS credentials as per https://pulumi.io/install/aws.html
     	 You can also set these via cli using `aws configure`.
```

can we remove the line suggesting
```
     	 • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
```
since it seems that there is a pre-existing region check that will catch and suggest solutions for that error case?

Did we reorder the checks for **valid credentials** and **provider config values**.

recording of session: https://asciinema.org/a/UlijRAOxYbMFc4LW9M5pP5ZMa

**Comment by MitchellGerdisch** [comment]
This is a very nice enhancement.
Maybe the message should be something like the following to help the densest amongst us to deduce that no action is needed for an item with [x] next to it.
```
    error: unable to configure AWS provider.
    See following checklist for missing items:
       [ ] ....
```

**Comment by stack72** [comment]
Unfortunately, I need to remove the explicit check for the region as we actually do fall back to the shared credentials for the check in the TF provider so by adding this check, we've regressed the provider.

Therefore, I am going to close this out as part of #2120 as we won't have 2 different error messages any more

**Comment by dixler** [comment]
> Unfortunately, I need to remove the explicit check for the region as we actually do fall back to the shared credentials for the check in the TF provider so by adding this check, we've regressed the provider.

> Therefore, I am going to close this out as part of https://github.com/pulumi/pulumi-aws/pull/2120 as we won't have 2 different error messages any more

Would I still run into 2 different error messages sequentially if my creds were outdated and I had also forgotten to run `pulumi config set aws:region us-east-1`?
