### ISSUE TITLE
No documentation provided for argument `ssl_support_method` of `aws.cloudfront.DistributionViewerCertificateArgs`

### ISSUE THREAD

**Issue by bolinocroustibat** [pulumi/pulumi-aws#2117]
On the page `https://www.pulumi.com/registry/packages/aws/api-docs/cloudfront/distribution/#distributionviewercertificate`, at least for the Python version (didn't check other languages), no values are provided for documenting the argument `ssl_support_method` of `aws.cloudfront.DistributionViewerCertificateArgs`:

<img width="820" alt="Screen Shot 2022-08-30 at 00 18 31" src="https://user-images.githubusercontent.com/4353767/187235970-71349e28-2c2a-4210-b5e0-13edb0358241.png">

Also would be great to provide other example of cloudfront distribution instanciations. The single provided example is not a standard case and missing some other options.

**Comment by mikhailshilkov** [comment]
We have the description now
<img width="742" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/88e937af-4a35-44f7-bb2f-fa6eb175efbe">
