### ISSUE TITLE
Wrong documentation about the `enabled` argument for `aws.cloudfront.Distribution`

### ISSUE THREAD

**Issue by bolinocroustibat** [pulumi/pulumi-aws#2119]
In the doc about `aws.cloudfront.Distribution` (https://www.pulumi.com/registry/packages/aws/api-docs/cloudfront/distribution/), it says the argument `enabled` is "A flag that specifies whether Origin Shield is enabled.".
It is wrong.
`enabled` is to enable / disable the Cloudfront distribution.

**Comment by guineveresaenger** [comment]
Hi @bolinocroustibat - thank you for filing these issues! 

[As stated in your related issues, we are hoping to fix issues like this soon](https://github.com/pulumi/pulumi-aws/issues/2117#issuecomment-1231003945).

**Comment by jkodroff** [comment]
I believe this is caused by: https://github.com/pulumi/pulumi-terraform-bridge/issues/529

**Comment by lukehoban** [comment]
Going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529 to track the required work centrally.
