### ISSUE TITLE
`aws:context` 

### ISSUE THREAD

**Issue by mike-chen-samsung** [pulumi/pulumi-aws#2147]
### What happened?

I get this error
```
error: Missing required configuration variable 'aws:context'
```
when running `pulumi up` containing this code
```
import { getBucketObject } from "@pulumi/aws/s3"

getBucketObject(
  {
    bucket: "bucketName",
    key: `/blah/blah.json`,
  },
  {
    provider: new Provider("us-east-2", {
      assumeRole: awsConfig.requireObject("assumeRole"),
      allowedAccountIds: awsConfig.requireObject("allowedAccountIds"),
      region: "us-east-2",
    }),
  }
)
```

### Steps to reproduce

Run the code in the "What happened" section

### Expected Behavior

I expected `pulumi up` to just work

### Actual Behavior

`pulumi up` resulted in this error
```
error: Missing required configuration variable 'aws:context'
```

### Output of `pulumi about`

```$ pulumi about
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  11.6
Arch     x86_64

This project is written in nodejs: executable='/Users/<redacted>/.nvm/versions/node/v16.15.1/bin/node' version='v16.15.1'
```

### Additional context

My workaround for this was just adding `aws:context: uhhh` to my stack config. After this, `pulumi up` ran just fine.

Original Slack thread: https://pulumi-community.slack.com/archives/CRH5ENVDX/p1663363028832449

using NPM package `@pulumi/aws` version `5.10.0`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @mike-chen-samsung I've been unable to reproduce this issue myself. Does this erorr occurr in a Pulumi program which only has that one `getBucketObject` call and no other code?

There's also no reference I've found to an `aws:context` configuration variable in the provider which leads me to think this error could be originating from another source. Please could you share any more output information:

- Is the error attached to a specific resource?
- Would you be able to share [additional diagnostics information](https://www.pulumi.com/docs/support/troubleshooting/)?
- Would you be able to provide a minimal reproduction of the issue that we can run and see the issue for ourselves?

Thanks!
