### ISSUE TITLE
ap-southeast-1c zone not unavailable

### ISSUE THREAD

**Issue by Matrix-Zhang** [pulumi/pulumi-aws#2156]
### What happened?

when i create aws rds cluster, it failed

```
creating RDS Cluster (data-sync-dev-cluster): InvalidVPCNetworkStateFault: Availability zone '[ap-southeast-1c]' is unavailable in this region, please choose another zone set.
```

### Steps to reproduce

```
ws
  .getAvailabilityZones({
    state: "available",
  })
  .then((res) => {
    const clusterIdentifier = `${baseTags.Name}-cluster`;

    const rdsCluster = new aws.rds.Cluster(clusterIdentifier, {
      allocatedStorage: 20480,
      availabilityZones: res.names,
      clusterIdentifier,
      dbClusterInstanceClass: "db.m6g.8xlarge",
      backupRetentionPeriod: 30,
      preferredBackupWindow: "23:00-01:00",
      preferredMaintenanceWindow: "Sat:02:00-Sat:12:00",
      dbSubnetGroupName: subnetGroup.name,
      deletionProtection: true,
      vpcSecurityGroupIds: [networkingStack.getOutput("peeredSecurityGroupId")],
      finalSnapshotIdentifier,
      engine: "aurora-postgresql",
      engineVersion: "14.3",
      databaseName: baseConfig.dbName,
      masterPassword: baseConfig.dbPassword,
      masterUsername: "postgres",
      tags: baseTags,
    });
  });
```

### Expected Behavior

it will create the cluster successed

### Actual Behavior

failed

### Output of `pulumi about`

Diagnostics:
  pulumi:pulumi:Stack (relation-data-sync-dev):
    error: update failed

  aws:rds:Cluster (data-sync-dev-cluster):
    error: 1 error occurred:
        * creating RDS Cluster (data-sync-dev-cluster): InvalidVPCNetworkStateFault: Availability zone '[ap-southeast-1c]' is unavailable in this region, please choose another zone set.
        status code: 400, request id: 7f551116-22c4-40bd-9db4-f68d6119e9c0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
This feels like another manifestation of https://github.com/hashicorp/terraform-provider-aws/issues/5725. Could you make sure you have a subnet created in the availability zone being chosen?

**Comment by Matrix-Zhang** [comment]
no, i created the vpc use `new awsx.ec2.Vpc` with default subnets configuration, it will be 2
