### ISSUE TITLE
Regex validation for `eventBusName` field of event rule doesn't work properly

### ISSUE THREAD

**Issue by bglgwyng** [pulumi/pulumi-aws#2161]
### What happened?

I tried to get existing an aws event rule resource using `get` method.
The code read as follows.
```typescript
import * as aws from '@pulumi/aws';

const eventRule = aws.cloudwatch.EventRule.get('test3', 'arn:aws:events:ap-northeast-2:751870429738:rule/test3', {
  eventBusName: 'arn:aws:events:ap-northeast-2:751870429738:event-bus/default',
});
```

It failed and pulumi gave me error messages.
```
Diagnostics:
  aws:cloudwatch:EventRule (test3):
    error: Preview failed: refreshing urn:pulumi:dev::pulumi-sandbox::aws:cloudwatch/eventRule:EventRule::test3: 1 error occurred:
        * error reading EventBridge Rule (arn:aws:events:ap-northeast-2:751870429738:rule/test3): ValidationException: 1 validation error detected: Value 'arn:aws:events:ap-northeast-2:751870429738:rule' at 'eventBusName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+
        status code: 400, request id: 1ad7d268-2c1b-4dc7-b37b-1cd6a3f7af02
```
As you can see, value 'arn:aws:events:ap-northeast-2:751870429738:rule' is not what I provided for `eventBustName`. Pulumi is validating a wrong value for `eventBusName` field.

### Steps to reproduce

You should create an event rule resource in advance to get. I tested several cases and now it seems that the detailed configurations don't matter. So you can make an event rule resource in aws console with any configurations and test my code above.

### Expected Behavior

It returns the correct event rule resource.

### Actual Behavior

It failed.

### Output of `pulumi about`

CLI          
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.16.0
docker      3.2.0
kubernetes  3.19.3
nodejs      unknown
random      4.7.0

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.16.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
@danielrbradley Can you double-check the get syntax here? I'm wondering if the state argument is causing the problem here.

**Comment by danielrbradley** [comment]
Hi @bglgwyng the issue is that the `get` function only requires the rule name, not the ARN. E.g.

```typescript
export const newEventRule = new aws.cloudwatch.EventRule("dansTestEventRule", {
  scheduleExpression: "cron(0 12 * * ? *)",
  name: "dansTestEventRule",
});
```

Creating something like the above can be fetched using the following snippet:

```typescript
export const testEventRule = aws.cloudwatch.EventRule.get(
  "testEventRule",
  "dansTestEventRule"
);
```

If using a non-default eventBus, then, again it should only be the name rather than the ARN set in the `eventBusName` state.

Will close as working correct.

**Comment by bglgwyng** [comment]
@danielrbradley Thanks. Your solution works well with `default` event bus.

However, I tried a event rule with a partner event bus like below and it failed.
```
const eventRule = aws.cloudwatch.EventRule.get('eventRuls, 'test7', {
  eventBusName: 'aws.partner/mongodb.com/stitch.trigger/632fed9d9d9500795e56fd9c',
});
```
The response was
```
aws:cloudwatch:EventRule (test3):
    error: Preview failed: resource 'test7' does not exist
```

**Comment by bglgwyng** [comment]
I saw the following error message by putting a completely wrong value as the event rule name argument.
```
* unexpected format for ID (arn:aws:events:ap-northeast-2:751870429738:event-bus/aws.partner/mongodb.com/stitch.trigger/632fed9d9d9500795e56fd9c), 
  expected EVENTBUSNAME/RULENAME or RULENAME
```

So I tried
```
const eventBusName = 'aws.partner/mongodb.com/stitch.trigger/632fed9d9d9500795e56fd9c';
const eventRule1 = aws.cloudwatch.EventRule.get('eventRule1', pulumi.interpolate`${eventBusName}/test7`);
```
and it worked well!
However, at the same time, the following isn't still working.
```
const eventRule2 = aws.cloudwatch.EventRule.get('eventRule2', 'test7', {
  eventBusName: eventBusName,
});
```
