### ISSUE TITLE
python typing for `resources` in `GetPolicyDocumentStatementArgs` doesn't support `Output`s

### ISSUE THREAD

**Issue by drone-ah** [pulumi/pulumi-aws#2162]
In the following code:

```
# Policies for sagemaker execution training job
sagemaker_s3_policy_document = aws.iam.get_policy_document(statements=[
    aws.iam.GetPolicyDocumentStatementArgs(
        sid="1",
        actions=[
            "s3:*"
        ],
        resources=[
            training_bucket.arn.apply(lambda arn: arn),
            training_bucket.arn.apply(lambda arn: f"{arn}/*"),
        ]
    )
])
```

There is a typing warning (in PyCharm) on the resources line:

`Expected type 'Optional[Sequence[str]]', got 'list[Union[Output, Output[str]]]' instead`

It looks like it should be something like `List[Union[str, Awaitable[str], Output[str]]` instead

**Comment by lblackstone** [comment]
Hmm, that's not what [I see in the API docs](https://www.pulumi.com/registry/packages/aws/api-docs/iam/getpolicydocument/#using), so I'm not sure why you're getting that type hint. There are two forms of the getter; you're using the synchronous version, which should not be an Output type.

Could you update this issue with the information of `pulumi about` so we can see if there might be a problem with the version of the provider that you're using?

**Comment by drone-ah** [comment]
Sorry for the delay. Info as requested

```
$ pulumi about
CLI          
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.19.0
python  unknown

Host     
OS       debian
Version  11.5
Arch     x86_64

This project is written in python: executable='/home/shri/Projects/hicarer/dist/export/python/virtualenvs/python-default/3.9.2/bin/python3' version='3.9.2
'

Current Stack: minerva-dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:minerva-dev::rv-core::pulumi:pulumi:Stack::rv-core-minerva-dev
pulumi:providers:aws                               urn:pulumi:minerva-dev::rv-core::pulumi:providers:aws::default
pulumi:providers:aws                               urn:pulumi:minerva-dev::rv-core::pulumi:providers:aws::default_5_19_0
aws:iam/role:Role                                  urn:pulumi:minerva-dev::rv-core::aws:iam/role:Role::minerva-github-build-agent
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:minerva-dev::rv-core::aws:iam/rolePolicyAttachment:RolePolicyAttachment::github-build-agent-administrator


Found no pending operations associated with minerva-dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/drone-ah
User           drone-ah
Organizations  drone-ah, EpicGames, RascalVentures, SWGfL-Minerva

Dependencies:
NAME           VERSION
pip            20.3.4
pkg-resources  0.0.0
pulumi-aws     5.19.0
setuptools     44.1.1
```

**Comment by lblackstone** [comment]
Thanks for the update!

> I'd like to redact some of the identifiable information from the above if it's not needed please :)

Done. :)

**Comment by lblackstone** [comment]
Oh, I think I misunderstood the problem originally. My first answer was about the result type for the function, but you're talking about the `resources` arg:
```py
resources=[
            training_bucket.arn.apply(lambda arn: arn),
            training_bucket.arn.apply(lambda arn: f"{arn}/*"),
        ]
```

The `apply` methods are returning an `Output[str]`, but the synchronous getter is expecting a `str`. I think it should work if you use `get_policy_document_output` instead.

**Comment by lblackstone** [comment]
Oh, sure enough. Ok, since the `resources` arg is not typed as an Input, you would need to wrap the get inside an apply like this:

```py
pulumi.Output.all("arn1", "arn2", "arn3", "etc").apply(lambda args: aws.iam.get_policy_document(statements=[
    aws.iam.GetPolicyDocumentStatementArgs(
        resources=args,
    )
])
```

https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#all

**Comment by drone-ah** [comment]
Does it not make more sense to update `aws.iam.GetPolicyDocumentStatementArg`? i.e.

```python
  resources: Optional[Sequence[str|Output[str]]] = None,
```

**Comment by lblackstone** [comment]
Yes, that would be ideal. Unfortunately, the types are auto-generated from the underlying terraform provider schema, so it's not a simple change.

**Comment by drone-ah** [comment]
Ah! That sucks! I think I'll just ignore the type warning then and keep it a wee bit more readable.

**Comment by lblackstone** [comment]
Sure thing! I'll go ahead and close this out since it looks like you got the info you need.
