### ISSUE TITLE
Mandatory and Optional properties indication is missing for VPC CIDR block

### ISSUE THREAD

**Issue by patilpappmodz1** [pulumi/pulumi-aws#2176]
File: [themes/default/content/registry/packages/aws/api-docs/ec2/vpc/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/vpc/)

In the earlier version of the API docs, there used to be a red asterisk for mandatory properties. It seems like it is missing now. Similar to how you indicate a sign for trigger replacement (for example on CIDR Block) can we add mandatory or optional indication ?

**Comment by thomas11** [comment]
Hi @patilpappmodz1, thank you for reporting this. Looking at [the EC2 VPC docs](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/vpc/) you linked, I do see the red asterisk for the `name` and `id` properties. Reading through the resource properties, they all seem to have defaults, meaning they're optional.

Are there any particular properties that you noticed that should have the asterisk?

**Comment by patilpappmodz1** [comment]
i don't see the asterisk in the INPUT properties section. i am assuming you see the red asterisk in the output section. For VPC, i understand that CIDR Block is a mandatory property.

**Comment by thomas11** [comment]
I see the red asterisk in the constructor section:
<img width="756" alt="Screen Shot 2022-10-14 at 8 13 03 AM" src="https://user-images.githubusercontent.com/12074/195881301-c33b3b7f-2929-4da5-b13a-0369a6eacf1d.png">

`VPC:CidrBlock` is not a required input. The docs on the page linked above say "... CIDR can be explicitly set _or it can be derived from IPAM_". I double-checked with Amazon's API specification and it is not listed as a required input there.
