### ISSUE TITLE
Mac DNS resolution failing CGO_ENABLED=0 for macos

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-aws#2185]
### What happened?

Hi I have a DNS resolution problem on my Mac (M1) with pulumi AWS provider

I keep getting error
```
 1 error occurred:
    	* error reading EC2 VPC (vpc-0f364d0fbd5be0015) ClassicLinkDnsSupported: RequestError: send request failed
    caused by: Post "https://ec2.eu-central-1.amazonaws.com/": dial tcp: lookup ec2.eu-central-1.amazonaws.com on 192.168.168.254:53: no such host
```

My DNS servers are coming from DHCP server (my router):
```
nameserver 192.168.168.254
nameserver 213.75.63.75
nameserver 213.75.63.76
```

When I set my DNS server to `213.75.63.75` pulumi then starts working 

I suspect it is the same case as these issues
https://github.com/hashicorp/terraform/issues/3536
https://github.com/hashicorp/terraform-provider-kubernetes/issues/969

### Steps to reproduce

n/a

### Expected Behavior

no dns problems

### Actual Behavior

dns is not resolving

### Output of `pulumi about`

5.16.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by 1oglop1** [comment]
Perhaps someone can help me modify my fork to build the binary I can test https://github.com/jans-forks/pulumi-aws/actions/runs/3288534376/jobs/5418989775

**Comment by guineveresaenger** [comment]
Hi @1oglop1 - you should be able to build your own provider locally, running `make provider`.

As for the resolution failure, we're not certain it's an M1 issue specifically, but rather a result of [an upstream Golang resolver issue](https://github.com/golang/go/issues/12524) and as such we have very limited options to address this here.

**Comment by thomas11** [comment]
The linked upstream issue was fixed.
