### ISSUE TITLE
rum - AppMonitor returns name instead of id

### ISSUE THREAD

**Issue by piwysocki** [pulumi/pulumi-aws#2187]
### What happened?

I'm creating new rum AppMonitor and trying to obtain an id:

```
const appMonitor = new aws.rum.AppMonitor("name_of_app_monitor", { domain: "*.example.com" });
console.log(appMonitor.id); //this logs name instead of an id
```

We have to put AppMonitor ID into RUM code snippet:

[https://github.com/aws-observability/aws-rum-web/blob/main/docs/cdn_installation.md#arguments](url)

![id](https://user-images.githubusercontent.com/86244209/151339258-b497906a-70f6-4778-b7ca-7346c5fa6393.png)

### Steps to reproduce

1.  Create AppMonitor using Pulumi AWS Classic package
`const appMonitor = new aws.rum.AppMonitor("name_of_app_monitor", { domain: "*.example.com" });`
2.  Log appMonitor.id
`console.log(appMonitor.id); //this logs name instead of an id`

### Expected Behavior

Expected: appMonitor.id should be 

> The provider-assigned unique ID for this managed resource.

### Actual Behavior

appMonitor.id is name

### Additional context

![screenshot from AWS](https://user-images.githubusercontent.com/86244209/151314992-4235835a-3519-4ad9-b50d-cd49f41239ad.png)

[Documentation](https://www.pulumi.com/registry/packages/aws/api-docs/rum/appmonitor/#outputs)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @piwysocki, this appears to be exactly the same core issue as the one you filed in https://github.com/pulumi/pulumi-aws-native/issues/333. 

This provider is generated based on the terraform AWS definitions and would therefore need to be fixed there first. It appears that this is the relevant upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/26430

**Comment by mikhailshilkov** [comment]
`appMonitorId` has been exported upstream in https://github.com/hashicorp/terraform-provider-aws/pull/26994
