### ISSUE TITLE
User agent is TF instead of Pulumi

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-aws#2190]
### What happened?

Read logs show

```
userAgent": "aws-sdk-go/1.44.12 (go1.19.1; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/ (+https://www.terraform.io/)"
```

### Steps to reproduce

The exact affected version of pulumi-aws is unknown at this point.

### Expected Behavior

The User Agent should be Pulumi, similar to this

```
User-Agent: APN/1.0 Pulumi/1.0 Pulumi-Aws/4.17.0-alpha.1629393364+0b9d696e.dirty (+https://www.pulumi.com/) aws-sdk-go/1.40.20 (go1.16.4; darwin; amd64)
```

### Actual Behavior

see above

### Additional context

related previous PR: #1604 

see `internal/conns/conns.go:StdUserAgentProducts`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
I tried with 5.18.0 and I am seeing
```
User-Agent: APN/1.0 Pulumi/1.0 Pulumi/1.0 Pulumi-Aws/0.11+compatible (+https://www.pulumi.com) aws-sdk-go-v2/1.16.16 os/macos lang/go/1.19.1 md/GOOS/darwin md/GOARCH/amd64 api/sts/1.16.4
```
in calls to `GetCallerIdentity`. Note the provider version is indeed not propagating. Looks like while we made the change in https://github.com/pulumi/ci-mgmt/pull/264/ to set the `ProviderVersion` correctly, we aren't actually using it and using the `terraformVersion` as the version for pulumi-aws. See https://github.com/pulumi/terraform-provider-aws/pull/70 for a fix there.

Do we know what version of the provider and what resource they are running into this issue with as yet?  Looking through the code, AFAICS the session for services is [correctly seeded](https://github.com/pulumi/terraform-provider-aws/blob/f0bb13fb9328269659a8f44db29519c52f29ce3a/internal/conns/config_gen.go#L296) by a session generated using the aws config with the right APN user agent middleware handler which generates the user agent string.
