### ISSUE TITLE
aws.s3.BucketObject does not detect diff when `source` is a string

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-aws#2198]
### What happened?

I did not get an expected diff in a resource and it hurt my feelings.

### Steps to reproduce

Given this project:

```typescript
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("jkodroff-test-bucket-object", {
  versioning: {
    enabled: true,
  }
});

const functionCode = new aws.s3.BucketObject("file.txt", {
  bucket: bucket.bucket,
  key: "file.txt",
  source: "file.txt",
});
```

Changing the contents of `file.txt` does not create a diff in the `BucketObject`.

Note that `source: new pulumi.asset.FileAsset("file.txt")` works as expected.

### Expected Behavior

Either changing the contents of the file should create a diff in the resource or a plain old string should not be accepted as input. (Note when a string is passed to `source`, it appears to upload the file, not the literal string.)

### Actual Behavior

No diff, plus hurt feelings.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
I believe this is just the way the AWS terraform provider is implemented. If a change is detected in the value of the `source` there, then a fresh upload is performed. A change in the content of the file referenced in `source` will not trigger the upload. https://github.com/hashicorp/terraform-provider-aws/blob/e1d68faa27997073d80bd71ae99f73a40a6ef20c/internal/service/s3/bucket_object.go#L580

**Comment by viveklak** [comment]
I am happy to mark this as a feature request if you think this is a common mechanism. I do think the asset model in Pulumi is more powerful/appropriate for this reason.

**Comment by jkodroff** [comment]
@viveklak Is is feasible to make it so that `source` does not accept a string (which does not behave as expected) and instead forced the user to use an asset (which does behave as expected)?
