### ISSUE TITLE
Is there support for the new AWS region "me-central-1"

### ISSUE THREAD

**Issue by aidanhyland** [pulumi/pulumi-aws#2202]
##  Question

Looking to deploy resources to me-central-1 but with the latest versions of Pulumi, it seems there isn't support for this region.
Is this correct?

[Terraform added support](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4290-september--1-2022)

[Now Open–AWS Region in the United Arab Emirates (UAE)](https://aws.amazon.com/blogs/aws/now-open-aws-region-in-the-united-arab-emirates-uae/)

**Comment by aidanhyland** [comment]
Hi @lblackstone , 

Thanks for the reply, I'll take a look at v5.20.0 & let you know. 

Aidan

**Comment by aidanhyland** [comment]
Hi @lblackstone, 

Upgraded to the latest version `5.21.1` and I'm still seeing issues. Has anyone else reported similar?

`const emea3Provider = new Provider("emea3-provider", {
  region: "me-central-1",
  profile: "nebula-emea3",
});`

`error TS2820: Type '"me-central-1"' is not assignable to type 'Input<Region> | undefined'. Did you mean '"eu-central-1"'?`

**Comment by lblackstone** [comment]
@danielrbradley Any idea?

**Comment by danielrbradley** [comment]
Need to track down where that type is coming from. As a workaround you might be able to use `"me-central-1" as any` to skip the language validation.

**Comment by danielrbradley** [comment]
For new regions, in addition to bypassing the language validation, you also need to set `skipRegionValidation` to `true` in the [provider configuration](https://www.pulumi.com/registry/packages/aws/installation-configuration/#configuration-options)
