### ISSUE TITLE
Pulumi hangs on invalid AWS credentials

### ISSUE THREAD

**Issue by musmuris** [pulumi/pulumi-aws#2205]
### What happened?

Trying to get a lambda deployed by pulumi AWS.  I'd not updated my AWS credentials and when running `pulumi up` or `preview` it hangs. 

```
C:\temp\Sandboxes\test-lambda-1\infrastructure>pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/nexar-devops/....

     Type                 Name                             Plan       Info
 +   pulumi:pulumi:Stack  test-lambda-1-dev       create
     └─ aws:iam:Role      test-lambda-1-dev-role             error: unable to validate AWS credentials.
```

### Steps to reproduce

`__main.py__`  below.  Old (out of date) credentials in ~\.aws\credentials

```
"""lambda test"""

import json
import pulumi
import pulumi_aws as aws

project = pulumi.get_project()
stack = pulumi.get_stack()
project_full_name = f"{project}-{stack}"

publishFolder = "C:\\temp\\Sandboxes\\test-lambda-1\\bin\\Release\\net6.0\\publish"

role = aws.iam.Role(
    resource_name=project_full_name + "-role",
    assume_role_policy=json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {"Service": "lambda.amazonaws.com"},
                    "Action": "sts:AssumeRole",
                }
            ],
        }
    ),    
    managed_policy_arns=[
        aws.iam.ManagedPolicy.AWS_LAMBDA_BASIC_EXECUTION_ROLE,
        aws.iam.ManagedPolicy.AWS_LAMBDA_VPC_ACCESS_EXECUTION_ROLE,
        aws.iam.ManagedPolicy.AMAZON_KINESIS_READ_ONLY_ACCESS,
    ],
)

test_lambda = aws.lambda_.Function(
    resource_name=project_full_name + "",
    code = FileArchive(publishFolder),
    role=role.arn,
    handler = "test-lambda-1::test_lambda_1.Function::FunctionHandler",
    timeout=300,
    runtime="dotnet6",
)
```

### Expected Behavior

Error is expected - but then should display and exit.

Using "live" URL can see additional information (saying it got a 403 error) but this isn't shown on the console and the deployment is hanging there as well  (started 18 mins ago as of writing)

### Actual Behavior

Hangs - just sits there. Cannot CTRL-C break out either

### Output of `pulumi about`

```
CLI
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.20.0
python  unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in python: executable='C:\Users\<usrer>\AppData\Local\Microsoft\WindowsApps\python.exe' version='3.10.8
'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/nexar-devops
<redacted>

Dependencies:
NAME               VERSION
boto               2.49.0
boto3              1.26.3
cryptography       38.0.1
docutils           0.15.2
Flask              2.2.2
pip                22.3.1
pulumi-aws         5.20.0
PySpice            1.5.0
requests-oauthlib  1.3.1
requests-toolbelt  0.9.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by musmuris** [comment]
Adding to this - it seems to be any error that happens in the AWS provider.  The error get's logged so it can been seen on the service but it doesn't print to local console and then hangs

**Comment by squaremo** [comment]
I have seen behaviour like this while messing around with the Pulumi Kubernetes operator. I tried a minimal reproduction:

```bash
mkdir issue2205
cd issue2205
pulumi new aws-python
# paste in the program given above, with minor edits for macos
pulumi preview
```

With just an old AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, I got

```
Diagnostics:
  aws:iam:Role (python-dev-role):
    error: unable to validate AWS credentials.
    Details: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: a8cbc2d6-3696-485b-99e0-08e28163bd3d, api error InvalidClientTokenId: The security token included in the request is invalid.
    
    Make sure you have:
    
         • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
         • Configured your AWS credentials as per https://pulumi.io/install/aws.html
         You can also set these via cli using `aws configure`.
```

With an expired AWS_SESSION_TOKEN, I got

```
Diagnostics:
  aws:iam:Role (python-dev-role):
    error: unable to validate AWS credentials.
    Details: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: ba7eb278-1a81-4124-8d6f-dac1fcf41cff, api error ExpiredToken: The security token included in the request is expired
    
    Make sure you have:
    
         • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
         • Configured your AWS credentials as per https://pulumi.io/install/aws.html
         You can also set these via cli using `aws configure`.
```

So with my naive attempt to reproduce the problem, it works as expected.

However: when working on the operator, I noticed that often a test involving AWS would time out waiting for anything to happen, and the test suite would sit there until I killed the pulumi-resource-aws process. Refreshing my AWS credentials always fixed it. So I do believe there's a problem here -- there's just a subtlety I'm missing.

Do you have a foolproof way to generate credentials which cause this failure, @musmuris?

**Comment by musmuris** [comment]
_I_ have a foolproof way, yes - which is I go via the corporate SSO and then wait ~24 hours for them to timeout 😂 

However I have since discovered this happens, on my machine at least, for pretty much any error that I got from AWS when getting it working - valid credentials or otherwise.  I'll try and get a reproduceable scenario next week.  Just to clarify this is on windows in a CMD shell.

**Comment by squaremo** [comment]
Ha yes, that is my foolproof method as well 😁. If you can find a repro that doesn't rely on credentials that would be brilliant -- thanks for putting time into this, really appreciated.

**Comment by mjeffryes** [comment]
Anecdotally, this doesn't seem to happen anymore and this report is very old; we can file a new ticket if this issue pops up again.
