### ISSUE TITLE
aws.iam.AccountAlias can't be changed

### ISSUE THREAD

**Issue by filip-zyzniewski** [pulumi/pulumi-aws#2208]
### What happened?

Pulumi fails after changing the `aws.iam.AccountAlias`'es  `alias` attribute.

### Steps to reproduce

Have the following code applied:

```python
pulumi_aws.iam.AccountAlias(
    "somealias",
    account_alias="somealias",
)
```

Introduce the following change:

```python
pulumi_aws.iam.AccountAlias(
    "somealias",
    account_alias="someotheralias",
)
```

### Expected Behavior

I expected `pulumi up` to complete successfully and the alias to be updated.

### Actual Behavior

Pulumi wants to replace the resource:

```diff
+-aws:iam/accountAlias:AccountAlias: (replace)
[...]
~ accountAlias: "somealias" => "someotheralias"
        --outputs:--
      ~ id          : "somealias" => "someotheralias"
error: deleting [...]::aws:iam/accountAlias:AccountAlias::somealias: 1 error occurred:
	* Error deleting account alias with name 'somealias': NoSuchEntity: The account alias somealias cannot be found.
	status code: 404, request id: [...]
```

It probably fails miserably because https://www.pulumi.com/registry/packages/aws/api-docs/iam/accountalias/#accountalias:

> Note: There is only a single account alias per AWS account.

The replace (create/delete) model does not seem like a good match for a singleton.

### Output of `pulumi about`

```console
$ pulumi about                    
CLI          
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.20.0
awsx        1.0.0-beta.10
docker      3.5.0
eks         0.42.7
kubernetes  3.22.1
python      unknown

Host     
OS       darwin
Version  12.2
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.10.8
'

Current Stack: [...]

TYPE                                               URN
[...]


Found no pending operations associated with [...]

Backend        
Name           pulumi.com
URL            [...]
User           [...]
Organizations  [...], [...]

Pulumi locates its logs in /var/folders/xc/rb73zyjd3kq26tv0hpk4wxh40000gq/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: illegal semver returned by language host: pulumi-awsx@1.0.0b10: Invalid character(s) found in patch number "0b10"
$
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by filip-zyzniewski** [comment]
The workaround is to add `opts=pulumi.ResourceOptions(delete_before_replace=True)` .

**Comment by lblackstone** [comment]
Thanks for the report and workaround @filip-zyzniewski. I opened a PR that should fix the replace behavior for this resource.
