### ISSUE TITLE
Aliases resource option isn't working with the TargetGroup resource in Go SDK

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-aws#2217]
### What happened?

I have a `TargetGroup` resource that I'd like to rename. However, passing the `Aliases` resource option doesn't seem to work. Pulumi still wants to replace the resource because the name has changed. Note that I am using the Go SDK for this provider.

### Steps to reproduce

1. Create a target group resource first in your stack.
2. Rename the resource and provide the `Aliases` resource option.

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
        "github.com/pulumi/pulumi-aws/sdk/v5/go/aws/alb"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

vpc, _ := ec2.NewVpc(ctx, vpcName, &ec2.VpcArgs{
		CidrBlock:          pulumi.String("10.0.0.0/16"),
		EnableDnsHostnames: pulumi.Bool(true),
})

targetGroupName := "targetGroup"
targetGroup, _ := alb.NewTargetGroup(ctx, targetGroupName, &alb.TargetGroupArgs{
                // I am not using auto-naming for this resource.
		Name:            pulumi.String(targetGroupName+"-2"),
		Port:               pulumi.Int(input.HostPort),
		Protocol:        pulumi.String("HTTP"),
		VpcId:            vpc.Id,
		ProtocolVersion: pulumi.String("GRPC"),
}, pulumi.Aliases([]pulumi.Alias{{Name: pulumi.String(targetGroupName)}}))
```

### Expected Behavior

No changes to the stack since the resource is properly aliased.

### Actual Behavior

A resource replacement for the renamed resource is proposed by Pulumi.

### Output of `pulumi about`

⚠️ sanitized output to remove sensitive info.

```
CLI
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME  VERSION
aws   5.1.2
go    unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

...
...
...
Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v5  5.1.2
github.com/pulumi/pulumi/sdk/v3      3.46.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @praneetloke! I notice that your pulumi-aws version is from April. It might be unrelated but I'd suggest giving upgrading it a try. In the meantime, I'll check with some aliasing SMEs.

**Comment by praneetloke** [comment]
> on second glance I think I see what's happening [here](https://www.pulumi.com/docs/intro/concepts/resources/names/). You've renamed and aliased the physical (cloud provider) name of the resource. That is not supported by aliases since, they are only for logical (Pulumi) names. See here for the distinction. In your example, you could rename the second argument to NewTargetGroup and alias it to the old name.

Ah. My bad. I guess I need to swap the names which should fix this. I'll test that.

**Comment by praneetloke** [comment]
@thomas11 the corrections worked. Thank you for setting my understanding straight with aliases. It, of course, makes sense to me now that Pulumi can't alias a provider's own resource! 🤦‍♂️ Apologies for the distraction.

<details>

<summary>Corrected app</summary>

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
        "github.com/pulumi/pulumi-aws/sdk/v5/go/aws/alb"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

vpc, _ := ec2.NewVpc(ctx, vpcName, &ec2.VpcArgs{
		CidrBlock:          pulumi.String("10.0.0.0/16"),
		EnableDnsHostnames: pulumi.Bool(true),
})

targetGroupName := "targetGroup"
// The Pulumi resource name (aka logical name) can be renamed with an alias.
targetGroup, _ := alb.NewTargetGroup(ctx, targetGroupName+"2", &alb.TargetGroupArgs{
                // Can't alias this since it's the name of the resource used by the provider.
		Name:            pulumi.String(targetGroupName),
		Port:               pulumi.Int(input.HostPort),
		Protocol:        pulumi.String("HTTP"),
		VpcId:            vpc.Id,
		ProtocolVersion: pulumi.String("GRPC"),
}, pulumi.Aliases([]pulumi.Alias{{Name: pulumi.String(targetGroupName)}}))
```
</details>

**Comment by thomas11** [comment]
No worries and glad I could help!
