### ISSUE TITLE
gp3 not supported on aws rds

### ISSUE THREAD

**Issue by altais** [pulumi/pulumi-aws#2218]
### What happened?

Aws release support for GP3 storage on rds: https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

Right now, the package only allow us to set standard, gp2 or io1 in the enum `Instance.StorageType`

error: aws:rds/instance:Instance resource 'postgresql-rds-server' has a problem: expected storage_type to be one of [standard gp2 io1], got gp3. Examine values at 'Instance.StorageType'.

### Steps to reproduce

```
const postgresqlRdsServer = new aws.rds.Instance("postgresql-rds-server", {
    engine: "postgres",
    engineVersion: "14.5",
    username: pulumiConfig.require("username"),
    password: pulumiConfig.requireSecret("password"),
    maintenanceWindow: "Mon:03:00-Mon:04:00",
    backupWindow: "22:00-03:00",
    instanceClass: "db.m6g.large",
    allocatedStorage: 400,
    backupRetentionPeriod: 30,
    multiAz: true,
    performanceInsightsEnabled: true,
    performanceInsightsRetentionPeriod: 31,
    storageEncrypted: true,
    storageType: "gp3",
    skipFinalSnapshot: false,
    publiclyAccessible: false,
    dbSubnetGroupName: subnetGroup.name,
    vpcSecurityGroupIds: [rdsSecurityGroup.id],
    allowMajorVersionUpgrade: true
})
```

### Expected Behavior

Be able to create rds with gp3 storage

### Actual Behavior

error: aws:rds/instance:Instance resource 'postgresql-rds-server' has a problem: expected storage_type to be one of [standard gp2 io1], got gp3. Examine values at 'Instance.StorageType'.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @altais, thank you for letting us know! Support for gp3 will come soon, although I'm not able to give a concrete time frame right now. It's not supported in the underlying Terraform provider yet.
