### ISSUE TITLE
Support for Neptune Serverless

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-aws#2229]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Recently, AWS released Neptune Serverless: https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-neptune-serverless-generally-available/

This feature has also been included in Terraform (https://github.com/hashicorp/terraform-provider-aws/pull/27763), so it would be nice to have it available in pulumi too. 

### Affected area/feature

Pulumi AWS package. Neptune service: https://www.pulumi.com/registry/packages/aws/api-docs/neptune/

**Comment by danielrbradley** [comment]
Yup, hoping to get this release out shortly :)

**Comment by thomas11** [comment]
Hi @albertocorrales, [Neptune Serverless](https://www.pulumi.com/registry/packages/aws/api-docs/neptune/cluster/#serverlessv2scalingconfiguration_go) is now available in pulumi-aws 5.22.0.
