### ISSUE TITLE
New Kinesis Analytics runtime environment missing

### ISSUE THREAD

**Issue by mattfysh** [pulumi/pulumi-aws#2230]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently unable to upload a Kinesis Analytics app using the newest runtime (`FLINK-1_15`)

```
Diagnostics:
  aws:kinesisanalyticsv2:Application (<snip>):
    error: aws:kinesisanalyticsv2/application:Application resource '<snip>' has a problem: expected runtime_environment to be one of [SQL-1_0 FLINK-1_6 FLINK-1_8 ZEPPELIN-FLINK-1_0 FLINK-1_11 FLINK-1_13 ZEPPELIN-FLINK-2_0], got FLINK-1_15. Examine values at 'Application.RuntimeEnvironment'.
```

### Affected area/feature

Module `kinesisanalayticsv2`

**Comment by lblackstone** [comment]
Hi @mattfysh -- you didn't indicate which version of the provider that you're using, but this validation error is coming from an older version of the aws sdk, and should be fixed in the latest release.

https://github.com/pulumi/terraform-provider-aws/blob/patched-v4.42.0/go.mod#L7
https://github.com/aws/aws-sdk-go/commit/1356aada4806053cf6a64f66288912c9625fa016#diff-d6ee7cddb85132c8e4a2732b17c323705c690519d23ad9a49cf98706d186c951R15891

**Comment by mattfysh** [comment]
hey @lblackstone apologies! I landed here from the npm pkg and falsely assumed the whole repo was for the node.js plugin

I am using:
- pulumi CLI v3.48.0 (installed via homebrew)
- nodejs `@pulumi/pulumi` v3.48.0
- nodejs `@pulumi/aws` v5.21.1

I'm having a hard time following the upstream dependencies so unfortunately unable to know which of those 3 packages contains the outdated enum. Let me know if I can offer any more info, cheers!

**Comment by lblackstone** [comment]
Ok, I double-checked the dependencies for `@pulumi/aws@v5.21.1`, and confirmed that it's pulling in an older version of the aws SDK that does not include the enum. We are in the process of releasing a new version in https://github.com/pulumi/pulumi-aws/pull/2237 that does include the dependency you need, so this should be resolved once that's out.

---

Here's the dependency chain in case you're interested:
[upstream fix which is first available in v1.44.144](https://github.com/aws/aws-sdk-go/commit/1356aada4806053cf6a64f66288912c9625fa016#diff-d6ee7cddb85132c8e4a2732b17c323705c690519d23ad9a49cf98706d186c951)

[pulumi-aws@v5.21.1](https://github.com/pulumi/pulumi-aws/blob/v5.21.1/provider/go.mod#L17)
[pulumi/terraform-provider-aws@4f71b6571c4a](https://github.com/pulumi/terraform-provider-aws/blob/4f71b6571c4a1dcafadf0de636c216bcf6382637/go.mod#L7)
`v1.44.133` is older than `v1.44.144`, so doesn't include the enum fix

**Comment by mattfysh** [comment]
Thank you :) will keep an eye on the PR.

**Comment by mattfysh** [comment]
Hey @lblackstone - are you sure the linked pull request will bring in the updated enum? I see it is upgrading to `v4.42.0` but when I look at the documentation for this version, I don't see the new enum value of `FLINK-1_15`

https://registry.terraform.io/providers/hashicorp/aws/4.42.0/docs/resources/kinesisanalyticsv2_application

It appears the Flink v1.15 option only appears in the documentation for v4.44.0 onwards

**Comment by lblackstone** [comment]
I believe the documentation is updated separately from the underlying aws client SDK, so it wouldn't surprise me if it lags a bit, but let us know if the issue isn't resolved with this release as I expected.
