### ISSUE TITLE
Problems using external libraries in Pulumi (installed using pip)

### ISSUE THREAD

**Issue by LiamLairdAG** [pulumi/pulumi-aws#2236]
Hi,

I installed jsonSchema using pip into my repo. When I run the file from the command line it works fine.

`python3 validate_config.py`

However when I run

`pulumi up`

I get the error

`ModuleNotFoundError: No module named 'jsonschema'`

I can't seem to find any documentation on how to manage external libraries in Pulumi projects. Do I have to run certain commands to add this module to pulumi's path?

**Comment by lblackstone** [comment]
Hi @LiamLairdAG, I think https://www.pulumi.com/docs/intro/languages/python/#packages has the information you need. I'd suggest asking in our community slack if you're still having troubles with it after that.
