### ISSUE TITLE
import error in @pulumi/aws/types/s3/input.ts after c984ddf

### ISSUE THREAD

**Issue by 742617000027** [pulumi/pulumi-aws#2243]
### What happened?

It seems that https://github.com/pulumi/pulumi-aws/commit/c984ddfba812c33e5ebf7267cdf9c1498174f3d4 might  have introduced an import error in https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/s3/input.ts on line 10. 

Instead of `import {RoutingRule} from "@/s3";` it should probably be `import {RoutingRule} from  "@pulumi/aws/s3";`.

It results in a compile error when running `tsc` in projects that depend on @pulumi/aws.

```
> tsc

node_modules/@pulumi/aws/types/s3/input.d.ts:3:29 - error TS2307: Cannot find module '@/s3' or its corresponding type declarations.

3 import { RoutingRule } from "@/s3";
```

### Steps to reproduce

Add `"@pulumi/aws": "^5.22.0"` to the dependencies of a project und run `tsc` on it.

### Expected Behavior

For the compiler not to throw.

### Actual Behavior

Compiler throws.

### Output of `pulumi about`

Identifying information replaced with `[...]`.

```
[...]@[...] [...]_infrastructure_shared % pulumi about
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Host     
OS       darwin
Version  12.6
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/[...]
User           [...]
Organizations  [...], [...]

Pulumi locates its logs in /var/folders/sf/0f34djss1j917pd41kk0lwqc0000gn/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /Users/[...]/projects/node/products_v1/web_modules/libs/[...]_infrastructure_shared). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /Users/[...]/projects/node/products_v1/web_modules/libs/[...]_infrastructure_shared). If you have not created a project yet, use `pulumi new` to do so: no project file found

```

### Additional context

<3 Pulumi

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @742617000027, thanks for the issue! I've passed this along to the team who are looking at it now.

**Comment by lionello** [comment]
Confirmed. Changing the `@pulumi/aws` entry in `package.json` to `"~5.21.0"` (followed by `yarn`) fixed the issue for me.
