### ISSUE TITLE
Incorrect ARN for Managed Policy `AWSConfigRole`

### ISSUE THREAD

**Issue by chrisfentiman** [pulumi/pulumi-aws#2244]
### What happened?

Hi!

Within the ManagedPolicy enums, the arn for `AWSConfigRole` is `"arn:aws:iam::aws:policy/service-role/AWSConfigRole"` which does not exist. The correct arn in AWS is `arn:aws:iam::aws:policy/service-role/AWS_ConfigRole`. It seems this role is missing the `_`.

AWS Documentation:
https://docs.aws.amazon.com/config/latest/developerguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AWS_ConfigRole

Pulumi/aws code reference:
https://github.com/pulumi/pulumi-aws/blob/c984ddfba812c33e5ebf7267cdf9c1498174f3d4/sdk/nodejs/types/enums/iam/index.ts#LL39-L39C73

### Steps to reproduce

```
import * as aws from "@pulumi/aws"

aws.iam.ManagedPolicy.AWSConfigRole
```

### Expected Behavior

The `AWSConfigRole` to be valid (e.g., `arn:aws:iam::aws:policy/service-role/AWS_ConfigRole`)

### Actual Behavior

the `AWSConfigRole` is `arn:aws:iam::aws:policy/service-role/AWSConfigRole`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @chrisfentiman, thanks for the issue! We're taking a look at it now so it may be appropriately prioritized and added to our work stack.

It appears that there is both an `AWSConfigRole` and an `AWS_ConfigRole` (with the former being deprecated a few years ago). This might be related to this issue?

**Comment by chrisfentiman** [comment]
Ahh! That does seem to be the case. You are right. AWS deprecated the `AWSConfigRole` [earlier this year](https://aws.amazon.com/blogs/mt/service-notice-upcoming-changes-required-for-aws-config/)

Would be great to have it updated! Thanks for the speedy response @roothorp
