### ISSUE TITLE
Add NodeJS 18.x runtime

### ISSUE THREAD

**Issue by mbogh** [pulumi/pulumi-aws#2251]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

On the 18th of November, AWS added support for [NodeJS 18.x runtime](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/) and it is also listed in the [Lambda runtimes list](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

### Affected area/feature

Only affected area seem to be the Enums of the supported languages, in the top of the file it says autogenerated by tfgen, if someone can point me towards how to run this tool, I will gladly make a PR :)

**Comment by mbogh** [comment]
Or can we just add it manually to the enum files?

**Comment by pierskarsenbarg** [comment]
@mbogh you can use the string value in the runtime field. We don't validate it, leaving that to AWS

**Comment by mbogh** [comment]
@pierskarsenbarg we know, types are just 😍

**Comment by roothorp** [comment]
Thanks for the issue @mbogh! I would've expected this to have been picked up in a provider upgrade as it is present upstream, so we'll investigate why that hasn't happened and try to get it resolved. Hopefully for the time being you can use a string value as Piers suggested!

**Comment by IsaacBord** [comment]
I guess I am back to using 'node-fetch' 😢
