### ISSUE TITLE
Support for AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by MMartyn** [pulumi/pulumi-aws#2252]
### What happened?

The credential validation that is currently in here doesn't handle AssumeRoleWithWebIdentity. So if you use AssumeRoleWithWebIdentity then you currently need to skip the validation checks.

### Steps to reproduce

Attempt to use AssumeRoleWithWebIdentity

### Expected Behavior

It to seemlessly work regardless of if you are using keys, roles, or web identities.

### Actual Behavior

You get an error saying that the credentials couldn't be validated.

### Additional context

Relevant code: 
https://github.com/hashicorp/terraform-provider-aws/blob/46dbaeb5a40328b9a5200de13fa842700c5a1a35/internal/provider/provider.go#L2316
https://github.com/pulumi/pulumi-aws/blob/master/provider/resources.go#L340

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @MMartyn, thanks for the issue! I've raised this with the team to be prioritized and added to our work stack.
