### ISSUE TITLE
The LifecyclePolicyPolicyDetailsScheduleCreateRule description is wrong

### ISSUE THREAD

**Issue by TimLukasDev** [pulumi/pulumi-aws#2253]
Described is that 

**LifecyclePolicyPolicyDetailsScheduleCreateRule** 

can use the attribute [intervalUnit] with everythink from DAYS to YEARS but in reality it can only be used with HOURS also the description for [interval] is wrong because there stands "The amount of time to retain each snapshot" but i think with that option you can define in which interval an snapshot should be created.

 has a problem: expected policy_details.0.schedule.0.create_rule.0.interval to be one of [1 2 3 4 6 8 12 24], got 9. Examine values at 'LifecyclePolicy.PolicyDetails.Schedule[0].CreateRule[0].Location'.

 error: aws:dlm/lifecyclePolicy:LifecyclePolicy resource '***********' has a problem: expected policy_details.0.schedule.0.create_rule.0.interval_unit to be one of [HOURS], got DAYS. Examine values at 'LifecyclePolicy.PolicyDetails.Schedule[0].CreateRule[0].Times'.

File: [themes/default/content/registry/packages/aws/api-docs/dlm/lifecyclepolicy/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/dlm/lifecyclepolicy/)

**Comment by roothorp** [comment]
Hi @TimLukasDev, thanks for the issue! Looking at the upstream provider, it looks like (as the error suggests) create rules only allow the interval unit to be `HOURS`. I apologise for the error in our docs.

It looks like the descriptions for these fields are erroneously using the descriptions for the retain rules, hence the "retain each snapshot" and the incorrect intervalUnits (as retain rules do allow Days/Weeks/Months/Years).

**Comment by lukehoban** [comment]
This is another case of https://github.com/pulumi/pulumi-terraform-bridge/issues/529.  I'll close this out as a duplicate so that we can track the needed improvement there.
