### ISSUE TITLE
Leaking "Managed by terraform" when user leaves comment blank in Route53

### ISSUE THREAD

**Issue by Tperklumi** [pulumi/pulumi-aws#2256]
When a user creates a Route53 resource, they see "Managed by Terraform" whenever a comment isn't added.

**Comment by blampe** [comment]
Related https://github.com/pulumi/home/issues/476 https://github.com/pulumi/registry/issues/1297


![](https://user-images.githubusercontent.com/106352758/206800884-676a4ca3-59f4-4b87-8ada-3a64d4b9615d.png)
