### ISSUE TITLE
AWS Provider Docs - Lambda Function - Typescript - Missing Runtime enum section

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#2263]
### What happened?

Selected Typescript and 
went here: https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#runtime
Expected to the enums list but see nothing.

For comparison select Python and go the Runtime section and you'll see enums.

### Steps to reproduce

- Go to https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function
- Select typescript
- navigate to the runtime property and select the `Runtime` link which will take you to:  https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#runtime
- See that there is no enums listed

### Expected Behavior

There should be some information in the section.

### Actual Behavior

The section is empty.

### Output of `pulumi about`

N/A

### Additional context

If, say, Python is selected, there is a docs section for Runtime.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
There's something more generally screwy about that page -- there's a set of examples in different languages that appear one after another at the top. I think there's a docs generation problem underlying both things. It might be related to #2259.

**Comment by sean1588** [comment]
resolved by: https://github.com/pulumi/registry/issues/3724
