### ISSUE TITLE
cdc_min_file_size incorrect docstrings definition and default value

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [pulumi/pulumi-aws#2264]
### What happened?

https://github.com/pulumi/pulumi-aws/blob/9b42f6461c8f7476508da3ef0f24f7a54af24473/sdk/python/pulumi_aws/dms/_inputs.py#L890 states that value is defined in megabytes but value defined in kylobytes

### Steps to reproduce

NA

### Expected Behavior

Docstring should be correct

### Actual Behavior

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
Hi, thank you for posting this. I'm looking at the inputs for S3Endpoint (https://www.pulumi.com/registry/packages/aws/api-docs/dms/s3endpoint/#cdc_min_file_size_python) which has units of kilobytes and a default of 32MB, and the inputs for Endpoint (https://www.pulumi.com/registry/packages/aws/api-docs/dms/endpoint/#cdc_min_file_size_python) which has units of megabytes and a default of 32. So, the two field have the same default quantity, but the units are different.

If the unit for the field in EndpointS3Settings were kilobytes, the default quantity would be 32KB, different to the analogous field in S3Endpoint. These are the possible situations:

 1. the unit is KB and the default quantity really is different;
 2. the unit and default are as given; they are just, confusingly, different units
 3. the unit and default are actually the same as the other field, and the docstring is wrong

I think 2.) is the most likely, but if it's 3.), that's a big problem! Do you have evidence pointing at any of those cases?

**Comment by SoumayaMauthoorMOJ** [comment]
Hey Micheal

We have set cdc_min_file_size to 32000 as follows:

```
   targetEndpoint = aws.dms.Endpoint(
        resource_name=f"{database_name}-target-{region}-{env}",
        endpoint_id=f"{database_name}-target-{region}-{env}",
        endpoint_type="target",
        engine_name=target_endpoint_config["engine_name"],
        extra_connection_attributes=format_extra_connection_attributes(
            target_extra_connection_attributes
        ),
        s3_settings=aws.dms.EndpointS3SettingsArgs(
            bucket_folder=s3_settings["bucket_folder"],
            bucket_name=s3_settings["bucket_name"],
            compression_type=s3_settings.get("compression_type", "GZIP"),
            date_partition_enabled=s3_settings.get("date_partition_enabled", None),
            service_access_role_arn=dmsRole.arn,
            data_format="parquet",
            parquet_version="parquet-2-0",
            parquet_timestamp_in_millisecond=True,
            encryption_mode="SSE_S3",
            add_column_name=True,
            timestamp_column_name="EXTRACTION_TIMESTAMP",
            canned_acl_for_objects="bucket-owner-full-control",
            cdc_max_batch_interval=3600,
            cdc_min_file_size=32000,
            include_op_for_full_load=True,
        ),
        tags=tagger.create_tags(f"{database_name}-target-{region}-{env}"),
    )
```
This results in parquet files which are at least 32MB or at most created every hour.  If we don't set cdc_min_file_size, we end up with files which are at least 32 KB.

Note that according to AWS DMS CdcMinFileSize default value is 32MB:
https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html

Hence I think you probably need to:

1. Update doctrings to say KB
1. Update default value to 32000

Cheers
Soumaya

**Comment by mikhailshilkov** [comment]
Fixed to kilobytes now: https://github.com/pulumi/pulumi-aws/blob/0f4e8e5e641e496e4f2d5437d3a9f069952ec67c/sdk/python/pulumi_aws/dms/_inputs.py#L892
