### ISSUE TITLE
AWS ECS Service forceNewDeployment not working

### ISSUE THREAD

**Issue by avanmalleghem** [pulumi/pulumi-aws#2266]
### What happened?

I created a [AWS ECS Service resource](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/service/) using pulumi. This service is associated with a TaskDefinition linked to a docker image with the "latest" tag. The deployment is on Fargate. I fixed the "forceNewDeployment" flag to true in order to deploy my changes each time I push another image to the ECR. Unfortunately, I don't see any new deployment when I update the image on ECR and run "pulumi up" without changing anything in the service.

### Steps to reproduce

(Code executed with Typescript)
- Create an AWS ECS Service with the forceNewDeployment field
- Push an image to an ECR with the latest tag
- Create an AWS TaskDefinition : in the container, use the latest tag for the image
- Deploy pulumi code
- Modify the image and push it to ECR again
- pulumi up

### Expected Behavior

A new deployment should occurs with the modification you did

### Actual Behavior

Nothing happens on ECS

### Output of `pulumi about`

CLI          
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.23.0
cloudflare  4.13.0
nodejs      unknown
random      4.8.2

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/Users/***/.nvm/versions/node/v16.15.0/bin/node' version='v16.15.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
This certainly seems like a bug, as described. Thanks for bringing this to our notice @avanmalleghem 🙏

**Comment by DaniWS** [comment]
Is there any update about this? Experiencing the same issue.

**Comment by luizfp** [comment]
Same problem here.

**Comment by AndresMorelos** [comment]
If you guys are using any CI/CD environment to deploy your infra that lets you know the commit or PR hash, I made a workaround adding the commit/pr hash to force a new deployment.

GitHub example:

```js
const { COMMIT_SHA } = process.env

const getRegistryInfo = () => { ... };

const buildImage = async ({ dockerFilePath, repo, tag = '', contextDir = './' }) => {
    const registry = await getRegistryInfo(repo);

    //Build image 
    const imageName = pulumi.interpolate`${repo.repositoryUrl}:${tag}`
    const image = new docker.Image(dockerFilePath, {
        build: {
            context: contextDir,
            dockerfile: dockerFilePath
        },
        name: imageName,
        imageName,
        registry: registry,
    });

    return {
        baseImageName: image.baseImageName,
        fullImageName: image.imageName,
        imageUri: imageName,
    };
}

// Implementation
const ecrDockerImage = await docker.buildImage({
    repo: ecrRepository,
    tag: COMMIT_SHA,
    dockerFilePath: path.resolve('../', '../', 'apps', 'server', 'Dockerfile.production'),
    contextDir: path.resolve('../', '../'),
});

// LOAD BALANCER NAME || update this settings depending on the application. 
const balancer = new awsx.lb.ApplicationLoadBalancer(LOAD_BALANCER_NAME, {
    name: LOAD_BALANCER_NAME,
    defaultTargetGroup: {
        deregistrationDelay: 60,
        port: PORT,
        protocol: 'HTTP',
        healthCheck: {
            enabled: true,
            port: PORT,
            path: '/',
            interval: 60,
            timeout: 30,
            unhealthyThreshold: 5,
        }
    },
    listener: {
        port: 443,
        protocol: 'HTTPS',
        certificateArn: certificate.arn
    }
});

const ecsCluster = new aws.ecs.Cluster(ECS_CLUSTER_NAME, {
    name: ECS_CLUSTER_NAME,
    configuration: {
        executeCommandConfiguration: {
            logging: "OVERRIDE",
            logConfiguration: {
                cloudWatchEncryptionEnabled: false,
                cloudWatchLogGroupName: ECS_CLOUDWATCH_GROUP_NAME,
            },
        },
    }
});

const containerName = `${REPOSITORY_NAME}-container`
const taskName = `${REPOSITORY_NAME}-task`

const fargateTaskDefinition = new awsx.ecs.FargateTaskDefinition(taskName, {
    containers: {
        [containerName]: {
            name: containerName,
            image: ecrDockerImage.imageUri,
            cpu: 1,
            memory: 128,
            portMappings: [{
                containerPort: PORT,
                targetGroup: balancer.defaultTargetGroup.arn
            }],
            environment: envs
        }
    },
    family: taskName,
})
```

**Comment by corymhall** [comment]
It looks like the way to handle this is with the [triggers](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/service/#triggers_nodejs) property. 

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const example = new aws.ecs.Service("example", {
  triggers: {
    redeployment: time.Now(),
  }
});
```
