### ISSUE TITLE
Add support for OpenSearch VPC Endpoint

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-aws#2267]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
As soon as https://github.com/hashicorp/terraform-provider-aws/pull/28140/files is merged, add support for Opensearch VPC endpoints

**Comment by squaremo** [comment]
This will get picked up in the routine update, once it's in a release of the upstream provider. I'm not sure (genuinely) how realistic it is to have it as soon as the PR gets merged, though.

**Comment by ploxiln** [comment]
I think this exists in pulumi-aws by now?
https://pkg.go.dev/github.com/pulumi/pulumi-aws/sdk/v6/go/aws/opensearch#VpcEndpoint
