### ISSUE TITLE
Managed IAM Policy `AWSCloudWatchLambdaInsightsExecutionRolePolicy` incorrect ARN

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws#2269]
### What happened?

According to this older issue https://github.com/pulumi/pulumi-aws/issues/1700 the `CloudWatchLambdaInsightsExecutionRolePolicy` was added as a constant in the AWS IAM managed policies list.  

However, the item is not within the typescript defined list and typing the role that was added in the referred Github issue (and related MR) gives me back an error that the role does not exist. My best guess is that the previous fix forgot a list variable or something.

### Steps to reproduce

```
new aws.iam.RolePolicyAttachment("lambda_role-lambda_insights-attachment", {
  role: signAndVerifyDeclarationsLambdaRole,
  policyArn: aws.iam.ManagedPolicies.AWSCloudWatchLambdaInsightsExecutionRolePolicy, // <-- this should return  "arn:aws:iam::aws:policy/AWSCloudWatchLambdaInsightsExecutionRolePolicy", but errors out instead.
});
```

### Expected Behavior

No error when you use the IAM managed policy `aws.iam.ManagedPolicies.AWSCloudWatchLambdaInsightsExecutionRolePolicy`.

### Actual Behavior

Error occurs.

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws         5.23.0
@pulumi/pulumi      3.49.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
The documentation on `aws.iam.ManagedPolicies` says `Use ManagedPolicy instead`. The plural version of the enum appears to be an early TypeScript only implementation whereas `ManagedPolicy` is supported between all languages. 

This code works correctly:

```typescript
aws.iam.ManagedPolicy.AWSCloudWatchLambdaInsightsExecutionRolePolicy
```

It appears we didn't surface this documenation as a hard deprecation to avoid causing existing users too much noise, though perhaps this would be worth revisiting in the future.

**Comment by Jimmy89** [comment]
@danielrbradley I tried your line (with the singular version). However, I still get the error:
```
operation CREATE failed with "NotFound": Policy arn:aws:iam::aws:policy/AWSCloudWatchLambdaInsightsExecutionRolePolicy does not exist or is not attachable. (Service: Iam, Status Code: 404, Request ID: 1a1ecdb6-6d63-4415-a588-6725dc37954e)
```

I looked the policy up in my AWS account and matched the naming closely (watching for typo's), but all seems to be fine on that side. Any clue why this error occurs?

**Comment by danielrbradley** [comment]
Ok, I've reopened so we can continue to track this.

**Comment by Jimmy89** [comment]
@danielrbradley I checked the source code (search: https://github.com/pulumi/pulumi-aws/search?q=AWSCloudWatchLambdaInsightsExecutionRolePolicy).

And indeed the auto-generated files contain the wrong policy name: https://github.com/pulumi/pulumi-aws/blob/682d5dac3a211aa2cdae472eefe9721462433a27/sdk/nodejs/types/enums/iam/index.ts#L21

`"arn:aws:iam::aws:policy/AWSCloudWatchLambdaInsightsExecutionRolePolicy",` --> must become `"arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy",`

**Comment by Jimmy89** [comment]
> And indeed the auto-generated files contains the wrong policy name:
> 
> https://github.com/pulumi/pulumi-aws/blob/682d5dac3a211aa2cdae472eefe9721462433a27/sdk/nodejs/types/enums/iam/index.ts#L21
> 
> `"arn:aws:iam::aws:policy/AWSCloudWatchLambdaInsightsExecutionRolePolicy",` --> must become `"arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy",`

@danielrbradley I'm bumping this topic as you might have missed my update (with the problem and solution) on the previous comment. If this issue needs to be addressed somewhere else (/other team), please let me know so this issue can be resolved.

**Comment by danielrbradley** [comment]
Ok, thanks for the detail @Jimmy89. It's in the backlog for further investigation 👍
