### ISSUE TITLE
Cannot call LaunchTemplate with UserData

### ISSUE THREAD

**Issue by brgirgis** [pulumi/pulumi-aws#2284]
I'm trying to create a simple launch template:

```C#
var launchTemplate = new Pulumi.Aws.Ec2.LaunchTemplate(
    "test",
    new() { ImageId = "ami-0f49ec39b0f6fff05", UserData = "echo hi", },
    new() { }
);
```
And I'm getting this error:

```
Diagnostics:
  pulumi:pulumi:Stack (Template-dev):
    error: update failed

  aws:ec2:LaunchTemplate (test):
    error: 1 error occurred:
        * error creating EC2 Launch Template: InvalidUserData.Malformed: Invalid BASE64 encoding of user data.
        status code: 400, request id: ab5003f8-da3c-424d-893d-948a56592b49
```

When I use an empty string, the call goes through just fine.

I'm using latest `pulumi`:

```
 pulumi version
v3.50.2
```

and latest `Pulumi.Aws`:

```xml

    <PackageReference Include="Pulumi" Version="3.*" />
    <PackageReference Include="Pulumi.Aws" Version="5.*" />
```

**Comment by brgirgis** [comment]
When I 64 encode it goes through fine:

```C#
    public Output<string> Encode64(Output<string> value)
    {
        return value.Apply(
            x => System.Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes(x))
        );
    }
```

This is not consistent with `Pulumi.Aws.Ec2.Instance` which does not require explicit encoding from the user side for the `UserData`.

**Comment by mikhailshilkov** [comment]
Hi @brgirgis 

> And I'm getting this error: ...
> When I 64 encode it goes through fine:

This is by design and is clearly [documented](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/launchtemplate/):

> The base64-encoded user data to provide when launching the instance.

and

> This is not consistent with Pulumi.Aws.Ec2.Instance which does not require explicit encoding from the user side for the UserData.

I agree. The `Instance` resource has a separate `UserDataBase64` instead. It's not consistent but this is defined by the upstream provider, likely for historic reasons, and there isn't much we can do.

I'm glad you found a working solution.
