### ISSUE TITLE
Dynamodb attribute types not allowed

### ISSUE THREAD

**Issue by badaljain** [pulumi/pulumi-aws#2290]
### What happened?

Hi,

I want to have a dynamodb attribute type of BOOL and I see that only [S, N, B] type of attribute types are allowed in in the table creation command. When I try to set type as `BOOL`, I get below error:

`error: aws:dynamodb/table:Table resource 'MerchantNomination-dev' has a problem: expected attribute.2.type to be one of [S N B], got BOOL. Examine values at 'Table.Attributes'.`

### Steps to reproduce

```
new aws.dynamodb.Table(name, {
            name: tableName,
            attributes: [
                {
                    name: "userId",
                    type: "S",
                },
                {
                    name: "isActive",
                    type: "BOOL"
                },
})
```

### Expected Behavior

The table should be created successfully with the dynamodb defined type

### Actual Behavior

error thrown while creating table

### Output of `pulumi about`

CLI          
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.24.0
kubernetes  3.23.0
nodejs      unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.12.1'

Current Stack: badaljain/pulumi-services-infra/dev

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:dev::pulumi-services-infra::pulumi:pulumi:Stack::pulumi-services-infra-dev
pkg:index:MobileBff                        urn:pulumi:dev::pulumi-services-infra::pkg:index:MobileBff::mobile-bff
pks:index:MerchantList                     urn:pulumi:dev::pulumi-services-infra::pks:index:MerchantList::MerchantList-dev
pks:index:UserPlaidAccessToken             urn:pulumi:dev::pulumi-services-infra::pks:index:UserPlaidAccessToken::UserPlaidAccessToken-dev
pkg:index:ContainerRegistry                urn:pulumi:dev::pulumi-services-infra::pkg:index:ContainerRegistry::mobile-bff
pulumi:providers:pulumi                    urn:pulumi:dev::pulumi-services-infra::pulumi:providers:pulumi::default
pks:index:DDBTables                        urn:pulumi:dev::pulumi-services-infra::pks:index:DDBTables::DDBTables
pulumi:providers:kubernetes                urn:pulumi:dev::pulumi-services-infra::pulumi:providers:kubernetes::render-yaml-k8s-provider
pks:index:MerchantNomination               urn:pulumi:dev::pulumi-services-infra::pks:index:MerchantNomination::MerchantNomination-dev
pulumi:providers:aws                       urn:pulumi:dev::pulumi-services-infra::pulumi:providers:aws::default_5_24_0
pulumi:pulumi:StackReference               urn:pulumi:dev::pulumi-services-infra::pulumi:pulumi:StackReference::badaljain/pulumi-core-infra/dev
aws:dynamodb/table:Table                   urn:pulumi:dev::pulumi-services-infra::aws:dynamodb/table:Table::MerchantList-dev
aws:ecr/repository:Repository              urn:pulumi:dev::pulumi-services-infra::pkg:index:ContainerRegistry$aws:ecr/repository:Repository::mobile-bff_repo
aws:dynamodb/table:Table                   urn:pulumi:dev::pulumi-services-infra::aws:dynamodb/table:Table::UserPlaidAccessToken-dev
pulumi:providers:kubernetes                urn:pulumi:dev::pulumi-services-infra::pulumi:providers:kubernetes::eksInfra-dev-provider
pkg:index:K8sDeployment                    urn:pulumi:dev::pulumi-services-infra::pkg:index:K8sDeployment::mobile-bff
pkg:index:k8sService                       urn:pulumi:dev::pulumi-services-infra::pkg:index:k8sService::mobile-bff-service
kubernetes:core/v1:Service                 urn:pulumi:dev::pulumi-services-infra::kubernetes:core/v1:Service::mobile-bff-service
kubernetes:apps/v1:Deployment              urn:pulumi:dev::pulumi-services-infra::kubernetes:apps/v1:Deployment::mobile-bff-deployment
kubernetes:core/v1:Namespace               urn:pulumi:dev::pulumi-services-infra::kubernetes:core/v1:Namespace::regular
aws:iam/role:Role                          urn:pulumi:dev::pulumi-services-infra::aws:iam/role:Role::regular-services-sa-role
kubernetes:core/v1:ServiceAccount          urn:pulumi:dev::pulumi-services-infra::kubernetes:core/v1:ServiceAccount::regular-services-sa
aws:iam/policyAttachment:PolicyAttachment  urn:pulumi:dev::pulumi-services-infra::aws:iam/role:Role$aws:iam/policyAttachment:PolicyAttachment::regular-services-sa-policy-attachment
aws:dynamodb/table:Table                   urn:pulumi:dev::pulumi-services-infra::aws:dynamodb/table:Table::MerchantNomination-dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/badaljain
User           badaljain
Organizations  badaljain

Dependencies:
NAME                 VERSION
@pulumi/pulumi       3.49.0
@types/node          14.18.35
@pulumi/aws          5.24.0
@pulumi/kubernetes   3.23.0
@pulumi/kubernetesx  0.1.6

Pulumi locates its logs in /var/folders/zh/1df5c24n0dbbmq3w5b2jg1rw0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @badaljain 

It looks like those three values are the only three allowed, see [this code in AWS SDK](https://github.com/aws/aws-sdk-go/blob/5ce492c7b41aa6fa66f08a247219dcab734f31c3/service/dynamodb/api.go#L26845-L26851) which is the source of truth for us.

Doesn't `B` work for you?
