### ISSUE TITLE
Warning: skip_get_ec2_platforms attribute has been deprecated

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#2292]
I am getting the following warning on many (all?) uses of this provider:

```
    warning: provider config warning: With the retirement of EC2-Classic the skip_get_ec2_platforms attribute has been deprecated and will be removed in a future version.
```

This was introduced earlier this month in: https://github.com/pulumi/pulumi-aws/blame/f36c8c5d0726702a5af0e5d8debd4051b99909bb/sdk/nodejs/provider.ts#L229.

I believe this is caused by the overriding of the upstream provider default for this value.  Given the deprecation, this overriding can likely be removed.

**Comment by Zaid-Ajaj** [comment]
> Given the deprecation, this overriding can likely be removed.

Do you mean that this property should no longer be applied a default value? i.e.
```js
resourceInputs["skipCredentialsValidation"] = 
  pulumi.output((args ? args.skipCredentialsValidation : undefined) ?? false).apply(JSON.stringify);
```
Becomes:
```js
resourceInputs["skipCredentialsValidation"] = 
  pulumi.output(args ? args.skipCredentialsValidation : undefined).apply(JSON.stringify);
```
Which can simplified:
```js
resourceInputs["skipCredentialsValidation"] = 
  pulumi.output(args && args.skipCredentialsValidation).apply(JSON.stringify);
```

**Comment by thomas11** [comment]
@Zaid-Ajaj I think it's more involved than that. We [define `skip_get_ec2_platforms` as a provider configuration](https://github.com/pulumi/pulumi-aws/blob/f36c8c5d0726702a5af0e5d8debd4051b99909bb/provider/resources.go#L443), and [document it](https://www.pulumi.com/registry/packages/aws/installation-configuration/#configuration-options).
