### ISSUE TITLE
Support new AWS Europe (Zurich) Region `eu-central-2`

### ISSUE THREAD

**Issue by SijmenHuizenga** [pulumi/pulumi-aws#2298]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

eu-central-2 region [was launched in November 2022](https://aws.amazon.com/fr/blogs/aws/a-new-aws-region-opens-in-switzerland/). At the moment trying to use this region in Typescript results in a type error:

> Type '"eu-central-2"' is not assignable to type 'Input<Region> | undefined'

Terraform provider has added support for the region: https://github.com/hashicorp/terraform-provider-aws/pull/27814

Workaround in Typescript: add `// @ts-ignore`

**Comment by thomas11** [comment]
Thanks for the bug report @SijmenHuizenga! This was an oversight and should be fixed in the next release.
