### ISSUE TITLE
removeAddons is missing from eks/cluster.go upstream fork in versions later than 5.21.1

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-aws#2306]
### What happened?

removeAddons seems to be missing from eks/cluster.go in upstream version since version 5.21.1, while the parameter is still available on the object it does nothing. 

There is a PR: https://github.com/pulumi/terraform-provider-aws/pull/73 with this added in. 

### Steps to reproduce

Create an eks cluster with addons to remove, they will not be removed. 

### Expected Behavior

That the addons are removed. 

### Actual Behavior

They are not removed.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
hi @rshade - the fix for this should be in today's release!
