### ISSUE TITLE
Misrepresented docs about lambda-retries

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-aws#2324]
File: [themes/default/content/registry/packages/aws/api-docs/lambda/function/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#lambda-retries)

Hello `lambda retries` section shows the wrong documentation and instead of the original text from terraform it shows the example for Lambda Logs configuration.
The original text is missing entirely.

Pulumi:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/7480694/213086609-4160ae8d-5cc2-4c9b-8f57-157a73b42626.png">
Terraform:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/7480694/213086655-9d9d581d-5f48-4556-b4f5-a2cf9ac12507.png">

**Comment by t0yv0** [comment]
I believe this got fixed now. Thanks for your patience.
