### ISSUE TITLE
Bucket property, acceleration_status doesn't return a value

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#2325]
### What happened?

Ran code shown below and saw that while an unset property such as `website_domain` returns a `None`, the `acceleration_status` property, also unset by the code, returned nothing.

I would have expected `accelaration_status` to have returned one of the two values it is supposed to have: `Enabled` or `Suspended`.
as per: https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucket/#acceleration_status_python

---- code -----
```
from pulumi_aws import s3

bucket = s3.Bucket('my-bucket')
bucket.acceleration_status.apply(lambda accel_status: print("bucket accel_status: ",accel_status))
bucket.website_domain.apply(lambda ws_domain: print("bucket website_domain: ", ws_domain))

gotten_bucket = bucket.id.apply(lambda bucketid: s3.Bucket.get("gotten_bucket", id=bucketid))
gotten_bucket.acceleration_status.apply(lambda accel_status: print("gotten_bucket accel_status: ",accel_status))
gotten_bucket.website_domain.apply(lambda ws_domain: print("gotten_bucket website_domain: ", ws_domain))
```

### Steps to reproduce

Run the code shared above

### Expected Behavior

The output for the `acceleration_status` should be one of the required values.

### Actual Behavior

The `acceleration_status` property is not set correctly.

### Output of `pulumi about`

CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.27.0
python  unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in python: executable='/Users/mitch/.pyenv/shims/python3' version='3.9.6
'

Current Stack: MitchGerdisch/bucket-get-properties/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::bucket-get-properties::pulumi:pulumi:Stack::bucket-get-properties-dev
pulumi:providers:aws  urn:pulumi:dev::bucket-get-properties::pulumi:providers:aws::default_5_27_0
aws:s3/bucket:Bucket  urn:pulumi:dev::bucket-get-properties::aws:s3/bucket:Bucket::my-bucket
aws:s3/bucket:Bucket  urn:pulumi:dev::bucket-get-properties::aws:s3/bucket:Bucket::gotten_bucket

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME        VERSION
pip         22.3.1
pulumi-aws  5.27.0
setuptools  66.0.0
wheel       0.38.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
The `s3.Bucket` resource is largely in maintenance mode. It has been removed upstream and we keep it for backwards compatibility. I don't think we are going to invest any time in improving it at this point, and we'll consider deprecating it in further provider versions.

We recommend you use `s3.BucketV2` for all new resources. Note that `accelaration_status` property is marked deprecated there too:

> @deprecated Use the aws_s3_bucket_accelerate_configuration resource instead
