### ISSUE TITLE
EFS MountTarget tagging

### ISSUE THREAD

**Issue by rodrigobrim** [pulumi/pulumi-aws#2331]
### What happened?

MountTarget package has no option to set tags. The network interfaces created are untagged too.

### Steps to reproduce

I can't find the tagging config on MountTargetArgs at the source code (go).

### Expected Behavior

Have a config to set tags in the Mount targets.

### Actual Behavior

No tagging config is available.

### Output of `pulumi about`

```
CLI          
Version      3.52.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.19.4 linux/amd64'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @rodrigobrim, it seems that AWS doesn't support tags for mount targets. Neither the [API docs](https://docs.aws.amazon.com/efs/latest/ug/API_CreateMountTarget.html) nor `aws efs create-mount-target help` show parameters for them. Correct me if I'm missing something.

**Comment by kpitzen** [comment]
Echoing what @thomas11 mentioned above, only EFS Access Points and File Systems support tagging in the AWS API at this time. Given this is an AWS restriction, and not an issue with Pulumi's implementation, I'm going to mark this issue as by-design. If EFS eventually supports tagging for Mount Targets, and this issue persists, please feel free to re-raise on this issue and we'll open it again for investigation. Thank you!
