### ISSUE TITLE
ECS Service Connect configuration should be a list

### ISSUE THREAD

**Issue by stevesloka** [pulumi/pulumi-aws#2336]
### What happened?

An ECS service can have multiple ports configured when managing it's service connect  setup. Today Pulumi allows me to specify a single port configuration, however, if I wanted to have more, I can't because it's not a list rather a single object. I'm not sure if there's an SDK issue or if there's a generation issue. 

Here's what it looks like in the ECS console where I am able to specify multiple services:

![image](https://user-images.githubusercontent.com/1048184/215677304-29f51334-44cb-4516-baa9-1bbbccd385c0.png)

### Expected Behavior

When defining a service connect config, allow me to configure multiple services: 
```
serviceConnectConfiguration: {
        enabled: true,
        namespace: namespace.arn,
        service: {
          clientAliases: [{
            port: 8081
          }],
          portName: "ratelimit"
        }
      }
```

### Steps to reproduce

Try to setup multiple services via code. 

### Output of `pulumi about`

:latest:

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @stevesloka! Unfortunately, this is a limitation in the upstream provider. While their docs say `service` is a list, the list is actually annotated with constraint `MaxItems: 1`, so we translate it into a scalar property in our SDK. I hope that helps. If this issue is blocking for you, we'll need to see whether we can find a workaround.

**Comment by stevesloka** [comment]
Hey @thomas11 thanks for the clarification. Do you know what upstream repo we could open an issue with to get this changed? I'm not blocked at the moment since my current needs are met with a single entry, but wanted to raise in case someone else came along and had an issue.
