### ISSUE TITLE
Import error in awsx packages during ecs-fargate tutorial

### ISSUE THREAD

**Issue by L0Z1K** [pulumi/pulumi-aws#2337]
File: [themes/default/content/registry/packages/aws/how-to-guides/ecs-fargate.md](https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/)

I just followed the tutorial but there is some import error in awsx packages.

Error message is "Property 'elasticloadbalancingv2' does not exist on type {}".

<img width="740" alt="image" src="https://user-images.githubusercontent.com/64528476/215797265-b105be29-a8ee-4916-a12d-b404ac53d4ee.png">

**Comment by mikhailshilkov** [comment]
I believe this has been fixed, the current guide has no reference to `elasticloadbalancingv2`
