### ISSUE TITLE
Support for custom events in AppMonitor 

### ISSUE THREAD

**Issue by lukasz-giants** [pulumi/pulumi-aws#2342]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In implementation of AppMonitor there is no option to pass value to enable or disable custom events for RUM monitoring. It would be nice if this property will be available for pulumi aws. 
![image](https://user-images.githubusercontent.com/83639499/216038735-078d2397-8b95-4da3-bb77-07acd501e805.png)

As I see terraform support it already https://github.com/hashicorp/terraform-provider-aws/blob/v4.51.0/CHANGELOG.md

**Comment by thomas11** [comment]
Hi @lukasz-giants, the upgrade of the Pulumi provider is in progress and will come out this week, adding custom events. Thanks for checking in!
