### ISSUE TITLE
Support ALB Attributes x-forwarded-for processing mode

### ISSUE THREAD

**Issue by tizzo** [pulumi/pulumi-aws#2346]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We need support for ALB attributers so that we can set x-forwarded-for header processing. [There is some corresponding terraform discussion](https://github.com/hashicorp/terraform-provider-aws/issues/22049#issuecomment-1181581025) but not yet any open issue. It would be really lovely to be able to configure this from pulumi and not have to hook in with boto to configure this in code.

### Affected area/feature

This would probably be a new resource for attributes - we're trying to set `routing.http.xff_header_processing.mode = (Append, Preserve, Remove)`.

**Comment by thomas11** [comment]
Hi @tizzo, apologies that these attributes are not available yet. For our bridged providers, we don't usually add resources before the underlying Terraform provider supports them. Often, using our native provider can be an alternative, but in the case of AWS it's limited by what's available in Cloud Control and ALB isn' there yet.

Let us know if this is a dealbreaker and we'll see if there are workarounds.

Note that sometimes the [command provider](https://www.pulumi.com/registry/packages/command/) can be helpful to wrap your custom code into the Pulumi resource model.
