### ISSUE TITLE
Attributes in applicationloadbalancing reference types from alb

### ISSUE THREAD

**Issue by david-latacora** [pulumi/pulumi-aws#2362]
### What happened?

I'm working on a project that involves schema traversal and I noticed something peculiar in the schema. There are two Identical data types declared for `ipAddressType`, one for the `alb` module and one for the `applicationloadbalancing` module. This is also the same  for `loadBalanderType` and both cases expected and consistent with documentation. What is unusual is, schema for "aws:applicationloadbalancing/loadBalancer:LoadBalancer" starts at line 413732 and then describes the property `ipAddressType` at line 413787 with the`$ref` as "#/types/aws:alb/ipAddressType:IpAddressType". It then describes the property `loadBalancerType` at line 413792 with the `$ref` as "#/types/aws:alb/loadBalanderType:LoadBalancerType". meanwhile "#/types/aws:applicationloadbalancing/ipAddressType:IpAddressType", and "#/types/aws:applicationloadbalancing/LoadBalancerType:LoadBalancerType" never get used at all in the schema. 

This does not cause any issues with conventional usage of Pulumi but can be troubling for people trying to use unsupported languages against the YAML runtime.

line 1033
```
   "aws:alb/IpAddressType:IpAddressType": {
            "type": "string",
            "enum": [
                {
                    "name": "Ipv4",
                    "value": "ipv4"
                },
                {
                    "name": "Dualstack",
                    "value": "dualstack"
                }
            ]
        },
```
line 9012
```
"aws:applicationloadbalancing/IpAddressType:IpAddressType": {
            "type": "string",
            "enum": [
                {
                    "name": "Ipv4",
                    "value": "ipv4"
                },
                {
                    "name": "Dualstack",
                    "value": "dualstack"
                }
            ]
        },
```

line 413787
```
"ipAddressType": {
                   "type": "string",
                   "$ref": "#/types/aws:alb/ipAddressType:IpAddressType",
                   "description": "The type of IP addresses used by the subnets for your load balancer. The possible values are `ipv4` and `dualstack`\n"
               },
```

line 2344
```        "aws:alb/LoadBalancerType:LoadBalancerType": {
            "type": "string",
            "enum": [
                {
                    "name": "Application",
                    "value": "application"
                },
                {
                    "name": "Network",
                    "value": "network"
                }
            ]
        },
```

line 10323
```        "aws:applicationloadbalancing/LoadBalancerType:LoadBalancerType": {
            "type": "string",
            "enum": [
                {
                    "name": "Application",
                    "value": "application"
                },
                {
                    "name": "Network",
                    "value": "network"
                }
            ]
        },
```

line 413792
```      "loadBalancerType": {
                    "type": "string",
                    "$ref": "#/types/aws:alb/loadBalancerType:LoadBalancerType",
                    "description": "The type of load balancer to create. Possible values are `application`, `gateway`, or `network`. The default value is `application`.\n"
                },
```

### Expected Behavior

The `ipAddressType` property under "aws:applicationloadbalancing/loadBalancer:LoadBalancer" should reference the ipAddressType type from `applicationloadbalancing`, not `alb`

example:
```
"ipAddressType": {
                   "type": "string",
                   "$ref": "#/types/aws:applicationloadbalancing/ipAddressType:IpAddressType",
                   "description": "The type of IP addresses used by the subnets for your load balancer. The possible values are `ipv4` and `dualstack`\n"
               },
```

The `loadBalancerType` property under "aws:applicationloadbalancing/loadBalancer:LoadBalancer" should reference the loadBalanderType type from `applicationloadbalancing`, not `alb`

example
```  "loadBalancerType": {
                    "type": "string",
                    "$ref": "#/types/aws:alb/loadBalancerType:LoadBalancerType",
                    "description": "The type of load balancer to create. Possible values are `application`, `gateway`, or `network`. The default value is `application`.\n"
                },
```

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Additional context

I filed an issue with schema last week that is a little different but am linking here for visibility.
[https://github.com/pulumi/pulumi-aws/issues/2358](https://github.com/pulumi/pulumi-aws/issues/2358)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
Thank you for digging into this; whatever you're doing it must be pretty interesting :-)
Paging @mikhailshilkov: more schema inconsistencies!

**Comment by david-latacora** [comment]
Thanks! I am indeed working on something interesting. I will let you know if/when i open source it.

**Comment by mikhailshilkov** [comment]
The `applicationloadbalancing` module has been deprecated and removed in V6 of the provider, so I believe I can close this issue as done.
