### ISSUE TITLE
Aws Provider missing new AWS service: Resource Explorer

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-aws#2368]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It is already in the [Terraform Provider version currently in use](https://registry.terraform.io/providers/hashicorp/aws/4.52.0/docs/resources/resourceexplorer2_view), but it's not been made available. 

### Affected area/feature

AWS Pulumi Provider

**Comment by lukehoban** [comment]
It appears none of the new resources in v4.51.0 or v4.52.0 of upstream are available currently - but resources from v4.50.0 are.  So it appears the latests updates of upstream haven't been picked up in the release.

**Comment by mikhailshilkov** [comment]
This has been fixed, the resources are now available: https://www.pulumi.com/registry/packages/aws/api-docs/resourceexplorer/

I suspect this was related to us lacking TFPF integration.
