### ISSUE TITLE
Add node affinity for aws eks addons

### ISSUE THREAD

**Issue by snichifor** [pulumi/pulumi-aws#2369]
Hello. It is possible to add in the near future node affinity feature for aws eks addons to select the node which will have the add-ons added. Thank you

**Comment by lukehoban** [comment]
I am not aware of an EKS Addon feature for controlling which Nodes they are installed to -  do you have a link to the feature in the AWS EKS documentation?

**Comment by lukehoban** [comment]
I believe you may be able to use https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/#state_configurationvalues_go to provide configuration for the AddOn.

**Comment by lukehoban** [comment]
Closing for now - but if that doesn't address your needs and you have a link to what AWS EKS API you need access to from this provider - let us know and we'll reopen!
