### ISSUE TITLE
tfgen does not recognise all new resources

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-aws#2372]
In the playbook for updating a Terraform-bridged provider (in a private repo; the relevant bits are reproduced below), step 7 says:

> Check the upstream provider CHANGELOG or release notes. For each new resource, add the appropriate mapping in resources.go. Add to the bottom of the relevant section by convention.

Then step 9 says:

> make tfgen <-- check the output for unmapped resources and data sources and add to the provider map (normally provider/resources.go)

When I followed these steps for pulumi-aws, updating to the upstream v4.54.0 (https://github.com/pulumi/terraform-provider-aws/tree/patched-v4.54.0), I added new resources and data sources mentioned in the changelog (https://github.com/pulumi/terraform-provider-aws/blob/patched-v4.54.0/CHANGELOG.md):

>  - New Data Source: aws_auditmanager_framework (https://github.com/hashicorp/terraform-provider-aws/issues/28989)
>  - New resource: aws_auditmanager_assessment_delegation (https://github.com/hashicorp/terraform-provider-aws/issues/29099)
>  - New Resource: aws_auditmanager_framework_share (https://github.com/hashicorp/terraform-provider-aws/issues/29049)
>  - New Resource: aws_auditmanager_organization_admin_account_registration

NB These are mentioned under v4.53.0; the prior update branch was v4.52.0).

When I subsequently ran `make tfgen`, it complained that the resources shouldn't be in provider/resources.go:

```
error: failed to gather package metadata: problem gathering resources: 3 errors occurred:
	* Pulumi token "aws:auditmanager/assessmentDelegation:AssessmentDelegation" is mapped to TF provider resource "aws_auditmanager_assessment_delegation", but no such resource found. The mapping will be ignored in the generated provider
	* Pulumi token "aws:auditmanager/frameworkShare:FrameworkShare" is mapped to TF provider resource "aws_auditmanager_framework_share", but no such resource found. The mapping will be ignored in the generated provider
	* Pulumi token "aws:auditmanager/organizationAdminAccountRegistration:OrganizationAdminAccountRegistration" is mapped to TF provider resource "aws_auditmanager_organization_admin_account_registration", but no such resource found. The mapping will be ignored in the generated provider
```

(it was not just ignored; it stopped the build in its tracks)

I removed the resource definitions and reran `make tfgen` and it was happy.

Notably, the new data source added to the mapping was not mentioned as a problem. When I removed its definition from resources.go and reran `make tfgen`, it still completed -- it doesn't care whether it's there or not, apparently.

**Comment by mikhailshilkov** [comment]
I'm pretty sure this has been fixed with out tooling advances, closing as done
