### ISSUE TITLE
IPv6 IPAM-managed address blocks fail on second apply

### ISSUE THREAD

**Issue by kwohlfahrt** [pulumi/pulumi-aws#2378]
### What happened?

I deployed a VPC with the following parameters (where `pools.ipv6.id` and `pools.ipv4.id`) are exernally created AWS IPAM pools:
```
const vpc = new aws.ec2.Vpc(
  "vpn",
  {
    ipv4IpamPoolId: pools.ipv4.id,
    ipv6IpamPoolId: pools.ipv6.id,
    ipv4NetmaskLength: 20,
    ipv6NetmaskLength: 56,
  },
  { provider }
);
```

Checking this VPC in the AWS console, the IPv6 pool was listed as `IPAM Managed - Associated`.

I then ran `pulumi up` a second time, without making any changes. This showed the following changes during preview:

```
    ~ aws:ec2/vpc:Vpc: (update)
        [id=vpc-06b282e4c36d5e329]
        [urn=urn:pulumi:kai::vpn::aws:ec2/vpc:Vpc::vpn]
        [provider=urn:pulumi:kai::vpn::pulumi:providers:aws::vpn::b388bb36-9b01-435d-b432-77d5ff419602]
      ~ ipv6IpamPoolId   : "IPAM Managed" => "ipam-pool-029ddd08697068a8e"
      ~ ipv6NetmaskLength: 0 => 56
```

The update failed with the error below:
```
  aws:ec2:Vpc (vpn):
    error: 1 error occurred:
    	* updating urn:pulumi:kai::vpn::aws:ec2/vpc:Vpc::vpn: 1 error occurred:
    	* updating EC2 VPC (vpc-06b282e4c36d5e329): associating IPv6 CIDR block: InvalidParameterCombination: The parameter 'ipv6NetmaskLength' may not be used in combination with 'ipv6CidrBlock'.
    	status code: 400, request id: 9acb086f-09e8-4700-9f88-1a0058d1508e
```

After this failure, in the AWS console, the IPv6 pool was listed as `IPAM Managed - Disassociated`

### Expected Behavior

I expected Pulumi to not make any changes on the second update.

### Steps to reproduce

The content above ("what happened") be sufficient to reproduce:

1. Create an IPv6 IPAM pool (can be done manually in the console)
2. Create a VPC in Pulumi using this IPAM pool for it's IPv6 CIDR
3. `pulumi up` again after creating the VPC

### Output of `pulumi about`

```
CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.30.0
docker  3.6.1
nodejs  unknown
random  4.11.2

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/Users/kai/.nix-profile/bin/node' version='v18.14.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/kwohlfahrt
User           kwohlfahrt
Organizations  kwohlfahrt, CHARM-Tx

Dependencies:
NAME                  VERSION
@pulumi/pulumi        3.55.0
ip-num                1.5.0
typescript            4.9.5
zod                   3.20.6
@charm-tx/pulumi-aws  0.3.0
@pulumi/aws           5.30.0
@pulumi/random        4.11.2
@types/jest           29.4.0
@types/node           16.18.12
ts-jest               29.0.5
ts-node               10.9.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kwohlfahrt** [comment]
A tenuously related additional bug - I'm seeing a similar diff with subnet resources created in an IPv6 VPC:

```
    ~ aws:ec2/subnet:Subnet: (update)
        [id=subnet-0ffff15057dd016c0]
        [urn=urn:pulumi:kai::vpn::aws:ec2/subnet:Subnet::vpn]
        [provider=urn:pulumi:kai::vpn::pulumi:providers:aws::vpn::b388bb36-9b01-435d-b432-77d5ff419602]
      ~ ipv6CidrBlock: "2a05:d024:0:6200::/64" => "2a05:d024:0:6200:0:0:0:0/64"
```

The CIDR blocks are two identical ways of writing the same address range.

**Comment by thomas11** [comment]
Hi @kwohlfahrt, sorry for the delay in responding to this. I haven't been able to reproduce this error mode yet because I get 

> InvalidIpamPoolId.NotFound: The ipam-pool IDs ..., ... do not exist

even though I see them in the AWS console.

Can you share more detail on your pools and their configuration? Thanks!

**Comment by kwohlfahrt** [comment]
Hm, I don't think there's much unusual about the set-up. There's a global IPAM resource, and the IPv6 pools (which are the interesting ones for this bug) are provisioned in the public scope, like this:

```
const ipam = new aws.ec2.VpcIpam(
  "ipam",
  { operatingRegions: regions.map((regionName) => ({ regionName })) },
  { provider }
);

regions.forEach(region => new aws.ec2.VpcIpamPool(
  name,
  {
    ipamScopeId: ipam.publicDefaultScopeId,
    addressFamily: "ipv6",
    locale: region,
    publicIpSource: "amazon",
    awsService: "ec2"
  },
  { provider })
);
```

I don't _think_ it matters what region the pools are provisioned from, as long as the `locale` matches the region you are creating your VPC in.

**Comment by thomas11** [comment]
Ok, I'll need some help from more AWS-savvy teammates then. Will put this issue on the queue. Thanks for your understanding!

**Comment by kwohlfahrt** [comment]
No worries - unfortunately I can't test a complete minimal example, because the IPAM pools are an org-wide resource.

**Comment by flostadler** [comment]
Hey @kwohlfahrt,
I had a look at this, but couldn't reproduce the issue with both the pulumi aws version you were using (v5.30.0) as well as the latest version (v6.52.0). Maybe this was a cloud API bug that was since fixed. Can you confirm whether you're still running into this issue?

This is the program I used to repro:
```ts
import * as aws from "@pulumi/aws";

// Replace with your scopes
const publicScopeId = "ipam-scope-abcd"
const privateScopeId = "ipam-scope-abcde"

const ipamPool = new aws.ec2.VpcIpamPool(
    "retriage",
    {
        ipamScopeId: privateScopeId,
        addressFamily: "ipv4",
        locale: "us-west-2",
    },
);
const ipv6Pool = new aws.ec2.VpcIpamPool(
    "retriage-v6",
    {
        ipamScopeId: publicScopeId,
        addressFamily: "ipv6",
        locale: "us-west-2",
        publicIpSource: "amazon",
        awsService: "ec2",
        publiclyAdvertisable: false,
    },
);

const cidr = new aws.ec2.VpcIpamPoolCidr("retriage", {
    ipamPoolId: ipamPool.id,
    cidr: "172.20.0.0/16",
})

const v6Cidr = new aws.ec2.VpcIpamPoolCidr("retriagev6", {
    ipamPoolId: ipv6Pool.id,
    netmaskLength: 52,
});

const vpc = new aws.ec2.Vpc(
    "retriage",
    {
        ipv4IpamPoolId: ipamPool.id,
        ipv6IpamPoolId: ipv6Pool.id,
        ipv4NetmaskLength: 20,
        ipv6NetmaskLength: 56,
    },
    {dependsOn: [cidr, v6Cidr]},
);

```
