### ISSUE TITLE
InvalidNetworkInterface.InUse while recreating a instance

### ISSUE THREAD

**Issue by georgettica** [pulumi/pulumi-aws#2394]
### What happened?

I changed a KeyName in in the instance, and tried to `pulumi up` but I got an 
```
    	* creating EC2 Instance: InvalidNetworkInterface.InUse: Interface: [eni-XXX] in use.
```

### Expected Behavior

that the replacement would be successful

### Steps to reproduce

use a `pulumi-go` project
```go
networkInterface, err := ec2.NewNetworkInterface(ctx, "aa", nil)
instance, err := ec2.NewInstance(ctx, prefix+"-ec2", &ec2.InstanceArgs{
    NetworkInterfaces: ec2.InstanceNetworkInterfaceArray{
        &ec2.InstanceNetworkInterfaceArgs{
            NetworkInterfaceId: networkInterface.ID(),
            DeviceIndex:        pulumi.Int(0),
        },
   },
   ...
})
```

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME  VERSION
aws   5.30.0
go    unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in go: executable='XXX' version='go version go1.20.1 darwin/arm64'

Backend        
Name           XXX
URL            file://
User           XXX
Organizations  

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v5  5.30.0
github.com/pulumi/pulumi/sdk/v3      3.55.0

Pulumi locates its logs in XXX by default
warning: Failed to get information about the current stack: No current stack

### Additional context

when I searched online I found https://github.com/hashicorp/terraform-provider-aws/issues/27513

as noted, I am using a local backend, not that this should be an issue

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @georgettica , sorry you're running into trouble. I was able to reproduce this behavior, and it stems from Pulumi creating new resources before deleting old ones. This doesn't work here as the network interface is still attached to the old instance. The solution is to use `deleteBeforeReplace` as [documented here](https://www.pulumi.com/docs/intro/concepts/resources/options/deletebeforereplace/). I hope that helps.
