### ISSUE TITLE
typo. Should be BEANSTALK. L is missing

### ISSUE THREAD

**Issue by znotdead** [pulumi/pulumi-aws#2396]
https://github.com/pulumi/pulumi-aws/blob/ec4663b76f2a04fe62af706d841d0b679bb3fda5/sdk/python/pulumi_aws/iam/_enums.py#L215

**Comment by mikhailshilkov** [comment]
There is a correctly named value on the next line:
https://github.com/pulumi/pulumi-aws/blob/ec4663b76f2a04fe62af706d841d0b679bb3fda5/sdk/python/pulumi_aws/iam/_enums.py#L216

We kept the old value to ensure we don't break people. We should probably remove it at the next major version of the provider.

**Comment by znotdead** [comment]
Great! already in master. Thanks!
