### ISSUE TITLE
Previewing Deployment of S3 Bucket Shows Change In `serverSideEncryptionConfiguration`

### ISSUE THREAD

**Issue by adrians5j** [pulumi/pulumi-aws#2403]
### What happened?

When previewing a deployment of an S3 bucket, we get this change in the report:

![image](https://user-images.githubusercontent.com/5121148/223432955-744bbe51-607a-4f11-8f99-e68296e6aa2d.png)

I was OK, let's redeploy, so that this gets applied.

But even after I redeployed, the change is still being reported when doing a deployment preview.

### Expected Behavior

After deployment, no changes should be shown when doing a deployment preview. On the other hand, not sure if this needs to be reported at all. Maybe this should be internally handled. 🤔 

### Steps to reproduce

Try deploying a S3 bucket, and then do a preview deployment.

### Output of `pulumi about`

```CLI          
Version      3.41.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.3
Arch     arm64

This project is written in nodejs: executable='/private/var/folders/j3/33xmnlyn6db75qqn6n06j6nh0000gn/T/xfs-2f7785c0/node' version='v16.19.0'

Current Stack: dev

TYPE                                                      URN
pulumi:pulumi:Stack                                       urn:pulumi:dev::admin::pulumi:pulumi:Stack::admin-dev
pulumi:providers:aws                                      urn:pulumi:dev::admin::pulumi:providers:aws::default_5_16_2
aws:cloudfront/originAccessIdentity:OriginAccessIdentity  urn:pulumi:dev::admin::aws:cloudfront/originAccessIdentity:OriginAccessIdentity::wby-admin-app-origin-identity
aws:s3/bucket:Bucket                                      urn:pulumi:dev::admin::aws:s3/bucket:Bucket::wby-admin-app
aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock    urn:pulumi:dev::admin::aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock::wby-admin-app-bucket-block-access
aws:s3/bucketPolicy:BucketPolicy                          urn:pulumi:dev::admin::aws:s3/bucketPolicy:BucketPolicy::wby-admin-app-bucket-policy
aws:cloudfront/distribution:Distribution                  urn:pulumi:dev::admin::aws:cloudfront/distribution:Distribution::wby-admin-app-cdn
aws:dynamodb/tableItem:TableItem                          urn:pulumi:dev::admin::aws:dynamodb/tableItem:TableItem::wby-adminSettings


Found no pending operations associated with dev

Backend        
Name           Adrians-MacBook-Pro-2.local
URL            file:///Users/adrian/dev/webiny-js/.pulumi/apps/admin
User           adrian
Organizations  

Pulumi locates its logs in /var/folders/j3/33xmnlyn6db75qqn6n06j6nh0000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: Could not find either /Users/adrian/dev/webiny-js/.webiny/workspaces/apps/admin/pulumi/yarn.lock or /Users/adrian/dev/webiny-js/.webiny/workspaces/apps/admin/pulumi/package-lock.json
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jenslauterbach** [comment]
This is related to a change AWS "released" on January 5th. All new buckets created after that date will automatically be encrypted.

Source: https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-encryption-faq.html

If I had to guess, then I'd say that the AWS provider is not yet aware of this new default and therefore always reports a `diff`. The Pulumi state does not reflect this default, therefore causing the `diff`.

**Comment by lukehoban** [comment]
I expect we'll need to pull https://github.com/hashicorp/terraform-provider-aws/pull/28702 into our fork to address this.

**Comment by danielrbradley** [comment]
This should now be fixed in v5.31.0 which should be released in the next couple of hours.

**Comment by adrians5j** [comment]
Thank you for this, so far so good! :)

**Comment by kianmtx** [comment]
This is problematic when adding your own bucket `aws.s3.BucketServerSideEncryptionConfigurationV2` (Eg KMS specific encryption) directly will be passively removed by the diff on the bucket object here.
