### ISSUE TITLE
[docs] awsx.elasticloadbalancerv2.NetworkListener doesn't exist

### ISSUE THREAD

**Issue by bartekkustra** [pulumi/pulumi-aws#2424]
File: [themes/default/content/registry/packages/aws/how-to-guides/ecs-fargate.md](https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/)

**Comment by mikhailshilkov** [comment]
Fixed in https://github.com/pulumi/registry/commit/39ee28b3f0090ff695212974ace625446288b1b1
