### ISSUE TITLE
Change string to number

### ISSUE THREAD

**Issue by simqsticker** [pulumi/pulumi-aws#2428]
```
    buildTimeout: "5",
    queuedTimeout: "5",
```

Seems to be a typo and should be:

```
    buildTimeout: 5,
    queuedTimeout: 5,
```

File: [themes/default/content/docs/reference/pkg/aws/codebuild/project/_index.md](https://www.pulumi.com/docs/reference/pkg/aws/codebuild/project/)

**Comment by lukehoban** [comment]
This appears to be correct now.
