### ISSUE TITLE
Root module Go examples don't include the module for args

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-aws#2430]
https://www.pulumi.com/registry/packages/aws/api-docs/getipranges/ and https://www.pulumi.com/registry/packages/aws/api-docs/getavailabilityzones/ are examples of this where Go example references `GetAvailabilityZonesArgs` instead of `aws.GetAvailabilityZonesArgs`

**Comment by mikhailshilkov** [comment]
This has been fixed
<img width="701" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/7dec6eca-f5cf-48af-95ac-57196d890ac0">
<img width="611" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/32fd8be5-dffa-4f68-b158-70ccad3b17a7">
