### ISSUE TITLE
AWS EKS control plane logging example incorrectly shows use of custom log group

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-aws#2433]
File: [docs/reference/pkg/nodejs/pulumi/aws/eks/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/eks/)

The "Enabling Control Plane Logging" example in this file is incorrect, as AWS manages the log group and logs for the control plane. User's cannot provide their own `exampleLogGroup` as the example demonstrates per the [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html), and even in how the example is written, the group is only being `dependedOn` -- it's not actually being used by the cluster.

The `exampleLogGroup` should be removed all-together.

Note: not sure if these docs are being auto-generated or were manually constructed.

**Comment by mikhailshilkov** [comment]
It sounds like this is by design:

> The below configuration uses `dependsOn` to prevent ordering issues with EKS automatically creating the log group first and a variable for naming consistency. Other ordering and naming methodologies may be more appropriate for your environment.
