### ISSUE TITLE
Python "Usage with Lambda" example raises Exception

### ISSUE THREAD

**Issue by smcoll** [pulumi/pulumi-aws#2434]
File: [docs/reference/pkg/aws/lb/targetgroupattachment.md](https://www.pulumi.com/docs/reference/pkg/aws/lb/targetgroupattachment/)

The Python code for [**Usage with Lambda**](https://www.pulumi.com/docs/reference/pkg/aws/lb/targetgroupattachment/#usage-with-lambda) results in an exception:

> Exception: 'depends_on' was passed a value that was not a Resource.

i believe changing the `depends_on` value resolves it:

```python
# ...
test_target_group_attachment = aws.lb.TargetGroupAttachment("testTargetGroupAttachment",
    target_group_arn=test_target_group.arn,
    target_id=test_function.arn,
    opts=ResourceOptions(depends_on=[with_lb]))
```

**Comment by lukehoban** [comment]
This example now includes the correct code:

```
test_target_group_attachment = aws.lb.TargetGroupAttachment("testTargetGroupAttachment",
    target_group_arn=test_target_group.arn,
    target_id=test_function.arn,
    opts=pulumi.ResourceOptions(depends_on=[with_lb]))
```

Note that https://github.com/pulumi/pulumi-terraform-bridge/issues/926 is affecting this page now though, which appears to be a regression.  But tracking that in that other issue.

Will close this one out for now.
