### ISSUE TITLE
sslSupportMethod not documented

### ISSUE THREAD

**Issue by mowat27** [pulumi/pulumi-aws#2435]
File: [docs/reference/pkg/aws/cloudfront/distribution.md](https://www.pulumi.com/docs/reference/pkg/aws/cloudfront/distribution/)

The sslSupportMethod on viewer_certificate is not documented.

A worked example would be really helpful here.  Cloudfront is a complex beast and probably not something most people need to setup or change very often and I found I had to dig around quite a bit online.

My use case is to make a static s3 website with HTTPS support.

**Comment by iwahbe** [comment]
Thanks for filing this. It's now documented!
<img width="725" alt="Screenshot 2023-07-18 at 12 51 44 PM" src="https://github.com/pulumi/pulumi-aws/assets/22222529/a0b81218-20f4-4341-93a4-378575fb16b6">
