### ISSUE TITLE
Docs tend not to describe as much as the provider(AWS classic) for dynamo

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-aws#2436]
### Problem description

- Some areas of the docs tend to not describe as much as the provider(AWS), so I jump to that area of documentation that might help me get more info. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html for example for this. I like cloud formation, it has nearly everything for their services, properties, valid inputs, required, etc. perhaps this is intentional and Pulumi can't cover every single detail. and in the Pulumi code, I do a Go To Definition/Type Definition to get more details on the structure of Inputs sometimes.

Using AWS Classic Provider:
```
import * as aws from '@pulumi/aws';
```

**Comment by mikhailshilkov** [comment]
I'm not sure what exactly this issue is tracking. @tusharshahrs can you add a link to a problematic Pulumi docs page and the piece(s) that are missing from it? Thank you.
