### ISSUE TITLE
Mistake in the docs

### ISSUE THREAD

**Issue by MalulDekel** [pulumi/pulumi-aws#2437]
File: [themes/default/content/registry/packages/aws/api-docs/ec2/getami/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/getami/)

The aws.ec2.get_ami states that owner is optional argument but he is required as the following error occurred to me:
`invoke of aws:ec2/getAmi:getAmi failed: Missing required argument: The argument "owners" is required, but no definition was found.`

**Comment by mikhailshilkov** [comment]
I believe this has been fixed upstream in https://github.com/hashicorp/terraform-provider-aws/commit/99c347bfecabcaf80e0cb1937f68ded2354c34d3#diff-a51462b771642362edab698a42f164d1e010d618dc168a313fa74044bbfbe621 and the parameter is not required anymore.
