### ISSUE TITLE
MSK Connector can't be replaced by Pulumi

### ISSUE THREAD

**Issue by sicarul** [pulumi/pulumi-aws#2441]
### What happened?

When Pulumi tries to delete an MSK Connector (new aws.mskconnect.Connector), the following error appears:

aws:mskconnect:Connector (<connector_name>):
    error: 1 error occurred:
    	* updating urn:pulumi:<masked>::<masked>::aws:mskconnect/connector:Connector::cdctest-kafka-connect: 1 error occurred:
    	* error updating MSK Connect Connector (arn:aws:kafkaconnect:us-west-2:<masked>:connector/<masked>/<masked>): BadRequestException: Missing required request parameters: [currentVersion]

Which means to change anything i have to manually go into the console, delete the resource, and try again.

### Expected Behavior

I'd expect Pulumi to delete the resource

### Steps to reproduce

Reproduction is a bit annoying, you'll need to create an MSK cluster (Which takes around 30 minutes) and add a connector to it.

### Output of `pulumi about`

CLI
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME            VERSION
aws             5.33.0
awsx            1.0.2
confluentcloud  1.11.0
docker          3.6.1
nodejs          unknown

Host
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/pabloseibelt/.nvm/versions/node/v18.6.0/bin/node' version='v18.6.0'

Current Stack: v-pablo-pulumi-corp/pablo_dms_test/pablo_dms_test_cdc

TYPE                                                    URN
<Hidden>

Found no pending operations associated with pablo_dms_test_cdc

Backend
Name           pulumi.com
URL            https://app.pulumi.com/v-pablo-pulumi-corp
User           v-pablo-pulumi-corp
Organizations  v-pablo-pulumi-corp, pulumi

Dependencies:
NAME                    VERSION
@types/node             16.18.14
@pulumi/aws             5.33.0
@pulumi/awsx            1.0.2
@pulumi/confluentcloud  1.11.0
@pulumi/pulumi          3.60.0

Pulumi locates its logs in /var/folders/0g/n3hrlpn56jb72cnjwggcy3kh0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@sicarul Would you also be able to provide a code sample so we can see how the resource is defined? Thanks!

**Comment by mikhailshilkov** [comment]
@sicarul Do you have a repro snippet for this issue?

**Comment by sicarul** [comment]
Closing because i don't have a repro snippet handy and i've moved away from using MSK.
