### ISSUE TITLE
Circular dependency between `lambda.Function` and `cognito.UserPool`

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#2444]
When creating a `cognito.UserPool` and `lambda._Function` it can be difficult because each needs to know about the other:

```
user_pool = cognito.UserPool("example_with_trigger",
    lambda_config={
        "preTokenGeneration": function.qualified_arn, # needs to exist
    },
    name="test"
)

function = lambda_.Function("users",
    ...
    environment={
        "variables": {
            "USERPOOL_ID": user_pool.id, # needs to exist!
        },
    },
    name="user-api"
)
```

If we had a `aws.lambda.FunctionEnvironment` or a `aws.cognito.UserPoolLambdaConfig` we could fix this, but unfortunately, it's not in the provider

**Comment by jaxxstorm** [comment]
Related https://github.com/hashicorp/terraform-provider-aws/issues/9864

**Comment by mikhailshilkov** [comment]
This has to be done upstream, so I don't see a ton of value of tracking it in Pulumi provider. I'll go ahead and close it for now, let me know if you don't agree.
