### ISSUE TITLE
Vague error message for invalid or unknown key when adding invalid aws config variables

### ISSUE THREAD

**Issue by maknotavailable** [pulumi/pulumi-aws#2446]
### What happened?

Having `aws:XXX` variables in your pulumi configurations can result in an undescriptive error:

```
Diagnostics:
  aws:s3:BucketV2 (xxx):
    error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
```

### Expected Behavior

The error message should state which key is causing the issue.

### Steps to reproduce

1. Create a pulumi project using python
2. Add any, or all, of the following to your `Pulumi.<env>.yaml` config:
```
config:
  aws:account_id: XXX
  aws:access_key_id: XXX
  aws:secret_access_key: XXX
```
3. Create a S3 Bucket (or any other AWS resource), for example in `main.py`:
```
import pulumi_aws as aws

bucket = aws.s3.Bucket("bucket",
    acl="private",
    tags={
        "Environment": "Dev",
        "Name": "My bucket",
    })
```
3. Run `pulumi preview` or `pulumi up`, you'll see this error:
```
Diagnostics:
  aws:s3:BucketV2 (bucket):
    error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
        * Invalid or unknown key
        * Invalid or unknown key
```

### Output of `pulumi about`

CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.33.0
aws-native  0.49.0
datadog     4.16.0
python      unknown
random      4.12.1
snowflake   0.18.1

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in python: executable='/Users/xxx/Library/Caches/pypoetry/virtualenvs/xxx-x-infra-O3l4sU9N-py3.11/bin/python3' version='3.11.1
'

Current Stack: seenons/cloud-monitoring/prod

TYPE                                 URN
pulumi:pulumi:Stack                  urn:pulumi:prod::cloud-monitoring::pulumi:pulumi:Stack::cloud-monitoring-prod
pulumi:providers:datadog             urn:pulumi:prod::cloud-monitoring::pulumi:providers:datadog::default_4_16_0
datadog:aws/integration:Integration  urn:pulumi:prod::cloud-monitoring::datadog:aws/integration:Integration::datadog-integration

Found no pending operations associated with seenons/prod

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xxx
User           xxx
Organizations  xxx, xxx

Dependencies:
NAME               VERSION
autopep8           2.0.2
black              22.12.0
flake8             6.0.0
ipython            8.12.0
pip                22.3.1
pulumi-aws         5.33.0
pulumi-aws-native  0.49.0
pulumi-datadog     4.16.0
pulumi-random      4.12.1
pulumi-snowflake   0.18.1
setuptools         65.6.3
toml               0.10.2
wheel              0.38.4
yapf               0.32.0

Note: annonymzed some parts using `xxx`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
This should be closed in a recent provider like pulumi-aws v6.31.0 ; please reopen if it is still a problem.
