### ISSUE TITLE
explicit provider secrets are shown as plaintext in CLI output

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-aws#2447]
### What happened?

Explicit providers sourcing plaintext values from the environment for accessKey, secretKey, token are showing up in the CLI output (pre and up) as plaintext.

### Expected Behavior

Regardless if plaintext values are provided to provider or not, they should be marked as secrets (outputs masked).

### Steps to reproduce

Create an aws typescript project with the following:

```
const awsProvider = new aws.Provider("aws-provider", {
        accessKey: process.env["AWS_ACCESS_KEY_ID"],
        secretKey: process.env["AWS_SECRET_ACCESS_KEY"],
        token: process.env["AWS_SESSION_TOKEN"],
        region: <aws.Region>process.env["AWS_REGION"],
    });
```
set the applicable environment variables with plaintext values. Those plaintext values will show up in the CLI output.

### Output of `pulumi about`

@pulumi/aws@5.13.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Related to https://github.com/pulumi/pulumi/issues/10319.

**Comment by phillipedwards** [comment]
My understanding is if a provider input is marked as `Sensitive` in the upstream provider, inputs should automatically be marked as Secrets, but it seems that is not true? @lukehoban

**Comment by rquitales** [comment]
@phillipedwards That was also my understanding. I'll take a deeper look into this.

**Comment by t0yv0** [comment]
Looks like we still don't have a good fix here, escalating so our team takes a look. Apologies for the wait.

**Comment by t0yv0** [comment]
@phillipedwards do you have a reference for "showing up in the CLI output (pre and up) as plaintext." are you perchance running Pulumi with some parameters? on a very simple `pulumi up` I'm currently not seeing these values exposed on stdout/stderr on the latest version of the provider.

However! I do see the values exposed as plaintext in the statefile which is very bad.

I seem to be able to easily fix that behavior by configuring  the following config options as secret in resources.go:

```
			"access_key": {
				Secret: tfbridge.True(),
			},
			"secret_key": {
				Secret: tfbridge.True(),
			},
			"token": {
				Secret: tfbridge.True(),
			},
```

They are not marked sensitive upstream but we can make them secret in the pulumi projection. Doing so encrypts them in the state both in output and in input position, so state is then clear. 

I think it's a good change we should take, but if there's any additional leak in the stdout/stderr I would love a repro.
