### ISSUE TITLE
CloudWatch Cross-Account Observability

### ISSUE THREAD

**Issue by Fydon** [pulumi/pulumi-aws#2449]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

AWS encourages the use of AWS Organisations to improve security. However adding multiple accounts results in challenges. [Amazon CloudWatch Observability Access Manager](https://docs.aws.amazon.com/OAM/latest/APIReference/Welcome.html) allows an account to receive CloudWatch data from multiple accounts within the same region, which helps monitor all the accounts. Blog [here](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-cloudwatch-cross-account-observability-multiple-aws-accounts/). Being able to manage this through Pulumi would be a significantly help to people with many AWS accounts.

### Affected area/feature

The Terraform AWS Provider just released [support for this](https://github.com/hashicorp/terraform-provider-aws/pull/30401). The API documentation is [here](https://docs.aws.amazon.com/OAM/latest/APIReference/Welcome.html).

**Comment by danielrbradley** [comment]
Thanks for bringing this to our attention @Fydon 

This hasn't been released yet on the Terraform side - only merged to master. Looks like it will be included when they cut v4.62.0 which I'd expect will be some time later this week. The feature will then be integrated in Pulumi's provider on the release following that.

**Comment by adityaoke** [comment]
Is this supported in Pulumi native or classic now?

**Comment by VenelinMartinov** [comment]
Looks like both:
https://www.pulumi.com/registry/packages/aws/api-docs/oam/link/
https://www.pulumi.com/registry/packages/aws-native/api-docs/oam/link/
