### ISSUE TITLE
Inspector2: OrganizationConfiguration setting `auto_enable` `lambda_=True` fails 

### ISSUE THREAD

**Issue by magreenbaum** [pulumi/pulumi-aws#2459]
### What happened?

When attempting to apply `lambda_=True` in `auto_enable=aws.inspector2.OrganizationConfigurationAutoEnableArgs()`, the following stack trace is produced:
```
  pulumi:pulumi:Stack (organization-settings):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "file_location.py", line 43, in <module>
        inspector2_organization_configuration = Inspector2OrganizationConfiguration(
      File "file_location.py", line 22, in __call__
        return super().__call__(*args, **kwargs)
      File "file_location.py", line 98, in __init__
        auto_enable=aws.inspector2.OrganizationConfigurationAutoEnableArgs(
    TypeError: OrganizationConfigurationAutoEnableArgs.__init__() got an unexpected keyword argument 'lambda_'

```
All other attributes (ecr=True, ec2=True) are applied with no issue. 

### Expected Behavior

When running pulumi up, this configuration would get applied without issue. 

### Steps to reproduce

Following the example [here](https://www.pulumi.com/registry/packages/aws/api-docs/inspector2/organizationconfiguration/#basic-usage), setting `lambda_` at all whether `True` or `False` will produce the error described:
```
import pulumi
import pulumi_aws as aws

example = aws.inspector2.OrganizationConfiguration("example", auto_enable=aws.inspector2.OrganizationConfigurationAutoEnableArgs(
    ec2=True,
    ecr=False,
    lambda_=True,
))
```

### Output of `pulumi about`

```
CLI          
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @magreenbaum - thank you for raising this issue! Before we proceed too much further, would you mind running the same `pulumi about` command in the same directory as your `Pulumi.yaml` file? That will give us a better idea of which version of this provider is being used, etc.  This argument was only added ~3 weeks ago, and it's possible you're on a version which is older than that.

**Comment by magreenbaum** [comment]
Thanks @kpitzen, I needed to update pulumi-aws version 🤦‍♀️.

**Comment by kpitzen** [comment]
Thanks @magreenbaum ! I'm glad that worked out for you - feel free to reach out if you encounter any further issues!
