### ISSUE TITLE
Support c7g instance types

### ISSUE THREAD

**Issue by jonasbostoen** [pulumi/pulumi-aws#2474]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi doesn't currently support the [c7g instance types](https://aws.amazon.com/ec2/instance-types/c7g/). I would like to request or add support for them (not familiar with the codebase though so would need some guidance).

**Comment by mikhailshilkov** [comment]
@jonasbostoen Thank you for reporting this. Where exactly aren't you able to specify a c7g instance type? Can you provide a snippet code?

In principle, you should be able to pass any string to the instance type property, including c7gs.

**Comment by jonasbostoen** [comment]
Oh you're right, that's my bad. I thought all available instance types where pre-defined in the `aws.ec2.InstanceType` enum.
