### ISSUE TITLE
Add support to add WebAcl Rules after the creation of a WebAcl (WAF)

### ISSUE THREAD

**Issue by LazaroOnline** [pulumi/pulumi-aws#2487]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`pulumi/aws` doesn't seem to support creating "wafv2.WebAclRules" after the creation of the WAF with `new aws.wafv2.WebAcl(...)`, 
in the AWS-CLI it is supported here "[create-rule](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/waf/create-rule.html)", and it can be done also from AWS web console, but [pulumi WebAcl](https://www.pulumi.com/registry/packages/aws/api-docs/wafv2/webacl/) doesn't seem to have it...
It would allow my team to create the WAF in a shared project while allowing specific domains to add more rules to the WAF afterwards.

**Comment by rquitales** [comment]
@LazaroOnline Thanks for reaching out about this issue.

If I'm reading the documentation correctly for the AWS CLI command, [create-rule](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/waf/create-rule.html) is for WAF Classic. I'm unfamiliar with this surface area, so I'm unsure if this will also work for WAF v2. For WAF Classic, we do have a resource to support creating rules: https://www.pulumi.com/registry/packages/aws/api-docs/waf/rule/

For WAF v2, per the AWS Documentation, I do not see a CLI command or API endpoint that creates a rule. The closest I see relates to creating RuleGroups (https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateRuleGroup.html). For this, we have the following Pulumi resource: https://www.pulumi.com/registry/packages/aws/api-docs/wafv2/rulegroup/.

As I believe we have coverage of the inquired endpoints, I will close this issue. Please feel free to re-open though if you believe this answer is insufficient.

Thanks!
