### ISSUE TITLE
Nuget package appears to have incorrect version for 5.38.0

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#2500]
### What happened?

```
System.IO.FileLoadException: Could not load file or assembly 'Pulumi.Aws, Version=5.38.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Pulumi.Aws, Version=5.38.0.0, Culture=neutral, PublicKeyToken=null'
```

### Expected Behavior

It should install

### Steps to reproduce

`5.*` 

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
That looks like a valid dotnet assembly version? 
Assembly versions aren't semver, they're major.minor[.build[.revision]] (see https://learn.microsoft.com/en-us/dotnet/api/system.version?view=net-7.0).
Nuget versions are semver, but I'd expect the 5.38.0 nuget package to have 5.38.0.0 for the assembly version.

**Comment by rquitales** [comment]
I'm not sure if this is an issue? I've tried to see if I could reproduce this by creating a new AWS classic C# project with: `pulumi new aws-csharp` and running `pulumi up`. I am not running into any issues with using v5.38.0 of the provider and SDK.

Checking the `*.deps.json` file, I see that I am indeed pulling in v5.38.0 successfully: 
```json
"Pulumi.Aws/5.38.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-epku4ZdYGEQB6xNUHgxWk7OsgHT3aj/yunF1ZUHGJB3aMffaNLAVeComEzTw3an6EgJ0UiIwRaYuci0zuS1eZA==",
      "path": "pulumi.aws/5.38.0",
      "hashPath": "pulumi.aws.5.38.0.nupkg.sha512"
    },
```
