### ISSUE TITLE
aws.sesv2.ConfigurationSet.supressionOptions incorrectly requires supressedReasons to have at least 1 item

### ISSUE THREAD

**Issue by lily-es** [pulumi/pulumi-aws#2512]
### What happened?

Attempting to create a SES v2 Configuration Set with empty supressed reasons(to override account-wide supression options) fails with this error:

` error: aws:sesv2/configurationSet:ConfigurationSet resource 'xxxxxxxx' has a problem: Not enough list items: Attribute requires 1 item minimum, but config has only 0 declared.. Examine values at 'ConfigurationSet.SuppressionOptions.SuppressedReasons'.`

When creating a configuration set on the console, it is possible to override account-level supression options and disable them. I edited the configuration set created by pulumi through the console to override and disable supression options. Then, running `pulumi import` showed this result:

```
Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.
 details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:sms-email-prod::sms-email::pulumi:pulumi:Stack::sms-email-sms-email-prod]
    ~ aws:sesv2/configurationSet:ConfigurationSet: (update)
        [id=default]
        [urn=urn:pulumi:sms-email-prod::sms-email::aws:sesv2/configurationSet:ConfigurationSet::xxxxxx]
        [provider=urn:pulumi:sms-email-prod::sms-email::pulumi:providers:aws::default_5_39_0::0233d0ba-3de7-4a05-99f4-cc50c04ee517]
        --outputs:--
      + suppressionOptions  : {
          + suppressedReasons: []
        }
```

This shows that it should be possible to set supressionReasons to an empty array, and that this is the only way to override account-level supression options and disable supression.

### Expected Behavior

When defining a ConfigurationSet resource as so:

```
{
  configurationSetName: "example",
  suppressionOptions: {
    suppressedReasons: []
  },
}
``` 

I expect `pulumi up` to succeed and create a Configuration Set overriding the account-level supression options and disabling supression.

### Steps to reproduce

1. Create a sesv2.ConfigurationSet resource with empty supressedReasons like so:
```
{
  configurationSetName: "example",
  suppressionOptions: {
    suppressedReasons: []
  },
}
```
2. Run `pulumi up`

### Output of `pulumi about`

```
CLI          
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.39.0
awsx        1.0.2
docker      3.6.1
nodejs      unknown
postgresql  3.8.0
random      4.13.0

Host     
OS       arch
Version  22.1.0
Arch     x86_64

This project is written in nodejs: executable='/home/lilyes/.local/share/nvm/v16.13.2/bin/node' version='v16.13.2'

Current Stack: sms-email-prod

TYPE                                         URN
pulumi:pulumi:Stack                          urn:pulumi:sms-email-prod::sms-email::pulumi:pulumi:Stack::sms-email-sms-email-prod
pulumi:providers:pulumi                      urn:pulumi:sms-email-prod::sms-email::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference                 urn:pulumi:sms-email-prod::sms-email::pulumi:pulumi:StackReference::networking-prod
pulumi:pulumi:StackReference                 urn:pulumi:sms-email-prod::sms-email::pulumi:pulumi:StackReference::logging-prod
pulumi:providers:aws                         urn:pulumi:sms-email-prod::sms-email::pulumi:providers:aws::default_5_39_0
aws:ses/domainIdentity:DomainIdentity        urn:pulumi:sms-email-prod::sms-email::aws:ses/domainIdentity:DomainIdentity::xxxxx-ses-domain-identity-sms-email-prod
aws:sns/smsPreferences:SmsPreferences        urn:pulumi:sms-email-prod::sms-email::aws:sns/smsPreferences:SmsPreferences::sms-email-prod-sns-sms-preferences
aws:ses/domainDkim:DomainDkim                urn:pulumi:sms-email-prod::sms-email::aws:ses/domainDkim:DomainDkim::xxxxxx-ses-domain-dkim-sms-email-prod
aws:sesv2/configurationSet:ConfigurationSet  urn:pulumi:sms-email-prod::sms-email::aws:sesv2/configurationSet:ConfigurationSet::xxxxxx-ses-configuration-set-sms-email-prod
aws:route53/record:Record                    urn:pulumi:sms-email-prod::sms-email::aws:route53/record:Record::xxxxxx-domain-dkim-record-1-sms-email-prod
aws:route53/record:Record                    urn:pulumi:sms-email-prod::sms-email::aws:route53/record:Record::xxxxxx-domain-dkim-record-2-sms-email-prod
aws:route53/record:Record                    urn:pulumi:sms-email-prod::sms-email::aws:route53/record:Record::xxxxxx-domain-dkim-record-0-sms-email-prod


Found no pending operations associated with sms-email-prod

Backend        
Name           lily-20n3s6gk00
URL            s3://xxxxxxx-pulumi
User           lilyes
Organizations  

Dependencies:
NAME                VERSION
@pulumi/aws         5.39.0
@pulumi/awsx        1.0.2
@pulumi/postgresql  3.8.0
@pulumi/pulumi      3.65.1
@pulumi/random      4.13.0
@types/node         14.18.20
mime-types          2.1.35

Pulumi locates its logs in /tmp by default
```

### Additional context

This might be a problem with the upstream terraform provider, but since I have never used terraform and I am experiencing this issue with pulumi I decided to create the issue here.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @lily-es, sorry you're running into this issue. As a workaround while we look into it, does it work if you leave out `suppressedReasons: []` altogether?

**Comment by thomas11** [comment]
This is actually a [bug in the upstream provider](https://github.com/hashicorp/terraform-provider-aws/issues/28669). We'll look into a way to work around this on our side.

**Comment by mikhailshilkov** [comment]
The upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/28669 has been resolved as fix, so I'll close this issue too. Please report a new issue if the problem occurs again.
