### ISSUE TITLE
[python] Pulumi Import Codegen Fails

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-aws#2517]
### What happened?

When running a `pulumi import ...` command, the importing of the resource succeeds, however, the codegen part fails with an obscure error.

```
error: anonymous.pp:24,22-25,14: cannot assign expression of type (null) to location of type   list(  { onDeregistration: output(string) | string, onUnhealthy: output(string) | string }
  | output({ onDeregistration: string, onUnhealthy: string }))
| output(list({ onDeregistration: string, onUnhealthy: string }))?: ; 
```

### Expected Behavior

Pulumi import succeeds and correctly generates the required code definition.

### Steps to reproduce

Create pulumi python program on pulumi and generate the appropriate code definition.

`pulumi import ....`

See error shown above.

### Output of `pulumi about`

```
CLI          
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.40.0
python  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Watching this, I'm available to investigate this as a potential bridge bug.

**Comment by t0yv0** [comment]
Just some more info to help reproduce. This provisions a TargetGroup.

```python
import pulumi
import pulumi_aws as aws

main = aws.ec2.Vpc("main", cidr_block="10.0.0.0/16")
test = aws.lb.TargetGroup("test",
    port=80,
    protocol="HTTP",
    vpc_id=main.id)

pulumi.export('arn', test.arn)
```

Then I can reproduce with:

```
pulumi import aws:lb/targetGroup:TargetGroup foo $(pulumi stack output arn)
```

```
error: anonymous.pp:27,22-28,14: cannot assign expression of type (null) to location of type   list(  { onDeregistration: output(string) | string, onUnhealthy: output(string) | string }
  | output({ onDeregistration: string, onUnhealthy: string }))
| output(list({ onDeregistration: string, onUnhealthy: string }))?: ; 
```

**Comment by t0yv0** [comment]
Found that this line upstream generates a list with an empty map element:

```
https://github.com/pulumi/terraform-provider-aws/blob/d058da74480f4f9e2faa385eeca82db6915c98a7/internal/service/elbv2/target_group.go#L1133
```

There is an issue in the bridge that translates the empty map to null. Repro-as-unit-test is available:

https://github.com/pulumi/pulumi-terraform-bridge/pull/1105

We have a potential fix that changes that but there's a lot of testing diligence to roll that out. 

I recommend finding some workarounds in the meanwhile so we can reduce urgency from P1. 

Perhaps import code could tolerate it somehow? 

Could we patch upstream code to return an empty list?

**Comment by danielrbradley** [comment]
To resolve the P1, I'll do a patch on the upstream implementation to remove the map if it's got zero elements.
