### ISSUE TITLE
ASG Metrics Missing from Enum

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#2523]
### What happened?

Attempting to enable Warm Pool CloudWatch metrics for an AutoScaling group per [this documentation.](https://www.pulumi.com/registry/packages/aws/api-docs/autoscaling/group/#enabledmetrics_nodejs) 

This references the [underlying AWS API](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_EnableMetricsCollection.html) documentation for acceptable values, to which numerous WarmPool… metrics are available. 

However in the pulumi code (using the latest AWS 5.40.0 provider, I do not have access to these values. Looks like latest code does not include them? https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/enums/autoscaling/index.ts

### Expected Behavior

Support the WarmPool... metrics.

### Steps to reproduce

Try to create an ASG using Typescript and set enabled Metrics to something like `WarmPoolDesiredCapacity` and see it is not supported.

### Output of `pulumi about`

Using latest aws 5.40.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hey @MitchellGerdisch - thanks for opening this issue! The fix here is actually very straightforward:
https://github.com/pulumi/pulumi-aws/blob/e18f3a34298bde434bffb26c275ad48c0ff39d61/provider/resources.go#L4070
Simply add the missing values to this enum here, run `make tfgen` and `make build_sdks`. I have a commit which does the first part, and will try to get around to the others when possible, but if you or someone else beats me to it, that'd be great!
