### ISSUE TITLE
Release Python 3.10 Lambda Runtime support

### ISSUE THREAD

**Issue by mraspberry** [pulumi/pulumi-aws#2542]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

PR #2530 has been merged but not included in a release. Please cut a release that includes that PR so we can use Python 3.10 for Lambda functions.

**Comment by thomas11** [comment]
Hi @mraspberry, since the PR has been merged it will automatically be included in the next release. It should come out this week, we're just a little delayed because it's a new major version.
