### ISSUE TITLE
Upgrade bridge to latest version

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2547]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Upgrade bridge to latest version

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.49.0 would be most helpful.
