### ISSUE TITLE
Upgrade plugin framework to latest version

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2548]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Upgrade plugin framework to latest version
This will allow for newly ported / created plugin framework resources to be exposed via the Pulumi AWS provider in addition to the current SDK-based resources.

**Comment by t0yv0** [comment]
The work here is generating a version of https://github.com/pulumi/pulumi-aws/pull/2464 PR on top of https://github.com/pulumi/pulumi-aws/pull/2544 so that plugin-framework based resources are available in the alpha.
