### ISSUE TITLE
Update implementation method of backported resources for v6

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2549]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Update implementation method of backported resources for v6

The majority of this work is just renaming the `_reverted` and removing the corresponding backported files. We will also need to track down backported resources which do not follow this pattern, since it was only adopted relatively recently. A decent starting point is just pulling a diff between our fork and the upstream provider, and looking for diffs where ours is using the SDK, and theirs is not.

**Comment by t0yv0** [comment]
We believe  https://github.com/pulumi/pulumi-aws/issues/2533 might be fixes as part of but will need to verify.

**Comment by mikhailshilkov** [comment]
Fixed by #2578
