### ISSUE TITLE
Test and validate changes related to default tagging behavior

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2550]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Test and validate changes related to default tagging behavior
We should verify whether #2549 _actually_ closes out #2533 - ideally by adding a programtest to reproduce the issue, and validating that it passes once the reverted SDK resource is removed.

**Comment by mikhailshilkov** [comment]
I tested https://github.com/pulumi/pulumi-aws/issues/2533 manually and it does appear to be fixed. I'll have to think how to write a ProgramTest for it because the issue does not manifest in the Pulumi state - it's only in the actual cloud state where the tags are missing.

**Comment by mnlumi** [comment]
Let's add a specific test case for this scenario as part of https://github.com/pulumi/pulumi-aws/issues/2539

**Comment by iwahbe** [comment]
Closed by #2655
