### ISSUE TITLE
aws_cognito_managed_user_pool_client is referred to in docs but not available

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-aws#2566]
The registry docs for [aws.cognito.UserPoolClient](https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpoolclient/#aws-cognito-userpoolclient) state

> To manage a User Pool Client created by another service, such as when [configuring an OpenSearch Domain to use Cognito authentication](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cognito-auth.html), use the aws_cognito_managed_user_pool_client resource instead.

However, this resource ([upstream docs here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_managed_user_pool_client)) is not available in the Pulumi provider. We should either add it and link to it, or else update the docs in another way that doesn't refer directly to a TF resource.

**Comment by mikhailshilkov** [comment]
ManagedUserPoolClient is available now: https://www.pulumi.com/registry/packages/aws/api-docs/cognito/manageduserpoolclient/

I'll close the issue as done.
