### ISSUE TITLE
`aws.sdk` usage raises "NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023."

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#2568]
Any program which uses `aws.sdk` sees this warning:

```
    (node:61320) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
    Please migrate your code to use AWS SDK for JavaScript (v3).
    For more information, check the migration guide at https://a.co/7PzMCcy
    (Use `node --trace-warnings ...` to show where the warning was created)
```

This is because `@pulumi/aws` uses `"aws-sdk": "^2.0.0",`.  

We likely need to move to exposues `^3.0.0`, though that would be a breaking change.  We might want to include this change into v6?

**Comment by mikhailshilkov** [comment]
Sounds reasonable. @kpitzen @rquitales Could you please make sure it gets to 6.0?

**Comment by lukehoban** [comment]
Looked into this a little - and its unfortunately not at all clear how to handle this.

Moving from v2 to v3, they removed the existence of a monolithic AWS SDK (`aws-sdk`), and now have many smaller SDKs (`@aws-sdk/client-dynamodb`).  

The trouble is that our `aws.sdk` property fundamentally assumes there is a monolithic AWS SDK instance we can expose as that property.

I think the options are:
1. Keep using v2, and find a way to suppress the warning.  This avoids a breaking change, but may be even more fully deprecated in the future though, so quite likely just buys some time before we do something more breaking.
2. Remove the `aws.sdk` property entirely in v6, and include in the migration guide steps for how users can move to using the new AWS SDK v3 directly from their code.  This seems to be the thing we'll almost have to do eventually.  
3. Somehow bundle all the modules into a single property we expose. This seems to largely defeat the point of AWS SDK v3, and still wouldn't be compatible.  It's not clear there's a meaningful benefit to this.

We should make a decision on 1 vs. 2 quickly ahead of the v6 release.

**Comment by kpitzen** [comment]
To me, it seems like the value-add here is relatively minimal. Is there a use case I'm missing where users who, today, use `aws.sdk` would be _unable_ to use aws-sdk v3 directly? I notice closure serialization mentioned in the comments of our sdk exposure, but that shouldn't be an issue given lambda already includes the sdk, correct?

**Comment by pierskarsenbarg** [comment]
Removing it will affect folks who use our TS serialisation in lambda functions. Admittedly it does go against AWS best practice because you're performing initialisation within the handler. I'll update this shortly with an example of what I mean.

**Comment by lukehoban** [comment]
> Removing it will affect folks who use our TS serialisation in lambda functions.

It will only affect them if they use `aws.sdk` instead of relying on the AWS SDK directly themselves.  This feature is largely undocumented, though it is convenient.  

> Admittedly it does go against AWS best practice because you're performing initialisation within the handler.

Note that you can always use `callbackFactory` to run code in initialization using the `aws.sdk` object (or directly initializing AWS SDK modules).

**Comment by lukehoban** [comment]
Here's a PR with the proposed removal: https://github.com/pulumi/pulumi-aws/pull/2584

Here's how user code using `aws.sdk` would need to be updated to avoid using this library.

https://github.com/pulumi/pulumi-aws/pull/2584/files#diff-3221528d83aa757e1d24587b5c168bb09079ed5d31ddad796019529e302a3317L19-R57

**Comment by iwahbe** [comment]
Closed by https://github.com/pulumi/pulumi-aws/pull/2584.
