### ISSUE TITLE
Consider safer approach to determining packages to include in serverless Function zip

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#257]
In https://github.com/pulumi/pulumi-aws/pull/222, we reduced the size of serverless Function zip uploads by computing the package dependencies of the serialized code as a base set, and then allowing the user to specify additional packages to include if these dependencies were not computed correctly.

This approach generally works well, and computes minimal required depdendencies, but has a hole in one important case - when a relative require like  `require("./other")` is seen in serialized code, we cannot know what packages may transitively be needed by the code in `other.js` and it's transitive dependencies.

https://github.com/pulumi/pulumi-aws/blob/master/overlays/nodejs/serverless/function.ts#L265-L276

At the time, we felt this was rare enough, and the escape hatch of manually including the packages acceptable enough, that this was okay.

There is an alternative though that we may want to consider - switching to include everything *except* `@pulumi/*` packages (and transitive dependencies only pulled in through those - like `grpc` and `typescript` in the common case).

The existing `read-package-tree` search that we do would allow us to determine the true transitive dependencies of the subset of non-`@pulumi` dependencies.  We could in principle base this on a tag in `package.json` instead of on `@pulumi/*`, though the latter is probably sufficient initially.  

We could then have a user-controlled blacklist instead of whitelist, as a means to remove additional packages from the zip upload (better pay-for-play, as using this feature proactively helps further reduce upload time/size).

**Comment by joeduffy** [comment]
I am very much in favor of an approach like this.  Requiring people to think deeply about this problem waters down our value proposition significantly, wherein we want developers to just write easy and intuitive code and have it work, using that Pulumi magic.

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/pulumi-aws/pull/268.
