### ISSUE TITLE
After tagging v6-alpha main branch fails to build

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2572]
### What happened?

After creating v6-alpha tags, main branch builds are affected as they are confused about the major version. `pulumictl` now thinks that master builds are on 6.0.0 whereas other parts of the code are assuming a v5 major version. This causes failures like https://pulumi.slack.com/archives/C02FXTZEZ6W/p1687524638095169?thread_ts=1687492809.750579&channel=C02FXTZEZ6W&message_ts=1687524638.095169

I can reproduce by calling `make tfgen` on master and observing a v6 version being linked into the binary.

### Expected Behavior

main branch builds correctly on the v5 version

### Steps to reproduce

run make tfgen provider on master and observe non-empty diff

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Closing this issue as this is resolved by removing the `v6.0.0-alpha.0` tag which was mistakenly created.

**Comment by t0yv0** [comment]
@rquitales resolved it by removing the -alpha tag that accidentally marked the master branch tip commit as 6.x.x.
