### ISSUE TITLE
RolePolicyAttachment not reattached if manually detached

### ISSUE THREAD

**Issue by shawnjones253** [pulumi/pulumi-aws#2600]
### What happened?

when using `RolePolicyAttachment` via pulumi, if the policy is detached from the role outside of pulumi, pulumi won't reattach the policy to the role on the next run of `pulumi up`

### Expected Behavior

if the policy is no longer attached to the role, `pulumi up` will reattach it

### Steps to reproduce

1. create role
2. create policy
3. attach policy by creating a `RolePolicyAttachment`
4. pulumi up
5. manually remove the policy from the role via the aws console or cli
6. pulumi up

### Output of `pulumi about`

```
❯ pulumi about
CLI
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Host
OS       darwin
Version  13.3.1
Arch     arm64

Backend
Name           pulumi.com
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @shawnjones253 thanks for writing this up. 

Are you performing a `pulumi refresh` before the second `pulumi up`?

Can you confirm the issue still occurs with the following flow:

1. create role
2. create policy
3. attach policy by creating a RolePolicyAttachment
4. pulumi up
5. manually remove the policy from the role via the aws console or cli
6. _pulumi refresh_
7. pulumi up

**Comment by shawnjones253** [comment]
thanks, this does work -- i misunderstood how `pulumi up` works and assumed it did the equivalent of a `pulumi refresh` before applying an update
