### ISSUE TITLE
ec2.RouteTable throws "instance_id" deprecated warning when not specified

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#2612]
### What happened?

Running the code below, throws this warning:
`warning: instance_id is deprecated: Use network_interface_id instead`

However no `instance_id` is passed as an input.
It seems like some default value is being set in the API and thus triggering the warning about the deprecated `instance_id` property.

```
import pulumi
from pulumi_aws import ec2
name = "mydeployment"
vpc_name = name+'-vpc'
vpc = ec2.Vpc(vpc_name,
    cidr_block='10.100.0.0/16',
    instance_tenancy='default',
    enable_dns_hostnames=True,
    enable_dns_support=True,
    tags={
        'Name': vpc_name
    })

igw_name = name+'-igw'
igw = ec2.InternetGateway(igw_name,
    vpc_id=vpc.id,
    tags={
        'Name': igw_name
    })

rt_name = name+'-rt'
route_table = ec2.RouteTable(rt_name,
    vpc_id=vpc.id,
    routes=[ec2.RouteTableRouteArgs(
        cidr_block='0.0.0.0/0',
        gateway_id=igw.id,
    )],
    tags={
        'Name': rt_name
    })
```

### Expected Behavior

No warning should be given.

### Steps to reproduce

1. `pulumi new aws-python`
2. Copy the code given above into the `__main__.py`
3. Run `pulumi preview` or `pulumi up`
4. See warning about instance_id even though no instance_id is specified.

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
python  unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME        VERSION
pip         23.1.2
pulumi-aws  5.42.0
setuptools  68.0.0
wheel       0.40.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by MitchellGerdisch** [comment]
Note, this issue does not appear to exist with the typescript version of the provider.

**Comment by thomas11** [comment]
Thanks for reporting this, @MitchellGerdisch. It seems that the deprecation is due to [an upstream change](https://github.com/hashicorp/terraform-provider-aws/issues/14197) that was released in the new major version. Therefore, the upcoming release of pulumi-aws 6.0 should remove this warning.
