### ISSUE TITLE
Bump java codegen to max

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2616]
There's a TODO [here](https://github.com/pulumi/pulumi-aws/blob/b1af0c35e3deb9fbc325c3032834a50c4a9e58bc/sdk/java/src/main/java/com/pulumi/aws/Utilities.java#L60) that should be resolved by bumping codegen to max.

**Comment by iwahbe** [comment]
This is a potentially breaking change, so we will add this as part of the v6 upgrade.

**Comment by iwahbe** [comment]
Closed by #2619.
