### ISSUE TITLE
v6 is incompatible with `@pulumi/aws` and `@pulumi/aws-apigateway`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#2639]
It appears that some of the breaking changes in v6 lead to very unfortunate incompatibility with some of our most popular libraries.

For example - updating https://github.com/pulumi/examples/blob/master/aws-apigateway-ts-routes/index.ts to use `@pulumi/aws` v6 leads to errors like the following:

```
Type 'CallbackFunction<unknown, { statusCode: number; body: string; }>' is not assignable to type 'Input<Function> | undefined'.
  Type 'CallbackFunction<unknown, { statusCode: number; body: string; }>' is not assignable to type 'Function'.
    Types of property 'roleInstance' are incompatible.
      Type 'import("/Users/lukehoban/go/src/github.com/pulumi/examples/aws-apigateway-ts-routes/node_modules/@pulumi/aws/iam/role").Role | undefined' is not assignable to type 'import("/Users/lukehoban/go/src/github.com/pulumi/examples/aws-apigateway-ts-routes/node_modules/@pulumi/aws-apigateway/node_modules/@pulumi/aws/iam/role").Role | undefined'.
        Property 'roleLastUseds' is missing in type 'import("/Users/lukehoban/go/src/github.com/pulumi/examples/aws-apigateway-ts-routes/node_modules/@pulumi/aws/iam/role").Role' but required in type 'import("/Users/lukehoban/go/src/github.com/pulumi/examples/aws-apigateway-ts-routes/node_modules/@pulumi/aws-apigateway/node_modules/@pulumi/aws/iam/role").Role'.
```

That is - the v6 instance of `aws.lambda.Function` can not be passed to the MLCs expected v5 version of `aws.lambda.Function`.

This appears to be because of a confluence of two things:
1. The `roleLastUseds` property of `aws.iam.Role` was removed by upstream as a breaking change: https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#510-june--1-2023
2. The `aws.lambda.Function` type has, by a weird mechanism, a `roleInstance: aws.iam.Role` as a property.

This prevents passing a v6 `Function` to something expecting a v5 `Function`.

I think there are two potential fixes:
a. It is not clear why the `roleInstance` property above is being added to the `aws.lambda.Function` type.  It should be added directly to `aws.lambda.CallbackFunction` instead.  Moving it there in v6 (it can never be present in practice on other Function instances AFAICT), would alleviate this problem.
b. We could bitigate the removal of the `roleLastUseds` property, by keeping the property and just not populating it, to avoid a type-level breaking change.  

I'm inclined to do (a) unless there are other similar problems that lead to the need for something deeper.

**Comment by mikhailshilkov** [comment]
@lukehoban Could you please share your branch so that we could repro the issue? I tried updating `aws-apigateway-ts-routes/index.ts` myself and it compiled just fine for me. Also, Ian and I couldn't find a `roleInstance` property on `aws.lambda.Function` - I guess there is some confusion somewhere here. Thank you!

**Comment by lukehoban** [comment]
> Also, Ian and I couldn't find a roleInstance property on aws.lambda.Function - I guess there is some confusion somewhere here.

https://github.com/pulumi/pulumi-aws/blob/8163083eae9db18e6a73f9a516d906cc57461266/sdk/nodejs/lambda/lambdaMixins.ts#L447

This is an odd TS specific “overlay”. I believe that can be removed and the property can be added directly to CallbackFunction instead.

**Comment by iwahbe** [comment]
Closed by https://github.com/pulumi/pulumi-aws/pull/2645.
