### ISSUE TITLE
Resolve AutoNaming warnings in the V6 release

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2644]
### What happened?

Currently on the V6 branch we have this warning emitted by tfgen:

```
warning: SetAutonaming call is currently ignored for bridged resources built with the Plugin Framework. Supporting this feature is tracked in pulumi/pulumi-terraform-bridge#917.
These resources employ autonaming:
- resource:aws_appconfig_environment
- resource:aws_cognito_user_pool_client
- resource:aws_simpledb_domain
To avoid this warning, exclude these resources from auto naming, for example by adding them to ProviderInfo.Resources after the SetAutonaming call.
```

The user-facing impact is that retracting auto-naming support a resource, for a resource that has a Required "name" property, changes the type of that property from Optional to Required. It was previously made optional by the Bridge Auto-Naming feature which would supply a default name. In strongly typed languages the code would fail to compile after the update. Further, to make a non-eventful stack upgrade the user would need to find the previous auto name-populated value from the stack state and copy it into her program.

I believe cognito is new in V6, but simpledb Domain might have been supported in v6 and regressing.

### Expected Behavior

Autonaming support does not regress in V6

### Steps to reproduce

Try to provision aws:simpledb/domain:Domain on V5 without specifying name and upgrade the stack to v6.

### Output of `pulumi about`

N/A

### Additional context

If we were to fix the warning, it should be possible to finish up https://github.com/pulumi/pulumi-terraform-bridge/pull/1116 and update the bridge used in AWS. Alternatively suggest a workaround for users to manually populate "name" to match the previous auto-generated name in their programs.

 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
> The user-facing impact is that retracting auto-naming support a resource, for a resource that has a Required "name" property, changes the type of that property from Optional to Required.

> It currently returns these on the V6 branch:
> 
> ```
> aws:cognito/userPoolClient:UserPoolClient
> aws:appconfig/environment:Environment
> aws:simpledb/domain:Domain
> ```

None of these appear to have `name` required in the v6 branch.
* https://github.com/pulumi/pulumi-aws/blob/8163083eae9db18e6a73f9a516d906cc57461266/sdk/nodejs/cognito/userPoolClient.ts#L386
* https://github.com/pulumi/pulumi-aws/blob/8163083eae9db18e6a73f9a516d906cc57461266/sdk/nodejs/appconfig/environment.ts#L181
* https://github.com/pulumi/pulumi-aws/blob/8163083eae9db18e6a73f9a516d906cc57461266/sdk/nodejs/simpledb/domain.ts#L100

Does that indicate there is no impact here?  Or could they have the right type but behave incorrectly inside the provider?

**Comment by t0yv0** [comment]
Interesting. There's still impact. This would fail at runtime without a name specified. We can resolve the warning by moving around the SetAutonaming call so that it happens before the resources are declared; once we do that the warning won't be there but schema will change into required.
