### ISSUE TITLE
Supporting python 3.11 in lambda function runtime

### ISSUE THREAD

**Issue by jamie-chapman** [pulumi/pulumi-aws#2652]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Python 3.11 support for lambda functions was announced yesterday by AWS, it would be great to have it supported in Pulumi so we can upgrade ASAP. https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#runtime

### Affected area/feature

aws.lambda.Function

**Comment by rquitales** [comment]
Hi @jamie-chapman and thanks for reporting this enhancement. I'll add this to our backlog.

#2530 would be a good reference PR on how to support Python 3.11.

**Comment by WillDaSilva** [comment]
@rquitales I'd be happy to contribute this enhancement. Any objections to me getting started on a PR for this?

**Comment by rquitales** [comment]
@WillDaSilva Thanks for picking this up. We welcome all community contributions and look forward to working with you! Feel free to ping me if you need any further assistance.

**Comment by WillDaSilva** [comment]
Thanks @rquitales

I've made a PR for this:
- https://github.com/pulumi/pulumi-aws/pull/2653

**Comment by rquitales** [comment]
I've merged the PR, and the change will be picked up in our next release!

**Comment by WillDaSilva** [comment]
Thanks @rquitales!

Do you have an estimate for when the next release will be published? This isn't urgent for us, but even a rough prediction (weeks versus months) would be nice to have. I see you're working on V6 right now, which might impact the release schedule.

**Comment by mnlumi** [comment]
@WillDaSilva We're targeting the release of v6 soon, within the next two weeks. This fix will be included in v6.
