### ISSUE TITLE
Update local examples to v6

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2674]
Update all examples and tests within pulumi-aws repo to use v6.

https://github.com/pulumi/pulumi-aws/tree/master/examples
https://github.com/pulumi/pulumi-aws/blob/master/examples/examples_go_test.go#L18

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/blob/e5e6ddd926f63895c34342d8f19a01b771942674/examples/examples_go_test.go#L18-#L18 looks like Ramon updated this one already

**Comment by t0yv0** [comment]
Just giving it a quick scan again, I think the effect is mostly cosmetic that is things like https://github.com/pulumi/pulumi-aws/blob/e5e6ddd926f63895c34342d8f19a01b771942674/examples/webserver-go/go.mod#L6-#L6 aren't great for users to discover, but these dependencies get updated on-the-fly by the CI to the current in-source version so I'm not worried about testing the wrong software in CI, just a nice cleanup task.

**Comment by mnlumi** [comment]
Current V5 references: 
- https://github.com/pulumi/pulumi-aws/blob/master/examples/webserver-go/go.mod#L6
- https://github.com/pulumi/pulumi-aws/blob/master/examples/webserver-go/go.sum#L170-L171
- https://github.com/pulumi/pulumi-aws/blob/master/examples/webserver-go/main.go#L6

**Comment by mnlumi** [comment]
Fixed by https://github.com/pulumi/pulumi-aws/pull/2716
