### ISSUE TITLE
aws.acm.Certificate no CNAME name/value for validation

### ISSUE THREAD

**Issue by tangr** [pulumi/pulumi-aws#2687]
### What happened?

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const exampleCertificate = new aws.acm.Certificate("exampleCertificate", {
  domainName: "example.com", // <-- replace with your primary domain
  validationMethod: "DNS",
  // add the list of alternate domain names you want to associate with the certificate
  subjectAlternativeNames: [
    "www.example.com",
    "api.example.com",
    "blog.example.com",
  ], // <-- replace with your SANs
});

export const certificateArn = exampleCertificate.arn;
```

see: https://www.pulumi.com/ai/?convid=6839ad9c-83c0-44c5-b00a-c5a7ac6363d0

but there was no CNAME name/value for validation, see attached:
![screenshot-20230809-233335](https://github.com/pulumi/pulumi/assets/4860338/c5279d6b-b43f-4b6c-999b-32357e24ecc4)

### Expected Behavior

show the validation records for the manual validation, and not hangs on the creating when pulumi up.
 

### Steps to reproduce

above code, with pulumi version 3.77.1 and aws version: resource-aws-v5.42.0
run pulumi up, directly.

```json
{
    "name": "aws-iam",
    "devDependencies": {
        "@types/js-yaml": "^4.0.5",
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/aws": "^5.0.0",
        "@pulumi/pulumi": "^3.32.1",
        "js-yaml": "^4.1.0"
    }
}
```

### Output of `pulumi about`

```
CLI
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       centos
Version  7.9.2009
Arch     x86_64

This project is written in nodejs: executable='/bin/node' version='v16.18.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @tangr. Thanks for reporting this. How long have you waited for the described cert to appear? `aws.acm.Certificate` returns before the cert is valid. If you want to guarantee that you have waited long enough, you can use `aws.acm.CertificateValidation`. This is described in https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#amazon-issued-certificates.

If you are using manual validation, you need to attach the appropriate DNS record after validation is requested but before it can succeed.

**Comment by tangr** [comment]
> Hey @tangr. Thanks for reporting this. How long have you waited for the described cert to appear? `aws.acm.Certificate` returns before the cert is valid. If you want to guarantee that you have waited long enough, you can use `aws.acm.CertificateValidation`. This is described in https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#amazon-issued-certificates.
> 
> If you are using manual validation, you need to attach the appropriate DNS record after validation is requested but before it can succeed.

Hey  @iwahbe , thanks for the reply. I waited for more than a few minutes, until the pulumi update finished, but I don't think it will be ok done, since the needed validation records was empty. 
If I create domain manual on the aws console, ~10secs, no more than 1 minute longest.

**Comment by tangr** [comment]
> Hey @tangr. Thanks for reporting this. How long have you waited for the described cert to appear? `aws.acm.Certificate` returns before the cert is valid. If you want to guarantee that you have waited long enough, you can use `aws.acm.CertificateValidation`. This is described in https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#amazon-issued-certificates.
> 
> If you are using manual validation, you need to attach the appropriate DNS record after validation is requested but before it can succeed.

@iwahbe any updates on this? It was easy & 100% reproduce.

**Comment by iwahbe** [comment]
Hey @tangr. Sorry for not responding. The team was on vacation last week. No updates yet.

**Comment by tangr** [comment]
> Hey @tangr. Sorry for not responding. The team was on vacation last week. No updates yet.

@iwahbe Hi, any update on this?

**Comment by mikhailshilkov** [comment]
Hey @tangr, I changed your code from `example.com` to some bogus domain name:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const exampleCertificate = new aws.acm.Certificate("exampleCertificate", {
  domainName: "somethingdsfhoghwoe.com", 
  validationMethod: "DNS",
  subjectAlternativeNames: [
    "www.somethingdsfhoghwoe.com",
    "api.somethingdsfhoghwoe.com",
    "blog.somethingdsfhoghwoe.com",
  ], // <-- replace with your SANs
});

export const certificateArn = exampleCertificate;
```

and then the deployment succeeded in a few seconds. I can see CNAME data in AWS Console:

<img width="1354" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/e89f4258-9d48-4483-9c76-63236293737d">

I think `example.com` is a bit of special case here. Do you get the same behaviour with proper custom domains, or imaginary ones as mine?

**Comment by tangr** [comment]
> Hey @tangr, I changed your code from `example.com` to some bogus domain name:
> 
> ```ts
> import * as pulumi from "@pulumi/pulumi";
> import * as aws from "@pulumi/aws";
> 
> const exampleCertificate = new aws.acm.Certificate("exampleCertificate", {
>   domainName: "somethingdsfhoghwoe.com", 
>   validationMethod: "DNS",
>   subjectAlternativeNames: [
>     "www.somethingdsfhoghwoe.com",
>     "api.somethingdsfhoghwoe.com",
>     "blog.somethingdsfhoghwoe.com",
>   ], // <-- replace with your SANs
> });
> 
> export const certificateArn = exampleCertificate;
> ```
> 
> and then the deployment succeeded in a few seconds. I can see CNAME data in AWS Console:
> 
> <img alt="image" width="1354" src="https://user-images.githubusercontent.com/1454008/266275153-e89f4258-9d48-4483-9c76-63236293737d.png">
> I think `example.com` is a bit of special case here. Do you get the same behaviour with proper custom domains, or imaginary ones as mine?


Hmmm, so weird, I tested example11.com & example22.com before, not works.
but it's ok now.
thx @mikhailshilkov
