### ISSUE TITLE
Cloudfront distribution fills in 0'd defaultTtl / minTtl / maxTtl if not set

### ISSUE THREAD

**Issue by mivtachyahu** [pulumi/pulumi-aws#2688]
### What happened?

I would like my defaultCacheBehaviour to use the "Use origin cache headers" setting.
In terraform I achieve this by not setting defaultTtl, minTtl or maxTtl.

If I do this in pulumi, it fills them in with 0's instead. There appears to be no option to "Use origin cache headers"

### Expected Behavior

Not setting a defaultTtl, minTtl and maxTtl should use the "Use origin cache headers" behaviour instead of filling these in with 0's.

### Steps to reproduce

1. Create a cloudfront distribution with a forwardedValues set for the defaultCacheBehavior
2. Do not set a defaultTtl, minTtl, or maxTtl

### Output of `pulumi about`

CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
nodejs  unknown

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in nodejs: executable='/Users/matthewbrown/.nvm/versions/node/v18.15.0/bin/node' version='v18.15.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @mivtachyahu , could you provider an example or reproduction of your program? Also, what language are you using – it looks like 0's should be the correct default value for these attributes in each language regardless

**Comment by mivtachyahu** [comment]
Hi @aq17  - I'm using TypeScript.
Here's an example piece of code with minTtl / maxTtl / defaultTtl values unset:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("myBucket");

const distributionArgs: aws.cloudfront.DistributionArgs = {
    enabled: true,
    origins: [{
        domainName: bucket.bucketRegionalDomainName,
        originId: bucket.arn,
    }],
    defaultCacheBehavior: {
        targetOriginId: bucket.arn,
        viewerProtocolPolicy: "redirect-to-https",
        allowedMethods: ["GET", "HEAD", "OPTIONS"],
        cachedMethods: ["GET", "HEAD", "OPTIONS"],
        forwardedValues: {
            cookies: {
                forward: 'none',           
            },
            queryString: false,
        },
    },
    restrictions: {
        geoRestriction: {
            restrictionType: "none",
        },
    },
    viewerCertificate: {
        cloudfrontDefaultCertificate: true,
    }
};



const cdn = new aws.cloudfront.Distribution("cdn", distributionArgs);

export const cdnUrl = cdn.domainName;
```

Which yields this config in the aws console:
<img width="790" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/5746715/f7a83988-ee09-4009-a84a-d664d58ae69e">

On a whim I decided to update the example above with the default values for maxTtl / defaultTtl from reading the aws-sdk code and a 0 of minTtl:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("myBucket");

const distributionArgs: aws.cloudfront.DistributionArgs = {
    enabled: true,
    origins: [{
        domainName: bucket.bucketRegionalDomainName,
        originId: bucket.arn,
    }],

    defaultCacheBehavior: {
        targetOriginId: bucket.arn,
        viewerProtocolPolicy: "redirect-to-https",
        allowedMethods: ["GET", "HEAD", "OPTIONS"],
        cachedMethods: ["GET", "HEAD", "OPTIONS"],
        forwardedValues: {
            cookies: {
                forward: 'none',           
            },
            queryString: false,
        },
        minTtl: 0,
        defaultTtl: 86400,
        maxTtl: 31536000,
    },
    restrictions: {
        geoRestriction: {
            restrictionType: "none",
        },
    },
    viewerCertificate: {
        cloudfrontDefaultCertificate: true,
    }
};



const cdn = new aws.cloudfront.Distribution("cdn", distributionArgs);

// Export the CloudFront distribution domain name
export const cdnUrl = cdn.domainName;
```

And it turns out this *does* yield the config setting that I was after in AWS
<img width="790" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/5746715/efae2f90-8b7c-4213-b578-6a6710ac09f1">

But that behaviour isn't documented anywhere, and I assume it's probably the bug that they probably should have the default values from the aws-sdk if they're not set instead of 0s?
