### ISSUE TITLE
No nodes available to schedule pods.

### ISSUE THREAD

**Issue by omidraha** [pulumi/pulumi-aws#2697]
### What happened?

I created a `VPC` using `pulumi_aws` and a `cluster` using `pulumi_eks`, but in the end, I received the error `no nodes available to schedule pods`.

Here is the code:

https://github.com/omidraha/pulumi_example/blob/main/vpc.py
https://github.com/omidraha/pulumi_example/blob/main/iam.py
https://github.com/omidraha/pulumi_example/blob/main/cluster.py
https://github.com/omidraha/pulumi_example/blob/main/setup.py
```bash
$ kubectl get pods -A 
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-6ff9c46cd8-98sck   0/1     Pending   0          24h
kube-system   coredns-6ff9c46cd8-hrj56   0/1     Pending   0          24h

$ kubectl get event -A
NAMESPACE     LAST SEEN   TYPE      REASON             OBJECT                         MESSAGE
kube-system   38s         Warning   FailedScheduling   pod/coredns-6ff9c46cd8-98sck   no nodes available to schedule pods
kube-system   68s         Warning   FailedScheduling   pod/coredns-6ff9c46cd8-hrj56   no nodes available to schedule pods
```

### Expected Behavior

Node be available for Pods.

### Steps to reproduce

```bash
git clone https://github.com/omidraha/pulumi_example
pulumi up
```

### Output of `pulumi about`

```bash
CLI          
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.41.0
aws-native  0.73.0
awsx        1.0.2
cloudflare  5.5.0
docker      3.6.1
eks         1.0.2
kubernetes  3.29.1
python      unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.12
'
Dependencies:
NAME               VERSION
cryptography       41.0.1
graphviz           0.20.1
pip                23.1.2
pulumi-aws-native  0.73.0
pulumi-awsx        1.0.2
pulumi-cloudflare  5.5.0
pulumi-eks         1.0.2
setuptools         65.5.1
websockets         11.0.3
wheel              0.38.4

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @omidraha,

We apologize for the issue you're encountering. It seems that you've successfully created an Amazon EKS cluster; however, the problem you're facing might stem from the absence of nodes or node groups in the cluster. This situation would prevent any work jobs from being scheduled, leading to the issue you're currently experiencing.

To address this, you need to add nodes or node groups to your EKS cluster. Here's an example that demonstrates how to achieve this using the `eks.NodeGroup` resource: [Example AWS EKS with Pulumi](https://github.com/pulumi/examples/blob/master/aws-py-eks/__main__.py).

We will proceed to close this issue, but if you require further assistance or have additional questions, please don't hesitate to reopen it. We're here to help you navigate through any challenges you're facing. Thank you for your understanding, and we look forward to assisting you further if needed.

**Comment by omidraha** [comment]
I've created the cluster, and the nodes have been provisioned,
But the nodes haven't joined the cluster.
What's the problem or missed part?
The complete code is provided below:
https://github.com/omidraha/pulumi_example/blob/main/base/cluster_manual.py
