### ISSUE TITLE
Consider adding runtime APIs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#271]
It would be super convenient if our resource types also exposed the runtime APIs for those types.  For instance, `aws.sqs.Queue` could have `send`, etc. functions on it.  These would be thin wrappers that basically just merge the Pulumi SDK with the target SDK in the language of choice.  For example, that SQS example would just export a subset of these functions directly: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html

There are alternative designs, of course, such as separate libraries.  I'll admit that's where my mind was previously, but at this point, it feels like "low risk" to depend on the actual official AWS SDK libraries -- they version presumably far less frequently than we do, and probably have a better breaking change discipline -- and it's very appealing for this sort of thing to "just work."  It also significantly highlights a unique aspect of Pulumi's platform, which is the use of real languages.

**Comment by stack72** [comment]
@joeduffy is this still something we need now that we have awsx?

**Comment by lukehoban** [comment]
I’d say we should close this out in its current form. We’ve added `aws.sdk` which provides a handle to an AWS SDK instance at runtime which in practice is a substitute for this (but without inventing a new API surface area).
