### ISSUE TITLE
aws.ec2.GetVpcI(p)amPool mis-named

### ISSUE THREAD

**Issue by kwohlfahrt** [pulumi/pulumi-aws#2758]
### What happened?

I was looking for the equivalent of terraform's `aws_vpc_ipam_pool` [data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc_ipam_pool), to get data about an externally provisioned IPAM Pool. I was unable to find it under the expected name, `aws.ec2.getVpcIpamPool`.

Instead, I eventually found `aws.ec2.getVpcIamPool` (note missing the `p` of `Ipam`), [the description](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/getvpciampool/) of which describes it as returning the IPAM pool:
> `aws.ec2.VpcIpamPool` provides details about an IPAM pool.
> This resource can prove useful when an ipam pool was created in another root module and you need the pool’s id as an input variable. For example, pools can be shared via RAM and used to create vpcs with CIDRs from that pool.

### Expected Behavior

I expect the function to be named `aws.ec2.getVpcIpamPool`, not `aws.ec2.getVpcIamPool`.

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A, this typo is [present in the current master branch](https://github.com/pulumi/pulumi-aws/blob/f658bfbb3b1797479c6eac1e1e1d1928062376f7/sdk/nodejs/ec2/getVpcIamPool.ts#L45).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @kwohlfahrt. Thanks for pointing that out to us. This looks like a typo on our end. We should have it fixed soon.
