### ISSUE TITLE
Add state machine principal

### ISSUE THREAD

**Issue by nickroberts** [pulumi/pulumi-aws#2786]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add `states.amazonaws.com` service principal to principal constants.

### Affected area/feature

Add something like this:

```typescript
/**
  * Service Principal for Amazon State Machines
  */
export const StateMachineServicePrincipal: Principal = {Service: "states.amazonaws.com"};
```

to here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/iam/principals.ts

**Comment by mikhailshilkov** [comment]
Thank you for opening this issue @nickroberts! Do you want to try to open a PR for it? It should be fairly straightforward and comparable to https://github.com/pulumi/pulumi-aws/pull/1494 (and no need for manual changeling anymore)
