### ISSUE TITLE
AWS Provider v6 Preview Diff Follow-Up Questions

### ISSUE THREAD

**Issue by caseyyh** [pulumi/pulumi-aws#2800]
PR: https://github.com/pulumi/pulumi-service/pull/15056
Preview Diff: https://app.pulumi.com/pulumi/pulumi-service/testing/previews/efb8fe37-6e61-4025-a132-9753f565776c

@aaijazi pointed out the following in the PR:

> 1. The aws:rds/clusterParameterGroup:ClusterParameterGroup has some paramaters that are maybe changing. Can we confirm that's expected?
> 
> 2. it looks like the containerDefinitions for ecs are changing from a full JSON object to output<string>. That doesn't seem problematic, but just wanted to flag to make sure you saw it

Just wanted to confirm whether this behavior is expected or of concern. Thanks! 🙏

**Comment by mikhailshilkov** [comment]
> The aws:rds/clusterParameterGroup:ClusterParameterGroup has some paramaters that are maybe changing. Can we confirm that's expected?

The current stack [state](https://app.pulumi.com/pulumi/pulumi-service/testing/resources/latest/urn:pulumi:testing::pulumi-service::pulumi-service:infrastructure:ServiceDatabaseCluster$aws:rds/clusterParameterGroup:ClusterParameterGroup::cluster-parameter-testing-80) seem to have three parameters:
<img width="911" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/1454008/02fe28ad-d058-4103-93fa-26e76689966f">

while code seems to have four parameters:

https://github.com/pulumi/pulumi-service/blob/5cab70f6f08779ddb4f9aefb250ff020ea5c70e3/infrastructure/database-cluster.ts#L214-L238

So the diff makes sense and looks unrelated to the provider upgrade?
