### ISSUE TITLE
Add missing `aws.neptune.Cluster` resource

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-aws#281]
As part of #277, I noticed that the `aws_neptune_cluster` Terraform resource is not mapped via `resources.go`, though the other Neptune resources are. From what I can tell it looks like a straightforward mapping, I'll open a pull request once #277 is merged (in order to use the correct `Tags` type).

[1]: https://www.terraform.io/docs/providers/aws/r/neptune_cluster.html

**Comment by joeduffy** [comment]
It looks like this was addressed in https://github.com/pulumi/pulumi-aws/commit/91d022dae3a239244d61574b22bb4af57d45bd5c.
