### ISSUE TITLE
aws.rds.Instance replacement when upgrading from 5.42.0 to 6.2.0

### ISSUE THREAD

**Issue by fruttu** [pulumi/pulumi-aws#2823]
### What happened?

Pulumi is attempting to execute a replacement of the ```aws.rds.Instance``` in our case when updating to newest pulumi-aws. This is probably not as intended?

### Example

When using the deprecated **name** property.
Pulumi preview shows:
```aws:rds:Instance   **-*****-***   replace   [diff: +dbName]; 2 warnings```

Pulumi preview --diff shows:
```
warning: "name" is deprecated, use "dbName" instead.
warning: "name" is deprecated, use "dbName" instead.
        +-aws:rds/instance:Instance: (replace)
            [id=xxx-xxxx-rdsd5e5988]
            [urn=urn:pulumi:xxx::xxxx::Vpc$aws:rds/instance:Instance::xx-xxx-rds]
```

If we change the **name** property to **db_name**
Pulumi preview displays:
```aws:rds:Instance   **-*****-***   replace   [diff: +dbName]```

Pulumi preview --diff displays:
```
warning: name is deprecated: This property has been deprecated. Please use 'dbName' instead.
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:xxx::xxx::pulumi:pulumi:Stack::xxx]
        +-aws:rds/instance:Instance: (replace)
            [id=xxx-xxxx-rdsd5e5988]
            [urn=urn:pulumi:xxx::xxxx::Vpc$aws:rds/instance:Instance::xx-xxx-rds]
```

If we don't set properties **name** or **db_name** Pulumi preview runs without any changes (update/replace) to the RDS instance.[](url)

### Output of `pulumi about`

```
CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.2.0
docker      3.6.1
kubernetes  4.2.0
python      unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/home/xxxxx' version='3.8.10
```

### Additional context

This warning is probably incorrect:
```warning: name is deprecated: This property has been deprecated. Please use 'dbName' instead.```

As there is no 'dbName' property here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/rds/instance.py#L19-L81

My original post can be found here https://github.com/pulumi/pulumi-aws/pull/2686#issuecomment-1729223015

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@fruttu I'm sorry for the trouble. Please ignore the warning for now to avoid the replacement. We are looking at the reasons for the issue with a high priority.

**Comment by iwahbe** [comment]
@fruttu Can you please post some code that reproduces the issue for you. I am unable to reproduce your the issue. I have tried:

```python
rds.Instance("rds",
             name="name", # or db_name="name"
             instance_class="db.t3.micro",
             engine="mysql",
             username="root",
             allocated_storage=16,
             password="FOO-BAR-FIZZ1!2",
             skip_final_snapshot=True)
```

- Experiment 1
  - Steps
    1. Run `pulumi up` on the above program with `pulumi_aws==5.42.0` and `name="name"`.
    2. Run `pulumi up` on the above program with `pulumi_aws==6.2.0` and `name="name"`.
    3. Run `pulumi up` on the above program with `pulumi_aws==6.2.0` and `db_name="name"`.
  - Result
    (2) runs with a warning. No steps cause the db to replace.
- Experiment 2
  - Steps:
    1. Run `pulumi up` on the above program with `pulumi_aws==5.42.0` and `name="name"`.
    2. Run `pulumi up` on the above program with `pulumi_aws==6.2.0` and `db_name="name"`.
  - Result
    No warnings and no changes (except in the `aws` resource).

**Comment by fruttu** [comment]
This is our exact code for an rds instance. The rds instance itself is part of a larger ComponentResource.
```python
        self.rds = rds.Instance(
            backup_retention_period=my_config.require_int("db_backup_retention_period"),
            resource_name=self.my_name,
            db_name=self.my_db_name,
            username=args.db_initial_username,
            password=args.db_initial_password,
            engine="postgres",
            engine_version=my_config.require("db_engine_version"),
            publicly_accessible=False,
            monitoring_interval=my_config.require_int("rds_monitoring_interval"),
            monitoring_role_arn=self.enhanced_monitoring_role.arn,
            multi_az=my_config.require_bool("db_multi_az"),
            allocated_storage=my_config.require_int("db_allocated_storage"),
            instance_class=my_config.require("db_instance_class"),
            storage_type=my_config.require("db_storage_type"),
            storage_encrypted=my_config.require_bool("db_storage_encrypted"),
            db_subnet_group_name=self.rds_subnet_group.name,
            skip_final_snapshot=my_config.require_bool("db_skip_final_snapshot"),
            backup_window=my_config.require("db_backup_window"),
            maintenance_window=my_config.require("db_maintenance_window"),
            apply_immediately=my_config.require_bool("db_apply_immediately"),
            vpc_security_group_ids=self.my_db_security_group_id_list,
            allow_major_version_upgrade=my_config.require_bool("db_allow_major_RDS_version_upgrade"),
            parameter_group_name = deployment + "-custom-postgres13",
            enabled_cloudwatch_logs_exports = ["postgresql"],
            tags=self.my_rds_tags,
            opts=ResourceOptions(
                parent=self.my_vpc
            )
        )
```

This is same as above but with fetched config values.
```python
self.rds = rds.Instance(
    backup_retention_period=35,
    resource_name=self.my_name,
    db_name=self.my_db_name,
    username=args.db_initial_username,
    password=args.db_initial_password,
    engine="postgres",
    engine_version="13.10",
    publicly_accessible=False,
    monitoring_interval=60,
    monitoring_role_arn=self.enhanced_monitoring_role.arn,
    multi_az=False,
    allocated_storage=100,
    instance_class="db.t3.large",
    storage_type="gp2",
    storage_encrypted=True,
    db_subnet_group_name=self.rds_subnet_group.name,
    skip_final_snapshot=True,
    backup_window="01:00-02:00",
    maintenance_window="sun:02:00-sun:03:00",
    apply_immediately=True,
    vpc_security_group_ids=self.my_db_security_group_id_list,
    allow_major_version_upgrade=True,
    parameter_group_name = deployment + "-custom-postgres13",
    enabled_cloudwatch_logs_exports = ["postgresql"],
    tags=self.my_rds_tags,
    opts=ResourceOptions(
        parent=self.my_vpc
    )
)
```

I also think it's worth mentioning that this is an old project, and the RDS instance was created with pulumi-aws <=3.27.0. We executed an update to pulumi-aws 5.42.0 with this code, and when we try to update it to 6.2.0, we are facing this replace issue.

**Comment by atrudeau-vitall** [comment]
+1, same issue using typescript. Old project created with @pulumi/aws 2.57, upgraded to 6.2.0 and experienced the replacement issue. Downgrading to 5.42.0 works

**Comment by iwahbe** [comment]
I have been able to reproduce by starting at an earlier version. Thanks for pointing that out!
