### ISSUE TITLE
Autoscaling Group updates resource but fails program. Inputs and Outputs are out of sync

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-aws#2836]
### What happened?

When an Autoscaling Group has errors in the activity history, changing values on desiredCapacity will change the desiredCapacity on the resource in the cloud. This will leave the inputs on the resource set at the original value while the outputs will be set to the new value.

### Example
```python
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

vpc = awsx.ec2.Vpc(
    "my-vpc",
    number_of_availability_zones=1,
    cidr_block="10.0.0.0/26",
    nat_gateways=1
)

launch_template = aws.ec2.LaunchTemplate("repro-lt",
    name_prefix="repro-lt",
    image_id="ami-0f3769c8d8429942f",
    instance_type="t3.large"
)
config = pulumi.Config()
if config.require_int("step") == 1:
    config_desired_capacity = 28
elif config.require_int("step") == 2:
    config_desired_capacity = 1
else:
    config_desired_capacity = 1

print(f"desired_capacity: {config_desired_capacity}")

group = aws.autoscaling.Group("bar",
    vpc_zone_identifiers=vpc.private_subnet_ids,
    desired_capacity=config_desired_capacity,
    max_size=32,
    min_size=1,
    launch_template=aws.autoscaling.GroupLaunchTemplateArgs(
        id=launch_template.id,
        version="$Latest",
    ))

pulumi.export("vpc_id", vpc.vpc_id)
```

### Output of `pulumi about`

CLI          
Version      3.83.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
cloudinit   1.3.0
datadog     4.17.1
kubernetes  3.30.2
random      4.13.0
tls         4.10.0

Host     
OS       darwin
Version  13.5.2
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
It looks like it was tracked upstream in https://github.com/hashicorp/terraform-provider-aws/issues/29753 which is now solved and shipped at Pulumi Aws 6.0
