### ISSUE TITLE
StackSetInstance fails when deploying to ou with no accounts

### ISSUE THREAD

**Issue by ruben-janssens** [pulumi/pulumi-aws#2839]
### What happened?

I am setting up a new OU and applying an stackset to that OU but the OU has no accounts in it yet as of the moment of creation.
If I create an StackSetInstance at that moment the resource returns an error because no stacks were deployed but when I look in the AWS console the operation was successful.

The reason I do this is because I want to enable automatic deployment on that OU alone.

### Example

Steps to recreate:

1. Create a new OU
2. Create a StackSet (Or use an existing.)
3. Apply an StackSetInstance to that OU with `deployment_targets`
4. Error!

### Output of `pulumi about`

CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
python  3.10.12

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hello @ruben-janssens thank you for reporting this issue.

Could you please provide a code snippet that I can run locally to reproduce the issue?

**Comment by ruben-janssens** [comment]
I think this should be enough. Just some copy paste from my original code.

```
import json
from pulumi import ResourceOptions, InvokeOptions
from pulumi_aws.organizations import OrganizationalUnit, get_organization
from pulumi_aws.cloudformation import StackSet, StackSetAutoDeploymentArgs, StackSetInstance, StackSetInstanceDeploymentTargetsArgs

suspended_ou = OrganizationalUnit(
    "Suspended",
    name="Suspended",
    parent_id=get_organization(opts=InvokeOptions()).roots[0].id
)

role_stackset = StackSet(
            f"MyStackSet",
            name="MyStackSet",
            permission_model = "SERVICE_MANAGED",
            auto_deployment=StackSetAutoDeploymentArgs(
                enabled=True,
                retain_stacks_on_account_removal=False
            ),
            capabilities=["CAPABILITY_NAMED_IAM"],
            template_body=json.dumps(
                {
                    "Resources" : {
                        "Role" : {
                            "Type" : "AWS::IAM::Role",
                            "Properties" : {
                                "RoleName" : "MyUniqueRoleName",
                                "AssumeRolePolicyDocument" : {
                                    "Version" : "2012-10-17",
                                    "Statement" : [
                                        {
                                            "Effect" : "Allow",
                                            "Principal": {
                                                "AWS": "000000000000"
                                            },
                                            "Action": "sts:AssumeRole"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            )),
            opts=ResourceOptions(ignore_changes=["administrationRoleArn"])
        )
        
        StackSetInstance(
           "Instance",
            stack_set_name=role_stackset.name,
            deployment_targets=StackSetInstanceDeploymentTargetsArgs(
                organizational_unit_ids=[suspended_ou.id]
            )
        )
```

**Comment by mikhailshilkov** [comment]
@ruben-janssens Thank you for the snippet! And what is the error that you are getting?

**Comment by ruben-janssens** [comment]
I currently do not have my code open to execute it, but it was something in the trend of not being able to find the ID of the stackset instance. I assume this references a stackset instance for an account but because none exist it throws an error.

**Comment by mikhailshilkov** [comment]
This sounds like it has to be an upstream issue but without a concrete error message it's a bit hard to point out the exact one. Maybe https://github.com/hashicorp/terraform-provider-aws/issues/27877? There are quite a few of those: https://github.com/hashicorp/terraform-provider-aws/issues?q=is%3Aissue+is%3Aopen+aws_cloudformation_stack_set_instance

**Comment by ruben-janssens** [comment]
I ran it again and here is the error:
```
aws:cloudformation:StackSetInstance (MyStackSet):
    error: 1 error occurred:
        * updating urn:pulumi:production::pulumi-project::custom:ResourceStuff$aws:cloudformation/stackSetInstance:StackSetInstance::MyStackSet: 1 error occurred:
        * reading CloudFormation StackSet Instance (MyStackSet,,eu-west-1): unexpected format for ID (MyStackSet,,eu-west-1), expected STACKSETNAME,ACCOUNTID,REGION
```

**Comment by mikhailshilkov** [comment]
@ruben-janssens Thank you! Then it looks like this upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/23349

Please upgrade to 6.x version of Pulumi AWS that includes the fix for it.
