### ISSUE TITLE
'AwaitableGetOrganizationalUnitsResult' object has no attribute 'childrens'

### ISSUE THREAD

**Issue by ruben-janssens** [pulumi/pulumi-aws#2840]
### What happened?

The returned object of the get_organizational_units() function no longer has the childrens property.

### Example

AttributeError: 'AwaitableGetOrganizationalUnitsResult' object has no attribute 'childrens'

### Output of `pulumi about`

CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.2.1
python  3.10.12

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @ruben-janssens 

We fixed the name from `childrens` to `children` in v6 of the provider, it's called out in our Migration Guide: https://www.pulumi.com/registry/packages/aws/how-to-guides/6-0-migration/#property-name-of-organizationsgetorganizationalunits-resource-changed-from-childrens-to-children

Please change your code accordingly.
