### ISSUE TITLE
Documentation contains TODO references

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-aws#2871]
### What happened?

The `upstream-tools/replacements.json` file contains multiple (currently 608) `TODO` specifications. This results in user facing docs containing incomplete/wrong instructions. We should clean these up.

### Example

Example replacement.json line with a TODO: https://github.com/pulumi/pulumi-aws/blob/d1c717283556a7aae44a91f40db23a7ae8b38a34/upstream-tools/replacements.json#L19048

Results in the following user facing docs:
https://www.pulumi.com/registry/packages/aws/api-docs/verifiedaccess/trustprovider/#import

### Output of `pulumi about`

-

### Additional context

Surfaced in: https://github.com/pulumi/pulumi-aws/pull/2870

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
We discussed this in our team's ideation. We identified 3 problems with the current system:
1. Addressing TODOs is done manually, increasing the burden on maintainers of the provider. Most of these can be automated. For example `% TODO import` is unaddressed 78 times. It should be replaced with `% pulumi import`.
2. It is unclear which TODOs need to be addressed. Maintainers only need to fix TODOs when they would appear in docs, but it is hard to understand exactly what will end up in docs.
3. Unaddressed TODOs *should not* end up in user facing docs. They should either be omitted entirely, or they should be block the upgrade until they are addressed.

To resolve these issues, we proposed two solutions. One to be implemented immediately and one to be implemented in the next iteration.

1. (Immediately) Move the responsibility for applying `replacements.json` into the `resources.go.Provider().DocRuleInfo`. Do not replace when the new text is identical to the new text with a TODO. This will cause docs section containing the TODO to be omitted.
2. Apply systematic fixes to reduce the number of omitted docs. If this number gets low enough, we can block releases on unmitigated TODOs.

**Comment by iwahbe** [comment]
https://github.com/pulumi/pulumi-aws/pull/2883 is an example of what it looks like to apply a programatic docs fix.

**Comment by mikhailshilkov** [comment]
Fixed by #2883

**Comment by iwahbe** [comment]
Fixed by https://github.com/pulumi/pulumi-aws/pull/2892.
