### ISSUE TITLE
The eks.NewAddon() in Golang fails with "Invalid or unknown key" when setting ResolveConflictsOnCreate, ResolveConflictsOnUpdate, or ConfigurationValues

### ISSUE THREAD

**Issue by romelbumanlagpb** [pulumi/pulumi-aws#2873]
### What happened?

I’m trying to deploy an EKS Addon using the Golang example on this page (the one that sets up ConfigurationValues) https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/, but it keeps throwing this error below: 

```
Diagnostics:
  aws:eks:Addon (my-cluster-vpc-cni):
    error: aws:eks/addon:Addon resource 'my-cluster-vpc-cni' has a problem: Invalid or unknown key. Examine values at 'Addon.ConfigurationValues'.

```
I also get a similar error when I try to set ResolveConflictsOnCreate and ResolveConflictsOnUpdate.

```
Diagnostics:
  aws:eks:Addon (my-cluster-vpc-cni):
    error: aws:eks/addon:Addon resource 'my-cluster-vpc-cni' has a problem: Invalid or unknown key. Examine values at 'Addon.ResolveConflictsOnUpdate'.
```

### Example

I tried the 4th Golang example code found on this Pulumi site: https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/#example-usage

### Output of `pulumi about`

CLI          
Version      3.87.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       darwin
Version  13.6
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by romelbumanlagpb** [comment]
@justinvp, see code below.  As mentioned above, the code is from the Pulumi site example: https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/#example-usage

`		tmpJSON0, err := json.Marshal(map[string]interface{}{
			"replicaCount": 4,
			"resources": map[string]interface{}{
				"limits": map[string]interface{}{
					"cpu":    "100m",
					"memory": "150Mi",
				},
				"requests": map[string]interface{}{
					"cpu":    "100m",
					"memory": "150Mi",
				},
			},
		})
		if err != nil {
			return err
		}
		json0 := string(tmpJSON0)
		_, err = eks.NewAddon(ctx, "example", &eks.AddonArgs{
			ClusterName:              pulumi.String("mycluster"),
			AddonName:                pulumi.String("coredns"),
			AddonVersion:             pulumi.String("v1.10.1-eksbuild.1"),
			ResolveConflictsOnCreate: pulumi.String("OVERWRITE"),
			ConfigurationValues:      pulumi.String(json0),
		})
`

**Comment by romelbumanlagpb** [comment]
May I ask for a feedback about this ticket, @justinvp, or from anybody whom it got transferred to?

**Comment by jaxxstorm** [comment]
@romelbumanlagpb do you use the pulumi-eks or pulumi-awsx package in the same program? perhaps when creating the cluster or VPC?

**Comment by romelbumanlagpb** [comment]
@jaxxstorm -- I only use github.com/pulumi/pulumi-aws/sdk/v5/go/aws/eks.  Issue occurs only on cluster creation, and not related to VPC.

**Comment by romelbumanlagpb** [comment]
@jaxxstorm -- I need to clarify what I said. When I said cluster creation, I meant I get the error when deploying AWS Addons with these options set: ResolveConflictsOnCreate, ResolveConflictsOnUpdate, or ConfigurationValues.  If I run the deployment without them, it works fine. The code I used came from Pulumi's site: 

```
package main

import (
	"encoding/json"

	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/eks"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		tmpJSON0, err := json.Marshal(map[string]interface{}{
			"replicaCount": 4,
			"resources": map[string]interface{}{
				"limits": map[string]interface{}{
					"cpu":    "100m",
					"memory": "150Mi",
				},
				"requests": map[string]interface{}{
					"cpu":    "100m",
					"memory": "150Mi",
				},
			},
		})
		if err != nil {
			return err
		}
		json0 := string(tmpJSON0)
		_, err = eks.NewAddon(ctx, "example", &eks.AddonArgs{
			ClusterName:              pulumi.String("mycluster"),
			AddonName:                pulumi.String("coredns"),
			AddonVersion:             pulumi.String("v1.10.1-eksbuild.1"),
			ResolveConflictsOnCreate: pulumi.String("OVERWRITE"),
			ConfigurationValues:      pulumi.String(json0),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

**Comment by mikhailshilkov** [comment]
@romelbumanlagpb Apologies for a long pause in response. I haven't managed to reproduce it yet. Do you get this error on preview or update? What is the version of the AWS provider that you use?

**Comment by romelbumanlagpb** [comment]
I get this error on both preview and update. The AWS plugin/provider version I use is v5.4.0.

**Comment by mikhailshilkov** [comment]
> The AWS plugin/provider version I use is v5.4.0.

ResolveConflictsOnCreate was added in 6.0 of the provider. I'm not sure how your code compiles... but my recommendation is to upgrade to the latest version of the provider.

**Comment by romelbumanlagpb** [comment]
This issue was fixed after using a newer version of the AWS plugin/provider.
