### ISSUE TITLE
CallbackFunction comments broken docs link in lambdaMixins

### ISSUE THREAD

**Issue by ernieMrtnz** [pulumi/pulumi-aws#2901]
Hello, I was looking through the `CallbackFunction` code and I saw that this link is now broken: [L270](https://github.com/pulumi/pulumi-aws/blob/ac5e135518b02defbb3cf665c987ab3ffae1503a/sdk/nodejs/lambda/lambdaMixins.ts#L270)

Should it be replaced by this link instead: [https://www.pulumi.com/docs/concepts/inputs-outputs/function-serialization/](https://www.pulumi.com/docs/concepts/inputs-outputs/function-serialization/)

**Comment by mikhailshilkov** [comment]
@ernieMrtnz Yes, thank you for noticing? Do you want to open a PR for it?

**Comment by ernieMrtnz** [comment]
@mikhailshilkov will do!
