### ISSUE TITLE
Add CloudWatchFullAccessV2 managed policy

### ISSUE THREAD

**Issue by ahanoff** [pulumi/pulumi-aws#2913]
## Issue details

> AWS recently added the CloudWatchFullAccessV2 manged IAM policy. This policy grants full access to CloudWatch actions and resources and also more properly scopes the permissions granted for other services such as Amazon SNS and Amazon EC2 Auto Scaling. We recommend that you begin using this policy instead of using CloudWatchFullAccess. AWS plans to deprecate CloudWatchFullAccess in the near future.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/auth-and-access-control-cw.html#managed-policies-cloudwatch-CloudWatchFullAccessV2

### Affected area/feature

> After December 7, 2023, "CloudWatchFullAccess" will no longer be supported.

**Comment by mikhailshilkov** [comment]
Hi @ahanoff thank you for opening an issue. Any chance you would want to contribute a PR for it?

**Comment by rishav-karanjit** [comment]
Hi @mikhailshilkov, I was wondering if I can work on this? I also want to ask where can I start to resolve this issue?

**Comment by JustinTW** [comment]
Hi @mikhailshilkov, I add PR for this issue, let me know if more modify is required.

**Comment by imZack** [comment]
Can anyone help to review the PR #2978?

**Comment by t0yv0** [comment]
Can we possibly close this now?

**Comment by mikhailshilkov** [comment]
Resolved in https://github.com/pulumi/pulumi-aws/pull/2978
