### ISSUE TITLE
False warning on `resolve_conflicts` in `eks.Addon`

### ISSUE THREAD

**Issue by dennispan** [pulumi/pulumi-aws#2937]
### What happened?

Our EKS addon set `resolve_conflicts` to `OVERWRITE`. But it receive this warning:

```
Diagnostics:
  aws:eks:Addon (job-cluster-eks-csi-addon):
    warning: urn:pulumi:prod::compute::aws:eks/addon:Addon::job-cluster-eks-csi-addon verification warning: The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation. Use "resolve_conflicts_on_create" and/or "resolve_conflicts_on_update" instead

  pulumi:pulumi:Stack (compute-prod):
    warning: resolve_conflicts is deprecated: The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation. Use "resolve_conflicts_on_create" and/or "resolve_conflicts_on_update" instead
```

It's puzzling because we are not using `PRESERVE`

### Example

Here's the code:

```
eks.Addon(
    f"{cluster_name}-eks-csi-addon",
    cluster_name=cluster_name,
    addon_name="aws-efs-csi-driver",
    addon_version="v1.7.0-eksbuild.1",
    resolve_conflicts="OVERWRITE",
    service_account_role_arn=oidc_role.arn,
    opts=ResourceOptions(provider=aws_provider, depends_on=cluster),
)
```

### Output of `pulumi about`

```
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.6.1
python  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.11/bin/python3' version='3.11.4'

......


Dependencies:
NAME        VERSION
pip         23.3.1
pre-commit  3.5.0
pulumi-aws  6.6.1
ruff        0.1.3
wheel       0.41.2
yamllint    1.32.0

Pulumi locates its logs in /var/folders/d8/t7tynv650qjbvwvgzdf9k_vm0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dennispan** [comment]
The warning message suggests `resolve_conflicts_on_create` and/or `resolve_conflicts_on_update`. But they don't seem to be valid property of `eks.Addon`

**Comment by dennispan** [comment]
Also worth point out they are supported by [Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#example-update-add-on-usage-with-resolve_conflicts_on_update-and-preserve)

<img width="493" alt="image" src="https://github.com/pulumi/pulumi-aws/assets/14064342/a081b291-f0ac-4cfa-983a-efd61b8a78b9">

**Comment by mikhailshilkov** [comment]
Hi @dennispan  The properties are there: 
- Docs: https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/#resolve_conflicts_on_create_python
- Code: https://github.com/pulumi/pulumi-aws/blob/2cafade7f629b8f8df4a71e02e733fd56820f6e4/sdk/python/pulumi_aws/eks/addon.py#L23-L24

I'm able to preview this program just fine

```py
import json
from pulumi import ResourceOptions, InvokeOptions
import pulumi_aws as aws

aws.eks.Addon(
    "eks-csi-addon",
    cluster_name="cluster_name",
    addon_name="aws-efs-csi-driver",
    addon_version="v1.7.0-eksbuild.1",
    resolve_conflicts_on_create="OVERWRITE",
)
```

So I'm surprised you can't use them. Could you give it another try?

**Comment by dennispan** [comment]
Yes indeed. I might be on a version that's too old. Thank you!
