### ISSUE TITLE
Missing m7a EC2 instance types

### ISSUE THREAD

**Issue by mwcampbell** [pulumi/pulumi-aws#2939]
I noticed that the EC2 m7a instance types haven't yet been added to the list of known instance types.

**Comment by mikhailshilkov** [comment]
@mwcampbell Thank you for letting us know! Any chance you could try to open a PR to add those?

**Comment by rishav-karanjit** [comment]
Hi @mikhailshilkov, if @mwcampbell is not working on this issue. I might be able to work on this. 

Can you point to the file where this issue occurs?

**Comment by rishav-karanjit** [comment]
Hi @mikhailshilkov, I have create a new PR

**Comment by bhurlow** [comment]
this was merged, seems like it would be ok to close the issue

**Comment by iwahbe** [comment]
Fixed by https://github.com/pulumi/pulumi-aws/pull/2965
