### ISSUE TITLE
Unable to Deploy Stack. rpc error: code = Unknown desc = unable to validate AWS credentials

### ISSUE THREAD

**Issue by Luca-Blight** [pulumi/pulumi-aws#2986]
### What happened?

  
 I have verified the credentials to be correct by using the command below:

``` 
aws sts get-caller-identity 
```

Here's the pulumi config file:

```
              config:
            aws:profile: default
            aws:region: us-east-1
```

 The local aws credential file uses [default]
            

    

### Example

Executing 'Pulumi Run' Returns:

Diagnostics:
  pulumi:providers:aws (default_5_42_0):
    error: rpc error: code = Unknown desc = unable to validate AWS credentials.
    Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 400, RequestID: 0b0a3693-2bcd-4110-ac5c-d82205dbc300, api error IncompleteSignature: '/20231114/us-east-1/sts/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 

### Output of `pulumi about`

Zachary_Royals@Juan-MacBook-Pro infra_two % pulumi about
CLI          
Version      3.93.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME            VERSION
aws             5.42.0
aws-apigateway  1.0.1
awsx            1.0.6
docker          3.6.1
python          unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in python: executable='/Users/Zachary_Royals/.pyenv/shims/python3' version='3.11.0'

Current Stack: Luca-Blight/demo_infra/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/Luca-Blight
User           Luca-Blight
Organizations  Luca-Blight
Token type     personal

Dependencies:
NAME                   VERSION
pip                    23.3.1
pulumi-aws-apigateway  1.0.1
pulumi-awsx            1.0.6
setuptools             68.2.2
wheel                  0.41.3

Pulumi locates its logs in /var/folders/0g/9x7mn9056cq7b63r4cs0pzlm0000gn/T/ by st file 'pygraphviz.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Luca-Blight** [comment]
I uninstalled graphviz and get a slightly different error when attempting execute pulumi run:

View in Browser (Ctrl+O): https://app.pulumi.com/Luca-Blight/demo_infra/dev/previews/8008677a-3c07-472e-af62-8abf1d0b1edb
     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  demo_infra-dev  create
     └─ aws:iam:Role      role                       1 error
Diagnostics:
  aws:iam:Role (role):
    error: 1 error occurred:
        * configuring Terraform AWS Provider: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 400, RequestID: c3ff20e6-4733-489b-a58c-02818112a933, api error IncompleteSignature: '/20231114/us-east-1/sts/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256

**Comment by mikhailshilkov** [comment]
Can you obfuscate and share result of `aws sts get-caller-identity` and aws credential file? Please be careful not to post any sensitive information, but it's hard to diagnoze an auth error without looking at your setup.

**Comment by Luca-Blight** [comment]
A few last digits of each property have been altered for security. 
{
    "UserId": "AIDA5PSXE366ME543",
    "Account": "92682196",
    "Arn": "arn:aws:iam::926821965756:user/zack"
}

**Comment by Luca-Blight** [comment]
All settled, it was simply a trailing space in the aws credentials file
