### ISSUE TITLE
Deprecate eks.Cluster defaultAddonsToRemoves property

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3009]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In a recent investigation of the patch conflict (https://github.com/pulumi/pulumi-aws/issues/2732 and https://github.com/pulumi/pulumi-aws/pull/2998) it came up that we use upstream patching to implement default_addon_to_remove property (which pluralizes in Pulumi as defaultAddonToRemoves). This property seems to implement create hooks to remove eks.Cluster addons. 

When trying to write a test for this functionality it appears that it is now redundant:

- provision simple eks.Cluster
- run `aws eks list-addons --cluster-name cluster-b83e45e`
- `# { "addons": [] "`

The cluster does not provision any addons by default. Instead, eks.Addon is a resource that users can opt into to provision the addons that are needed.

Suggest making this property a  no-op, removing upstream patches, pertaining to it, and making it as deprecated to remove in a future version.

**Comment by mikhailshilkov** [comment]
Sounds like a good plan!

**Comment by SharpEdgeMarshall** [comment]
Sorry @t0yv0, I just checked and the creation of a new EKS cluster provision the 3 default addons (vpc-cni, core-dns, kubeproxy) even if the command `aws eks list-addons --cluster-name <my-cluster>` returns an empty list.
If the feature will be removed, how we are supposed to remove default addons?

**Comment by scottslowe** [comment]
My experience mirrors that of @SharpEdgeMarshall; even when I don't explicitly specify add-ons in my Pulumi code I'll still get VPC CNI, kube-proxy, and CoreDNS. If these add-ons are going to be installed by default, then how will users opt-out without this property?

**Comment by t0yv0** [comment]
Thanks @scottslowe and @SharpEdgeMarshall for our feedback! It appears that I incorrectly interpreted the `aws eks list-addons --cluster-name cluster-b83e45e` results as authoritative. If this is being relied on we will keep the option. Thank you!
