### ISSUE TITLE
Support for lambda logs with JSON-structured format

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-aws#3017]
## Issue details

AWS has recently introduced Lambdas with Logs with JSON structured format https://aws.amazon.com/blogs/compute/introducing-advanced-logging-controls-for-aws-lambda-functions/

This is how we can configure it with CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-loggingconfig.html#cfn-lambda-function-loggingconfig-logformat

This would be a great addition, because JSON structured logs are really useful, as we can use them in queries, data aggregation, etc.

**Comment by mikhailshilkov** [comment]
Tracked upstream in https://github.com/hashicorp/terraform-provider-aws/issues/34455, we'll ship it as soon as the upstream is ready

**Comment by leungleoqin** [comment]
> Tracked upstream in [hashicorp/terraform-provider-aws#34455](https://github.com/hashicorp/terraform-provider-aws/issues/34455), we'll ship it as soon as the upstream is ready

Bumping this as it has been released in Terraform AWS provider v5.32.0. Thanks @mikhailshilkov!

**Comment by iwahbe** [comment]
Thanks for bumping this @leungleoqin. This feature is present in the currently released provider, so I'm closing:

https://github.com/pulumi/pulumi-aws/blob/32a25bf835192640fadeba71ddf264123e9473fa/provider/cmd/pulumi-resource-aws/schema.json#L263173-L263176
