### ISSUE TITLE
aws.opensearch.getDomain missing UseOffPeakWindow attribute in autoTuneOptions

### ISSUE THREAD

**Issue by j-mori** [pulumi/pulumi-aws#3030]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Starting from February 16, 2023  AWS [dropped](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/off-peak.html#off-peak-migrate) the support for Auto-Tune maintenance windows in favour of off-peak window.

There is a new API parameter [UseOffPeakWindow](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_AutoTuneOptionsInput.html) to enable the new behaviour which is not currently supported by [pulumi](https://www.pulumi.com/registry/packages/aws/api-docs/opensearch/getdomain/#getdomainautotuneoption)

### Affected area/feature

Opensearch Domains

**Comment by mikhailshilkov** [comment]
I believe this is tracked upstream in https://github.com/hashicorp/terraform-provider-aws/issues/33208

As soon as that ships, we'll include the change as well.

**Comment by mikhailshilkov** [comment]
Closing since it was implemented upstream in https://github.com/hashicorp/terraform-provider-aws/issues/33208
