### ISSUE TITLE
OpenZfsFileSystem.subnetIds is a string, not a string array

### ISSUE THREAD

**Issue by shartte** [pulumi/pulumi-aws#3034]
### What happened?

Trying to create an OpenZfsFileSystem with multiple subnet ids.

### Example

The example in the docs will not compile:

https://www.pulumi.com/registry/packages/aws/api-docs/fsx/openzfsfilesystem/

### Output of `pulumi about`

CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       amazon
Version  2
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v18.18.2'

Additional info:
```
    "@pulumi/aws": "^6.7.0",
    "@pulumi/pulumi": "^3.76.1",
```

### Additional context

The type of `subnetIds` here should be `string[]`, not `string`. The example code on the same page also expects this to be the case.

https://github.com/pulumi/pulumi-aws/blob/a40c588e1160a51301619512299a0650bdc028bb/sdk/nodejs/fsx/openZfsFileSystem.ts#L148

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Only one subnet is currently supported:

> A list of IDs for the subnets that the file system will be accessible from. Exactly 1 subnet need to be provided.

This is a limitation of the upstream provider and we can't do much about it.

The example in our docs is definitely wrong though, so I'll keep the issue open to track fixing this.

**Comment by shmulikah** [comment]
I think these two issues are related - #3106
