### ISSUE TITLE
Secrets Manager can not create key-value secrets

### ISSUE THREAD

**Issue by rkochar** [pulumi/pulumi-aws#3042]
### What happened?

Passing a dict should create a key/value secret. AWS displays the dict in plaintext but choosing the key/value pair gives the error `The secret value can't be converted to key name and value pairs.`

### Example

```python
import pulumi
import pulumi_aws as aws

# Create an AWS Secret for RDS
rds_secret = aws.secretsmanager.Secret("db",
    description="RDS Database secret",
    kms_key_id="alias/aws/secretsmanager",  # default KMS key
)

# Define the secret value
secret_string = {
    "username": "test",
    "password": "test",
    "engine": "mysql",
    "host": "test",
    "port": 3306,
    "dbname": "test",
}

# Create a secret version in AWS Secrets Manager with the secret value
rds_secret_version = aws.secretsmanager.SecretVersion("version",
    secret_id=rds_secret.id,
    secret_string=str(secret_string),
)
```

### Output of `pulumi about`

```
> pulumi about
CLI
Version      3.93.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME            VERSION
aws             6.9.0-alpha.1699538295
aws-apigateway  2.0.0-alpha.1
azure           5.55.0
azure-native    2.16.0
command         0.9.2
gcp             7.0.0
python          unknown
```

### Additional context

The dict is passed as string because str is required according to [documentation](https://www.pulumi.com/registry/packages/aws/api-docs/secretsmanager/secretversion/#secret_string_python).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rkochar** [comment]
Alternatively, how can I do this [tutorial](https://docs.aws.amazon.com/secretsmanager/latest/userguide/create_database_secret.html) "Create an AWS Secrets Manager database secret" on Pulumi in another way? My use case is that I want to use `rds-data` of boto3 ([docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds-data/client/execute_sql.html)) which requires database connection information to be stored in AWS Secrets Manager.

**Comment by rkochar** [comment]
Python can be tricked into creating the key/value pairs by passing `json.dumps(secret_string)` (instead of `str(secret_string)`). Leaving the ticket open because I recommend adding this to documentation.

**Comment by mikhailshilkov** [comment]
@rkochar I'm glad you found a working solution. I think this behavior is largely by design. Which piece of documentation do you think we should adjust to make this more clear? The description of each property is currently shared across all languages, so it's a bit hard to call out language-specific functions in them.

**Comment by rkochar** [comment]
@mikhailshilkov From [documentation](https://www.pulumi.com/registry/packages/aws/api-docs/secretsmanager/secretversion/#inputs) `secret_string: str`. This will simply create a secret version that will not have a meaning in Key-Value pair. To create a Key-Value secret use `json.dumps(<dict>)`. Or maybe this can be added as an example?

**Comment by iwahbe** [comment]
@rkochar To clarify, you are suggesting that we add an example showing that if `secret_string` is valid JSON of type `{ str: str }` then AWS will create a key-value secret. Something like this?

```python
import pulumi
import pulumi_aws as aws

# Create an AWS Secret for RDS
rds_secret = aws.secretsmanager.Secret("db",
    description="RDS Database secret",
    kms_key_id="alias/aws/secretsmanager",  # default KMS key
)

# Define the secret value
secret_string = json.dumps({
    "username": "test",
    "password": "test",
    "engine": "mysql",
    "host": "test",
    "port": 3306,
    "dbname": "test",
})

# Create a secret version in AWS Secrets Manager with the secret value
rds_secret_version = aws.secretsmanager.SecretVersion("version",
    secret_id=rds_secret.id,
    secret_string=secret_string,
)
```

**Comment by rkochar** [comment]
@iwahbe that is correct. Minor point: the json does not have to be str -> str. It can also be int as with port in the example.

I would think the Value of the Key-Value pair be limited to Int, String, Float and maybe Boolean?

**Comment by rkochar** [comment]
The code snippet will also need `import json` at the top.

**Comment by rkochar** [comment]
This is a cleaner version of the code to create a valid KeyValue secret.
```python
from json import dumps
from pulumi_aws.secretsmanager import Secret, SecretVersion

# Create an AWS Secret for RDS
rds_secret = Secret("db",
    description="RDS Database secret",
    kms_key_id="alias/aws/secretsmanager",  # default KMS key
)

# Define the secret value
secret_string = dumps({
    "username": "username",
    "password": "password",
    "engine": "mysql",
    "host": "<endpoint>",
    "port": 3306,
    "dbname": "<db_name>",
})

# Create a secret version in AWS Secrets Manager with the secret value
rds_secret_version = SecretVersion("version",
    secret_id=rds_secret.id,
    secret_string=secret_string,
)
```

Thanks for taking the time to do this.
