### ISSUE TITLE
RDS getInstance(s) is missing Status information

### ISSUE THREAD

**Issue by benlongo** [pulumi/pulumi-aws#3055]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The RDS getInstance(s) API does not yield status information.

### Affected area/feature

RDS

**Comment by iwahbe** [comment]
Hi @benlongo. This function tracks the terraform datasource [aws_db_instances](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_instances). The best way to get that change here is to make the request [here](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=enhancement&projects=&template=02_enhancement.yml&title=%5BEnhancement%5D%3A+).

For my own edification, can you explain how you would use the `status` field. I don't understand the use case for a transient piece of information in a Pulumi program.
