### ISSUE TITLE
SQS Queue docs look wrong

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-aws#3100]
### What happened?

https://www.pulumi.com/registry/packages/aws/api-docs/sqs/queue/

Some of the examples for all languages are listed underneath each other, without a language selection menu.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
This is a duplicate of: https://github.com/pulumi/pulumi-terraform-bridge/issues/926

**Comment by iwahbe** [comment]
This has been fixed with https://github.com/pulumi/pulumi-terraform-bridge/issues/926.
