### ISSUE TITLE
Unable to create Fsx for OpenZFS Multi-AZ file system

### ISSUE THREAD

**Issue by shmulikah** [pulumi/pulumi-aws#3106]
### What happened?

When trying to create Fsx filesystem for OpenZFS with deployment type: Multi-AZ, I received the following error:
```
  aws:fsx:OpenZfsFileSystem (fsxOpenZfs):
    error: 1 error occurred:
        * creating FSx for OpenZFS File System: BadRequest: 1 validation error detected: Value '[subnet-xxxxxxxxxxxxxxxxx,
           subnet-xxxxxxxxxxxxxxxxx]' at 'subnetIds' failed to satisfy constraint: Member must satisfy constraint: 
           [Member must have length less than or equal to 24, Member must have length greater than or equal to 15, 
           Member must satisfy regular expression pattern: ^(subnet-[0-9a-f]{8,})$]
```

### Example

```

fsx_open_zfs = fsx.OpenZfsFileSystem(
                        "fsxOpenZfs",
                        subnet_ids="subnet-xxxxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxxxx",
                        deployment_type="MULTI_AZ_1",
                        throughput_capacity=320,
                        automatic_backup_retention_days=7,
                        storage_capacity=500,        
                        preferred_subnet_id="subnet-xxxxxxxxxxxxxxxxx",
                        disk_iops_configuration=fsx.OpenZfsFileSystemDiskIopsConfigurationArgs(
                            iops=3000,
                            mode="USER_PROVISIONED"
                        ),
                        root_volume_configuration=fsx.OpenZfsFileSystemRootVolumeConfigurationArgs(
                            data_compression_type="LZ4",
                            record_size_kib=128,
                        ),
                        weekly_maintenance_start_time="2:00:00"
                    ),
```

### Output of `pulumi about`

CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.13.0
kubernetes    4.5.4

Host     
OS       darwin
Version  14.1
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.11/bin/python3' version='3.11.5'

Backend        
Name           << REDACTED >>
URL            s3://<< REDACTED >>
User           xxxxxxxx
Organizations  xxxxxxxx
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.13.0
@pulumi/pulumi  3.94.2

### Additional context
Passing a list instead of a string result in a type error.
Passing only single subnet to the subnetIds resulted in another error/;

```
  aws:fsx:OpenZfsFileSystem (fsxOpenZfs):
    error: 1 error occurred:
        * creating FSx for OpenZFS File System: BadRequest: Exactly 2 subnet IDs are required for MULTI_AZ_1.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @shmulikah. Thanks for reporting this. I'm sorry you're hitting this error. We will try to get a fix out soon.

---

This is caused by enforcing a `maxItemsOne: true` field here:

https://github.com/pulumi/pulumi-aws/blob/08401e22ddaab298c9006c17aabb605fcaa87d0e/provider/cmd/pulumi-resource-aws/bridge-metadata.json#L10794-L10797

I see two options for a fix:

1. Remove the `maxItemsOne: true`. This would fix the problem simply, but create a breaking change for all users of this field.
2. Patch this field to split on `,` if present, making `"subnet-xxxxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxxxx"` a valid input.

**Comment by mikhailshilkov** [comment]
@iwahbe Do you know _why_ we have `maxItemsOne: true` on it? I don't see a manual annotation in `resources.go`, so it must be a bridge logic that goes wrong?

**Comment by mikhailshilkov** [comment]
Ah, this was removed upstream in https://github.com/hashicorp/terraform-provider-aws/commit/dba62f6348b72f6246f89c54c5bbb96193887214
