### ISSUE TITLE
Format method: runtime error rendered into docs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3125]
### What happened?

https://www.pulumi.com/registry/packages/aws/api-docs/iot/getendpoint/ see the Java pane.

The code says:

```

public class App {
    public static void main(String[] args) {
        Pulumi.run(App::stack);
    }

    public static void stack(Context ctx) {
        final var example = IotFunctions.getEndpoint();

        var agent = new Kubernetes_pod("agent", Kubernetes_podArgs.builder()        
            .metadata(%!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference))
            .spec(%!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference))
            .build());

    }
}
```

Looks like something is rendering a PANIC into the example.

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@t0yv0 My understanding is that this is a program-gen issue. Should we transfer it to pulumi/pulumi?

**Comment by t0yv0** [comment]
Ah yes, let me run one more check here. I can see if this persists under PULUMI_CONVERT=1 and if so extract a minimal repro in terms of `pulumi convert`.

**Comment by t0yv0** [comment]
Duplicate of https://github.com/pulumi/pulumi-java/issues/1341

**Comment by t0yv0** [comment]
Per investigation in pulumi-java#1341 this may just mean that we're missing a pinned k8s dependency here.

**Comment by t0yv0** [comment]
But we do seem to have it: https://github.com/pulumi/pulumi-aws/blob/upstream-v5.47.0/.ci-mgmt.yaml#L24

Curious. Investigating.

**Comment by t0yv0** [comment]
This was finally fixed in https://github.com/pulumi/pulumi-aws/pull/3891
