### ISSUE TITLE
tier parameter for aws.ec2.VpcIpam

### ISSUE THREAD

**Issue by rkistner** [pulumi/pulumi-aws#3128]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

IPAM resources now supports a new `tier` parameter on AWS, which defaults to "advanced". It would help to support this parameter in Pulumi. As a workaround, this can be edited manually after creating the resource with Pulumi.

See:
 * https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-vpc-address-manager-free-features-tier/
 * https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateIpam.html
 * https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyIpam.html

### Affected area/feature

`aws.ec2.VpcIpam`

**Comment by iwahbe** [comment]
Hi @rkistner. This provider is bridged from the terraform provider `terraform-provider-aws`. `pulumi-aws` will get support for a tier option when they do (tracked in https://github.com/hashicorp/terraform-provider-aws/issues/34616). In the mean time, `pulumi-aws-native` already supports a `tier` parameter: https://www.pulumi.com/registry/packages/aws-native/api-docs/ec2/ipam/.

**Comment by mikhailshilkov** [comment]
Closing as done since it was implemented upstream in https://github.com/hashicorp/terraform-provider-aws/issues/34616
