### ISSUE TITLE
While creating eks using Pulumi in Go all the resources are getting created but node group creation getting failed 

### ISSUE THREAD

**Issue by Rajaguru12** [pulumi/pulumi-aws#3151]

**Comment by iwahbe** [comment]
Hi @Rajaguru12. It sounds like you are trying to report a bug. Can you please post what happened, what you expected to happen, and a pulumi program that we can use to reproduce your bug on our computer?

Please include the output of `pulumi about` so we know what version we are working with.

Thanks
