### ISSUE TITLE
Upgrade terraform-provider-aws upon release of new Terraform AWS Resource(issue #34982)

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-aws#3160]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Upgrade Pulumi-AWS Provider upon the release of [[New Resource]: Add IAM cluster access management API resources](https://github.com/hashicorp/terraform-provider-aws/issues/34982) to add IAM cluster access management API resources

**Comment by t0yv0** [comment]
Thank you for filing this @zbuchheit 

We're currently on par with upstream at 5.31.0 per https://github.com/pulumi/pulumi-aws/pull/3159 and I believe our processes will kick in to ensure a release shortly after upstream releases this. We'll let you know here when this is ready

**Comment by zbuchheit** [comment]
@t0yv0 It looks like the upstream issue was completed but there is an [interesting note](https://github.com/hashicorp/terraform-provider-aws/issues/34982#issuecomment-1866230978) in the comments.

```
Access entry requires a lot more params, most of them optional, compared to what's requested here. I.e.:

resource aws_eks_access_entry example {
  iam_role = arn:aws:iam::012345678910:role/MyRole
  username = "my-other-username" (optional)
  kubernetes_groups = "my-other-group" (optional)
  type = "" (optional, options are: 
    EC2_LINUX
    EC2_WINDOWS
    FARGATE_LINUX
    STANDARD
  )
}
As entries for node bootstrap also need to be supported. Same with authenticationMode, which needs a note that it's a one way street if you go from API_AND_CONFIG_MAP to API. And that should be a new optional param within aws_eks_cluster imho. Wit the default of CONFIG_MAP. That way it's backwards compatible.

Here's a good doc on what is covered by this change: https://github.com/aws/containers-roadmap/issues/185#issuecomment-1863025784
```

**Comment by zbuchheit** [comment]
@t0yv0 fyi on the upstream issue there are comments on the PR that suggest it wasn’t implemented correctly and is still missing things.

**Comment by zbuchheit** [comment]
[PR 35391](https://github.com/hashicorp/terraform-provider-aws/pull/35391) addresses the issues I mentioned.

**Comment by t0yv0** [comment]
Checking up on this @zbuchheit , we caught up with the latest upstream release but the fix in question is https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5340-unreleased still unreleased - will be coming in 5.34.0 upstream or some such new version. I'll update here when that is released and we catch up on our side.

**Comment by zbuchheit** [comment]
5.34.0 appears to be released now

**Comment by t0yv0** [comment]
CC @guineveresaenger --^ thank you

**Comment by iwahbe** [comment]
5.34.0 has been released.

**Comment by zbuchheit** [comment]
thank you all involved!
