### ISSUE TITLE
ServiceQuota reports wrong value on import

### ISSUE THREAD

**Issue by lionello** [pulumi/pulumi-aws#3195]
### What happened?

Trying to move a `aws.servicequotas.ServiceQuota` resource from one stack to another (without triggering a quota increase request), I first deleted the ServiceQuota resources from the source stack using `pulumi state delete <urn>` and then cut-pasted the relevant code to the target stack and issued the import statements:
```
$ pulumi import aws:servicequotas/serviceQuota:ServiceQuota spot-quota8 ec2/L-7212CCBC 
Previewing import (defang-io/dev)

View in Browser (Ctrl+O): https://app.pulumi.com/…

     Type                               Name           Plan       Info
     pulumi:pulumi:Stack                bootstrap-dev             4 warnings
 =   └─ aws:servicequotas:ServiceQuota  spot-quota8    import     

Resources:
    = 1 to import
    74 unchanged

Do you want to perform this import? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::bootstrap::pulumi:pulumi:Stack::bootstrap-dev]

    = aws:servicequotas/serviceQuota:ServiceQuota: (import) 🔒
        [id=ec2/L-7212CCBC]
        [urn=urn:pulumi:dev::bootstrap::aws:servicequotas/serviceQuota:ServiceQuota::spot-quota8]
        [provider=urn:pulumi:dev::bootstrap::pulumi:providers:aws::default_5_42_0::5ce991a8-f364-45a9-834d-033525e58000]
        quotaCode  : "L-7212CCBC"
        serviceCode: "ec2"
        value      : 0
```
The read value `0` is wrong: the current value in the AWS dashboard ("Applied quota value") is 8, which is indeed what is was set to in the original stack.

Doing Import using the `{ import: "ec2/…" }` resource option has the same problem and results in `inputs to import do not match the existing resource`.

### Example

```ts
const spotQuota = config.getNumber("spot-quota"); // 8
if (spotQuota) {
  new aws.servicequotas.ServiceQuota(
    `spot-quota${spotQuota}`,
    {
      quotaCode: "L-7212CCBC",
      serviceCode: "ec2",
      value: spotQuota,
    }
    // { import: "ec2/L-7212CCBC" } same issue as executing `pulumi import …`
  );
}
```

### Output of `pulumi about`

CLI          
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/nix/store/h1h4xhz3dpg09kb6kjk3brc33mfp5kwm-nodejs-18.16.0/bin/node' version='v18.16.0'

Current Stack: defang-io/bootstrap/dev

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:dev::bootstrap::pulumi:pulumi:Stack::bootstrap-dev
pulumi:providers:pulumi                              urn:pulumi:dev::bootstrap::pulumi:providers:pulumi::default
pulumi:providers:aws                                 urn:pulumi:dev::bootstrap::pulumi:providers:aws::default_5_42_0
…

Found no pending operations associated with defang-io/dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/lionello
User           lionello
Organizations  lionello, defang-io
Token type     personal

Pulumi locates its logs in /var/folders/wp/g4m6l2dx3f71wsy8j6l2wwdc0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @lionello. I'm sorry to hear you're having trouble. I am able to reproduce this issue (full repro below).

There is a trivial workaround here. This resource [does not need to be imported](https://www.pulumi.com/registry/packages/aws/api-docs/servicequotas/servicequota/#import). You can simply drop the `{ import: "ec2/L-7212CCBC" }` block and everything should work as expected in AWS.

---

Repro:

```ts
import * as aws from '@pulumi/aws';

const args = {
        quotaCode: "L-7212CCBC",
        serviceCode: "ec2",
        value: 8,
};

// Step 1: Run `pulumi up` on this resource
new aws.servicequotas.ServiceQuota("spot-quota8", args);

// Step 2: Un-comment the next import and run `pulumi up`.

// new aws.servicequotas.ServiceQuota("spot-quota8-dupe", args,
//         { import: `${args.serviceCode}/${args.quotaCode}` });

// Step 3: Observe that there are diffs for both values:
//
// ```
//     Type                               Name              Plan       Info
//     pulumi:pulumi:Stack                ts-dev
// =   ├─ aws:servicequotas:ServiceQuota  spot-quota8-dupe  import     [diff: ~value]; 1 warning
// ~   └─ aws:servicequotas:ServiceQuota  spot-quota8       update     [diff: ~value]
// ```
```

**Comment by lionello** [comment]
Turns out this was my mistake: I was using the wrong account ID :(
