### ISSUE TITLE
aws.identitystore.User has a problem: Attribute must be a list.

### ISSUE THREAD

**Issue by mpuhacz** [pulumi/pulumi-aws#3199]
### What happened?

`name` property turns out to be required. If not provided the returned error is not descriptive enough.

```
Diagnostics:
  aws:identitystore:User (marcin):
    error: aws:identitystore/user:User resource 'marcin' has a problem: Attribute must be a list. Examine values at 'marcin.name'.
```

### Example

This will fail:
```ts
  const user = new aws.identitystore.User("marcin", {
    userName: "marcin",
    displayName: "Marcin",
    emails: {
        primary: true,
        type: "WORK",
        value: "marcin@email.com",
    },
    identityStoreId: sso.identityStoreIds[0],
  });
```

This will work:
```ts
  const user = new aws.identitystore.User("marcin", {
    name: {
      givenName: "Marcin",
      middleName: "Marcin",
      familyName: "Marcin",
    },
    userName: "marcin",
    displayName: "Marcin",
    emails: {
        primary: true,
        type: "WORK",
        value: "marcin@email.com",
    },
    identityStoreId: sso.identityStoreIds[0],
  });
```

### Output of `pulumi about`
```
Dependencies:
NAME            VERSION
@pulumi/aws     6.17.0
@pulumi/pulumi  3.99.0
@types/node     18.19.4
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @mpuhacz. The `name` property is required. It looks like a bug is causing the `name` property to attempt to auto-populate (and marking it as optional). The error message is actually saying (correctly) that the auto-populated value is invalid. We will get a fix out for that soon.
