### ISSUE TITLE
Docs point to non-existant EC2 AMI

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-aws#3208]
### What happened?

Amazon linux 1 reached end of life at the end of 2023 and the AMIs for it are no longer returned by getAmi queries.

This means that a few places in the docs have broken examples:

https://github.com/search?q=repo%3Apulumi%2Fpulumi-aws%20amzn-ami-hvm&type=code

They can be fixed by changing the query to search for amazon linux 2 like in https://github.com/pulumi/pulumi-aws/pull/3207

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
I assume this will be addressed by upstream. Do you think action is needed here?

**Comment by VenelinMartinov** [comment]
Yeah, I think you're right.
