### ISSUE TITLE
Endpoints option missing from valid config options in docs

### ISSUE THREAD

**Issue by lakkeger** [pulumi/pulumi-aws#3213]
### What happened?

As the title says, the docs are missing the `aws:endpoints` option, even though the upstream terraform provider has them ([here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#endpoints)). However using the aws package (>6.12.0) this option is a valid config.

### Example
Unrelated as the issue is with the docs.

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.17.0
awsx    2.4.0
docker  4.5.0
local   1.2.1
python  unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/Users/lakkeger/Workspace/pulumi/ecs-sample/venv/bin/python3' version='3.11.5'

Backend
Name           lakkeger-MacBook-Pro.local
URL            file:///Users/lakkeger/Workspace/pulumi/ecs-sample
User           lakkeger
Organizations
Token type     personal

Dependencies:
NAME          VERSION
pip           23.3.2
pulumi-awsx   2.4.0
pulumi-local  1.2.1
setuptools    69.0.3
wheel         0.42.0

Pulumi locates its logs in /var/folders/8x/dyq5jnvj7md_z7km73gn496m0000gn/T/ by default
warning: Failed to get information about the current stack: No current snapshot
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @lakkeger. Thanks for reporting this issue.

Related: https://github.com/pulumi/pulumi-terraform-bridge/issues/1585
