### ISSUE TITLE
Cognito User Pool, tags don't exist

### ISSUE THREAD

**Issue by christrt9** [pulumi/pulumi-aws#3231]
### What happened?

I try to create Cognito User Pool but in AWS the tags don't show, how can i add them in AWS

### Example

```
user_pool = cognito.UserPool(name,
            name=name,
            schemas=[
                # Make the built-in 'email' attribute required
                {
                    'attributeDataType': 'String',
                    'developerOnlyAttribute': False,
                    'mutable': True,
                    'name': 'email',
                    'required': True,
                    'stringAttributeConstraints': {
                        'maxLength': '2048',
                        'minLength': '1'
                    }
                }
            ],
            tags={
                "Name": name,
                "environment": "dev",
            } 
        )
```

### Output of `pulumi about`

CLI
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.43.0
python  unknown

Host     
OS       linuxmint
Version  21
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.12'

Current Stack: xxxx/pulumi-xxxx/dev

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:dev::xxx::pulumi:pulumi:Stack::xxxx
pulumi:providers:aws                       urn:pulumi:dev::xxx::pulumi:providers:aws::default_5_43_0
aws:cognito/userPool:UserPool              urn:pulumi:dev::xxx::aws:cognito/userPool:UserPool::xxx
aws:cognito/userPoolDomain:UserPoolDomain  urn:pulumi:dev::xxx::aws:cognito/userPoolDomain:UserPoolDomain::xxx

Found no pending operations associated with xxxx/xxx

Dependencies:
NAME        VERSION
pip         23.3.1
pulumi-aws  5.43.0
setuptools  69.0.2
wheel       0.42.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @r00t9. I'm sorry things aren't working as you expected. Just to clarify, the program runs, but the tags described don't show up in the console?

**Comment by r00t9** [comment]
@iwahbe  Yes it create ok in the AWS, but in aws console tags is empty

**Comment by iwahbe** [comment]
Thanks for confirming @r00t9.

**Comment by t0yv0** [comment]
Working for me on latest.

```
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.52.0
language  python  unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in python: executable='/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-3231/venv/bin/python' version='3.10.13'

Current Stack: anton-pulumi-corp/aws-3231/devpy

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:devpy::aws-3231::pulumi:pulumi:Stack::aws-3231-devpy
pulumi:providers:aws           urn:pulumi:devpy::aws-3231::pulumi:providers:aws::default_6_52_0
aws:cognito/userPool:UserPool  urn:pulumi:devpy::aws-3231::aws:cognito/userPool:UserPool::u_p


Found no pending operations associated with devpy

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

Dependencies:
NAME        VERSION
pip         24.2
pulumi_aws  6.52.0
setuptools  75.1.0
wheel       0.44.0

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default

```
