### ISSUE TITLE
aws.s3.Bucket doesn't behave the same way than aws_s3_bucket terraform resource

### ISSUE THREAD

**Issue by pgdagenais** [pulumi/pulumi-aws#3245]
### What happened?

Hello!

In our setup we are using the aws provider to create a bucket on a Ceph environment, this is achieved with using the `endpoints` option.

When using the `aws.s3.Bucket` resource it is not working correctly. We are getting errors on the website configuration as this is not available in Ceph. 

```
  aws:s3:Bucket (test-bucket):
    error: 1 error occurred:
    	* creating urn:pulumi:dev::test::aws:s3/bucket:Bucket::test-bucket: 1 error occurred:
    	* error getting S3 Bucket website configuration: MethodNotAllowed:
    	status code: 405, request id: tx0000000000000007ff406-00659ed8f9-66559-apac, host id:
```

This is explained in detail in this terraform-provider-aws issue: https://github.com/hashicorp/terraform-provider-aws/issues/14645

As part of this issue, a MR was created to allow Ceph and other application to use the provider: https://github.com/hashicorp/terraform-provider-aws/pull/23278

This was achieved by ignoring specific errors on specific options.

This error cannot be reproduced when using `aws.s3.bucketV2` (see Example).

Is that the expected behaviour from these 2 different resources?

As stated in [this blog post](https://www.pulumi.com/blog/announcing-v5.0.0-of-the-pulumi-aws-provider/), it seems that the BucketV2 should be the one we use. Could I help by contributing some documentation update to try and avoid this issue?

Thanks!

### Example

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const cephProvider = new aws.Provider("ceph", {
    accessKey: pulumi.secret("ACCESS_KEY"),
    secretKey: pulumi.secret("SECRET_KEY"),
    skipCredentialsValidation: true,
    skipMetadataApiCheck: true,
    skipRegionValidation: true,
    skipRequestingAccountId: true,
    region: "us-east-1",
    s3UsePathStyle: true,
    insecure: true,
    endpoints: [
      {s3: pulumi.secret("<SOME_CEPH_IP>"),}
    ],
  })

const bucket = new aws.s3.Bucket("test-bucket", {}, { provider: cephProvider });
```

Using this with a Ceph endpoint will cause this error:

```
  aws:s3:Bucket (test-bucket):
    error: 1 error occurred:
    	* creating urn:pulumi:dev::test::aws:s3/bucket:Bucket::test-bucket: 1 error occurred:
    	* error getting S3 Bucket website configuration: MethodNotAllowed:
    	status code: 405, request id: tx0000000000000007ff406-00659ed8f9-66559-apac, host id:
```

With this error, the bucket is created correctly, but pulumi is not able to refresh:

```
Previewing refresh (dev):
     Type                     Name         Plan        Info
     pulumi:pulumi:Stack      test-dev                 1 error
 ~   ├─ aws:s3:Bucket         test-bucket  refresh     1 error
     └─ pulumi:providers:aws  ceph

Diagnostics:
  pulumi:pulumi:Stack (test-dev):
    error: preview failed

  aws:s3:Bucket (test-bucket):
    error: Preview failed: refreshing urn:pulumi:dev::test::aws:s3/bucket:Bucket::test-bucket: 1 error occurred:
    	* error getting S3 Bucket website configuration: MethodNotAllowed:
    	status code: 405, request id: tx0000000000000007ffe40-00659edb3d-66559-apac, host id:
```

-----

Using the same configuration than above, but replacing `aws.s3.Bucket` by `aws.s3.BucketV2`, it works: 

```typescript
...

const bucket = new aws.s3.BucketV2("test-bucket", {}, { provider: cephProvider });
```

Refresh now works:

```
Previewing refresh (dev):
     Type                     Name         Plan
     pulumi:pulumi:Stack      test-dev
     ├─ pulumi:providers:aws  ceph
     └─ aws:s3:BucketV2       test-bucket

Resources:
    3 unchanged

Refreshing (dev):
     Type                     Name         Status
     pulumi:pulumi:Stack      test-dev
     ├─ pulumi:providers:aws  ceph
     └─ aws:s3:BucketV2       test-bucket

Resources:
    3 unchanged

Duration: 1s
```

### Output of `pulumi about`

```bash
CLI
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.18.0
awsx    2.4.0
docker  4.5.0
docker  3.6.1
nodejs  unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/pdagenais/.asdf/shims/node' version='v18.17.0'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           mbp
URL            file://~
User           pdagenais
Organizations
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.18.0
@pulumi/awsx    2.4.0
@pulumi/pulumi  3.100.0
@types/node     18.19.6

Pulumi locates its logs in /var/folders/9l/nw87v1wj1rbct1f86lvm91_r0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pgdagenais** [comment]
Hey @iwahbe !

I just opened #3277 to update the docs!

Maybe just so I understand how the whole process works, I saw that most of the documentation is also part of the direct code equivalent, for example: https://github.com/pulumi/pulumi-aws/blob/b3675bdf87e4dbd1536b6b88dd23881f2e8aaba7/sdk/nodejs/s3/bucket.ts#L16

Are these updated by the patches and then it what it shows online? I am just trying to understand here so I can help in the future.

Thank you very much!

**Comment by iwahbe** [comment]
After we update the patch, we run a generate step (`make tfgen`) that applies the patch and inserts the correct documentation into the provider schema (`provider/cmd/pulumi-resource-aws/schema.json`). This is what is used to generate online docs. We run another generate step (`make build_sdks`) to put the generated schema into each SDK.
