### ISSUE TITLE
`defaultTags` causes the `tagsAll` output in resources to be created and marked as `[secret]`

### ISSUE THREAD

**Issue by bob-bins** [pulumi/pulumi-aws#3265]
### What happened?

See Title. This behavior is undesired because it taints anything that touches the Stack Output as `[secret]`

### Example

Stack config:
```
  aws:defaultTags:
    tags:
      managedBy: Pulumi
```

index.ts:
```
import { Bucket } from '@pulumi/aws/s3'
new Bucket('asdf')
```

`pulumi up` output:
```
    + aws:s3/bucket:Bucket: (create)
        [urn=urn:pulumi:eks-eng-user-usw2::eks::aws:s3/bucket:Bucket::asdf]
        [provider=urn:pulumi:eks-eng-user-usw2::eks::pulumi:providers:aws::default_6_17_0::2cb09fa4-29fc-4648-8c83-a4e2bd484b8a]
        acl         : "private"
        bucket      : "asdf-6231ce5"
        forceDestroy: false
        tags        : {
            managedBy: "Pulumi"
        }
        tagsAll     : [secret]
```

### Output of `pulumi about`

```

CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v19.8.1'
```

### Additional context

```
"@pulumi/aws": "^6.17.0",
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @bob-bins. Thanks for letting us know that this is a problem for you. We are aware that `tagsAll` is secret, but knowing that it is impacting users helps us prioritize fixing it.

**Comment by t0yv0** [comment]
Can you use tags instead of tagsAll in your program? One possibility for us is to deprecate tagsAll completely at some point. In the Pulumi projection the tags output is already the union of defaultTags and the tags input so tagsAll is redundant.

**Comment by t0yv0** [comment]
In fact it's already deprecated .e.g.

https://github.com/pulumi/pulumi-aws/blob/master/sdk/go/aws/alb/loadBalancer.go#L231

**Comment by filip-taxamo** [comment]
@t0yv0 but @bob-bins is not specifying`tagsAll`, it's the provider that is setting it.

We are having the same issue.

**Comment by t0yv0** [comment]
@filip-taxamo can you please help me understand what the issue is with a sample program and desired vs actual behavior? 

"This behavior is undesired because it taints anything that touches the Stack Output as [secret]"

What does this mean ?

**Comment by filip-taxamo** [comment]
> @filip-taxamo can you please help me understand what the issue is with a sample program and desired vs actual behavior?

We're doing some postprocessing of the state exports and spurious and opaque changes to `tagsAll` is throwing it off.

**Comment by t0yv0** [comment]
Since we've deprecated tagsAll we're considering removing it in a future version. Would that work for your use case? Would it be possible to exclude tagsAll from the exports post-processing as a temporary workaround? 

We cannot at the moment simply remove secret masking behavior because it results in secret leaks through copying secret material from tags to tagsAll, and until the root cause of that is addressed which is fairly involved we continue carrying this workaround.

**Comment by gunzy83** [comment]
I just found this as well after testing a new typescript package on an existing stack (the package deals with the AWS provider and its tag configuration, standardising it across our org). We are just changing values in `defaultTags` and the spurious diffs for `tagsAll` had me hunting around the program looking for where a secret might be infecting outputs but `tags` are showing the correct values.

I would vote for deprecating `tagsAll` ASAP.

**Comment by t0yv0** [comment]
Thank you for elaborating this! Removing tagsAll may break programs that still read from it but perhaps what we can do is remove the secret marker from tagsAll while adding warnings for cases where someone is inadvertently pushing secret material into tags (which leaks via tagsAll). CC @iwahbe @VenelinMartinov
