### ISSUE TITLE
Unable to Select Serverless v2 in aws:rds/cluster for Aurora MySQL 3.x database engine (MySQL 8.0-compatible version)

### ISSUE THREAD

**Issue by adelkedjour** [pulumi/pulumi-aws#3364]
### Description:
I am currently facing an issue while attempting to configure the `aws:rds/cluster` resource in Pulumi for an Aurora MySQL 3.x database engine cluster (MySQL 8.0-compatible version). Specifically, I am unable to select the `Serverless v2` engine mode even when setting `engineMode` to `provisioned` and providing the `serverlessv2ScalingConfiguration` attribute.

### Expected Behavior:
I expect to be able to create a **Serverless v2** AWS RDS cluster instance for Aurora MySQL 3.x database engine (MySQL 8.0-compatible version) when following the documented guidance.

### Example

```ts
// Relevant Pulumi code snippet
const cluster = new aws.rds.Cluster("aurora-cluster-mysql8-serverlessv2", {
    engine: "aurora-mysql",
    engineVersion: "8.0.mysql_aurora.3.05.1", // Specify the compatible Aurora MySQL version
    engineMode: "provisioned", // Set to 'provisioned' as per documentation
    masterUsername: "masteruser",
    masterPassword: "yourpassword", // Change to a secure password
    dbSubnetGroupName: "your-db-subnet-group", // The DB subnet group name
    skipFinalSnapshot: true,
    backupRetentionPeriod: 1, // Number of days to retain backups
    vpcSecurityGroupIds: ["sg-xxxxxxxx"], // Update with your VPC security group ID

    serverlessv2ScalingConfiguration: {
        minCapacity: 0.5, // Specify the minimum capacity units for the cluster
        maxCapacity: 64,   // Specify the maximum capacity units for the cluster
    },
});

// Export the cluster's endpoint for easy access
export const endpoint = cluster.endpoint;

```

### Output of `pulumi about`

No error, but the DB instance it's been created not as Serverless v2. If I try to use the `engineMode: serverlessv2` I got this error:

```
error: aws:rds/cluster:Cluster resource 'aurora-cluster-mysql8-serverlessv2' has a problem:
    expected engine_mode to be one of ["global" "multimaster" "parallelquery" "provisioned" "serverless"],
    got serverlessv2. Examine values at 'aurora-cluster-mysql8-serverlessv2.engineMode'.
```

### Additional context

Pulumi Version: `v3.103.1`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by adelkedjour** [comment]
> Hi @adelkedjour, this looks specific to the AWS provider so I'm going to transfer to the AWS repo for further triage.

Thanks @justinvp .

**Comment by iwahbe** [comment]
Hi @adelkedjour. I couldn't find this in our docs, but I believe that you also need to provision an associated `aws.rds.ClusterInstance` with `  instanceClass: "db.serverless"` set.

See https://www.pulumi.com/registry/packages/aws/api-docs/rds/cluster/#rds-serverless-v2-cluster:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const exampleCluster = new aws.rds.Cluster("exampleCluster", {
    clusterIdentifier: "example",
    engine: "aurora-postgresql",
    engineMode: "provisioned",
    engineVersion: "13.6",
    databaseName: "test",
    masterUsername: "test",
    masterPassword: "must_be_eight_characters",
    serverlessv2ScalingConfiguration: {
        maxCapacity: 1,
        minCapacity: 0.5,
    },
});
const exampleClusterInstance = new aws.rds.ClusterInstance("exampleClusterInstance", {
    clusterIdentifier: exampleCluster.id,
    instanceClass: "db.serverless",
    engine: exampleCluster.engine,
    engineVersion: exampleCluster.engineVersion,
});
```

Let me know if that works. I'll leave this issue open to track the docs fix.

**Comment by adelkedjour** [comment]
Hi @iwahbe go to line 118 in `https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/rds/cluster.ts` it's documented there. I think I haven't added `instanceClass: "db.serverless"`  instead in my case I did choose `instanceClass: InstanceType.R5_Large`. I will update my code and check it out and let you know if it worked. If yes I think `InstanceType` enum class need to have type `db.serverless`. Thanks :)

**Comment by adelkedjour** [comment]
> Hi @adelkedjour. I couldn't find this in our docs, but I believe that you also need to provision an associated `aws.rds.ClusterInstance` with ` instanceClass: "db.serverless"` set.
> 
> See https://www.pulumi.com/registry/packages/aws/api-docs/rds/cluster/#rds-serverless-v2-cluster:
> 
> ```ts
> import * as pulumi from "@pulumi/pulumi";
> import * as aws from "@pulumi/aws";
> 
> const exampleCluster = new aws.rds.Cluster("exampleCluster", {
>     clusterIdentifier: "example",
>     engine: "aurora-postgresql",
>     engineMode: "provisioned",
>     engineVersion: "13.6",
>     databaseName: "test",
>     masterUsername: "test",
>     masterPassword: "must_be_eight_characters",
>     serverlessv2ScalingConfiguration: {
>         maxCapacity: 1,
>         minCapacity: 0.5,
>     },
> });
> const exampleClusterInstance = new aws.rds.ClusterInstance("exampleClusterInstance", {
>     clusterIdentifier: exampleCluster.id,
>     instanceClass: "db.serverless",
>     engine: exampleCluster.engine,
>     engineVersion: exampleCluster.engineVersion,
> });
> ```
> 
> Let me know if that works. I'll leave this issue open to track the docs fix.

Hi @iwahbe I can confirm that it worked by setting `instanceClass` to `db.serverless`. Thank you for assistance :)
