### ISSUE TITLE
Error updating WAF WebAcl after partial failure

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi-aws#337]
After this failure:

```
  aws:waf:WebAcl: [...]
    error: Plan apply failed: updating urn:pulumi:[...]::aws:waf/webAcl:WebAcl::[...]: Error Updating WAF ACL: Error Updating WAF ACL: WAFNonexistentItemException: The referenced item does not exist.
```

It would appear that future updates to this resource (using partial state saved after the failure) results in a panic:

```
 *  pulumi:pulumi:[...] running 2 info messages. info: panic: runtime error: index out of range
```

It's possible here that the partial state returned by the provider wasn't a valid input for this resource.

**Comment by swgillespie** [comment]
Now that https://github.com/pulumi/pulumi/pull/2035 has landed this is less severe, although this resource does still need to be refreshed in order to be updated or deleted again.

**Comment by lukehoban** [comment]
There is no remaining Pulumi bug here.  

If we fix https://github.com/pulumi/pulumi-terraform/issues/57, that would help here.

Other than that, the only remaining possible change we might want is to update the `WebAcl` provider implementation to better support workflows without refresh.
