### ISSUE TITLE
ScaleInProtectedInstances not available in the Typescript SDK

### ISSUE THREAD

**Issue by rlukata** [pulumi/pulumi-aws#3422]
### What happened?

The typescript SDK doesn't have the option to use ScaleInProtectedInstances in the preferences of ASG instanceRefresh.

### Example

```
asgArgs.instanceRefresh = {
        strategy: 'Rolling',
        preferences: {
            autoRollback: true,
            minHealthyPercentage: 50,
            scaleInProtectedInstances: true  <--- this is not an option
        },
        triggers: ['tag'],
    };
```

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Can you provide more details. I see a `scaleInProtectedInstances` field:

https://github.com/pulumi/pulumi-aws/blob/6cef7e74e328f4d104032b58126c084ca4ffc2bd/sdk/nodejs/types/input.ts#L8205-L8208

Where do you think you should be able to find it?

**Comment by rlukata** [comment]
> Can you provide more details. I see a `scaleInProtectedInstances` field:
> 
> https://github.com/pulumi/pulumi-aws/blob/6cef7e74e328f4d104032b58126c084ca4ffc2bd/sdk/nodejs/types/input.ts#L8205-L8208
> 
> Where do you think you should be able to find it?

I guess it wasn't an option in v5 of the SDK but now that I've updated to v6 I can see the option. Apologies for not checking this beforehand 😓 . Closing and thank you for your reply.
