### ISSUE TITLE
more readable iam details

### ISSUE THREAD

**Issue by rkochar** [pulumi/pulumi-aws#3450]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
After `pulumi up`, checking details of IAM looks like picture below. Would be great to make it readable.

![image](https://github.com/pulumi/pulumi-aws/assets/44548936/e99904e2-d30a-4f0a-8e66-555ae585e49f)

Thanks!

**Comment by VenelinMartinov** [comment]
Hi @rkochar, sorry you've had issues with this and thanks for reporting!
Could you please add which versions of the provider and the pulumi cli are you using? Running `pulumi about` should report that.

This looks similar to https://github.com/pulumi/pulumi/issues/13981

**Comment by rkochar** [comment]
@VenelinMartinov the other issue looks similar indeed.
```
> pulumi about
CLI
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME            VERSION
aws             6.10.0

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.11.7'
```
