### ISSUE TITLE
ConfigurationProfile outputs its id concatinated with the application id

### ISSUE THREAD

**Issue by GeoffMillerAZ** [pulumi/pulumi-aws#3467]
### What happened?

When a `ConfigurationProfile` resource is created and then it's `id` parameter is accessed, it returns `<profileID>:<applicationID>`. Example: `d80dybh:dsmvkxm`.

### Example

```typescript
import * as aws from "@pulumi/aws";

// Create an AWS AppConfig Application
const app = new aws.appconfig.Application("myApp", {
    name: "my-appconfig-application",
    // Optional: You can add a description and tags
    // description: "My AppConfig Application",
    // tags: {
    //     Environment: "Production",
    // },
});

// Create an AWS AppConfig Configuration Profile within the Application
const profile = new aws.appconfig.ConfigurationProfile("myProfile", {
    applicationId: app.id,
    name: "my-configuration-profile",
    locationUri: "hosted", // Specify the location of the configuration data
    // Optional: You can specify the type and description
    // type: "AWS.Freeform",
    // description: "My Configuration Profile",
});

// Create an AWS AppConfig Hosted Configuration Version referencing the Application and Configuration Profile
const configVersion = new aws.appconfig.HostedConfigurationVersion("myConfigVersion", {
    applicationId: app.id,
    configurationProfileId: profile.id,
    content: JSON.stringify({ key: "value" }), // The content of the configuration version
    contentType: "application/json", // The content type, e.g. application/json, text/plain, etc.
    // Optional: You can add a description
    // description: "Version 1 of configuration",
});

// Export the IDs of the created resources
export const appId = app.id;
export const profileId = profile.id;
export const configVersionId = configVersion.id;
```

This returns the following error:
```
  aws:appconfig:HostedConfigurationVersion (myConfigVersion):
    error: 1 error occurred:
        * creating AppConfig HostedConfigurationVersion for Application (knbgttn): BadRequestException: 1 validation error detected: Value '1qjchp3:knbgttn' at 'configurationProfileId' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-z0-9]{4,7}
    {
      RespMetadata: {
        StatusCode: 400,
        RequestID: "ad2545f7-d56a-4c0c-a744-2cb76f161af5"
      },
      Message_: "1 validation error detected: Value '1qjchp3:knbgttn' at 'configurationProfileId' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-z0-9]{4,7}"
    }
```

Updating the code to split the string and keep the value to the left of the `:` works because the value to the left actually is the profile ID. The rest of the string is the application ID which should not be returned on this parameter.
```typescript
const configVersion = new aws.appconfig.HostedConfigurationVersion("myConfigVersion", {
...
    configurationProfileId: pulumi.all([profile.id]).apply(([profileId]) => profileId.split(':')[0]),
...
});
```

The outputs are:
```
Outputs:
  - appId          : "knbgttn"
  - configVersionId: "knbgttn/1qjchp3/1"
  - profileId      : "1qjchp3:knbgttn"
```

### Output of `pulumi about`

CLI          
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.23.0
awsx    2.5.0
docker  4.5.1
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.2.0'

Current Stack: GeoffMillerAZ/t4764/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/GeoffMillerAZ
User           GeoffMillerAZ
Organizations  GeoffMillerAZ, team-ce
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.107.0
@types/node     18.19.18
@pulumi/aws     6.23.0
@pulumi/awsx    2.5.0

Pulumi locates its logs in /var/folders/39/pjbcs1t54djdg68ptpxw5q880000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @GeoffMillerAZ. I think this is a case of a badly field. `id` is the identity of the resource to the provider. If you want the profile id, you need to use `.configurationProfileId`:


```patch
 const configVersion = new aws.appconfig.HostedConfigurationVersion("myConfigVersion", {
 ...
-    configurationProfileId: pulumi.all([profile.id]).apply(([profileId]) => profileId.split(':')[0]),
+    configurationProfileId: profile.configurationProfileId,
 ...
 });
