### ISSUE TITLE
Kinesis Firehose ExtendedS3Configuration support for FileExtension

### ISSUE THREAD

**Issue by dygfloyd** [pulumi/pulumi-aws#3479]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
[Kinesis Firehose ExtendedS3Configuration](https://www.pulumi.com/registry/packages/aws/api-docs/kinesis/firehosedeliverystream/#extended-s3-destination-with-dynamic-partitioning) current does not support the optional FileExtension property. This property is described in the [AWS Destination Settings documentation](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-s3). This causes issues when you are trying to import files in S3 into other systems that require specific file extensions. For example, Datadog log rehydration only supports files with the extension `.json.gz`.

**Comment by iwahbe** [comment]
Hi @dygfloyd. Thanks for letting us know about this. The `pulumi-aws` provider is bridged from https://github.com/hashicorp/terraform-provider-aws. The best way to get this feature added is to open an issue [there](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=enhancement&projects=&template=02_enhancement.yml&title=%5BEnhancement%5D%3A+).

**Comment by dygfloyd** [comment]
I posted a feature request in that repo as well. https://github.com/hashicorp/terraform-provider-aws/issues/35989
Unfortunately, I am unfamiliar with the terraform provider so if anyone has any details they can add to the request, that would be great.

**Comment by dygfloyd** [comment]
Looks like there was a duplicate ticket and this feature was added 3 days ago: 
https://github.com/hashicorp/terraform-provider-aws/pull/35969

**Comment by iwahbe** [comment]
Great. Then `pulumi-aws` will pick up the feature shortly after terraform-provider-aws's next release.

**Comment by mikhailshilkov** [comment]
Closing as implemented upstream in https://github.com/hashicorp/terraform-provider-aws/issues/35957
