### ISSUE TITLE
Lambda callback value is required by should be optional

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#348]
The callback to a lambda should be okay to call with only a single value (the error).  Currently that is not allowed because the signature is:

```
export declare type Callback<E, R> = (event: E, context: Context, callback: (error: any, result: R) => void) => Promise<R> | void;
```

instead of

```
export declare type Callback<E, R> = (event: E, context: Context, callback: (error: any, result?: R) => void) => Promise<R> | void;
```

**Comment by CyrusNajmabadi** [comment]
I think technically both could be optional.  you can just do `callback()` to indicate success (with no result), right?

**Comment by CyrusNajmabadi** [comment]
have confirmed with the docs.
