### ISSUE TITLE
s3.BucketObject() fails after denying s3:GetObject on IAM role

### ISSUE THREAD

**Issue by ba1ajinaidu** [pulumi/pulumi-aws#3483]
### What happened?

I create a bucket and upload objects to it using aws.s3.BucketObject(), it started to throw error after I changed permission on the IAM role used to create the bucket to deny `s3:GetObject`. Does s3.BucketObject() require GetObject permission to identify the drift or to read metadata?

### Example

```
const sourceBucketObject = new aws.s3.BucketObject("data-connector-sort-bucket-object", {
        bucket: sourceBucket,
        key: "sort_script.py",
        source: new pulumi.asset.FileAsset(scriptPath),
        etag: fileHash,
        sourceHash: fileHash,
    }, { provider: awsProvider });
```

The IAM role used to create the BucketObject has a policy to deny "s3:GetObject"

### Output of `pulumi about`

```
CLI
Version      3.101.1
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.20.1
aws         5.43.0
docker      4.5.1
eks         2.2.1
kubernetes  4.7.1
nodejs      unknown
random      4.15.1
tls         4.11.1

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/nix/store/xr7qgwzvymigkn4lhz8hzdky765m32r4-nodejs-20.11.1/bin/node' version='v20.11.1'

Dependencies:
NAME                VERSION
glob                10.3.10
@pulumi/random      4.15.1
fp-ts               2.16.2
@pulumi/postgresql  3.10.1
@types/netmask      1.0.30
ts-pattern          5.0.6
@pulumi/eks         2.2.1
@pulumi/kubernetes  4.7.1
@types/glob         8.1.0
netmask             2.0.2
vite                5.0.12
@pulumi/kafka       3.6.0
cidr-tools          6.4.2
ts-md5              1.3.1
@pulumi/docker      4.5.1
immer               10.0.3
ts-node             10.9.2
@pulumi/aws         5.43.0
@pulumi/cloudflare  5.19.0
@pulumi/command     0.5.2
@pulumi/tls         4.11.1
vitest              0.33.0
@pulumi/pulumi      3.103.1
@types/jsbn         1.2.33
typescript          5.3.3

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @ba1ajinaidu. I'm pretty sure that `aws.s3.BucketObject` does need permission to get the objects from the bucket it is acting on.

`aws.s3.BucketObject` manages the lifecycle of a bucket object. That means it needs to be able to check if the object it is managing exists and validate that the data matches what it should.

This access is needed for Pulumi's update and refresh operations at the very least.

**Comment by ba1ajinaidu** [comment]
@iwahbe It’s possible (at least in Pulumi’s model, which doesn’t have bi-directional reconciliation) to detect drift without `s3:GetObject` permission, because it would be detecting drift between Pulumi’s state and the new changes. We can store a checksum in Pulumi’s state and compare that to the checksum of the object the user is trying the upload. If they are the same, just skip the upload.
