### ISSUE TITLE
Add support for custom authorizes in aws.apigateway.x.API

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#352]
We’ve heard several requests for supporting custom authorizers from cloud.API/aws.apigateway.x.API.

**Comment by roychoo** [comment]
Hi i saw this is being assigned. is this being work on already? If not I would not mind contributing, but may need some guidance.

**Comment by CyrusNajmabadi** [comment]
Hey @roychoo .  It's been assigned, but not given a milestone.  So no work really has happened on it.  If you're interested, i'd be happy to work with you on adding this functionality.  From my brief look at authorizers, it doesn't seem like this would be that tough to do (i hope!)

**Comment by metral** [comment]
Another user in the community slack is hitting this. Any updates?

**Comment by roychoo** [comment]
Hi @CyrusNajmabadi sorry for not responding as I was busy. In a nutshell, is it to include the aws authorizer openapi extention in the swagger string?

As mentioned in here?



https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html

**Comment by lukehoban** [comment]
This support was added some time ago - see https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/#lambda-authorizers.
