### ISSUE TITLE
Add types and automatic JSON serialisation for aws.cloudwatch.Dashboard::dashboardBody 

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-aws#353]
As described in [this post](https://pulumi.io/aws/cloudwatch.html#create-an-aws-cloudwatch-resource-using-pulumiaws) and brought up in the community Slack channel, JSON is used to define a Cloudwatch dashboard.

It would be nice to provide some type helpers for making these easier to construct, and to add automatic serialisation.

**Comment by jen20** [comment]
Information on the schema is available here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html

**Comment by stack72** [comment]
@jen20 I am going to close this - [this](https://blog.pulumi.com/aws-cloudwatch-made-easy-with-pulumi-infrastructure-as-code) shows that there was work added for awsx for this - do you think that this suffices? If not, let's reopen it
