### ISSUE TITLE
Dotnet8 runtime not avaliable

### ISSUE THREAD

**Issue by luizhcrocha** [pulumi/pulumi-aws#3549]
### What happened?

Hi, .NET 8.0 runtime is not yet available on Pulumi, so we get an error while creating a Lamba Function. 

`dotnet8` runtime is [already an option on AWS Lambda](https://docs.aws.amazon.com/lambda/latest/api/API_CreateFunction.html#SSS-CreateFunction-request-Runtime), but [the related enums are missing on Pulumi codebase](https://github.com/search?q=repo%3Apulumi%2Fpulumi-aws%20dotnet6&type=code).

### Example

```typescript
// Editing Validation
const editingValidationLambda = new aws.lambda.Function(
  "editingValidationLambda",
  {
    name: "wrike-editing-validation",
    runtime: "dotnet8",
    s3Bucket: lambdaZip.bucket,
    s3Key: lambdaZip.key,
    s3ObjectVersion: lambdaZip.versionId,
    handler: dotNetApplicationEntryPoint + "::EditingValidationHandler",
    timeout: 15,
    memorySize: 512,
    publish: true,
    reservedConcurrentExecutions: 30,
    role: lambdasRole.arn,
  }
);
```

### Output of `pulumi about`

error: aws:lambda/function:Function resource 'createDeadlineReportAfternoonLambda' has a problem: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17], got dotnet8.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @luizhcrocha. Thanks for pointing this out to us. A fix will be out shortly.

**Comment by kanewestwood** [comment]
Thanks for adding the runtime so quickly @iwahbe ...

We want to upgrade our lambdas to Dotnet8 (we use the automation flow).

When targeting the alpha version it does not install the relevant plugin:
```
pulumi:providers:aws provider  error: Could not automatically download and install resource plugin 'pulumi-resource-aws' at version v6.25.0-alpha.1709567465+59f3fffe, install the plugin using `pulumi plugin install resource aws v6.25.0-alpha.1709567465+59f3fffe`: error downloading provider aws to file: failed to download plugin: aws-6.25.0-alpha.1709567465+59f3fffe: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v6.25.0-alpha.1709567465%2B59f3fffe-linux-amd64.tar.gz
```

I see commit was tagged 6.24.2 however that is not appearing on nuget.
