### ISSUE TITLE
Missing M5 instances types for EC2

### ISSUE THREAD

**Issue by eshamay** [pulumi/pulumi-aws#357]
There are no `M5` instance types defined in @pulumi/aws/ec2/instanceType.d.ts however they are supported as per EC2's docs: https://aws.amazon.com/ec2/instance-types/

**Comment by lukehoban** [comment]
We should bring these enums up to date with current EC2 offerings. 

Note that in the meantime - you can pass any string you want and cast `<any>”m5.large”`.

**Comment by eshamay** [comment]
> We should bring these enums up to date with current EC2 offerings.
> 
> Note that in the meantime - you can pass any string you want and cast `<any>”m5.large”`.

I tried this but it failed:

```
// Create the Kubernetes cluster and all associated artifacts and resources
const cluster = new eks.Cluster(environment+"-eks-cluster", {
    vpcId             : config.require("vpc-id"),
    subnetIds         : vpcSubnetIds,
    instanceType      : "m5.large",
    nodePublicKey     : config.require("worker-ssh-key"),
    nodeRootVolumeSize: 250,
    desiredCapacity   : 3,
    maxSize           : 10,
    minSize           : 1,
    nodeUserData      : userData,
});
```

Can you paste an example that corrects it?

**Comment by eshamay** [comment]
The list of instances can be programatically accessed and parsed for automated updates (with a little `jq` magic?):

`curl https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonRDS/current/index.json`

as per this: https://aws.amazon.com/about-aws/whats-new/2015/12/announcing-aws-price-list-api-programmatic-access-to-aws-prices/
