### ISSUE TITLE
OIDC AWS China Regional Issues

### ISSUE THREAD

**Issue by SeanWei-lab** [pulumi/pulumi-aws#3644]
### What happened?

When I configured the AWS-CN region of OICD, an error occurred that I could not call OIDC to obtain AKSK+Token.

### Example

Configure OIDC's AWS as cn-north-1 region

### Output of `pulumi about`

oidc-dev:4:7 - values.aws.login:
		Error: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://api.pulumi.com/oidc
	status code: 400, request id: e5da2212-0eba-4c74-88f5-a4ca3c997eac

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
We can't reproduce with the current information, but feel free to reopen with more details
