### ISSUE TITLE
Provider assumeRole argument does not work

### ISSUE THREAD

**Issue by masterada** [pulumi/pulumi-aws#371]
The following line references a closed issue in pulumi-terraform project: https://github.com/pulumi/pulumi-aws/blob/master/resources.go#L171 . It seems like assumeRole argument of the aws provider was not implemented because of this. As the mentioned issue is resolved, could you check if you can make it work?

**Comment by jen20** [comment]
Hi @masterada! I committed an example of [using AssumeRole](https://github.com/pulumi/examples/tree/master/aws-ts-assume-role) a few weeks ago - while that comment is technically correct, it's not required to use AssumeRole.

The following snippet shows the meat of doing this. I do think we need to improve the documentation here, and will open a new issue about that:

https://github.com/pulumi/examples/blob/master/aws-ts-assume-role/assume-role/index.ts#L4-L14

I'll go ahead and close out this issue for now - if the example doesn't meet your requirements please feel free to comment here and we'll take another look!

**Comment by texdc** [comment]
@jen20 @lukehoban I've followed the example and am getting this error:
```
Error: invocation of aws:acmpca/getCertificateAuthority:getCertificateAuthority returned an error: No valid credential sources found for AWS Provider.
```
I've validated that the role is accurate and that I have access to assume it via the aws cli.
```ts
// build provider with STS creds
const provider = new aws.Provider('assume-role', {
    assumeRole: {
        roleArn: config.require('role_arn'),
        sessionName: 'name',
        externalId: 'id'
    },
    region: aws.config.requireRegion()
})

const ca = output(getCertificateAuthority(
    { arn: config.require('ca_arn') },
    { provider } // use the AssumeRole STS creds for this call
))
```
