### ISSUE TITLE
Add retry to drainGroup for autoscaling groups. 

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-aws#3732]
### What happened?

We ran into an issue when destroying an autoscaling group where the drain call doesn't see to have a retry: 
```
2024-03-25 18:49:01,966 INFO     	* waiting for Auto Scaling Group (dedicated-autoscaling-group-7895a96) drain: RequestError: send request failed
2024-03-25 18:49:01,966 INFO     caused by: Post "https://autoscaling.us-west-2.amazonaws.com/": read tcp IP:37744->IP:443: read: connection reset by peer
```
I think its this call that needs a retry patch: https://github.com/hashicorp/terraform-provider-aws/blob/34e0a64a6adf1d7779e47b74bbc8a3c75aace6c8/internal/service/autoscaling/group.go#L1882

### Example

I don't have an example where I can make it fail Autoscaling Group destroy. 

### Output of `pulumi about`
```
CLI          
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.25.1
cloudinit   1.4.1
command     0.9.2
datadog     4.26.0
kubernetes  4.9.0
random      4.16.0
tls         5.0.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Hi @rshade thanks for filing this up, me and @corymhall are having a quick look. Is this something ok for next week or you need it right away? Available for a call sometime to clarify?

**Comment by t0yv0** [comment]
Per our conversation it sounded like something less urgent. We'll take a look in the next iteration.

**Comment by corymhall** [comment]
@rshade after looking into this more I don't know if it is worth the effort of maintaining a patch to try and fix this behavior, especially since these random network errors are difficult to reproduce and therefore ensure we have a sufficient fix for the issue.

If this issue starts occurring more regularly or becomes a serious blocker we can revisit this.

**Comment by mjeffryes** [comment]
Huh, the error message looks like it comes from   
```
	if _, err := waitGroupDrained(ctx, conn, name, timeout); err != nil {
		return fmt.Errorf("waiting for Auto Scaling Group (%s) drain: %w", name, err)
	}
```

around line 1882 (https://github.com/hashicorp/terraform-provider-aws/blob/34e0a64a6adf1d7779e47b74bbc8a3c75aace6c8/internal/service/autoscaling/group.go#L1882), but it looks like `waitGroupDrained` already has a retry policy applied:

```
func waitGroupDrained(ctx context.Context, conn *autoscaling.AutoScaling, name string, timeout time.Duration) (*autoscaling.Group, error) {
	stateConf := &retry.StateChangeConf{
		Target:  []string{"0"},
		Refresh: statusGroupInstanceCount(ctx, conn, name),
		Timeout: timeout,
	}

	outputRaw, err := stateConf.WaitForStateContext(ctx)

	if output, ok := outputRaw.(*autoscaling.Group); ok {
		return output, err
	}

	return nil, err
}
```
(https://github.com/hashicorp/terraform-provider-aws/blob/34e0a64a6adf1d7779e47b74bbc8a3c75aace6c8/internal/service/autoscaling/group.go#L2596)

I agree with Cory that it will probably be difficult to know what changes would be required there without a good repro case.

**Comment by t0yv0** [comment]
Taking another pass at reading the code here from waitGroupDrained today.

waitGroupDrained:
https://github.com/hashicorp/terraform-provider-aws/blob/5547244/internal/service/autoscaling/group.go#L2551

Sets up statusGroupInstanceCount as an atomic operation:
https://github.com/hashicorp/terraform-provider-aws/blob/5547244/internal/service/autoscaling/group.go#L2385

Calls WaitForStateContext which does outer-level retries over statusGroupInstanceCount::
https://github.com/hashicorp/terraform-provider-aws/blob/5547244/internal/service/autoscaling/group.go#L2551

WaitForStateContext stops retrying at first error, which is happening here.

However, statusGroupInstanceCount by itself is doing some retries at a lower level.

This function engages NewDescribeAutoScalingGroupsPaginator from aws-sdk-go-v2 which uses an autoscaling Client which in
turn has a default retryer setup.

From the TF docs:

```
### Default AWS Go SDK Retries

In some situations, while handling a response, the AWS Go SDK automatically retries a request before returning the
output and error. The retry mechanism implements an exponential backoff algorithm. The default conditions triggering
automatic retries (implemented through
[`client.DefaultRetryer`](https://docs.aws.amazon.com/sdk-for-go/api/aws/client/#DefaultRetryer)) include:

- Certain network errors. A common exception to this is connection reset errors.
- HTTP status codes 429 and 5xx.
- Certain API error codes, which are common across various AWS services (e.g., `ThrottledException`). However, not all AWS services implement these error codes consistently. A common exception to this is certain expired credentials errors.

By default, the Terraform AWS Provider sets the maximum number of AWS Go SDK retries based on the [`max_retries`
provider configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#max_retries). The provider
configuration defaults to 25 and the exponential backoff roughly equates to one hour of retries. This very high default
value was present before the Terraform AWS Provider codebase was split from Terraform CLI in version 0.10.
```

Pulumi exposes aws:maxRetries configuration setting that allows increasing the number of retry attempts. AS far as I can
tell from reading the code, pulumi-aws should be honoring this setting, but somehow for the reported error the retryer
runs of of the configured attempts.

For users experiencing this issue consistently, consider increasing maxRetries configuration from the default value.
