### ISSUE TITLE
Warn when changing the region of the default provider

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#3777]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

If you are using the default provider, and set the region in the stack config and deploy your resources, they all get created in the region specified.

if you then change the region in the stack config, because you assume that the resources will get re-created in the new region.

This doesn't happen and it can cause your stack to get out of sync because there are some resources that are in one region but the default provider is pointing at the other region.

If the region in default provider is changed from one update to another, we should at least warn that this may have undesired effects, if we don't just block this action from being possible.

**Comment by pierskarsenbarg** [comment]
I'm not suggesting we fix the problem (as in cascade the actual changes) but could we detect either if the region in the default provider changes or even if the region in the default provider doesn't match the region that the resources are deployed to (maybe from the ARN?)

**Comment by t0yv0** [comment]
@pierskarsenbarg we have a fix coming shortly that will actually re-create the resources in the provider. Would that work?
