### ISSUE TITLE
Provider assigning random and unique but not-compliant properties for RDS.

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi-aws#3808]
### What happened?

It seems like the intention and deafult behavior is if `name` is omitted from aws.rds.SubnetGroup that it will be generated. The same with aws.rds.Instance and `identifier`. However that does not seem to be the case illustrated below.

### First Example
```typescript
  // Create a subnet group for the RDS instance
  const dbSubnetGroup = new aws.rds.SubnetGroup(`rds-subnet-group`, {
    subnetIds: vpc.privateSubnetIds,
    tags: {
      "Owner": ownerTag!
    },
  });
  ```

Error
 ```
error: aws:rds/subnetGroup:SubnetGroup resource 'rds-subnet-group'
 has a problem: only lowercase alphanumeric characters, hyphens, underscores, periods, 
and spaces allowed in "name". Examine values at 'rds-subnet-group.name'.
```

Tooltip about `name` property.
```
The name of the DB subnet group. If omitted, the provider will assign a random, unique name.
```

Fix
```typescript
  // Create a subnet group for the RDS instance
  const dbSubnetGroup = new aws.rds.SubnetGroup(`rds-subnet-group`, {
    name: "this-name-is-compliant"
    subnetIds: vpc.privateSubnetIds,
    tags: {
      "Owner": ownerTag!
    },
  });
  ```
###  Second Example
 ```typescript
   const rdsInstance = new aws.rds.Instance(`rds-instance`, {
    allocatedStorage: 20,
    engine: "mysql",
    engineVersion: "8.0",
    instanceClass: "db.t3.micro",
    dbName: rdsName,
    username: "admin",
    password: cfg.requireSecret("rdspassword"),
    skipFinalSnapshot: true,
    vpcSecurityGroupIds: [dbSecurityGroup.id],
    dbSubnetGroupName: dbSubnetGroup.name, // Use the subnet group created above
    tags: {
      "Owner": ownerTag!
    },
  });
  ```
  
  Error
  ```
      error: aws:rds/instance:Instance resource 'rds-instance' has a problem: 
only lowercase alphanumeric characters and hyphens allowed in "identifier". 
Examine values at 'rds-instance.identifier'.
    error: aws:rds/instance:Instance resource 'rds-instance' has a problem: 
first character of "identifier" must be a letter. 
Examine values at 'rds-instance.identifier'.
 ```
 
 Tooltip about the `identifier` property.
 ```
 The name of the RDS instance, if omitted, this provider will assign a random, unique identifier. 
Required if restoreToPointInTime is specified.
 ```
 
 Fix
 ```typescript
    const rdsInstance = new aws.rds.Instance(`rds-instance`, {
    allocatedStorage: 20,
    engine: "mysql",
    engineVersion: "8.0",
    instanceClass: "db.t3.micro",
    dbName: rdsName,
    identifier: "this-identifier-is-compliant"
    username: "admin",
    password: cfg.requireSecret("rdspassword"),
    skipFinalSnapshot: true,
    vpcSecurityGroupIds: [dbSecurityGroup.id],
    dbSubnetGroupName: dbSubnetGroup.name, // Use the subnet group created above
    tags: {
      "Owner": ownerTag!
    },
  });
 ```

### Output of `pulumi about`

 pulumi about
CLI
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.29.1
awsx        2.6.0
docker      4.5.3
docker      3.6.1
eks         2.3.0
kubernetes  4.9.1
nodejs      unknown

Host
OS       darwin
Version  13.6.6
Arch     x86_64

This project is written in nodejs: executable='/Users/redacted/.nvm/versions/node/v16.20.2/bin/node' version='v16.20.2'

Current Stack: organization/redis-and-rds/dev

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:dev::redis-and-rds::pulumi:pulumi:Stack::redis-and-rds-dev
eks:index:Cluster                                    urn:pulumi:dev::redis-and-rds::eks:index:Cluster::redacted-eks-cluster
eks:index:ServiceRole                                urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole::redacted-eks-cluster-eksRole
eks:index:ServiceRole                                urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole::redacted-eks-cluster-instanceRole
pulumi:providers:aws                                 urn:pulumi:dev::redis-and-rds::pulumi:providers:aws::default_6_29_1
pulumi:providers:awsx                                urn:pulumi:dev::redis-and-rds::pulumi:providers:awsx::default_2_6_0
awsx:ec2:Vpc                                         urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc::redacted-vpc
pulumi:providers:eks                                 urn:pulumi:dev::redis-and-rds::pulumi:providers:eks::default
eks:index:RandomSuffix                               urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:RandomSuffix::redacted-eks-cluster-cfnStackName
aws:iam/role:Role                                    urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::redacted-eks-cluster-eksRole-role
aws:iam/role:Role                                    urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::redacted-eks-cluster-instanceRole-role
pulumi:providers:aws                                 urn:pulumi:dev::redis-and-rds::pulumi:providers:aws::default_6_9_0
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::redacted-eks-cluster-eksRole-4b490823
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::redacted-eks-cluster-instanceRole-e1b295bd
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::redacted-eks-cluster-instanceRole-3eb088f2
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::redacted-eks-cluster-instanceRole-03516f97
aws:iam/instanceProfile:InstanceProfile              urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:iam/instanceProfile:InstanceProfile::redacted-eks-cluster-instanceProfile
aws:ec2/vpc:Vpc                                      urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::redacted-vpc
aws:ec2/internetGateway:InternetGateway              urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::redacted-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::redacted-vpc-private-2
aws:ec2/subnet:Subnet                                urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::redacted-vpc-private-3
aws:ec2/subnet:Subnet                                urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::redacted-vpc-private-1
aws:ec2/subnet:Subnet                                urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::redacted-vpc-public-1
aws:ec2/subnet:Subnet                                urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::redacted-vpc-public-2
aws:ec2/subnet:Subnet                                urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::redacted-vpc-public-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::redacted-vpc-private-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::redacted-vpc-private-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::redacted-vpc-private-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::redacted-vpc-public-1
aws:ec2/eip:Eip                                      urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::redacted-vpc-1
aws:ec2/eip:Eip                                      urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::redacted-vpc-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::redacted-vpc-public-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::redacted-vpc-public-3
aws:ec2/eip:Eip                                      urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::redacted-vpc-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::redacted-vpc-private-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::redacted-vpc-private-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::redacted-vpc-private-1
aws:ec2/route:Route                                  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::redacted-vpc-public-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::redacted-vpc-public-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::redacted-vpc-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::redacted-vpc-2
aws:ec2/route:Route                                  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::redacted-vpc-public-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::redacted-vpc-public-2
aws:ec2/route:Route                                  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::redacted-vpc-public-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::redacted-vpc-public-3
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::redacted-vpc-3
aws:ec2/route:Route                                  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::redacted-vpc-private-1
aws:ec2/route:Route                                  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::redacted-vpc-private-2
aws:ec2/route:Route                                  urn:pulumi:dev::redis-and-rds::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::redacted-vpc-private-3
pulumi:providers:pulumi                              urn:pulumi:dev::redis-and-rds::pulumi:providers:pulumi::default
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::redacted-eks-cluster-eksClusterSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::redacted-eks-cluster-eksClusterInternetEgressRule
aws:eks/cluster:Cluster                              urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:eks/cluster:Cluster::redacted-eks-cluster-eksCluster
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::redacted-eks-cluster-nodeSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::redacted-eks-cluster-eksNodeIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::redacted-eks-cluster-eksNodeClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::redacted-eks-cluster-eksClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::redacted-eks-cluster-eksExtApiServerClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::redacted-eks-cluster-eksNodeInternetEgressRule
pulumi:providers:kubernetes                          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$pulumi:providers:kubernetes::redacted-eks-cluster-eks-k8s
eks:index:VpcCni                                     urn:pulumi:dev::redis-and-rds::eks:index:Cluster$eks:index:VpcCni::redacted-eks-cluster-vpc-cni
kubernetes:core/v1:ConfigMap                         urn:pulumi:dev::redis-and-rds::eks:index:Cluster$kubernetes:core/v1:ConfigMap::redacted-eks-cluster-nodeAccess
aws:ec2/launchConfiguration:LaunchConfiguration      urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:ec2/launchConfiguration:LaunchConfiguration::redacted-eks-cluster-nodeLaunchConfiguration
aws:cloudformation/stack:Stack                       urn:pulumi:dev::redis-and-rds::eks:index:Cluster$aws:cloudformation/stack:Stack::redacted-eks-cluster-nodes
pulumi:providers:kubernetes                          urn:pulumi:dev::redis-and-rds::eks:index:Cluster$pulumi:providers:kubernetes::redacted-eks-cluster-provider
kubernetes:core/v1:Service                           urn:pulumi:dev::redis-and-rds::kubernetes:core/v1:Service::webapp-service
kubernetes:core/v1:Service                           urn:pulumi:dev::redis-and-rds::kubernetes:core/v1:Service::redis-service
kubernetes:apps/v1:Deployment                        urn:pulumi:dev::redis-and-rds::kubernetes:apps/v1:Deployment::webapp-deployment
kubernetes:apps/v1:Deployment                        urn:pulumi:dev::redis-and-rds::kubernetes:apps/v1:Deployment::redis-deployment

Found no pending operations associated with dev

Backend
Name           redacteds-MacBook-Pro-6084.local
URL            REDACTED
User           redacted
Organizations
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.112.0
@types/node     18.19.31
chai            5.1.0
sinon           17.0.1
@pulumi/aws     6.29.1
@pulumi/awsx    2.6.0
@pulumi/eks     2.3.0

Pulumi locates its logs in /var/folders/w7/vxl3tlsj4vb7kxf0jw20_08w0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@orcutt989 thanks for reporting this issue! Are you able to reproduce this on a fresh project? I've tried to reproduce this using the simple example, but everything is auto named for me. I'm curious if there is something else going on with your configuration that might be causing the issue.

**Comment by mikhailshilkov** [comment]
Hmm, same here, I tried reproducing the problem but the below program succeeds:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const vpc = new awsx.ec2.Vpc("myvpc");

// Create a subnet group for the RDS instance
const dbSubnetGroup = new aws.rds.SubnetGroup(`rds-subnet-group`, {
    subnetIds: vpc.privateSubnetIds,
  });
```

@orcutt989 Could you give this standalone sample a try? Any chance you are using transformations in your code?

**Comment by mikhailshilkov** [comment]
@orcutt989 Any chance you could take another look here?

**Comment by orcutt989** [comment]
I havent had the chance to test this and if you guys cannot reproduce it feel free to close. Thanks for the attention though!
