### ISSUE TITLE
ecs/service always times out

### ISSUE THREAD

**Issue by eelkeh** [pulumi/pulumi-aws#381]
Given the following:

```
const cloud = require("@pulumi/cloud-aws");

const REDIS_URL = "redis://foo";
const DATABASE_URL = "psql://bar";

let service = new cloud.Service("django-app", {
  containers: {
    django: {
      build: "../",
      memory: 512,
      cpu: 2,
      // ports: [{ port: 443, protocol: "https", targetPort: 8000 }],
      ports: [{ port: 8000 }],
      environment: {
        DATABASE_URL: DATABASE_URL,
        CELERY_BROKER_URL: REDIS_URL,
        CELERY_RESULT_BACKEND: REDIS_URL
      }
    }
  }
  // replicas: 2
});

let workerService = new cloud.Service("django-app-worker", {
  containers: {
    celery: {
      build: "../",
      command: ["celery", "-A", "app", "worker", "-l", "info"],
      memory: 512,
      cpu: 2,
      environment: {
        DATABASE_URL: DATABASE_URL,
        CELERY_BROKER_URL: REDIS_URL,
        CELERY_RESULT_BACKEND: REDIS_URL
      }
    }
  }
  // replicas: 2
});

// export just the hostname property of the container frontend
exports.url = service.defaultEndpoint.apply(e => `http://${e.hostname}`);
```
Creating the resources with `pulumi up` the first time seems to work fine. After that any update to the Dockerfile results in a timeout of the update:
```
Diagnostics:
  aws:ecs:Service (django-app-worker):
    error: Plan apply failed: 1 error occurred:

    * updating urn:pulumi:backend-dev::django-deploy::cloud:service:Service$aws:ecs/service:Service::django-app-worker: timeout while waiting for state to become 'true' (last state: 'false', timeout: 10m0s)

  aws:ecs:Service (django-app):
    error: Plan apply failed: 1 error occurred:

    * updating urn:pulumi:backend-dev::django-deploy::cloud:service:Service$aws:ecs/service:Service::django-app: timeout while waiting for state to become 'true' (last state: 'false', timeout: 10m0s)
```
Times out after 10 minutes, when I run `pulumi up` after this timeout it seems to cleanup and not timeout. Any subsequent update again will timeout, tried many times to destroy and redo the entire setup, always end up here.
Any ideas on how to debug this issue?

**Comment by lukehoban** [comment]
Followed up with @eelkeh at https://pulumi-community.slack.com/archives/C84L4E3N1/p1542817597870700.  It appears the most immediate issue was due to ENI limits in ECS:

```
service django-app-e087161 was unable to place a task because no container instance met all of its requirements. The closest matching container-instance c02faa85-e355-43c2-af55-925ffeba89ce encountered error "RESOURCE:ENI
```

I'll close this out for now, and continue the debugging conversation in Slack. If it turns out there is an issue in Pulumi that is causing this we'll open a new issue as appropriate.

**Comment by michaelharrisonroth** [comment]
@lukehoban has any progress been made on this issue? I'm not sure if it's simply related to the number of changes or the application growth but we are no longer able to deploy as it always times out.

**Comment by duro** [comment]
@lukehoban @joeduffy I seem to be experiencing this every time I deploy a stack using the Pulumi GitHub action. 

```updating urn:pulumi:dev::infra::awsx:x:ecs:FargateService$aws:ecs/service:Service::backend: timeout while waiting for state to become 'true' (last state: 'false', timeout: 10m0s)```

The service does eventually complete in AWS, and reach the intended state.

**Comment by volkanunsal** [comment]
Is there  solution to this issue? Here is the explanation of the error from AWS docs:

```
For RESOURCE:ENI errors, your cluster does not have any available elastic network interface attachment points, which are required for tasks that use the awsvpc network mode. Amazon EC2 instances have a limit to the number of network interfaces that can be attached to them, and the primary network interface counts as one. For more information about how many network interfaces are supported per instance type, see IP Addresses Per Network Interface Per Instance Type in the Amazon EC2 User Guide for Linux Instances.
```

What I don't understand is how this error only comes up on updating a deployed infrastructure.

**Comment by volkanunsal** [comment]
I think in my case I was using an instance, `t2-nano`, that is limited to 2 network interfaces. And when I run an update, 2 revisions of the same task definition have to be running simultaneously on the same instance, apparently. (Probably a graceful way to redirect network traffic to the new revision?)

So, I upgraded my instance to `t2-small`, which has 3 network interfaces, and it seems to have gotten rid of the timeouts and "RESOURCE:ENI" errors.
