### ISSUE TITLE
Elasticache replaced on every run with empty diff

### ISSUE THREAD

**Issue by kovaxur** [pulumi/pulumi-aws#3848]
### What happened?

We have an Elasticache set up via Pulumi. Whenever we run the pulumi script, it wants to replace the Elasticache instance without showing any diff.

### Example

Code part to create the instance:

```
    return new aws.elasticache.ServerlessCache(`${name}`, {
      engine: 'redis',
      kmsKeyId: options.kmsKey.keyId,
      majorEngineVersion: options.majorEngineVersion,
      name,
      securityGroupIds: [securityGroup.id],
      subnetIds: getSubnetIds(instanceSubnet),
    }, {
      deleteBeforeReplace: true,
    });
```

When it's first ran, it created all the resources properly, but if re-ran, it tries to replace it without any diff, the output:

```
     Type                                Name                                                        Plan        Info
     pulumi:pulumi:Stack                 XXXX                              1 warning; 23 messages
 ~   ├─ pulumi:providers:aws             certManagerProvider                                         update      [diff: ~version]
 +-  ├─ aws:elasticache:ServerlessCache  XXXXX-cache                              replace     [diff: ]

```

If I try to get the details, it's again not showing any diff.

This might be similar to https://github.com/pulumi/pulumi-aws/issues/684.

### Output of `pulumi about`

    "@pulumi/aws": "6.31.1",
    "@pulumi/kubernetes": "3.30.1",
    "@pulumi/pulumi": "3.113.2",
Node version: v18.19.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@kovaxur thanks for reporting this issue! It looks like this is due to an [upstream issue](https://github.com/hashicorp/terraform-provider-aws/issues/35285).

The API accepts a key id for the `kmsKeyId` field, but it actually expects a key `arn` and stores a key arn in state.

Can you try changing your field to the key `arn` and let me know if it fixes your issue?

**Comment by kovaxur** [comment]
Hi,
Thanks, it solved the issue.
