### ISSUE TITLE
Locally working stack fails to use CI credentials

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3861]
### What happened?

https://github.com/pulumi/customer-support/issues/1500

Need to extract repro from the above ticket. It involves explicit providers.

### Example

TBD.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@tusharshahrs I looked at the linked ticket, but I don't see anything that can be used to reproduce this issue. Do you think you could get a contained example that we could use to reproduce?

**Comment by tusharshahrs** [comment]
We got on a call with the customer who couldn't reproduce the issue, and we are awaiting more information in regards to the code block. We sent them code showing how to do it also.

**Comment by t0yv0** [comment]
Checking in here @tusharshahrs , do we have the ability to reproduce this? Much appreciated.
