### ISSUE TITLE
infinite aws.provider updates after upgrading to v6.24.2

### ISSUE THREAD

**Issue by isaac-smothers** [pulumi/pulumi-aws#3869]
### What happened?

Upgrading to @pulumi/aws causes my existing aws provider to report a diff. Running a pulumi up does not get rid of this message.

My aws package was originally on 6.21.0 when the provider was created. I attempted to upgrade to every single version above that and the issue didn't show up until v6.24.2. Other versions just showed a ~version update that went away after the update. It also isn't resolved in the newest provider version (v.6.25.0).

I'd love to use the node8 support for lambda so let me know if I'm doing something wrong.

### Example

provider code
```
const provider = new aws.Provider("privileged", {
          assumeRole: {
              roleArn: "arn:aws:iam::X:role/PulumiDeployer",
              sessionName: "PulumiSession",
              externalId: "PulumiApplication",
          },
          region: "us-west-2",
      })
```

update message
```
     pulumi:pulumi:Stack      PROJECTNAME-STACKNAME             
 ~   └─ pulumi:providers:aws  privileged                      update     [diff: +assumeRole,region,skipCredentialsValidation,skipMetadataApiCheck,skipRegionValidation,version]

    ~ pulumi:providers:aws: (update)
        [id=IDSTRING]
        [urn=urn:pulumi:STACKNAME::PROJECTNAME::pulumi:providers:aws::privileged]
      + assumeRole               : (json) {
          + externalId : "PulumiApplication"
          + roleArn    : "arn:aws:iam::X:role/PulumiDeployer"
          + sessionName: "PulumiSession"
        }

      + region                   : "us-west-2"
      + skipCredentialsValidation: "false"
      + skipMetadataApiCheck     : "true"
      + skipRegionValidation     : "true"
      + version                  : "6.24.2"
```

### Output of `pulumi about`

CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME     VERSION
archive  0.0.5
aws      6.24.2
nodejs   unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.7.3'

Current Stack: organization/projectname/StackName

Found no pending operations associated with StackName

Backend        
Name           redacted
URL            s3://companyname-pulumi-state
User           isaacsmothers
Organizations  

Dependencies:
NAME                                         VERSION
@aws-sdk/client-resource-groups-tagging-api  3.509.0
@pulumi/pulumi                               3.105.0
@types/chai                                  4.3.11
@types/node                                  16.18.79
js-yaml                                      4.1.0
@aws-sdk/types                               3.502.0
@pulumi/archive                              0.0.5
@types/js-yaml                               4.0.9
eslint                                       8.56.0
proxyquire                                   2.1.3
sinon                                        15.2.0
@aws-sdk/client-elastic-load-balancing-v2    3.509.0
@types/mocha                                 10.0.6
ajv                                          8.12.0
chai                                         4.4.1
lint-staged                                  14.0.1
prettier                                     3.2.5
@pulumi/aws                                  6.24.2
@typescript-eslint/parser                    6.21.0
ts-node                                      10.9.2
typescript                                   4.9.5
yaml                                         2.3.4
@aws-sdk/client-route-53                     3.509.0
@types/sinon                                 10.0.20
aws-sdk                                      2.1554.0
eslint-config-prettier                       9.1.0
eslint-plugin-import                         2.29.1
eslint-plugin-n                              16.6.2
eslint-plugin-promise                        6.1.1
husky                                        8.0.3
mocha                                        10.3.0
@types/ajv                                   1.0.0
@typescript-eslint/eslint-plugin             6.21.0
aws-sdk-client-mock                          3.0.1
eslint-config-standard-with-typescript       39.1.1
jszip                                        3.10.1

Pulumi locates its logs in /var/folders/bw/69jmnfd15ds9yh1r1l9s74b00000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@isaac-smothers thanks for creating this issue! Do you have a minimal example we can use to reproduce this? I've tried with the below example, but I haven't been able to.

```ts
import * as aws from "@pulumi/aws";

const provider = new aws.Provider('provider', {
  region: 'us-east-2',
  assumeRole: {
    roleArn: `arn:aws:iam::${process.env.AWS_ACCOUNT}:role/assumable-role`,
    sessionName: 'MySession',
    externalId: 'my-external-id',
  }
});

// create this role first to be able to use in the provider config
const role = new aws.iam.Role('assumable-role', {
  name: 'assumable-role',
  assumeRolePolicy: aws.iam.getPolicyDocument({
    statements: [{
      actions: ['sts:AssumeRole'],
      principals: [{ type: 'AWS', identifiers: [`arn:aws:iam::${process.env.AWS_ACCOUNT}:root`]}],
      conditions: [{
        test: 'StringEquals',
        variable: 'sts:ExternalId',
        values: ['my-external-id'],
      }]
    }]
  }).then(policy => policy.json),
  managedPolicyArns: [aws.iam.ManagedPolicies.AdministratorAccess],
});


new aws.s3.Bucket('test-bucket', {}, { provider });
export const roleArn = role.arn;

```

**Comment by DrorBuhnik** [comment]
Hi,
I don't have minimal example for reproduce, I just wanted to pitch in and say that I also encounter the same issue
My stack was updated from ^5 aws provider to the latest 6.32.0 and I didn't try to pin-point it to the exact version with the issue

The drift that I get is the same:
```
    ~ pulumi:providers:aws: (update)
        [id=XXX]
        [urn=urn:pulumi:dev::infra::pulumi:providers:aws::aws]
      + profile                  : "dev"
      + region                   : "us-east-2"
      + skipCredentialsValidation: "false"
      + skipMetadataApiCheck     : "true"
      + skipRegionValidation     : "true"
      + version                  : "6.32.0"
```

and this is the relevant stack state part, maybe that info will help in finding the issue:
```json
            {
                "urn": "urn:pulumi:dev::infra::pulumi:providers:aws::aws",
                "custom": true, 
                "id": "XXX",
                "type": "pulumi:providers:aws",
                "inputs": {
                    "profile": "dev",
                    "region": "us-east-2",
                    "skipCredentialsValidation": "false",
                    "skipMetadataApiCheck": "true",
                    "skipRegionValidation": "true",
                    "version": "6.32.0"
                },
                "outputs": {
                    "profile": "dev",
                    "region": "us-east-2",
                    "skipCredentialsValidation": "false",
                    "skipMetadataApiCheck": "true",
                    "skipRegionValidation": "true",
                    "version": "6.32.0"
                },
                "parent": "urn:pulumi:dev::infra::pulumi:pulumi:Stack::infra-dev",
                "propertyDependencies": {
                    "profile": null, 
                    "region": null, 
                    "skipCredentialsValidation": null, 
                    "skipMetadataApiCheck": null, 
                    "skipRegionValidation": null
                },
                "created": "2023-05-18T06:39:52.64441148Z",
                "modified": "2024-04-28T10:26:54.223756357Z"
            },
```

**Comment by isaac-smothers** [comment]
Sorry for the late response been super busy. Here's a minimal example to reproduce this issue:

## Start with this code, npm install it and pulumi up
 
### Index.ts

``` ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config()
const roleToAssumeARN = config.get("roleToAssumeARN")

const provider = new aws.Provider("privileged", {
    assumeRole: {
        roleArn: roleToAssumeARN,
        sessionName: "PulumiSession",
        externalId: "PulumiApplication",
    },
    region: aws.config.requireRegion(),
})
```

###  Stack config YAML

``` yaml
config:
    aws:region: us-west-2
    PROJECT_NAME:roleToAssumeARN: arn:aws:iam::123:role/pulumirole
```

### Package.json

``` json
{
    "name": "testing-provider-upgrade",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^18"
    },
    "dependencies": {
        "@pulumi/aws": "6.21.0",
        "@pulumi/pulumi": "3.105.0",
        "typescript": "^5.0.0"
    }
}
```

## Then swap your package.json to this, npm install, and rerun

``` json
{
    "name": "testing-provider-upgrade",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^18"
    },
    "dependencies": {
        "@pulumi/aws": "6.33.1",
        "@pulumi/pulumi": "3.105.0",
        "typescript": "^5.0.0"
    }
}
```

## Result
```
Previewing update (dev):
     Type                     Name                          Plan       Info
     pulumi:pulumi:Stack      testing-provider-upgrade-dev             
 ~   └─ pulumi:providers:aws  privileged                    update     [diff: +assumeRole,region,skipCredentialsValidation,skipMetadataApiCheck,skipRegionVal
```

**Comment by isaac-smothers** [comment]
Note - it doesn' _seem_ that this provider change causes a replacement of any resources.. so I'm going to try using it as I really need the updated aws package. The main issue is that all previews and ups will show an update to that provider no matter how many times you run it.

It's odd that it continues showing that change even after deploying it, almost like the provider state isn't being updated.. Don't have time to investigate further right now

**Comment by isaac-smothers** [comment]
Update: It was my pulumi CLI verison. I upgraded from pulumi cli 3.73.0 to 3.115.2 and it fixed it.

I realized it was happening even with creating the provider from scratch and that led me to figuring out I needed to update my cli.
