### ISSUE TITLE
Revisit import issues

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3875]
~https://github.com/pulumi/pulumi-aws/issues/2318~ import subnet warnings
 ~https://github.com/pulumi/pulumi-aws/issues/3670~
  https://github.com/pulumi/pulumi-aws/issues/3158 (awaiting/upstream)

https://github.com/pulumi/pulumi-aws/issues/1528 ((awaiting/upstream)

~https://github.com/pulumi/pulumi-aws/issues/1940~ (needs-repro) import LaunchTemplate warnings
~https://github.com/pulumi/pulumi-aws/issues/2410~ (needs-repro)

~https://github.com/pulumi/pulumi-aws/issues/2318~ conflicting arguments on subnet import (+13) bridge issue

https://github.com/pulumi/pulumi-aws/issues/2852 quickSight.Analyiss

~https://github.com/pulumi/pulumi-aws/issues/2854~ import (no repro)

https://github.com/pulumi/pulumi-aws/issues/3311 tags import

https://github.com/pulumi/pulumi-aws/issues/3986

https://github.com/pulumi/pulumi-aws/issues/4054

**Comment by flostadler** [comment]
Another tags import issue: https://github.com/pulumi/pulumi-aws/issues/4030

**Comment by t0yv0** [comment]
Specifically looking here for opportunities/recommendations to fix import-related issues globally, in the bridge or in Pulumi itself.

https://github.com/pulumi/pulumi-terraform-bridge/issues/2028 has an assortment of bridged provider import issues this can help inform.

**Comment by t0yv0** [comment]
For example, perhaps if it is possible to fix https://github.com/pulumi/pulumi-aws/issues/4054 generically by dropping Read entries that do not pass ValidateDiagFunc that could also improve the ecosystem as a whole, in e.g. linode.

**Comment by t0yv0** [comment]
That's a great result too!

**Comment by t0yv0** [comment]
Counting this as done, thanks so much!
