### ISSUE TITLE
Issue with Autoscaling group

### ISSUE THREAD

**Issue by graforlock** [pulumi/pulumi-aws#389]
I am trying to achieve a basic Rabbitmq launch configuration with autoscaling group.

The code I use for index.js is as follows:

```javascript
const aws = require('@pulumi/aws');

let size = 't2.micro';  
let ami  = 'ami-0d2505740b82f7948'; 
let region = 'us-east-1';

let group = new aws.ec2.SecurityGroup('rabbitmq-secgrp', { 
  ingress: [
      { protocol: 'tcp', fromPort: 0, toPort: 22, cidrBlocks: ['0.0.0.0/0'] },
      { protocol: 'tcp', fromPort: 0, toPort: 65535, cidrBlocks: ['0.0.0.0/0'] }, 
  ],
  egress: [
      { protocol: 'tcp', fromPort: 0, toPort: 65535, cidrBlocks: ['0.0.0.0/0'] }
  ]
});

let vpc = new aws.ec2.DefaultVpc('rabbitmq-vpc', {
  cidrBlock: '172.31.0.0/16',
  instanceTenancy: 'default'
});

let server = new aws.ec2.LaunchConfiguration('rabbitmq', {
  name: 'rabbitmq-ec2',
  instanceType: size,
  securityGroups: [ group.name ],
  imageId: ami,
  keyName: 'rabbitmq'
});

let autoscaling = new aws.autoscaling.Group('rabbitmq-asg', {
  name: 'rabbitmq-asg',
  minSize: 3,
  maxSize: 7,
  launchConfiguration: 'rabbitmq-ec2',
  vpcZoneIdentifiers: [ vpc.id ]
});

exports.publicIp = server.publicIp;
exports.publicHostName = server.publicDns;
```

When I try running this with `pulumi update` I get:

```
Diagnostics:
  aws:autoscaling:Group (rabbitmq-asg):
    error: Plan apply failed: Error creating AutoScaling Group: ValidationError: The subnet ID 'vpc-b0c26eca' does not exist
    	status code: 400, request id: a26a887f-f713-11e8-ad9a-4baa7189910d
```

1) It is a valid VPC ID (I can easily use it trying manually)
2) Is the vpc id used in place of Subnet ID by any chance? This looks like what's causing the problem.
3) Version used is `@pulumi/aws@0.16.2`

**Comment by jen20** [comment]
Hi @graforlock! This one is tricky but a result of the underlying AWS API - `vpcZoneIdentifiers` should be subnet IDs rather than a VPC ID.

If you only have a VPC ID, and need to get the subnet IDs, you can make use of the `aws.ec2.getSubnets` function in the SDK, though this will require wrapping your program in an `async` main function because of lack of top-level await in TypeScript.

If you need an example of this please reply on here and I'll put one together for you.

**Comment by graforlock** [comment]
Thanks, that solved the issue!

**Comment by carlopiloto** [comment]
Just encountered the same error, but I am not sure how to implement the async call. 

Basically the code need to wait for the creation of the vpc, and then invoke the autoscaling call. Correct? Could you please give an example?
