### ISSUE TITLE
How to set up a vpc Id in RDS Instance ?

### ISSUE THREAD

**Issue by graforlock** [pulumi/pulumi-aws#390]
According to: https://docs.subzero.cloud/images/fargate/db-advanced-1.png

It should be a property somewhere, but this is not available as per interface: https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/rds/instance.ts

Apart from vpc security group ids and subnet group name.

**Comment by jen20** [comment]
Hi @graforlock! Sorry for the delay in replying here. You actually _don't_ set the VPC ID directly in the RDS API, even though the UI presents it that way. Instead, you create database subnets and a database subnet group in a given VPC, and specify the database subnet group name in the `dbSubnetGroupName` property. This is a confusing piece of the API - feel free to reopen this issue if you have any further problems getting this to work!

**Comment by konsumer** [comment]
Would it be possible to show an example of this? I am having a heck of a time figuring out how to expose a database to the internet.

Here is what I have so far:

```js
const dbPassword = new random.RandomPassword(`${project}-password-${stack}`, {
  length: 32,
  special: false
})

const securityGroup = new aws.ec2.SecurityGroup(`${project}-db-${stack}`, {
  ingress: [
    { protocol: 'tcp', fromPort: 5432, toPort: 5432, cidrBlocks: ['0.0.0.0/0'] }
  ]
})

const vpc = new aws.ec2.Vpc(`${project}-vpc-${stack}`, {
  cidrBlock: '10.0.0.0/16'
})

const internetGateway = new aws.ec2.InternetGateway(`${project}-gateway-${stack}`, {
  vpcId: vpc.id
})

const publicRouteTable = new aws.ec2.RouteTable(`${project}-routes-${stack}`, {
  routes: [
    {
      cidrBlock: '0.0.0.0/0',
      gatewayId: internetGateway.id
    }
  ],
  vpcId: vpc.id
})

const db = new aws.rds.Instance(`${project}-data-${stack}`, {
  engine: 'postgres',

  instanceClass: 'db.t2.micro',
  allocatedStorage: 20,

  name: project,
  username: project,
  password: dbPassword.result,

  skipFinalSnapshot: true,

  publiclyAccessible: true
})
```

I think this is right so far, but I can't seem to figure out how to hook `vpc` up to `db`.

**Comment by steveellis** [comment]
Example here: https://gist.github.com/lukehoban/5c168258b641368dcccc7810dc454ca9

**Comment by jasonkuhrt** [comment]
Having the same issue, asked in slack: https://pulumi-community.slack.com/archives/CRH5ENVDX/p1644871760215299
