### ISSUE TITLE
TestAccWebserverComp flake

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3903]
See https://github.com/pulumi/pulumi-aws/issues/3895

```
aws:ec2:Instance (web-server-app):
  error: 1 error occurred:
  	* creating urn:pulumi:p-it-fv-az1019--webserver--0adc9e13::webserver_comp::aws:ec2/instance:Instance::web-server-app: 1 error occurred:
  	* waiting for EC2 Instance (i-032319ee5436b513c) create: timeout while waiting for state to become 'running' (last state: 'pending', timeout: 10m0s)
 ```
 
Could be a need for higher timeout, or could be a manifestation of test account health.

**Comment by t0yv0** [comment]
one more: https://github.com/pulumi/pulumi-aws/issues/3902

**Comment by flostadler** [comment]
one more: https://github.com/pulumi/pulumi-aws/issues/3906

**Comment by flostadler** [comment]
Another two occurrences: https://github.com/pulumi/pulumi-aws/issues/3925

This is way too flaky now. I'm gonna dig into why it's starting to fail to often, seems like the startup of the EC2 instance isn't  properly working because it doesn't go to running state

**Comment by flostadler** [comment]
My hunch is that this is caused by a combination of a very small instance type `t2.nano` and a very old AMI (deprecated since 2022, no security patches anymore...).
All the test failures mention the `t2.nano` instance failing to become healthy so I'm gonna try switching that for a t2 micro with a more recent AMI.

**Comment by flostadler** [comment]
I upgraded the AMI of the failing test to AL2023. Let's see if this fixes the test

**Comment by flostadler** [comment]
It happened again: Just upgrading the AMI was not enough. I'll change the test to only start a t2.micro instance

**Comment by t0yv0** [comment]
Sadness. Thanks for looking into this. Feel free to also skip the test while we investigate since the disturbance from flakiness outweighs the coverage we get out of it.
