### ISSUE TITLE
`ec2.NewRouteTableAssociation()` resource got removed from stack after an update

### ISSUE THREAD

**Issue by tiffyuen** [pulumi/pulumi-aws#3911]
### What happened?

When we try to modify a route table association by attaching the subnet from one route table to another, pulumi will attempt to update the `aws:ec2:RouteTableAssociation` resource as expected. But after the update, the resource is gone from the stack, and the next `pulumi preview/ up` will try to create the association again, which results in an error that the association already existed.

### Example
The goal is to associate `subnet-1` and `subnet-2` from route table `rtb-001`(what's currently in pulumi stack) to route table `rtb-002`.

First `pulumi prevew` after updating the route table association in code to switch from `rtb-001` to `rtb-002`:
```
~   ├─ aws:ec2:RouteTableAssociation  subnet-1       update     [diff: ~routeTableId]
~   ├─ aws:ec2:RouteTableAssociation  subnet-2       update     [diff: ~routeTableId]

~ aws:ec2/routeTableAssociation:RouteTableAssociation: (update)
        [id=rtbassoc-123]
        [urn=urn:pulumi:env::stack-name::aws:ec2/routeTableAssociation:RouteTableAssociation::subnet-1]
      ~ routeTableId: "rtb-001" => output<string>
~ aws:ec2/routeTableAssociation:RouteTableAssociation: (update)
        [id=rtbassoc-456]
        [urn=urn:pulumi:env::stack-name::aws:ec2/routeTableAssociation:RouteTableAssociation::subnet-2]
      ~ routeTableId: "rtb-001" => output<string>
```

After the update is successful with `pulumi up`, running `pulumi preview` again will attempt to create the same associations currently route table `rtb-002`:
```
 +   ├─ aws:ec2:RouteTableAssociation  subnet-1  create      
 +   ├─ aws:ec2:RouteTableAssociation  subnet-2  create
 
+ aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
        [urn=urn:pulumi:env::stack-name::aws:ec2/routeTableAssociation:RouteTableAssociation::subnet-1]
        routeTableId: "rtb-002"
        subnetId    : "subnet-abc"
+ aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
        [urn=urn:pulumi:env::stack-name::aws:ec2/routeTableAssociation:RouteTableAssociation::subnet-2]
        routeTableId: "rtb-002"
        subnetId    : "subnet-xyz"
```

If we proceed with the `pulumi up` for these 2 resource creations, it will result in this error:
```
Diagnostics:
  pulumi:pulumi:Stack (xxx):
    error: update failed
 
  aws:ec2:RouteTableAssociation (subnet-1):
    error: 1 error occurred:
    	* creating Route Table (rtb-002) Association: Resource.AlreadyAssociated: the specified association for route table rtb-002 conflicts with an existing association
    	status code: 400, request id: xxx
 
  aws:ec2:RouteTableAssociation (subnet-2):
    error: 1 error occurred:
    	* creating Route Table (rtb-002) Association: Resource.AlreadyAssociated: the specified association for route table rtb-002 conflicts with an existing association
    	status code: 400, request id: xxx
``` 

### Output of `pulumi about`

```
CLI          
Version      3.101.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.13.3
aws-native  0.99.0
go          unknown
kubernetes  4.7.1
random      4.15.1
tls         4.11.1

Host     
OS       darwin
Version  14.4.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Thanks for reporting this @tiffyuen! You mentioned that you've changed the CIDR of a `RouteTableAssociation` and this caused the resources to be removed. `RouteTableAssociation` does not have a CIDR parameter, are you referring to changing the CIDR of the VPC or the CIDR of one of the routes in the route table?

If possible, could you provide an example so we can reproduce this issue?

**Comment by tiffyuen** [comment]
> Thanks for reporting this @tiffyuen! You mentioned that you've changed the CIDR of a `RouteTableAssociation` and this caused the resources to be removed. `RouteTableAssociation` does not have a CIDR parameter, are you referring to changing the CIDR of the VPC or the CIDR of one of the routes in the route table?
> 
> If possible, could you provide an example so we can reproduce this issue?

Hi @flostadler thank you for the quick response. It was a long day and I messed up with the terms. Updated the comment with the correct problem! I was referring to the scenario where we try to modify a route table association for a subnet from one route table to another one. 

e.g. Currently `subnet-abc` is associated to the route table `rtb-001` in this following code:
```
subnet1RtAsso, err := ec2.NewRouteTableAssociation(ctx, "subnet-1", &ec2.RouteTableAssociationArgs{
			SubnetId:     subnet.ID(), // subnet-abc in pulumi.StringPtrInput format
			RouteTableId: routeTable1.ID(), // rtb-001 in pulumi.StringInput format
		})
		if err != nil {
			return err
		}
```

We are trying to move this association so `subnet-abc` will be associated to `rtb-002` with this modified code:
```
subnet1RtAsso, err := ec2.NewRouteTableAssociation(ctx, "subnet-1", &ec2.RouteTableAssociationArgs{
			SubnetId:     subnet.ID(), // subnet-abc in pulumi.StringPtrInput format
			RouteTableId: routeTable2.ID(), // rtb-002 in pulumi.StringInput format
		})
		if err != nil {
			return err
		}
```

Thank you very much for your help!

**Comment by flostadler** [comment]
Thanks, I'll try to reproduce this on our end. Will keep you posted with updates about what I find out!

**Comment by flostadler** [comment]
I wasn't able to reproduce that on our end.

I deployed two subnets and associated it to a route table. After that I changed the `RouteTableId` of the `RouteTableAssociations` to another route table.

After doing this route table change I couldn't observe the attempted recreation & failure you were seeing; instead I had no diff.

These are the versions I tested with:
```
CLI
Version      3.113.1
Go Version   go1.22.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.32.0
awsx    2.9.0
docker  4.4.3
go      unknown

Host
OS       darwin
Version  14.4
Arch     arm64
```

@tiffyuen  Can you please test with the latest versions of pulumi and the provider whether you can reproduce the issue. Please also add a minimal reproducible example if it reproduces, so we can replicate the issue on our end.

Here's the code I tried with:
```
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/ec2"
	ec2x "github.com/pulumi/pulumi-awsx/sdk/v2/go/awsx/ec2" 
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	cidr := "10.0.0.0/16"
	pulumi.Run(func(ctx *pulumi.Context) error {
		vpcArgs := &ec2x.VpcArgs{
			CidrBlock: &cidr,
		}
		vpc, err := ec2x.NewVpc(ctx, "awsx-3911-test-vpc", vpcArgs)
		if err != nil {
			return err
		}

		subnetArgs := &ec2.SubnetArgs{
			VpcId:             vpc.VpcId,
			CidrBlock:         pulumi.String("10.0.254.0/24"),
			MapPublicIpOnLaunch: pulumi.Bool(true),
		}
		subnet, err := ec2.NewSubnet(ctx, "my-new-public-subnet", subnetArgs)
		if err != nil {
			return err
		}

		otherSubnetArgs := &ec2.SubnetArgs{
			VpcId:             vpc.VpcId,
			CidrBlock:         pulumi.String("10.0.255.0/24"),
			MapPublicIpOnLaunch: pulumi.Bool(true),
		}
		otherSubnet, err := ec2.NewSubnet(ctx, "my-other-public-subnet", otherSubnetArgs)
		if err != nil {
			return err
		}

		routeTableArgs := &ec2.RouteTableArgs{
			VpcId: vpc.VpcId,
		}
		routeTable, err := ec2.NewRouteTable(ctx, "myRouteTable", routeTableArgs)
		if err != nil {
			return err
		}

		otherRouteTableArgs := &ec2.RouteTableArgs{
			VpcId: vpc.VpcId,
		}
		_, err = ec2.NewRouteTable(ctx, "otherRouteTable", otherRouteTableArgs) // switch the associations below to this route table after the initial deployment
		if err != nil {
			return err
		}

		_, err = ec2.NewRouteTableAssociation(ctx, "myRouteTableAssociation", &ec2.RouteTableAssociationArgs{
			SubnetId:     subnet.ID(),
			RouteTableId: routeTable.ID(),
		})
		if err != nil {
			return err
		}

		_, err = ec2.NewRouteTableAssociation(ctx, "otherTableAssociation", &ec2.RouteTableAssociationArgs{
			SubnetId:     otherSubnet.ID(),
			RouteTableId: routeTable.ID(),
		})
		if err != nil {
			return err
		}

		return nil
	})
}
```
