### ISSUE TITLE
Improper partition used when generating SNS Topic ARN

### ISSUE THREAD

**Issue by farvour** [pulumi/pulumi-aws#3926]
### What happened?

In US Gov partitions, the provider generates the wrong ARN for the `GetTopicAttributes` call. This results in the `pulumi_aws.sns.Topic()` resource from failing to create when the lookup happens.

### Example

When using a provider in the US Gov (or China I'm sure too) creation of the topic fails:

```test_topic = aws.sns.Topic("test_tjf_1")```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.32.0
datadog     4.28.0
kubernetes  4.11.0
postgresql  3.11.0
python      unknown
random      4.16.1

Host     
OS       darwin
Version  13.6.6
Arch     arm64

This project is written in python: executable='/Users/tomfarvour/.local/share/virtualenvs/pulumi-FBQqJsZg/bin/python3' version='3.11.7'
```

### Additional context

This patch, which I presume patches the upstream TF provider, assumes it can use `aws` as the partition.

https://github.com/pulumi/pulumi-aws/blob/ba6524913c1a4b5b254bcc20465ed59b83b92b34/patches/0052-non-idempotent-sns-topic-creation.patch#L23-L28

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
It could be the case that our patch introduced a new failure mode:

```
	if !tfresource.NotFound(err) {
+		return diag.FromErr(err)
+	}
+
```

If we're not always predicting ARN correctly, this could surface a failure from by-ARN locator that wasn't a failure in upstream provider.
