### ISSUE TITLE
Next version of terraform will likely break us.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-aws#396]
The next version of terraform contains several changes around how they handle deleting apigateway Deployments and Stages.  Specifically, changes like https://github.com/terraform-providers/terraform-provider-aws/commit/8973a045c4185a107e16b9a240bba039585d5cf5#diff-b9c79ba2fce900769c374964689ecc90

This impacts us due to the order in which we destroy an apigateway.  Specifically, we destroy the Stage, then the Deployment.  This ends up throwing in their Deployment deleting code here https://github.com/terraform-providers/terraform-provider-aws/commit/8973a045c4185a107e16b9a240bba039585d5cf5#diff-b9c79ba2fce900769c374964689ecc90R184

The primary problem is that they are only resilient to hearing back 'ErrCodeNotFoundException' from the awssdk.  However, the error terraform actually gets when it calls GetStageInput is:

```
InvalidParameter: 1 validation error(s) found.
    - minimum field size of 1, GetStageInput.StageName
```

--

Figured more out with @swgillespie.  Core issue here is that we create Deployment with a stageName that is the empty string.  This is legal, and has the semantics we want.  But this fails later with terraform because AWS doesn't then allow querying for such an empty-stringed stage name.  The fix is likely for terraform to check for this and not do what they're doing.  We're investigating creating a repro for this based purely in terraform so we can file an issue on their side.

**Comment by CyrusNajmabadi** [comment]
This is caused by the following change in teh aws-sdk for go: https://github.com/aws/aws-sdk-go/pull/2323

Specifically, they now have added these checks that the names passed in in URIs cannot be null/empty.  When terraform themselves update to this sdk, this will be an issue for them.

**Comment by swgillespie** [comment]
It's likely that upstream Terraform now has this problem due to their uptake of the new AWS SDK: https://github.com/terraform-providers/terraform-provider-aws/pull/6771

**Comment by stack72** [comment]
@CyrusNajmabadi I think we can close this out - 0.12 was released so we should be good

**Comment by stack72** [comment]
ok, this definitely doesn't break us - I have been using pulumi this weekend on the latest providers built after 0.12

going to close this out for now - please reopen if we need to

**Comment by FirstInternetUser** [comment]
@ CyrusNajmabadi is there a work around for this if tied to a particular version of terraform? Can some updates be done in the UI?

**Comment by lukehoban** [comment]
@FirstInternetUser what problem exactly are you seeing?

**Comment by FirstInternetUser** [comment]
@lukehoban I have resolved the problem. The terraform was falling over due to log role not being set up. If I then ran it again, it complained about:
```
InvalidParameter: 1 validation error(s) found.
    - minimum field size of 1, GetStageInput.StageName
```

Once the api gateway logs role was set up, the issue was resolved.
