### ISSUE TITLE
PF Resources missing `.ComputeID`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-aws#4008]
https://github.com/pulumi/pulumi-terraform-bridge/pull/2029 introduced ID error checking for muxed providers. It has revealed 4 resources in AWS that don't check:
- aws_lambda_runtime_management_config
- aws_datazone_environment_blueprint_configuration
- aws_vpc_endpoint_service_private_dns_verification
- aws_vpc_endpoint_private_dns

Currently, these resources fail an assert (panicking) on create (or any other op).

**Comment by t0yv0** [comment]
For simpler stats tracking purposes my thinking is that impact/panic should be reserved for user-facing panics not build-time failures manifesting in this way, removing if that's ok? Happy to talk through if it is contentious.

**Comment by iwahbe** [comment]
I added the `impact/panic` because the issue *is* tracking a user-facing runtime panic. It's not a build failure until the next bridge release.

I didn't add a P1 because no user has reported the panic, but it is 100% a user facing panic.

**Comment by t0yv0** [comment]
Good callout. Bringing it back. I guess we had a build-time check but it failed to fire.

**Comment by iwahbe** [comment]
> Good callout. Bringing it back. I guess we had a build-time check but it failed to fire.

Yep. We have a build-time failure for PF providers, but pulumi-aws is a muxed provider (PF + SDK) and we didn't have a check for that. We will have that check on the next bridge release, and attempting to release is what caused us to discover the problem.
