### ISSUE TITLE
When importing self-managed certificate to ACM, remove the `validationMethod` from the code and don't show warning

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#4054]
From: #4046 

When you import a self-managed certificate into Pulumi, the `validationMethod` is set to `NONE` ([as it should be](https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#validationmethod_nodejs)) but the provider sees this as invalid.

The code generated looks like this (typescript example): 

```typescript
const my_cert = new aws.acm.Certificate("my-cert", {
  domainName: "test.pierskarsenbarg.com",
  keyAlgorithm: "RSA_2048",
  options: {
      certificateTransparencyLoggingPreference: "DISABLED",
  },
  subjectAlternativeNames: ["test.pierskarsenbarg.com"],
  validationMethod: "NONE",
}, {
  protect: true,
});
```

and you get a warning that looks like this:

```
aws:acm/certificate:Certificate resource 'my-cert' has a problem: expected validation_method to be one of ["EMAIL" "DNS"], got NONE. Examine values at 'my-cert.validationMethod'.
```

which is only technically correct, as in the case of self-managed certificates there doesn't need to be a `validationMethod` input.

My suggestion: don't include `validationMethod` input in the import code and hide the warning.

**Comment by t0yv0** [comment]
Thanks for this issue @pierskarsenbarg 

Relevant code extracts from `certificate.go`:

```go
certificateValidationMethodNone = "NONE"

func certificateValidationMethod(certificate *types.CertificateDetail) string {
	if certificate.Type == types.CertificateTypeAmazonIssued {
		for _, v := range certificate.DomainValidationOptions {
			return string(v.ValidationMethod)
		}
	}

	return certificateValidationMethodNone
}

func resoruceCertificateRead() {
      ...
	d.Set("validation_method", certificateValidationMethod(certificate))
}
        
type ValidationMethod string

// Enum values for ValidationMethod
const (
	ValidationMethodEmail ValidationMethod = "EMAIL"
	ValidationMethodDns   ValidationMethod = "DNS"
)


"validation_method": {
        Type:             schema.TypeString,
        Optional:         true,
        Computed:         true,
        ForceNew:         true,
        ValidateDiagFunc: enum.Validate[types.ValidationMethod](),
        ConflictsWith:    []string{"certificate_authority_arn", "certificate_body", names.AttrCertificateChain, names.AttrPrivateKey},
},
```

It seems to be just something that upstream does. 

This is a special variation of https://github.com/pulumi/pulumi-terraform-bridge/issues/1225 stemming from TF being more lax about Read results than is needed for Pulumi import to succeed. 

It might be interesting to include an automatic correction pass in the bridge that would remove optional properties from the `Read()` result IFF they fail to pass ValidateDiagFunc.
