### ISSUE TITLE
`aws.codebuild.Webhook` missing the `scopeConfiguration` property

### ISSUE THREAD

**Issue by Makeshift** [pulumi/pulumi-aws#4116]
The [`aws.codebuild.Webhook`](https://www.pulumi.com/registry/packages/aws/api-docs/codebuild/webhook/#aws-codebuild-webhook) resource is missing the [`scopeConfiguration`](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateWebhook.html#CodeBuild-CreateWebhook-request-scopeConfiguration) property.

This property also isn't in Terraform's provider, and I assume very few people use it, but it would be appreciated if it could be added as it's used to scope the webhook for self-hosted GitHub Actions runners on CodeBuild.

My workaround for the moment is to have a pulumi output that instructs the user how to create it via the CLI, which isn't ideal!

Thanks

**Comment by flostadler** [comment]
Hey @Makeshift, thanks for raising this issue! We'll need to get this enhancement implemented in the upstream terraform provider first.
There's already a feature request tracking this in the upstream repository (https://github.com/hashicorp/terraform-provider-aws/issues/38091) and it has a PR attached. I'd recommend upvoting both the issue and PR to get it prioritized as quickly as possible

**Comment by Makeshift** [comment]
This appears to have been resolved in a recent update. Thanks!
