### ISSUE TITLE
OpenZFS test failing on new pulumi version

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#4132]
### Describe what happened

https://github.com/pulumi/pulumi-aws/actions/runs/9703240405/job/26782216746?pr=4126#step:17:984

### Sample program

N/A

### Log output

N/A

### Affected Resource(s)

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Will be fixed in https://github.com/pulumi/pulumi-aws/pull/4131
