### ISSUE TITLE
ElasticCache ParameterGroup changes does not handled correctly

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-aws#427]
The `aws.elasticache.ParameterGroup` could contain parameters which needs a reboot, like the `databases` for Redis.  
When we're changing a reboot only parameter, pulumi tries to update the resource, but aws does not allow that: 
```
updating urn:pulumi:dev::dliver::storage:elasticCache:redis$aws:elasticache/replicationGroup:ReplicationGroup::dlv-dev-rd-ch: error updating Elasticache Replication Group (dlv-dev-rd-ch): InvalidParameterValue: The parameter databases has a different value in the requested parameter group than the current parameter group. This parameter value cannot be changed for a cache cluster.
```
Pulumi somehow should now when a replace necessary and when an update is enough.

**Comment by lukehoban** [comment]
This is effectively the same thing tracked by https://github.com/pulumi/pulumi-terraform/issues/225.  Until we support that, I don't believe there is any way to fix this - as the behaviour here comes from the static decisions made by the AWS Terraform provider.  

I'll go ahead and close this and add a comment to that issue about this use case.
