### ISSUE TITLE
Maven central publishes an out of date (6.41.0) version from 18-june-2024. Current version is 6.45.0

### ISSUE THREAD

**Issue by the-gigi** [pulumi/pulumi-aws#4289]
### Describe what happened

The current latest release 22-july-2024 is 6.45.0. See https://github.com/pulumi/pulumi-aws/releases/tag/v6.45.0

However, on maven central the stable version 6.41.0, and 6.42.0 is available as alpha that were published on  18-june-2024

### Sample program

N/A

### Output of `pulumi about`

```
CLI
Version      3.125.0
Go Version   go1.22.5
Go Compiler  gc

Host
OS       darwin
Version  14.1
Arch     arm64

Backend
Name           Gigis-MacBook-Pro.local
URL            s3://invisible-pulumi/aws?profile=ProdRW
User           gigi
Organizations
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I am sorry you are experiencing this. We were working through a key rotation initiated by the OSSRH repository transition, and several releases were indeed affected. The issue should be resolved in release https://github.com/pulumi/pulumi-aws/releases/tag/v6.45.2 and onwards. Is it acceptable for your use case to upgrade to 6.45.2?

**Comment by t0yv0** [comment]
Checking up on this today, it looks like the latest release didn't make it to Central either. We're troubleshooting the publishing process one more time, apologies for the disruption.

**Comment by t0yv0** [comment]
I can finally confirm 6.47.0 has the artifacts published to Central. Apologies for the disruption here!
