### ISSUE TITLE
Better solution for rolling updates of container cluster

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi-aws#43]
This is our version of https://github.com/hashicorp/terraform/issues/1552.

The better solution here may be container instances, when and if available, at which point we're not managing a group of instances at all.

**Comment by joeduffy** [comment]
I feel like we've gotten by with native ECS, EKS, etc. behavior here. Please do reopen with more details on what specifically we need to do here, if that's not adequate.

/cc @lukehoban @pgavlin
