### ISSUE TITLE
A parameter in route53 is incorrectly documented

### ISSUE THREAD

**Issue by cristi-** [pulumi/pulumi-aws#432]
Hi,

While trying to create a new `aws.route53.Record` A type I was looking at the parameters for `RecordArgs` and noticed that the documentation for this parameter is not correct. 
It should be:
```
(Required) The record type. Valid values are A, AAAA, CAA, CNAME, MX, NAPTR, NS, PTR, SOA, SPF, SRV and TXT.
```
Currently:
```
    /**
     * `PRIMARY` or `SECONDARY`. A `PRIMARY` record will be served if its healthcheck is passing, otherwise the `SECONDARY` will be served. See http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring-options.html#dns-failover-failover-rrsets
     */
```
The code:
https://github.com/pulumi/pulumi-aws/blob/9555aaff1fdf87ec6271fd620f29b1867d0aac29/sdk/nodejs/route53/record.ts#L256-L259

The documentation seems to be from the `type` parameter in `failoverRoutingPolicies`.

Thank you!

**Comment by stack72** [comment]
Hi @cristi-,

Firstly, my apologies that we have not gotten back to you on this bug. This is an area we are trying to improve on going forward.

Secondly, this actually seems to be a bug in our pulumi-terraform library. Therefore, I am going to close this out as a duplicate and we will be able to follow along with the upstream bug that is linked.

Please make any comments in the upstream library if needed

Thanks

Paul
