### ISSUE TITLE
Add the ability to associate a routing table to a subnet

### ISSUE THREAD

**Issue by synhershko** [pulumi/pulumi-aws#436]
From the AWS VPC docs:

> Each subnet must be associated with a route table, which controls the routing for the subnet. If you don't explicitly associate a subnet with a particular route table, the subnet is implicitly associated with the main route table.

There is currently no way (at least not in the JS code) to control the routing of a subnet. A routing-table can only be created for a VPC.

**Comment by jen20** [comment]
Hi @synhershko! This is actually an oddity of the underlying AWS API. You can control routing by associating a new route table with a subnet using an `aws.ec2.RouteTableAssociation`, like this:

```typescript
import * as aws from "@pulumi/aws";

const vpc = new aws.ec2.Vpc("network", {
    cidrBlock: "10.0.0.0/16",
});

const ig = new aws.ec2.InternetGateway("network-ig", {
    vpcId: vpc.id,
});

const subnet = new aws.ec2.Subnet("subnet", {
    vpcId: vpc.id,
    cidrBlock: "10.0.1.0/24",
});

const routeTable = new aws.ec2.RouteTable("rt", {
    vpcId: vpc.id,
    routes: [
        {
            cidrBlock: "0.0.0.0/0",
            gatewayId: ig.id,
        }
    ],
});

new aws.ec2.RouteTableAssociation("rta", {
    routeTableId: routeTable.id,
    subnetId: subnet.id,
});
```

Hope this helps!
