### ISSUE TITLE
Type checking failure when using ec2.LaunchTemplate and the iamInstanceProfile

### ISSUE THREAD

**Issue by karlmutch-cynch** [pulumi/pulumi-aws#4360]
### What happened?

When supplying an object to the function aws.ec2.LaunchTemplate(...) the iam_instance_profile parameter does not pass type checking.

It appears that what ever is passed into this parameter somehow becomes a string even if I supply a pulumi_aws.iam.instance_profile.InstanceProfile object

### Example

```
    ecs_instance_profile = aws.iam.InstanceProfile(f"{cluster_name}_ecs_iam_instance_profile",
                                                   role=ecs_instance_role.name)

...

        gpu_launch_config = aws.ec2.LaunchTemplate(f"{cluster_name}_ec2_gpu_launch",
            instance_type=asg_gpu_class,
            image_id=aws.ec2.get_ami(most_recent=True, 
                                owners=["amazon"],
                                filters=[{
                                    "name":"name", 
                                    "values":["amzn2-ami-ecs-hvm-*-x86_64-ebs"]}]
                                ).id,  
            iam_instance_profile=ecs_instance_profile,
            vpc_security_group_ids=security_groups_ids,
            name_prefix=f"abacus-{cluster_name}-gpu-",
            user_data=f"""{user_data}
echo "ip_resolve=4" >> /etc/yum.conf
echo "ECS_ENABLE_GPU_SUPPORT=true" >>/etc/ecs/ecs.config 
            """)

...

$ pulumi up
     └─ aws:ec2:LaunchTemplate  devel_ec2_gpu_launch           1 error; 3 warnings

Diagnostics:
  aws:ec2:LaunchTemplate (devel_ec2_gpu_launch):
    warning: Type checking failed:
    warning: Unexpected type at field "iamInstanceProfile":
               expected object type, got string type
    warning: Type checking is still experimental. If you believe that a warning is incorrect,
    please let us know by creating an issue at https://github.com/pulumi/pulumi-terraform-bridge/issues.
    This will become a hard error in the future.
    error: aws:ec2/launchTemplate:LaunchTemplate resource 'devel_ec2_gpu_launch' has a problem: Expected Object Type. Expected object, got string. Examine values at 'devel_ec2_gpu_launch.iamInstanceProfile'.
```

### Output of `pulumi about`

CLI
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.41.0
resource  docker  4.5.4
language  python  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

...

Backend
Name           pulumi.com
URL            https://app.pulumi.com/karlmutch-cynch
User           karlmutch-cynch
Organizations  karlmutch-cynch, cynch-ai
Token type     personal

Dependencies:
NAME           VERSION
pip            24.1
pulumi_aws     6.41.0
pulumi_docker  4.5.4
setuptools     70.1.1
wheel          0.43.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
@karlmutch-cynch you managed to sort out the issue with `iam_instance_profile`, right?

To get the userdata working you'll need to base64 encode it.

**Comment by karlmutch-cynch** [comment]
> [@karlmutch-cynch](https://github.com/karlmutch-cynch) you managed to sort out the issue with `iam_instance_profile`, right?
> 
> To get the userdata working you'll need to base64 encode it.
> 
> In python you can do this like this:
> 
> ```
> import base64
> encoded = base64.b64encode(b'your userdata string')
> ```

Yes that was sorted.  Thanks
