### ISSUE TITLE
Removing `minimumProtocolVersion` from `viewerCertificate` from DistributionArgs had no effect

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-aws#439]
This change https://github.com/pulumi/get.pulumi.com/commit/5547a2d621bf27968d2b13b1aa671abb9422ab96 removed the minimumProtocolVersion value from the viewerCertificate.  The intention that this change would move us back to the behavior we had before (where we did not specify anything and got some AWS default).

In practice, it seemed to have no effect.  The update for this showed no changes:

```
Previewing update (pulumi/get-pulumi-com-staging):
    pulumi:pulumi:Stack get-pulumi-com-get-pulumi-com-staging running 
    aws:s3:Bucket get.pulumi-staging.io-logs  
    aws:s3:Bucket get.pulumi-staging.io-bucket  
    aws:s3:BucketObject new/button.png  
    aws:s3:BucketObject install.ps1  
    aws:cloudfront:Distribution get.pulumi-staging.io-cf  
    aws:s3:BucketObject install.sh  
    aws:s3:BucketPolicy deny-list  
    aws:s3:BucketObject new/button.svg  
    aws:route53:Record get.pulumi-staging.io-record  
 
Resources:
    10 unchanged
Updating (pulumi/get-pulumi-com-staging):
    pulumi:pulumi:Stack get-pulumi-com-get-pulumi-com-staging running 
    aws:s3:Bucket get.pulumi-staging.io-logs  
    aws:s3:Bucket get.pulumi-staging.io-bucket  
    aws:cloudfront:Distribution get.pulumi-staging.io-cf  
    aws:s3:BucketObject new/button.svg  
    aws:s3:BucketPolicy deny-list  
    aws:s3:BucketObject install.ps1  
    aws:s3:BucketObject install.sh  
    aws:s3:BucketObject new/button.png  
    aws:route53:Record get.pulumi-staging.io-record  
 
Resources:
    10 unchanged
Duration: 6s
Permalink: https://app.pulumi.com/pulumi/get-pulumi-com-staging/updates/13
```

Explicitly setting the value to something different did cause the update to see a change, but simply removing the setting had no effect.  This seemed super weird to me, given that the value we had been setting is not the AWS default.

**Comment by pgavlin** [comment]
Neat.

Best guess is that this is a side-effect of the way we handle defaults: when `tfbridge` encounters a property in the TF or Pulumi schema that has a default value but has no value in the input bag, it either pulls the default from the old state (to avoid recomputing it) or computes a new default value. In this case, `minimum_protocol_version` property has a default value in the TF schema, a value in the resource's old state, and no value in the new inputs, so `tfbridge` decides to use the value from the old state.

**Comment by jen20** [comment]
Moving this to M22, as the fix (from @pgavlin) relies on some other work which is not likely to land until next week.
