### ISSUE TITLE
pulumi doesn't allow data larger than 16K for aws_imagebuilder_component

### ISSUE THREAD

**Issue by anilaws** [pulumi/pulumi-aws#4453]
### Describe what happened

While creating an aws_imagebuilder_component with a data field larger than 16KB it should be marked as valid based on the service quota. At the very least it should support the standard 64KB as that is the default service limit for a component size.

### Sample program

import * as aws from "@pulumi/aws";

export const test = new aws.imagebuilder.Component("test", {
    platform: "Linux",
    version: "1.0.0",
    data: `
schemaVersion: 1.0
name: test
description: testing image builder
phases:
  - name: build
    steps:
      - name: test
        action: ExecuteBash
        inputs:
          commands:
              - |
                #!/usr/bin/env bash
                ...................
    `,
});

### Log output

Diagnostics:
  aws:imagebuilder:Component (test):
    error: aws:imagebuilder/component:Component resource 'hardeningOneAl2023' has a problem: expected length of data to be in the range (1 - 16000), go

### Affected Resource(s)

aws.imagebuilder.Component

### Output of `pulumi about`

❯ pulumi about
CLI
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.50.0
resource  awsx    2.14.0
resource  docker  4.5.5
resource  docker  3.6.1
language  nodejs  unknown

Host
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v22.6.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/*****
User           ******
Organizations  ******
Token type     personal

Dependencies:
NAME            VERSION
typescript      5.5.4
@pulumi/aws     6.50.0
@pulumi/awsx    2.14.0
@pulumi/pulumi  3.129.0
@types/node     18.19.45

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @anilaws, thanks a lot for raising this! It looks like this limit is imposed by the [AWS API](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateComponent.html#imagebuilder-CreateComponent-request-data). Are you seeing different results elsewhere that indicate that this should be possible via the API? If so, we can investigate whether the linked document is out of date, and adjust the provider accordingly.
