### ISSUE TITLE
Certificate logical name change may not always re-attach to Listener

### ISSUE THREAD

**Issue by smithrobs** [pulumi/pulumi-aws#4466]
### Describe what happened

Customer reports possible variant of #1923 specific to `Certificate`.

### Prerequisites:
* Ability to create DNS CNAME for certificate. This is outside the scope of this issue. The issue assumes the CNAME is already created and valid for the `DomainName` in question.
* The `DomainName` will not change throughout this issue repro.

### Steps to reproduce:

1. `pulumi up` the sample program. Note this may require multiple `up`s depending on whether the DNS CNAME for the certificate is already created and correct and how long the validation takes.
2. Change the logical name of the `Certificate`:
`var primaryCert = new Aws.Acm.Certificate("example", new CertificateArgs`
to
`var primaryCert = new Aws.Acm.Certificate("example-chg", new CertificateArgs`

```
     Type                           Name                Plan        Info
     pulumi:pulumi:Stack            aws-cs-scratch-dev              
 +   ├─ aws:acm:Certificate         example-chg         create      
 ~   ├─ aws:lb:Listener             front_end           update      [diff: ~certificateArn]
 +-  ├─ aws:lb:ListenerCertificate  example             replace     [diff: ~certificateArn]
 -   └─ aws:acm:Certificate         example             delete      

Resources:
    + 1 to create
    ~ 1 to update
    - 1 to delete
    +-1 to replace
    4 changes. 36 unchanged
```

3. An `up` here will very likely fail as the `Certificate` is deleted/created and the new `Certificate` has not been validated:

```
aws:lb:Listener (front_end):
    error:   sdk-v2/provider2.go:472: sdk.helper_schema: modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-east-2:052848974346:listener/app/test-lb-tf/e93d81e93c873f36/43899502ff6b7ba9): operation error Elastic Load Balancing v2: ModifyListener, https response error StatusCode: 400, RequestID: db627dbd-699c-424f-a6cb-9545c3b5ab5d, api error UnsupportedCertificate: The certificate 'arn:aws:acm:us-east-2:052848974346:certificate/86264671-7825-46ac-9095-4d1dbaf1eacf' must have a fully-qualified domain name, a supported signature, and a supported key size.: provider=aws@6.51.1

  pulumi:pulumi:Stack (aws-cs-scratch-dev):
    error: update failed

  aws:lb:Listener (front_end):
    error: 1 error occurred:
        * modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-east-2:052848974346:listener/app/test-lb-tf/e93d81e93c873f36/43899502ff6b7ba9): operation error Elastic Load Balancing v2: ModifyListener, https response error StatusCode: 400, RequestID: db627dbd-699c-424f-a6cb-9545c3b5ab5d, api error UnsupportedCertificate: The certificate 'arn:aws:acm:us-east-2:052848974346:certificate/86264671-7825-46ac-9095-4d1dbaf1eacf' must have a fully-qualified domain name, a supported signature, and a supported key size.
```

4. If one waits a short indeterminate amount of time and retries the `up` with no changes it will succeed as the validation has occurred:

```
Type                           Name                Status               Info
pulumi:pulumi:Stack            aws-cs-scratch-dev                       
~   ├─ aws:lb:Listener             front_end           updated (1s)         [diff: ~certificateArn]
+-  ├─ aws:lb:ListenerCertificate  example             replaced (0.44s)     [diff: ~certificateArn]
-   └─ aws:acm:Certificate         example             deleted (16s)        

Resources:
~ 1 updated
- 1 deleted
+-1 replaced
3 changes. 37 unchanged
```

5. (Possible workaround) If a `CertificateValidation` resource is used, a single `up` after a logical name change of the `Certificate` will suffice as the program waits for the certificate to become validated:

```
     Type                              Name                Status               Info
     pulumi:pulumi:Stack               aws-cs-scratch-dev                       
 +   ├─ aws:acm:Certificate            example             created (5s)         
 +-  ├─ aws:acm:CertificateValidation  example             replaced (0.21s)     [diff: ~certificateArn]
 ~   ├─ aws:lb:Listener                front_end           updated (0.75s)      [diff: ~certificateArn]
 +-  ├─ aws:lb:ListenerCertificate     example             replaced (0.39s)     [diff: ~certificateArn]
 -   └─ aws:acm:Certificate            example-chg         deleted (16s)        

Resources:
    + 1 created
    ~ 1 updated
    - 1 deleted
    +-2 replaced
    5 changes. 36 unchanged
```

### Expected Behavior:

In all cases, if a logical name change occurs to a `Certificate` the `ListenerCertificate` is attached to the `Listener`.

### Actual Behavior:

Customer reports that on logical name change **with no usage of `CertificateValidation`** there is a possibility of the old `Certificate` being deleted, the new `Certificate` being created, but not being associated with the `ListenerCertificate`. The Pulumi program returns as completing successfully however the `Certificate` is not attached to the `Listener` and user requests fail.

### Sample program

```csharp
var vpc = new Vpc("scratch-vpc");

var primaryCert = new Aws.Acm.Certificate("example", new CertificateArgs
    {
        DomainName = "www.mycompany.com",
        ValidationMethod = "DNS",
        KeyAlgorithm = "RSA_2048",
        ValidationOptions = new[]
        {
            new Aws.Acm.Inputs.CertificateValidationOptionArgs
            {
                DomainName = "www.mycompany.com",
                ValidationDomain = "mycompany.com",
            },
        },
    });

var primaryCertValidation = new Aws.Acm.CertificateValidation("example", new()
    {
        CertificateArn = primaryCert.Arn
        // CNAME managed externally in this example
        // ValidationRecordFqdns = exampleRecord.Apply(exampleRecord => exampleRecord.Select(record => 
        // {
        //     return record.Fqdn;
        // }).ToList()),
    });

var frontEnd = new Aws.LB.LoadBalancer("front_end", new()
    {
        Name = "test-lb-tf",
        Internal = false,
        LoadBalancerType = "application",
        Subnets = vpc.PrivateSubnetIds,
        EnableDeletionProtection = false
    });

var frontEndTargetGroup = new Aws.LB.TargetGroup("frontend-tg", new()
    {
        Name = "frontend-lb-tg",
        Port = 80,
        Protocol = "HTTP",
        VpcId = vpc.VpcId,
    });

var frontEndListener = new Aws.LB.Listener("front_end",
    new ListenerArgs
    {
        LoadBalancerArn = frontEnd.Arn,
        Port = 443,
        Protocol = "HTTPS",
        SslPolicy = "ELBSecurityPolicy-2016-08",
        
        CertificateArn = primaryCert.Arn,
        // comment prev line and uncomment next to use CertificateValidation
        // CertificateArn = primaryCertValidation.CertificateArn,

        DefaultActions = new[]
        {
            new Aws.LB.Inputs.ListenerDefaultActionArgs
            {
                Type = "forward",
                TargetGroupArn = frontEndTargetGroup.Arn,
            },
        },
    });

// additional cert
var exampleListenerCertificate = new Aws.LB.ListenerCertificate("example", new()
    {
        ListenerArn = frontEndListener.Arn,
        CertificateArn = primaryCert.Arn,
        // comment prev line and uncomment next to use CertificateValidation
        // CertificateArn = primaryCertValidation.CertificateArn,
    });
```

### Affected Resource(s)

Aws.Acm.Certificate
Aws.LB.Listener
Aws.LB.ListenerCertificate

### Output of `pulumi about`

CLI          
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.51.1
resource  awsx    2.14.0
resource  docker  4.5.5
language  dotnet  unknown
resource  random  4.16.4

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in dotnet: executable='/Users/rsmith/.dotnet/dotnet' version='8.0.302'

Current Stack: rsmith-pulumi-corp/aws-cs-scratch/dev

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:dev::aws-cs-scratch::pulumi:pulumi:Stack::aws-cs-scratch-dev
pulumi:providers:awsx                                urn:pulumi:dev::aws-cs-scratch::pulumi:providers:awsx::default_2_14_0
awsx:ec2:Vpc                                         urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc::scratch-vpc
pulumi:providers:aws                                 urn:pulumi:dev::aws-cs-scratch::pulumi:providers:aws::default_6_51_1
pulumi:providers:aws                                 urn:pulumi:dev::aws-cs-scratch::pulumi:providers:aws::default_6_47_0
aws:ec2/vpc:Vpc                                      urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::scratch-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::scratch-vpc-private-2
aws:ec2/subnet:Subnet                                urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::scratch-vpc-private-3
aws:ec2/subnet:Subnet                                urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::scratch-vpc-private-1
aws:ec2/internetGateway:InternetGateway              urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::scratch-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::scratch-vpc-public-1
aws:ec2/subnet:Subnet                                urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::scratch-vpc-public-3
aws:ec2/subnet:Subnet                                urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::scratch-vpc-public-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::scratch-vpc-private-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::scratch-vpc-private-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::scratch-vpc-private-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::scratch-vpc-public-1
aws:ec2/eip:Eip                                      urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::scratch-vpc-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::scratch-vpc-public-3
aws:ec2/eip:Eip                                      urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::scratch-vpc-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::scratch-vpc-public-2
aws:ec2/eip:Eip                                      urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::scratch-vpc-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::scratch-vpc-public-3
aws:ec2/route:Route                                  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::scratch-vpc-public-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::scratch-vpc-private-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::scratch-vpc-public-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::scratch-vpc-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::scratch-vpc-private-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::scratch-vpc-private-1
aws:ec2/route:Route                                  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::scratch-vpc-public-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::scratch-vpc-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::scratch-vpc-2
aws:ec2/route:Route                                  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::scratch-vpc-public-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::scratch-vpc-public-2
aws:ec2/route:Route                                  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::scratch-vpc-private-3
aws:ec2/route:Route                                  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::scratch-vpc-private-1
aws:ec2/route:Route                                  urn:pulumi:dev::aws-cs-scratch::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::scratch-vpc-private-2
pulumi:providers:pulumi                              urn:pulumi:dev::aws-cs-scratch::pulumi:providers:pulumi::default
aws:lb/targetGroup:TargetGroup                       urn:pulumi:dev::aws-cs-scratch::aws:lb/targetGroup:TargetGroup::frontend-tg
aws:lb/loadBalancer:LoadBalancer                     urn:pulumi:dev::aws-cs-scratch::aws:lb/loadBalancer:LoadBalancer::front_end
aws:acm/certificate:Certificate                      urn:pulumi:dev::aws-cs-scratch::aws:acm/certificate:Certificate::example
aws:acm/certificateValidation:CertificateValidation  urn:pulumi:dev::aws-cs-scratch::aws:acm/certificateValidation:CertificateValidation::example
aws:lb/listener:Listener                             urn:pulumi:dev::aws-cs-scratch::aws:lb/listener:Listener::front_end
aws:lb/listenerCertificate:ListenerCertificate       urn:pulumi:dev::aws-cs-scratch::aws:lb/listenerCertificate:ListenerCertificate::example

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/rsmith-pulumi-corp
User           rsmith-pulumi-corp
Organizations  rsmith-pulumi-corp
Token type     personal

Dependencies:
NAME           VERSION
Pulumi         3.67.1
Pulumi.Aws     6.51.1
Pulumi.Awsx    2.14.0
Pulumi.Random  4.16.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@smithrobs just to confirm is the issue that everything completes successfully even though the attachment doesn't happen, or is it that the operation completes with the mentioned error?

```
modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-east-2:052848974346:listener/app/test-lb-tf/e93d81e93c873f36/43899502ff6b7ba9): operation error Elastic Load Balancing v2: ModifyListener, https response error StatusCode: 400, RequestID: db627dbd-699c-424f-a6cb-9545c3b5ab5d, api error UnsupportedCertificate: The certificate 'arn:aws:acm:us-east-2:052848974346:certificate/86264671-7825-46ac-9095-4d1dbaf1eacf' must have a fully-qualified domain name, a supported signature, and a supported key size.
```

The error would be what I would expect to happen in that situation. If no error is thrown then that is an issue that we can look into.

**Comment by smithrobs** [comment]
@corymhall the former - the report is (in no defined order):
the old Certificate was detached from the listener and deleted
the new Certificate was created but **not** attached to the listener
the `pulumi up` reported as completed successfully

**Comment by catoa** [comment]
> [@corymhall](https://github.com/corymhall) the former - the report is (in no defined order): the old Certificate was detached from the listener and deleted the new Certificate was created but **not** attached to the listener the `pulumi up` reported as completed successfully

@smithrobs the certificates are not being deleted. They just aren't being reattached to the load balancer following our renaming.

**Comment by smithrobs** [comment]
> [@smithrobs](https://github.com/smithrobs) the certificates are not being deleted. They just aren't being reattached to the load balancer following our renaming.

@catoa My mistake. I am going to close this issue and reopen a new one so as not to conflate issues.

For others experiencing this particular issue (`Certificate` logical name change causing error) below are two suggestions:

1. Make use of [aliases](https://www.pulumi.com/docs/iac/concepts/options/aliases/) to alias the certificate's new logical name to the old:
```csharp
// alias new "example-chg" to old "example"
var primaryCert = new Aws.Acm.Certificate("example-chg", new CertificateArgs
{
    // ...
}, new()
{
    Aliases = {new Alias { Name = "example" } }
});
```
2. Add CertificateValidation ([rsrc doc](https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificatevalidation/)) to wait for and ensure certificate validation is complete before attaching certificates. See the [issue](https://github.com/pulumi/pulumi-aws/issues/4466) for a code example.
