### ISSUE TITLE
[appsync] support for pipeline resolvers missing

### ISSUE THREAD

**Issue by BerndWessels** [pulumi/pulumi-aws#460]
It seems that the support for [pipeline resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html) is missing.

If so please take this as a feature request.

If not please point me to the documentation.

Thank you

**Comment by austin43** [comment]
Is there support for resolvers at all? I've not seen a Pulumi method for it and am wondering if I'm missing something.  

https://docs.aws.amazon.com/appsync/latest/APIReference/API_CreateResolver.html

**Comment by woeps** [comment]
Yesterday resolver an schema fuctionality was merged into Terraform 2.4: https://github.com/terraform-providers/terraform-provider-aws/pull/6451
I hope it will land in Pulumi soon.

**Comment by austin43** [comment]
@woeps thanks for the reply, looks like it was merged in to the pulumi provider today. https://github.com/pulumi/terraform-provider-aws

**Comment by jen20** [comment]
This was released in v0.18.1 of `pulumi-aws` - please feel free to reopen if you think something else is missing with respect to this feature!

**Comment by lukehoban** [comment]
> This was released in v0.18.1 of pulumi-aws

@jen20 Were the docs updated for that release?  I believe the feedback here is that these are not yet showing up in the docs.
