### ISSUE TITLE
Add support for Valkey engine to Elasticache.

### ISSUE THREAD

**Issue by j-fulbright** [pulumi/pulumi-aws#4620]
### Describe what happened

AWS has made a new engine for Elasticache available called Valkey. It appears all that really needs to happen is engine change.

### Sample program

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
Linking the upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/39641. Once this is added in the upstream provider we would release support in the next release.

**Comment by steveteuber** [comment]
This functionality has been released in [v5.73.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.73.0) of the Terraform AWS Provider.
Pulumi AWS [v6.57.0](https://github.com/pulumi/pulumi-aws/releases/tag/v6.57.0) is released as well but it doesn't support this functionality yet?

```
Diagnostics:
  aws:elasticache:Cluster (cluster):
    error: aws:elasticache/cluster:Cluster resource 'cluster' has a problem: expected engine to be one of ["memcached" "redis"], got valkey. Examine values at 'cluster.engine'.
```

**Comment by flostadler** [comment]
Currently the `CreateCacheCluster` API on the AWS side does not support `valkey`.
The corresponding upstream issue is currently blocked on that: https://github.com/hashicorp/terraform-provider-aws/issues/39905

You can start using Valkey with the `ReplicationGroup` resource: https://www.pulumi.com/registry/packages/aws/api-docs/elasticache/replicationgroup/

You can even deploy a single-primary cluster with the `ReplicationGroup` resource

**Comment by flostadler** [comment]
For reference, this is how you'd deploy a single node cluster using the `ReplicationGroup` resource:
```ts
import * as aws from "@pulumi/aws";

const valkey = new aws.elasticache.ReplicationGroup("valkey-test", {
    description: "valkey cluster",
    nodeType: "cache.m4.large",
    numCacheClusters: 1,
    engine: "valkey",
    port: 6379,
});
```

**Comment by flostadler** [comment]
I opened https://github.com/pulumi/pulumi-aws/issues/4771 to track Valkey support for the `CacheCluster` resource.

I'm going to close this issue for now because Valkey is supported according to AWS current API capabilities.
