### ISSUE TITLE
`aws.ecs.Cluster.get()` returned Cluster with `undefined` arn when lookup failed?

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-aws#465]
This is sort of a contrived example, but I had deployed an existing cluster and was attempting to use `Cluster.get()` to read it, so I could pluck off its arn.

I assumed that I would be able to pass the name of the cluster as the `id` argument to `.get` since other parts of the AWS API allow me to just use a name, however when I did this, I got back a `Cluster`'s who's `name` and `arn` properties ended up being undefined:

Here's information about the cluster itself, fetched by name via the aws CLI
```
[matell@matell tmp.7sesxBtLCK]$ aws ecs describe-clusters --clusters matt--a47e2e4
{
    "clusters": [
        {
            "status": "ACTIVE", 
            "statistics": [], 
            "tags": [], 
            "clusterName": "matt--a47e2e4", 
            "registeredContainerInstancesCount": 2, 
            "pendingTasksCount": 0, 
            "runningTasksCount": 8, 
            "activeServicesCount": 2, 
            "clusterArn": "arn:aws:ecs:us-west-2:153052954103:cluster/matt--a47e2e4"
        }
    ], 
    "failures": []
}
```

In my program I did the following:

```
import * as aws from "@pulumi/aws";

aws.ecs.Cluster.get("by-name", "matt--a47e2e4").arn.apply(a => console.log(`when looking up by name arn is ${a}`));
aws.ecs.Cluster.get("by-arn", "arn:aws:ecs:us-west-2:153052954103:cluster/matt--a47e2e4").arn.apply(a => console.log(`when looking up by arn arn is ${a}`));
```

When run, I see the following output:

```
[matell@matell tmp.7sesxBtLCK]$ pulumi update --skip-preview
Updating (dev):

     Type                 Name                Status     Info
     pulumi:pulumi:Stack  tmp.7sesxBtLCK-dev             2 messages
 >-  ├─ aws:ecs:Cluster   by-name             read       
 >-  └─ aws:ecs:Cluster   by-arn              read       
 
Diagnostics:
  pulumi:pulumi:Stack (tmp.7sesxBtLCK-dev):
    when looking up by name arn is undefined
    when looking up by arn arn is arn:aws:ecs:us-west-2:153052954103:cluster/matt--a47e2e4
 
Resources:
    1 unchanged

Duration: 3s
```

This was with 0.16.14 of the CLI and 0.16.8 of the provider.

I would have expected if looking up by name was not supposed to work that the call to `.get` would have thrown or something.

**Comment by ellismg** [comment]
@jen20, @lukehoban was also super confused when I showed this and had this to say:

> Hmm - so I'm actually rather confused how we would do what you are showing - the "importer" seems to do the opposite:
>
>https://github.com/terraform-providers/terraform-provider-aws/blob/03a8516d988de201ca3358f09b92a22f2507894d/aws/resource_aws_ecs_cluster.go#L40-L50

**Comment by ellismg** [comment]
> I would have expected if looking up by name was not supposed to work that the call to `.get` would have thrown or something.

I understand that get throwing is probably not reasonable as the call has to return promptly, but the read requires an RPC, but the behavior here was still super surprising to me.

**Comment by jen20** [comment]
I _think_ what might be going on here is that in the bridge, we don't expect importers to call `SetId`, and don't play nicely when they do. This resource is implemented in a rather strange manner upstream (it's not something I've looked at before) - I think this issue likely wants transferring over to `pulumi-terraform`.

**Comment by pgavlin** [comment]
Smells relates to this bug: https://github.com/pulumi/pulumi-terraform/issues/262

**Comment by lukehoban** [comment]
This is fixed - presumably by https://github.com/pulumi/pulumi-terraform/issues/262.
