### ISSUE TITLE
Python API needs opts on get_X functions to allow for different region providers

### ISSUE THREAD

**Issue by rswail** [pulumi/pulumi-aws#466]
Each of the AWS Resource classes (eg Vpc, Instance) take an opts parameter that can include an alternate provider. This allows resources to be created and tracked across regions.

However the equivalent get_x functions (eg get_vpc) do not, which means that only the default provider will be called when the function is invoked in pulumi.do_invoke.

This doesn't allow cross region queries via alternate providers.

**Comment by swgillespie** [comment]
Moved to https://github.com/pulumi/pulumi-terraform/issues/331 - thanks for the report!
