### ISSUE TITLE
Incorrect example in documentation

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-aws#469]
This example consists only of an import statement (which likely isn't required anyway) - I suspect the part of `pulumi-terraform` that extracts these is being overzealous.

https://pulumi.io/reference/pkg/nodejs/@pulumi/aws/apigateway/#Method-requestParameters

![image](https://user-images.githubusercontent.com/548524/53053812-4bcc7380-3457-11e9-9644-a3d8348e3241.png)

Thanks to @mfergus1 for reporting this in the community slack!

**Comment by stack72** [comment]
@jen20 I am going to close this out - it looks like it's correct now - ping me if not
