### ISSUE TITLE
Builds: minimal schema computation not working with bridge upgrades

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#4702]
### Describe what happened

https://github.com/pulumi/pulumi-aws/actions/runs/11614217568/job/32341851869?pr=4694

We need to either make sure it gets recomputed as part of `make tfgen` or take it out of repo and compute it as part of build so it's not tracked in source.

### Sample program

N/A

### Log output

N/A

### Affected Resource(s)

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
The same is true for provider upgrades as well

**Comment by t0yv0** [comment]
I'm not 100% sure but I think @corymhall fixed it in https://github.com/pulumi/pulumi-aws/pull/4823

If he didn't I'll pick up on Monday to tidy it up.

**Comment by t0yv0** [comment]
This should be fixed in https://github.com/pulumi/pulumi-aws/pull/4829
