### ISSUE TITLE
Errant `===`'s in waitForSteadyState` docs

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-aws#472]
This block has a `====` at the end:

https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/ecs/service.ts#L200-L204

It makes VSCode think that this text should be a header, which causes poor rending:

![image](https://user-images.githubusercontent.com/9602953/53203350-c9ba8700-35dd-11e9-9f78-ebb6108d740a.png)

**Comment by stack72** [comment]
@ellismg looks like this is no longer the case:

```
/**
     * If `true`, Terraform will wait for the service to reach a steady state (like [`aws ecs wait services-stable`](https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html)) before continuing. Default `false`.
     */
    public readonly waitForSteadyState!: pulumi.Output<boolean | undefined>;
```

I am going to close this out - if this is still an issue, let's reopen it

Paul
