### ISSUE TITLE
@pulumi/aws@0.16.9 fails with an unhandled error during update phase when executing within AWS CodeBuild

### ISSUE THREAD

**Issue by robertbullen** [pulumi/pulumi-aws#479]
Error message:

> error: an unhandled error occurred: Program exited with non-zero exit code: 1

Running the exact same pulumi script in the following environments gives these results:

| Machine | OS | @pulumi/aws Version | Result |
|---|---|---|---|
| MacBook Pro | macOS 10.14.2 | 0.16.9 | ✅ |
| AWS CodeBuild | image aws/codebuild/nodejs:8.11.0 | 0.16.8 | ✅ |
| AWS CodeBuild | image aws/codebuild/nodejs:8:11:0 | 0.16.9 | ❌ |

The last resource printed to the console before the unhandled error occurs is consistently an `aws:waf:WebAcl`. So there might be a problem with the latest AWS provider plugin when it is interacting with a WebAcl resource while running on Linux (the CodeBuild image mentioned above is based on ubuntu:14.04.5).

**Comment by jen20** [comment]
Hi @robertbullen! Sorry for the delay in replying here. Is this still occurring with the latest versions (v0.18.3)? If so, do you have any more information about how you are using the `WebAcl` resource in your program to help diagnose?

**Comment by stack72** [comment]
Hi @robertbullen,

I am going to close this out - it's been idle for a while now. If you are still having the same issue, please do recomment on the issue and we can reopen it

Thanks again 

Paul
