### ISSUE TITLE
Panic on latest version v6.62.0

### ISSUE THREAD

**Issue by corymhall** [pulumi/pulumi-aws#4863]
### Describe what happened

Using the latest version will fail with a panic

```
panic: fatal: error An assertion has failed: Failed to read schema-embed.json. source error: read schema-embed.json/: is a directory

goroutine 1 [running]:

```

### Sample program

```ts

new aws.s3.BucketV2('bucket');
```

### Output of `pulumi about`

CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME             VERSION

resource  aws              6.62.0

Host     
OS       darwin
Version  15.1.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jcla490** [comment]
same problem here, pinning to previous version `v6.61.0` for now. Thanks for posting this bug report

**Comment by jaxxstorm** [comment]
Looks to be caused by https://github.com/pulumi/pulumi-aws/commit/ea37daecbb549cbf52749147da1e1cb59c2d3cbe

my guess is 

```
//go:embed schema*embed.json
var schemas embed.FS
```

**Comment by t0yv0** [comment]
Apologies for the disruption. A patch release will be coming shortly with the fix.

**Comment by aaomidi** [comment]
I think adding some test coverage to prevent a regression here may be useful?

**Comment by blampe** [comment]
@aaomidi absolutely. In particular this snuck in due to https://github.com/pulumi/ci-mgmt/issues/967 which we're fixing right now.
