### ISSUE TITLE
AWS lambda Nodejs 22 runtime is missing

### ISSUE THREAD

**Issue by curtdept** [pulumi/pulumi-aws#4875]
### Describe what happened

AWS added it to go SDK in https://github.com/aws/aws-sdk-go-v2/blob/release-2024-11-20/service/lambda/CHANGELOG.md#v1670-2024-11-20
That was bumped in the TF provider on https://github.com/hashicorp/terraform-provider-aws/commit/5698f695d8f3163dd4173ef5ee9455f06f07ff22 and released with 5.77

It doesn't look like the bridge is regenerating this (and other related) file(s)
https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/enums/lambda/index.ts
https://github.com/pulumi/pulumi-aws/blob/master/sdk/java/src/main/java/com/pulumi/aws/lambda/enums/Runtime.java

This was present in 6.62 prior to retraction as well.

### Sample program

aws.lambda.Runtime.NodeJS22dX

### Output of `pulumi about`

CLI
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.62.0
resource  aws     6.61.0
resource  awsx    2.19.0
resource  docker  4.5.7
resource  docker  3.6.1
language  nodejs  unknown

Host
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @curtdept, the provider does not automatically pull in new enum values for the lambda runtimes. This is maintained manually at the moment: https://github.com/pulumi/pulumi-aws/blob/384111d99980bd10f9df4c96197ab98c1e2fa1d3/provider/types.go#L227-L243

I checked `6.62.0` to be sure and it wasn't part of that release: https://github.com/pulumi/pulumi-aws/blob/9d0a03f14938f4aeb4e83c97597799c8cdcd644e/sdk/nodejs/types/enums/lambda/index.ts#L6-L22

I'm gonna track this as an enhancement and create a PR right away to add this new runtime

**Comment by curtdept** [comment]
@flostadler thank you :)

The 6.62 part was ambiguously worded on my part. I mean the runtime values were also missing in that release.
