### ISSUE TITLE
BucketLifecycleConfigurationV2 has no nonCurrent version action configuration

### ISSUE THREAD

**Issue by davidfries** [pulumi/pulumi-aws#4877]
### Describe what happened

When creating an `aws.s3.BucketLifecycleConfigurationV2` resource, one would expect to control what happens to objects once they expire. The only "rule type" that is allowed is an `expiration` rule.  If you go into your bucket lifecycle rule in the AWS console and check the box that says "Permanently delete noncurrent versions of objects", a new ` noncurrent version action ` is created in the console. **When running a `pulumi preview` after checking the "Permanently delete noncurrent versions of objects" box, the stack shows a diff in the rules configuration.** 

![Image](https://github.com/user-attachments/assets/c545567e-08f5-43b7-aba2-2f2a43e446e1)

![Image](https://github.com/user-attachments/assets/63177cfe-0388-4c16-abaf-c4d66f05101d)

### Sample program

```                  
const bucketName = "superdupermegatestbucketforpulumi"
const bucketLifeCycle = new aws.s3.BucketLifecycleConfigurationV2(`${name}-bucket-lifecycle`, {
                        bucket: bucketName,
                        rules: [{
                            id: "DeleteObjects",
                            status: "Enabled",
                            filter: {
                                prefix: "",
                            },
                            expiration: {
                                days: 3,
                                expiredObjectDeleteMarker: true,
                            },
                                
                        }],
                    });
```

### Log output

`  aws:s3:BucketLifecycleConfigurationV2 [redacted]-bucket-lifecycle update [diff: ~rules] `

### Affected Resource(s)

`aws.s3.BucketLifecycleConfigurationV2`

### Output of `pulumi about`

```
Plugins
KIND      NAME        VERSION
resource  aws         6.57.0
resource  awsx        2.16.1
resource  cloudflare  5.42.0
resource  docker      4.5.7
resource  docker      3.6.1
resource  eks         2.8.1
resource  kubernetes  4.18.3
language  nodejs      unknown

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in nodejs: executable='/home/dj/.nvm/versions/node/v21.7.2/bin/node' version='v21.7.2'

[redacted stack resources]

Found no pending operations associated with development

Backend        
Name           pop-os
URL            file://~
User           dj
Organizations  
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/awsx        2.16.1
@pulumi/kubernetes  4.18.3
typescript          4.9.5
@pulumi/pulumi      3.137.0
@types/node         18.19.63
npm-upgrade         3.1.0
prettier            3.3.3
zod                 3.23.8
@pulumi/aws         6.57.0
@pulumi/cloudflare  5.42.0
@pulumi/eks         2.8.1
```

### Additional context

I would want to be able to configure what happens to objects once they expire with Pulumi. It seems this might just be a missing type in the typescript package? Essentially, the end goal is after x number of days, expire the objects in the bucket, then after those x days, delete all expired objects.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @davidfries, `BucketLifecycleConfigurationV2 ` has two nonCurrent related actions available.
- [`noncurrentVersionExpiration`](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketlifecycleconfigurationv2/#noncurrentversionexpiration_nodejs): Can be used to delete non-current object versions
- [`noncurrentVersionTransitions`](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketlifecycleconfigurationv2/#noncurrentversiontransitions_nodejs): Can be used to move non-current objects to other storage classes

[This example](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketlifecycleconfigurationv2/#creating-a-lifecycle-configuration-for-a-bucket-with-versioning) shows both of them at play.
You should be able to use the `noncurrentVersionExpiration` option for your usecase.

**Comment by davidfries** [comment]
Hey @flostadler that did the trick! I guess the of `noncurrentVersionTransitions` was a little confusing in-regards to whether it deletes or does something else. I'll go ahead and mark this closed, thanks for your time and help!
