### ISSUE TITLE
aws.ec2.Eip "allocationId" output is undefined.

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-aws#498]
When instantiating a `new aws.ec2.Eip`, I expect to be able to get the resulting allocation ID output from the variable described here: https://pulumi.io/reference/pkg/nodejs/@pulumi/aws/ec2/#Eip-allocationId.

This seems to return undefined.  The allocation ID is instead under `.id`

```
const eip = new aws.ec2.Eip("test", {
        vpc: true,
});

eip.id.apply(i => console.log('ALLOCATION', i))
eip.allocationId.apply(i => console.log('ALLOCATION', i))
```

The first log shows the correct allocation ID, the second shows undefined.

**Comment by lukehoban** [comment]
This appears to be rooted in an issue in the upstream Terraform AWS provider that `allocation_id` is defined to be an output of an `eip` resource, but is never set to a value:

https://github.com/terraform-providers/terraform-provider-aws/blob/03a8516d988de201ca3358f09b92a22f2507894d/aws/resource_aws_eip.go#L53

This means it will always be `undefined`.  The documentation for this resource doesn't list it - so it's probably rare for Terraform users to try to use it - but if they do they will run into the same problems. 

We should consider whether we can suppress this field to closer align with the reality that it will never be set.

There appear to be several other properties of this resource that similarly are marked as outputs but will never be set to a value.

**Comment by jen20** [comment]
I've submitted a pull request upstream to the Terraform AWS provider to fix this particular instance, but I think more generally we should consider a way to opt out of having fields mapped in `pulumi-terraform`. I'll open an issue there to track that, and leave this one open until upstream merges.

**Comment by adaniline-traderev** [comment]
Allocation id is empty even after reading the EIP from AWS:

```
const eip = new aws.ec2.Eip(`${baseName}-nat-eip-${index + 1}`, {}, subnetParent);
const natGateway = new aws.ec2.NatGateway(`${baseName}-nat-gw-${index + 1}`, {
                allocationId: eip.id.apply((_id) => aws.ec2.Eip.get(`created-eip-${index + 1}`, _id).allocationId),
                subnetId: publicSubnets[index].id,
                tags: natGatewayTags,
            }, subnetParent);


error: aws:ec2/natGateway:NatGateway resource 'eks-qa1-nat-gw-2' has a problem: "allocation_id": required field is not set
```
This really blocks us - we cannnot create a vpc with Pulumi

**Comment by lukehoban** [comment]
Note that the `id` property should contain the allocation id - so this should not be blocking.

**Comment by adaniline-traderev** [comment]
Yes, thank you, my issue was that I was not setting eip.vpc to true, I resolved it now

**Comment by timmyers** [comment]
Yeah, feel free to close this since there is a simple alternative.  Especially if the docs were potentially updated (though I'm sure those are probably auto-generated).

**Comment by KaoruDev** [comment]
I must be doing something wrong here:

```python
nat_ip = ec2.Eip("kaoru-test-nat-eip", tags=DEFAULT_TAGS)

ec2.NatGateway(
    'kaoru-nat',
    allocation_id=nat_ip.id.apply(lambda x: x),
    subnet_id=subnet_a.id,
    tags=DEFAULT_TAGS,
)
```

cause I'm unable to get a NAT created.

**Comment by KaoruDev** [comment]
ah, nvm, found the issue, i didn't have an internet gateway setup in the VPC i assigned the Nat to, sorry AWS newb here. https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html

**Comment by irl-segfault** [comment]
> Yes, thank you, my issue was that I was not setting eip.vpc to true, I resolved it now

weird that this causes the allocationId to not be accessible, because it definitely still would exist in AWS
