### ISSUE TITLE
Policy not found with pulumi destory

### ISSUE THREAD

**Issue by adaniline-traderev** [pulumi/pulumi-aws#501]
I have a chart that creates an IAM policy and deploys the KIAM helm chart.

After it was deploy, if I do `pulumi refresh`, it does not find any updates

After that when I do `pulumi destroy`, I get 404 error:

```
  aws:iam:PolicyAttachment (kiamRoleAssumeK8SPolicy):
    error: Plan apply failed: deleting urn:pulumi:test1::kiam::aws:iam/policyAttachment:PolicyAttachment::kiamRoleAssumeK8SPolicy: [WARN] Error removing user, role, or group list from IAM Policy Detach eksCluster-eksCluster-7252959-assume-pod-roles-attachment:
    – NoSuchEntity: Policy arn:aws:iam::082894742960:policy/eksCluster-eksCluster-7252959-assume-pod-roles was not found.
        status code: 404, request id: 44cbaa47-4665-11e9-b604-4fdfe40cdda9
```

```
Pulumi version: v0.17.1
Plugin kubernetes [resource] version: 0.21.0
 Plugin aws [resource] version: 0.17.1
```

**Comment by d-nishi** [comment]
@adaniline-traderev -- can you share the example IAM policy and the helm chart you are deploying. I will recreate the issue and revert back with my findings.

**Comment by stack72** [comment]
Hi @adaniline-traderev 	

We haven't heard back from you on this issue, therefore I am going to close this out for now. If you are still having the same issue, please do comment and we can reopen it

Thanks

Paul
