### ISSUE TITLE
Add "Name" tag when creating resources

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-aws#53]
When creating an instance such as `aws.ec2.Instance`, should use the first constructor argument to automatically name the resource using the `Name` property in the `tags` collection. 

Should do this for all resources that are named, not just EC2.

**Comment by jen20** [comment]
I'm not sure this is a great idea in current form, though I do like the idea of attaching the "Pulumi name" in a tag in a similar manner to that described in #113.

My reasoning is that in AWS, the `Name` tag is used as a display name in the console for many resources, and consequently operators are likely to want to assign human-readable names where possible.

**Comment by joeduffy** [comment]
I agree with @jen20 here. Retiring this work item in favor of https://github.com/pulumi/pulumi-aws/issues/113.
