### ISSUE TITLE
IgnoreChanges failes on a kubernetes tag

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-aws#553]
I have a weird issue with ignoreChanges, there's a resource in a ComponentResource class:
```
    const vpc = new aws.ec2.Vpc(
      vpcName,
      {
        cidrBlock: cidrBlock,
        enableDnsHostnames: true,
        enableDnsSupport: true,
        tags: Object.assign(
          {
            Name: vpcName
          },
          args.resourceTags
        )
      },
      { parent: this }
    )
```
if I change this to
```
    const vpc = new aws.ec2.Vpc(
      vpcName,
      {
        cidrBlock: cidrBlock,
        enableDnsHostnames: true,
        enableDnsSupport: true,
        tags: {
          Name: vpcName
        }
      },
      { parent: this, ignoreChanges: ['tags'] }
    )
```
and trying to update the stack, I got an error:
```
  aws:ec2:Vpc (dlv-sbx-vpc):
    error: aws:ec2/vpc:Vpc resource 'dlv-sbx-vpc' has a problem: tags (kubernetes): '' expected type 'string', got unconvertible type 'map[string]interface {}'
 
  pulumi:pulumi:Stack (dliver-dlv-sbx):
    error: Running program '/home/ncsibra/dev/prmrgt-infra/pulumi/dliver' failed with an unhandled exception:
    Error: invocation of aws:ec2/getVpc:getVpc returned an error: transport is closing
        at monitor.invoke (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@pulumi/pulumi/runtime/invoke.js:74:33)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/grpc/src/client_interceptors.js:1205:9)
        at InterceptingListener._callNext (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/grpc/src/client_interceptors.js:845:24)
```
This resource has a tag, added by EKS, something like `kubernetes.io/cluster/dlv-sbx-cluster-eks-197239a: shared`, this tag not exist in pulumi code, because vpc created first, then EKS, so unable to add it from pulumi, but after a refresh, pulumi tries to remove that, but that would cause problems with resources handled by kubernetes.
So I tried to add ignoreChanges, but looks like it want to do something with the tags anyway and unable to parse it.

**Comment by lukehoban** [comment]
@ncsibra I haven't been able to reproduce this yet - and I feel like there is a step in your repro I am missing.  Where is the `kubernetes` tag coming from?

If I deploy your first example, then manually add a tag, then refresh, then `pulumi preview --diff` I see:

```
$ pulumi preview --diff
Previewing update (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws553::pulumi:pulumi:Stack::aws553-dev]
    ~ aws:ec2/vpc:Vpc: (update)
        [id=vpc-0fd4f9fb432983070]
        [urn=urn:pulumi:dev::aws553::aws:ec2/vpc:Vpc::myvpcname]
      ~ tags: {
            Foo       : "bar"
            Name      : "myvpcname"
          - kubernetes: "something"
        }
```

If I then add `ignoreChanges: ["tags"]` as in your second example, I then see:

```
$ pulumi preview --diff
Previewing update (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws553::pulumi:pulumi:Stack::aws553-dev]
Resources:             
    2 unchanged
```

I feel like there is something unrelated to `ignoreChanges` going on here - but I also feel like it's due to something that is not part of the code snippet shared here.

If you have any more details on how to reproduce this - please let me know.

**Comment by ncsibra** [comment]
The tag added by EKS, our stack does not have this tag for the vpc, and because the vpc has to be created first, then the EKS cluster, impossible to do that without a custom resource.
I assumed the problem caused by the more complex tag, containing "/" characters, etc, did you tried with the exact tag I wrote?
