### ISSUE TITLE
[appsync] neglected for more than 6 month?

### ISSUE THREAD

**Issue by BerndWessels** [pulumi/pulumi-aws#559]
According to [this](https://github.com/terraform-providers/terraform-provider-aws/blame/dc66b70d59c8c2fabd1dd35cc67aa3d44d8fde21/vendor/github.com/aws/aws-sdk-go/service/appsync/api.go#L3769) - terraform supports `relational_database` as an `appsync` `data source` for about half a year already.

- Why is `pulumi` not yet updated?
- Is this a sign that there is no more ongoing investment in `pulumi`?
- I really like `pulumi` but it is a hard sell especially into big enterprises if important features are neglected like this :(

**Comment by lukehoban** [comment]
Please see https://github.com/pulumi/pulumi-aws/issues/461#issuecomment-492401459.

The `@pulumi/aws` package is up to date with v2.9.0 of the Terraform AWS provider.

**Comment by BerndWessels** [comment]
Closing in favor of #461
