### ISSUE TITLE
Add constants for RDS engine names and engine modes

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-aws#578]
It would be nice to provide constants for RDS cluster engine names and engine names - lists of valid values are available here:

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html

**Comment by lukehoban** [comment]
FWIW - I would still *love* to find a way to auto generate these if possible from published API specifications.  Even if some manual mapping is required - being able to automatically stay up-to-date and to automatically identify when new enums are added that should be mapped would be invaluable relative to incrementally adding these manually one-by-one.

**Comment by stack72** [comment]
There is no direct API for getting these right now - but I agree that we will need to do that soon...
