### ISSUE TITLE
Intermittent failures when removing `BucketNotification`s

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-aws#588]
We observed the following failure when running our integration tests on examples:

```
[ /examples/cloud-js-thumbnailer ]  -  aws:s3:BucketNotification onNewVideo **deleting failed** error: Plan apply failed: deleting urn:pulumi:p-it-travis-job-cloud-js-t-b6a1df4e::video-thumbnailer::cloud:bucket:Bucket$aws:s3/bucket:Bucket$aws:s3/bucketNotification:BucketNotification::onNewVideo: Error deleting S3 notification configuration: OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
```

In this case, we simply spin up the program (which creates a bucket notification) and then immediately destroy it.  I can imagine that the lack of time between these two operations could lead to the above.  I suspect the upstream provider should be tolerant to these issues.

Per the [S3 Error Response documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) it feels like simply retrying here would have been sufficient.

**Comment by stack72** [comment]
Hi @ellismg 	

Is this still an issue?

Paul

**Comment by lukehoban** [comment]
Did we disable that test in the examples repo due to this?

**Comment by ellismg** [comment]
We did not disable the test.  I assume this is still an issue but I have not looked at the upstream Terraform provider to see if there have been any changes recently in this area.

**Comment by stack72** [comment]
ok, nothing has changed upstream here for a retry of removing the bucket notifications. I think we need to raise a bug up there as it's 100% an upstream issue.

Thoughts?

**Comment by ellismg** [comment]
@stack72 I think that is correct.  Looking at their provider it does not seem to handle this error message, but I believe they could detect it and return resource.RetryableError here and everything would just work.  This is likely a problem for both Delete and Update.

**Comment by stack72** [comment]
Ok, I've been monitoring the test runs of these examples. This isn't flakey anymore - I am going to close this out for now and then we can revisit this if this is a problem again later
