### ISSUE TITLE
elasticsearch.DomainPolicy does not accept `pulumi.output()`

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-aws#627]
The elasticsearch `DomainPolicy` resource does not accept `pulumi.output(...)` as the value.

```
new aws.elasticsearch.DomainPolicy('elastic-search', {
  domainName: elasticSearchDomain.domainName,
  accessPolicies: pulumi.output({
    Version: '2012-10-17',
    Statement: [
      {
        Action: ['es:*'],
        Effect: 'Allow',
        Resource: `${elasticSearchDomain.arn}/*`,
        Condition: {
          IpAddress: {
            'aws:sourceIp': ['10.60.0.0/16']
          }
        }
      }
    ]
  })
});
```

**Comment by lukehoban** [comment]
I believe you need to use `pulumi.interpolate` here to build the resource ARN. 

```
Resource: pulumi.interpolate`${esDomain.arn}/*`,
```

**Comment by lukehoban** [comment]
BTW - what error did you get when you tried the original code above?  With recent Pulumi libraries, I would have expected you would get an informative error message suggesting that you needed to make this change.

**Comment by lukehoban** [comment]
I'm going to close this out - as I don't believe there is any Pulumi issue here - and I believe the approach above will work here.  But would be interested in more details on error messages in case there is something further we can do to guide users in the right direction here.

**Comment by nesl247** [comment]
![image](https://user-images.githubusercontent.com/1037526/60105786-00daa980-9732-11e9-8c6e-49bcd002ba69.png)

This is the error given by the IDE. I am using the latest versions of pulumi as of this morning. This is with and without `pulumi.interpolate` as you have mentioned.

**Comment by stack72** [comment]
Ok @nesl247 - just to circle back on this one, I just tried this with Pulumi interpolate and it worked as expected. You are indeed correct that you would need to make the apply with the pulumi.output to make it into the correct format

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

export const domain = new aws.elasticsearch.Domain("example", {
    domainName: "example",
    elasticsearchVersion: "1.5",
    clusterConfig: {
        instanceType: "r4.large.elasticsearch",
    },
});

export const policy = new aws.elasticsearch.DomainPolicy("elastic-search", {
    domainName: domain.domainName,
    accessPolicies: pulumi.interpolate`{
      "Version": "2012-10-17",
      "Statement": [
          {
              "Action": "es:*",
              "Principal": "*",
              "Effect": "Allow",
              "Condition": {
                  "IpAddress": {"aws:SourceIp": "127.0.0.1/32"}
              },
              "Resource": "${domain.arn}/*"
          }
      ]
  }
  `,
});
```

One word of note, I have added the ability to pass an IAM Policy Document as follows:

```
import * as aws from "@pulumi/aws";

export const domain = new aws.elasticsearch.Domain("example", {
    domainName: "example",
    elasticsearchVersion: "1.5",
    clusterConfig: {
        instanceType: "m4.large.elasticsearch",
    },
    ebsOptions: {
        ebsEnabled: true,
        volumeSize: 20,
    },
});

export const policy = new aws.elasticsearch.DomainPolicy("elastic-search", {
    domainName: domain.domainName,
    accessPolicies: {
        Version: "2012-10-17",
        Statement: [{
            Effect: "Allow",
            Principal: "*",
            Action: "es:*",
            Resource: `${domain.arn}/*`,
            Condition: {
                IpAddress: {
                    "aws:SourceIp": "127.0.0.1/32",
                }
            },
        }],
    },
});
```

**Comment by nesl247** [comment]
Your solution is exactly what I really wanted, so thanks for that!

**Comment by stack72** [comment]
@nesl247 I found 1 tiny bud with this - it’s to do with passing a resource - I will take care of that and get a new version released tomorrow and ping you here about it

**Comment by stack72** [comment]
ok @nesl247 just a FYI, you will be able to monitor #665 - when that has been merged and released, then you will be able to run the following:

```
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

export const domain = new aws.elasticsearch.Domain("example", {
    domainName: "example",
    elasticsearchVersion: "1.5",
    clusterConfig: {
        instanceType: "m4.large.elasticsearch",
    },
    ebsOptions: {
        ebsEnabled: true,
        volumeSize: 20,
    },
});

export const policy = new aws.elasticsearch.DomainPolicy("elastic-search", {
    domainName: domain.domainName,
    accessPolicies: {
        Version: "2012-10-17",
        Statement: [{
            Effect: "Allow",
            Principal: "*",
            Action: "es:*",
            Resource: pulumi.interpolate`{${domain.arn}/*)}`,
            Condition: {
                IpAddress: {
                    "aws:SourceIp": "127.0.0.1/32",
                }
            },
        }],
    },
});
```

Note the use of `pulumi.interpolate` around the need to create the interpolated Resource.

**Comment by stack72** [comment]
@nesl247 apologies for the silence here - I just fixed this all up and my code from above will now work for you :)

**Comment by nesl247** [comment]
Thanks!
