### ISSUE TITLE
Cannot override bucket name

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi-aws#637]
I'm attempting to write some pulumi code to manage an [S3-based website](https://medium.com/@kyle.galbraith/how-to-host-a-website-on-s3-without-getting-lost-in-the-sea-e2b82aa6cd38).

For this to work, you must be able to specify a bucket name exactly. This doesn't seem to be happening, though?

```python
    web_bucket = s3.Bucket(
        f'{name}-bucket',
        __name__=domain,
        website={
            "index_document": "index.html"
        },
        website_domain=domain,
        **opts(parent=self),
    )
```

Is producing bucket names like `dingbots.dev-6fe3d77`, and it's not clear how to override this.

**Comment by lukehoban** [comment]
I believe that passing `bucket=domain` instead of `__name__=domain` should accomplish what you want here.

**Comment by astronouth7303** [comment]
What is `__name__` supposed to be, anyways?

**Comment by astronouth7303** [comment]
Yes, that did it.
