### ISSUE TITLE
Failure deleting aws.ssm.Document

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#641]
After creating an `aws.ssm.Document`, attempting to destroy it leads to this:

`error: Plan apply failed: unexpected null property parameter[0]`

This appears to ultimately be due to this:

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_document.go#L282

It’s not clear whether this is a bug in the provider, or a bug in the Pulumi Terraform bridge, or both.

**Comment by stack72** [comment]
Closing this in favour of #649
