### ISSUE TITLE
apigateway.DomainName() does not accept documented security_policy

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi-aws#676]
```python
    domainname = apigateway.DomainName(
        f"{name}-domain",
        domain_name=domain,
        regional_certificate_arn=cert.cert_arn,
        security_policy="TLS_1_2",
        endpoint_configuration={
            'types': 'REGIONAL',
        },
        **opts(parent=self)
    )
```

```
    TypeError: __init__() got an unexpected keyword argument 'security_policy'
```

Per https://www.pulumi.com/docs/reference/pkg/python/pulumi_aws/apigateway/

**Comment by lukehoban** [comment]
This was added very recently. Is it possible you are using an older version of the library?

See also https://github.com/terraform-providers/terraform-provider-aws/issues/9199.

**Comment by astronouth7303** [comment]
Oh, yeah, i need to update the venv with the pulumi releases. I've just be updating the binaries.

**Comment by lukehoban** [comment]
Note that updating the vent packages will actually take care of updating the binaries for you - you shouldn’t need to worry about those separately.

**Comment by astronouth7303** [comment]
Ummm.... I do? The PyPI packages don't include the `pulumi` and `pulumi-*` binaries?
