### ISSUE TITLE
aws.acm.Certificate should support CertificateAuthorityArn

### ISSUE THREAD

**Issue by texdc** [pulumi/pulumi-aws#683]
I realize that the `Certificate` resource is generated from Terraform and that TF lacks this functionality, too.  However, the AWS SDKs all support `CertificateAuthorityArn` as a configuration parameter.  This is essential for requesting ACM Certificates leveraging the ACM Private CA.

[JS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ACM.html#requestCertificate-property)
[boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm.html#ACM.Client.request_certificate)

**Comment by stack72** [comment]
Hi @texdc 	

thanks for the feature request here. There is currently an issue in Terraform that tracks the work - https://github.com/terraform-providers/terraform-provider-aws/issues/5550. I would suggest that you comment on the issue there for your level of ugency

I am going to suggest that we can close this out and use this upstream issue as the tracking. As soon as it arrives in Terraform, it will be a matter of hours until it is available in Pulumi

Hope this helps

Paul

**Comment by texdc** [comment]
@stack72 When will Pulumi be decoupled from TF?

**Comment by lukehoban** [comment]
> @stack72 When will Pulumi be decoupled from TF?

No immediate timeframe - but we are exploring options.
