### ISSUE TITLE
SES ConfigurationSet, ConfigurationSetArgs, and ConfigurationSetState Typo

### ISSUE THREAD

**Issue by mk0a1a** [pulumi/pulumi-aws#688]
Minor typo for typescript SES ConfigurationSet class, ConfigurationSetArgs, and ConfigurationSetState interfaces. Missing an "i" for Configuration.

[ConfigurationSet ts file](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/ses/confgurationSet.ts)

**Comment by lukehoban** [comment]
@stack72 Another case of a typo in the name of a resource:

https://github.com/pulumi/pulumi-aws/blob/377945d2fea136d27dfea1402221b607e41554c5/resources.go#L1564
