### ISSUE TITLE
No way to configure SES on Cognito

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-aws#691]
Current with Cognito Api https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/cognito/ we don't have a way to configure Cognito email to use SES Configuration.

This is the way to enable SES from the UI on AWS.
![cognitoSES](https://user-images.githubusercontent.com/33038414/62528883-e0783180-b83d-11e9-9eb4-b0e7538dd647.PNG)

**Comment by stack72** [comment]
Hi @albertocorrales 	

Thanks for opening the issue here - which part of cognito needs to allow email to be configured?

Is there something specific missing on an individual package or are we missing an entire package?

Thanks

Paul

**Comment by albertocorrales** [comment]
Hey @stack72, I think I found the problem. This feature was added in version 0.18 and I was working with version 0.17. 

In new latest version of @pulumi/aws there is a property "emailSendingAccount" in object "emailConfiguration", which allow us to configure SES in Cognito.

Thanks for your quick response and keep it up with the great work you are doing with Pulumi!

**Comment by stack72** [comment]
@albertocorrales thanks for closing this out :)
