### ISSUE TITLE
TaskDefinition dependsOn property not available

### ISSUE THREAD

**Issue by Blitz2145** [pulumi/pulumi-aws#713]
I am setting up a awsx.FargateService and it looks like there is no way to pass dependsOn for the containers configs? Not to be confused with the pulumi dependsOn, I am referring to https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_dependson
It looks like this parameter is not inside the pulumi-aws package either.

**Comment by stack72** [comment]
Hi @Blitz2145 	

There is no named property for `dependsOn` in either Pulumi nor Terraform. DependsOn is part of `container_definition` - that property is a string which is made up of JSON

Therefore, you can include that `dependsOn` in that JSON blob

Can you try this and let me know? 

thanks

Paul

**Comment by Blitz2145** [comment]
Thanks, I understand I can workaround it by generating the container definition json string myself, but I was hoping the property could be added to `ecs.Container` type and pulumi code could do the work like it does with the other props for a container.
