### ISSUE TITLE
aws.iam.AccessKey secret property should be marked as secret

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-aws#726]
Hi,

Currently the secret output property of the aws.iam.AccessKey is not marked as secret, so written to the state file as plain text, but I think it should be secret.

**Comment by pgavlin** [comment]
> Currently the secret output property of the aws.iam.AccessKey is not marked as secret, so written to the state file as plain text, but I think it should be secret.

This property is [deprecated](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_iam_access_key.go#L40-L44); see the note at https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/iam/#AccessKeyState-secret. Passing a valid PGP key to the `pgpKey` input property will cause the provider to leave `secret` empty (`encryptedSecret` will be populated instead). You can then e.g. decrypt the value by exporting `encryptedSecret` as a stack output and using the command line: `pulumi stack output encryptedSecret | base64 --decode | keybase pgp decrypt`.

For now, you can manually mark the `secret` property as secret by using the `additionalSecretOutputs` field of `ResourceOptions`: https://www.pulumi.com/docs/intro/concepts/programming-model/#explicitly-marking-resource-outputs-as-secrets
