### ISSUE TITLE
Property 'executionArn' does not exist on type 'Input<RestApi>'.

### ISSUE THREAD

**Issue by texdc** [pulumi/pulumi-aws#727]
Because Crosswalk (awsx) Api does not support custom IAM Roles and instead uses *highly* insecure generic AWS Read Access roles (no [least-privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)), I'm needing to build out ComponentResources for various parts of ApiGateway.  Inside one, I'm wanting to build the Permission to execute a lambda and get this typing error:

```
Property 'executionArn' does not exist on type 'Input<RestApi>'.
```

Sample excerpt from my CustomResource:
```ts
this.permissions.push(getLambdaApiPermission(`${name}-method-${httpMethod}-permission`, {
  functionName: methodConfig.function.name,
  executionArn: config.restApi.executionArn,  // config is an instance of ResourceArgs
  method: method.httpMethod,
  path: this.resource.path
}, { parent: method }))
```

From yarn:
```
├─ @pulumi/aws@1.0.0-rc.2
```

**Comment by texdc** [comment]
I "fixed" it with `apply`.  But, `apply` and `get` are probably the worst part of Pulumi.  Can `Lifted` be used more extensively?  Right now, I'm trying to check the value of a `Resource.path`, but I can't call `toString()` on an `Output<string>`.

**Comment by pgavlin** [comment]
> Because Crosswalk (awsx) Api does not support custom IAM Roles and instead uses highly insecure generic AWS Read Access roles (no least-privilege), I'm needing to build out ComponentResources for various parts of ApiGateway

cc @CyrusNajmabadi @lukehoban
