### ISSUE TITLE
Kinesis Firehose processingConfiguration parameters updates every time

### ISSUE THREAD

**Issue by benswinburne** [pulumi/pulumi-aws#735]
As per the title, on every update the stack attempts to update by removing this parameter `BufferSizeInMBs` which I've never had in my configuration, but presumably is added behind the scenes?

```
~ extendedS3Configuration: {
          ~ processingConfiguration: {
              ~ processors: [
                  ~ [0]: {
                          ~ parameters: [
                              - [1]: {
                                      - parameterName : "BufferSizeInMBs"
                                      - parameterValue: "1"
                                    }
                            ]
                        }
                ]
            }
        }
```

```
const bufferSizes = {
  bufferInterval: 60,
  bufferSize: 1,
};

const bucketConfig = {
  compressionFormat: 'GZIP',
  bucketArn: bucket.arn,
  roleArn: firehoseRole.arn,
};

const firehose = new aws.kinesis.FirehoseDeliveryStream(
  'inbound-delivery-stream',
  {
    destination: 'extended_s3',
    extendedS3Configuration: {
      ...bufferSizes,
      ...bucketConfig,
      prefix: 'processed-',
      processingConfiguration: {
        enabled: true,
        processors: [
          {
            parameters: [
              {
                parameterName: 'LambdaArn',
                parameterValue: pulumi.interpolate`${enricherHandler.arn}:$LATEST`,
              },
            ],
            type: 'Lambda',
          },
        ],
      },

      s3BackupMode: 'Enabled',
      s3BackupConfiguration: {
        ...bufferSizes,
        ...bucketConfig,
        prefix: 'raw-',
      },
    },
  },
  { provider }
);
```

**Comment by pgavlin** [comment]
I _think_ that this is due to the following issue in the upstream Terraform provider: https://github.com/terraform-providers/terraform-provider-aws/issues/9827
> The BufferSizeInMBs and BufferIntervalInSeconds parameters are also required so we can't leave them out if we want them to be set to the default values and have a clean terraform plan.

We'll pick up the fix for this issue once it is fixed in the upstream provider, and we'll use that issue for tracking. In the meantime, can you try setting the [`ignoreChanges` property of `ResourceOptions`](https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges) like so:

const firehose = new aws.kinesis.FirehoseDeliveryStream(
  'inbound-delivery-stream',
  {
    destination: 'extended_s3',
    extendedS3Configuration: {
      ...bufferSizes,
      ...bucketConfig,
      prefix: 'processed-',
      processingConfiguration: {
        enabled: true,
        processors: [
          {
            parameters: [
              {
                parameterName: 'LambdaArn',
                parameterValue: pulumi.interpolate`${enricherHandler.arn}:$LATEST`,
              },
            ],
            type: 'Lambda',
          },
        ],
      },

      s3BackupMode: 'Enabled',
      s3BackupConfiguration: {
        ...bufferSizes,
        ...bucketConfig,
        prefix: 'raw-',
      },
    },
  },
  { provider, ignoreChanges: [ "extendedS3Configuration.processingConfiguration.processors[0].parameters[1]" ] }
);
```

If that does not work, you should be able to add a matching `"BufferSizeInMBs"` parameter to your inputs to avoid the diff.

**Comment by benswinburne** [comment]
@pgavlin, cheers. I added add a matching `BufferSizeInMBs` parameter for now and will keep an eye on the TF issue. What's the best way of knowing when a fixed TF issue ends up in Pulumi?

**Comment by pgavlin** [comment]
> What's the best way of knowing when a fixed TF issue ends up in Pulumi?

In general, a fixed TF issue ends up in Pulumi within 24 hours of the release of whichever version of the corresponding TF provider contains the fix. We update the CHANGELOG for each release with the version of the TF provider the release contains: https://github.com/pulumi/pulumi-aws/blob/master/CHANGELOG.md

**Comment by benswinburne** [comment]
Ah, nice that's easy enough. Thanks for the quick response; much appreciated.
