### ISSUE TITLE
EC2 instance gets always recreated due to securityGroups diff

### ISSUE THREAD

**Issue by pawelros** [pulumi/pulumi-aws#744]
Version:
```
        "@pulumi/pulumi": "1.1.0",
        "@pulumi/aws": "1.1.0",
        "@pulumi/awsx": "0.18.10"
```
(tested as well on 1.0.0).

Repo to reproduce: https://github.com/LykkeCorp/pulumi-ec2-test

Subsequent `pulumi up`  always recreates EC2 instance despite the fact that nothing changes in the code and in aws infrastructure. `pulumi preview --diff` shows:

```
Previewing update (sandbox):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:sandbox::pulumi-test::pulumi:pulumi:Stack::pulumi-test-sandbox]
    +-aws:ec2/instance:Instance: (replace)
        [id=i-009a5e6c9f723a700]
        [urn=urn:pulumi:sandbox::pulumi-test::aws:ec2/instance:Instance::my-ec2]
        [provider=urn:pulumi:sandbox::pulumi-test::pulumi:providers:aws::sandboxProvider::4db4b328-a1e1-4a6c-851b-e29c50e7e5c6]
      ~ securityGroups: [
          + [0]: "sg-031ff89f54c568531"
        ]
Resources:
    +-1 to replace
    38 unchanged
```

Security group `sg-031ff89f54c568531` of course already exists and does not change between runs. I tried to use inline ingress and egress rules on `awsx.ec2.SecurityGroup` resource but the result is the same. Please help as I run out of ideas on how that can be fixed.

**Comment by stack72** [comment]
Hi @pawelros 

You can only use securityGroups when you are using the default VPC / Classic EC2

You need to change to use vpcSecurityGroupIds as the parameter and this will solve your problem

Paul

**Comment by pawelros** [comment]
That was it. Thank you very much.
