### ISSUE TITLE
Tags for Name property on LaunchTemplate generated EC2s

### ISSUE THREAD

**Issue by armenr** [pulumi/pulumi-aws#758]
Quick question:

How can tag ec2s created by a LaunchTemplate + an AutoScale Group with names...like `web` or `web-1` for example?

Thanks for any help you might be able to provide!

**Comment by stack72** [comment]
Hi @armenr 

I’m not sure I understand the question - you want to be able supply Name tags to instances in an ASG launched by InstanceTemplate

Right?

Paul

**Comment by stack72** [comment]
IF that is what you mean, then in the AutoScaling group, you would add the following:

```
     tags: [
         {
             key: "name",
             propagateAtLaunch: true,
             value: "web",
         },
     ],
```

There is no real way of adding `-1` etc as there is no real understanding of what is 1, 2, 3 etc

**Comment by armenr** [comment]
Thank you!! :)
