### ISSUE TITLE
Cloudformation get_stack is returning weird error to fetch the template

### ISSUE THREAD

**Issue by Brijeshrpatel9** [pulumi/pulumi-aws#768]
I have bunch of AWS cloudformation stacks. I am planning to call get_stack method on my existing stack using this code:
`aws.cloudformation.get_stack(name = 'my-stack-name')`

But when I tried to run it, I am getting following error:
`Exception: invocation of aws:cloudformation/getStack:getStack returned an error: invoking aws:cloudformation/getStack:getStack: template body contains an invalid JSON or YAML: invalid character 'L' after array element
    error: an unhandled error occurred: Program exited with non-zero exit code: 1`

For the same stack, aws cli call worked fine and it returned valid JSON template. 
`aws cloudformation get-template --stack-name my-stack-name`

I tried calling get_stack for 5-7 stacks. get_stack call worked only for 1 or 2 stacks while aws cli call worked for all the stacks.

**Comment by stack72** [comment]
Hi @Brijeshrpatel9 

Firstly, I am sorry for the time that has passed here - this is something we are trying to get better at.

Now, I have tried to recreate this error. I have deployed a few sample stacks as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w2ab1c28c58c13c39

When I run the following pulumi code, I can import as expected:

```
import * as aws from "@pulumi/aws";

const stack = aws.cloudformation.getStack({name: "Stack72Demo"});

export const name = stack.name;
export const templateBody = stack.templateBody;
```

This returns:

```
▶ pulumi up --yes
Previewing update (dev):

     Type                 Name              Plan
 +   pulumi:pulumi:Stack  get-cf-stack-dev  create

Resources:
    + 1 to create

Updating (dev):

     Type                 Name              Status
 +   pulumi:pulumi:Stack  get-cf-stack-dev  created

Outputs:
    name        : "Stack72Demo"
    templateBody: "{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"AWS CloudFormation Sample Template SQS_With_CloudWatch_Alarms: Sample template showing how to create an SQS queue with AWS CloudWatch alarms on queue depth. **WARNING** This template creates an Amazon SQS Queue and one or more Amazon CloudWatch alarms. You will be billed for the AWS resources used if you create a stack from this template.\",\"Outputs\":{\"QueueARN\":{\"Description\":\"ARN of newly created SQS Queue\",\"Value\":{\"Fn::GetAtt\":[\"MyQueue\",\"Arn\"]}},\"QueueName\":{\"Description\":\"Name newly created SQS Queue\",\"Value\":{\"Fn::GetAtt\":[\"MyQueue\",\"QueueName\"]}},\"QueueURL\":{\"Description\":\"URL of newly created SQS Queue\",\"Value\":{\"Ref\":\"MyQueue\"}}},\"Parameters\":{\"AlarmEMail\":{\"AllowedPattern\":\"([a-zA-Z0-9_\\\\-\\\\.]+)@((\\\\[[0-9]{1,3}\\\\.[0-9]{1,3}\\\\.[0-9]{1,3}\\\\.)|(([a-zA-Z0-9\\\\-]+\\\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\\\]?)\",\"ConstraintDescription\":\"must be a valid email address.\",\"Description\":\"EMail address to notify if there are any operational issues\",\"Type\":\"String\"}},\"Resources\":{\"AlarmTopic\":{\"Properties\":{\"Subscription\":[{\"Endpoint\":{\"Ref\":\"AlarmEMail\"},\"Protocol\":\"email\"}]},\"Type\":\"AWS::SNS::Topic\"},\"MyQueue\":{\"Properties\":{},\"Type\":\"AWS::SQS::Queue\"},\"QueueDepthAlarm\":{\"Properties\":{\"AlarmActions\":[{\"Ref\":\"AlarmTopic\"}],\"AlarmDescription\":\"Alarm if queue depth grows beyond 10 messages\",\"ComparisonOperator\":\"GreaterThanThreshold\",\"Dimensions\":[{\"Name\":\"QueueName\",\"Value\":{\"Fn::GetAtt\":[\"MyQueue\",\"QueueName\"]}}],\"EvaluationPeriods\":\"1\",\"InsufficientDataActions\":[{\"Ref\":\"AlarmTopic\"}],\"MetricName\":\"ApproximateNumberOfMessagesVisible\",\"Namespace\":\"AWS/SQS\",\"Period\":\"300\",\"Statistic\":\"Sum\",\"Threshold\":\"10\"},\"Type\":\"AWS::CloudWatch::Alarm\"}}}"

Resources:
    + 1 created

Duration: 7s
```

Please can you try this again using the latest pulumi aws plugin and see if you still get the error?

If you do get the error, can you supply me a template that you can recreate it with?

Thanks

Paul

**Comment by stack72** [comment]
Hi @Brijeshrpatel9 

I have not heard back from you on this issue - I am going to close this out. If you are still having this problem then I'd love to see what else we can try and diagnose here

Thanks

Paul
