### ISSUE TITLE
lifecycle block does not exist in aws.ec2.LaunchConfigurationArgs

### ISSUE THREAD

**Issue by nguyenxndaidev** [pulumi/pulumi-aws#769]
I could not specify lifecycle for aws.ec2.LaunchConfiguration.

In the [documentation](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ec2/#using-with-autoscaling-groups):
> it’s recommended to specify createBeforeDestroy in a lifecycle block.

But does it exist?

Terraform supports it: https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

I am using @pulumi/aws 1.6.0

**Comment by nguyenxndaidev** [comment]
Hi @stack72, thanks for your reply!

I will test that default behavior and let you know if it works for me.

But anyway, we still need to allow to set `createBeforeDestroy` to `false` when needed, right?

Best regards

**Comment by stack72** [comment]
Hi @nguyenxndaidev 

You shouldn’t need to unless you are overriding Pulumis autonaming 

Paul

**Comment by nguyenxndaidev** [comment]
> You shouldn’t need to unless you are overriding Pulumis autonaming
Hmm, I am new to both Terraform and Pulumi, so I don't know what do you mean. Why Terraform allows to configure lifecycle but Pulumi not? I understand that Pulumi gives us the best default for most cases, but do not allow to change the default configuration is strange to me.

**Comment by stack72** [comment]
Pulumi has that lifecycle by default

You can disable it of course but it would be via the custom resource options where you can enable deleteBeforeCreate

**Comment by nguyenxndaidev** [comment]
Cool! thanks for the tip. I need to learn more to understand how Pulumi works.

**Comment by stack72** [comment]
Let me know if this doesn’t work for you :)

**Comment by nguyenxndaidev** [comment]
I confirm that the default behavior `createBeforeDestroy` works as expected.
`deleteBeforeReplace: true` in `CustomResourceOptions` block also works as expected.

Thanks for your help!

**Comment by stack72** [comment]
Thanks for confirming @nguyenxndaidev!
