### ISSUE TITLE
Directly importing a type leads to exception

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#772]
If I try to do this

```
import { Table } from "@pulumi/aws/dynamodb";
new Table(...);
```

rather than this

```
import * as aws from "@pulumi/aws";
new aws.dynamodb.Table(...);
```

I receive the following error

```
Running program '...' failed with an unhandled exception:
    TypeError: Class extends value undefined is not a constructor or null
        at Object.<anonymous> (.../node_modules/@pulumi/cloudwatch/eventRuleMixins.ts:70:55)
        at Module._compile (module.js:573:30)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)
        at Function.Module._load (module.js:462:3)
        at Module.require (module.js:517:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (.../node_modules/@pulumi/cloudwatch/cloudwatchMixins.ts:16:1)
        at Module._compile (module.js:573:30)
```

I assume this is an import ordering issue and might not be something we can fix. If it is fixable, however, that would be nice, as the former import style is preferable sometimes.

**Comment by CyrusNajmabadi** [comment]
I think this may be easy to fix.  The main issue is that we generate our index.ts in these cloud providers such that they import their own directory files in alphabetical order. This can be highly problematic with ordering.

I solved this in Azure (where it actually was blocking us) by making all the mixins called `zMixins.ts` so they would be mixed in at the end, after all the normal code had loaded.  I think that should fix the issue here.

**Comment by joeduffy** [comment]
Great! Not super urgent, obviously, but probably a nice thing to fix eventually.

**Comment by nickcaballero** [comment]
Had this same issue importing `aws.s3.Bucket`.

**Comment by kxtran** [comment]
Had this same issue importing `aws.cloudwatch.LogGroup`

**Comment by Dysproz** [comment]
I have the same problem with `aws.cloudwatch.LogGroup`.

Figured out temporary fix which is probably better than importing * from aws package:
```
import { cloudwatch } from "@pulumi/aws";
new cloudwatch.LogGroup(...)
```

**Comment by andrewdibiasio6** [comment]
Any updates on this? I am also having this issue.

**Comment by jkodroff** [comment]
Actively working on this. Blocked for the moment b/c we need to update the pulumi-terraform-bridge > 3.26.1.

**Comment by jwarwick-delfi** [comment]
+1, still an issue on pulumi v3.43.1 with "@pulumi/aws": "5.17.0"

**Comment by Senja20** [comment]
I tried to use the fix, but the error still persists. 

I have updated the import statement to the following:

```ts
import { StorageAccount } from "@pulumi/azure-native/storage";
```
And creating a Storage Account: 

```ts
const storageAccount = new StorageAccount(labelName, { ... }, { dependsOn: dependencies })
```

I am getting the following error message:  

```
    const storageAccount = new storage_1.StorageAccount(labelName, {
                           ^

TypeError: storage_1.StorageAccount is not a constructor
    at Object.createAzureStorageAccount [as default]
```

What should I do and how can I fix that?

**Comment by joeduffy** [comment]
Now that we have landed lazy-loading for submodules in https://github.com/pulumi/pulumi/pull/10538, I believe this is "easier" to fix. Indeed, for the `cloudwatch/index.js` file, I manually changed the exports from eager:

```javascript
__exportStar(require("./cloudwatchMixins"), exports);
__exportStar(require("./eventRuleMixins"), exports);
__exportStar(require("./logGroupMixins"), exports);
```

to lazy:

```javascript
exports.QueryDefinition = ... = exports.onSchedule = exports.EventRuleEventSubscription = exports.LogGroupEventSubscription = void 0;
...
exports.onSchedule = null;
utilities.lazyLoad(exports, ["onSchedule"], () => require("./cloudwatchMixins"));
exports.EventRuleEventSubscription = null;
utilities.lazyLoad(exports, ["EventRuleEventSubscription"], () => require("./eventRuleMixins"));
exports.LogGroupEventSubscription = null;
utilities.lazyLoad(exports, ["LogGroupEventSubscription"], () => require("./logGroupMixins"));
...
```

as well as doing the same for other affected modules (`dynamodb`, `kinesis`, `sqs`, etc), and it resolved the problem.

In looking at how lazy loading works, the primary thing I'm unsure about is whether we have sufficient schema information about mixin exports, to be able to generate the specific exports (`onSchedule`, `EventRuleEventSubscription`, `LogGroupEventSubscription`, and so on). Presumably that's why we use `__exportStar` today?

Here is a very minimal/simple program to reproduce, by the way; slight modification from our AWS starter template, just imports `Bucket` directly rather than the parent module as we often do:

```typescript
import { Bucket } from "@pulumi/aws/s3";

// Create an AWS resource (S3 Bucket)
const bucket = new Bucket("my-bucket");

// Export the name of the bucket
export const bucketName = bucket.id;
```
