### ISSUE TITLE
Update the default Lambda runtime to Node 10.x

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws#774]
Node.js 8.10 will reach EOL end of this year:

> The Node community has decided to end support for Node.js 8.x on December 31, 2019. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS.
> For Node.js 8.x, there will be 2 stages to the runtime deprecation process:
> 1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10
> 2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10
> After this period, both function creation and updates will be disabled permanently. However, existing Node 8.x functions will still be available to process invocation events.

As per email communication ([this page](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) doesn't seem to reflect it yet).

`pulumi-aws` should now default to Node 10.x for Callback Functions.

Probably, the docs should reflect this too, e.g. [here](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/lambda/#NodeJS8d10Runtime)

**Comment by stack72** [comment]
@mikhailshilkov so the clarify the work you want done here:

1. Mark 8.10 as deprecated and add a message as to why
2. Set the default to be 10.x - we currently don't set a default in Pulumi - but I am presuming we can do that

**Comment by mikhailshilkov** [comment]
@stack72 Yes, correct. Not sure if it's correct to deprecate it right now or closer to Jan 1, but the default (which we set [here](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/lambda/lambdaMixins.ts#L320)) should be changed.

**Comment by danielrbradley** [comment]
My suggestion would be to indicate the deprecation as early as possible to dissuade use of a runtime which will soon be reaching end of life. As of Jan 6 using the runtime will start causing deploy errors when trying to create new functions. Therefore, it would be good to give plenty of time to migrate ahead of that date to minimise disruption.

**Comment by stack72** [comment]
I agree @danielrbradley - we should add the deprecation message to it now saying when it will be EOLed

**Comment by stack72** [comment]
@CyrusNajmabadi / @lukehoban I'd like your thoughts on the defaulting to NodeJS 10.x please :)

**Comment by stack72** [comment]
I just added the deprecation message for now - we can revisit the default across all of our product suites after this has been deprecated
