### ISSUE TITLE
Pulumi creates Glue database and table names that are incompatible with Athena

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-aws#793]
Athena is commonly backed by Glue tables (hive metastore). Pulumi programs creating Glue tables and databases use `-` as the separator between the user defined name and the random number appended to the resource. Athena throws an error [if it sees any special characters in table/db names other than '_'](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html#ate-table-database-and-column-names-allow-only-underscore-special-characters). This is not leading users into the pit of success, we should consider using the legal separator value here.

**Comment by stack72** [comment]
@EvanBoyle is this due to our autonaming?

**Comment by lukehoban** [comment]
Yes - sounds like we need to customize the autonaming for this resource.

**Comment by stack72** [comment]
@lukehoban it just so happens I centralised the custom naming code yesterday 💃

**Comment by EvanBoyle** [comment]
Thanks for looking into this @stack72!

**Comment by EvanBoyle** [comment]
@stack72 [This doc](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html) provides further details about how db and table naming impact querying. For the most straight forward user experience, I think we should conform to something along the lines of 

```
^[a-z]+(_[a-z]+)*$
```

Which will match `abc_def`, but not `_abc_`.  Can we convert the random number to a lowercase letter string: `tablename_123` -> `tablename_abc` ?
