### ISSUE TITLE
Inconsistent provider behaviour when using profiles in shared credentials.

### ISSUE THREAD

**Issue by jonjitsu** [pulumi/pulumi-aws#794]
Given ~/.aws/config:
```
[profile assumableprofile]
region = us-east-1

[profile test]
role_arn = arn:aws:iam::1234456789:role/Admin
source_profile = assumableprofile
region = us-east-1
```
and ~/.aws/credentials
```
[profile assumableprofile]
aws_access_key_id = HIDDEN
aws_secret_access_key = HIDDEN
aws_session_token = HIDDEN
```

and index.ts:
```
import * as aws from '@pulumi/aws'
const
   provider = new aws.Provider('myprovider', {profile: 'test', region: 'us-east-1'}),
   opts = {provider: provider},
   b = new aws.s3.Bucket('mybucket', {}, {provider: p}),  // this works
   callerId = aws.getCallerIdentity(opts),  // this fails
   region = aws.getRegion({}, opts)  // this fails
```

when I execute `pulumi up` the bucket is correctly created while the two data calls fail with `unable to discover AWS AccessKeyID and/or SecretAccessKey`

when I change the call to `AWS_SDK_LOAD_CONFIG=true pulumi up` everything succeeds.

It seems like the use of providers is inconsistent.

Update:
When I run the above from a bash shell with `export AWS_PROFILE=profile1` set then the `callerId` above is not of the provider as expected but of profile1.

**Comment by pgavlin** [comment]
Interesting. @jen20 @stack72 can one of y'all take a look at this?

**Comment by jonjitsu** [comment]
Sorry I seem to have made a mistake. I didn't isolate the code neatly as in the example above. So it was a problem in the program I was writing. This can be closed.

**Comment by lukehoban** [comment]
Thanks for confirming @jonjitsu!
