### ISSUE TITLE
AWS S3 bucket import proceeds even if policy is not imported

### ISSUE THREAD

**Issue by jandom** [pulumi/pulumi-aws#804]
hi there!

This is my first ticket with pulumi, I love the package and what it allowed us to do with our infrastructure (big mess -> no mess)

I end up importing a lot of resources from an existing click-ops setup, and pulumi does an awesome job trying to ensure that the imported configuration matches what the resource args that pulumi program creates (and complains otherwise). 

Found a bit of odd behavior, not sure if that's a feature. 

Steps to reproduce
- create a random bucket named "example-bucket-8q1nc"
- attach a very simple JSON policy to it, doesn't really matter what the policy document is

```json
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::123:user/SomeUser"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::example-bucket-8q1nc"
        }
    ]
}
```

- import this resource with a very simple pulumi program 

```typescript
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

// Load the Pulumi program configuration. These act as the "parameters" to the Pulumi program,
// so that different Pulumi Stacks can be brought up using the same code.
const stackConfig = new pulumi.Config("pulumi-debug");
const config = {
    contentBucket: stackConfig.require("contentBucket"),
};

const createContentBucketArgs = (bucketName: string) => {
  return ({
          bucket: bucketName,
      });
};

// contentBucket is the S3 bucket that the website's contents will be stored in.
const contentBucket = new aws.s3.Bucket("contentBucket", createContentBucketArgs(config.contentBucket), { import: "example-bucket-8q1nc" });
```

This commands succeeds without any errors which is not expected because my config completely ignored the custom policy attached to the bucket. I would expect to have to re-create/re-import the policy resource for this import to work

```bash
$ pulumi version
v1.6.0

$ pulumi up
Previewing update (debug):

     Type                 Name                Plan       
 +   pulumi:pulumi:Stack  pulumi-debug-debug  create     
 =   └─ aws:s3:Bucket     contentBucket       import     
 
Resources:
    + 1 to create
    = 1 to import
    2 changes

Do you want to perform this update? details
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:debug::pulumi-debug::pulumi:pulumi:Stack::pulumi-debug-debug]
    = aws:s3/bucket:Bucket: (import)
        [id=example-bucket-8q1nc]
        [urn=urn:pulumi:debug::pulumi-debug::aws:s3/bucket:Bucket::contentBucket]
        [provider=urn:pulumi:debug::pulumi-debug::pulumi:providers:aws::default_1_7_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        arn                              : "arn:aws:s3:::example-bucket-8q1nc"
        bucket                           : "example-bucket-8q1nc"
        hostedZoneId                     : "SomeHostedZoneId"
        region                           : "eu-west-1"
        requestPayer                     : "BucketOwner"
        versioning                       : {
            enabled  : false
            mfaDelete: false
        }
```

**Comment by pgavlin** [comment]
This is due to the way the underlying Terraform provider treats the `policy` property. This property is treated as an input-only property, meaning that it is not fetched from AWS when the resource's existing state is read during the import. As a result, we cannot detect a diff in the policy.

 I believe that you can import the bucket's policy using a `BucketPolicy` resource: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/s3/#BucketPolicy

**Comment by jandom** [comment]
Thanks so much for explaining @pgavlin – yeah this looked like a limitation. 

Still, it's not easy to stumble upon this with Pulumi or Terraform docs. And this applies not just to S3 buckets but also IAM users (and who knows where else). 

Is there any chance the docs could be updated? I'm happy to provide a PR – which pulumi repo would this be best placed?
