### ISSUE TITLE
updating Bucket: panic: interface conversion: interface {} is nil, not map[string]interface {} 

### ISSUE THREAD

**Issue by rradillen** [pulumi/pulumi-aws#821]
I'm getting the following issue when running pulumi up on

```
const thumbBucket = new aws.s3.Bucket('thumbs', {
  lifecycleRules: [{
    enabled: true,
    expiration: {
      days: 1
    }
  }],
  bucket: `thumbs-${stack}`
},{
  deleteBeforeReplace: true
});
```   

panic: interface conversion: interface {} is nil, not map[string]interface {} 
    goroutine 144 [running]: 
    github.com/terraform-providers/terraform-provider-aws/aws.expirationHash(0x0, 0x0, 0x1) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20191204061439-296f6e649040/aws/resource_aws_s3_bucket.go:2312 +0x3d6 
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Set).hash(0xc000a25460, 0x0, 0x0, 0xc000eba000, 0x0) 
     /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/set.go:221 +0x3d 
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Set).add(0xc000a25460, 0x0, 0x0, 0xc0006fb600, 0x0, 0xc000cc9ed0) 
     /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/set.go:198 +0x83 
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ConfigFieldReader).readSet(0xc000d199e0, 0xc000cfe7b0, 0x1, 0x1, 0xc0006fb680, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
     /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/field_reader_config.go:309 +0x329 
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ConfigFieldReader).readField(0xc000d199e0, 0xc000cfe7b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
     /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/field_reader_config.go:132 +0x97f 
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ConfigFieldReader).ReadField(0xc000d199e0, 0xc000cfe7b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000cfe808, ...) 
     /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/field_reader_config.go:28 +0xae 
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.visitPropertyValue(0xc000e49410, 0x2e, 0xc000e493e0, 0x2d, 0x0, 0x0, 0xc0006fb680, 0x0, 0x0, 0xc000cff118) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.4.3/pkg/tfbridge/diff.go:129 +0xd66 
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.visitPropertyValue(0xc000cc9930, 0x10, 0xc000ccbd00, 0x11, 0x5169a40, 0xc000cea5d0, 0xc000d31040, 0x0, 0x0, 0xc000cff118) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.4.3/pkg/tfbridge/diff.go:172 +0x2ea 
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.visitPropertyValue(0xc000fdf1e0, 0xe, 0xc000cc83c0, 0xe, 0x42f9460, 0xc000a0ca80, 0xc0006fc140, 0x0, 0x0, 0xc000cff118) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.4.3/pkg/tfbridge/diff.go:148 +0x90d 
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.doIgnoreChanges(0xc0006bf830, 0xc00080c540, 0xc000cea5a0, 0xc000ceb3b0, 0x0, 0x0, 0x0, 0xc000a0dac0) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.4.3/pkg/tfbridge/diff.go:273 +0x279 
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Diff(0xc0005fea80, 0x5d5cb20, 0xc000cea510, 0xc000c19110, 0xc0005fea80, 0x49d6501, 0xc000c83f00) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.4.3/pkg/tfbridge/provider.go:551 +0x7c5 
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler.func1(0x5d5cb20, 0xc000cea510, 0x5241420, 0xc000c19110, 0x528ce20, 0x8beadf8, 0x5d5cb20, 0xc000cea510) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.0/sdk/proto/go/provider.pb.go:1597 +0x86 
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x5d5cb20, 0xc000cad8c0, 0x5241420, 0xc000c19110, 0xc000a0c760, 0xc000a0c780, 0x0, 0x0, 0x5cbc760, 0xc00040cae0) 
     /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e 
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler(0x5330380, 0xc0005fea80, 0x5d5cb20, 0xc000cad8c0, 0xc000caa540, 0xc0000baa00, 0x5d5cb20, 0xc000cad8c0, 0xc000852500, 0x4da) 
     /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.0/sdk/proto/go/provider.pb.go:1599 +0x14b 
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f0580, 0x5d7f720, 0xc000854600, 0xc000bcc800, 0xc0008363c0, 0x8bbc718, 0x0, 0x0, 0x0) 
     /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460 
    google.golang.org/grpc.(*Server).handleStream(0xc0000f0580, 0x5d7f720, 0xc000854600, 0xc000bcc800, 0x0) 
     /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97 
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003b6100, 0xc0000f0580, 0x5d7f720, 0xc000854600, 0xc000bcc800) 
     /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb 
    created by google.golang.org/grpc.(*Server).serveStreams.func1 
     /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1 
    aws:s3:Bucket thumbs  error: transport is closing 
    aws:s3:Bucket thumbs  1 error

**Comment by mazamats** [comment]
I pulled this from our state file, this is the shape of the s3 bucket object we have.

```
            {
                "urn": "urn:pulumi:stage::XXXXXX::cointainer$aws:s3/bucket:Bucket::XXXXXXXXX-2510",
                "custom": true,
                "id": "XXXXXXXXX-2510-751e8ab",
                "type": "aws:s3/bucket:Bucket",
                "inputs": {
                    "__defaults": [
                        "acl",
                        "bucket"
                    ],
                    "acl": "private",
                    "bucket": "XXXXXXXXX-2510-751e8ab",
                    "forceDestroy": true,
                    "lifecycleRules": [
                        {
                            "__defaults": [],
                            "enabled": true,
                            "expiration": {
                                "__defaults": [],
                                "days": 7
                            }
                        }
                    ]
                },
                "outputs": {
                    "accelerationStatus": "",
                    "acl": "private",
                    "arn": "arn:aws:s3:::XXXXXXXXX-2510-751e8ab",
                    "bucket": "XXXXXXXXX-2510-751e8ab",
                    "bucketDomainName": "XXXXXXXXX-2510-751e8ab.s3.amazonaws.com",
                    "bucketRegionalDomainName": "XXXXXXXXX-2510-751e8ab.s3.eu-west-1.amazonaws.com",
                    "corsRules": [],
                    "forceDestroy": true,
                    "hostedZoneId": "Z1BKCTXD74EZPE",
                    "id": "XXXXXXXXX-2510-751e8ab",
                    "lifecycleRules": [
                        {
                            "abortIncompleteMultipartUploadDays": 0,
                            "enabled": true,
                            "expiration": {
                                "date": "",
                                "days": 7,
                                "expiredObjectDeleteMarker": false
                            },
                            "id": "tf-s3-lifecycle-20191114212817156700000002",
                            "noncurrentVersionTransitions": [],
                            "prefix": "",
                            "tags": {},
                            "transitions": []
                        }
                    ],
                    "loggings": [],
                    "region": "eu-west-1",
                    "requestPayer": "BucketOwner",
                    "tags": {},
                    "versioning": {
                        "enabled": false,
                        "mfaDelete": false
                    }
                },
                "parent": "urn:pulumi:stage::XXXXXX::cointainer::parity::XXXXXXXXX",
                "provider": "urn:pulumi:stage::XXXXXX::pulumi:providers:aws::default_1_14_1::28f28934-5caa-4978-8e8d-2ae7341ea139",
                "propertyDependencies": {
                    "forceDestroy": null,
                    "lifecycleRules": null
                }
            },
```

**Comment by pgavlin** [comment]
Thanks for the instructions--I can repro this locally. Looking into a fix now.
