### ISSUE TITLE
Error creating application autoscaling target for managing lambda provisioned concurrency

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [pulumi/pulumi-aws#822]
Hi, 
I tried create application auto scaling policy for provisioned concurrency based on this doc:
https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking.html
Based this I have written pulumi script, but I faced this error, after executing script:
 
```
error: Error creating application autoscaling target: ValidationException: Unsupported service namespace, resource type or scalable dimension
```
My code something like this :
```
          appautoscaling.Target(
                'some_name,
                service_namespace="lambda",
                resource_id=f'function:some_lambda.name:some_lambda.version',
                min_capacity=1,
                max_capacity=10,
                scalable_dimension="lambda:function:ProvisionedConcurrency"
            )
```

Through cli I can create that target and then policy.
What is wrong or pulumi doesn't support this now ?
Thanks.

**Comment by stack72** [comment]
Hi @Ilchuk-Mihail 

Apologies for the issue you are facing here - please can you tell me what version of pulumi-aws you are using for this?

Paul

**Comment by stack72** [comment]
Hi @Ilchuk-Mihail 

Another question on this, is the version being set as $LATEST?

**Comment by Ilchuk-Mihail** [comment]
I added `publish=True` parameter in lambda Function constructor, so it will create a new version for each update, and I used this version.
Also I tried to use alias for Lambda, but got the same error.

I used these versions: 
pulumi  1.6.1
pulumi-aws 1.14.1

**Comment by Ilchuk-Mihail** [comment]
Connected with: https://github.com/pulumi/examples/issues/491

**Comment by mikhailshilkov** [comment]
@Ilchuk-Mihail Here is a TypeScript example which works for me:

``` ts
const resourceId = pulumi.interpolate`function:${lambda.name}:${lambda.version}`;
const target = new aws.appautoscaling.Target("target", {
    resourceId,
    serviceNamespace: "lambda",
    scalableDimension: "lambda:function:ProvisionedConcurrency",
    minCapacity: 1,
    maxCapacity: 10,
});
```

I'm not fluent with python, but I suspect your `resource_id` is not built correctly?

**Comment by stack72** [comment]
Hi @Ilchuk-Mihail 

Please can you let me know if you still need help with this issue. 

Thanks

Paul

**Comment by stack72** [comment]
I am going to close this out as we haven't heard anything back on the issue - if you still have issues, please let us know

Paul
