### ISSUE TITLE
Any changes to user attributes trigger creation of new user pool. All existing users get removed

### ISSUE THREAD

**Issue by naumanmahanatx** [pulumi/pulumi-aws#828]
Please see code below. The user pool gets created fine. After that if i add additional attributes and apply changes pulumi deletes the original user pool and creates a new one. All existing users gets removed. 

Additional attributes can be added from UI. and aws cli. see https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/update-user-attributes.html There seems to be similar issues in terraform which seems to have resolved please see https://github.com/terraform-providers/terraform-provider-aws/issues/3891

 
# Create Cognito User pool 
        appuserpool = aws.cognito.UserPool(
           "app-user-pool",
            name="userpool",
            alias_attributes=["preferred_username"],
            auto_verified_attributes=["email"],
            admin_create_user_config={
                "UnusedAccountValidityDays": 7,
                "AllowAdminCreateUserOnly": True
            },
            schemas=[
                {
                    "name": "email",
                    "stringAttributeConstraints": {
                        "minLength": "0",
                        "maxLength": "2048"
                    },
                    "developerOnlyAttribute": False,
                    "required": True,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "testKey",
                    "stringAttributeConstraints": {
                        "minLength": "32",
                        "maxLength": "32"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "initialRole",
                    "stringAttributeConstraints": {
                        "minLength": "1",
                        "maxLength": "256"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "testattribute",
                    "stringAttributeConstraints": {
                        "minLength": "1",
                        "maxLength": "256"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
            ])

# Example additional user attribute

                 {
                    "name": "testattribute2",
                    "stringAttributeConstraints": {
                        "minLength": "1",
                        "maxLength": "256"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
#####
# Add New example user attribute

        # Create Cognito User pool 
        appuserpool = aws.cognito.UserPool(
           "app-user-pool",
            name="userpool",
            alias_attributes=["preferred_username"],
            auto_verified_attributes=["email"],
            admin_create_user_config={
                "UnusedAccountValidityDays": 7,
                "AllowAdminCreateUserOnly": True
            },
            schemas=[
                {
                    "name": "email",
                    "stringAttributeConstraints": {
                        "minLength": "0",
                        "maxLength": "2048"
                    },
                    "developerOnlyAttribute": False,
                    "required": True,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "testKey",
                    "stringAttributeConstraints": {
                        "minLength": "32",
                        "maxLength": "32"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "initialRole",
                    "stringAttributeConstraints": {
                        "minLength": "1",
                        "maxLength": "256"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "testattribute",
                    "stringAttributeConstraints": {
                        "minLength": "1",
                        "maxLength": "256"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
                {
                    "name": "testattribute2",
                    "stringAttributeConstraints": {
                        "minLength": "1",
                        "maxLength": "256"
                    },
                    "developerOnlyAttribute": False,
                    "required": False,
                    "attributeDataType": "String",
                    "mutable": True
                },
            ])
The user pool will get recreated instead of just adding attributes pulumi recreates the user pool

Thanks.

**Comment by stack72** [comment]
Hi @naumanmahanatx 

The userPool resource will force a new resource when the schema attribute is updated. This is because, as of this time, there is no way to update a schema in a Cognito User Pool. This isn't just in the SDK but it's also true of the CLI

https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/update-user-pool.html

Unfortunately this isn't something that Pulumi is going to be able to do for you

Paul

**Comment by stack72** [comment]
Hi @naumanmahanatx 

I have not heard back from you on this issue. As this is something that isn't supported in the AWS SDK or CLI, I am going to close this issue out

If you need anything else, please do let me know

Paul

**Comment by naumanmahanatx** [comment]
Thanks for looking into this and  closing this issue. Hopefully AWS can support updating schemas from cli or sdk in future.
