### ISSUE TITLE
AWS Amplify plugin

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi-aws#839]
[AWS Amplify](https://aws.amazon.com/amplify/) is a framework that acts as a bridge between DevOps teams and Frontend teams.

It comes with several SDKs (JS, React, etc.) as well as a CLI that can be extended through plugins.

According to the [documentation](https://aws-amplify.github.io/docs/cli-toolchain/usage#--providers):
> Currently there is only one official provider plugin: `amplify-provider-awscloudformation`

> Provider plugins contained in this object will be initialized, and able to provide functionalities for creation and maintenance of the cloud resources.

It would be great to be able to use Pulumi instead of CloudFormation in Amplify.

Typical use cases:
- Creating an authentication backend : `amplify auth add`
- Creating a REST or a GraphQL API : `amplify api add`
- Creating a function : `amplify function add`

In a sense, the idea behind Amplify is very close to Pulumi's AWS Crosswalk : better accessibility to high-level cloud use-cases.

**Comment by mikhailshilkov** [comment]
Amplify is supported in Pulumi these days: https://www.pulumi.com/registry/packages/aws/api-docs/amplify/
