### ISSUE TITLE
Audit AWS resource overlay to ensure proper name limits are in place

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-aws#84]

**Comment by stack72** [comment]
@CyrusNajmabadi / @lukehoban is this still something we need to care about?

**Comment by lukehoban** [comment]
I haven’t heard any reports of issues here recently - but it’s definitely still a problem in principal. I’m fine closing this though - I’m not sure we are likely to do anything more to proactively try and address this at this stage.

**Comment by stack72** [comment]
Ok, closing this out for now - we can revisit it in 2020 if needed
