### ISSUE TITLE
healthchecks for containerDefinitions don't calculate changes correctly

### ISSUE THREAD

**Issue by baronfel** [pulumi/pulumi-aws#847]
I had a `FargateTaskDefinition` with inline `containers`, where one of the containers had a `healthCheck` with the following content:

```javascript
healthCheck: {
 command: ["CMD-SHELL", "curl -f http://localhost || exit 1"],
}
```

and I noticed that each `pulumi up` was causing a replacement of the task definition.  I dug further into the diff generated and saw that there were some properties on the 'current state' that were not in the 'about to be applied' state, and after some trial and error determined that the `healthCheck` defaults for `interval`, `retries`, and `timeout` were required to prevent this recalculation, ie:

```javascript
healthCheck: {
  // healthchecks help the cluster replace bad services
  command: ["CMD-SHELL", "curl -f http://localhost || exit 1"],
  // these next three properties are all just the default values, but there's a bug in pulumi's change detection
  // where if you don't set them, the container definition always flags as needing replacement
  interval: 30,
  retries: 3,
  timeout: 5
},
```

This feels like a bug to me, because the values are clearly being set to defaults, and as soon as I added those properties myself `pulumi up` reported no changes.

I think the change-detection should be enhanced for healthchecks to not require these properties.

**Comment by lukehoban** [comment]
This is also being tracked in https://github.com/hashicorp/terraform-provider-aws/issues/22060 upstream.

**Comment by mikhailshilkov** [comment]
The upstream issue was closed due to inactivity, this issue is 4 year old with no comments or upvotes, so I'll take the liberty to follow upstream here.
