### ISSUE TITLE
Deprecate `securityGroups` instance argument 

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aws#852]
[`securityGroups`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ec2/#InstanceArgs-securityGroups) is a legacy setting from EC2's "classic" days and is almost always the wrong argument for users to use. When `securityGroups` is used, any changes to the list of security groups will result in replacing the instance (this is an EC2 limitation). Instead users should use [`vpcSecurityGroupIds`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ec2/#InstanceArgs-vpcSecurityGroupIds) which allows for changes.

Recommendation: can we deprecate `securityGroups` and/or log a warning when it is used to discourage its use?

**Comment by stack72** [comment]
@clstokes this doesn't feel like the correct fix IMO - this parameter is allowed because of EC2 classic - terraform still supports that.

If we mark as deprecated then we may be adding confusion if they try and use EC2-Classic

Thoughts?

**Comment by clstokes** [comment]
`vpcSecurityGroupIds` works for EC2-Classic too, so it should always be used. Using `securityGroups` is the wrong argument for nearly all users.

Given this, I think deprecating `securityGroups` is the right move.

**Comment by stack72** [comment]
ok, can you tell me what message you would like the deprecation notice to have? I will be able to do it once https://github.com/pulumi/pulumi-terraform-bridge/pull/96 is merged

**Comment by clstokes** [comment]
How about _"Use of `securityGroups` is discouraged as it does not allow for changes and will force your instance to be replaced if changes are made. To avoid this, use `vpcSecurityGroupIds` which allows for updates."_ ?

Can we "parameterize" the attribute names `vpcSecurityGroupIds` for the different languages?
