### ISSUE TITLE
pulumi.all level-pro with multiple Output<string> into string

### ISSUE THREAD

**Issue by jandom** [pulumi/pulumi-aws#859]
Hi there guys, 

Many thanks for providing this awesome tool! I just bumped into something a bit tricky trying to create an ELB configuration template with a large number of deps. Here is a minimal example

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
import * as pulumi from "@pulumi/pulumi";

import {
  createSecurityGroupArgs,
  createVpcArgs,
} from "./src/args/ec2";
import { createStackConfig } from "./src/stack";

const stackConfig = new pulumi.Config("application-backend");
const config = createStackConfig(stackConfig);

const customVpc = new awsx.ec2.Vpc("custom", createVpcArgs(config));

const securityGroup = new aws.ec2.SecurityGroup(
  "security-group",
  createSecurityGroupArgs(config, customVpc)
);

const settings: aws.types.output.elasticbeanstalk.ConfigurationTemplateSetting[] =  ([
  {
    name: "VPCId",
    namespace: "aws:ec2:vpc",
    value: customVpc.id,
  },
  {
    namespace: "aws:autoscaling:launchconfiguration",
    name: "SecurityGroups",
    value: securityGroup.id,
  }
]);
```

Of course that's a naughty thing to do 

> Type 'Output<string>' is not assignable to type 'string'

One should use `pulumi.all` but 
- it's really complicated&error prone, when you need to convert say 7 outputs into strings
- it doesn't "spark joy"

Is that the only way to go? Is there no better way to get this off the ground?

This issue seems related to other, existing ones
- https://github.com/pulumi/pulumi-aws/issues/410

**Comment by pgavlin** [comment]
> Type 'Output' is not assignable to type 'string'

Which line triggers this error?

**Comment by jandom** [comment]
2 lines

> value: customVpc.id,
value: securityGroup.id,

Value is supposed to be a string in ConfigurationTemplateSetting

**Comment by pgavlin** [comment]
I think things will work out if you change the type from `aws.types.output.elasticbeanstalk.ConfigurationTemplateSetting` to `aws.types.input.elasticbeanstalk.ConfigurationTemplateSetting`.

**Comment by jandom** [comment]
Problem solved!

**Comment by jandom** [comment]
Many many thanks @pgavlin
