### ISSUE TITLE
Route53 Record Type documentation contains bug

### ISSUE THREAD

**Issue by reilly3000** [pulumi/pulumi-aws#861]
The docstring for aws.route53.Record.type reads:
`
PRIMARY or SECONDARY. A PRIMARY record will be served if its healthcheck is passing, otherwise the SECONDARY will be served. See http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring-options.html#dns-failover-failover-rrsets
`
via https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/route53/#Record-type

However in practice the `type` property seems to be used for indicating the DNS record type, ie "A", "CNAME" etc.

**Comment by clstokes** [comment]
@stack72 is there a way to fix specific instances of documentation issues on resource properties, or does this need the broader fix as described in https://github.com/pulumi/pulumi-terraform-bridge/issues/15 ?

**Comment by stack72** [comment]
@clstokes this is still a problem that needs fixed in the bridge I'm afraid :/

**Comment by leezen** [comment]
Closing as dupe of https://github.com/pulumi/pulumi-terraform-bridge/issues/15
