### ISSUE TITLE
was.rds.Cluster gets stuck in failing update state if shorthand engine_version string is supplied

### ISSUE THREAD

**Issue by sammck** [pulumi/pulumi-aws#867]
I have encountered what seems like a bug in aws.rds.Cluster, at least with Aurora and in Python. If you specify an engine_version of, say '5.7' it will happily create the cluster for you. But from that point on, on any update it thinks that the cluster version has changed (ostensibly because AWS converts it to a fully qualified form in the resource) and tries to update it, and the update fails because the resource says that you are attempting to  change to the same version. It seems to only work properly if a fully qualified version string is supplied; e.g., '5.7.mysql_aurora.2.07.1'

**Comment by lukehoban** [comment]
This is - unfortunately - a behaviour of the upstream https://github.com/terraform-providers/terraform-provider-aws and of AWS itself.  They both are liberal in what they accept here, but then will show (benign) diffs if you don't fully specify what you really want.  

The solution should be just to encode the specific version you do really want, or else add `{ ignoreChanges: ["engineVersion"] }` to suppress any diffs related to this property after creation.

Hopefully that helps - if not let us know.
