### ISSUE TITLE
LogSubscriptionFilter expected type does not match docs

### ISSUE THREAD

**Issue by ValkyrieUK** [pulumi/pulumi-aws#869]
[The documentation ](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/cloudwatch/#example-usage-10) insinuates that the property `logGroup` can be a `string`. Currently the only supported type is `pulumi.Input<aws.cloudwatch.LogGroup>`. This makes it a little awkward to setup as I first have to `aws.cloudwatch.LogGroup.get` the resource before I can use it even if the log group name is predictable e.g `/aws/lambda/lambdaFunctionName`.

In an ideal scenario the following would be valid.

```typescript
new aws.cloudwatch.LogSubscriptionFilter('alerting-lambda-log-filter', {
  name: `${serviceName}-alerts-log-filter`,
  filterPattern: '?error ?timed ?Error',
  logGroup: '/aws/lambda/myLambdaFunction',
  roleArn: lambdaRole.arn,
  destinationArn: lambdaAlerts.arn,
});
```

**Comment by leezen** [comment]
Thanks for pointing out this inconsistency. I'll keep this open to track the desire to simply use the log group name and I've created a separate issue for the docs bug https://github.com/pulumi/docs/issues/2512

**Comment by stack72** [comment]
Hi @ValkyrieUK 

This was actually updated in v1.25.0 of pulumi-aws. We now allow the LogGroup type OR the string of the LogGroup name

I hope that helps you?

Paul

**Comment by ValkyrieUK** [comment]
Hey @stack72 ,

Thats great, thank you. I'll close this issue now.

Cheers

**Comment by stack72** [comment]
Thanks so much for coming back to me on this @ValkyrieUK
