### ISSUE TITLE
Elastic Beanstalk always show diff.

### ISSUE THREAD

**Issue by skopa** [pulumi/pulumi-aws#878]
When setups the settings of elastic beanstalk environment Pulumi always show updates.

STR:
configure some environment with settings.
run `pulumi up`
run `pulumi up` one more time without changes

second runs will show diff

**Comment by leezen** [comment]
Could you please provide more details on what your program looks like and where the diff occurs?

**Comment by clstokes** [comment]
Same issue as https://github.com/pulumi/pulumi-aws/issues/920, which has repro code.

**Comment by lukehoban** [comment]
Closing as dupe of #920.
