### ISSUE TITLE
Cannot change region of bucket

### ISSUE THREAD

**Issue by squarebracket** [pulumi/pulumi-aws#879]
If you create a bucket in a particular region, but then want to "move" that bucket to another region by changing its `region` attribute, the change fails with:
```
updating urn:pulumi:x::y::aws:s3/bucket:Bucket::z: error reading S3 Bucket (z):
  BucketRegionError: incorrect region, the bucket is not in 'new-region' region at
  endpoint ''
```
In this scenario, I think it would make more sense to delete the bucket in the "old" region, and create the bucket in the "new" region, i.e. do a resource replacement rather than outright fail.

**Comment by lukehoban** [comment]
I believe this will be possible to implement correctly once https://github.com/pulumi/pulumi-terraform-bridge/issues/14 is implemented.

**Comment by iwahbe** [comment]
I can confirm that we still have the same issue with `v5.42.0`.

This is still a dangerous change:
```patch
import * as aws from "@pulumi/aws";

-const provider = new aws.Provider("p", {region: "us-east-1"})
+const provider = new aws.Provider("p", {region: "eu-west-1"})

new aws.s3.Bucket("bucket", {}, {provider})
```

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/244 possibly related.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/pull/3497 should enable moving the bucket by having Pulumi calculate a replacement plan.

**Comment by t0yv0** [comment]
Had to revert the initial fix due to a legacy situation causing unexpected replaces for stacks with states on old versions on Pulumi: https://github.com/pulumi/pulumi-aws/issues/3826  - this needs a workaround before we move forward.
