### ISSUE TITLE
Mark `secretKey` as secret on Provider

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aws#884]
#### Problem
If I use a custom provider and pass in a `secretKey`, the secret key value ends up in plaintext in the state file. 

#### Suggestion 
`secretKey` should be marked secret automatically by the provider itself so that users don't have to do the workaround below.

#### Code to reproduce
```ts
const awsProvider = new aws.Provider("main", {
    region: <aws.Region>env["AWS_REGION"]!,
    accessKey: env["AWS_ACCESS_KEY_ID"]!,
    secretKey: env["AWS_SECRET_ACCESS_KEY"]!,
});
```

#### Workaround
```ts
const awsProvider = new aws.Provider("main", {
    region: <aws.Region>env["AWS_REGION"]!,
    accessKey: env["AWS_ACCESS_KEY_ID"]!,
    secretKey: pulumi.secret(env["AWS_SECRET_ACCESS_KEY"]!), // Use pulumi.secret(...) to protect this value
});
```

**Comment by ceelian** [comment]
Just for reference, in python it would be
```python
import pulumi
import pulumi_aws as aws

aws_provider = aws.Provider("main", region=env["AWS_REGION"], access_key=env["AWS_ACCESS_KEY_ID"],
                        secret_key=pulumi.Output.secret(env["AWS_SECRET_ACCESS_KEY"]))
```

**Comment by stack72** [comment]
We don't store these values in Provider any more - that was fixed since this issue was raised - sorry for the issue here

Paul
