### ISSUE TITLE
Cannot remove ebs volumes that come with AMI

### ISSUE THREAD

**Issue by saada** [pulumi/pulumi-aws#885]
Example AMI: centos/7.6/aws/DCOS-1.11.11/docker-19.03.0-ce/selinux_disabled
If you try to spin that AMI up, it launches with an additional 5 ebs volumes that I want to remove. 

These are the only fields I could find on the `aws.ec2.Instance()` constructor that were related. Unfortunately, `ebsBlockDevices` only covers additional volumes, not existing ones on the AMI.

```js
      rootBlockDevice: { volumeSize: 50 },
      ebsBlockDevices: [],
```

You can see that using the aws console UI, it's easy to remove those default volumes as shown in screenshot:

<img width="1590" alt="Screen Shot 2020-02-25 at 12 01 09 PM" src="https://user-images.githubusercontent.com/1087987/75269245-9c8f4e80-57c6-11ea-8ec3-0cea5154a6e1.png">

What is the pulumi way of creating AWS instances without the existing ebs volumes attached to the AMI?

**Comment by leezen** [comment]
Counterintuitively, the way to do this is to specify those devices as 'noDevice' in the ephemeral device section. Here's an example:

```typescript
const instance = new aws.ec2.Instance("myinstance", {
    ami: ami.id,
    instanceType: "t2.micro",
    ephemeralBlockDevices: [
        {
            deviceName: "/dev/sde",
            noDevice: true
        },
        {
            deviceName: "/dev/sdf",
            noDevice: true
        },
        {
            deviceName: "/dev/sdg",
            noDevice: true
        },
        {
            deviceName: "/dev/sdh",
            noDevice: true
        }
    ]
});
```

**Comment by leezen** [comment]
For reference: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html -- and the NoDevice mapping is considered an 'ephemeral' device (vs. an EBS-backed device).

Closing this issue, but feel free to re-open if you have additional questions/concerns.
