### ISSUE TITLE
Incorrect typings in ElastiCache

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi-aws#886]
`aws.elasticache.Cluster#clusterAddress` is of type `Output<string>`. It should be `Output<string | undefined>`; if you are running a single Redis node this will be undefined and you have to spelunk through `cacheNodes` to get the address.

**Comment by stack72** [comment]
Hi @eropple 

Can you give me a small reproduction of this that I can use to triage it?

Thanks

Paul

**Comment by stack72** [comment]
ping @eropple

**Comment by eropple** [comment]
I've already worked around it, sorry. You can attempt to create a one-node Redis AWS cluster and try to use `clusterAddress` as an output.

**Comment by stack72** [comment]
This is now marked as an optional field:

> public /*out*/ readonly clusterAddress!: pulumi.Output<string>;

Notice the use of `!` so we can close this out
