### ISSUE TITLE
Default provider `secretKey` should be marked as a secret

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#888]
Today, if a user passes `aws:secretKey` as a Pulumi config setting, it is not encrypted in the Pulumi state file.  If they pass it into a first-class provider, I believe we will correctly encrypt it.  We should ensure that secret config gets passed into the default provider as secrets.

**Comment by lukehoban** [comment]
(note - this may actually just be an issue in pulumi/pulumi)

**Comment by clstokes** [comment]
Related to https://github.com/pulumi/pulumi-aws/issues/884.

**Comment by lukehoban** [comment]
Closing as dupe of #884
