### ISSUE TITLE
AWS temporary credentials of custom aws.Provider resources are saved in Pulumi state, preventing stack deletion

### ISSUE THREAD

**Issue by nhinds** [pulumi/pulumi-aws#890]
The `aws.Provider` resource automatically grabs my `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` environment variables and persists them in Pulumi's state as its inputs and outputs. For permanent credentials, it seems odd to store secrets from the environment like this (#884 tracks marking them as secret, at least), but for temporary credentials this prevents stacks from being deleted because Pulumi tries to use the persisted credentials when deleting the stack.

The behaviour seems to have changed in #874

In my use case, this makes it impossible to `pulumi destroy` an EKS cluster that was created using the [`eks.getRoleProvider()`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/#getRoleProvider) helper unless I run a dummy `pulumi up` to update the `aws.Provider` first.

Minimal reproduction:
```typescript
import * as aws from "@pulumi/aws";

const provider = new aws.Provider("provider", { region: "us-west-2" });
new aws.cloudwatch.LogGroup("logGroup", undefined, { provider: provider });
```

Assume a role on the CLI (or run `aws sts get-session-token` to get temporary credentials and export them into your environment), then run `pulumi up`. Wait for your original credentials to expire, then re-assume the role and run `pulumi destroy`.

More detailed steps:
1. Get temporary token and confirm it is valid
```
$ aws sts get-session-token --duration-seconds 900
{
    "Credentials": {
        "AccessKeyId": "redacted",
        "SecretAccessKey": "redacted",
        "SessionToken": "redacted",
        "Expiration": "2020-03-05T01:04:31Z"
    }
}
$ export AWS_ACCESS_KEY_ID=redacted AWS_SECRET_ACCESS_KEY=redacted AWS_SESSION_TOKEN=redacted
$ aws sts get-caller-identity
{
    "UserId": "redacted",
    "Account": "redacted",
    "Arn": "arn:aws:iam::redacted:user/redacted"
}
```
2. Create the stack with Pulumi
```
$ pulumi up
Previewing update (foo):
     Type                        Name                          Plan       
 +   pulumi:pulumi:Stack         aws-provider-credentials-foo  create     
 +   ├─ pulumi:providers:aws     provider                      create     
 +   └─ aws:cloudwatch:LogGroup  logGroup                      create     
 
Resources:
    + 3 to create

Do you want to perform this update? yes
Updating (foo):
     Type                        Name                          Status      
 +   pulumi:pulumi:Stack         aws-provider-credentials-foo  created     
 +   ├─ pulumi:providers:aws     provider                      created     
 +   └─ aws:cloudwatch:LogGroup  logGroup                      created     
 
Resources:
    + 3 created

Duration: 9s

Permalink: file:///home/redacted/.pulumi/stacks/foo.json
```
3. Observe that Pulumi has saved the temporary credentials to its state file:
```
$ grep -E 'accessKey|secretKey|token' ~/.pulumi/stacks/foo.json
                        "accessKey": "redacted",
                        "secretKey": "redacted",
                        "token": "redacted"
                        "accessKey": "redacted",
                        "secretKey": "redacted",
                        "token": "redacted"
```
4. Wait for the temporary credentials to expire, then get fresh ones:
```
$ aws sts get-caller-identity

An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired
$ unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN 
$ aws sts get-session-token --duration-seconds 900
{
    "Credentials": {
        "AccessKeyId": "redacted",
        "SecretAccessKey": "redacted",
        "SessionToken": "redacted",
        "Expiration": "2020-03-05T01:19:50Z"
    }
}
$ export AWS_ACCESS_KEY_ID=redacted AWS_SECRET_ACCESS_KEY=redacted AWS_SESSION_TOKEN=redacted
$ aws sts get-caller-identity
{
    "UserId": "redacted",
    "Account": "redacted",
    "Arn": "arn:aws:iam::redacted:user/redacted"
}
```
5. Try to destroy the stack, it hangs trying to delete the resource using the custom provider:
```
$ pulumi destroy
Previewing destroy (foo):
     Type                        Name                          Plan       
 -   pulumi:pulumi:Stack         aws-provider-credentials-foo  delete     
 -   ├─ aws:cloudwatch:LogGroup  logGroup                      delete     
 -   └─ pulumi:providers:aws     provider                      delete     
 
Resources:
    - 3 to delete

Do you want to perform this destroy? yes
Destroying (foo):
     Type                        Name                          Status       
     pulumi:pulumi:Stack         aws-provider-credentials-foo               
 -   └─ aws:cloudwatch:LogGroup  logGroup                      deleting..   
```

Adding `-v9 --logtostderr` doesn't provide any relevant information, but setting `TF_LOG=TRACE` shows that AWS is returning `403` with the code `ExpiredToken` and message "The security token included in the request is expired".

I downgraded to `@pulumi/aws` `1.21.0`, which does not store temporary credentials in the state file on `pulumi up`, and `pulumi destroy` works fine after re-exporting fresh temporary credentials.

It seems like `@pulumi/aws` should not be defaulting the `accessKey`, `secretKey`, or `token` parameters based on its environment at the point `pulumi up` was run, since the upstream providers (e.g. the Terraform AWS provider) should be able to discover fresh values from their environment when they are run.

**Comment by unthought** [comment]
The same problem happens when creating ACM certificates, which must by definition sit in `us-east-1`. In our case it even prevents running pulumi up, as it seems to use the old credentials to read the old state. If I run `up --target-replace <provider-urn>`, the stack recovers.

PS: In our case we don't fetch through awscli, instead we run pulumi under [aws-vault](https://github.com/99designs/aws-vault), which is how we get the temp tokens (using role assumption) into the env vars.
