### ISSUE TITLE
Remediate gone MaxItems

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws#900]
TF removed a bunch of MaxItems annotations from the latest version of the AWS provider https://github.com/terraform-providers/terraform-provider-aws/commit/e6489e61a37b1b27bcc1566e33b9ffb34f25b362 which breaks our singular/plural rules and corresponding types. They were just clearing their lint warnings, so apparently they don’t need this annotation (see https://github.com/bflad/tfproviderlint/blob/ddad891cc11517c1a15c58687aaaef1667b5272b/passes/S031/README.md).

We should come up with a way to fix this for 2.53.0 and long-term.

**Comment by lukehoban** [comment]
> a way to fix this for 2.53.0

For now, let's manually recover the existing experience by adding `MaxItemsOne: boolRef(true),` annotations in `resources.go`.  That will at least avoid a breaking change.

In fact, that might be all we can realistically do here?
