### ISSUE TITLE
 tags: error untagging resource (InvalidSignatureException)

### ISSUE THREAD

**Issue by Erwinvandervalk** [pulumi/pulumi-aws#909]
I'm trying to modify tags on a lambda using pulumi and I'm getting the following error:

  aws:lambda:Function (________):
    error: 1 error occurred:
        * updating urn:pulumi:sandbox::_____::aws:lambda/function:Function::_____-_____: error updating Lambda Function (arn:aws:lambda:eu-central-1:_____:function:_____-_____) tags: error untagging resource (arn:aws:lambda:eu-central-1:_____:function:_____-_____): InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
        status code: 403, request id: 6009aba4-ee05-459d-8c21-ea1bd19f5ff4

I get the same errors if I remove the tags.

I'm fairly certain it's not a security issue though, cause i'm able to delete and recreate the lambda (with the new tags) just fine. 

Any thoughts on what might be the issue?

I'm on version v1.13.0 but I had the same issue with 1.12.0. 

Thanks!

**Comment by leezen** [comment]
Signature mismatch can occur if you're trying to use a provider configured for one region against resources in another region. Could that possibly be the case here?

**Comment by Erwinvandervalk** [comment]
Sorry for the slow response. I'll double check, but that would be weird. I'm able to change any other attribute on the lambda. I have a default profile set up that i'm using for this. It's only when I change the tag that this happens.

**Comment by stack72** [comment]
Hi @Erwinvandervalk 

Did you get a chance to checkout on this?

Thanks

Paul

**Comment by Erwinvandervalk** [comment]
HI Paul, sorry, haven't been able to create a repro. Having destroyed my stack and recreating it now i'm not able to repro it. 

probably was a temporary local thing then. 
Will close the issue.

**Comment by stack72** [comment]
Thanks for getting back to me @Erwinvandervalk 

Let me know if it happens again and we can reopen

Paul
