### ISSUE TITLE
associatePublicIpAddress type is incorrect

### ISSUE THREAD

**Issue by slikk66** [pulumi/pulumi-aws#911]
https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/input.ts#L5631

The comment shows "boolean", my old code used "boolean", but now it's listed as type string and I'm pretty sure that is not correct.

1.27.0

**Comment by stack72** [comment]
This looks like it has been fixed to be a boolean again - please let me know if there are any further issues here

Paul
