### ISSUE TITLE
Stuck at aws.ecr.getCredentials

### ISSUE THREAD

**Issue by spion-h4** [pulumi/pulumi-aws#912]
Example:

```typescript
const repository = new aws.ecr.Repository('test');
export let credentials = repository.registryId.apply(registryId => {
  return aws.ecr.getCredentials({ registryId });
})
```

Result: Repository gets created, the call to ecr.getCredentials is made (via runtime.invoke) but there is no response whatsoever from the runtime. The last line in the debug logs with verbosity 9 is:

```
I0327 15:06:15.297615   30958 eventsink.go:63] eventSink::Debug(<{%reset%}>RegisterResource RPC finished: resource:test[aws:ecr/repository:Repository]; err: null, resp: urn:pulumi:gk::test::aws:ecr/repository:Repository::test,test-67e5b06,.... a bunch of other data here.
```

No indication that the runtime got the getCredentials request.

**Comment by lukehoban** [comment]
Could you try updating to:

```ts
const repository = new aws.ecr.Repository('test');
export let credentials = repository.registryId.apply(registryId => {
  return aws.ecr.getCredentials({ registryId }, { async: true });
});
```

There are hangs that may occur on recent versions of Node if that `async: true` is not passed.  See https://github.com/pulumi/pulumi/issues/3528.  We are making a breaking change in `2.0` to make that the default, see https://github.com/pulumi/pulumi/issues/3693.

**Comment by spion-h4** [comment]
Yup, that did the trick. Thank you!
