### ISSUE TITLE
Need help configuring route tables with Go

### ISSUE THREAD

**Issue by chirauki** [pulumi/pulumi-aws#928]
Hi all,

First of all, if I should be addressing somewhere else for help, please let me know.

I've been trying to configure a VPC with some subnets, an internet gw and I want to create a route table so default route points to IG. I've been looking at the docs and can only see examples in typescript but not Go.

My issue right now is that I have no idea on how to get the GW ID (created with pulumi) to use it as a param in the route table here https://pkg.go.dev/github.com/pulumi/pulumi-aws@v1.27.0/sdk/go/aws/ec2?tab=doc#RouteTableRoute

I'm lost on how to get the ID converted to a string pointer... Clues?

**Comment by EvanBoyle** [comment]
Hey @chirauki, broadly this example of VPC configuration in go may be of use to you: https://github.com/joeduffy/pulumi-architectures/blob/master/aws-go-base-infra/main.go

More specifically, you actually need to construct an instance of [RouteTableRouteArgs](https://pkg.go.dev/github.com/pulumi/pulumi-aws@v1.27.0/sdk/go/aws/ec2?tab=doc#DefaultRouteTableRouteArgs) which will require passing a `pulumi.StringPointerOutput`.

You should be able to call `id.ToStringOutput()` and pass that in: https://github.com/pulumi/pulumi/blob/2408d34c712d01fa0dd9382e6068878fc2ee274d/sdk/go/pulumi/types_builtins.go#L2824

The `StringOutput` type implements `StringPointerOutput` and you should be able to use that.

**Comment by chirauki** [comment]
I just realised by looking at the main you provided that I was trying to just create a `RouteTableRoute` object as is, not using the `NewRouteTableRoute` method... shame on me.

BTW, that main you provided is gold...

Thans @EvanBoyle !
