### ISSUE TITLE
error tagging resource

### ISSUE THREAD

**Issue by Erwinvandervalk** [pulumi/pulumi-aws#930]
Hi there,

I'm getting another error while tagging a resource. This time fargate:

  aws:ecs:Service (_____):
    error: 1 error occurred:
    	* updating urn:pulumi:test::aws-infra::awsx:x:ecs:FargateService$aws:ecs/service:Service::_____: error updating ECS Service (arn:aws:ecs:eu-central-1:_____:service/_____) tags: error tagging resource (arn:aws:ecs:eu-central-1:_____:service/_____): InvalidParameterException: **Long arn format must be used for tagging operations**
 
The code i'm using to tag the resource is fairly straightforward:

``` typescript

  const tags = {
     tag:"value"
  };

   new awsx.ecs.FargateService(servicename, {
            name: servicename,
            cluster: cluster,
            taskDefinitionArgs: {
                taskRole: taskRole,
                logGroup: logGroup,
                container: {
                    image: pulumi.concat(ecr.repositoryUrl, ":latest"),
                    cpu: 256 /*1024 is one cpu */,
                    memory: 512 /*MB*/,
                }
            },
            assignPublicIp: true,
            subnets: settings.vpc.publicSubnetIds,
            desiredCount: 1,
            deploymentMaximumPercent: 100,
            deploymentMinimumHealthyPercent: 0,
            securityGroups: securityGroups,
            tags: TAGS 
        }, {
            provider: settings.provider,
            dependsOn: settingsS3Object,
            customTimeouts: { create: '1m', update: '2m' },
        });

```

Initial deploy works, but updating doesn't.

**Comment by Erwinvandervalk** [comment]
I believe I have found something. https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/ 

Does pulumi use the new arn format or the old one?

**Comment by leezen** [comment]
The ARN format is actually dictated by your account or role per the link you posted. So you can opt into it per the instructions on that page. It doesn't look like there's a way to choose this when creating a role programmatically, unfortunately.

**Comment by Erwinvandervalk** [comment]
ok, thanks
