### ISSUE TITLE
Serializing JavaScript functions fail if `main` in Pulumi.yaml is changed from the default

### ISSUE THREAD

**Issue by lukemundy-vgw** [pulumi/pulumi-aws#933]
I've created a brand new Pulumi project to create a some `aws.lambda.CallbackFunction` resources however I run in to an error on `pulumi preview` or `pulumi up` if I've changed the `main` setting in `Pulumi.yaml`. It appears that due to the change in directory, Pulumi is unable to locate the `package.json` file from the project root.

```
Error: Error reading file '<PATH-TO-PROJECT>/src/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '<PATH-TO-PROJECT>/src/package.json'
        at readFile (<PATH-TO-PROJECT>/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:167:19)
        at computeDependenciesDirectlyFromPackageFile (<PATH-TO-PROJECT>/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:150:22)
        at readPackageTree (<PATH-TO-PROJECT>/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:115:36)
        at p.then.tree (<PATH-TO-PROJECT>/node_modules/read-package-tree/rpt.js:162:20)
```

Steps to reproduce:

1. Create a new Pulumi project `pulumi new aws-typescript`
2. Modify `Pulumi.yaml` and add `main: src/`
3. Move `index.ts` into `src/`
4. Create a `CallbackFunction` in `index.ts`:
```ts
import * as aws from "@pulumi/aws";

const myFunc = new aws.lambda.CallbackFunction("my-func", {
    callback: (foo, bar) => { console.log(foo, bar); }
});
```
5. Run `pulumi preview` or `pulumi up`

Some more context in [Slack](https://pulumi-community.slack.com/archives/CJ909TL6P/p1586246368060000).

**Comment by leezen** [comment]
The `main` in `Pulumi.yaml` describes the working directory. What you probably want is to simply change the main entry point via editing `package.json`. For example:

```
{
    "name": "project",
    "devDependencies": {
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^1.0.0",
        "@pulumi/aws": "^1.0.0",
        "@pulumi/awsx": "^0.18.10"
    },
    "main": "src/index.ts"
}
```

If you do that without modifying `main` in `Pulumi.yaml` - I think you'll get the behavior you want.

**Comment by lukemundy-vgw** [comment]
That appears to work, though does mean I need to modify any paths in my template to be relative to the top-level dir now. Not a huge issue thought.

Thanks for your help.

**Comment by Dominik-K** [comment]
@leezen I think always adding the `main` entry in `package.json` on `pulumi new` will help avoiding such issues from the beginning. Took me some time to figure this out the first time I've seen this.

**Comment by AlexBuitrago** [comment]
Anyone has any ideas how to solve this error?
Error reading file 'infra/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/infra/package.json'
My dir:
- project
    ...
    - infra
        - Pulumi.yaml
        - tsconfig.json
        ...
    - src
       ...
   - package.json
   - tsconfig.json
   
  
I need to have the package.json at that place in my directory.
Any help or alternatives to solve the problem will be welcome.
I'm using @pulumi/pulumi: "^3.4.0"
this error occurs when i run pulumi preview --cwd infra  I run that command in the root of my project.
the problem occurs when I try to use  aws.lambda.CallbackFunction
