### ISSUE TITLE
Kinesis Firehose Processors array only accepts one processor

### ISSUE THREAD

**Issue by benswinburne** [pulumi/pulumi-aws#937]
Just checking this is correct? `processingConfiguration` accepts an array of processors, but then when passing multiple processors I get the following error.

> Exactly 1 Processor needs to be supplied when processing is enabled

```
      processingConfiguration: {
        enabled: true,
        processors: [
          {
            type: 'Lambda',
            parameters: [
              {
                parameterName: 'LambdaArn',
                parameterValue: inputValidator.arn,
              },
              ...pulumiParameterFix,
            ],
          },
          {
            type: 'Lambda',
            parameters: [
              {
                parameterName: 'LambdaArn',
                parameterValue: newLineAdder.arn,
              },
              ...pulumiParameterFix,
            ],
          },
        ],
      },
```

**Comment by leezen** [comment]
Thanks for reporting this. This appears to be how Kinesis itself works. That error message is coming from the Kinesis API. You can see that the API itself does take an array (https://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html)

I tried removing `enabled: true` which allowed the creation to succeed. Oddly, I couldn't find anything in the Kinesis documentation describing this behavior. Unfortunately, I don't know enough about Kinesis on what the best way to do what you're doing to do is, but I'm going to close this out as the correct behavior.
