### ISSUE TITLE
Can't import primary Athena Workgroup

### ISSUE THREAD

**Issue by benswinburne** [pulumi/pulumi-aws#938]
When using the console in Athena, you must set up location for the query results.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1208977/79148527-7eed6700-7dbd-11ea-8140-29861abe90a5.png">

This is because the primary workgroup already exists in the account (region?) and queries are run as part of this workgroup, but it doesn't know where you want to store the results.

I've created a bucket with Pulumi, and I've created a database which uses said bucket, however the console doesn't let you query the database without fixing the workgroup first.

I tried the suggestion on [this StackOverflow post](https://stackoverflow.com/questions/57631490/how-to-modify-athenas-primary-workgroup-configuration-using-terraform) which suggests importing the resource so that Pulumi (TF in the post) can configure it.

So I created a workgroup and grabbed the ARN from the console

```
const arn = 'arn:aws:athena:eu-west-1:ACCOUNTNO:workgroup/primary'
new aws.athena.Workgroup('name', {config}, { import: arn });
```

But got this error

```
error: Preview failed: refreshing urn:pulumi:production::infrastructure::aws:athena/workgroup:Workgroup::primary-workgroup: error reading Athena WorkGroup (arn:aws:athena:eu-west-1:ACCOUNTID:workgroup/primary): InvalidRequestException: 1 validation error detected: Value 'arn:aws:athena:eu-west-1:ACCOUNTID:workgroup/primary' at 'workGroup' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9._-]{1,128}
    {
      AthenaErrorCode: "INVALID_INPUT",
      Message_: "1 validation error detected: Value 'arn:aws:athena:eu-west-1:ACCOUNTID:workgroup/primary' at 'workGroup' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9._-]{1,128}"
    }
```

Which presumably is because the ARN has a `/` in it. How can I access the existing workgroup if I can't use the ARN?

I also noticed the error mentions `workGroup` with a capital G, so I'm not sure where it's getting that from as my ARN is just `workgroup/...`

I also noticed that the account ID in the ARN in the console doesn't appear to match that of my actual account/`aws.getBillingServiceAccount().id`. Mine starts with a 3, and the one in the default workgroup starts with a 4? Any idea why that might be and if that could have anything to do with it?

**Comment by leezen** [comment]
I believe that that error is coming from the API itself. The import will attempt a read and it appears that that read is failing against `arn:aws:athena:eu-west-1:ACCOUNTID:workgroup/primary` Looking at the documentation, I believe the expected `id` for the import is actually the name of the workgroup and not the ARN -- https://www.pulumi.com/docs/reference/pkg/aws/athena/workgroup/. Have you tried that?

**Comment by benswinburne** [comment]
I just gave it a go.

```
const primaryWorkgroup = aws.athena.Workgroup.get(
  'primary-workgroup',
  'primary'
);
```

Does indeed get hold of the resource with

```
arn: arn:aws:athena:eu-west-1:ACCOUNT:workgroup/primary
id: primary
name: primary
```

But then I can't import the resource

```
new aws.athena.Workgroup('name', {config}, { import: 'primary' });
```

> warning: inputs to import do not match the existing resource; importing this resource will fail

**Comment by leezen** [comment]
What's the value of `config` -- that needs to match precisely the properties of the resource you're attempting to import and the warning is suggesting that that isn't the case.

**Comment by benswinburne** [comment]
```
new aws.athena.Workgroup(
  'primary-athena-workgroup',
  {
    configuration: {
      // enforceWorkgroupConfiguration: true,
      // publishCloudwatchMetricsEnabled: true,
      resultConfiguration: {
        outputLocation: pulumi.interpolate`s3://{queryResultBucket.bucket}`,
        // encryptionConfiguration: {
        //   encryptionOption: 'SSE_S3',
        // },
      },
    },
  },
  {
    dependsOn: [queryResultBucket],
    import: 'primary',
  }
);
```

The commented out bits are the bits which I was trying to add in addition to setting the `outputLocation`. I've tried just importing it with no configuration, just the configuration above, and all of the above.

If you can't take control of a resource and update some attributes, doesn't that just mean I'd need to write my program, let it import it, update my program then run it again? how does this work in a CI/CD or even a testing environment if I want to ensure I can adopt a resource but ensure it's set up a specific way?

**Comment by leezen** [comment]
Looking at the config above, it looks like you're missing the `name` key: `name: 'primary'`

In terms of how imports are supposed to work - the programming model philosophy is indeed as you stated. First, import it such that the state is reflected correctly in your program. This way, future mutations are recorded correctly. Then, make any modifications you want in subsequent changes (including removing the `import` statement). From a CD perspective, these are separate commits (one import, one for the change). An analogy might be doing doing things like schema migration where in some cases, you want to ensure a specific commit is flushed through your pipeline before future commits take place.

I'm going to close the issue for now. I was able to successfully import an Athena workgroup with the name. Feel free to re-open if you're still having trouble. Thanks!

**Comment by benswinburne** [comment]
Thanks, Lee. I just checked and it does indeed work with `name: 'primary'`, I hadn't realised that was a required field. Typecript hadn't complained so I'd missed it.

That's a bit of a shame that it needs to be done in two parts. If someone wanted to take the stack and spin it up as a test environment separately it wouldn't work. I wonder if there could be some facility to get the default group similarly to how awsx offers `awsx.ec2.Vpc.getDefault();` for this primary workgroup, but also facilitate updates on it in some way?

```
const primaryWorkgroup = aws.athena.getPrimaryWorkgroup();

primaryWorkgroup.setConfiguration({
  resultConfiguration: {
    outputLocation: pulumi.interpolate`s3://{queryResultBucket.bucket}`,
  }
});
```

Something along those lines perhaps?

**Comment by leezen** [comment]
It's not a required field from the input perspective (since pulumi will do autonaming otherwise), which is why TS didn't complain. But it's required to make the config match the import.

Interesting idea -- could you describe your scenario a bit more? I'm wondering how it would work in practice? Wouldn't two users end up stomping on top of each other? Why not two ephemeral stacks to test instead?

**Comment by benswinburne** [comment]
My scenario is as follows, If I commit the following to the repository, the next test (or developer) to run it against their own stack is going to have it fail to import.

```
new aws.athena.Workgroup(
  'primary-athena-workgroup',
  {
    name: 'primary',
    configuration: {
      resultConfiguration: {
        outputLocation: pulumi.interpolate`s3://{queryResultBucket.bucket}`,
      },
    },
  },
  {
    dependsOn: [queryResultBucket],
    import: 'primary',
  }
);
```

If i commit the following code into the repository, it will import successfully but then doesn't have the configuration which is actually required.

```
new aws.athena.Workgroup(
  'primary-athena-workgroup',
  {
    name: 'primary',
    // configuration: {
    //  resultConfiguration: {
    //    outputLocation: pulumi.interpolate`s3://{queryResultBucket.bucket}`,
    //  },
    // },
  },
  {
    dependsOn: [queryResultBucket],
    import: 'primary',
  }
);
```

If this runs, and the developer goes to the Athena console to run a test query they can't because it won't have attached the storage bucket to the workgroup. What do we do then? Document that they must uncomment the configuration object and run again?

I had been thinking about it from a different AWS account for staging and production but I see what you're saying that it'd clash if two of this stack were run on the same account as it's one main workgroup on the account no matter how many stacks have created databases and storage buckets etc.

I wonder if using my example above it could set if it's not already set by another stack perhaps. That way many stacks would share the result bucket and if the stack which created configuration is removed the configuration is unset.

Starting to get a bit complicated at this point! Probably too complicated...

**Comment by leezen** [comment]
> I wonder if using my example above it could set if it's not already set by another stack perhaps. That way many stacks would share the result bucket and if the stack which created configuration is removed the configuration is unset.

My suggestion there would be to create a common "workgroup" project that has the bucket and other relevant information output as stack outputs. Those outputs can be consumed by other stacks via StackReferences (https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/#inter-stack-dependencies).

Happy to chat more on community slack if you want to talk through any of it https://slack.pulumi.com/ or open a separate issue if you're having trouble with any architectural patterns, but going to close this issue as we've drifted a bit from the resolved import issue at this point.
