### ISSUE TITLE
Upgrading to Pulumi/aws 2.0.0 changes return types

### ISSUE THREAD

**Issue by ValkyrieUK** [pulumi/pulumi-aws#945]
Upgraded this morning and noticed that the return type of some functions has changed.

Pre-2.0.0
```typescript
import * as aws from "@pulumi/aws";
const awsAccountId = aws.getCallerIdentity().awsAccountId // Returns a string
```

2.0.0
```typescript
import * as aws from "@pulumi/aws";
aws.getCallerIdentity() // Returns a Promise
const awsAccountId = aws.getCallerIdentity().then(account => account.id )
```

The documentation also hasn't been updated to reflect this https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/#getCallerIdentity

**Comment by leezen** [comment]
I'll keep this issue open to track the docs change.

In terms of the actual change itself, please see https://www.pulumi.com/docs/get-started/install/migrating-2.0/ which describes how synchronous invokes have been removed and all invokes return promises now.

**Comment by ValkyrieUK** [comment]
Ah okay, big shame on the synchronous invokes. Makes the code no where near as readable/tidy :/

**Comment by praneetloke** [comment]
The API docs now correctly reflect the return type of Functions as well as showing how to use them in conjunction with `pulumi.output()`. I believe we can close this now. What do you think, @leezen ?

**Comment by leezen** [comment]
SGTM
