### ISSUE TITLE
Add support for AWS Cape Town region (af-south-1)

### ISSUE THREAD

**Issue by CSergienko** [pulumi/pulumi-aws#956]
Hi there! Had a look at the existing PRs and Issues and found nothing related to this, so apologies if it's a duplicate.

I am currently getting the following error:
```
Exception: invocation of aws:ec2/getVpc:getVpc returned an error: Invalid AWS Region: af-south-1
```

As per [this pull request](https://github.com/terraform-providers/terraform-provider-aws/pull/12967), Terraform has added support for the recently launched af-south-1 region. Are there plans by the Pulumi team to add support for this region soon as well?

I'm really looking forward to migrating my infra closer to home. :smile: 

Edit:

I am running Pulumi 2.1.0

**Comment by stack72** [comment]
Hi @stack72 

This was released in Pulumi-aws 2.2.0 that was released on April 29th in #947 

Thanks

Paul

**Comment by mikhailshilkov** [comment]
> Hi @stack72

🤣

**Comment by stack72** [comment]
> > Hi @stack72
> 
> 
> 
> 🤣 

Doh!! I’ve even started replying like a bot :)

I meant @CSergienko of course!!

**Comment by CSergienko** [comment]
@stack72 Ah, I think I see why it wasn't working for me. I'm using the Python package, and it doesn't appear to have been added to that part of the SDK as yet.

**Comment by stack72** [comment]
@CSergienko yeah we don’t have overlays in Python as of yet - it’s on the plan though!
