### ISSUE TITLE
Add support for eu-south-1 region

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aws#957]
Added in https://github.com/terraform-providers/terraform-provider-aws/pull/13061.

See also https://github.com/pulumi/pulumi-aws/issues/956.

**Comment by CSergienko** [comment]
Thanks for the speedy response, and apologies for not reporting the issue here directly.

Just a minor correction, the region in question is `af-south-1`, not `eu-south-1` as per the title.

**Comment by clstokes** [comment]
Hey @CSergienko, your issue still for `af-south-1` still exists at https://github.com/pulumi/pulumi-aws/issues/956. I referenced that from this one as they're related - both adding new regions.

**Comment by CSergienko** [comment]
Duly noted! Thanks :smile:

**Comment by stack72** [comment]
Hi folks

This is currently in master as it was merged as part of #955

I will get this released ASAP!

Paul
