### ISSUE TITLE
sourceDestCheck cannot be disabled with aws.ec2.SpotInstanceRequest

### ISSUE THREAD

**Issue by johnktims** [pulumi/pulumi-aws#959]
```
const natInstance = new aws.ec2.SpotInstanceRequest("nat", {
    ami: ami.id,
    instanceType: "t3.nano",
    subnetId: vpc.publicSubnetIds[0],
    vpcSecurityGroupIds: [natSg.id],
    spotPrice: "0.0052",
    keyName: keyPair.keyName,
    sourceDestCheck: false,
    spotType: 'one-time'
});
```
The spot instance is launched with `Source/Destination Check` set to `true`. I am able to set `Source/Destination Check` to `false` in the AWS console so don't think anything is preventing pulumi from changing this value. `aws.ec2.Instance` sets the flag correctly.

```
$ pulumi plugin ls -p
NAME    KIND      VERSION  SIZE    INSTALLED     LAST USED
aws     resource  2.2.0    223 MB  9 hours ago   8 hours ago
aws     resource  1.31.0   222 MB  2 weeks ago   2 weeks ago
docker  resource  0.17.4   44 MB   7 months ago  7 months ago
nodejs  language           17 MB   3 weeks ago   now

$ pulumi version
v1.14.1
```

**Comment by leezen** [comment]
It looks like the issue occurs upstream as well, so we'd need to see if we can help with the effort in https://github.com/terraform-providers/terraform-provider-aws/issues/2751

**Comment by johnktims** [comment]
Thanks for tracking this down, @leezen. I found this workaround for propagating tags to spot instances and used it to disable the source-dest-check via ec2 userdata: https://github.com/hashicorp/terraform/issues/3263#issuecomment-284387578

```
#!/bin/bash
set -ex
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | awk -F'"' '/"region"/ { print $4 }')
INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
aws --region $REGION ec2 modify-instance-attribute --instance-id "$INSTANCE_ID" --no-source-dest-check
```
