### ISSUE TITLE
Cannot use ElasticSearch with ServiceLinkedRole

### ISSUE THREAD

**Issue by manymikes** [pulumi/pulumi-aws#961]
I've followed the documentation (with a few adjustments) as outlined here https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/elasticsearch/ to create an ElasticSearch domain. 

I've adjusted a few things because I'd like to use a t2.small instance for a staging environment to avoid costs–although I believe this issue will still apply to a larger instance as long as the target ES version is > 5.

The issue I am running into is that the ES domain requires a ServiceLinkedRole in order to provision properly. If I add the logic to include a role, it will work the first time, but future deployments fail with: `error: Error creating service-linked role with name es.amazonaws.com: InvalidInput: Service role name AWSServiceRoleForAmazonElasticsearchService has been taken in this account, please try a different suffix.`

I attempted to add a suffix as the error response suggests but that was unsuccessful as a suffix is not allowed on an ES Service Linked Role.

Seems potentially related to the following Terraform issues:
https://github.com/cloudposse/terraform-aws-elasticsearch/issues/5

If it cannot be resolved due to the Terraform implementation, are there any recommendations for a work around?

Thanks!

Here is my implementation:

```typescript
      const esServiceLinkedRole = new aws.iam.ServiceLinkedRole(`${name}-es-${ENV_LOWER}`, {
          awsServiceName: "es.amazonaws.com",
          description: "Managed by Pulumi"
      });
      
      // create es domain
      const currentRegion = aws.getRegion().then(region => region.name);
      const currentCallerIdentity = aws.getCallerIdentity().then(id => id.accountId);
      const esDomain = new aws.elasticsearch.Domain(`${name}-es-${ENV_LOWER}`, {
          accessPolicies: `{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Action": "es:*",
                "Principal": "*",
                "Effect": "Allow",
                "Resource": "arn:aws:es:${currentRegion}:${currentCallerIdentity}:domain/${name}-es-${ENV_LOWER}/*"
              }
            ]
          }`,
          advancedOptions: {
              "rest.action.multi.allow_explicit_index": "true",
          },
          clusterConfig: {
              instanceType: "t2.small.elasticsearch",
          },
          elasticsearchVersion: "6.3",
          snapshotOptions: {
              automatedSnapshotStartHour: 23,
          },
          ebsOptions: {
            ebsEnabled: true,
            volumeType: "gp2",
            volumeSize: 10,  // GB
          },
          tags: {
              Domain: `${name}-${ENV_LOWER}`,
          },
          vpcOptions: {
              securityGroupIds: [esSecurityGroup.id],
              subnetIds: [subnetId]
          }
      },
      {
        dependsOn: [esServiceLinkedRole]
      });
```

**Comment by leezen** [comment]
Do future deployments attempt to create a new service linked role? Given that it's already defined in this stack, it shouldn't attempt to create a new role. Or do you mean subsequent deployments of this project in a different stack result in the error?

Assuming the latter, you could attempt to first check for the role. For example:
```
export = async () => {
    try {
        const role = await aws.iam.getRole({
            name: "AWSServiceRoleForAmazonElasticsearchService",
        });
    } catch {
        // create role since it doesn't exist
    }
    // continue with the rest of your code now that you either have the role of have created one
}
```

**Comment by manymikes** [comment]
@leezen appreciate the quick response.

That was my assumption as well but subsequent deployments are attempting to recreate role, even within the same stack (which goes against TFs model).

I could use your role check logic but it will require a refactor of my `ComponentResource` so I was trying to avoid using the async syntax if possible.

Unless I am misunderstanding something. In general it seems like the `aws.elasticsearch.Domain` module functions different than most. Other modules such as `aws.rds.Instance` seems to handle all of the `ServiceLinkedRoled` logic internally.

**Comment by leezen** [comment]
Is `${name}` or `${ENV_LOWER}` somehow changing within the same stack? Otherwise, you shouldn't see a create/delete within the same stack.

**Comment by manymikes** [comment]
Same stack, same variables, the only variability is that the deployment (`pulumi up`) happens both locally (on my local dev box) and in CI/CD but both environments are deploying the same stack with the same env. I know they are the same as all of the environment variables are coming from an encrypted environment file (using Jet from Codeship), I have also echo'd all variables prior to deployment.

**Comment by leezen** [comment]
Could you please provide the detailed diff? That'd be helpful in understanding why there's a create happening.

**Comment by manymikes** [comment]
I've discovered the issue. It turns out my deployment script was getting passed an older Pulumi Access Token from a different account so the state was getting split between different accounts. I didn't recognize it prior because the Pulumi token was one of the only ENV vars I wasn't printing out.

@leezen thanks for taking the time to help troubleshoot.
