### ISSUE TITLE
Inconsistent import behavior with `aws.ecs.Cluster`

### ISSUE THREAD

**Issue by gibsonjoshua55** [pulumi/pulumi-aws#962]
When importing an existing cluster from my infrastructure,  the only way to successfully do so has been using the name as the import key.  For example if I have a cluster called `MyCluster` the construction of the cluster would look like this:
```
const existingCluster = new aws.ecs.Cluster(
            'pulumi-resource-name',
            {
                name: 'MyCluster'
            },
            {
                import: 'MyCluster',
                parent: this,
                protect: true
            }
        );
```

I am then putting this cluster in a crosswalk Cluster.

However, every time after importing the cluster this way, Pulumi tries to replace the cluster when a service is added to it.  To fix this (after creating the stack), I changed the import key to be `import: arnForMyCluster`. Now when I got to deploy a new stack, that import statement is failing with the message.

```
Preview failed: refreshing urn:pulumi:staging::loop-lxp::loop-lxp:ecs:cluster$aws:ecs/cluster:Cluster::loop-lxp-cluster-existing-resource: error reading ECS Cluster (arn:aws:ecs:us-east-1:**account_id**:cluster/arn:aws:ecs:us-east-1:**account_id**::cluster/Loop): InvalidParameterException: Unsupported resource type: cluster
```

In opening this issue, I ultimately have two questions.

1. What is the correct way to import a cluster? Is it with the cluster name or its arn?
2. If it is with the cluster name, how can I keep that import statement with the cluster name consistent so new stack can be made, but not have pulumi try to recreate the cluster on every service change.  I understand that might be a better issue to open up in crosswalk, but considering that its the non crosswalk import that is failing and being replaced, I figured I would start here.

Thanks for your assistance!

Package/runtime versions:
```
"node": 12.8.1,
"@pulumi/aws": "^2.0.0",
"@pulumi/awsx": "^0.20.0",
"@pulumi/pulumi": "^2.0.0",
"aws-sdk": "^2.667.0",
"typescript": "3.8.3"
```

**Comment by leezen** [comment]
> What is the correct way to import a cluster? Is it with the cluster name or its arn?

Yes, it's the name.

> If it is with the cluster name, how can I keep that import statement with the cluster name consistent so new stack can be made, but not have pulumi try to recreate the cluster on every service change. I understand that might be a better issue to open up in crosswalk, but considering that its the non crosswalk import that is failing and being replaced, I figured I would start here.

After you've imported the resource, you should be able to delete the `import` -- does it still attempt to create a new cluster with a service change after that?

**Comment by gibsonjoshua55** [comment]
Maybe I'm misunderstanding stacks, but I don't think I can get rid of the import. For example, the first stack I made was `development`, which needed to import in that resource. That exists now so maybe I could get rid of the import line. The next stack I want to make is for `staging`. If I don't keep the import statements, it is going to instead create a new cluster when that import statement is removed.

As a test, I just removed the import and did a preview on the new stack for `staging` and this was my output.

```
+  aws:ecs/cluster:Cluster (create)
    [urn=urn:pulumi:staging::loop-lxp::loop-lxp:ecs:cluster$aws:ecs/cluster:Cluster::loop-lxp-cluster-existing-resource]
    __defaults: []
    name      : "Loop"
```
I believe that because this is a new stack and has a new `urn` those resources still need to be imported the first time they are ran.  I guess I could add a flag or something to see if my stack is being ran for the first time and not attach those imports, but so far cluster is the only resource where this is a problem.  It's also not really possible to get in there and remove the code for just those first runs on a new stack because the same code is ran automatically on commits for various stacks.  I can't remove or add the imports for just one stack necessarily.

Now I have seen some writing around having a stack of shared resources between stacks. I could see that working here, except for the fact that I'm not sure how those outputs would work with crosswalk.  It seems like if I want to continue to use crosswalk (which maybe isn't the right choice considering my existing structure), I would still have to import resources from the shared stack, which would seem to cause the same issues I am having now.

Overall, though, my biggest concern is that the cluster is the only resource where I have this problem.  All other resources are imported, keep their import key, and are not attempted to be recreated by Pulumi, but when I add a new service using crosswalk, the cluster tries to get replaced and fails because it is protected. There seems to be something unique about the cluster compared to the other resources.

**Comment by leezen** [comment]
When you import a resource, it implies you want to manage that resource from within that stack. It sounds like you actually want to use `get` here: https://www.pulumi.com/docs/reference/pkg/aws/ecs/getcluster/

This way, the cluster is not adopted into the stack

**Comment by gibsonjoshua55** [comment]
Ah, that makes sense. Is there a way to pass that in to Crosswalk? I imagine probably not, and probably the also that we should not be using crosswalk if we don't want the pulumi stack to manage our resources.

Thanks for the help!

**Comment by gunar** [comment]
You can import an existing ECS Cluster into Crosswalk:

```ts
const cluster = new awsx.ecs.Cluster("cluster", {
  cluster: networking.getOutput("clusterName"),
});
```

Here's the full snippet:
```ts
// networking/index.ts
export const clusterName = cluster.cluster.name;

// application/index.ts
const env = pulumi.getStack();
const networking = new pulumi.StackReference(`…/networking/${env}`);
const cluster = new awsx.ecs.Cluster("cluster", {
  cluster: networking.getOutput("clusterName"),
});
```

**Comment by lukehoban** [comment]
I believe the questions raised here have been addressed.  We also now support `pulumi import` which can be used in these cases.  If there area any issues you are still seeing, please do open a new issue.
