### ISSUE TITLE
Support autonaming of SQS fifo queues

### ISSUE THREAD

**Issue by rofr** [pulumi/pulumi-aws#967]
SQS FIFO queue names must have a ".fifo" suffix. This does not play well will auto-naming because the random hex will be tacked on at the end yielding an invalid name. I suggest that the ".fifo" suffix should be added by pulumi when autonaming a fifo queue.

Here is some example C# code:

```csharp

    // fails on AWS because name must end with .fifo
    var q1 = new Queue("myqueue", new QueueArgs {
        FifoQueue = true
    });

    //fails in pulumi with the message:
    //only alphanumeric characters and hyphens allowed in "name"
    var q2 = new Queue("myqueue.fifo", new QueueArgs {
        FifoQueue = true
   });

   //explicitly assigning a name works but does not use autonaming 
   var q3 = new Queue("myqueue" new QueueArgs {
        FifoQueue = true,
        Name = "myqueue.fifo"
    });
```

**Comment by clstokes** [comment]
Related:
- https://github.com/pulumi/docs/issues/3083
- https://github.com/pulumi/pulumi/issues/4371

**Comment by clstokes** [comment]
This appears to have regressed. Full repro at https://gist.github.com/c3f571b0af3b891b3b8283cbf58ecb9c.

```ts
import * as aws from "@pulumi/aws";

// FAILS - name becomes `main-abc123` - Error validating the FIFO queue name: [FIFO queue name should end with ".fifo": main-4d1963b]
const main = new aws.sqs.Queue("main", {
    fifoQueue: true,
});

// FAILS - name becomes `main.fifo-abc123` - resource 'main.fifo' has a problem: only alphanumeric characters and hyphens allowed in "name"
const mainFifo = new aws.sqs.Queue("main.fifo", {
    fifoQueue: true,
});

// SUCCEEDS - name stays `main.fifo`
const mainFifoName = new aws.sqs.Queue("main", {
    name: "main.fifo",
    fifoQueue: true,
});
```

```
p-ts-aws-sqs-fifo@ /Users/clstokes/cc/customers/mbo/p-ts-aws-sqs-fifo
├── @pulumi/aws@3.32.1
├── @pulumi/awsx@0.24.0
├── @pulumi/pulumi@2.22.0
└── @types/node@10.17.55

p-ts-aws-sqs-fifo % pulumi version
v2.22.0
```

**Comment by leezen** [comment]
@stack72 The property in the PR that fixes this is `fifo` but the underlying property seems like it should be `fifo_queue`? Am I missing something?

**Comment by stack72** [comment]
@leezen great question - this actually uses our property bag that gets translated from the TF provider - I think this regressed around the time we changed to use v2 of the plugin sdk as the properties changed around

Regardless, it was a lift and shift of a PR that Luke created that actually worked originally

PR is open - it's been approved and tests have been added to ensure we don't regress again!

I will publish a patch as soon as this goes green
