### ISSUE TITLE
SSM not reading aws provider

### ISSUE THREAD

**Issue by alexistimic** [pulumi/pulumi-aws#969]
When iterating through regions, ssm will not take into account its provider and will always read the one set in the environment `~/.aws/config`.

ie:
```
$ pulumi version
v2.1.1
```
**`~/.aws/config: `**
```
[profile us-west-2]
...
region = us-west-2
...
```

**`index.ts: `**
```
const provider = new aws.Provider("provider-test-eu-west-1", { region: "eu-west-1" });
let imageId = aws.ssm.getParameter({
  name: "foo"
}).value;
console.log("test imageId : " + imageId)
```
Will read the value `foo` from us-west-2 and not the one from eu-west-1

**Comment by stack72** [comment]
Hi @alexistimic 

You are setting up a provider, but you are not actually using it in this resource. the resource is using the default provider. To ensure that you are using the correct provider, you can do something like the following:

```
const provider = new aws.Provider("provider-test-eu-west-1", { region: "eu-west-1" });
let imageId = aws.ssm.getParameter({
  name: "foo"
}, {
	provider
}).value;
````

**Comment by alexistimic** [comment]
Hi @stack72,

Thanks for the quick answer :+1:

When I set the provider in the ssm resource, I am running in a stale preview/deployment with this error: `For more details see: https://www.pulumi.com/docs/troubleshooting/#synchronous-call`

Seems to me that the resource is already set to use the specified provider and I am trying to override it.

WDYT ?

**Comment by stack72** [comment]
@alexistimic 

try this out (since you are on > Pulumi 2.0)

```
const provider = new aws.Provider("provider-test-eu-west-1", { region: "eu-west-1" });

let imageId = pulumi.ouput(aws.ssm.getParameter({
  name: "foo"
}, {
	provider
})).value;
```

**Comment by alexistimic** [comment]
@stack72,

That seems to have done the trick.
Thanks a lot :)
