### ISSUE TITLE
Step Functions - "Express" type

### ISSUE THREAD

**Issue by dror-g** [pulumi/pulumi-aws#982]
Would be nice to have a way to create "Express" type state machines.
I don't think it's implemented in Terraform though.

**Comment by leezen** [comment]
Correct, this appears to be tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/11348

**Comment by jaxxstorm** [comment]
Looks like this will get released in 3.27.0 of the provider in https://github.com/hashicorp/terraform-provider-aws/pull/12249
