### ISSUE TITLE
Latest update broke autoscaling groups with tags set

### ISSUE THREAD

**Issue by solidDoWant** [pulumi/pulumi-aws#990]
Due to this PR in the terraform provider (https://github.com/terraform-providers/terraform-provider-aws/pull/13515), autoscaling groups with tags set will fail due to the type change on line 83 (https://github.com/terraform-providers/terraform-provider-aws/pull/13515/files#diff-153d061c5aa12e0ddd425ff2728eb0bfL83) and 88 (https://github.com/terraform-providers/terraform-provider-aws/pull/13515/files#diff-153d061c5aa12e0ddd425ff2728eb0bfL88). It looks like the documentation was updated from "list" to "set" in all the SDK documentation but the underlying type was not updated.

Minimum code to reproduce (python)
```
from pulumi_aws import autoscaling, ec2, get_availability_zones, get_ami

ami = get_ami(
    most_recent=True,
    owners=[
        "amazon"
    ],
    filters=[
        {
            "name": "name",
            "values": ["amzn-ami-hvm-2018.03.0.20180811-x86_64-gp2"]
        }
    ]
)

launch_template = ec2.LaunchTemplate(
    "launch-template",
    instance_type="t3.medium",
    image_id=ami.id
)

autoscaling.Group(
    "as-group",
    max_size=1,
    min_size=1,
    launch_template={
        "id": launch_template.id,
        "version": launch_template.latest_version
    },
    availability_zones=get_availability_zones().names,
    tags_collection=[    # This is the important part
        {
            "key": "example",
            "value": "value",
            "propagate_at_launch": True
        }
    ]
)
```

Not sure if the root issue is here or the terraform bridge.

**Comment by loopingz** [comment]
It started with version `2.7.0` and it still open.
To work around you can enforce the aws version to 2.6.1
`new aws.Provider(`provider-${region}`, { region: <any>region }, { version: "2.6.1" });`
