### ISSUE TITLE
Continuous replace of EC2 instance if root EBS volume is encrypted

### ISSUE THREAD

**Issue by hseagle2015** [pulumi/pulumi-aws#999]
I'm experiencing strange behavior with Pulumi 2.3.0. I'm using Python SDK and when I provision EC2 instance with an encrypted root EBS volume (with default, AWS-managed KMS key), Pulumi is replacing the EC2 instance every time I run `pulumi up`.

Obviously, I'd like to avoid such behavior :smile: 

The problem can be reproduced with the following Python code:

```python
import pulumi
import pulumi_aws as aws

amzn_ami = aws.get_ami(most_recent="true",
                  owners=["137112412989"],
                  filters=[{"name":"name","values":["amzn-ami-hvm-*"]}])


# Get ARN for default, AWS-managed EBS KMS key
default_kms_key = aws.kms.get_alias(name="alias/aws/ebs")

# Set default EBS volume settings
root_ebs= { "deleteOnTermination": True,
            "volume_size": 10,
            "volumeType": "gp2",
            "encrypted": True,
            "kms_key_id": default_kms_key.arn
          }

# Provision test EC2 instance
ec2_instance = aws.ec2.Instance(
                                "TestEC2Instance",
                                instance_type='t3.micro',
                                ami=amzn_ami.id,
                                root_block_device=root_ebs,
                               )
```

Here are the results of initial `pulumi up` and another one right after the first one.

```
$ pulumi up

Previewing update (myproject-dev):
     Type                 Name                     Plan       
 +   pulumi:pulumi:Stack  myproject-myproject-dev  create     
 +   └─ aws:ec2:Instance  TestEC2Instance          create     
 
Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (myproject-dev):
     Type                 Name                     Status      
 +   pulumi:pulumi:Stack  myproject-myproject-dev  created     
 +   └─ aws:ec2:Instance  TestEC2Instance          created     
 
Resources:
    + 2 created

Duration: 30s



$ pulumi up

Previewing update (myproject-dev):
     Type                 Name                     Plan        Info
     pulumi:pulumi:Stack  myproject-myproject-dev              
 +-  └─ aws:ec2:Instance  TestEC2Instance          replace     [diff: ~rootBlockDevice]
 
Resources:
    +-1 to replace
    1 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:myproject-dev::myproject::pulumi:pulumi:Stack::myproject-myproject-dev]
    ++aws:ec2/instance:Instance: (create-replacement)
        [id=i-0b5c5ef331fe87c2f]
        [urn=urn:pulumi:myproject-dev::myproject::aws:ec2/instance:Instance::TestEC2Instance]
        [provider=urn:pulumi:myproject-dev::myproject::pulumi:providers:aws::default_2_8_0::aeeb6a03-5959-4d27-b5f0-aa65aafbd9f0]
      ~ rootBlockDevice: {
          ~ kmsKeyId: "arn:aws:kms:eu-north-1:123123123123:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" => "arn:aws:kms:eu-north-1:123123123123:alias/aws/ebs"
        }
    +-aws:ec2/instance:Instance: (replace)
        [id=i-0b5c5ef331fe87c2f]
        [urn=urn:pulumi:myproject-dev::myproject::aws:ec2/instance:Instance::TestEC2Instance]
        [provider=urn:pulumi:myproject-dev::myproject::pulumi:providers:aws::default_2_8_0::aeeb6a03-5959-4d27-b5f0-aa65aafbd9f0]
      ~ rootBlockDevice: {
          ~ kmsKeyId: "arn:aws:kms:eu-north-1:123123123123:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" => "arn:aws:kms:eu-north-1:123123123123:alias/aws/ebs"
        }
    --aws:ec2/instance:Instance: (delete-replaced)
        [id=i-0b5c5ef331fe87c2f]
        [urn=urn:pulumi:myproject-dev::myproject::aws:ec2/instance:Instance::TestEC2Instance]
        [provider=urn:pulumi:myproject-dev::myproject::pulumi:providers:aws::default_2_8_0::aeeb6a03-5959-4d27-b5f0-aa65aafbd9f0]
```

The problem is not present if EBS encryption is disabled (i.e. if keys `encrypted` and `mks_key_id` are removed from the `root_ebs` dictionary). With EBS encryption disabled, Pulumi correctly recognizes the actual state of both EC2 instance and its root EBS volume and doesn't try to replace anything.

I stumbled upon a similar issue #605, but I'm not sure if it's the same kind of problem, since there additional/attached EBS volumes are mentioned as well.

**Comment by stack72** [comment]
Hi @hseagle2015 

Just checking back on this to see if you have managed to test this resolution?

Thanks

Paul

**Comment by hseagle2015** [comment]
> Hi @hseagle2015
> 
> Just checking back on this to see if you have managed to test this resolution?
> 
> Thanks
> 
> Paul

Hi @stack72,

I'm sorry, vacation got in the way :smile: 
I'll be able to test suggested solution on Monday and I'll get back to you guys with the feedback.

**Comment by stack72** [comment]
Thanks so much :)

**Comment by johnbairmbo** [comment]
I ran into this same issue and just solved it.  The issue for me was doing the volumes together.  

ebsBlockDevices: [{deviceName: '/dev/xvda'
encrypted: true
},{deviceName: '/dev/sdb',
   volumeSize: 300,
   volumeType: 'gp2',
   encrypted: true
}],

That would cause the rebuild everytime.  Volumes were encrypted so I assumed...... :)

rootBlockDevice: { encrypted: true },
ebsBlockDevices: [{
  deviceName: '/dev/sdb',
  volumeSize: 300,
  volumeType: 'gp2',
  encrypted: true
}],

This one works 100% no rebuild and all is encrypted without issue.

**Comment by hseagle2015** [comment]
> It looks like this is happening b/c as the diff points out, the alias is getting resolved to the actual ARN. Then, it shows a diff since the input is the alias (instead of the actual ARN). While ideally this would 'work' it's also not clear this can be 'known' that the key id isn't changing under the hood (the alias could be pointing to something else after all).
> 
> I believe if you change `"kms_key_id": default_kms_key.arn` (which specifies the alias's ARN) to `"kms_key_id": default_kms_key.target_key_arn` then this diff should go away.

@leezen  @stack72 thank you for your help. I made the suggested correction to my Pulumi program and managed to resolve the issue.

Much appreciated!
